### ISSUE TITLE
2015-12-28 12:10:47.233:WARN:oejs.ServletHandler:/druid/wall.json java.lang.IllegalArgumentException: class [J and class [J not supported.

### ISSUE THREAD

**Issue by zhenzhenwudi** [alibaba/druid#1016]
at com.alibaba.druid.sql.visitor.SQLEvalVisitorUtils.add(SQLEvalVisitorUtils.java:1830)
	at com.alibaba.druid.stat.DruidStatManagerFacade.mergWallStat(DruidStatManagerFacade.java:258)
	at com.alibaba.druid.stat.DruidStatManagerFacade.mergeNamedList(DruidStatManagerFacade.java:282)
	at com.alibaba.druid.stat.DruidStatManagerFacade.mergWallStat(DruidStatManagerFacade.java:253)
	at com.alibaba.druid.stat.DruidStatManagerFacade.getWallStatMap(DruidStatManagerFacade.java:179)
	at com.alibaba.druid.stat.DruidStatService.getWallStatMap(DruidStatService.java:285)
	at com.alibaba.druid.stat.DruidStatService.service(DruidStatService.java:131)
	at com.alibaba.druid.support.http.StatViewServlet.process(StatViewServlet.java:162)
	at com.alibaba.druid.support.http.ResourceServlet.service(ResourceServlet.java:248)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:565)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1360)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:83)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
	at net.core.filter.WebContextFilter.doFilter(WebContextFilter.java:28)

求解决办法，着急中

**Comment by qq291462491** [comment]
+1  遇到同样问题，版本：1.0.18

**Comment by cnzzr** [comment]
关注一下，tomcat6、Server 2008环境

**Comment by ankeway** [comment]
1.0.19在使用sql防火墙的时候也会出现这种现象，是不是哪配置的不对呢？

**Comment by xupengggggg** [comment]
这个问题还没解决吗，看了好多个版本，都还是这样，有个值的类型是long,在判断逻辑里只有包装类型Long,直接跑到异常里，会是这个问题吗？
