### ISSUE TITLE
defaultAutoCommit : false 引发异常

### ISSUE THREAD

**Issue by javanan** [alibaba/druid#1056]
当程序运行的时候，数据库如果隔一段时间不去请求，，再去请求的时候出现了错误！

2016-01-20 15:21:55,657 [Druid-ConnectionPool-Destroy-1741624376] DEBUG com.alibaba.druid.util.JdbcUtils - close connection error
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown.
 at sun.reflect.GeneratedConstructorAccessor239.newInstance(Unknown Source)
 at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
 at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
 at com.mysql.jdbc.Util.getInstance(Util.java:386)
 at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015)
 at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:989)
 at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:975)
 at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:920)
 at com.mysql.jdbc.ConnectionImpl.rollback(ConnectionImpl.java:5062)
 at com.mysql.jdbc.ConnectionImpl.realClose(ConnectionImpl.java:4654)
 at com.mysql.jdbc.ConnectionImpl.close(ConnectionImpl.java:1630)
 at com.alibaba.druid.filter.FilterChainImpl.connection_close(FilterChainImpl.java:169)
 at com.alibaba.druid.filter.stat.StatFilter.connection_close(StatFilter.java:254)
 at com.alibaba.druid.filter.FilterChainImpl.connection_close(FilterChainImpl.java:165)
 at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.close(ConnectionProxyImpl.java:115)
 at com.alibaba.druid.util.JdbcUtils.close(JdbcUtils.java:83)
 at com.alibaba.druid.pool.DruidDataSource.shrink(DruidDataSource.java:2152)
 at com.alibaba.druid.pool.DruidDataSource$DestroyTask.run(DruidDataSource.java:1964)
 at com.alibaba.druid.pool.DruidDataSource$DestroyConnectionThread.run(DruidDataSource.java:1951)

**Comment by dachuanz** [comment]
那个版本？

**Comment by javanan** [comment]
数据库mysql  
SELECT @@version;
5.5.40

druid
druid-1.0.15.jar

**Comment by halober** [comment]
我mysql 5.6.35也出现了这个问题

**Comment by zongxingy** [comment]
1.1.9也会出现这个问题，请问有解决方法吗？

**Comment by zhuojl** [comment]
版本：1.0.27
我们系统的情况是：服务器改了wait_timeout，而程序中的timeBetweenEvictionRunsMillis 和 minEvictableIdleTimeMillis 都没有相应的改低，所以当程序检测到链接失效进行关闭时，报了链接异常，本来这个异常日志是debug，而系统中的日志级别就是debug，所以有这样的日志，其实只要调高级别就行了？

**Comment by comeonhero** [comment]
有人找到原因吗？一样的情况
druid  1.1.21
mysql 5.1.26
1.defaultAutoCommit : false 引发异常
2.数据库如果隔一段时间不去请求，，再去请求的时候出现了错误！

**Comment by lizongbo** [comment]
升级druid和mysql jdbc到最新版再验证
