### ISSUE TITLE
druid-1.0.9  执行 CREATE DATABASE `testRep` CHARACTER SET utf8 COLLATE utf8_general_ci 异常

### ISSUE THREAD

**Issue by zhuam** [alibaba/druid#1061]
java.sql.SQLException: sql injection violation, syntax error: syntax error, error in :'Rep` CHARACTER SET utf8 COLLATE utf',expect IDENTIFIER, actual IDENTIFIER CHARACTER : CREATE DATABASE `testRep` CHARACTER SET utf8 COLLATE utf8_general_ci
	at com.alibaba.druid.wall.WallFilter.check(WallFilter.java:711)
	at com.alibaba.druid.wall.WallFilter.connection_prepareStatement(WallFilter.java:240)
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:448)
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.prepareStatement(ConnectionProxyImpl.java:342)
	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:318)
	at com.feeyo.dbsync.entry.consumer.MysqlConsumer.comsume(MysqlConsumer.java:71)
	at com.feeyo.dbsync.MysqlBinlogEventTransfer.flush(MysqlBinlogEventTransfer.java:111)
	at com.feeyo.dbsync.entry.EntryTransactionBuffer.flush(EntryTransactionBuffer.java:120)
	at com.feeyo.dbsync.entry.EntryTransactionBuffer.add(EntryTransactionBuffer.java:70)
	at com.feeyo.dbsync.MysqlBinlogEventTransfer.run(MysqlBinlogEventTransfer.java:100)
Caused by: com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'Rep` CHARACTER SET utf8 COLLATE utf',expect IDENTIFIER, actual IDENTIFIER CHARACTER
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:210)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:307)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:112)
	at com.alibaba.druid.wall.WallProvider.checkInternal(WallProvider.java:619)
	at com.alibaba.druid.wall.WallProvider.check(WallProvider.java:574)
	at com.alibaba.druid.wall.WallFilter.check(WallFilter.java:699)
	... 9 more

**Comment by wenshao** [comment]
升级到druid-1.0.16看看

**Comment by wenshao** [comment]
已经修正，等待1.0.17版本吧

**Comment by zhuam** [comment]
OK THNAKS
