### ISSUE TITLE
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: syntax error, expect RPAREN, actual IDENTIFIER RETENTION

### ISSUE THREAD

**Issue by wood001** [alibaba/druid#1134]
解析Oracle建表语句的lob存储参数的时候报错，缺少对一致读参数（基于时间的版本保留retention和基于空间的版本保留pctversion）的解析。
例如LOB ("CL") STORE AS (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 **PCTVERSION 10**
  NOCACHE LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;

`
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: syntax error, expect RPAREN, actual IDENTIFIER RETENTION
    at com.alibaba.druid.sql.parser.SQLExprParser.accept(SQLExprParser.java:1590)
    at com.alibaba.druid.sql.dialect.oracle.parser.OracleExprParser.parseLobStorage(OracleExprParser.java:1194)
    at com.alibaba.druid.sql.dialect.oracle.parser.OracleCreateTableParser.parseCrateTable(OracleCreateTableParser.java:123)
    at com.alibaba.druid.sql.dialect.oracle.parser.OracleCreateTableParser.parseCrateTable(OracleCreateTableParser.java:41)
    at com.alibaba.druid.sql.parser.SQLStatementParser.parseCreate(SQLStatementParser.java:1589)
    at com.alibaba.druid.sql.dialect.oracle.parser.OracleStatementParser.parseStatementList(OracleStatementParser.java:173)
    at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:1956)
`

**Comment by wenshao** [comment]
能把完成SQL贴出来么，这样我好做回归测试

**Comment by wood001** [comment]
CREATE TABLE "TEST" 
   (	"NAMESPACE" VARCHAR2(100) NOT NULL ENABLE, 
	"RULESET_ID" VARCHAR2(32) NOT NULL ENABLE, 
	"DATA" CLOB NOT NULL ENABLE, 
	"FILENAME" VARCHAR2(100), 
	 CONSTRAINT "PK_T_RULES_REPOSITORY" PRIMARY KEY ("NAMESPACE", "RULESET_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "TBS_BPM_IDX"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TBS_BPM_DAT" 
 LOB ("DATA") STORE AS BASICFILE (
  TABLESPACE "TBS_BPM_DAT" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;

**Comment by lizongbo** [comment]
最新master代码解析不抛异常了
