### ISSUE TITLE
Druid不支持解析merge语句吗

### ISSUE THREAD

**Issue by zhuangmofei** [alibaba/druid#1147]
2016-03-28 10:34:47,131 Timer-0 ERROR (StatFilter.java:147) - merge sql error, dbType oracle, sql : 
merge into (select * from T09_RULE_CAL_COUNT  where data_dt = '20160328' and rule_type = '2') t using (select cust_no,organ_key from (select t1.cust_no, t1.organ_key from t08_cust_result_c_mid t1 union (select t2.cust_no, t2.organ_key from t08_cust_result_i_mid t2))) t3 on(t3.cust_no =t.cust_no) when matched then update set t.organ_key=t3.organ_key
com.alibaba.druid.sql.parser.ParserException: error LPAREN
	at com.alibaba.druid.sql.parser.SQLExprParser.name(SQLExprParser.java:813)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleExprParser.name(OracleExprParser.java:985)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleStatementParser.parseMerge(OracleStatementParser.java:1133)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleStatementParser.parseStatementList(OracleStatementParser.java:212)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:112)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:107)
	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:54)
	at com.alibaba.druid.filter.stat.StatFilter.mergeSql(StatFilter.java:145)
	at com.alibaba.druid.filter.stat.StatFilter.createSqlStat(StatFilter.java:629)
at com.alibaba.druid.filter.stat.StatFilter.statementPrepareAfter(StatFilter.java:305)
	at com.alibaba.druid.filter.FilterEventAdapter.connection_prepareStatement(FilterEventAdapter.java:124)
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:448)
	at com.alibaba.druid.filter.FilterAdapter.connection_prepareStatement(FilterAdapter.java:928)
	at com.alibaba.druid.filter.FilterEventAdapter.connection_prepareStatement(FilterEventAdapter.java:122)
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:448)
	at com.alibaba.druid.filter.FilterAdapter.connection_prepareStatement(FilterAdapter.java:928)
	at com.alibaba.druid.filter.FilterEventAdapter.connection_prepareStatement(FilterEventAdapter.java:122)
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:448)
	at com.alibaba.druid.filter.FilterAdapter.connection_prepareStatement(FilterAdapter.java:928)
	at com.alibaba.druid.filter.FilterEventAdapter.connection_prepareStatement(FilterEventAdapter.java:122)
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:448)
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.prepareStatement(ConnectionProxyImpl.java:342)
	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:318)
	at com.resoft.aml.server.db.SQLExecute.exeSql(SQLExecute.java:296)
at com.resoft.aml.server.db.SQLExecute.exeSql(SQLExecute.java:277)
	at com.resoft.aml.server.db.SQLExecute.exeSql(SQLExecute.java:264)
	at com.resoft.risk.server.cal.rule.score.ComputeRiskRuleCal.mergeIntoT09RuleCalCount(ComputeRiskRuleCal.java:1303)
	at com.resoft.risk.server.cal.rule.score.ComputeRiskRuleCal.runInsert(ComputeRiskRuleCal.java:329)
	at com.resoft.aml.server.cal.task.CompRiskRuleCal.runInsert(CompRiskRuleCal.java:30)
	at com.resoft.aml.server.cal.BaseTask.insertResult(BaseTask.java:73)
	at com.resoft.aml.server.cal.BaseTask.executeTask(BaseTask.java:48)
	at com.resoft.aml.server.cal.BaseServer.calTask(BaseServer.java:309)
	at com.resoft.aml.server.AMLTaskServer.executeTasks(AMLTaskServer.java:81)
	at com.resoft.aml.server.AMLTaskServer.access$0(AMLTaskServer.java:61)
	at com.resoft.aml.server.AMLTaskServer$1.run(AMLTaskServer.java:49)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)

**Comment by wenshao** [comment]
支持的，你这个是版本不对吧，升级到1.0.18之后的版本应该就好了

**Comment by zhuangmofei** [comment]
我更新了1.0.18，然后也测试了一下，针对简单的merge语句是没有问题的，可能是上面的那个SQL写的不够简洁。。。。。。不过这个应该可以算是一个可以优化的地方吧

**Comment by wenshao** [comment]
已经修复，等待druid-1.0.19版本吧
