### ISSUE TITLE
线程卡死在druiddatasource上

### ISSUE THREAD

**Issue by zcwease** [alibaba/druid#1160]
"pool-1-thread-2" prio=10 tid=0x0000000000e1b000 nid=0x3130 waiting on condition [0x00002b39e47cc000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x0000000780199268> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
        at com.alibaba.druid.pool.DruidDataSource.takeLast(DruidDataSource.java:1448)
        at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1090)
        at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:960)
        at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4544)
        at com.alibaba.druid.filter.logging.LogFilter.dataSource_getConnection(LogFilter.java:831)
        at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4540)
        at com.alibaba.druid.filter.stat.StatFilter.dataSource_getConnection(StatFilter.java:662)
        at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4540)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:938)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:930)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:102)

发现多个线程卡死在获取连接上，而且是长时间卡在这里（偶现），想问下具体什么原因

**Comment by zcwease** [comment]
版本是1.0.16

**Comment by lixin0120** [comment]
朋友你的问题解决了吗？我也遇到同样的问题，偶尔获得连接需要很长的时间

**Comment by yangzhijie1488** [comment]
您好，我没有获取连接需要很长时间的问题。

 

获取连接需要很长时间说明连接池的连接已经用完了。应该是程序出现了BUG，数据库的链接打开以后没有关闭。

 

你看一下当前线程池有哪些活动的线程，然后就可以找到在什么地方打开了数据库的链接，然后检查数据库的连接有没有关闭，这样就解决问题了。

 

发件人: noreply@github.com [mailto:noreply@github.com] 代表 lixin0120
发送时间: 2016年4月8日 16:23
收件人: alibaba/druid <druid@noreply.github.com>
主题: Re: [alibaba/druid] 线程卡死在druiddatasource上 (#1160)

 

朋友你的问题解决了吗？我也遇到同样的问题，偶尔获得连接需要很长的时间

**Comment by wenshao** [comment]
链接忘记关闭了吧

**Comment by loveczp** [comment]
我这边也遇到了类似的问题，java thread   stack 里面全是等待连接的线程。
看附件
[stack.txt](https://github.com/alibaba/druid/files/276253/stack.txt)

**Comment by lizhi2013** [comment]
我这边也碰到类似的问题，比如我的一个页面访问了18次，连接大概，开开关关了36次，然后就不能再连接了，换成c3p0又ok了，不像是连接未关闭的问题

**Comment by NinthCode** [comment]
我现在也遇到了这个问题，版本是1.0.9,，有人知道怎么解决吗。。。。。。。

**Comment by manzhizhen** [comment]
我们使用1.0.8的版本也遇到过同样的问题，重启应用才搞定

**Comment by NinthCode** [comment]
@manzhizhen 重启应用后确实会好，但是过段时间还会出现同样的问题。

**Comment by VEMTK** [comment]
有人解决了吗？

**Comment by chenhn** [comment]
我也遇到同样的问题，尝试将 maxActive 值 调大

**Comment by zhmz1326** [comment]
我这边一开始用 Spring boot集成druid 1.0.15，一个连接都连上不。
后来将druid版本升为1.1.12，就能获取到连接了。

**Comment by rickyman** [comment]
druid默认的maxActive=8  ; 如果并发数大于20 的时候就会出现大量的处于WAITING和 TIMED_WATING 状态的线程。
因此建议增加3个参数：
   <property name="removeAbandoned" value="true" />
        <property name="removeAbandonedTimeout" value="1800" />
        <property name="maxActive" value="1000" /> ---根据自己应用需要，合适调整大小

**Comment by oawang** [comment]
mark me too

**Comment by sdisk** [comment]
我使用druid-spring-boot-starter 1.1.10版本也出现了多个连接等待？ java.lang.Thread.State: WAITING (parking)，大家在测试环境是怎么重现这个问题的呢？

**Comment by wangpo1991** [comment]
都2020年了，我今天也遇到了这个问题，线程都挂起了，不再写入数据库，定位也是这坨代码

**Comment by wangpo1991** [comment]
> 我使用druid-spring-boot-starter 1.1.10版本也出现了多个连接等待？ java.lang.Thread.State: WAITING (parking)，大家在测试环境是怎么重现这个问题的呢？

多个线程并发写入，大量的写入

**Comment by zggg** [comment]
> > 我使用druid-spring-boot-starter 1.1.10版本也出现了多个连接等待？ java.lang.Thread.State: WAITING (parking)，大家在测试环境是怎么重现这个问题的呢？
> 
> 多个线程并发写入，大量的写入

有结论么

**Comment by greatwqs** [comment]
没有结论, 我们是在高并发时出的问题. 
tomcat http线程池200个线程全部挂在这个地方, 外部请求全部进不来.

**Comment by zyx870805** [comment]
遇到同样的问题， 重启应用好了

**Comment by vinartis** [comment]
多管齐下，首先这个问题是因为连接池被耗尽了，并且被一直占用没有释放，那么解决思路也就有了
1 druid本身提供了持有连接超时的配置选项，这个可以配置起来，但不建议配置，大部分情况一个事务执行的时间要尽量短
**2 增加应用的最大连接数配置
3 解决应用中的长事务。**

**Comment by skymilong** [comment]
前几天也出现了一样的问题。还是这默认配置的问题，并发下就会出现。配置超时时间就好了。这样会走pollLast而不是takeLast

**Comment by hasayaki** [comment]
去掉连接池maxWait配置，或者手动指定使用非公平锁：dataSouce.setUseUnfairLock(true)。
refer：https://github.com/alibaba/druid/wiki/Druid%E9%94%81%E7%9A%84%E5%85%AC%E5%B9%B3%E6%A8%A1%E5%BC%8F%E9%97%AE%E9%A2%98

**Comment by lifaxin** [comment]
1.1.20 版本完美复现这个问题

**Comment by zhanglidonga** [comment]
链接达梦启动的就卡住，也是卡在这里，后来加了参数配置解决了

**Comment by jack-love-rose** [comment]
1.1.22版本在高并发情况下复现了此问题

**Comment by ruanjianershu** [comment]
现在是2021.6.7  问题有解决的了么 ？

**Comment by sai129198** [comment]
1.2.6还能复现这个问题

**Comment by sai129198** [comment]
> 有连接超时的配置选项，这个可以配置起来，但不建议配置，大部分情况一个事务执行的时间要尽量短
> **2 增加应用的最大连接数配置 3 解决应用中的长事务。**

既然存在连接一直无法被释放，即使增大链接池maxActive、解决长事务，也只是延缓了问题发生而已，这个坑还留在线上服务，问题迟早也会暴雷。

**Comment by slipdaly** [comment]
1.1.22复现这个问题，最终分析是死锁导致的。
#是否自动回收超时连接
removeAbandoned=true
#超时时间(以秒数为单位)
removeAbandonedTimeout=180
#是否打印日志
logAbandoned=true
建议加上这几个配置，问题复现时，日志搜索关键字“abandon connection”查看长时间不释放链接的业务。

**Comment by caukie** [comment]
2021.7.9 1.1.23 报到，实际查看跟db的tcp连接只有个位数，maxactive有30，但是仍然卡住

**Comment by junfeng-feng** [comment]
2021.7.23遇到同样的问题，druid版本1.0.31, tomcat 200个线程，都在等待takelast，导致tomcat无法接收新的请求

**Comment by fengzao** [comment]
最近也遇到这个问题, 已定位并找到原因： 问题主要业务代码上,  大体原因可以描述为

- 一个线程在持有一个 connection 的没有释放的情况下 再次尝试去获取一个新的 connection.    比如: 在开启一个事务的场景下,下一个业务事务要求使用新的链接.

###  如何找到是那个线程持有了 connection 并尝试创建获取新链接. 并基于线程栈定位业务代码

-  dump 卡死机器 jvm 内存
- 使用 内存分析工具 分析，搜索 DruidPooledConnection 对象并通过查看传入引用定位是由那个线程持有了已有的 connection.
- 查看持有线程的 connection 代码位置 同时 比对该线程申请新 connection 的位置(业务代码).  
- 比对上述线程栈 即可发现问题.  下图是 jprofile 找到的 DruidPooledConnection 持有的线程示意图

![image](https://user-images.githubusercontent.com/26789705/128818367-198e36f5-9047-46c3-92e4-0abbabc3c584.png)

**Comment by wwangrystorm** [comment]
我在druid 1.1.20版本出现过这个问题
通过持续jstack 发现大量的线程卡在两处代码
一些线程卡在释放连接等待公平锁
![释放链接时等待公平锁](https://user-images.githubusercontent.com/89726170/131244625-8ec896f8-ceb3-4fa2-98eb-842a2f36361f.png)

一些线程卡在 获取连接等待公平锁
![请求链接时等待公平锁](https://user-images.githubusercontent.com/89726170/131244767-5668fe4c-5516-4ec6-913d-3f074d06ed5c.png)
 druid 默认配置为非公平锁，不过一旦设置了maxWait 之后就会使用公平锁模式。
参考这个帖子的解释
https://www.136.la/jingpin/show-27144.html

**Comment by wwangrystorm** [comment]
上面的帖子中给出了方法
// 设置druid 连接池非公平锁模式
dataSource.setUseUnfairLock(true);
但是我实验了一下，不成功，需要再配置文件中设置
类似这样：
![image](https://user-images.githubusercontent.com/89726170/131244813-45d4fb04-b74b-484d-9e63-0cbeb24986ff.png)
因为druid的代码逻辑有问题
![setUseUnfairLock问题](https://user-images.githubusercontent.com/89726170/131244958-af815c9e-f963-4b91-8435-1137c622c7b7.png)

在配置文件中设置为啥又可以能？
因为配置文件中现有一个参数maxWait，这个会导致执行setMaxWait创建一个公平锁来代替非公平锁
![image](https://user-images.githubusercontent.com/89726170/131245027-1145d4b0-b30a-4136-8ab9-794b9a9b4ed4.png)
在maxWait之后，再设置useFairLock 这个时候函数setUseUnfairLock的条件就满足了。
可以继续往下执行代码，又将锁换成了非公平锁

**Comment by whiletrue2009** [comment]
druid-1.1.16 版本报道，  服务两个节点一起跑就出现问题，停止一个就正常。
有大量的

```
"http-nio-10031-exec-194" #255 daemon prio=5 os_prio=0 tid=0x00007f7f6815b000 nid=0x5157 waiting on condition [0x00007f7f28a4a000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000c0f41348> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at com.alibaba.druid.pool.DruidDataSource.takeLast(DruidDataSource.java:2029)
	at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1557)
	at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1337)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1317)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1307)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:109)
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:261)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.startTransaction(AbstractPlatformTransactionManager.java:400)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:574)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:361)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	
```
存在，几乎所有都在  `parking to wait for  <0x00000000c0f41348>`

暂时恢复运行，问题原因还在定义

**Comment by wenshao** [comment]
这个是慢SQL导致连接池不够用吧

**Comment by whiletrue2009** [comment]
> 这个是慢SQL导致连接池不够用吧

感觉是很像，怀疑是突然出现了大量请求，耗尽了连接。

**Comment by David0789** [comment]
都2022年了，我今天也遇到了这个问题，线程都挂起了，不再写入数据库，定位也是这坨代码

**Comment by LvanLiu** [comment]
都 2022 年底了，今天也重现了这个问题，服务挂了几个。

**Comment by LvanLiu** [comment]
Druid 没人维护了吗？

**Comment by hanjieliao** [comment]
`"http-nio-8002-exec-15" #158 daemon prio=5 os_prio=0 cpu=3.97ms elapsed=885.17s tid=0x00007f3ffc061000 nid=0xc6 waiting on condition  [0x00007f3f45cd0000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.16/Native Method)
	- parking to wait for  <0x0000000706e3e1b0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.16/LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@11.0.16/AbstractQueuedSynchronizer.java:2081)
	at com.alibaba.druid.pool.DruidDataSource.takeLast(DruidDataSource.java:2196)`

都快2023年了， 居然还遇到这个线程挂起问题， 我用的版本是1.2.11  升级到1.2.15暂时好了。 希望不要再出现这个问题

**Comment by manzhizhen** [comment]
我之前也遇到了，但是是使用SqlSessionManager时（非Spring的Java项目）开启了sqlSessionManager.startManagedSession(true);，用这个的话一旦连接被拿出来，就不会被放回去了，所以导致这个问题，切记勿用自己单独使用sqlSessionManager.startManagedSession(true)；用了也得主动去关闭Session

**Comment by me2in** [comment]
2023年同样遇到这个问题，最后解决了，提供下自己的解决思路：

1. 首先要确认自己的连接池配置是否正确被druid读取到，可以本地使用相同配置启动应用，然后用VisualVM通过mbean方式查看DruidDataSource属性值判断。
2. 确认自己的连接池设置是否合理？比如最大连接数过小？maxActive未设置（如果未设置是默认-1，加上默认的非公平锁，可能会导致某些线程无限等待）。
3. 如果前两者都确认无误，可能是你的应用存在连接泄漏，参考[连接池泄漏检测](https://github.com/alibaba/druid/wiki/%E8%BF%9E%E6%8E%A5%E6%B3%84%E6%BC%8F%E7%9B%91%E6%B5%8B)

**Comment by lizongbo** [comment]
还有一种卡死情况，是mysql 5.x和mysql 8.x的jdbc驱动同时存在， 出现class加载问题时，也会这样，是我们遇到的问题。
只保留一个版本的mysql jdbc驱动即可。

**Comment by fangxingfu** [comment]
都2024年了，还遇到同样的问题

**Comment by YourXin** [comment]
都2025年了，还遇到同样的问题;
----
提供一个解决思路：
1. 没有采用druid starter的情况下， 可以试下在代码中手动配置 DataSource  ； **实测有效**
```java
@Slf4j
@Configuration
public class DruidConfig {
    @Value("${spring.datasource.url}")
    private String dbUrl;
    @Value("${spring.datasource.username}")
    private String username;
    @Value("${spring.datasource.password}")
    private String password;
    @Value("${spring.datasource.druid.username:admin}")
    private String druidUsername;
    @Value("${spring.datasource.druid.password:hd123}")
    private String druidPassword;
    @Value("${spring.datasource.driver-class-name:com.mysql.jdbc.Driver}")
    private String driverClassName;
    @Value("${spring.datasource.initialSize:10}")
    private int initialSize;
    @Value("${spring.datasource.minIdle:10}")
    private int minIdle;
    @Value("${spring.datasource.maxActive:1000}")
    private int maxActive;
    @Value("${spring.datasource.maxWait:-1}")
    private int maxWait;
    @Value("${spring.datasource.timeBetweenEvictionRunsMillis:60000}")
    private int timeBetweenEvictionRunsMillis;
    @Value("${spring.datasource.minEvictableIdleTimeMillis:1800000}")
    private int minEvictableIdleTimeMillis;
    @Value("${spring.datasource.validationQuery:SELECT 1}")
    private String validationQuery;
    @Value("${spring.datasource.testWhileIdle:true}")
    private boolean testWhileIdle;
    @Value("${spring.datasource.testOnBorrow:false}")
    private boolean testOnBorrow;
    @Value("${spring.datasource.testOnReturn:false}")
    private boolean testOnReturn;
    @Value("${spring.datasource.poolPreparedStatements:true}")
    private boolean poolPreparedStatements;
    @Value("${spring.datasource.filters:stat,log4j}")
    private String filters;
    @Value("${spring.datasource.logSlowSql:true}")
    private String logSlowSql;

    public DruidConfig() {
    }

    @Bean
    public ServletRegistrationBean druidServlet() {
        ServletRegistrationBean reg = new ServletRegistrationBean();
        reg.setServlet(new StatViewServlet());
        reg.addUrlMappings(new String[]{"/druid/*"});
        reg.addInitParameter("loginUsername", this.druidUsername);
        reg.addInitParameter("loginPassword", this.druidPassword);
        reg.addInitParameter("logSlowSql", this.logSlowSql);
        return reg;
    }

    @Bean
    @Primary
    public DataSource druidDataSource() {
        DruidDataSource datasource = new DruidDataSource();
        datasource.setUrl(this.dbUrl);
        datasource.setUsername(this.username);
        datasource.setPassword(this.password);
        datasource.setDriverClassName(this.driverClassName);
        datasource.setInitialSize(this.initialSize);
        datasource.setMinIdle(this.minIdle);
        datasource.setMaxActive(this.maxActive);
        datasource.setMaxWait(this.maxWait);
        datasource.setTimeBetweenEvictionRunsMillis(this.timeBetweenEvictionRunsMillis);
        datasource.setMinEvictableIdleTimeMillis(this.minEvictableIdleTimeMillis);
        datasource.setValidationQuery(this.validationQuery);
        datasource.setTestWhileIdle(this.testWhileIdle);
        datasource.setTestOnBorrow(this.testOnBorrow);
        datasource.setTestOnReturn(this.testOnReturn);
        datasource.setPoolPreparedStatements(this.poolPreparedStatements);
        datasource.setConnectionInitSqls(Collections.singletonList("set names utf8mb4"));

        try {
            datasource.setFilters(this.filters);
        } catch (SQLException var3) {
            log.error("druid configuration initialization filter", var3);
        }

        return datasource;
    }
}
```

**Comment by Centerful** [comment]
26年了，使用1.2.18版本也有这个问题，配置了max-wait也不行。应用配置了两个数据源，偶然的一次并发导致另一个数据源的druid连接打满没有释放，排查对应数据库连接数很少，应该是druid自己没有释放connection导致，项目运行五年了第一次遇到。难道需要配置removeabandoned？这个在生产配置有风险吧。

对应堆栈信息：
`"http-thread-pool::http-listener(124)" #20379 daemon prio=5 os_prio=0 tid=0x00007f7c28125000 nid=0x4fa8 waiting on condition [0x00007f7ad15fb000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park0(Native Method)
	- parking to wait for  <0x00000005fc945b88> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at sun.misc.Unsafe.park(Unsafe.java:1038)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:176)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2047)
	at com.alibaba.druid.pool.DruidDataSource.takeLast(DruidDataSource.java:2315)
	at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1781)
	at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1494)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5058)
	at com.alibaba.druid.filter.logging.LogFilter.dataSource_getConnection(LogFilter.java:909)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5054)
	at com.alibaba.druid.filter.stat.StatFilter.dataSource_getConnection(StatFilter.java:704)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5054)
	at com.alibaba.druid.filter.FilterAdapter.dataSource_getConnection(FilterAdapter.java:2759)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5054)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1469)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1459)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:83)
	at org.springframework.jdbc.datasource.lookup.AbstractRoutingDataSource.getConnection(AbstractRoutingDataSource.java:164)
	at org.springframework.jdbc.datasource.lookup.AbstractRoutingDataSource.getConnection(AbstractRoutingDataSource.java:164)
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:211)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:447)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:277)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:52)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:52)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656)
`

**Comment by mrhanhan** [comment]
FK, 26年了也是这个问题
