### ISSUE TITLE
向含有text和blob字段类型的分表中插入数据时失败

### ISSUE THREAD

**Issue by dzxiang** [alibaba/druid#1201]
**# MyBatis+MySQL，向含有text和blob字段类型的分表中插入数据数据时失败，异常信息如下：**
Caused by: java.sql.SQLException: Invalid argument value: java.io.NotSerializableException
 at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:998)
 at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:937)
 at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926)
 at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:872)
 at com.mysql.jdbc.PreparedStatement.setSerializableObject(PreparedStatement.java:3887)
 at com.mysql.jdbc.PreparedStatement.setObject(PreparedStatement.java:3603)
 at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_setObject(FilterChainImpl.java:2923)
 at com.alibaba.druid.filter.FilterAdapter.preparedStatement_setObject(FilterAdapter.java:1298)
 at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_setObject(FilterChainImpl.java:2920)
 at com.alibaba.druid.filter.FilterAdapter.preparedStatement_setObject(FilterAdapter.java:1298)
 at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_setObject(FilterChainImpl.java:2920)
 at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.setObject(PreparedStatementProxyImpl.java:411)
 at com.alibaba.druid.pool.DruidPooledPreparedStatement.setObject(DruidPooledPreparedStatement.java:476)
 at com.dangdang.ddframe.rdb.sharding.jdbc.ShardingPreparedStatement.setParameters(ShardingPreparedStatement.java:188)
 at com.dangdang.ddframe.rdb.sharding.jdbc.ShardingPreparedStatement.routeSQL(ShardingPreparedStatement.java:163)
 at com.dangdang.ddframe.rdb.sharding.jdbc.ShardingPreparedStatement.routeIfNeed(ShardingPreparedStatement.java:151)
 at com.dangdang.ddframe.rdb.sharding.jdbc.ShardingPreparedStatement.getRoutedPreparedStatements(ShardingPreparedStatement.java:138)
 at com.dangdang.ddframe.rdb.sharding.jdbc.ShardingPreparedStatement.execute(ShardingPreparedStatement.java:107)

Caused by: java.io.NotSerializableException: java.io.StringReader
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at com.mysql.jdbc.PreparedStatement.setSerializableObject(PreparedStatement.java:3876)
	... 86 common frames omitted

**Comment by wenshao** [comment]
这是jdbc驱动的bug吧，和druid有关系么？

**Comment by dzxiang** [comment]
晕，发错地方了！
