### ISSUE TITLE
build error with 'mvn package'

### ISSUE THREAD

**Issue by nshigit** [alibaba/druid#1230]
nshi@beta /etc $ uname -a 
Linux beta 3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

nshi@beta /etc $ cat os-release
NAME="Ubuntu"
VERSION="14.04.4 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.4 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

java -version
java version "1.7.0_75"
Java(TM) SE Runtime Environment (build 1.7.0_75-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.75-b04, mixed mode)

mvn --version
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.7.0_75, vendor: Oracle Corporation
Java home: /usr/lib/jvm/jdk1.7.0_75/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.16.0-38-generic", arch: "amd64", family: "unix"

mvn package
[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building druid 1.0.19
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.oracle:ojdbc6:jar:11.2.0.3 is missing, no dependency information available
[WARNING] The POM for proxool:proxool:jar:0.9.1 is missing, no dependency information available
[WARNING] The POM for proxool:proxool-cglib:jar:0.9.1 is missing, no dependency information available
## Downloading: file:///home/nshi/workspace/druid-1.0.19/lib/org/sonatype/oss/oss-parent/9/oss-parent-9.pom

constituent[0]: file:/usr/share/maven/lib/aether-util.jar
constituent[1]: file:/usr/share/maven/lib/commons-cli.jar
constituent[2]: file:/usr/share/maven/lib/wagon-provider-api.jar
constituent[3]: file:/usr/share/maven/lib/aether-connector-wagon.jar
constituent[4]: file:/usr/share/maven/lib/plexus-component-annotations.jar
constituent[5]: file:/usr/share/maven/lib/maven-plugin-api-3.x.jar
constituent[6]: file:/usr/share/maven/lib/maven-model-3.x.jar
constituent[7]: file:/usr/share/maven/lib/commons-logging.jar
constituent[8]: file:/usr/share/maven/lib/plexus-sec-dispatcher.jar
constituent[9]: file:/usr/share/maven/lib/guava.jar
constituent[10]: file:/usr/share/maven/lib/aether-api.jar
constituent[11]: file:/usr/share/maven/lib/maven-core-3.x.jar
constituent[12]: file:/usr/share/maven/lib/sisu-guice.jar
constituent[13]: file:/usr/share/maven/lib/sisu-inject-bean.jar
constituent[14]: file:/usr/share/maven/lib/maven-embedder-3.x.jar
constituent[15]: file:/usr/share/maven/lib/maven-compat-3.x.jar
constituent[16]: file:/usr/share/maven/lib/plexus-utils.jar
constituent[17]: file:/usr/share/maven/lib/maven-artifact-3.x.jar
constituent[18]: file:/usr/share/maven/lib/maven-settings-builder-3.x.jar
constituent[19]: file:/usr/share/maven/lib/sisu-inject-plexus.jar
constituent[20]: file:/usr/share/maven/lib/commons-codec.jar
constituent[21]: file:/usr/share/maven/lib/maven-repository-metadata-3.x.jar
constituent[22]: file:/usr/share/maven/lib/maven-model-builder-3.x.jar
constituent[23]: file:/usr/share/maven/lib/aether-spi.jar
constituent[24]: file:/usr/share/maven/lib/plexus-interpolation.jar
constituent[25]: file:/usr/share/maven/lib/aether-impl.jar
constituent[26]: file:/usr/share/maven/lib/wagon-http-shaded.jar
constituent[27]: file:/usr/share/maven/lib/commons-httpclient.jar
constituent[28]: file:/usr/share/maven/lib/plexus-cipher.jar
constituent[29]: file:/usr/share/maven/lib/maven-aether-provider-3.x.jar
constituent[30]: file:/usr/share/maven/lib/maven-settings-3.x.jar
## constituent[31]: file:/usr/share/maven/lib/wagon-file.jar

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
    at org.apache.maven.wagon.providers.file.FileWagon.resolveDestinationPath(FileWagon.java:206)
    at org.apache.maven.wagon.providers.file.FileWagon.resourceExists(FileWagon.java:265)
    at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:577)
    at org.sonatype.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:60)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.StringUtils
    at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:259)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:235)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:227)
    ... 7 more
Exception in thread "pool-1-thread-1" java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
    at org.apache.maven.wagon.providers.file.FileWagon.resolveDestinationPath(FileWagon.java:206)
    at org.apache.maven.wagon.providers.file.FileWagon.resourceExists(FileWagon.java:265)
    at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:577)
    at org.sonatype.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:60)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.StringUtils
    at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:259)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:235)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:227)
    ... 7 more

**Comment by wenshao** [comment]
感觉是你本地的maven仓库里的jar有问题，建议清空.m2目录

**Comment by lizongbo** [comment]
请使用最新代码验证
