### ISSUE TITLE
druid1.0.4版项目运行一段时间后报错，重新获取连接需要半个小时？

### ISSUE THREAD

**Issue by wuzhiyong08** [alibaba/druid#1238]
连接池调用sqlserver出错：
[org.springframework.scheduling.concurrent.ThreadPoolExecutorFactoryBean#0-50] ERROR com.alibaba.druid.util.JdbcUtils:94 - close statement error
java.sql.SQLException: Invalid state, the Connection object is closed.
        at net.sourceforge.jtds.jdbc.TdsCore.checkOpen(TdsCore.java:458)
        at net.sourceforge.jtds.jdbc.TdsCore.clearResponseQueue(TdsCore.java:734)
        at net.sourceforge.jtds.jdbc.JtdsStatement.reset(JtdsStatement.java:723)
        at net.sourceforge.jtds.jdbc.JtdsStatement.close(JtdsStatement.java:972)
        at com.alibaba.druid.filter.FilterChainImpl.statement_close(FilterChainImpl.java:2386)
        at com.alibaba.druid.filter.stat.StatFilter.statement_close(StatFilter.java:311)
        at com.alibaba.druid.filter.FilterChainImpl.statement_close(FilterChainImpl.java:2383)
        at com.alibaba.druid.proxy.jdbc.StatementProxyImpl.close(StatementProxyImpl.java:124)
        at com.alibaba.druid.util.JdbcUtils.close(JdbcUtils.java:92)
        at com.alibaba.druid.pool.DruidAbstractDataSource.testConnectionInternal(DruidAbstractDataSource.java:1259)
        at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:928)
        at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4544)
        at com.alibaba.druid.filter.stat.StatFilter.dataSource_getConnection(StatFilter.java:661)
        at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4540)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:880)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:872)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:97)
        at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111)
        at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:77)
        at org.mybatis.spring.transaction.SpringManagedTransaction.openConnection(SpringManagedTransaction.java:80)
        at org.mybatis.spring.transaction.SpringManagedTransaction.getConnection(SpringManagedTransaction.java:66)
        at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:271)
        at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:69)
        at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:44)
        at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:100)
        at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:75)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:148)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.delete(DefaultSqlSession.java:161)
        at sun.reflect.GeneratedMethodAccessor30.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:354)
        at $Proxy8.delete(Unknown Source)
        at org.mybatis.spring.SqlSessionTemplate.delete(SqlSessionTemplate.java:264)
        at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:52)
        at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:43)
        at $Proxy10.delete(Unknown Source)
        at cn.i8.api.bo.AdPositionBo.syncAdPosition(AdPositionBo.java:60)
        at cn.i8.api.service.AdPositionService.adPosition(AdPositionService.java:21)
        at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at com.rop.impl.AnnotationServiceMethodAdapter.invokeServiceMethod(AnnotationServiceMethodAdapter.java:48)
        at com.rop.impl.AnnotationServletServiceRouter.doService(AnnotationServletServiceRouter.java:655)
        at com.rop.impl.AnnotationServletServiceRouter.access$600(AnnotationServletServiceRouter.java:43)
        at com.rop.impl.AnnotationServletServiceRouter$ServiceRunnable.run(AnnotationServletServiceRouter.java:453)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
        at java.util.concurrent.FutureTask.run(FutureTask.java:138)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
        at java.lang.Thread.run(Thread.java:662)

**Comment by FuZhenn** [comment]
.1.0.4版版本太老了, 升级一下试试.
我也遇到了这个问题, 这个补丁或许能解决这个问题
https://github.com/alibaba/druid/pull/1102

**Comment by wuzhiyong08** [comment]
多谢，我准备升级到1.0.19试试

**Comment by zpa3x60** [comment]
这个问题解决了吗?

**Comment by fuzhenn** [comment]
我这里已经解决, 没再出现这个错误了

**Comment by zpa3x60** [comment]
能否告诉我怎么解决的？

2016-05-31



57714769



发件人：Fu Zhen <notifications@github.com>
发送时间：2016-05-31 20:58
主题：Re: [alibaba/druid] druid1.0.4版项目运行一段时间后报错，重新获取连接需要半个小时？ (#1238)
收件人："alibaba/druid"<druid@noreply.github.com>
抄送："zpa3x60"<57714769@163.com>,"Comment"<comment@noreply.github.com>

我这里已经解决, 没再出现这个错误了

**Comment by fuzhenn** [comment]
升级到最新版就可以了

**Comment by zpa3x60** [comment]
1.0.19版本？

2016-05-31



57714769



发件人：Fu Zhen <notifications@github.com>
发送时间：2016-05-31 21:01
主题：Re: [alibaba/druid] druid1.0.4版项目运行一段时间后报错，重新获取连接需要半个小时？ (#1238)
收件人："alibaba/druid"<druid@noreply.github.com>
抄送："zpa3x60"<57714769@163.com>,"Comment"<comment@noreply.github.com>

升级到最新版就可以了

**Comment by fuzhenn** [comment]
对
