### ISSUE TITLE
执行验证sql: select 1 时大量报错java.sql.SQLNonTransientConnectionException: Could not read resultset: unexpected end of stream, read 0 bytes from 4

### ISSUE THREAD

**Issue by tonnyyi** [alibaba/druid#1241]
数据库版本: 5.5.48-MariaDB MariaDB Server
druid版本: 1.0.19
- 使用spring注解方式生成DataSource

``` java
@Bean
public DataSource druidDataSource(@Value("${jdbc.driver}") String driver, @Value("${jdbc.url}") String url,
        @Value("${jdbc.username}") String username, @Value("${jdbc.password}") String password) {
    DruidDataSource source = new DruidDataSource();
    source.setDriverClassName(driver);
    source.setUrl(url);
    source.setUsername(username);
    source.setPassword(password);

    source.setInitialSize(5);
    source.setMinIdle(3);
    source.setMaxWait(60_000);

    source.setValidationQuery("select 1");
    source.setTestOnBorrow(true);
    source.setTestOnReturn(true);
    source.setTestWhileIdle(true);
    source.setMaxActive(20);

    source.setTimeBetweenEvictionRunsMillis(60_000);
    source.setMinEvictableIdleTimeMillis(3_000_000);
    source.setRemoveAbandoned(true);
    source.setRemoveAbandonedTimeout(1800);
    source.setLogAbandoned(true);
    source.addConnectionProperty("druid.stat.slowSqlMillis", "300");

    try {
        source.setFilters("mergeStat,stat,slf4j,wall");
    }
    catch (SQLException e) {
        throw new RuntimeException(e);
    }
    return source;
}
```
- 配置信息

```
jdbc.url=jdbc:mysql://xxx:3306/virtualTest?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useCursorFetch=true&defaultFetchSize=1000
jdbc.username=xxx
jdbc.password=xxx
jdbc.driver=org.mariadb.jdbc.Driver
```
- 再生成spring JdbcTemplate, 后续sql都是通过JdbcTemplate执行

``` java
@Bean
public JdbcTemplate jdbcTemplate(DataSource dataSource) {
    return new JdbcTemplate(dataSource);
}
```
- 项目启动几分钟后报错(数量很多), 完整异常如下:

```
2016-05-16 15:06:37.355 [pool-10-thread-1] ERROR druid.sql.Statement:149 - {conn-10002, stmt-24042} execute error. select 1
java.sql.SQLNonTransientConnectionException: Could not read resultset: unexpected end of stream, read 0 bytes from 4
Query is : select 1
    at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:123)
    at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
    at org.mariadb.jdbc.MariaDbStatement.executeQueryEpilog(MariaDbStatement.java:250)
    at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:278)
    at org.mariadb.jdbc.MariaDbStatement.executeQuery(MariaDbStatement.java:391)
    at com.alibaba.druid.filter.FilterChainImpl.statement_executeQuery(FilterChainImpl.java:2363)
    at com.alibaba.druid.wall.WallFilter.statement_executeQuery(WallFilter.java:512)
    at com.alibaba.druid.filter.FilterChainImpl.statement_executeQuery(FilterChainImpl.java:2360)
    at com.alibaba.druid.filter.FilterAdapter.statement_executeQuery(FilterAdapter.java:2481)
    at com.alibaba.druid.filter.FilterEventAdapter.statement_executeQuery(FilterEventAdapter.java:302)
    at com.alibaba.druid.filter.FilterChainImpl.statement_executeQuery(FilterChainImpl.java:2360)
    at com.alibaba.druid.filter.FilterAdapter.statement_executeQuery(FilterAdapter.java:2481)
    at com.alibaba.druid.filter.FilterEventAdapter.statement_executeQuery(FilterEventAdapter.java:302)
    at com.alibaba.druid.filter.FilterChainImpl.statement_executeQuery(FilterChainImpl.java:2360)
    at com.alibaba.druid.filter.FilterAdapter.statement_executeQuery(FilterAdapter.java:2481)
    at com.alibaba.druid.filter.FilterEventAdapter.statement_executeQuery(FilterEventAdapter.java:302)
    at com.alibaba.druid.filter.FilterChainImpl.statement_executeQuery(FilterChainImpl.java:2360)
    at com.alibaba.druid.proxy.jdbc.StatementProxyImpl.executeQuery(StatementProxyImpl.java:211)
    at com.alibaba.druid.pool.DruidAbstractDataSource.testConnectionInternal(DruidAbstractDataSource.java:1303)
    at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1030)
    at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4544)
    at com.alibaba.druid.filter.FilterAdapter.dataSource_getConnection(FilterAdapter.java:2723)
    at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4540)
    at com.alibaba.druid.filter.logging.LogFilter.dataSource_getConnection(LogFilter.java:831)
    at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4540)
    at com.alibaba.druid.filter.stat.StatFilter.dataSource_getConnection(StatFilter.java:662)
    at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4540)
    at com.alibaba.druid.filter.stat.StatFilter.dataSource_getConnection(StatFilter.java:662)
    at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4540)
    at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:995)
    at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:987)
    at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:103)
    at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111)
    at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:77)
    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:390)
    at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:470)
    at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:480)
    at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:490)
    at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:496)
    at com.singulax.mysql2Elastic.ScheduledTasks.countOrder(ScheduledTasks.java:73)
    at com.singulax.mysql2Elastic.ScheduledTasks.dumpHourOrder(ScheduledTasks.java:47)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
    at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not read resultset: unexpected end of stream, read 0 bytes from 4
Query is : select 1
    at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:878)
    at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:574)
    at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:269)
    ... 50 common frames omitted
Caused by: java.io.EOFException: unexpected end of stream, read 0 bytes from 4
    at org.mariadb.jdbc.internal.packet.read.ReadPacketFetcher.getReusableBuffer(ReadPacketFetcher.java:168)
    at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:869)
    ... 52 common frames omitted
```

报错之后, 原先的sql还会执行成功, 应该是执行sql前验证连接是否可用, 报错后重新获取连接, 再执行原先的sql, 但为什么会报错呢? 虽然不影响业务, 但有什么配置可以解决吗?

**Comment by SplendorAnLin** [comment]
我也遇到了这个问题...  自建的MySQL 5.7

**Comment by guoruiak** [comment]
也遇到这个问题了。使用mariadb-connector就有这个问题，之前使用mysql-connecter是正常的。

**Comment by kevinusable** [comment]
+1

**Comment by lizongbo** [comment]
JDBC驱动的问题，升级JDBC驱动来解决

**Comment by kevinusable** [comment]
感谢您的来信，我会尽快查看的。
