### ISSUE TITLE
这个异常是什么原因引起的？java.sql.SQLException: connection holder is null

### ISSUE THREAD

**Issue by zhangjianweibj** [alibaba/druid#1282]
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown.
	at sun.reflect.GeneratedConstructorAccessor337.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.Util.getInstance(Util.java:387)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:917)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:896)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:885)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860)
	at com.mysql.jdbc.ConnectionImpl.rollback(ConnectionImpl.java:4634)
	at com.alibaba.druid.filter.FilterChainImpl.connection_rollback(FilterChainImpl.java:533)
	at com.alibaba.druid.filter.FilterAdapter.connection_rollback(FilterAdapter.java:972)
	at com.alibaba.druid.filter.logging.LogFilter.connection_rollback(LogFilter.java:383)
	at com.alibaba.druid.filter.FilterChainImpl.connection_rollback(FilterChainImpl.java:529)
	at com.alibaba.druid.filter.FilterAdapter.connection_rollback(FilterAdapter.java:972)
	at com.alibaba.druid.filter.FilterChainImpl.connection_rollback(FilterChainImpl.java:529)
	at com.alibaba.druid.filter.stat.StatFilter.connection_rollback(StatFilter.java:268)
	at com.alibaba.druid.filter.FilterChainImpl.connection_rollback(FilterChainImpl.java:529)
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.rollback(ConnectionProxyImpl.java:400)
	at com.alibaba.druid.pool.DruidPooledConnection.rollback(DruidPooledConnection.java:757)
	at org.hibernate.transaction.JDBCTransaction.rollbackAndResetAutoCommit(JDBCTransaction.java:213)

**Comment by junbaor** [comment]
检查配置是不是开启了 `removeAbandoned` 功能

**Comment by lovederh** [comment]
请问这个问题解决了吗？我也遇到了同样的问题！性能测试时300并发运行5-10分钟之间就会出这个异常！

**Comment by qq291462491** [comment]
表示遇到了同样的问题，有官方的答案吗？

**Comment by halober** [comment]
也遇到这个问题，不知道升级druid到1.1.6能不能好

**Comment by zongxingy** [comment]
1.1.9也会出现这个问题，请问有解决方法吗？

**Comment by Fadeoc** [comment]
因为在调用sql实例的时候发现sql实例为 null。
但是 def sql = new sql(连接池) 的时候的实例哪去了呢? 

可能之一是，检测代码中是否有 sql.close()。如果有，看看下面还有没有分支调用 sql。如果下面已经没有分支调用sql，看看sql.close()是不是在sql.withTransaction {}中。
