### ISSUE TITLE
com.alibaba.druid.sql.parser.ParserException: Error : CROSS

### ISSUE THREAD

**Issue by yongxing510** [alibaba/druid#1285]
com.alibaba.druid.sql.parser.ParserException: Error : CROSS
	at com.alibaba.druid.sql.parser.SQLParser.as(SQLParser.java:171)
	at com.alibaba.druid.sql.parser.SQLExprParser.parseSelectItem(SQLExprParser.java:1901)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseSelectList(SQLSelectParser.java:359)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.query(OracleSelectParser.java:264)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.select(OracleSelectParser.java:85)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleStatementParser.parseStatementList(OracleStatementParser.java:164)
当使用下述语句 select name as cross from crossing where id=86 时，解析出错，原因：as关键字后的名字为cross，解析cross时出错

**Comment by zhangjianweibj** [comment]
cross是oracle中的关键字吧。WallUtils.isValidateOracle(“select name as cross from crossing where id=86”)dubug试试

**Comment by yongxing510** [comment]
嗯，是关键字，还测试了部分其他关键字，在as后面都会报错，请问当前没有对as后为关键字的场景进行容错处理吧

**Comment by yongxing510** [comment]
WallUtils.isValidateOracle("select name as cross from abc") 依然解析异常，1.0.26 druid版
