### ISSUE TITLE
DruidDataSource recyle error

### ISSUE THREAD

**Issue by icallcenter** [alibaba/druid#1301]
druid 1.0.16
mysql 5.5.17
driver 5.1.37

2016-06-18 15:13:16,622 ERROR c.a.d.p.DruidDataSource [Thread-8] recyle error
java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1219) ~[?:1.7.0_80]
        at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:340) ~[?:1.7.0_80]
        at com.alibaba.druid.pool.DruidDataSource.recycle(DruidDataSource.java:1281) [druid-1.0.16.jar:1.0.16]
        at com.alibaba.druid.pool.DruidPooledConnection.recycle(DruidPooledConnection.java:297) [druid-1.0.16.jar:1.0.16]
        at com.alibaba.druid.filter.FilterChainImpl.dataSource_recycle(FilterChainImpl.java:4534) [druid-1.0.16.jar:1.0.16]
        at com.alibaba.druid.filter.FilterAdapter.dataSource_releaseConnection(FilterAdapter.java:2717) [druid-1.0.16.jar:1.0.16]
        at com.alibaba.druid.filter.FilterChainImpl.dataSource_recycle(FilterChainImpl.java:4530) [druid-1.0.16.jar:1.0.16]
        at com.alibaba.druid.pool.DruidPooledConnection.close(DruidPooledConnection.java:245) [druid-1.0.16.jar:1.0.16]
        at org.springframework.jdbc.datasource.DataSourceUtils.doCloseConnection(DataSourceUtils.java:341) [spring-jdbc-4.2.2.RELEASE.jar:4.2.2.RELEASE]
        at org.springframework.orm.hibernate3.LocalDataSourceConnectionProvider.closeConnection(LocalDataSourceConnectionProvider.java:100) [spring-orm-4.2.2.RELEASE.jar:4.2.2.RELEASE]
        at org.hibernate.jdbc.ConnectionManager.closeConnection(ConnectionManager.java:474) [hibernate-core-3.6.10.Final.jar:3.6.10.Final]
        at org.hibernate.jdbc.ConnectionManager.cleanup(ConnectionManager.java:408) [hibernate-core-3.6.10.Final.jar:3.6.10.Final]
        at org.hibernate.jdbc.ConnectionManager.close(ConnectionManager.java:347) [hibernate-core-3.6.10.Final.jar:3.6.10.Final]
        at org.hibernate.impl.SessionImpl.close(SessionImpl.java:343) [hibernate-core-3.6.10.Final.jar:3.6.10.Final]
        at org.springframework.orm.hibernate3.SessionFactoryUtils.closeSession(SessionFactoryUtils.java:820) [spring-orm-4.2.2.RELEASE.jar:4.2.2.RELEASE]
        at org.springframework.orm.hibernate3.SessionFactoryUtils.closeSessionOrRegisterDeferredClose(SessionFactoryUtils.java:806) [spring-orm-4.2.2.RELEASE.jar:4.2.2.RELEASE]
        at org.springframework.orm.hibernate3.HibernateTemplate.doExecute(HibernateTemplate.java:438) [spring-orm-4.2.2.RELEASE.jar:4.2.2.RELEASE]
        at org.springframework.orm.hibernate3.HibernateTemplate.executeWithNativeSession(HibernateTemplate.java:378) [spring-orm-4.2.2.RELEASE.jar:4.2.2.RELEASE]
        at org.springframework.orm.hibernate3.HibernateTemplate.findByCriteria(HibernateTemplate.java:1125) [spring-orm-4.2.2.RELEASE.jar:4.2.2.RELEASE]

**Comment by icallcenter** [comment]
@wenshao 大神，求助

**Comment by taojiaenx** [comment]
通求助，我这边的数据库是oracle

**Comment by wangxufire** [comment]
能修复下么 @wenshao

**Comment by changetoblow** [comment]
[用的postgresql也出现这问题](https://github.com/alibaba/druid/issues/3361)

**Comment by Tinet-zhaojy** [comment]
https://blog.csdn.net/qq_36762677/article/details/103251891
