### ISSUE TITLE
PostgreSQL中jsonb类型字段查找报错

### ISSUE THREAD

**Issue by imlizhiqiang** [alibaba/druid#1302]
PostgreSQL数据库中的jsonb类型字段有一个   @>  这样的操作符，用于在字段中查找指定的json串。

使用datagrip这样的数据库工具连接，执行语句正常。

但在使用数据库连接池的场景下则报错。

语句：

SELECT id
FROM spoc_tj_course_class_teacher 
WHERE teacher_id_json::JSONB @> '"eb707a05-b082-4c9f-a391-10f916cee43e"';

相关错误提示如下：

 com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'SONB @> '"eb707a05-b082-4c9f-a391-1',expect VARIANT, actual VARIANT @
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:232)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:407)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:145)
	at com.alibaba.druid.wall.WallProvider.checkInternal(WallProvider.java:620)
	at com.alibaba.druid.wall.WallProvider.check(WallProvider.java:574)
	at com.alibaba.druid.wall.WallFilter.check(WallFilter.java:711)
	at com.alibaba.druid.wall.WallFilter.connection_prepareStatement(WallFilter.java:252)
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:448)
	at com.alibaba.druid.filter.FilterAdapter.connection_prepareStatement(FilterAdapter.java:928)
	at com.alibaba.druid.filter.FilterEventAdapter.connection_prepareStatement(FilterEventAdapter.java:122)
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:448)
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.prepareStatement(ConnectionProxyImpl.java:342)
	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:331)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.ConnectionLogger.invoke(ConnectionLogger.java:55)
	at com.sun.proxy.$Proxy46.prepareStatement(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.instantiateStatement(PreparedStatementHandler.java:87)
	at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:88)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.prepare(RoutingStatementHandler.java:59)
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:85)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:325)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:434)
	at com.sun.proxy.$Proxy31.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:231)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:128)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:68)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:53)
	at com.sun.proxy.$Proxy35.queryListCourseByTeacherId(Unknown Source)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1502)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1458)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

**Comment by imlizhiqiang** [comment]
这个问题我觉得可能是出在sql语句的预处理上，上面的语句有另一种写法，同样是pg支持的操作符，如下：

SELECT id
FROM spoc_tj_course_class_teacher
WHERE teacher_id_json ? 'eb707a05-b082-4c9f-a391-10f916cee43e';

该语句同样是在工具中能够正常执行，即数据库驱动运行该语句是没问题的，我自己写了纯JDBC代码测试，发现使用statement执行该语句，可以正确执行，如果使用prepareStatement则报错，可知该错误发生在预处理语句时，语句中的问号被视为一个参数的占位符。

现在的问题就是如果我想要执行带有这种“可以被预处理的符号”的SQL语句的时候，是否可以跳过预处理（即使用statement而不是prepareStatement）？如果可以的话如何配置？

**Comment by imlizhiqiang** [comment]
这个问题暂时得到了解决，不过只是一时的权宜之计，首先，我们使用了mybatis，通过statementType="STATEMENT"关闭了得到数据库连接之后的sql语句预处理行为，然后在druid的配置文件中，filter配置项暂时去掉了wall，关闭了防御sql注入功能。

之前的猜测有错误，现在重新描述一下这个问题：druid的防御sql注入过滤器，即wall，对postgresql中的某些操作符的支持尚待完善。

**Comment by wenshao** [comment]
已支持，请等待下一个版本1.0.21

**Comment by imlizhiqiang** [comment]
感谢，速度真快，点个赞。

**Comment by liyibo1110** [comment]
你好，我也遇到了同样的问题，我要执行的sql片段是这样的：（在其它db工具上运行都没有问题）
AND '{1,2,3}' @> ('{' || c.mark_level || '}') :: int[]	
如果把中间的“@”去掉就可以，加上了就不行，我已经更新到1.0.22版本，但还是不行，1.0.21版也不行。
目前我的解决方式是暂时关闭了filter的wall模块，1.0.21新增了JSON操作符解析，不包括上面的数组操作符吗？

**Comment by AliredDevils** [comment]
这个问题什么时候ifx，最新的v1.1.22版本上依然存在这个问题。
