### ISSUE TITLE
ORACLE 语法解析错误

### ISSUE THREAD

**Issue by SaddestMoon** [alibaba/druid#1327]
SELECT TRIM(BOTH FROM XXXX) FROM TABLE_A ,XXXX为字段名,其中的BOTH FROM中的FROM会引起SQL解析错误。
以下为某次报错的部分日志:
Preparing: SELECT TRIM(BOTH FROM EUCD) AS "value",NTLANG1 AS "text" FROM T_HT_WREM_ENUMLANG_D WHERE TYPE=? ORDER BY "value" ASC 
2016-07-12 14:32:08,155 [http-apr-8080-exec-9] DEBUG [**dao.mapper.EnumLangMapper.selectByType] - ==> Parameters: 10(String)
2016-07-12 14:32:08,220 [http-apr-8080-exec-9] WARN  [com.alibaba.druid.sql.SQLUtils] - format error
com.alibaba.druid.sql.parser.ParserException: ERROR. token : FROM, pos : 21
	at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:547)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleExprParser.primary(OracleExprParser.java:485)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleExprParser.methodRest(OracleExprParser.java:512)
	at com.alibaba.druid.sql.parser.SQLExprParser.primaryRest(SQLExprParser.java:653)

**Comment by wenshao** [comment]
已经修复，请等待要下个版本1.0.23发布，可能就在周末
