### ISSUE TITLE
WallFilter check issue: 

### ISSUE THREAD

**Issue by JackFish** [alibaba/druid#1339]
ALTER TABLE `icp`.`wx_msg` ADD CONSTRAINT `idx_msgId_msgType_event_eventKey` UNIQUE (`msgId`, `msgType`, `event`, `eventKey`)
is a vaild sql

Caused by: java.sql.SQLException: sql injection violation, syntax error: TODO UNIQUE UNIQUE : ALTER TABLE `icp`.`wx_msg` ADD CONSTRAINT `idx_msgId_msgType_event_eventKey` UNIQUE (`msgId`, `msgType`, `event`, `eventKey`)
	at com.alibaba.druid.wall.WallFilter.check(WallFilter.java:724)
	at com.alibaba.druid.wall.WallFilter.statement_execute(WallFilter.java:396)
	at com.alibaba.druid.filter.FilterChainImpl.statement_execute(FilterChainImpl.java:2487)
	at com.alibaba.druid.filter.FilterAdapter.statement_execute(FilterAdapter.java:2451)
	at com.alibaba.druid.filter.FilterEventAdapter.statement_execute(FilterEventAdapter.java:188)
	at com.alibaba.druid.filter.FilterChainImpl.statement_execute(FilterChainImpl.java:2487)
	at com.alibaba.druid.proxy.jdbc.StatementProxyImpl.execute(StatementProxyImpl.java:137)
	at com.alibaba.druid.pool.DruidPooledStatement.execute(DruidPooledStatement.java:421)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:299)
	... 28 more
Caused by: com.alibaba.druid.sql.parser.ParserException: TODO UNIQUE UNIQUE
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseAlterTable(MySqlStatementParser.java:2376)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseAlter(MySqlStatementParser.java:2298)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:220)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:147)
	at com.alibaba.druid.wall.WallProvider.checkInternal(WallProvider.java:620)
	at com.alibaba.druid.wall.WallProvider.check(WallProvider.java:574)
	at com.alibaba.druid.wall.WallFilter.check(WallFilter.java:711)
	... 36 more

**Comment by wenshao** [comment]
问题已解决，请等待下一个版本
