### ISSUE TITLE
使用mysql-connector-java 6.0.3的时候，数据源建立失败

### ISSUE THREAD

**Issue by 89333367** [alibaba/druid#1351]
```
<dependency>
    <groupId>mysql</groupId>
    <artifactId>mysql-connector-java</artifactId>
    <version>6.0.3</version>
</dependency>
```

使用这个驱动的时候，数据源建立失败

如果使用
```
<dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>5.1.39</version>
        </dependency>
```
这个驱动就可以

**Comment by wenshao** [comment]
还有这样的问题啊，我将会尽快跟进，谢谢反馈，如果能够进一步提供错误信息就好了

**Comment by yosaku01** [comment]
从6.0开始mysql driver的class变成com.mysql.cj.jdbc.Driver了，楼主确定驱动没有写错？

**Comment by Amous-th** [comment]
升级驱动6.0.3，druid1.0.23后出现一个NPE 

> Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
2016-08-01 17:54:51  WARN (MySqlValidConnectionChecker.java:53)MySqlValidConnectionChecker:53 - Cannot resolve com.mysq.jdbc.Connection.ping method.  Will use 'SELECT 1' instead.
java.lang.NullPointerException
	at com.alibaba.druid.pool.vendor.MySqlValidConnectionChecker.<init>(MySqlValidConnectionChecker.java:48)
	at com.alibaba.druid.pool.DruidDataSource.initValidConnectionChecker(DruidDataSource.java:945)
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:660)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

原因应该是没有“com.mysql.jdbc.MySQLConnection”类了。
不过项目启动任然是成功的。

**Comment by 89333367** [comment]
我用了新驱动，也是不行



在 Amous <notifications@github.com>，2016年8月1日 18:20写道：升级驱动6.0.3，druid1.0.23后出现一个NPE 


Loading class com.mysql.jdbc.Driver'. This is deprecated. The new driver class iscom.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
2016-08-01 17:54:51  WARN (MySqlValidConnectionChecker.java:53)MySqlValidConnectionChecker:53 - Cannot resolve com.mysq.jdbc.Connection.ping method.  Will use 'SELECT 1' instead.
java.lang.NullPointerException
    at com.alibaba.druid.pool.vendor.MySqlValidConnectionChecker.(MySqlValidConnectionChecker.java:48)
    at com.alibaba.druid.pool.DruidDataSource.initValidConnectionChecker(DruidDataSource.java:945)
    at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:660)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)


原因应该是没有“com.mysql.jdbc.MySQLConnection”类了。
不过项目启动任然是成功的。

**Comment by wenshao** [comment]
这是一个问题，已经修复，请等待这几天发布新版本吧

**Comment by Jasonguitar** [comment]
Good One
