### ISSUE TITLE
特殊的索引格式 druid parser 会失败

### ISSUE THREAD

**Issue by ChinaXing** [alibaba/druid#1356]
```
CREATE TABLE "item_extra" (
  "id" int(10) unsigned NOT NULL AUTO_INCREMENT,
  "item_id" int(10) unsigned NOT NULL DEFAULT '0' COMMENT '商品id',
  "type" tinyint(4) unsigned NOT NULL DEFAULT '0' COMMENT '扩展属性类型，0：虚拟商品',
  "attr_key" varchar(50) NOT NULL COMMENT '扩展属性key',
  "attr_value" varchar(500) NOT NULL COMMENT '扩展属性value',
  PRIMARY KEY ("id"),
  KEY "idx_item_type_kv" ("item_id","type","attr_key","attr_value"(191))
)
```

使用 1.0.21 parser 会发生如下错误？

```
com.alibaba.druid.sql.parser.ParserException: not support token:LITERAL_INT
        at com.alibaba.druid.sql.parser.SQLExprParser.methodRest(SQLExprParser.java:799) ~[druid-1.0.21.jar:1.0.21]
        at com.alibaba.druid.sql.parser.SQLExprParser.primaryRest(SQLExprParser.java:751) ~[druid-1.0.21.jar:1.0.21]
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.primaryRest(MySqlExprParser.java:481) ~[druid-1.0.21.jar:1.0.21]
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.primary(MySqlExprParser.java:132) ~[druid-1.0.21.jar:1.0.21]
        at com.alibaba.druid.sql.parser.SQLExprParser.expr(SQLExprParser.java:124) ~[druid-1.0.21.jar:1.0.21]
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlCreateTableParser.parseConstraint(MySqlCreateTableParser.java:787) ~[druid-1.0.21.jar:1.0.21]
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlCreateTableParser.parseCrateTable(MySqlCreateTableParser.java:157) ~[druid-1.0.21.jar:1.0.21]
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseCreate(MySqlStatementParser.java:340) ~[druid-1.0.21.jar:1.0.21]
        at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:190) ~[druid-1.0.21.jar:1.0.21]
        at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:1974) ~[druid-1.0.21.jar:1.0.21]

```

**Comment by wenshao** [comment]
已修复，等周末发布新版吧

**Comment by wenshao** [comment]
已发布
https://github.com/alibaba/druid/releases/tag/1.0.24
