### ISSUE TITLE
[com.alibaba.druid.sql.SQLUtils]format error

### ISSUE THREAD

**Issue by qqcbqqkcel** [alibaba/druid#1377]
oracle有下一每天SQL语句执行时报format错误,但不影响查询结果.版本是1.0.24
select 
		  AA.ID,
		  AA.CODE,
		  AA.TYPE,
		  AA.STATUS,
		  AA.EMPLOYEENAME,
		  AA.CREATORNAME,
		  AA.OPERATIONTYPE,
		  AA.CREATEDATE,
		  AA.REMARK,
		  W.NAME,
		  DD.DESC
		from 
			a AA,
			w W,
			d DD
		where 
		    AA.employeeNo IN (
		    	SELECT employeeno FROM employeeauditor ea WHERE auditorno = 1 GROUP BY employeeno
        		UNION ALL
        		SELECT 1 FROM dual 
        	) and
		    AA.WNO = W.WNO(+) and
		    AA.DEPTNO = DD.DEPTNO(+)
------------------------------------------------------
[com.alibaba.druid.sql.SQLUtils]format error
com.alibaba.druid.sql.parser.ParserException: syntax error, expect RPAREN, actual UNION UNION
	at com.alibaba.druid.sql.parser.SQLExprParser.accept(SQLExprParser.java:1656)
	at com.alibaba.druid.sql.parser.SQLExprParser.inRest(SQLExprParser.java:1238)
	at com.alibaba.druid.sql.parser.SQLExprParser.exprRest(SQLExprParser.java:142)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleExprParser.exprRest(OracleExprParser.java:1129)
	at com.alibaba.druid.sql.parser.SQLExprParser.expr(SQLExprParser.java:132)

**Comment by wenshao** [comment]
这个问题修正过，我补充了测试是可以跑通的，预计在周末发布新版本
