### ISSUE TITLE
sql parser：Stat，db2，with语句

### ISSUE THREAD

**Issue by sxrstrive** [alibaba/druid#1384]
执行db2中含有with的脚本报错，db2客户端测试脚本通过,
如果不配置wallfilter可以，其中filter配置filters="stat,log4j,wall"
脚本：
with temp as(
            select
                a.dmnr,a.bz,a.jgqjbs,a.jgqjms,a.px
            from dm.td_hzdmb a
            where a.dm=5
        )
temp2 as(
select
                a.dmnr,a.bz,a.jgqjbs,a.jgqjms,a.px
            from dm.td_hzdmb a
            where a.dm=4
)
select \* from temp
union all
select \* from temp2

异常信息如下：
Caused by: com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'WITH temp as(
            sele',expect WITH, actual WITH WITH
    at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:239)
    at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:424)
    at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:147)
    at com.alibaba.druid.wall.WallProvider.checkInternal(WallProvider.java:620)
    at com.alibaba.druid.wall.WallProvider.check(WallProvider.java:574)
    at com.alibaba.druid.wall.WallFilter.check(WallFilter.java:711)
    ... 109 more

**Comment by lianrao** [comment]
我们是一样，这个有解决吗？

**Comment by sxrstrive** [comment]
@lianrao 没，需要改jar包下的META-INF/druid/wall目录下的过滤配置。不过不配置wall防火墙拦截也是可以正常使用的，项目中把filters="stat,log4j,wall"中的wall去掉即可。
