### ISSUE TITLE
应用跑半个小时左右，大量报错，压力降低后又恢复正常！数据库、应用服务器资源使用率并不高。

### ISSUE THREAD

**Issue by liweiping321** [alibaba/druid#1411]
com.microsoft.sqlserver.jdbc.SQLServerException: 服务器无法继续执行该事务，说明: 13f00000197。
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216) ~[sqljdbc4.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1515) ~[sqljdbc4.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404) ~[sqljdbc4.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350) ~[sqljdbc4.jar:?]
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696) ~[sqljdbc4.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715) ~[sqljdbc4.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180) ~[sqljdbc4.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155) ~[sqljdbc4.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:332) ~[sqljdbc4.jar:?]
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:2931) ~[druid-1.0.23-SNAPSHOT.jar:1.0.23-SNAPSHOT]
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_execute(FilterEventAdapter.java:440) ~[druid-1.0.23-SNAPSHOT.jar:1.0.23-SNAPSHOT]
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:2929) ~[druid-1.0.23-SNAPSHOT.jar:1.0.23-SNAPSHOT]
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_execute(FilterEventAdapter.java:440) ~[druid-1.0.23-SNAPSHOT.jar:1.0.23-SNAPSHOT]
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:2929) ~[druid-1.0.23-SNAPSHOT.jar:1.0.23-SNAPSHOT]
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.execute(PreparedStatementProxyImpl.java:131) ~[druid-1.0.23-SNAPSHOT.jar:1.0.23-SNAPSHOT]
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:493) ~[druid-1.0.23-SNAPSHOT.jar:1.0.23-SNAPSHOT]
	at com.road.ddt.dao.impl.ProduceDaoImpl.updatePlayerOrder(ProduceDaoImpl.java:2171) [bin/:?]
	at com.road.ddt.bll.ProduceBussiness.updatePlayerOrder(ProduceBussiness.java:371) [classes/:?]
	at com.road.ddt.gameobjects.GamePlayer.addGpDirect(GamePlayer.java:4976) [bin/:?]
	at com.road.ddt.battle.command.PlayerAddGpDirectCmd.execute(PlayerAddGpDirectCmd.java:38) [bin/:?]
	at com.road.ddt.battle.BattleCmdWrapper.run(BattleCmdWrapper.java:48) [bin/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_80]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_80]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]

**Comment by wenshao** [comment]
这个跟druid无关吧

**Comment by RandyZ** [comment]
遇到同样的问题，sqlserver，有什么解决方案吗？
