### ISSUE TITLE
从数据库获取连接 长时间等待

### ISSUE THREAD

**Issue by hongNickName** [alibaba/druid#1425]
长时间未访问后，访问时从数据库获取连接时，执行isValidConnection长时间卡顿（15分钟）。

"nioEventLoopGroup-3-8" prio=10 tid=0x00007fcd00012800 nid=0x7d6f runnable [0x00007fcd6dbf3000]
   java.lang.Thread.State: RUNNABLE
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.read(SocketInputStream.java:152)
        at java.net.SocketInputStream.read(SocketInputStream.java:122)
        at oracle.net.ns.Packet.receive(Packet.java:282)
        at oracle.net.ns.DataPacket.receive(DataPacket.java:103)
        at oracle.net.ns.NetInputStream.getNextPacket(NetInputStream.java:230)
        at oracle.net.ns.NetInputStream.read(NetInputStream.java:175)
        at oracle.net.ns.NetInputStream.read(NetInputStream.java:100)
        at oracle.net.ns.NetInputStream.read(NetInputStream.java:85)
        at oracle.jdbc.driver.T4CSocketInputStreamWrapper.readNextPacket(T4CSocketInputStreamWrapper.java:122)
        at oracle.jdbc.driver.T4CSocketInputStreamWrapper.read(T4CSocketInputStreamWrapper.java:78)
        at oracle.jdbc.driver.T4CMAREngine.unmarshalUB1(T4CMAREngine.java:1179)
        at oracle.jdbc.driver.T4CMAREngine.unmarshalSB1(T4CMAREngine.java:1155)
        at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:279)
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:186)
        at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:521)
        at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:194)
        at oracle.jdbc.driver.T4CStatement.executeForDescribe(T4CStatement.java:853)
        at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1145)
        at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1259)
        at oracle.jdbc.driver.OracleStatement.executeQuery(OracleStatement.java:1469)
        - locked <0x000000068645c2a8> (a oracle.jdbc.driver.T4CConnection)
        at oracle.jdbc.driver.OracleStatementWrapper.executeQuery(OracleStatementWrapper.java:389)
        at com.alibaba.druid.pool.vendor.OracleValidConnectionChecker.isValidConnection(OracleValidConnectionChecker.java:88)
        at com.alibaba.druid.pool.DruidAbstractDataSource.testConnectionInternal(DruidAbstractDataSource.java:1252)
        at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1000)
        at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4544)
        at com.alibaba.druid.filter.stat.StatFilter.dataSource_getConnection(StatFilter.java:662)
        at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4540)
        at com.alibaba.druid.filter.FilterAdapter.dataSource_getConnection(FilterAdapter.java:2723)
        at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4540)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:938)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:930)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:102)
        at org.springframework.jdbc.datasource.lookup.AbstractRoutingDataSource.getConnection(AbstractRoutingDataSource.java:164)
        at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:204)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:427)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:276)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at com.bailian.datasource.DataSourceRouteInterceptor.invoke(DataSourceRouteInterceptor.java:44)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at com.bailian.core.framework.exception.ExceptionLog.invoke(ExceptionLog.java:40)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
        at com.bailian.member.service.impl.MemberInfoServiceImpl$$EnhancerBySpringCGLIB$$dab2897e.saveMemberMethod(<generated>)

**Comment by zhangjianweibj** [comment]
![image](https://cloud.githubusercontent.com/assets/18585129/18821316/a8595e5c-83d7-11e6-8816-feb68a86f7fa.png)
超时时间是可以设置的。另外你的物理连接是不是断开了

**Comment by zhangjianweibj** [comment]
![image](https://cloud.githubusercontent.com/assets/18585129/18821316/a8595e5c-83d7-11e6-8816-feb68a86f7fa.png)
超时时间是可以设置的。另外你的物理连接是不是断开了

**Comment by hongNickName** [comment]
ok,生产环境，频发，DB定位不了问题

**Comment by missvivia** [comment]
该问题有解决吗， 我现在也遇到同样的问题，同样也是使用oracle数据库，一模一样的问题在连接闲置一段时间后再次使用的时候做validation check的时候会线程永久卡死。 druid版本 1.0.18

**Comment by missvivia** [comment]
该问题有解决吗， 我现在也遇到同样的问题，同样也是使用oracle数据库，一模一样的问题在连接闲置一段时间后再次使用的时候做validation check的时候会线程永久卡死。 druid版本 1.0.18

**Comment by bwzheng2010** [comment]
我也遇到了，你们解决了吗？

**Comment by chinadeng** [comment]
我也碰到了，目前设置超时时间，具体为什么有这个原因 哪位知道？
