### ISSUE TITLE
WallFilter开启以后,不能正确处理Oracle分页SQL(包含fetch first ? rows only)

### ISSUE THREAD

**Issue by liusimon** [alibaba/druid#1448]
出错内容如下：
Caused by: java.sql.SQLException: sql injection violation, syntax error: error QUES : select customeren0_.id as id1_13_, customeren0_.VERSION as VERSION2_13_, customeren0_.CREATED_BY as CREATED_BY3_13_, customeren0_.CREATED_DATE as CREATED_DATE4_13_, customeren0_.LAST_MODIFIED_BY as LAST_MODIFIED_BY5_13_, customeren0_.LAST_MODIFIED_DATE as LAST_MODIFIED_DATE6_13_, customeren0_.APPROVAL_PHASE as APPROVAL_PHASE7_13_, customeren0_.APPROVAL_STATUS as APPROVAL_STATUS8_13_, customeren0_.accept_sms as accept_sms9_13_, customeren0_.ALTERNATE_MOBILE as ALTERNATE_MOBILE10_13_, customeren0_.GENDER as GENDER11_13_, customeren0_.IDENTIFICATION_NUMBER as IDENTIFICATION_NU12_13_, customeren0_.IDENTIFICATION_TYPE as IDENTIFICATION_TY13_13_, customeren0_.IS_ENABLED as IS_ENABLED14_13_, customeren0_.IS_EXPIRED as IS_EXPIRED15_13_, customeren0_.IS_LOCKED as IS_LOCKED16_13_, customeren0_.IS_PASSWORD_EXPIRED as IS_PASSWORD_EXPIR17_13_, customeren0_.LAST_LOGON_DATETIME as LAST_LOGON_DATETI18_13_, customeren0_.LAST_LOGON_IP as LAST_LOGON_IP19_13_, customeren0_.LAST_LOGON_MAC as LAST_LOGON_MAC20_13_, customeren0_.LOCK_REASON as LOCK_REASON21_13_, customeren0_.MOBILE as MOBILE22_13_, customeren0_.NAME as NAME23_13_, customeren0_.NAME_PINYIN as NAME_PINYIN24_13_, customeren0_.PASSWORD as PASSWORD25_13_, customeren0_.RECOMMENDED_ID as RECOMMENDED_ID26_13_, customeren0_.RISK_GRADE as RISK_GRADE27_13_, customeren0_.STAFF_ID as STAFF_ID28_13_, customeren0_.USER_NO as USER_NO29_13_, customeren0_.USER_STATUS as USER_STATUS30_13_, customeren0_.USER_TYPE as USER_TYPE31_13_ from CUSTOMER customeren0_ where (customeren0_.STAFF_ID=? or customeren0_.id=? or '0'=?) and  not (exists (select blackliste1_.IDENTIFICATION_NUMBER from BLACK_LIST blackliste1_ where customeren0_.IDENTIFICATION_NUMBER=blackliste1_.IDENTIFICATION_NUMBER and blackliste1_.IS_ENABLED=1)) fetch first ? rows only
	at com.alibaba.druid.wall.WallFilter.check(WallFilter.java:724)
	at com.alibaba.druid.wall.WallFilter.connection_prepareStatement(WallFilter.java:252)
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:448)
	at com.alibaba.druid.filter.FilterAdapter.connection_prepareStatement(FilterAdapter.java:928)
	at com.alibaba.druid.filter.FilterEventAdapter.connection_prepareStatement(FilterEventAdapter.java:122)
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:448)
	at com.alibaba.druid.filter.FilterAdapter.connection_prepareStatement(FilterAdapter.java:928)
	at com.alibaba.druid.filter.FilterEventAdapter.connection_prepareStatement(FilterEventAdapter.java:122)
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:448)
	at com.alibaba.druid.filter.FilterAdapter.connection_prepareStatement(FilterAdapter.java:928)
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:448)
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.__xr__43__prepareStatement(ConnectionProxyImpl.java:342)
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.prepareStatement(ConnectionProxyImpl.java)
	at com.alibaba.druid.pool.DruidPooledConnection.__xr__1__prepareStatement(DruidPooledConnection.java:331)
	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:146)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:172)
	... 183 common frames omitted
Caused by: com.alibaba.druid.sql.parser.ParserException: error QUES
	at com.alibaba.druid.sql.parser.SQLExprParser.name(SQLExprParser.java:974)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleExprParser.name(OracleExprParser.java:997)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseFetch(SQLStatementParser.java:2149)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleStatementParser.parseStatementList(OracleStatementParser.java:237)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:148)
	at com.alibaba.druid.wall.WallProvider.checkInternal(WallProvider.java:620)
	at com.alibaba.druid.wall.WallProvider.check(WallProvider.java:574)
	at com.alibaba.druid.wall.WallFilter.check(WallFilter.java:711)
	... 199 common frames omitted

**Comment by wenshao** [comment]
fetch first是DB2的语法吧

**Comment by liusimon** [comment]
本条SQL由Spring Data JPA的分页功能自动产生的，可以确定是Oracle支持的语法，测试环境是Oracle 12C。去掉WallFilter以后，该语句可以顺利执行。
fetch first ? rows only 是ANSI/ISO SQL:2008标准的语法，应该有不少厂商支持。

**Comment by liusimon** [comment]
一点补充资料：
FETCH FIRST clause
Since ISO SQL:2008 results limits can be specified as in the following example using the FETCH FIRST clause.

SELECT * FROM T FETCH FIRST 10 ROWS ONLY

This clause currently is supported by CA DATACOM/DB 11, IBM DB2, Sybase SQL Anywhere, PostgreSQL, EffiProz, H2, HSQLDB version 2.0, Microsoft SQL Server 2012, Oracle 12c and Mimer SQL.

Microsoft SQL Server 2014 requires more:

SELECT * FROM atable ORDER BY acolumn DESC OFFSET 0 ROWS FETCH FIRST 10 ROWS ONLY
