### ISSUE TITLE
下载源码后编译执行mvn install出现问题

### ISSUE THREAD

**Issue by shijiyu** [alibaba/druid#1477]
Exception in thread "main" java.lang.ExceptionInInitializerError
        at javax.crypto.KeyAgreement.getInstance(KeyAgreement.java:173)
        at sun.security.ssl.JsseJce.getKeyAgreement(JsseJce.java:285)
        at sun.security.ssl.JsseJce.isEcAvailable(JsseJce.java:198)
        at sun.security.ssl.CipherSuite$KeyExchange.isAvailable(CipherSuite.java
:372)
        at sun.security.ssl.CipherSuite.isAvailable(CipherSuite.java:190)
        at sun.security.ssl.SSLContextImpl.getApplicableCipherSuiteList(SSLConte
xtImpl.java:342)
        at sun.security.ssl.SSLContextImpl.getDefaultCipherSuiteList(SSLContextI
mpl.java:300)
        at sun.security.ssl.SSLSocketImpl.init(SSLSocketImpl.java:576)
        at sun.security.ssl.SSLSocketImpl.<init>(SSLSocketImpl.java:541)
        at sun.security.ssl.SSLSocketFactoryImpl.createSocket(SSLSocketFactoryIm
pl.java:109)
        at org.apache.maven.wagon.providers.http.httpclient.conn.ssl.SSLConnecti
onSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:263)
        at org.apache.maven.wagon.providers.http.httpclient.conn.ssl.SSLConnecti
onSocketFactory.connectSocket(SSLConnectionSocketFactory.java:254)
        at org.apache.maven.wagon.providers.http.httpclient.impl.conn.HttpClient
ConnectionOperator.connect(HttpClientConnectionOperator.java:123)
        at org.apache.maven.wagon.providers.http.httpclient.impl.conn.PoolingHtt
pClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:318)
        at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.MainC
lientExec.establishRoute(MainClientExec.java:363)
        at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.MainC
lientExec.execute(MainClientExec.java:219)
        at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.Proto
colExec.execute(ProtocolExec.java:195)
        at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.Retry
Exec.execute(RetryExec.java:86)
        at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.Redir
ectExec.execute(RedirectExec.java:108)
        at org.apache.maven.wagon.providers.http.httpclient.impl.client.Internal
HttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.maven.wagon.providers.http.httpclient.impl.client.Closeabl
eHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.execute
(AbstractHttpClientWagon.java:832)
        at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInp
utData(AbstractHttpClientWagon.java:983)
        at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInp
utData(AbstractHttpClientWagon.java:960)
        at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:11
6)
        at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
        at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
        at org.eclipse.aether.transport.wagon.WagonTransporter$GetTaskRunner.run
(WagonTransporter.java:560)
        at org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTran
sporter.java:427)
        at org.eclipse.aether.transport.wagon.WagonTransporter.get(WagonTranspor
ter.java:404)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRu
nner.runTask(BasicRepositoryConnector.java:447)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunne
r.run(BasicRepositoryConnector.java:350)
        at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(Runn
ableErrorForwarder.java:67)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExe
cutor.execute(BasicRepositoryConnector.java:581)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(Basic
RepositoryConnector.java:249)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownl
oads(DefaultArtifactResolver.java:520)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(Defa
ultArtifactResolver.java:421)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtif
acts(DefaultArtifactResolver.java:246)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtif
act(DefaultArtifactResolver.java:223)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.
loadPom(DefaultArtifactDescriptorReader.java:267)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.
readArtifactDescriptor(DefaultArtifactDescriptorReader.java:198)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDe
pendencies(DefaultDependencyCollector.java:202)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDepen
dencies(DefaultRepositorySystem.java:316)
        at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.re
solveInternal(DefaultPluginDependenciesResolver.java:202)
        at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.re
solve(DefaultPluginDependenciesResolver.java:149)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.resolveExt
ensionArtifacts(DefaultMavenPluginManager.java:908)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupExten
sionsRealm(DefaultMavenPluginManager.java:839)
        at org.apache.maven.project.DefaultProjectBuildingHelper.createProjectRe
alm(DefaultProjectBuildingHelper.java:196)
        at org.apache.maven.project.DefaultModelBuildingListener.buildExtensions
Assembled(DefaultModelBuildingListener.java:99)
        at org.apache.maven.model.building.ModelBuildingEventCatapult$1.fire(Mod
elBuildingEventCatapult.java:44)
        at org.apache.maven.model.building.DefaultModelBuilder.fireEvent(Default
ModelBuilder.java:1295)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultMode
lBuilder.java:441)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultMode
lBuilder.java:421)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBu
ilder.java:620)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBu
ilder.java:411)
        at org.apache.maven.graph.DefaultGraphBuilder.collectProjects(DefaultGra
phBuilder.java:419)
        at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor
(DefaultGraphBuilder.java:410)
        at org.apache.maven.graph.DefaultGraphBuilder.build(DefaultGraphBuilder.
java:83)
        at org.apache.maven.DefaultMaven.buildGraph(DefaultMaven.java:491)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:219)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Laun
cher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.jav
a:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(La
uncher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:
356)
Caused by: java.lang.SecurityException: Can not initialize cryptographic mechani
sm
        at javax.crypto.JceSecurity.<clinit>(JceSecurity.java:86)
        ... 73 more
Caused by: java.lang.SecurityException: Cannot locate policy or framework files!

        at javax.crypto.JceSecurity.setupJurisdictionPolicies(JceSecurity.java:2
54)
        at javax.crypto.JceSecurity.access$000(JceSecurity.java:48)
        at javax.crypto.JceSecurity$1.run(JceSecurity.java:78)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.crypto.JceSecurity.<clinit>(JceSecurity.java:76)
        ... 73 more

**Comment by lizongbo** [comment]
请使用JDK8最新版本。
