### ISSUE TITLE
missing dependency : commons-lang

### ISSUE THREAD

**Issue by ChinaXing** [alibaba/druid#1509]
如下，解析double类型列的时候，走到了这里，抛出找不到类，原因是druid的pom中未添加对commons-lang 的依赖：

```
10:32:03.031 [qtp1240412896-9485] ERROR -- com.youzan.rds.console.web.mvc.controller.WorkflowAction [ 51] --
java.lang.NoClassDefFoundError: org/apache/commons/lang/math/NumberUtils
        at com.alibaba.druid.sql.parser.Lexer.decimalValue(Lexer.java:1288) ~[druid-1.0.24.jar:1.0.24]
        at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:265) ~[druid-1.0.24.jar:1.0.24]
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.primary(MySqlExprParser.java:167) ~[druid-1.0.24.jar:1.0.24]
        at com.alibaba.druid.sql.parser.SQLExprParser.bitXor(SQLExprParser.java:152) ~[druid-1.0.24.jar:1.0.24]
        at com.alibaba.druid.sql.parser.SQLExprParser.multiplicative(SQLExprParser.java:189) ~[druid-1.0.24.jar:1.0.24]
        at com.alibaba.druid.sql.parser.SQLExprParser.additive(SQLExprParser.java:1263) ~[druid-1.0.24.jar:1.0.24]
        at com.alibaba.druid.sql.parser.SQLExprParser.shift(SQLExprParser.java:1291) ~[druid-1.0.24.jar:1.0.24]
        at com.alibaba.druid.sql.parser.SQLExprParser.bitAnd(SQLExprParser.java:1169) ~[druid-1.0.24.jar:1.0.24]
        at com.alibaba.druid.sql.parser.SQLExprParser.bitOr(SQLExprParser.java:1183) ~[druid-1.0.24.jar:1.0.24]
        at com.alibaba.druid.sql.parser.SQLExprParser.parseColumnRest(SQLExprParser.java:1679) ~[druid-1.0.24.jar:1.0.24]
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.parseColumnRest(MySqlExprParser.java:600) ~[druid-1.0.24.jar:1.0.24]
        at com.alibaba.druid.sql.parser.SQLExprParser.parseColumnRest(SQLExprParser.java:1687) ~[druid-1.0.24.jar:1.0.24]
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.parseColumnRest(MySqlExprParser.java:600) ~[druid-1.0.24.jar:1.0.24]
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.parseColumn(MySqlExprParser.java:539) ~[druid-1.0.24.jar:1.0.24]
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseAlterTableAddColumn(MySqlStatementParser.java:2788) ~[druid-1.0.24.jar:1.0.24]
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseAlterTable(MySqlStatementParser.java:2335) ~[druid-1.0.24.jar:1.0.24]
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseAlter(MySqlStatementParser.java:2298) ~[druid-1.0.24.jar:1.0.24]
        at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:220) ~[druid-1.0.24.jar:1.0.24]
        at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:2036) ~[druid-1.0.24.jar:1.0.24]
```

**Comment by wenshao** [comment]
问题已经修复，升级到最新版本就好了，比如1.0.26
http://repo1.maven.org/maven2/com/alibaba/druid/
https://github.com/alibaba/druid/releases
