### ISSUE TITLE
druid 对Mysql DIV函数的不支持

### ISSUE THREAD

**Issue by luowang** [alibaba/druid#1526]
<druid.version>1.0.27</druid.version>
原sql如下：
select COUNT(*) AS count, 
DATE_FORMAT(DATE(reg_time), '%Y-%m-%d') AS date, 
(HOUR(reg_time) DIV 2) as intervalTime 
FROM USER_RECOMMEND_INFO WHERE 1=1 
and reg_time >='2016-12-01 00:00:00' 
and reg_time <='2016-12-01 23:59:59'
group by DATE(reg_time),HOUR(reg_time) DIV 2
异常如下：
Caused by: java.sql.SQLException: sql injection violation, syntax error: syntax error, expect RPAREN, actual IDENTIFIER DIV : select COUNT(*) AS count, DATE_FORMAT(DATE(reg_time), '%Y-%m-%d') AS date , (HOUR(reg_time) DIV ?) as intervalTime FROM USER_RECOMMEND_INFO WHERE 1=1 and reg_time >=? and reg_time <=? group by DATE(reg_time),HOUR(reg_time) DIV ?
	at com.alibaba.druid.wall.WallFilter.check(WallFilter.java:725)
	at com.alibaba.druid.wall.WallFilter.connection_prepareStatement(WallFilter.java:253)
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:448)
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.prepareStatement(ConnectionProxyImpl.java:342)
	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:331)
	at org.springframework.jdbc.core.JdbcTemplate$SimplePreparedStatementCreator.createPreparedStatement(JdbcTemplate.java:1517)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:623)
	... 106 common frames omitted
Caused by: com.alibaba.druid.sql.parser.ParserException: syntax error, expect RPAREN, actual IDENTIFIER DIV
	at com.alibaba.druid.sql.parser.SQLExprParser.accept(SQLExprParser.java:1817)
	at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:213)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.primary(MySqlExprParser.java:166)
	at com.alibaba.druid.sql.parser.SQLExprParser.expr(SQLExprParser.java:94)
	at com.alibaba.druid.sql.parser.SQLExprParser.parseSelectItem(SQLExprParser.java:2128)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseSelectList(SQLSelectParser.java:374)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlSelectParser.query(MySqlSelectParser.java:152)
	at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:62)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseSelect(MySqlStatementParser.java:247)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:114)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:79)
	at com.alibaba.druid.wall.WallProvider.checkInternal(WallProvider.java:620)
	at com.alibaba.druid.wall.WallProvider.check(WallProvider.java:574)
	at com.alibaba.druid.wall.WallFilter.check(WallFilter.java:712)
	... 112 common frames omitted

**Comment by luowang** [comment]
@wenshao thx
