### ISSUE TITLE
weblogic 环境下 com.alibaba.druid.pool.DruidDataSource recycle SEVERE: recyle error

### ISSUE THREAD

**Issue by wenwutao** [alibaba/druid#1533]
java.sql.SQLRecoverableException: Closed Connection
	at oracle.jdbc.driver.PhysicalConnection.clearWarnings(PhysicalConnection.java:3410)
	at com.alibaba.druid.pool.DruidConnectionHolder.reset(DruidConnectionHolder.java:260)
	at com.alibaba.druid.pool.DruidDataSource.recycle(DruidDataSource.java:1716)
	at com.alibaba.druid.pool.DruidPooledConnection.recycle(DruidPooledConnection.java:305)
	at com.alibaba.druid.pool.DruidPooledConnection.syncClose(DruidPooledConnection.java:284)
	at com.alibaba.druid.pool.DruidPooledConnection.close(DruidPooledConnection.java:241)
	at weblogic.jdbc.wrapper.PooledConnection.close(PooledConnection.java:259)
	at weblogic.jdbc.common.internal.ConnectionEnv.destroyForFlush(ConnectionEnv.java:758)
	at weblogic.jdbc.common.internal.ConnectionEnv.destroy(ConnectionEnv.java:706)
	at weblogic.jdbc.common.internal.ConnectionEnv.destroy(ConnectionEnv.java:684)
	at weblogic.common.resourcepool.ResourcePoolImpl.destroyResource(ResourcePoolImpl.java:1909)
	at weblogic.common.resourcepool.ResourcePoolImpl.doShrink(ResourcePoolImpl.java:2002)
	at weblogic.common.resourcepool.ResourcePoolImpl.access$1800(ResourcePoolImpl.java:41)
	at weblogic.common.resourcepool.ResourcePoolImpl$ResourcePoolMaintanenceTask.timerExpired(ResourcePoolImpl.java:2850)
	at weblogic.timers.internal.TimerImpl.run(TimerImpl.java:304)
	at weblogic.work.SelfTuningWorkManagerImpl$WorkAdapterImpl.run(SelfTuningWorkManagerImpl.java:548)
	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:311)
	at weblogic.work.ExecuteThread.run(ExecuteThread.java:263)

**Comment by wenshao** [comment]
连接断了，log error，不影响使用
