### ISSUE TITLE
java.sql.SQLRecoverableException: IO Error: Broken pipe

### ISSUE THREAD

**Issue by thxhappiness** [alibaba/druid#1534]
2016-12-08 01:15:26 [ HSFBizProcessor-4-thread-99:37395050 ] - [com.alibaba.druid.util.JdbcUtils]- [ ERROR ] close connection error
java.sql.SQLRecoverableException: IO Error: Broken pipe
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:504)
	at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:3754)
	at com.alibaba.druid.filter.FilterChainImpl.connection_close(FilterChainImpl.java:169)
	at com.alibaba.druid.filter.FilterAdapter.connection_close(FilterAdapter.java:776)
	at com.alibaba.druid.filter.FilterChainImpl.connection_close(FilterChainImpl.java:165)
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.close(ConnectionProxyImpl.java:115)
	at com.alibaba.druid.util.JdbcUtils.close(JdbcUtils.java:82)
	at com.alibaba.druid.pool.DruidDataSource.discardConnection(DruidDataSource.java:967)
	at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:934)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4544)
	at com.alibaba.druid.filter.FilterAdapter.dataSource_getConnection(FilterAdapter.java:2724)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4540)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:880)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:872)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:97)
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:203)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:372)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:417)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:255)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	at com.sun.proxy.$Proxy42.selectAccountCountTotal(Unknown Source)
	at com.sinopay.paas.acc.service.api.impl.AccountSearchServiceImpl.queryAccountInfoPageList(AccountSearchServiceImpl.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.taobao.hsf.remoting.provider.ProviderProcessor.handleRequest0(ProviderProcessor.java:450)
	at com.taobao.hsf.remoting.provider.ProviderProcessor.handleRequest(ProviderProcessor.java:189)
	at com.taobao.hsf.remoting.server.RPCServerHandler.handleRequest(RPCServerHandler.java:42)
	at com.taobao.hsf.remoting.server.RPCServerHandler.handleRequest(RPCServerHandler.java:20)
	at com.taobao.hsf.remoting.netty.server.NettyServerHandler$HandlerRunnable.run(NettyServerHandler.java:122)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Broken pipe

**Comment by wenshao** [comment]
连接断了，只是log error，不影响使用

**Comment by plutogeek** [comment]
数据库连接池中已经被数据库断掉的连接再次连接请求会报错，呆连接池所有关闭连接被重试之后就自然正常了

**Comment by LUAgam** [comment]
然而启动不了tomcat
