### ISSUE TITLE
order by 后面不能用函数么

### ISSUE THREAD

**Issue by 845629143** [alibaba/druid#1541]
select *
from table
where level between 10-5 and 10+5
order by -ABS(10 - level) desc
limit 0,100

在druid里面会提示
com.alibaba.druid.sql.parser.ParserException: not support token:QUES
	at com.alibaba.druid.sql.parser.SQLExprParser.methodRest(SQLExprParser.java:691)
	at com.alibaba.druid.sql.parser.SQLExprParser.primaryRest(SQLExprParser.java:651)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.primaryRest(MySqlExprParser.java:480)
	at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:548)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.primary(MySqlExprParser.java:166)
	at com.alibaba.druid.sql.parser.SQLExprParser.expr(SQLExprParser.java:118)
	at com.alibaba.druid.sql.parser.SQLExprParser.parseSelectOrderByItem(SQLExprParser.java:979)
	at com.alibaba.druid.sql.parser.SQLExprParser.parseOrderBy(SQLExprParser.java:963)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlSelectParser.query(MySqlSelectParser.java:138)
	at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:60)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseSelect(MySqlStatementParser.java:195)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:145)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:121)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:116)
	at com.alibaba.druid.sql.SQLUtils.toStatementList(SQLUtils.java:174)
	at com.alibaba.druid.sql.SQLUtils.format(SQLUtils.java:187)

**Comment by wenshao** [comment]
什么版本啊，我测试了是可以的哈。。。

**Comment by 845629143** [comment]
1.0.12版本

**Comment by wenshao** [comment]
那我先关闭啦
