### ISSUE TITLE
关于sharding-jdbc方法删除问题

### ISSUE THREAD

**Issue by z589533** [alibaba/druid#1544]
java.lang.NoSuchMethodError: com.alibaba.druid.sql.ast.expr.SQLAggregateExpr.getOption()Lcom/alibaba/druid/sql/ast/expr/SQLAggregateExpr$Option;
at com.dangdang.ddframe.rdb.sharding.parser.visitor.basic.mysql.MySQLSelectVisitor.visit(MySQLSelectVisitor.java:110) ~[sharding-jdbc-core-1.4.0.jar:na]
at com.alibaba.druid.sql.ast.expr.SQLAggregateExpr.accept0(SQLAggregateExpr.java:98) ~[druid-1.0.16.jar:1.0.16]
at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:41) ~[druid-1.0.16.jar:1.0.16]
at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.visit(SQLASTOutputVisitor.java:803) ~[druid-1.0.16.jar:1.0.16]
at com.dangdang.ddframe.rdb.sharding.parser.visitor.basic.mysql.MySQLSelectVisitor.visit(MySQLSelectVisitor.java:92) ~[sharding-jdbc-core-1.4.0.jar:na]

为啥在1.0.12之后版本把SQLAggregateExpr方法这个给删除了，导致当当的分库框架出错了sharding-jdbc

**Comment by wenshao** [comment]
这个重构不当，很抱歉，已经修改为com.alibaba.druid.sql.ast.expr.SQLAggregateOption，这个不好改回去了，改回去会导致新的不兼容，能否让sharding-jdbc-core-1.4.0做修改。

**Comment by terrymanu** [comment]
druid和sharding-jdbc的解析代码不兼容，sharding-jdbc将在新版本（1.5.0）版本中抽离parser，做到与druid所有版本的兼容。请耐心等待。
温少可以close issue啦。

**Comment by zhangyy3** [comment]
啥时候出sharding-jdbc的1.5.0啊
