### ISSUE TITLE
init error

### ISSUE THREAD

**Issue by devpage** [alibaba/druid#1550]
通过属性设置 构造一个连接池，就报错了

`java.lang.NullPointerException
	at com.alibaba.druid.pool.DruidAbstractDataSource.getCompositeData(DruidAbstractDataSource.java:1610) ~[druid-1.0.27.jar:1.0.27]
	at Serializer_3.write1(Unknown Source) ~[?:?]
	at Serializer_3.write(Unknown Source) ~[?:?]
	at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:188) ~[fastjson-1.1.43.jar:?]
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:369) ~[fastjson-1.1.43.jar:?]
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:393) ~[fastjson-1.1.43.jar:?]
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:381) ~[fastjson-1.1.43.jar:?]
	at cn.mycompany.configure.mysql.MysqlFactory.load(MysqlFactory.java:54) [filesystem.jar:0.0.1-SNAPSHOT]
	at cn.mycompany.configure.mysql.MysqlFactory.getDataSourceByMysqlId(MysqlFactory.java:188) [filesystem.jar:0.0.1-SNAPSHOT]
	at cn.mycompany.configure.mybatis.SessionFactoryUtil.loadSessionFactory(SessionFactoryUtil.java:65) [filesystem.jar:0.0.1-SNAPSHOT]
	at cn.mycompany.configure.mybatis.SessionFactoryUtil.getSqlSession(SessionFactoryUtil.java:96) [filesystem.jar:0.0.1-SNAPSHOT]
	 
	at IceInternal.Incoming.invoke(Incoming.java:221) [ice-3.6.2.jar:?]
	at Ice.ConnectionI.invokeAll(ConnectionI.java:2536) [ice-3.6.2.jar:?]
	at Ice.ConnectionI.dispatch(ConnectionI.java:1145) [ice-3.6.2.jar:?]
	at Ice.ConnectionI.message(ConnectionI.java:1056) [ice-3.6.2.jar:?]
	at IceInternal.ThreadPool.run(ThreadPool.java:395) [ice-3.6.2.jar:?]
	at IceInternal.ThreadPool.access$300(ThreadPool.java:12) [ice-3.6.2.jar:?]
	at IceInternal.ThreadPool$EventHandlerThread.run(ThreadPool.java:832) [ice-3.6.2.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
`

**Comment by lizongbo** [comment]
请使用最新版验证
