### ISSUE TITLE
Oracle数据库表结构修改导致"违反协议"异常

### ISSUE THREAD

**Issue by kajelas** [alibaba/druid#1557]
我们在一张oracle的表中添加了几个允许为空的字段，活跃中的应用就开始报如下错误：

> 2016-12-22 14:47:05,263 - druid.sql.Statement [http-nio-8005-exec-7] ERROR druid.sql.Statement  com.alibaba.druid.filter.logging.Log4jFilter.statementLogError(Log4jFilter.java:152) - {conn-10016, pstmt-23381} execute error.   select * from TB_PAY_ORDER where ORDER_ID = ? for update   
java.sql.SQLException: 违反协议: [6, 7, 0]
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:464)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:192)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:207)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:1044)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1199)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1289)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3584)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3685)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1376)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:2931)
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_execute(FilterEventAdapter.java:440)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:2929)
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_execute(FilterEventAdapter.java:440)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:2929)
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.execute(PreparedStatementProxyImpl.java:131)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:493)
	at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeQuery(SqlExecutor.java:185)
	at com.netease.lottery.base.ibatis.LimitSqlExecutor.executeQuery(LimitSqlExecutor.java:60)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.sqlExecuteQuery(MappedStatement.java:221)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryWithCallback(MappedStatement.java:189)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryForObject(MappedStatement.java:120)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForObject(SqlMapExecutorDelegate.java:518)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForObject(SqlMapExecutorDelegate.java:493)
	at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.queryForObject(SqlMapSessionImpl.java:106)
	at org.springframework.orm.ibatis.SqlMapClientTemplate$1.doInSqlMapClient(SqlMapClientTemplate.java:273)
	at org.springframework.orm.ibatis.SqlMapClientTemplate.execute(SqlMapClientTemplate.java:203)
	at org.springframework.orm.ibatis.SqlMapClientTemplate.queryForObject(SqlMapClientTemplate.java:271)

而且，一开始报错的SQL都与这张增加了字段的表有关，后来无论什么SQL都开始报"违反协议"异常（但是中括号内的数字不一样）。

我们推测这个错误和Druid开启了PreparedStatementCache有关。但是请问这个错误的具体原因是什么？为什么跟这张表无关的SQL也会违反协议？另外我们开启了testWhileIdle选项，如果改成testOnBorrow，是不是也能避免这个问题？

**Comment by wenshao** [comment]
什么版本？

**Comment by kajelas** [comment]
1.0.25

**Comment by kajelas** [comment]
请问这个和 #1516 有关吗？

**Comment by pansw2** [comment]
J2EE交流QQ群129478078 ，两年以上J2EE开发经验者请进。新手勿进。

**Comment by kajelas** [comment]
请问这个问题有最新进展吗

**Comment by kajelas** [comment]
我们自己在测试环境下复现了这个问题，另外发现关闭PreparedStatementCache确实能消除违反协议的报错。

**Comment by kajelas** [comment]
后续我们又尝试把druid升级到了1.0.27版本，主要是考虑到这个版本的ps cache可以自动丢掉失败的ps。
但是实际使用中，虽然"违反协议"异常不再出现，但是却出现了新的"关闭的语句"异常：
![image](https://cloud.githubusercontent.com/assets/3959938/22054299/d00d6350-dd8f-11e6-945c-7c7a6238d8aa.png)

这个异常出现后会持续一段时间，然后自动修复。我们推测这跟testWhileIdle的配置有关。请问能不能在出现这类异常后，自动执行一下validateQuery的相关逻辑，做一下连接验证和重连？

**Comment by 66951735** [comment]
我最近也遇到了同样的问题，表新增了两个可以为空的字段后应用就报下边的错误：
[2017-01-19 10:15:22,199][183.202.0.33][noLogin] - [exception][com.netease.insurance.activity.zengxian.recommand.action.DidiCouponZengxianAction@ab5a29b][
### Error querying database.  Cause: java.sql.SQLException: OALL8 处于不一致状态
### The error may exist in ibatis/activity/insuranceTaikangActivity2.xml
### The error may involve InsuranceTaikangActivityAll.selectSpecifiedRegisters-Inline
### The error occurred while setting parameters
### SQL: SELECT * FROM TB_INSU_ACT_APLY    WHERE     ACT_ID=?      and    ACT_UNIQUE_KEY=?
### Cause: java.sql.SQLException: OALL8 处于不一致状态
; SQL []; OALL8 处于不一致状态; nested exception is java.sql.SQLException: OALL8 处于不一致状态]org.springframework.dao.DataAccessResourceFailureException: 
### Error querying database.  Cause: java.sql.SQLException: OALL8 处于不一致状态
### The error may exist in ibatis/activity/insuranceTaikangActivity2.xml
### The error may involve InsuranceTaikangActivityAll.selectSpecifiedRegisters-Inline
### The error occurred while setting parameters
### SQL: SELECT * FROM TB_INSU_ACT_APLY    WHERE     ACT_ID=?      and    ACT_UNIQUE_KEY=?
### Cause: java.sql.SQLException: OALL8 处于不一致状态
; SQL []; OALL8 处于不一致状态; nested exception is java.sql.SQLException: OALL8 处于不一致状态
        at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:251)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
        at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
        at com.sun.proxy.$Proxy44.selectOne(Unknown Source)
        at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:163)
        at com.netease.insurance.dao.BaseDao.selectOne(BaseDao.java:34)

版本是1.0.25， 升级到1.0.27能解决这个问题吗

**Comment by 66951735** [comment]
@wenshao

**Comment by kajelas** [comment]
@66951735 你暴露了，同事:)

**Comment by kajelas** [comment]
升级到1.0.27后，貌似和#1516是一个问题，能不能对于出错的连接除了做关闭语句的处理，再做一个关闭连接的处理：

if(stmt.isPooled() && holder.isPoolPreparedStatements() && stmt.exceptionCount == 0) {

            holder.getStatementPool().put(stmt.getPreparedStatementHolder());

            stmt.clearResultSet();
            holder.removeTrace(stmt);

           stmt.getPreparedStatementHolder().setFetchRowPeak(stmt.getFetchRowPeak());

            stmt.setClosed(true); // soft set close
        } else {
            try {
               //Connection behind the statement may be in invalid state, which will throw a SQLException.
                //In this case, the exception is desired to be properly handled to remove the unusable connection from the pool.

                stmt.closeInternal();
               //在这里对于某些异常直接调用close()
            } catch (SQLException ex) {
                this.handleException(ex);
                throw ex;
            } finally {
                holder.getDataSource().incrementClosedPreparedStatementCount();
            }
        }
    }

**Comment by kajelas** [comment]
请问这个问题有最新的进展吗？@wenshao
