### ISSUE TITLE
MYCAT 全局sequence 查询语句报错

### ISSUE THREAD

**Issue by jiangchengshi** [alibaba/druid#1559]
SQL语句：
INSERT INTO C_CART
        (cartId, customerId, productSubId, distProdSubId, storeId, num, msg, isDel, delTime, createtime)
        VALUES
        (next value for MYCATSEQ_CART, ?, ?, ?, ?, ?, ?, ?, ?, ?)

报错地方： next value for MYCATSEQ_CART

报错信息(部分)：
nested exception is java.sql.SQLException: sql injection violation, syntax error: syntax error : INSERT INTO C_CART
        (cartId, customerId, productSubId, distProdSubId, storeId, num, msg, isDel, delTime, createtime)
        VALUES
        (next value for MYCATSEQ_CART, ?, ?, ?, ?, ?, ?, ?, ?, ?)] with root cause
com.alibaba.druid.sql.parser.ParserException: syntax error
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseValueClause(MySqlStatementParser.java:2132) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseInsert(MySqlStatementParser.java:2022) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseInsert(MySqlStatementParser.java:193) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:199) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:148) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.wall.WallProvider.checkInternal(WallProvider.java:620) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.wall.WallProvider.check(WallProvider.java:574) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.wall.WallFilter.check(WallFilter.java:711) ~[druid-1.0.26.jar:1.0.26]

**Comment by jiangchengshi** [comment]
大神 帮忙看看问题啊

**Comment by jiangchengshi** [comment]
在 控制台 运行， 报错信息(部分)：
caught err: com.alibaba.druid.sql.parser.ParserException: syntax error, error in :' FOR MYCATSEQ_CART',expect UPDATE, actual IDENTIFIER MYCATSEQ_CART
        at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:239)
        at com.alibaba.druid.sql.parser.SQLParser.accept(SQLParser.java:247)
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlSelectParser.query(MySqlSelectParser.java:179)
        at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:62)
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseSelect(MySqlStatementParser.java:237)
        at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:183)
        at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:2065)
        at io.mycat.server.util.SchemaUtil.parseSchema(SchemaUtil.java:25)
        at io.mycat.server.ServerConnection.execute(ServerConnection.java:214)
        at io.mycat.server.handler.SelectHandler.handle(SelectHandler.java:105)
        at io.mycat.server.ServerQueryHandler.query(ServerQueryHandler.java:79)
        at io.mycat.net.FrontendConnection.query(FrontendConnection.java:317)
        at io.mycat.net.FrontendConnection.query(FrontendConnection.java:337)
        at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71)

**Comment by jiangchengshi** [comment]
if (lexer.token() == Token.FOR) {
            lexer.nextToken();
            accept(Token.UPDATE);

            queryBlock.setForUpdate(true);
            
            if (identifierEquals("NO_WAIT")) {
                lexer.nextToken();
                queryBlock.setNoWait(true);
            } else if (identifierEquals("WAIT")) {
                lexer.nextToken();
                SQLExpr waitTime = this.exprParser.primary();
                queryBlock.setWaitTime(waitTime);
            }
        }

**Comment by DuLerWeil** [comment]
插入语句格式都拼错了

**Comment by jiangchengshi** [comment]
亲， 哪里拼错了， 去掉FOR...，可以正常插入的。

**Comment by wenshao** [comment]
这样的语法有文档么？

**Comment by jiangchengshi** [comment]
http://www.mycat.org.cn/document/Mycat_V1.6.0.pdf

这是 MYCAT的 文档： 您可以搜索 MYCATSEQ 然后可以看到 sql语句 INSERT INTO ......


感谢！

江成世
TEL：15966936933

**Comment by wenshao** [comment]
这是mycat的语法而不是mysql的语法吧？

**Comment by jiangchengshi** [comment]
對啊。  next value for MYCATSEQ_XXX， mycat會到全局表中查找ID， 作爲ID使用。

江成世
TEL：15966936933

**Comment by wenshao** [comment]
你是mycat的开发么？为啥不用Oracle/SQLServer/DB2的语法？
```sql
select MYCATSEQ_XXX.NEXTVAL from t
select MYCATSEQ_XXX.CURRVAL from t
select MYCATSEQ_XXX.PREVVAL from t
```

**Comment by HashZhang** [comment]
对于MyCat，你可以这么写就插入了：
`INSERT INTO C_CART (customerId, productSubId, distProdSubId, storeId, num, msg, isDel, delTime, createtime) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?)`
你不用自己写next value for MYCATSEQ_CART，这个是MyCat帮你改写的
MyCat内部自动改写成：
`INSERT INTO C_CART
(cartId, customerId, productSubId, distProdSubId, storeId, num, msg, isDel, delTime, createtime)
VALUES
(next value for MYCATSEQ_CART, ?, ?, ?, ?, ?, ?, ?, ?, ?)`
这个是为了内部解析替换成为自生成ID而这么改写，不用走druid parser 解析

**Comment by jiangchengshi** [comment]
测试通过，谢谢！@HashZhang 不过暂时只有一个库。
