### ISSUE TITLE
oracle数据库表和列的注释语句无法执行，被 java.sql.SQLException: sql injection violation

### ISSUE THREAD

**Issue by jxf114208** [alibaba/druid#1570]
druid-1.0.26
oracle 10

`throws exception: java.sql.SQLException: sql injection violation, class com.alibaba.druid.sql.ast.statement.SQLCommentStatement not allow : comment on table jswoa1.con_attach is '附件表'
java.sql.SQLException: sql injection violation, class com.alibaba.druid.sql.ast.statement.SQLCommentStatement not allow : comment on table jswoa1.con_attach is '附件表'
	at com.alibaba.druid.wall.WallFilter.check(WallFilter.java:726)
	at com.alibaba.druid.wall.WallFilter.statement_executeUpdate(WallFilter.java:525)
	at com.alibaba.druid.filter.FilterChainImpl.statement_executeUpdate(FilterChainImpl.java:2375)
	at com.alibaba.druid.filter.FilterAdapter.statement_executeUpdate(FilterAdapter.java:2486)
	at com.alibaba.druid.filter.FilterEventAdapter.statement_executeUpdate(FilterEventAdapter.java:327)
	at com.alibaba.druid.filter.FilterChainImpl.statement_executeUpdate(FilterChainImpl.java:2375)
	at com.alibaba.druid.proxy.jdbc.StatementProxyImpl.executeUpdate(StatementProxyImpl.java:225)
	at com.alibaba.druid.pool.DruidPooledStatement.executeUpdate(DruidPooledStatement.java:164)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jdbcdslog.StatementLoggingHandler.invoke(StatementLoggingHandler.java:27)
	at com.sun.proxy.$Proxy84.executeUpdate(Unknown Source)
	at org.hibernate.tool.hbm2ddl.SchemaUpdate.execute(SchemaUpdate.java:252)
	at org.hibernate.tool.hbm2ddl.SchemaUpdate.execute(SchemaUpdate.java:203)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:522)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1859)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1930)`

**Comment by pansw2** [comment]
J2EE交流QQ群129478078 ，两年以上J2EE开发经验者请进。新手勿进。

**Comment by wenshao** [comment]
已经支持，请使用1.0.28版本

**Comment by chinaxy** [comment]
druid-1.0.29
oracle 11gr2

遇到同样的错误
sql injection violation, class com.alibaba.druid.sql.ast.statement.SQLCommentStatement not allow : comment on column OPERATOR.eid is 'ID'

java.sql.SQLException: sql injection violation, class com.alibaba.druid.sql.ast.statement.SQLCommentStatement not allow : comment on column OPERATOR.eid is 'ID'

	at com.alibaba.druid.wall.WallFilter.check(WallFilter.java:727)
	at com.alibaba.druid.wall.WallFilter.statement_execute(WallFilter.java:397)
	at com.alibaba.druid.filter.FilterChainImpl.statement_execute(FilterChainImpl.java:2487)
	at com.alibaba.druid.filter.FilterAdapter.statement_execute(FilterAdapter.java:2451)
	at com.alibaba.druid.filter.FilterEventAdapter.statement_execute(FilterEventAdapter.java:188)
	at com.alibaba.druid.filter.FilterChainImpl.statement_execute(FilterChainImpl.java:2487)
	at com.alibaba.druid.proxy.jdbc.StatementProxyImpl.execute(StatementProxyImpl.java:137)
	at com.alibaba.druid.pool.DruidPooledStatement.execute(DruidPooledStatement.java:418)

SQL为 
create table OPERATOR
(
  eid                NUMBER(19) not null,
  code               VARCHAR2(255),
  name               VARCHAR2(255),
  password           VARCHAR2(255),
  enable             NUMBER(1),
  organization_id    NUMBER(19),
  department_id      NUMBER(19),
  update_time        TIMESTAMP(6),
  update_operator_id NUMBER(19)
);

comment on table OPERATOR is '操作员';

comment on column OPERATOR.eid is 'ID';

comment on column OPERATOR.code is 'Code';

comment on column OPERATOR.name is '姓名';

comment on column OPERATOR.password is '密码';

comment on column OPERATOR.enable is '是否启用';

comment on column OPERATOR.organization_id is '组织机构ID';

comment on column OPERATOR.department_id is '部门ID';

comment on column OPERATOR.update_time is '更新时间';

comment on column OPERATOR.update_operator_id is '更新操作员ID';
