### ISSUE TITLE
连接db2数据库报错，找不到COM.ibm.db2.jdbc.app.DB2Driver

### ISSUE THREAD

**Issue by mamacmm** [alibaba/druid#1573]
使用的druid：1.0.27
使用的de2驱动：db2jcc-3.59.81.jar

启动报错：
`Caused by: java.lang.ClassNotFoundException: COM.ibm.db2.jdbc.app.DB2Driver
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1680)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1526)
	at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:320)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:169)
	at com.alibaba.druid.util.JdbcUtils.createDriver(JdbcUtils.java:568)
	... 57 more`

换成druid1.0.5的版本（以前用的），发现没有报错

查看db2jcc-3.59.81.jar里面没有COM.ibm.db2.jdbc.app.DB2Driver，只有com.ibm.db2.jcc.DB2Driver

**Comment by wenshao** [comment]
手动配置driverClassName吧

**Comment by mamacmm** [comment]
是的，手动配置了
