### ISSUE TITLE
org.springframework.transaction.CannotCreateTransactionException: Could not open JDBC Connection for transaction; nested exception is  com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 24109, active 92

### ISSUE THREAD

**Issue by ww198610** [alibaba/druid#1582]
org.springframework.transaction.CannotCreateTransactionException: Could not open JDBC Connection for transaction; nested exception is
 com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 24109, active 92
        at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:241)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManag
er.java:372)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport
.java:417)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java
:255)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:631)
        at com.dingcai.core.service.UserGroupService$$EnhancerByCGLIB$$6fd54d4.getUserGroupAuthConfigByGId(<generated>)
        at com.dingcai.front.controller.WebBbsPostController.bbsDetail(WebBbsPostController.java:673)
        at sun.reflect.GeneratedMethodAccessor312.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
 at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:219)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandle
rMethod.java:104)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandle
rAdapter.java:745)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAda
pter.java:686)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:80)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:925)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:856)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:936)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:827)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:812)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
 at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:861)
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:620)
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
        at java.lang.Thread.run(Thread.java:662)
Caused by: com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 24109, active 92
        at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1099)
        at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:916)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:896)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:886)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:96)
        at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:203)

**Comment by wenshao** [comment]
连接不够用了吧？

**Comment by ww198610** [comment]
我们用的rds数据库，连接数是4000，够用的，当时挂的时候，连接数是234

**Comment by ww198610** [comment]
<property name="initialSize" value="300"/>
        <property name="maxActive" value="1000"/>
        <property name="maxWait" value="20000"/>
        <property name="validationQuery" value="select 1"/>
        <property name="timeBetweenEvictionRunsMillis" value="60000" />
        <property name="minEvictableIdleTimeMillis" value="300000" />
        <property name="testWhileIdle" value="true" />
        <property name="testOnBorrow" value="false" />
        <property name="testOnReturn" value="false" />
这是我的配置参数，是不是哪里配置得不对，读写数据源，都是这样配置的

**Comment by ww198610** [comment]
initialSize   300
maxActive  1000
maxWait     20000
validationQuery   select 1
timeBetweenEvictionRunsMillis  60000
minEvictableIdleTimeMillis  300000
testWhileIdle true
testOnBorrow value="false
testOnReturn   false
poolPreparedStatements  false
maxPoolPreparedStatementPerConnectionSize   200

**Comment by hailianglone** [comment]
请问这个问题，楼主你解决了吗

**Comment by ivyduan122** [comment]
楼主解决问题了吗，遇到了同样的问题
