### ISSUE TITLE
druid栈溢出。

### ISSUE THREAD

**Issue by xiaojinde** [alibaba/druid#1618]
循环调用，栈溢出！
配置：
	      
	<bean id="sqlSessionFactory_oracle" class="org.mybatis.spring.SqlSessionFactoryBean">
		<property name="dataSource" ref="dataSourceDruid2" />

	
	
	<bean id="sqlSessionFactory_mysql" class="org.mybatis.spring.SqlSessionFactoryBean">
      <property name="dataSource" ref="dataSourceDruid1" />

问题：
2017-02-21 10:17:43,796 ERROR [STDERR] java.lang.StackOverflowError
2017-02-21 10:17:43,798 ERROR [STDERR]  at com.alibaba.druid.sql.parser.Lexer.nextToken(Lexer.java:338)
2017-02-21 10:17:43,798 ERROR [STDERR]  at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:355)
2017-02-21 10:17:43,798 ERROR [STDERR]  at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.primary(MySqlExprParser.java:167)
2017-02-21 10:17:43,798 ERROR [STDERR]  at com.alibaba.druid.sql.parser.SQLExprParser.expr(SQLExprParser.java:94)
2017-02-21 10:17:43,798 ERROR [STDERR]  at com.alibaba.druid.sql.parser.SQLSelectParser.expr(SQLSelectParser.java:527)
2017-02-21 10:17:43,798 ERROR [STDERR]  at com.alibaba.druid.sql.parser.SQLSelectParser.parseTableSourceQueryTableExpr(SQLSelectParser.java:431)
2017-02-21 10:17:43,798 ERROR [STDERR]  at com.alibaba.druid.sql.dialect.mysql.parser.MySqlSelectParser.parseTableSource(MySqlSelectParser.java:239)
2017-02-21 10:17:43,798 ERROR [STDERR]  at com.alibaba.druid.sql.dialect.mysql.parser.MySqlSelectParser.parseFrom(MySqlSelectParser.java:74)
2017-02-21 10:17:43,798 ERROR [STDERR]  at com.alibaba.druid.sql.dialect.mysql.parser.MySqlSelectParser.query(MySqlSelectParser.java:158)
2017-02-21 10:17:43,798 ERROR [STDERR]  at com.alibaba.druid.sql.parser.SQLSelectParser.queryRest(SQLSelectParser.java:103)
2017-02-21 10:17:43,798 ERROR [STDERR]  at com.alibaba.druid.sql.dialect.mysql.parser.MySqlSelectParser.query(MySqlSelectParser.java:201)
2017-02-21 10:17:43,798 ERROR [STDERR]  at com.alibaba.druid.sql.parser.SQLSelectParser.queryRest(SQLSelectParser.java:103)
2017-02-21 10:17:43,798 ERROR [STDERR]  at com.alibaba.druid.sql.dialect.mysql.parser.MySqlSelectParser.query(MySqlSelectParser.java:201)
2017-02-21 10:17:43,798 ERROR [STDERR]  at com.alibaba.druid.sql.parser.SQLSelectParser.queryRest(SQLSelectParser.java:103)
2017-02-21 10:17:43,798 ERROR [STDERR]  at com.alibaba.druid.sql.dialect.mysql.parser.MySqlSelectParser.query(MySqlSelectParser.java:201)
2017-02-21 10:17:43,798 ERROR [STDERR]  at com.alibaba.druid.sql.parser.SQLSelectParser.queryRest(SQLSelectParser.java:103)
2017-02-21 10:17:43,798 ERROR [STDERR]  at com.alibaba.druid.sql.dialect.mysql.parser.MySqlSelectParser.query(MySqlSelectParser.java:201)

**Comment by xiaojinde** [comment]
有大神帮看看吗？

**Comment by wenshao** [comment]
什么版本？怎样的一个SQL？

**Comment by lizongbo** [comment]
请使用最新版验证
