### ISSUE TITLE
druid 解析SQL语句出错

### ISSUE THREAD

**Issue by lveliu** [alibaba/druid#1624]
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'_key ROW_FORMAT = DEFAULT',expect IDENTIFIER, actual IDENTIFIER ROW_FORMAT
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:239)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:416)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:145)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:140)
	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:53)
	at com.alibaba.druid.filter.stat.StatFilter.mergeSql(StatFilter.java:145)
	at com.alibaba.druid.filter.stat.StatFilter.createSqlStat(StatFilter.java:630)
	at com.alibaba.druid.filter.stat.StatFilter.statementExecuteBatchBefore(StatFilter.java:360)
	at com.alibaba.druid.filter.FilterEventAdapter.statement_executeBatch(FilterEventAdapter.java:276)
	at com.alibaba.druid.filter.FilterChainImpl.statement_executeBatch(FilterChainImpl.java:2594)
	at com.alibaba.druid.proxy.jdbc.StatementProxyImpl.executeBatch(StatementProxyImpl.java:192)
	at com.alibaba.druid.pool.DruidPooledStatement.executeBatch(DruidPooledStatement.java:568)
	at com.zcareze.AutoUpStartUp.executeSqlScript(AutoUpStartUp.java:177)
	at com.zcareze.AutoUpStartUp.upSqlScript(AutoUpStartUp.java:118)
	at com.zcareze.AutoUpStartUp.main(AutoUpStartUp.java:95)

原始SQL语句为：ALTER TABLE app_key ROW_FORMAT = DEFAULT

**Comment by lveliu** [comment]
![qq 20170301155722](https://cloud.githubusercontent.com/assets/7334179/23450778/de79e2f0-fe97-11e6-9292-ecf31b178f1d.png)
调试信息

**Comment by lveliu** [comment]
对于修改表，创建存储过程，SQL解析都过不了。

**Comment by wenshao** [comment]
什么数据库？

**Comment by lveliu** [comment]
mysql

**Comment by wenshao** [comment]
能提供完整SQL么？

**Comment by wenshao** [comment]
druid什么版本？

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.6
问题已修复，请用新版本
