### ISSUE TITLE
java.sql.SQLException: Error retrieving next row

### ISSUE THREAD

**Issue by Danier-Evens** [alibaba/druid#1631]
我使用druid管理hive jdbc的连接池，然后查询一个sql大概返回的数据量有70W+，出现检索下一行异常，异常信息也不够详细，HiveQueryResultSet 388行刚好也就是异常抛出异常的代码，没法定位到具体HiveQueryResultSet next()方法那行代码出错。 请问下这个是不是跟量大有关系。下边是全部的异常栈信息。。

java.lang.NullPointerException
org.springframework.jdbc.UncategorizedSQLException: StatementCallback; uncategorized SQLException for SQL [sql 语句]; SQL state [null]; error code [0]; Error retrieving next row; nested exception is java.sql.SQLException: Error retrieving next row
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:84)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:416)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:471)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:481)
	at org.springframework.jdbc.core.JdbcTemplate.queryForList(JdbcTemplate.java:521)
	at com.*.report.dao.spark.HiveOrSparkDao.querySqlFormHive(HiveOrSparkDao.java:44)
	at com.*.report.Thread.DataExportThread.run(DataExportThread.java:47)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: Error retrieving next row
	at org.apache.hive.jdbc.HiveQueryResultSet.next(HiveQueryResultSet.java:388)
	at com.alibaba.druid.pool.DruidPooledResultSet.next(DruidPooledResultSet.java:69)
	at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:92)
	at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:60)
	at org.springframework.jdbc.core.JdbcTemplate$1QueryStatementCallback.doInStatement(JdbcTemplate.java:460)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:405)
	... 8 more
Caused by: java.lang.NullPointerException

**Comment by Jandaes** [comment]
`NullPointerException` 空指针异常、读取下一行数据没有`Error retrieving next row`

肯定是在遍历读取数据的时候没有非空判断吧

**Comment by Danier-Evens** [comment]
还不是，这个是源码里边抛出来的。 不是我代码里边的。。

**Comment by baolijn** [comment]
请问这个问题最后怎么解决的啊？

**Comment by wenshao** [comment]
这个看起来像是hive jdbc的异常，和druid无关

**Comment by WeiXiaoYang2022** [comment]
这个问题解决了吗
