### ISSUE TITLE
关于timestamp类型的一个问题

### ISSUE THREAD

**Issue by shangdiyisi** [alibaba/druid#1642]
我遇到一个timestamp的值，使用druid会报错。

	2017-03-12 02:59:21

	DruidDataSource dataSource;
	dataSource = new DruidDataSource();
	dataSource.setUrl("jdbc:mysql://xxx:3306/db_test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull");
	dataSource.setUsername("root");
	dataSource.setPassword("123321");
	dataSource.setValidationQuery("SELECT 1");
	dataSource.setTestOnBorrow(true);
	dataSource.setTestWhileIdle(true);
	Connection connection = dataSource.getConnection();
	Statement stmt = connection.createStatement();
	ResultSet rs = stmt.executeQuery("select * from tb_test");
	System.out.println("-------------------------------");
	while(rs.next()) {
		System.out.println(rs.getTimestamp(1));
	}
    System.out.println("-------------------------------");
	rs.close();
	stmt.close();
	connection.close();
	dataSource.close();

	Exception in thread "main" java.sql.SQLException: Error
		at com.alibaba.druid.pool.DruidDataSource.handleConnectionException(DruidDataSource.java:1318)
		at com.alibaba.druid.pool.DruidPooledConnection.handleException(DruidPooledConnection.java:132)
		at com.alibaba.druid.pool.DruidPooledStatement.checkException(DruidPooledStatement.java:65)
		at com.alibaba.druid.pool.DruidPooledResultSet.checkException(DruidPooledResultSet.java:55)
		at com.alibaba.druid.pool.DruidPooledResultSet.getTimestamp(DruidPooledResultSet.java:222)
		at MySqlTest.main(MySqlTest.java:30)
	Caused by: java.lang.IllegalArgumentException: HOUR_OF_DAY: 2 -> 3
		at java.util.GregorianCalendar.computeTime(GregorianCalendar.java:2829)
		at java.util.Calendar.updateTime(Calendar.java:3393)
		at java.util.Calendar.getTimeInMillis(Calendar.java:1782)
		at com.mysql.cj.jdbc.io.JdbcTimestampValueFactory.createFromTimestamp(JdbcTimestampValueFactory.java:92)
		at com.mysql.cj.jdbc.io.JdbcTimestampValueFactory.createFromTimestamp(JdbcTimestampValueFactory.java:39)
		at com.mysql.cj.core.io.BaseDecoratingValueFactory.createFromTimestamp(BaseDecoratingValueFactory.java:54)
		at com.mysql.cj.core.io.BaseDecoratingValueFactory.createFromTimestamp(BaseDecoratingValueFactory.java:54)
		at com.mysql.cj.core.io.MysqlTextValueDecoder.decodeTimestamp(MysqlTextValueDecoder.java:177)
		at com.mysql.cj.mysqla.result.AbstractResultsetRow.decodeAndCreateReturnValue(AbstractResultsetRow.java:67)
		at com.mysql.cj.mysqla.result.AbstractResultsetRow.getValueFromBytes(AbstractResultsetRow.java:225)
		at com.mysql.cj.mysqla.result.ByteArrayRow.getValue(ByteArrayRow.java:78)
		at com.mysql.cj.jdbc.result.ResultSetImpl.getNonStringValueFromRow(ResultSetImpl.java:658)
		at com.mysql.cj.jdbc.result.ResultSetImpl.getDateOrTimestampValueFromRow(ResultSetImpl.java:671)
		at com.mysql.cj.jdbc.result.ResultSetImpl.getTimestamp(ResultSetImpl.java:967)
		at com.alibaba.druid.pool.DruidPooledResultSet.getTimestamp(DruidPooledResultSet.java:220)
		... 1 more

**Comment by shangdiyisi** [comment]
不知道是不是和什么夏令时有关

**Comment by zhanyd** [comment]
关注。。。

**Comment by wenshao** [comment]
这个是mysql驱动的问题

**Comment by shangdiyisi** [comment]
@wenshao   请问该如何解决？

**Comment by shangdiyisi** [comment]
@zhanyd    &serverTimezone=Asia/Shanghai   十分感谢
