### ISSUE TITLE
Add full support for MySQL EXPLAIN

### ISSUE THREAD

**Issue by bobtiernay-okta** [alibaba/druid#1645]
Although there is some support for `EXPLAIN`, not all forms are supported:

https://dev.mysql.com/doc/refman/5.7/en/explain.html

For example, the following query does not parse:

```sql
explain extended select * from foo
```

```
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'explain extended select * from foo',expect IDENTIFIER, actual IDENTIFIER extended

	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:239)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:362)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:2065)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:2055)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseExplain(SQLStatementParser.java:2090)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:142)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:79)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:74)
	at com.alibaba.druid.sql.SQLUtils.toStatementList(SQLUtils.java:224)
```

**Comment by bobtiernay-okta** [comment]
I have something that is close to working. Will submit a PR when ready.

**Comment by wenshao** [comment]
Which version are you using?

**Comment by bobtiernay-okta** [comment]
Lastest I believe: `1.0.29`

Note that although the classes exist, the feature is far from complete.

**Comment by bobtiernay-okta** [comment]
@wenshao  Opened PR :)

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.4
问题已经修复，请使用新版本
