### ISSUE TITLE
线程一直runable，一直hang在socketRead0处

### ISSUE THREAD

**Issue by Yaccc** [alibaba/druid#1653]
```java
"Thread-4" daemon prio=10 tid=0x00007f2c6000c000 nid=0x2455 runnable [0x00007f2c55deb000]
   java.lang.Thread.State: RUNNABLE
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.read(SocketInputStream.java:152)
        at java.net.SocketInputStream.read(SocketInputStream.java:122)
        at com.mysql.jdbc.util.ReadAheadInputStream.fill(ReadAheadInputStream.java:100)
        at com.mysql.jdbc.util.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:143)
        at com.mysql.jdbc.util.ReadAheadInputStream.read(ReadAheadInputStream.java:173)
        - locked <0x00000007b09ea480> (a com.mysql.jdbc.util.ReadAheadInputStream)
        at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2954)
        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3375)
        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3365)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3805)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2547)
        - locked <0x00000007b09dcfb8> (a com.mysql.jdbc.JDBC4Connection)
        at com.mysql.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:4874)
        - locked <0x00000007b09dcfb8> (a com.mysql.jdbc.JDBC4Connection)
        at com.alibaba.druid.pool.DruidPooledConnection.setAutoCommit(DruidPooledConnection.java:694)
        at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:225)
```
以上是jstack得到的线程状态，多次dump都发现该线程一直不返回，也一直不超时！！！

**Comment by Yaccc** [comment]
解决了，原因是网络抖动，同时因为没有设置socketTimeout，导致一直卡在setAutoCommit时一直read数据

**Comment by xuxinpeng** [comment]
那个版本解决了这个问题呢

**Comment by Yaccc** [comment]
@xuxinpeng 不是bug，只需要合理的设置底层socket的超时时间即可

**Comment by tahongshen** [comment]
@Yaccc 请问具体怎么改呢？我是在getConnection的地方卡住了。

**Comment by Sunyelw** [comment]
有什么办法证明是网络抖动导致的而不是其他原因？
