### ISSUE TITLE
BTREE is not supported by druid

### ISSUE THREAD

**Issue by haifzhu** [alibaba/druid#1654]
when use druid SQLUtils.parseStatements to parse the sql "ALTER TABLE db_manage.zcy_gpcatalog_node_t ADD INDEX `index_code` USING BTREE (`code`);", the exceptions will be dumped out:
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'ode` USING BTREE (`code`);',expect LPAREN, actual IDENTIFIER USING
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:239)
	at com.alibaba.druid.sql.parser.SQLParser.accept(SQLParser.java:247)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseAlterTableAddIndex(SQLStatementParser.java:2120)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseAlterTable(MySqlStatementParser.java:2355)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseAlter(MySqlStatementParser.java:2316)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:152)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:79)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:74)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:430)

**Comment by wenshao** [comment]
已经支持，请使用新版本 https://github.com/alibaba/druid/releases/tag/1.0.30
