### ISSUE TITLE
Operation not allowed after ResultSet closed

### ISSUE THREAD

**Issue by yuankui** [alibaba/druid#1656]
我在用jdbc对数据库进行dump,可以理解就是 `select * from table1 limit 100 where id > xxx`,不断的从数据库批量取数据

连接池管理用的druid(这也许是个错),然后不知道为什么,在线上跑一段时间就会报

```
java.sql.SQLException: Operation not allowed after ResultSet closed
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1084)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:973)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:918)
	at com.mysql.jdbc.ResultSetImpl.checkClosed(ResultSetImpl.java:799)
	at com.mysql.jdbc.ResultSetImpl.checkRowPos(ResultSetImpl.java:847)
	at com.mysql.jdbc.ResultSetImpl.getObject(ResultSetImpl.java:4877)
	at com.alibaba.druid.pool.DruidPooledResultSet.getObject(DruidPooledResultSet.java:439)
```

刚开始怀疑是mysql JDBC driver的问题
查了很多资料,最后发现一个人跟我情况类似,下面有个回答说,你是不是用了dbcp?
我后来想想,我也是用了druid来做连接池.

然后我后来弃用了druid,错误果然就没有报了.

所以我怀疑,druid是不是在我不期望的情况下关闭了我的数据库连接?

以下是我的druid配置

```
 DruidDataSource dataSource = new DruidDataSource();
    
    dataSource.setUrl(url);

    // 设置属性
    dataSource.setMaxActive(2);
    dataSource.setInitialSize(1);
    dataSource.setMaxWait(5000);
    dataSource.setMinEvictableIdleTimeMillis(30000);
    dataSource.setMaxEvictableIdleTimeMillis(300000);
    dataSource.setPoolPreparedStatements(true);
    dataSource.setTestWhileIdle(true);
    dataSource.setTestOnBorrow(false);
    dataSource.setTestOnReturn(false);
    dataSource.setPhyTimeoutMillis(1800000);
    dataSource.setRemoveAbandoned(true);
    dataSource.setRemoveAbandonedTimeout(180);
    dataSource.setValidationQuery("select 1");
    dataSource.setValidationQueryTimeout(1);
    dataSource.setTimeBetweenEvictionRunsMillis(10000);
    dataSource.setDefaultAutoCommit(true);
    dataSource.setConnectionProperties("connectTimeout=1000;socketTimeout=3000");
```

**Comment by wenshao** [comment]
为什么要在关闭的ResultSet对象上做操作？

**Comment by yuankui** [comment]
我没有手动关闭,我一直在next()取数据,取着取着就被关闭了.
不太清楚是不是druid关闭的. 线下问题复现不了,线上数据量大,持续时间长的时候就会出现这种错误.

**Comment by magicbest** [comment]
我也遇到了相同的情况，一次获取大量数据（大约一分钟后返回），时间长了就报相同的错。

**Comment by juneryo** [comment]
我这里也遇到了类似的问题

![err](https://user-images.githubusercontent.com/4101515/38594060-2de89bfa-3d77-11e8-9a66-fabb29aeb459.png)

看上去是因为用到了`Log4j2`的`AsyncLogger`的原因

**Comment by zhouguanglong1** [comment]
dataSource.setRemoveAbandoned(true);
dataSource.setRemoveAbandonedTimeout(180);
问题出在这两个属性的设置

**Comment by lione0** [comment]
> 我没有手动关闭,我一直在next()取数据,取着取着就被关闭了.
> 不太清楚是不是druid关闭的. 线下问题复现不了,线上数据量大,持续时间长的时候就会出现这种错误.

请问最后如何解决的

**Comment by yuankui** [comment]
> dataSource.setRemoveAbandoned(true);
> dataSource.setRemoveAbandonedTimeout(180);
> 问题出在这两个属性的设置

@lione0 试试这个

**Comment by yangmengmeng01** [comment]
使用mysql, 到底怎么解决的啊？
