### ISSUE TITLE
1.0.29版本在开启WallFilter后，以下Oralce语句无法正常通过

### ISSUE THREAD

**Issue by digitalsonic** [alibaba/druid#1658]
`SELECT ?||'ABC' FROM DUAL`这条语句在1.0.27上是能通过校验的，但是到了1.0.29上就会报以下异常：
```
com.alibaba.druid.sql.parser.ParserException: ERROR. token : QUESBAR, pos : 10
	at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:600) ~[druid-1.0.29.jar:1.0.29]
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleExprParser.primary(OracleExprParser.java:465) ~[druid-1.0.29.jar:1.0.29]
	at com.alibaba.druid.sql.parser.SQLExprParser.expr(SQLExprParser.java:85) ~[druid-1.0.29.jar:1.0.29]
	at com.alibaba.druid.sql.parser.SQLExprParser.parseSelectItem(SQLExprParser.java:2166) ~[druid-1.0.29.jar:1.0.29]
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseSelectList(SQLSelectParser.java:373) ~[druid-1.0.29.jar:1.0.29]
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.query(OracleSelectParser.java:267) ~[druid-1.0.29.jar:1.0.29]
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.select(OracleSelectParser.java:81) ~[druid-1.0.29.jar:1.0.29]
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleStatementParser.parseStatementList(OracleStatementParser.java:131) ~[druid-1.0.29.jar:1.0.29]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:79) ~[druid-1.0.29.jar:1.0.29]
```
我试了一下，加个空格就能通过校验，改为`SELECT ? ||'ABC' FROM DUAL`，避开了QUESBAR(`?|`)。

**Comment by wenshao** [comment]
已经支持，请使用新版本 https://github.com/alibaba/druid/releases/tag/1.0.30
