### ISSUE TITLE
解析修改表列名SQL失败

### ISSUE THREAD

**Issue by melin** [alibaba/druid#1667]
example： alter table sale_detail change column old_col_name rename to new_col_name;

val parser = OdpsStatementParser(sql)
val stmt = parser.parseStatement()

异常信息：
```java
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'name rename to new_col_name;',expect COMMENT, actual IDENTIFIER rename
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:239)
	at com.alibaba.druid.sql.parser.SQLParser.accept(SQLParser.java:247)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseAlter(SQLStatementParser.java:888)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:152)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:2065)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:2055)
```

**Comment by melin** [comment]
同时修改列名及列注释 解析也失败：
    ALTER TABLE table_name CHANGE COLUMN old_col_name new_col_name column_type COMMENT column_comment;

**Comment by wenshao** [comment]
已经支持，请使用新版本 https://github.com/alibaba/druid/releases/tag/1.0.30
