### ISSUE TITLE
sql injection violation, syntax error: error QUES; occurs while dynamically creating table with self-define columns.

### ISSUE THREAD

**Issue by will-v-king** [alibaba/druid#1671]
the **mybatisMapper**.xml is:

```
<mapper namespace="...">
....   
 <sql id="sqlInfo4CreateTable">
        (
            <choose>
                <when test="baseInfo.tableInfo != null and baseInfo.tableInfo != ''">
                    ${baseInfo.tableInfo},
                </when>
                <otherwise>
                </otherwise>
            </choose>
            `last_update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
        )
    </sql>
    <sql id="sql4CreateTable">
        CREATE TABLE IF NOT EXISTS
        <include refid="template.sqlTableName4All"/>
        <include refid="template.sqlInfo4CreateTable"/>
        ENGINE=InnoDB DEFAULT CHARSET=utf8
    </sql>
.......
</mapper>
```

**debug**:
org.springframework.jdbc.UncategorizedSQLException: 
\### Error querying database.  Cause: java.sql.SQLException: sql injection violation, syntax error: error QUES : CREATE TABLE IF NOT EXISTS
         
         
                log_20170328
             
     
         
        (
             
                    ?,
                 
            `last_update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
        )
     
        ENGINE=InnoDB DEFAULT CHARSET=utf8

Caused by: java.sql.SQLException: sql injection violation, syntax error: error QUES : CREATE TABLE IF NOT EXISTS
         
         
                log_20170328
             
     
         
        (
             
                    ?,
                 
            `last_update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
        )
     
        ENGINE=InnoDB DEFAULT CHARSET=utf8
	at com.alibaba.druid.wall.WallFilter.check(WallFilter.java:725)
	at com.alibaba.druid.wall.WallFilter.connection_prepareStatement(WallFilter.java:253)
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:448)
	at com.alibaba.druid.filter.FilterAdapter.connection_prepareStatement(FilterAdapter.java:928)
	at com.alibaba.druid.filter.FilterEventAdapter.connection_prepareStatement(FilterEventAdapter.java:122)
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:448)
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.prepareStatement(ConnectionProxyImpl.java:342)
	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:346)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.instantiateStatement(PreparedStatementHandler.java:79)
	at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:88)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.prepare(RoutingStatementHandler.java:58)
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:76)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:61)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:303)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:154)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:96)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:82)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:120)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:386)
	... 61 more
Caused by: com.alibaba.druid.sql.parser.ParserException: error QUES
	at com.alibaba.druid.sql.parser.SQLExprParser.name(SQLExprParser.java:1002)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.parseColumn(MySqlExprParser.java:541)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlCreateTableParser.parseCrateTable(MySqlCreateTableParser.java:170)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseCreate(MySqlStatementParser.java:304)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:125)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:79)
	at com.alibaba.druid.wall.WallProvider.checkInternal(WallProvider.java:620)
	at com.alibaba.druid.wall.WallProvider.check(WallProvider.java:574)
	at com.alibaba.druid.wall.WallFilter.check(WallFilter.java:712)
	... 84 more

**Comment by will-v-king** [comment]
my fault
