### ISSUE TITLE
Error occurs when parse sql "create table tb1(select * from tb2)"

### ISSUE THREAD

**Issue by haifzhu** [alibaba/druid#1675]
when use druid to parse the sql "create table tb1(select * from tb2)", exception will be dumped out:
com.alibaba.druid.sql.parser.ParserException: error SELECT
	at com.alibaba.druid.sql.parser.SQLExprParser.name(SQLExprParser.java:1002)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.parseColumn(MySqlExprParser.java:541)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlCreateTableParser.parseCrateTable(MySqlCreateTableParser.java:170)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseCreate(MySqlStatementParser.java:352)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:125)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:79)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:74)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:430)

**Comment by wenshao** [comment]
少了个as吧

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.4
问题已经修复，请使用新版本
