### ISSUE TITLE
注入失败select top 1 (CAST(OriganID AS VARCHAR(20)) + ',' + MobilePhoneUrl)

### ISSUE THREAD

**Issue by LEEay** [alibaba/druid#1678]
com.alibaba.druid.sql.parser.ParserException: not support token:CAST
        at com.alibaba.druid.sql.parser.SQLExprParser.methodRest(SQLExprParser.java:834)
        at com.alibaba.druid.sql.parser.SQLExprParser.primaryRest(SQLExprParser.java:771)
        at com.alibaba.druid.sql.dialect.sqlserver.parser.SQLServerExprParser.primaryRest(SQLServerExprParser.java:74)
        at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:603)
        at com.alibaba.druid.sql.dialect.sqlserver.parser.SQLServerExprParser.primary(SQLServerExprParser.java:62)
        at com.alibaba.druid.sql.dialect.sqlserver.parser.SQLServerExprParser.parseTop(SQLServerExprParser.java:128)
        at com.alibaba.druid.sql.dialect.sqlserver.parser.SQLServerSelectParser.query(SQLServerSelectParser.java:147)
        at com.alibaba.druid.sql.dialect.sqlserver.parser.SQLServerSelectParser.select(SQLServerSelectParser.java:48)
        at com.alibaba.druid.sql.parser.SQLStatementParser.parseSelect(SQLStatementParser.java:1831)
        at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:114)
        at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:79)
        at com.alibaba.druid.wall.WallProvider.checkInternal(WallProvider.java:620)
        at com.alibaba.druid.wall.WallProvider.check(WallProvider.java:574)
        at com.alibaba.druid.wall.WallFilter.check(WallFilter.java:712)

**Comment by wenshao** [comment]
什么场景下出现的？

**Comment by wenshao** [comment]
能提供完整的sql么？

**Comment by LEEay** [comment]
环境是spring-boot 数据库是sqlserver 后面直接跟表名就行，就是要把两列合并一下

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.4
问题已经修复，请使用新版本
