### ISSUE TITLE
active连接数小于max， 获取连接超时， 请问是怎么一回事

### ISSUE THREAD

**Issue by GodzillaHua** [alibaba/druid#1687]
数据库：mysql
jdk：1.7.0_75
druid:1.0.22

应用从cache中取数据， cache是使用google的guava， cache内容从数据库中取出来的
使用的orm是mybatis， review了代码，也没有程序去获取connection的情况

### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 60000, **active 2, maxActive 50**
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
        at com.service.impl.CourseServiceImpl.selectCourseFeaturesByCourseId(CourseServiceImpl.java:233)
        at com.service.mapi.impl.CourseForAppServiceImpl.detail(CourseForAppServiceImpl.java:395)
        at com.alibaba.dubbo.common.bytecode.Wrapper16.invokeMethod(Wrapper16.java)
        at com.alibaba.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:46)
        at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:72)
        at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53)
        at com.alibaba.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:64)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
        at com.alibaba.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:42)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
        at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)

**Comment by zxdmrg** [comment]
how do you resolve it

**Comment by VEMTK** [comment]
能问下怎么解决的了？

**Comment by wenshao** [comment]
什么数据库？是不是数据负荷很高，无法建立连接

**Comment by lp8608** [comment]
@GodzillaHua  这个问题有解决吗？

**Comment by linfenliang** [comment]
我也遇到了
`Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 119099, active 57, maxActive 300
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80)
	at org.mybatis.spring.transaction.SpringManagedTransaction.openConnection(SpringManagedTransaction.java:82)
	at org.mybatis.spring.transaction.SpringManagedTransaction.getConnection(SpringManagedTransaction.java:68)
	at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:337)
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:84)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:325)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	... 97 common frames omitted`

并发量比较大的时候出现的问题，数据库最大IOPS为5K，实际使用2.8K左右，每秒查询量在3K左右出现的问题

**Comment by HelodieJaqueline** [comment]
我这边线上的服务也是这种情况:Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 10000, active 4, maxActive 500, creating 1, runningSqlCount 3 : update
数据库连接池里面只有个位数的连接数,经常性的报上面的错。下面是配置
    druid:
         initial-size: 50
         max-active: 500
         min-idle: 200
         max-wait: 10000
         validation-query: SELECT 'x'
         test-on-borrow: false
         test-on-return: false
         test-while-idle: true

**Comment by 2129zxl** [comment]
请问有解决吗？1.0.9在高并发下同样的问题

**Comment by yzpnet** [comment]
为啥关闭了

**Comment by Jawf** [comment]
1.0.x是2016的版本，2017年closed，推测2017年的版本已经修复，换新版吧~~

**Comment by localhost845** [comment]
最新版也是这个问题

**Comment by liuweiwilliam** [comment]
请问下是怎么解决的呀
