### ISSUE TITLE
tomcat关闭时出警告

### ISSUE THREAD

**Issue by zqs125** [alibaba/druid#1699]
关闭tomcat时报警告，spring+mybatis+mysql+druid，版本都是目前的最新版，druid的spring配置按wiki里的配置写的，警告如下：
24-Apr-2017 01:19:37.689 警告 [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesJdbc The web application [ROOT] registered the JDBC driver [com.alibaba.druid.proxy.DruidDriver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
24-Apr-2017 01:19:37.691 警告 [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesJdbc The web application [ROOT] registered the JDBC driver [com.mysql.cj.jdbc.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
有什么解决方法吗？

**Comment by HiAscend** [comment]
我也遇到了相同的问题，请问你解决了么？

**Comment by HiAscend** [comment]
经过摸索，我解决了上面的警告。
对于第二个警告，我把pom.xml中的JDBC  修改为provided，然后再tomcat的./lib/下增加对应的jar。
 <dependency>
                <groupId>mysql</groupId>
                <artifactId>mysql-connector-java</artifactId>
                <version>${mysql-connector-java.version}</version>
                <scope>provided</scope>
            </dependency>
对于第一个警告，我的解决方案是：实现ServletContextListener,然后再contextDestroyed()方法中添加如下代码：
 Enumeration<Driver> drivers = DriverManager.getDrivers();
        while (drivers.hasMoreElements()) {
            Driver driver = drivers.nextElement();
            try {
                DriverManager.deregisterDriver(driver);
                logger.info(String.format("deregistering jdbc driver: %s", driver));
            } catch (SQLException e) {
                e.printStackTrace();
                logger.error(String.format("deregistering jdbc driver: %s", driver));
            }
        }
最后在web.xml中注册自己的监听器，问题解决。

**Comment by sunmaolin** [comment]
12-Aug-2017 10:12:19.371 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal One or more Filters failed to start. Full details will be found in the appropriate container log file
12-Aug-2017 10:12:19.371 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal Context [] startup failed due to previous errors
12-Aug-2017 10:12:20.932 WARNING [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesJdbc The web application [ROOT] registered the JDBC driver [com.alibaba.druid.proxy.DruidDriver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
12-Aug-2017 10:12:20.933 WARNING [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesJdbc The web application [ROOT] registered the JDBC driver [com.mysql.jdbc.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
12-Aug-2017 10:12:20.934 WARNING [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appears to have started a thread named [Abandoned connection cleanup thread] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
 com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:64)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 java.lang.Thread.run(Thread.java:745)
12-Aug-2017 10:12:20.980 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio2-80"]
12-Aug-2017 10:12:20.984 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["https-jsse-nio2-443"]
12-Aug-2017 10:12:20.985 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
12-Aug-2017 10:12:20.992 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 32908 ms
12-Aug-2017 10:12:22.551 INFO [Abandoned connection cleanup thread] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load []. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
 java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load []. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1289)
	at org.apache.catalina.loader.WebappClassLoaderBase.getResource(WebappClassLoaderBase.java:972)
	at com.mysql.jdbc.AbandonedConnectionCleanupThread.checkContextClassLoaders(AbandonedConnectionCleanupThread.java:90)
	at com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by sunmaolin** [comment]
shiroFilterFactoryBean.setFilters设置的Filter使用了bean注入导致在tomcat中启动失败

**Comment by microhuang** [comment]
#### 同问

```
2017-12-01 14:28:17,666 INFO  [http-nio-8080-exec-6] pool.DruidDataSource (DruidDataSource.java:1712)          - {dataSource-1} closed
01-Dec-2017 14:28:17.674 警告 [http-nio-8080-exec-6] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesJdbc The web application [ROOT] registered the JDBC driver [com.alibaba.druid.proxy.DruidDriver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
01-Dec-2017 14:28:17.674 警告 [http-nio-8080-exec-6] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesJdbc The web application [ROOT] registered the JDBC driver [com.mysql.jdbc.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
01-Dec-2017 14:28:17.675 警告 [http-nio-8080-exec-6] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appears to have started a thread named [Abandoned connection cleanup thread] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
 com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:64)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 java.lang.Thread.run(Thread.java:748)
01-Dec-2017 14:28:18.183 信息 [http-nio-8080-exec-6] org.apache.catalina.startup.HostConfig.undeploy Undeploying context []
```

**Comment by microhuang** [comment]
@HiAscend 可以分享一下你的解决办法吗

**Comment by lichong2** [comment]
@microhuang 您好，请问一下，您这个问题解决了吗，能分享一下解决的办法么

**Comment by Xanthuim** [comment]
> 经过摸索，我解决了上面的警告。
> 对于第二个警告，我把pom.xml中的JDBC 修改为provided，然后再tomcat的./lib/下增加对应的jar。
> 对于第一个警告，我的解决方案是：实现ServletContextListener,然后再contextDestroyed()方法中添加如下代码：
> Enumeration drivers = DriverManager.getDrivers();
> while (drivers.hasMoreElements()) {
> Driver driver = drivers.nextElement();
> try {
> DriverManager.deregisterDriver(driver);
> logger.info(String.format("deregistering jdbc driver: %s", driver));
> } catch (SQLException e) {
> e.printStackTrace();
> logger.error(String.format("deregistering jdbc driver: %s", driver));
> }
> }
> 最后在web.xml中注册自己的监听器，问题解决。

为什么阿里的专家（@wenshao）说这是tomcat误报？#502

**Comment by xieguanliang** [comment]
昨晚我也遇到了这个问题，然后查看了Tomcat源码之后，仔细查阅之后，确认是属于Tomcat的警告而已，但是不能说是误报！
问题1：放在Tomcat Lib 中的JDBC驱动却没有这个警告！
答： 下面这段源码来自org.apache.catalina.loader.WebappClassLoaderBase
 ` 
private final void clearReferencesJdbc() {
     ..........
        try (InputStream is = getResourceAsStream(
               .........
            List<String> driverNames = (List<String>) obj.getClass().getMethod(
                    "clearJdbcDriverRegistrations").invoke(obj);
            for (String name : driverNames) {
                // Tomcat 帮助WebApp 反注册JDBC的驱动，所以会发出警告。谁注册的谁就该应该负责，就应该注销掉！本来就应该应用程序自身去反注册 JDBC的驱动！WebApp的类加载器是ParallelWebappClassLoader，而且此类的作用只是针对WebApp防止内存泄漏的！
                log.warn(sm.getString("webappClassLoader.clearJdbc",
                        getContextName(), name));
            }
        } catch (Exception e) {
            // So many things to go wrong above...
            Throwable t = ExceptionUtils.unwrapInvocationTargetException(e);
            ExceptionUtils.handleThrowable(t);
            log.warn(sm.getString(
                    "webappClassLoader.jdbcRemoveFailed", getContextName()), t);
        }
    }`
为什么放在Tomcat Lib下就没有呢，因为放在Tomcat Lib中的话，他们的类加载是Common加载器.Common加载器卸载JDBC驱动实现，跟WebApp卸载JDBC实现不一样的！
