### ISSUE TITLE
whether the parser can support delimiter ?

### ISSUE THREAD

**Issue by xiaoma20082008** [alibaba/druid#1700]
I'm using the 1.0.29 version of druid.
I used the SQLUtils like this:
```java
String sql = "delimiter // ;\n" + "update tb set a = 'a' //";
List<SQLStatement> statements = SQLUtils.parseStatements(sql, JdbcUtils.MYSQL);
```
and it occurred some error like this:
```java
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'delimiter // ;
update tb set a',expect IDENTIFIER, actual IDENTIFIER delimiter
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:239)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:362)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:79)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:74)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:430)
```

**Comment by wenshao** [comment]
Is this legal SQL?

**Comment by xiaoma20082008** [comment]
![Uploading mysql delimite

**Comment by xiaoma20082008** [comment]
I use the mysql client and it worked well

![mysql delimiter](https://cloud.githubusercontent.com/assets/10076393/25472073/4f230f86-2b5c-11e7-9ab7-0e3ac0f73ade.png)
