### ISSUE TITLE
java.sql.SQLRecoverableException: 关闭的语句

### ISSUE THREAD

**Issue by qiufeng6407** [alibaba/druid#1708]
数据库连接池配置：
`<property name="url" value="${jdbc.url}" />    
<property name="username" value="${jdbc.user}" />    
<property name="password" value="${jdbc.password}" />    
<property name="initialSize" value="5" />    
<property name="maxActive" value="30" />     
<property name="minIdle" value="5" />  
<property name="maxWait" value="60000" />    
<property name="timeBetweenEvictionRunsMillis" value="3000" />    
<property name="minEvictableIdleTimeMillis" value="300000" />    
<property name="validationQuery" value="SELECT 'x'" />    
<property name="testWhileIdle" value="true" />    
<property name="testOnBorrow" value="false" />    
<property name="testOnReturn" value="false" />    
<property name="poolPreparedStatements" value="true" />    
<property name="maxPoolPreparedStatementPerConnectionSize" value="20" />    
<property name="filters" value="stat" />  `  
数据库链接在运行时报错：
Caused by: java.sql.SQLRecoverableException: 关闭的语句
	at oracle.jdbc.driver.OracleClosedStatement.exitImplicitCacheToActive(OracleClosedStatement.java:4667)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.exitImplicitCacheToActive(OraclePreparedStatementWrapper.java:1607)
	at com.alibaba.druid.util.OracleUtils.exitImplicitCacheToActive(OracleUtils.java:79)
	at com.alibaba.druid.pool.PreparedStatementPool.get(PreparedStatementPool.java:66)
	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:326)
	at com.ibatis.sqlmap.engine.execution.SqlExecutor.prepareStatement(SqlExecutor.java:497)
	at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeUpdate(SqlExecutor.java:75)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.sqlExecuteUpdate(MappedStatement.java:216)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeUpdate(MappedStatement.java:94)

请问有可能是什么原因导致的这个问题？？在线等

**Comment by wenshao** [comment]
网络有过中断？

**Comment by qiufeng6407** [comment]
网络并没有中断过，我看这个问题有点像 pscache 的问题；
表现形式与 [#1614](https://github.com/alibaba/druid/issues/1614)一致；
就是前一个事务出错后，后面的调用全部出错；
版本*1.0.28*，是否这个问题还未修复，如果未修复，是不是可以将poolPreparedStatements改为false即可以避免？

**Comment by qiufeng6407** [comment]
1.0.28关闭pscache，或者升级1.0.29
