### ISSUE TITLE
ConfigFilter数据库密码加密异常

### ISSUE THREAD

**Issue by ScnuWang** [alibaba/druid#1719]
是否只有我一个人遇到这样的问题呢？
命令生成公钥：
C:\Users\Jason\Desktop>java -cp druid-1.0.29.jar com.alibaba.druid.filter.config.ConfigTools admin
privateKey:MIIBVQIBADANBgkqhkiG9w0BAQEFAASCAT8wggE7AgEAAkEAo8d/T1YYwgaPd5n5ZimeraCouFk3m3j8m7C/iLSlePnVqIoQln+/cLtNjtOPbnsGEdDMM5ChaYbMCYIvpDlseQIDAQABAkAeBf5Snufe+bDnLfTIQ6zxC1iioshM2fsE13vlJaiH6olb8Q0AJ08aTjnCe5poP4bEVXdJxFZmEGoVfLMnVQ8BAiEA4EQeULf/KXNScQJHPi6qt8eIBE4GwOKHqsLAlLjlVakCIQC69El3I5PoP
7F6ul/6DuQO9uDCzIfJCW4EIOVN884CUQIgPidCy5Yi1mcKmx1Jh1dBowtei+rf/kcJ2G5/FvijPnkCIQCaKzEaCkDCWSPmbSMQdo8it/uJKFkhM6GBzg7KRa8wwQIhALW+C+p1Gx8HWh3vklYfbbWOoHz6UW3hhIMF+qqg+4ku
publicKey:MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKPHf09WGMIGj3eZ+WYpnq2gqLhZN5t4/Juwv4i0pXj51aiKEJZ/v3C7TY7Tj257BhHQzDOQoWmGzAmCL6Q5bHkCAwEAAQ==
password:CSuTqsFdnfoQXfyuKPw+2Ai3o6TEjomaIevss7WlJTKh9hLvDft57ZKRoXWYPytq0OroEyLKhuKaZ7A6/BB+Sw==

属性文件：
password=CSuTqsFdnfoQXfyuKPw+2Ai3o6TEjomaIevss7WlJTKh9hLvDft57ZKRoXWYPytq0OroEyLKhuKaZ7A6/BB+Sw==
publickey=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKPHf09WGMIGj3eZ+WYpnq2gqLhZN5t4/Juwv4i0pXj51aiKEJZ/v3C7TY7Tj257BhHQzDOQoWmGzAmCL6Q5bHkCAwEAAQ==

Spring配置文件部分：
<bean id="dataSource" class="com.alibaba.druid.pool.DruidDataSource" init-method="init" destroy-method="close">
        <property name="url" value="jdbc:mysql://localhost:3306/imwork?useUnicode=true;characterEncoding=UTF-8;zeroDateTimeBehavior=convertToNull;useSSL=false" />
        <property name="username" value="root" />
        <property name="password" value="${password}" />
        <property name="filters" value="config" />
        <property name="connectionProperties" value="config.file=C:/propertites/dbconfig.properties;config.decrypt=true;config.decrypt.key=${publickey}" />
</bean>

部分异常截取：
Caused by: java.lang.IllegalArgumentException: Failed to get public key
	at com.alibaba.druid.filter.config.ConfigTools.getPublicKey(ConfigTools.java:101)
	at com.alibaba.druid.filter.config.ConfigFilter.getPublicKey(ConfigFilter.java:229)
	at com.alibaba.druid.filter.config.ConfigFilter.decrypt(ConfigFilter.java:201)
	... 104 more
Caused by: java.lang.IllegalArgumentException: Illegal character $
	at com.alibaba.druid.util.Base64.base64toInt(Base64.java:174)
	at com.alibaba.druid.util.Base64.base64ToByteArray(Base64.java:140)
	at com.alibaba.druid.util.Base64.base64ToByteArray(Base64.java:107)
	at com.alibaba.druid.filter.config.ConfigTools.getPublicKey(ConfigTools.java:94)
	... 106 more

**Comment by ScnuWang** [comment]
Spring配置文件部分怎么不显示呢？
<bean id="dataSource" class="com.alibaba.druid.pool.DruidDataSource" init-method="init" destroy-method="close">
        <property name="url" value="jdbc:mysql://localhost:3306/imwork?useUnicode=true;characterEncoding=UTF-8;zeroDateTimeBehavior=convertToNull;useSSL=false" />
        <property name="username" value="root" />
        <property name="password" value="${password}" />
        <property name="filters" value="config" />
        <property name="connectionProperties" value="config.file=C:/propertites/dbconfig.properties;config.decrypt=true;config.decrypt.key=${publickey}" />
</bean>

**Comment by ScnuWang** [comment]
要点击右上角的编辑按钮才能看见，
