### ISSUE TITLE
createPhysicalConnection 异常

### ISSUE THREAD

**Issue by wuxiansen** [alibaba/druid#1722]
# createPhysicalConnection 异常，用的1.0.29版本
### 连接配置
```<property name="initialSize" value="3"/>
    <property name="maxActive" value="20"/>
    <property name="minIdle" value="0"/>

    <property name="maxWait" value="350000"/>
    
    <property name="timeBetweenEvictionRunsMillis" value="10000"/>
    <property name="minEvictableIdleTimeMillis" value="60000"/>
    <property name="maxEvictableIdleTimeMillis" value="350000"/>
	
	<property name="testWhileIdle" value="true"/>
    <property name="testOnBorrow" value="true"/>
    <property name="testOnReturn" value="true"/>
    
    <property name="validationQuery" value="SELECT 1"/>
```

```
[framework] 2017-05-08 15:47:33,615 - com.alibaba.druid.pool.DruidDataSource -17774892 [Druid-ConnectionPool-Create-301749835] ERROR com.alibaba.druid.pool.DruidDataSource  - create connection error, url: jdbc:mysql://localhost:3306/tablename?useUnicode=true&characterEncoding=utf8&autoReconnect=true, errorCode 0, state 08001
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
        at com.mysql.jdbc.Util.getInstance(Util.java:386)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:989)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:975)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:920)
        at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2385)
        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2306)
        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:834)
        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
        at sun.reflect.GeneratedConstructorAccessor6.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:416)
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:346)
        at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1461)
        at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1525)
        at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2100)
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
        at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1121)
        at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:357)
        at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2479)
        at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2324)

**Comment by wuxiansen** [comment]
- `testOnBorrow` 和 `testOnBorrow` 设置为true 是为了确保 连接失效问题。

**Comment by wenshao** [comment]
数据库挂了？无法连接到数据库

**Comment by wuxiansen** [comment]
没噢，数据库正常。目前检测到一次， 我在想会不会是因为 minIdle 和 init 设置为 0，导致频繁的往数据库拿连接导致的。

**Comment by BlankRain** [comment]
也有可能是驱动版本不一致.比如高版本的数据库,用了低版本的驱动

**Comment by chenlushun** [comment]
确实应该关了
