### ISSUE TITLE
日志打印可执行语句时报错

### ISSUE THREAD

**Issue by jijianganchu** [alibaba/druid#1733]
使用druid-1.0.18.jar，配置了日志打印，但是解析时报错了，貌似是不支持在SQL中指定表所属的DB？

另外，我还关心以下两个问题：
1. 报这个错是不是代表我没有用到SQLParser的性能优化？即没有把druid的性能优化用起来？谢谢！
2. 日志会如何打印连接数据库的用户名和密码吗？例如：[C3P0ConnectionProvider:104]: configure() Connection properties: {user=dbuser, password=****}

报错信息：
2017-05-12 12:50:20:147 [WARN] pool-31-thread-9 [SQLUtils:253]: format() format error
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'INTO DataDB..TBL_TEST_7',expect DOTDOT, actual DOTDOT MSODataDB
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:232)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:407)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:145)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:140)
	at com.alibaba.druid.sql.SQLUtils.format(SQLUtils.java:249)
	at com.alibaba.druid.sql.SQLUtils.format(SQLUtils.java:241)
	at com.alibaba.druid.filter.logging.LogFilter.logExecutableSql(LogFilter.java:546)
	at com.alibaba.druid.filter.logging.LogFilter.statementExecuteBatchAfter(LogFilter.java:471)
	at com.alibaba.druid.filter.FilterEventAdapter.statement_executeBatch(FilterEventAdapter.java:281)
	at com.alibaba.druid.filter.FilterChainImpl.statement_executeBatch(FilterChainImpl.java:2594)
	at com.alibaba.druid.filter.FilterAdapter.statement_executeBatch(FilterAdapter.java:2474)
	at com.alibaba.druid.filter.FilterEventAdapter.statement_executeBatch(FilterEventAdapter.java:279)
	at com.alibaba.druid.filter.FilterChainImpl.statement_executeBatch(FilterChainImpl.java:2594)
	at com.alibaba.druid.proxy.jdbc.StatementProxyImpl.executeBatch(StatementProxyImpl.java:192)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeBatch(DruidPooledPreparedStatement.java:559)

2017-05-12 12:50:20:147 [DEBUG] pool-31-thread-9 [Statement:137]: statementLog() {conn-10002, pstmt-20007} executed. 
INSERT INTO DataDB..TBL_TEST_7 VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2017-05-12 12:50:20:148 [DEBUG] pool-31-thread-9 [Statement:137]: statementLog() {conn-10002, pstmt-20007} batch executed. 86.012686 millis.

**Comment by wenshao** [comment]
升级到1.0.29版本或者更新版本吧，新版支持这种语法了
