### ISSUE TITLE
加密报错 DerInputStream.getLength(): lengthTag=105, too big.

### ISSUE THREAD

**Issue by maxiaoxian** [alibaba/druid#1747]
加密后运行，报一下错误，请问是怎么处理？
Caused by: java.lang.IllegalArgumentException: Failed to decrypt.
	at com.alibaba.druid.filter.config.ConfigFilter.decrypt(ConfigFilter.java:211)
	at com.alibaba.druid.filter.config.ConfigFilter.init(ConfigFilter.java:123)
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:643)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1060)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1056)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:104)
	at com.baomidou.mybatisplus.entity.GlobalConfiguration.setMetaData(GlobalConfiguration.java:255)
	at com.baomidou.mybatisplus.spring.MybatisSqlSessionFactoryBean.buildSqlSessionFactory(MybatisSqlSessionFactoryBean.java:530)
	at com.baomidou.mybatisplus.spring.MybatisSqlSessionFactoryBean.afterPropertiesSet(MybatisSqlSessionFactoryBean.java:387)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624)
	... 53 common frames omitted
Caused by: java.lang.IllegalArgumentException: Failed to get public key
	at com.alibaba.druid.filter.config.ConfigTools.getPublicKey(ConfigTools.java:101)
	at com.alibaba.druid.filter.config.ConfigFilter.getPublicKey(ConfigFilter.java:229)
	at com.alibaba.druid.filter.config.ConfigFilter.decrypt(ConfigFilter.java:201)
	... 63 common frames omitted
Caused by: java.security.spec.InvalidKeySpecException: java.security.InvalidKeyException: IOException: DerInputStream.getLength(): lengthTag=105, too big.
	at sun.security.rsa.RSAKeyFactory.engineGeneratePublic(Unknown Source)
	at java.security.KeyFactory.generatePublic(Unknown Source)
	at com.alibaba.druid.filter.config.ConfigTools.getPublicKey(ConfigTools.java:99)
	... 65 common frames omitted
Caused by: java.security.InvalidKeyException: IOException: DerInputStream.getLength(): lengthTag=105, too big.
	at sun.security.x509.X509Key.decode(Unknown Source)
	at sun.security.x509.X509Key.decode(Unknown Source)
	at sun.security.rsa.RSAPublicKeyImpl.<init>(Unknown Source)
	at sun.security.rsa.RSAKeyFactory.generatePublic(Unknown Source)
	... 68 common frames omitted

**Comment by maxiaoxian** [comment]
配置错误。
