### ISSUE TITLE
set语句支持有误

### ISSUE THREAD

**Issue by forestkeeper** [alibaba/druid#1775]
````
mysql> set character set utf8, names utf8mb4;
Query OK, 0 rows affected (0.00 sec)
````

在druid中代码:
````
        String sql = "set character set utf8, names utf8mb4;";
        MySqlStatementParser parser = new MySqlStatementParser(sql);
        SQLSetStatement set = (SQLSetStatement) parser.parseStatementList().get(0);
        String output = SQLUtils.toMySqlString(set);
        System.out.println(output);
````

测试报错：
````
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :' set utf8, names utf8mb4;',expect COMMA, actual COMMA utf8

	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:262)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:373)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:84)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:80)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:75)

````

**Comment by wenshao** [comment]
已修复问题，请用新版本 https://github.com/alibaba/druid/releases/tag/1.1.0
