### ISSUE TITLE
我在使用druid的时候，连接池产生了一个死锁，导致后续操作全部失败。

### ISSUE THREAD

**Issue by 4your** [alibaba/druid#1797]
下面是死锁发生是的jvm线程dump的死锁描述：
Found one Java-level deadlock:
=============================
"pool-1-thread-1":waiting to lock monitor 0x000000000ed99908 (object 0x00000007974af528, a oracle.jdbc.driver.OracleTimeoutThreadPerVM),which is held by "OracleTimeoutPollingThread"

"OracleTimeoutPollingThread":waiting to lock monitor 0x000000000ecb4e18 (object 0x00000007974af948, a oracle.jdbc.driver.T4CConnection),which is held by "pool-1-thread-1"

Java stack information for the threads listed above:
===================================================
"pool-1-thread-1":
	at oracle.jdbc.driver.OracleTimeoutThreadPerVM.cancelTimeout(OracleTimeoutThreadPerVM.java:120)
	- waiting to lock <0x00000007974af528> (a oracle.jdbc.driver.OracleTimeoutThreadPerVM)
	at oracle.jdbc.driver.OraclePreparedStatement.executeForRowsWithTimeout(OraclePreparedStatement.java:9206)
	at oracle.jdbc.driver.OraclePreparedStatement.executeBatch(OraclePreparedStatement.java:9315)
	- locked <0x00000007974af948> (a oracle.jdbc.driver.T4CConnection)
	at oracle.jdbc.driver.OracleStatementWrapper.executeBatch(OracleStatementWrapper.java:211)
	at com.alibaba.druid.filter.FilterChainImpl.statement_executeBatch(FilterChainImpl.java:2596)
	at com.alibaba.druid.filter.FilterAdapter.statement_executeBatch(FilterAdapter.java:2474)
	at com.alibaba.druid.filter.FilterEventAdapter.statement_executeBatch(FilterEventAdapter.java:279)
	at com.alibaba.druid.filter.FilterChainImpl.statement_executeBatch(FilterChainImpl.java:2594)
	at com.alibaba.druid.proxy.jdbc.StatementProxyImpl.executeBatch(StatementProxyImpl.java:192)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeBatch(DruidPooledPreparedStatement.java:559)
	at gps.dao.impl.HfFcdGpsDaoImpl.InserterGpsInfo(HfFcdGpsDaoImpl.java:69)
	at gps.service.impl.HfFcdGpsManagerImpl.positionReportDeal(HfFcdGpsManagerImpl.java:40)
	at gps.task.HfFcdGpsRealTimeSaveTask$1.call(HfFcdGpsRealTimeSaveTask.java:63)
	at gps.task.HfFcdGpsRealTimeSaveTask$1.call(HfFcdGpsRealTimeSaveTask.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
"OracleTimeoutPollingThread":
	at oracle.jdbc.driver.PhysicalConnection.setUsable(PhysicalConnection.java:10001)
	- waiting to lock <0x00000007974af948> (a oracle.jdbc.driver.T4CConnection)
	at oracle.jdbc.driver.DatabaseError.newSQLException(DatabaseError.java:117)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:199)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:263)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:521)
	at oracle.jdbc.driver.T4CConnection.cancelOperationOnServer(T4CConnection.java:807)
	at oracle.jdbc.driver.OracleStatement.doCancel(OracleStatement.java:3011)
	at oracle.jdbc.driver.OracleStatement.cancel(OracleStatement.java:2981)
	at oracle.jdbc.driver.OracleTimeoutThreadPerVM.interruptIfAppropriate(OracleTimeoutThreadPerVM.java:174)
	- locked <0x00000007974af528> (a oracle.jdbc.driver.OracleTimeoutThreadPerVM)
	at oracle.jdbc.driver.OracleTimeoutPollingThread.pollOnce(OracleTimeoutPollingThread.java:204)
	at oracle.jdbc.driver.OracleTimeoutPollingThread.run(OracleTimeoutPollingThread.java:158)

Found 1 deadlock.

请问，这是一个bug吗。druid版本是1.0.29，ojdbc6 11.1.0.7.0。@wenshao

**Comment by 4your** [comment]
我的场景是：批处理插入gps数据到oracle。服务程序和数据库在两个不同的网络，具体好像是经过了两个交换机（或者防火墙）。下面是主要代码：
public class HfFcdGpsRealTimeSaveTask implements Runnable {

	private final static Logger LOG = LoggerFactory.getLogger(HfFcdGpsRealTimeSaveTask.class);

	private IhfFcdGpsManager gpsManager;

	private int size = 1000; // 最大批处理数
	
	private int timeout = 30; // 等待执行时间，秒
	
	public static ExecutorService executor = Executors.newFixedThreadPool(1);

	@Override
	public void run() {
		deal();
	}

	private void deal() {
		LOG.warn("HfFcdGpsRealTimeSaveTask start");
		long t0 = System.currentTimeMillis();
		int count = Math.min(size, GpsQueueCache.GPS_REALTIME.size());
		if (count == 0) {
			return;
		}
		if (count < size / 10) {
			try {
				Thread.sleep(500);
			} catch (InterruptedException e) {
			}
			count = Math.min(size, GpsQueueCache.GPS_REALTIME.size());
			if (count == 0) {
				return;
			}
		}

		final List<GPS_RECEIVE> list = new ArrayList<GPS_RECEIVE>(count);
		GpsQueueCache.GPS_REALTIME.drainTo(list, count);
		try {
			// 批量处理
			if (!list.isEmpty()) {
				LOG.warn("deal list, size:{},undeal list, size:{}", list.size(),GpsQueueCache.GPS_REALTIME.size());
				
				FutureTask<Integer> task = new FutureTask<Integer>(new Callable<Integer>() {
					@Override
					public Integer call() throws Exception {
						gpsManager.positionReportDeal(list);
						return 1;
					}
				});
				try {
					executor.execute(task);
					task.get(timeout, TimeUnit.SECONDS);
					gpsManager.positionReportDeal(list);
					long t1 = System.currentTimeMillis();
					LOG.warn("time user:{}, size:{}", (t1 - t0), list.size());
				} catch (Exception e) {
					LOG.error("insert time out: size:{}", list.size());
				}
			}
		} catch (Throwable e) {
			LOG.error(e.getMessage(), e);
		}
	}

@Override
	public void positionReportDeal(List<GPS_RECEIVE> list) {
		if (gpsBus != null) {
			gpsBus.post(list);
		}

		Connection conn = null;
		try {
			conn = dataSource.getConnection();
			gpsDao.InserterGpsInfo(conn, list);
		} catch (Throwable e) {
			LOG.error(e.getMessage(), e);
		} finally {
			CloseUtil.closeConnection(conn);
		}

	}

@Override
	public void InserterGpsInfo(Connection conn, List<GPS_RECEIVE> gpsList)
			throws Exception {
		LOG.debug("InserterGpsInfo");
		StringBuilder sb = new StringBuilder();
		sb.append("INSERT INTO gps_receive(rec_carid, rec_time, rec_longitude, rec_latitude, rec_speed, rec_direction, rec_carstatus, dbtime) ");
		sb.append(" values(?, ?, ?, ?, ?, ?, ?, ?)");
		LOG.debug(sb.toString());
		PreparedStatement ps = null;
		try {
			ps = conn.prepareStatement(sb.toString());
			ps.setQueryTimeout(sqlQueryTime);

			for (GPS_RECEIVE gps : gpsList) {
				int i = 1;

				ps.addBatch();
			}
			ps.executeBatch();
		} finally {
			CloseUtil.closeSt(ps);
		}
	}



<bean id="gzgpsDataSource" class="com.alibaba.druid.pool.DruidDataSource"
		init-method="init" destroy-method="close">
		
		<property name="connectProperties">
			<props>
				
				<prop key="oracle.net.CONNECT_TIMEOUT">30000</prop>
				
				<prop key="oracle.net.READ_TIMEOUT">60000</prop>
				
				<prop key="oracle.jdbc.ReadTimeout">60000</prop>
			</props>
		</property>

		
		<property name="url" value="${gzgps.url}" />
		<property name="username">
			<bean
				class="org.springframework.beans.factory.config.MethodInvokingFactoryBean">
				<property name="targetObject" ref="gzgpsDbParameter" />
				<property name="targetMethod" value="getUserName" />
			</bean>
		</property>
		<property name="password">
			<bean
				class="org.springframework.beans.factory.config.MethodInvokingFactoryBean">
				<property name="targetObject" ref="gzgpsDbParameter" />
				<property name="targetMethod" value="getPassword" />
			</bean>
		</property>

		
		<property name="initialSize" value="4" />
		<property name="minIdle" value="4" />
		<property name="maxActive" value="8" />
		<property name="keepAlive" value="true" />

		
		<property name="maxWait" value="30000" />

		
		<property name="timeBetweenEvictionRunsMillis" value="120000" />

		
		<property name="minEvictableIdleTimeMillis" value="600000" />

		<property name="validationQuery" value="SELECT 0 from dual" />
		<property name="testWhileIdle" value="true" />
		<property name="testOnBorrow" value="false" />
		<property name="testOnReturn" value="false" />

		
		<property name="poolPreparedStatements" value="true" />
		<property name="maxPoolPreparedStatementPerConnectionSize"
			value="10" />

		
		<property name="filters" value="stat" />
	</bean>

**Comment by wenshao** [comment]
看像是Oracle驱动的问题，升级oracle jdbc驱动版本试试

**Comment by 4your** [comment]
升级到ojdbc8 12.2.0.1这个版本可以吗

**Comment by 4your** [comment]
我把第三个参数注释掉之后，正常运行7天了，以前一两天就会报错。@wenshao


                            
				<prop key="oracle.net.CONNECT_TIMEOUT">30000</prop>
				
				<prop key="oracle.net.READ_TIMEOUT">60000</prop>

**Comment by 4your** [comment]
@wenshao 温少，现在一直没出现问题，应该就是这两个参数冲突了吧。

**Comment by breakenknife** [comment]
请问这个问题解决了吗?现在您的connectProperties是怎样配置的呢?
