### ISSUE TITLE
poolPreparedStatements 关闭的语句

### ISSUE THREAD

**Issue by liuchink** [alibaba/druid#1833]
使用spring4集成的druid，当操作数据库抛出异常时，再次操作数据库就会出现“关闭的语句”，第三次再操作有正常了，当关闭配置中的poolPreparedStatements时，就没有这个问题，请问我这个应该怎么解决呢？

第一次：java.sql.SQLIntegrityConstraintViolationException: ORA-02292: 违反完整约束条件 (ICEFRAME.FK_ROLE_USER_ID) - 已找到子记录
第二次： Error delegating 'getAutoCommit' call java.sql.SQLException: connection holder is null
Caused by: java.sql.SQLRecoverableException: 关闭的语句

当配置这样，就不会出现问题
<property name="poolPreparedStatements" value="false"/>
<property name="maxPoolPreparedStatementPerConnectionSize" value="-1"/>

**Comment by wenshao** [comment]
操作数据库抛出异常，是DDL么？

**Comment by liuchink** [comment]
不是DDL，就是普通的DML，使用delete语句删除一条记录，这个条记录在数据库中存在级联关系，所以会报违反完整约束的错误，我使用的是springmvc，然后使用了全局异常捕获机制，处理了这个异常，再次操作数据库就会出现关闭的语句，任何对数据库的操作都会出这个错误，出现一次以后，只要系统不抛异常就又恢复正常使用

**Comment by wenshao** [comment]
什么数据库？

**Comment by liuchink** [comment]
oracle 11G R2    mysql 5.6上都发现了这个问题

**Comment by liuchink** [comment]
Oracle11gR2






在 2017-07-24 02:42:47，"高铁" <notifications@github.com> 写道：


什么数据库？

**Comment by lmtoo** [comment]
java.sql.SQLRecoverableException: Closed Connection
        at oracle.jdbc.driver.PhysicalConnection.needLine(PhysicalConnection.java:6295)
        at oracle.jdbc.driver.OracleStatement.closeOrCache(OracleStatement.java:1364)
        at oracle.jdbc.driver.OracleStatement.close(OracleStatement.java:1343)
        at oracle.jdbc.driver.OracleStatementWrapper.close(OracleStatementWrapper.java:100)
        at com.alibaba.druid.util.JdbcUtils.close(JdbcUtils.java:84)
        at com.alibaba.druid.pool.vendor.OracleValidConnectionChecker.isValidConnection(OracleValidConnectionChecker.java:88)
        at com.alibaba.druid.pool.DruidAbstractDataSource.testConnectionInternal(DruidAbstractDataSource.java:1412)
        at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1316)
        at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5007)
        at com.alibaba.druid.filter.stat.StatFilter.dataSource_getConnection(StatFilter.java:680)
        at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5003)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1250)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1242)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:89)
        at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:246)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:377)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)

ojdbc7-7.0 druid-1.1.12
