### ISSUE TITLE
oracle create sequence不支持cache选项

### ISSUE THREAD

**Issue by zzx8170** [alibaba/druid#1867]
sql：CREATE SEQUENCE "GJS_ZIXUN"."FINANCE_EXPLAIN_ID_GENERATOR"  CACHE 2
解析报错：syntax error: TODO : pos 67, LITERAL_INT CACHE

**Comment by zzx8170** [comment]
这几个问题怎么没人关注？

**Comment by JacoBlunt** [comment]
我也遇到这个问题 
sql脚本  create sequence SEQ_DSSWLOG minvalue 1 maxvalue 9999999999 start with 161 increment by 1 cache 10 

报错 ：
Caused by: com.alibaba.druid.sql.parser.ParserException: TODO : LITERAL_INT cache
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleStatementParser.parseStatementList(OracleStatementParser.java:462)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:79)
	at com.alibaba.druid.wall.WallProvider.checkInternal(WallProvider.java:620)
	at com.alibaba.druid.wall.WallProvider.check(WallProvider.java:574)
	at com.alibaba.druid.wall.WallFilter.check(WallFilter.java:712)
	... 36 more

**Comment by wenshao** [comment]
问题已解决，请用新版本 https://github.com/alibaba/druid/releases/tag/1.1.3
