### ISSUE TITLE
mysql数据库执行lock tables 语句报错

### ISSUE THREAD

**Issue by lwfcatch** [alibaba/druid#1885]
例如执行 lock tables oa_ding_access_token AS this_ WRITE

后台错误信息

com.alibaba.druid.sql.parser.ParserException: syntax error, AS AS, pos 35
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:300) ~[druid-1.0.2.jar:1.0.2]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:108) ~[druid-1.0.2.jar:1.0.2]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:103) ~[druid-1.0.2.jar:1.0.2]
	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:53) ~[druid-1.0.2.jar:1.0.2]
	at com.alibaba.druid.filter.stat.StatFilter.mergeSql(StatFilter.java:145) [druid-1.0.2.jar:1.0.2]
	at com.alibaba.druid.filter.stat.StatFilter.createSqlStat(StatFilter.java:629) [druid-1.0.2.jar:1.0.2]
	at com.alibaba.druid.filter.stat.StatFilter.statementPrepareAfter(StatFilter.java:305) [druid-1.0.2.jar:1.0.2]
	at com.alibaba.druid.filter.FilterEventAdapter.connection_prepareStatement(FilterEventAdapter.java:124) [druid-1.0.2.jar:1.0.2]
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:448) [druid-1.0.2.jar:1.0.2]
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.prepareStatement(ConnectionProxyImpl.java:342) [druid-1.0.2.jar:1.0.2]
	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:311) [druid-1.0.2.jar:1.0.2]
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$1.doPrepare(StatementPreparerImpl.java:98) [hibernate-core-4.2.5.Final.jar:4.2.5.Final]
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:182) [hibernate-core-4.2.5.Final.jar:4.2.5.Final]
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareStatement(StatementPreparerImpl.java:91) [hibernate-core-4.2.5.Final.jar:4.2.5.Final]
	at org.hibernate.engine.query.spi.NativeSQLQueryPlan.performExecuteUpdate(NativeSQLQueryPlan.java:196) [hibernate-core-4.2.5.Final.jar:4.2.5.Final]
	at org.hibernate.internal.SessionImpl.executeNativeUpdate(SessionImpl.java:1313) [hibernate-core-4.2.5.Final.jar:4.2.5.Final]
	at org.hibernate.internal.SQLQueryImpl.executeUpdate(SQLQueryImpl.java:401) [hibernate-core-4.2.5.Final.jar:4.2.5.Final]

**Comment by changealice** [comment]
@lwfcatch 解决了吗？ 我这边也遇到了，是不是需要关闭statsfilter
