### ISSUE TITLE
设置SelectLimit限制, 无法处理limit ?, ? 这种格式， 该怎么办

### ISSUE THREAD

**Issue by GodzillaHua** [alibaba/druid#1899]
![image](https://user-images.githubusercontent.com/18274190/29204666-ef5cda08-7eaa-11e7-97e2-a872a4d1a29c.png)

![image](https://user-images.githubusercontent.com/18274190/29204696-1ddbe716-7eab-11e7-9037-6288c91acc19.png)

Exception in thread "main" java.sql.SQLException: Parameter index out of range (2 > number of parameters, which is 1).
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1075)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:989)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:984)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:929)
	at com.mysql.jdbc.PreparedStatement.checkBounds(PreparedStatement.java:3711)
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3695)

**Comment by wenshao** [comment]
这个 mysql驱动的问题，不过可以在druid层处理掉的

**Comment by GodzillaHua** [comment]
这个会修复吗？

**Comment by koushr** [comment]
这个bug还没修复吗？
