### ISSUE TITLE
WARN  com.alibaba.druid.pool.DruidDataSource - not full timeout retry

### ISSUE THREAD

**Issue by zrweng** [alibaba/druid#1917]
连接Oracle数据库，一直抛出以下告警：

2017-08-16 17:45:57.911 [MultiThreadFullRecordApplier-JXPJ0724.UBE_STOCK_OUT_ITEM-2] WARN  com.alibaba.druid.pool.DruidDataSource - not full timeout retry : 1
2017-08-16 17:45:57.913 [MultiThreadFullRecordApplier-JXPJ0724.UBE_STOCK_OUT_ITEM-3] WARN  com.alibaba.druid.pool.DruidDataSource - not full timeout retry : 1
2017-08-16 17:45:57.913 [MultiThreadFullRecordApplier-JXPJ0724.UBE_STOCK_OUT_ITEM-6] WARN  com.alibaba.druid.pool.DruidDataSource - not full timeout retry : 1
2017-08-16 17:45:57.914 [MultiThreadFullRecordApplier-JXPJ0724.UBE_STOCK_OUT_ITEM-4] WARN  com.alibaba.druid.pool.DruidDataSource - not full timeout retry : 1
2017-08-16 17:45:57.914 [MultiThreadFullRecordApplier-JXPJ0724.UBE_STOCK_OUT_ITEM-5] WARN  com.alibaba.druid.pool.DruidDataSource - not full timeout retry : 1
2017-08-16 17:45:57.915 [MultiThreadFullRecordApplier-JXPJ0724.UBE_STOCK_OUT_ITEM-0] WARN  com.alibaba.druid.pool.DruidDataSource - not full timeout retry : 1
2017-08-16 17:46:02.914 [MultiThreadFullRecordApplier-JXPJ0724.UBE_STOCK_OUT_ITEM-6] WARN  com.alibaba.druid.pool.DruidDataSource - not full timeout retry : 2
2017-08-16 17:46:02.914 [MultiThreadFullRecordApplier-JXPJ0724.UBE_STOCK_OUT_ITEM-3] WARN  com.alibaba.druid.pool.DruidDataSource - not full timeout retry : 2
2017-08-16 17:46:02.915 [MultiThreadFullRecordApplier-JXPJ0724.UBE_STOCK_OUT_ITEM-4] WARN  com.alibaba.druid.pool.DruidDataSource - not full timeout retry : 2
2017-08-16 17:46:02.915 [MultiThreadFullRecordApplier-JXPJ0724.UBE_STOCK_OUT_ITEM-5] WARN  com.alibaba.druid.pool.DruidDataSource - not full timeout retry : 2
2017-08-16 17:46:02.916 [MultiThreadFullRecordApplier-JXPJ0724.UBE_STOCK_OUT_ITEM-0] WARN  com.alibaba.druid.pool.DruidDataSource - not full timeout retry : 2
2017-08-16 17:46:07.915 [MultiThreadFullRecordApplier-JXPJ0724.UBE_STOCK_OUT_ITEM-3] WARN  com.alibaba.druid.pool.DruidDataSource - not full timeout retry : 3
2017-08-16 17:46:07.917 [MultiThreadFullRecordApplier-JXPJ0724.UBE_STOCK_OUT_ITEM-4] WARN  com.alibaba.druid.pool.DruidDataSource - not full timeout retry : 3
2017-08-16 17:46:07.917 [MultiThreadFullRecordApplier-JXPJ0724.UBE_STOCK_OUT_ITEM-0] WARN  com.alibaba.druid.pool.DruidDataSource - not full timeout retry : 3
2017-08-16 17:46:07.917 [MultiThreadFullRecordApplier-JXPJ0724.UBE_STOCK_OUT_ITEM-5] WARN  com.alibaba.druid.pool.DruidDataSource - not full timeout retry : 3

之后就抛出异常：
Caused by: com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 5000, active 10, maxActive 300
	at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1192)
	at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1014)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:994)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:984)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:103)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:77)
	... 14 more

这.....什么原因？

**Comment by wenshao** [comment]
什么版本？当前数据库无法新建连接？

**Comment by 787100028** [comment]
怎么解决的？我也遇到了。

**Comment by IzzyXie2010** [comment]
有解决了吗？也遇到这个问题，总是突然间就出现这个问题。等一阵就好了

**Comment by wb1061978668** [comment]
> 有解决了吗？也遇到这个问题，总是突然间就出现这个问题。等一阵就好了

您好！我也出现这个问题了。请问您是怎么解决的呀？

**Comment by poc9999** [comment]
如何解决的

**Comment by zrweng** [comment]
不好意思，没有解决掉，后来没有使用了。
