### ISSUE TITLE
druid parser在解析oracle语句时，怎么解决oracle关键字做字段别名问题

### ISSUE THREAD

**Issue by lvxiaoxi123** [alibaba/druid#1925]
比如关键字STORE做字段别名：select (order.STORE - order.LAST_STORE) STORE from order;
报错为：
com.alibaba.druid.sql.parser.ParserException: TODO : pos 45, line 1, column 40, token STORE
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleStatementParser.parseStatementList(OracleStatementParser.java:615)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:78)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:419)

**Comment by wenshao** [comment]
问题已解决，请用新版本 https://github.com/alibaba/druid/releases/tag/1.1.3
