### ISSUE TITLE
RDS 读取blob 类型错误

### ISSUE THREAD

**Issue by lveliu** [alibaba/druid#1937]
29-Aug-2017 18:10:40.139 INFO [quartzScheduler_QuartzSchedulerThread] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [com.mysql.jdbc.Blob]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
 java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [com.mysql.jdbc.Blob]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1352)
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1340)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1205)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1166)
	at com.mysql.jdbc.ResultSetImpl.getBlob(ResultSetImpl.java:1482)
	at com.mysql.jdbc.ResultSetImpl.getBlob(ResultSetImpl.java:1503)
	at com.alibaba.druid.filter.FilterChainImpl.resultSet_getBlob(FilterChainImpl.java:1739)
	at com.alibaba.druid.filter.stat.StatFilter.resultSet_getBlob(StatFilter.java:732)
	at com.alibaba.druid.filter.FilterChainImpl.resultSet_getBlob(FilterChainImpl.java:1737)
	at com.alibaba.druid.proxy.jdbc.ResultSetProxyImpl.getBlob(ResultSetProxyImpl.java:293)
	at com.alibaba.druid.pool.DruidPooledResultSet.getBlob(DruidPooledResultSet.java:1170)
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.getObjectFromBlob(StdJDBCDelegate.java:3190)
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.selectTrigger(StdJDBCDelegate.java:1780)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.retrieveTrigger(JobStoreSupport.java:1531)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2808)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$40.execute(JobStoreSupport.java:2759)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$40.execute(JobStoreSupport.java:2757)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3803)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTriggers(JobStoreSupport.java:2756)
	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:272)

**Comment by wenshao** [comment]
这个看起来像是mysql driver的问题，升级到最新版本试试看

**Comment by kimmking** [comment]
排查一下是不是加载的classloader里存在不同版本的mysql驱动。
