### ISSUE TITLE
H2数据库创建触发器SQL解析异常

### ISSUE THREAD

**Issue by godsmell** [alibaba/druid#1941]
2017-09-01 19:39:22 DEBUG [org.springframework.jdbc.core.JdbcTemplate] org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:417)- Executing SQL statement [create trigger employee_trigger after insert,update,delete on employee for each row call "test.redisson.h2cluster.trigger.ClusterTrigger"]
2017-09-01 19:39:22 DEBUG [org.springframework.jdbc.datasource.DataSourceUtils] org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:110)- Fetching JDBC Connection from DataSource
2017-09-01 19:39:22 ERROR [com.alibaba.druid.filter.stat.StatFilter] com.alibaba.druid.filter.stat.StatFilter.mergeSql(StatFilter.java:148)- merge sql error, dbType h2, sql : **create trigger employee_trigger after insert,update,delete on employee for each row call "test.redisson.h2cluster.trigger.ClusterTrigger"**
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'fter insert,update,delete on employ',expect ON, actual COMMA pos 45, line 1, column 45, token COMMA
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:280)
	at com.alibaba.druid.sql.parser.SQLParser.accept(SQLParser.java:288)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseCreateTrigger(SQLStatementParser.java:1992)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseCreate(MySqlStatementParser.java:348)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:155)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:78)
	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:43)
	at com.alibaba.druid.filter.stat.StatFilter.mergeSql(StatFilter.java:146)
	at com.alibaba.druid.filter.stat.StatFilter.createSqlStat(StatFilter.java:634)
	at com.alibaba.druid.filter.stat.StatFilter.internalBeforeStatementExecute(StatFilter.java:402)
	at com.alibaba.druid.filter.stat.StatFilter.statementExecuteBefore(StatFilter.java:350)
	at com.alibaba.druid.filter.FilterEventAdapter.statement_execute(FilterEventAdapter.java:185)
	at com.alibaba.druid.filter.FilterChainImpl.statement_execute(FilterChainImpl.java:2598)
	at com.alibaba.druid.proxy.jdbc.StatementProxyImpl.execute(StatementProxyImpl.java:153)
	at com.alibaba.druid.pool.DruidPooledStatement.execute(DruidPooledStatement.java:497)
	at org.springframework.jdbc.core.JdbcTemplate$1ExecuteStatementCallback.doInStatement(JdbcTemplate.java:421)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:396)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:428)
	at test.redisson.h2cluster.H2Manager.initTable(H2Manager.java:64)
	at test.redisson.h2cluster.H2Manager.<init>(H2Manager.java:52)
	at test.redisson.h2cluster.H2Manager.<clinit>(H2Manager.java:35)
	at test.redisson.h2cluster.H2DBService.<init>(H2DBService.java:32)
	at test.redisson.h2cluster.H2DBService.<clinit>(H2DBService.java:31)
	at test.redisson.h2cluster.H2ClusterManager.main(H2ClusterManager.java:33)

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.4
问题已经修复，请使用新版本
