### ISSUE TITLE
MySqlOptimizeStatement not allow : optimize table 

### ISSUE THREAD

**Issue by cwocwo** [alibaba/druid#1943]
通过jdbc执行 ：`optimize table  table1`
时出现以下错误：
```
Caused by: java.sql.SQLException: sql injection violation, class com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlOptimizeStatement not allow : optimize table table1
        at com.alibaba.druid.wall.WallFilter.check(WallFilter.java:728)
        at com.alibaba.druid.wall.WallFilter.statement_execute(WallFilter.java:398)
        at com.alibaba.druid.filter.FilterChainImpl.statement_execute(FilterChainImpl.java:2487)
        at com.alibaba.druid.filter.FilterAdapter.statement_execute(FilterAdapter.java:2451)
        at com.alibaba.druid.filter.FilterEventAdapter.statement_execute(FilterEventAdapter.java:188)
        at com.alibaba.druid.filter.FilterChainImpl.statement_execute(FilterChainImpl.java:2487)
        at com.alibaba.druid.proxy.jdbc.StatementProxyImpl.execute(StatementProxyImpl.java:137)
        at com.alibaba.druid.pool.DruidPooledStatement.execute(DruidPooledStatement.java:421)
```

这是WallFilter拦截造成的吗？ 应当如何配置才能执行？

**Comment by kimmking** [comment]
看起来是的。

**Comment by wenshao** [comment]
问题已修复，请用新版本 https://github.com/alibaba/druid/releases/tag/1.1.3

**Comment by cwocwo** [comment]
已更新。
