### ISSUE TITLE
SQLBinaryOpExpr死循环问题

### ISSUE THREAD

**Issue by freeman983** [alibaba/druid#1963]
java.lang.StackOverflowError , at 2017-09-02 10:11
	at com.alibaba.druid.sql.ast.expr.SQLBinaryOpExpr.equals(SQLBinaryOpExpr.java:160)
	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.merge(ParameterizedOutputVisitorUtils.java:189)
	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.merge(ParameterizedOutputVisitorUtils.java:207)
	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.merge(ParameterizedOutputVisitorUtils.java:207)
	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.merge(ParameterizedOutputVisitorUtils.java:207)
	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.merge(ParameterizedOutputVisitorUtils.java:207)
	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.merge(ParameterizedOutputVisitorUtils.java:207)
	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.merge(ParameterizedOutputVisitorUtils.java:207)
	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.merge(ParameterizedOutputVisitorUtils.java:207)
	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.merge(ParameterizedOutputVisitorUtils.java:207)
	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.merge(ParameterizedOutputVisitorUtils.java:207)
	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.merge(ParameterizedOutputVisitorUtils.java:207)
	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.merge(ParameterizedOutputVisitorUtils.java:207)
....

项目是运行在storm里的,日志量比较大,所以无法打印sql语句,通过查看storm的错误日志可以看到这里解析到某条sql时会出现死循环导致堆栈溢出.

`
       WallConfig config = new WallConfig(OracleWallProvider.DEFAULT_CONFIG_DIR);
        config.setStrictSyntaxCheck(false);
        config.setConditionDoubleConstAllow(false);
        config.setConstArithmeticAllow(false);

        //支持条件为真
        config.setConditionAndAlwayTrueAllow(true);

        config.setConditionDoubleConstAllow(true);

        //支持算数表达式
        config.setConstArithmeticAllow(true);

        //支持注解
        config.setCommentAllow(true);

        this.provider = new OracleWallProvider(config);
        WallCheckResult wcr = provider.check(sql);
`

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.3 升级到最新版本就好了

**Comment by freeman983** [comment]
ok,谢谢温少
