### ISSUE TITLE
 No enum constant com.alibaba.druid.sql.dialect.oracle.ast.expr.OracleIntervalType.second

### ISSUE THREAD

**Issue by kenputon1** [alibaba/druid#1969]
1.1.2
oracle 11g
Oracle10gDialect

sql:
select * from cp_data_edit_lock a where a.lock_time > sysdate -  interval '58' second  and datatype_code='ANY'

 java.lang.IllegalArgumentException: No enum constant com.alibaba.druid.sql.dialect.oracle.ast.expr.OracleIntervalType.second

	at java.lang.Enum.valueOf(Enum.java:236)

	at com.alibaba.druid.sql.dialect.oracle.ast.expr.OracleIntervalType.valueOf(OracleIntervalType.java:18)

	at com.alibaba.druid.sql.dialect.oracle.parser.OracleExprParser.parseInterval(OracleExprParser.java:892)

	at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:623)

	at com.alibaba.druid.sql.dialect.oracle.parser.OracleExprParser.primary(OracleExprParser.java:457)

	at com.alibaba.druid.sql.parser.SQLExprParser.bitXor(SQLExprParser.java:112)

	at com.alibaba.druid.sql.parser.SQLExprParser.multiplicative(SQLExprParser.java:192)

	at com.alibaba.druid.sql.parser.SQLExprParser.additiveRest(SQLExprParser.java:1470)

	at com.alibaba.druid.sql.parser.SQLExprParser.additive(SQLExprParser.java:1453)

	at com.alibaba.druid.sql.parser.SQLExprParser.shift(SQLExprParser.java:1480)

	at com.alibaba.druid.sql.parser.SQLExprParser.bitAnd(SQLExprParser.java:1341)

	at com.alibaba.druid.sql.parser.SQLExprParser.bitOr(SQLExprParser.java:1355)

	at com.alibaba.druid.sql.parser.SQLExprParser.relationalRest(SQLExprParser.java:1601)

	at com.alibaba.druid.sql.dialect.oracle.parser.OracleExprParser.relationalRest(OracleExprParser.java:957)

	at com.alibaba.druid.sql.parser.SQLExprParser.exprRest(SQLExprParser.java:103)

	at com.alibaba.druid.sql.dialect.oracle.parser.OracleExprParser.exprRest(OracleExprParser.java:1146)

	at com.alibaba.druid.sql.parser.SQLExprParser.expr(SQLExprParser.java:92)

	at com.alibaba.druid.sql.parser.SQLSelectParser.expr(SQLSelectParser.java:599)

	at com.alibaba.druid.sql.parser.SQLSelectParser.parseWhere(SQLSelectParser.java:260)

	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.query(OracleSelectParser.java:275)

	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.select(OracleSelectParser.java:70)

	at com.alibaba.druid.sql.dialect.oracle.parser.OracleStatementParser.parseStatementList(OracleStatementParser.java:94)

	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:78)

	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:43)

	at com.alibaba.druid.filter.stat.StatFilter.mergeSql(StatFilter.java:146)

	at com.alibaba.druid.filter.stat.StatFilter.createSqlStat(StatFilter.java:634)

	at com.alibaba.druid.filter.stat.StatFilter.statementPrepareAfter(StatFilter.java:310)

	at com.alibaba.druid.filter.FilterEventAdapter.connection_prepareStatement(FilterEventAdapter.java:124)

	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:473)

	at com.alibaba.druid.filter.FilterAdapter.connection_prepareStatement(FilterAdapter.java:929)

	at com.alibaba.druid.filter.FilterEventAdapter.connection_prepareStatement(FilterEventAdapter.java:122)

	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:473)

	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.prepareStatement(ConnectionProxyImpl.java:342)

	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:350)

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.4
问题已经修复，请使用新版本
