### ISSUE TITLE
无法解析CONCAT

### ISSUE THREAD

**Issue by jayzch** [alibaba/druid#1982]
在1.0.31版本下和1.1.3版本下均不能解析如下语句。
select  ID, AUTHORITY_TYPE from t_authority a where authority_type like CONCAT('%', ?)
报错如下

Caused by: com.alibaba.druid.sql.parser.ParserException: ERROR. pos 209, line 1, column 203, token CONCAT
	at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:697)
	at com.alibaba.druid.sql.parser.SQLExprParser.bitXor(SQLExprParser.java:133)
	at com.alibaba.druid.sql.parser.SQLExprParser.multiplicative(SQLExprParser.java:213)
	at com.alibaba.druid.sql.parser.SQLExprParser.additive(SQLExprParser.java:1577)

**Comment by wwyu8901** [comment]
我也遇到同样的问题，db2环境下。1.0.11版本是正常的，但是升级后就报concat解析错误了。试了一下最新的1.1也不行。

**Comment by wenshao** [comment]
@jayzch 你的sql from前多了一个逗号吧

**Comment by jayzch** [comment]
@wenshao 不是的。我只是粘贴的时候把无关查询字段删了

**Comment by jayzch** [comment]
我们使用的时候，是用druid解析sql的特性，不是单纯使用连接池

**Comment by wenshao** [comment]
问题已重现，会尽快发布新版本，可能在周末，也可能在国庆

**Comment by jayzch** [comment]
求发

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.4
问题已经修复，请使用新版本
