### ISSUE TITLE
1.1.3版本Lexer.scanAlias()方法校验过严

### ISSUE THREAD

**Issue by hnhckj** [alibaba/druid#1985]
1.1.3之前的版本能够校验过的sql在1.1.3版本中的Lexer.scanAlias()会抛出com.alibaba.druid.sql.parser.ParserException: unclosed str. pos 66, line 1, column 66, token COMMA异常，具体堆栈如下
com.alibaba.druid.filter.stat.StatFilter.mergeSql(StatFilter.java:148) -- merge sql error, dbType mysql, sql : SELECT totalNumber,  concat("",? , round(memberNumber, 0) , "") AS totalDisplay FROM (
SELECT count(1) AS totalNumber, SUM(memberNumber) AS memberNumber FROM(
SELECT mmd.office_id AS departID,st.no AS staffNO,st.name AS staffName,COUNT(mmd.id) memberNumber FROM ms_member_def mmd
LEFT JOIN sys_user st ON mmd.salesman_id=st.id AND st.del_flag='0'
WHERE mmd.create_date BETWEEN (?) AND DATE_ADD((?),INTERVAL '23:59:59' HOUR_SECOND) AND mmd.del_flag='0'
AND ('' IN (?) OR st.no IN (?))
AND ('' IN (?) OR mmd.office_id IN (?))
GROUP BY mmd.office_id,st.no
) gg 
)temp com.alibaba.druid.sql.parser.ParserException: unclosed str. pos 66, line 1, column 66, token COMMA
	at com.alibaba.druid.sql.parser.Lexer.scanAlias(Lexer.java:1042) ~[druid-1.1.3.jar:1.1.3]
	at com.alibaba.druid.sql.parser.Lexer.nextToken(Lexer.java:586) ~[druid-1.1.3.jar:1.1.3]
	at com.alibaba.druid.sql.parser.SQLExprParser.exprList(SQLExprParser.java:1118) ~[druid-1.1.3.jar:1.1.3]
	at com.alibaba.druid.sql.parser.SQLExprParser.methodRest(SQLExprParser.java:964) ~[druid-1.1.3.jar:1.1.3]
	at com.alibaba.druid.sql.parser.SQLExprParser.parseSelectItem(SQLExprParser.java:2604) ~[druid-1.1.3.jar:1.1.3]

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.4
问题已经修复，请使用新版本
