### ISSUE TITLE
Caused by: javax.management.InstanceAlreadyExistsException: com.alibaba.druid.filter.stat:name=statFilter,type=StatFilter

### ISSUE THREAD

**Issue by haochencheng** [alibaba/druid#1989]
Caused by: javax.management.InstanceAlreadyExistsException: com.alibaba.druid.filter.stat:name=statFilter,type=StatFilter
	at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
	at org.springframework.jmx.support.MBeanRegistrationSupport.doRegister(MBeanRegistrationSupport.java:195)
	at org.springframework.jmx.export.MBeanExporter.registerBeanInstance(MBeanExporter.java:674)
	at org.springframework.jmx.export.MBeanExporter.registerBeanNameOrInstance(MBeanExporter.java:618)
	... 25 common frames omitted

springboot打war包部署tomcat中启动报错

**Comment by Lisl0828** [comment]
druid的state实例貌似只能启动一个 不能多启动， 我也是多个springboot打成war包跑的时候遇到的这个问题，目前没有一个非常好的解决办法

**Comment by Lisl0828** [comment]
出现这种问题是因为同时部署的时候spring 默认的mbean名字都一样了，只需要在每个yml下配置spring.jmx.default-domain= 自定义名字  ，名字不同，实例化出的对象就不一样了。

**Comment by ITGrocery** [comment]
我也遇到了这个问题，按照楼上的方法解决了，但不知道报错的具体原因。

**Comment by zhcosin** [comment]
我也遇到这问题了，按照 @Lisl0828 说的方案解决了.
