### ISSUE TITLE
sql server 序列查询问题

### ISSUE THREAD

**Issue by LeasonX** [alibaba/druid#1992]
开启wall filter执行`select next value for orderId`这个语句报错，报错信息如下 
```
Caused by: com.alibaba.druid.sql.parser.ParserException: syntax error, not support option : IDENTIFIER, pos 29, line 1, column 22, token IDENTIFIER OrderId
	at com.alibaba.druid.sql.dialect.sqlserver.parser.SQLServerSelectParser.select(SQLServerSelectParser.java:93)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseSelect(SQLStatementParser.java:2087)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:143)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:93)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:89)
	at com.alibaba.druid.wall.WallProvider.checkInternal(WallProvider.java:620)
	at com.alibaba.druid.wall.WallProvider.check(WallProvider.java:574)
	at com.alibaba.druid.wall.WallFilter.check(WallFilter.java:712)
	... 160 common frames omitted
```
请问是因为什么原因

**Comment by wenshao** [comment]
不能解析sql语句导致的，这个周末回发布新版本解决此问题

**Comment by LeasonX** [comment]
@wenshao 最好也能在druid-spring-boot-starter项目中解决此问题。

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.4
问题已经修复，请使用新版本
