### ISSUE TITLE
以下pg语句执行通过，但是mergeSql里面报错了

### ISSUE THREAD

**Issue by kingour** [alibaba/druid#2002]
# 1.环境
数据库：PG9.5
ORM： mybatis
DRUID:1.1.3
# 2.sql，类似下面这种
```sql
select id,sum(uv[1]) uv1,sum(uv[2]) uv2
from xxxxx where a in
                     (  
                        ?
                     ) 
 and ta->'taAge' ??|
                 
                         '{  
                            1
                         , 
                            2
                         , 
                            3
                         }' 
group by id
```

# 3.错误输出
```
11:09:37.995 ERROR com.alibaba.druid.filter.stat.StatFilter:148 - merge sql error, dbType postgresql, sql : select id,sum(uv[1]) uv1,sum(uv[2]) uv2
from xxxxx where a in
                     (  
                        ?
                     ) 
 and ta->'taAge' ??|
                 
                         '{  
                            1
                         , 
                            2
                         , 
                            3
                         }' 
group by id

com.alibaba.druid.sql.parser.ParserException: ERROR. pos 516, line 21, column 36, token BAR
	at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:697)
	at com.alibaba.druid.sql.dialect.postgresql.parser.PGExprParser.primary(PGExprParser.java:122)
	at com.alibaba.druid.sql.parser.SQLExprParser.bitXorRest(SQLExprParser.java:184)
	at com.alibaba.druid.sql.parser.SQLExprParser.bitXorRest(SQLExprParser.java:151)
	at com.alibaba.druid.sql.parser.SQLExprParser.bitXor(SQLExprParser.java:134)
	at com.alibaba.druid.sql.parser.SQLExprParser.multiplicative(SQLExprParser.java:213)
	at com.alibaba.druid.sql.parser.SQLExprParser.additive(SQLExprParser.java:1577)
	at com.alibaba.druid.sql.parser.SQLExprParser.shift(SQLExprParser.java:1607)
	at com.alibaba.druid.sql.parser.SQLExprParser.bitAnd(SQLExprParser.java:1464)
	at com.alibaba.druid.sql.parser.SQLExprParser.bitOr(SQLExprParser.java:1478)
	at com.alibaba.druid.sql.parser.SQLExprParser.equality(SQLExprParser.java:1493)
	at com.alibaba.druid.sql.parser.SQLExprParser.relational(SQLExprParser.java:1757)
	at com.alibaba.druid.sql.parser.SQLExprParser.andRest(SQLExprParser.java:1659)
	at com.alibaba.druid.sql.parser.SQLExprParser.expr(SQLExprParser.java:109)
	at com.alibaba.druid.sql.parser.SQLSelectParser.expr(SQLSelectParser.java:697)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseWhere(SQLSelectParser.java:318)
	at com.alibaba.druid.sql.dialect.postgresql.parser.PGSelectParser.query(PGSelectParser.java:135)
	at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:50)
	at com.alibaba.druid.sql.dialect.postgresql.parser.PGSQLStatementParser.parseSelect(PGSQLStatementParser.java:237)
	at com.alibaba.druid.sql.dialect.postgresql.parser.PGSQLStatementParser.parseSelect(PGSQLStatementParser.java:41)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:133)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:70)
	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:42)
	at com.alibaba.druid.filter.stat.StatFilter.mergeSql(StatFilter.java:146)
	at com.alibaba.druid.filter.stat.StatFilter.createSqlStat(StatFilter.java:634)
	at com.alibaba.druid.filter.stat.StatFilter.statementPrepareAfter(StatFilter.java:310)
	at com.alibaba.druid.filter.FilterEventAdapter.connection_prepareStatement(FilterEventAdapter.java:124)
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:473)
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.prepareStatement(ConnectionProxyImpl.java:342)
	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:350)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.instantiateStatement(PreparedStatementHandler.java:79)
	at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:88)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.prepare(RoutingStatementHandler.java:58)
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:76)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:61)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:303)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:154)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:102)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:82)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:120)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:386)
	at com.sun.proxy.$Proxy22.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:205)
	at .....
```

**Comment by kingour** [comment]
补充：关闭mergeSql，错就不报了

**Comment by kingour** [comment]
关闭mergeSql后，报WARN：
```
11:22:52.425  WARN com.alibaba.druid.sql.SQLUtils:244 - format error
com.alibaba.druid.sql.parser.ParserException: ERROR. pos 516, line 21, column 36, token BAR
	at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:697)
	at com.alibaba.druid.sql.dialect.postgresql.parser.PGExprParser.primary(PGExprParser.java:122)
	at com.alibaba.druid.sql.parser.SQLExprParser.bitXorRest(SQLExprParser.java:184)
	at com.alibaba.druid.sql.parser.SQLExprParser.bitXorRest(SQLExprParser.java:151)
	at com.alibaba.druid.sql.parser.SQLExprParser.bitXor(SQLExprParser.java:134)
	at com.alibaba.druid.sql.parser.SQLExprParser.multiplicative(SQLExprParser.java:213)
	at com.alibaba.druid.sql.parser.SQLExprParser.additive(SQLExprParser.java:1577)
	at com.alibaba.druid.sql.parser.SQLExprParser.shift(SQLExprParser.java:1607)
	at com.alibaba.druid.sql.parser.SQLExprParser.bitAnd(SQLExprParser.java:1464)
	at com.alibaba.druid.sql.parser.SQLExprParser.bitOr(SQLExprParser.java:1478)
	at com.alibaba.druid.sql.parser.SQLExprParser.equality(SQLExprParser.java:1493)
	at com.alibaba.druid.sql.parser.SQLExprParser.relational(SQLExprParser.java:1757)
	at com.alibaba.druid.sql.parser.SQLExprParser.andRest(SQLExprParser.java:1644)
	at com.alibaba.druid.sql.parser.SQLExprParser.expr(SQLExprParser.java:109)
	at com.alibaba.druid.sql.parser.SQLSelectParser.expr(SQLSelectParser.java:697)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseWhere(SQLSelectParser.java:318)
	at com.alibaba.druid.sql.dialect.postgresql.parser.PGSelectParser.query(PGSelectParser.java:135)
	at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:50)
	at com.alibaba.druid.sql.dialect.postgresql.parser.PGSQLStatementParser.parseSelect(PGSQLStatementParser.java:237)
	at com.alibaba.druid.sql.dialect.postgresql.parser.PGSQLStatementParser.parseSelect(PGSQLStatementParser.java:41)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:133)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:70)
	at com.alibaba.druid.sql.SQLUtils.format(SQLUtils.java:240)
	at com.alibaba.druid.filter.logging.LogFilter.logExecutableSql(LogFilter.java:569)
	at com.alibaba.druid.filter.logging.LogFilter.statementExecuteAfter(LogFilter.java:466)
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_execute(FilterEventAdapter.java:442)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3049)
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_execute(FilterEventAdapter.java:440)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3049)
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.execute(PreparedStatementProxyImpl.java:168)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:494)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:62)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:78)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:303)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:154)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:102)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:82)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:120)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:386)
	at com.sun.proxy.$Proxy22.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:205)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:122)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:64)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:53)
```

**Comment by wenshao** [comment]
```
??|
```
这个操作符号是你自定义的么？

**Comment by kingour** [comment]
不是，pg里json查询支持?|操作，在mybatis里?被当做参数占位符了，所以需要转义，就成??了

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.4
问题已经修复，请使用新版本
