### ISSUE TITLE
初始化物理连接很慢，然后会报错

### ISSUE THREAD

**Issue by LUAgam** [alibaba/druid#2008]
1、如果initialSize为1或者更大，在启动时会很慢，然后报错
`Caused by: java.net.SocketException: Broken pipe
        at java.net.SocketOutputStream.socketWrite0(Native Method) ~[na:1.7.0_80]
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113) ~[na:1.7.0_80]
        at java.net.SocketOutputStream.write(SocketOutputStream.java:159) ~[na:1.7.0_80]
        at oracle.net.ns.DataPacket.send(DataPacket.java:199) ~[ojdbc6-ojdbc6-11.1.0.7.0-jar.jar:11.2.0.1.0]
        at oracle.net.ns.NetOutputStream.flush(NetOutputStream.java:211) ~[ojdbc6-ojdbc6-11.1.0.7.0-jar.jar:11.2.0.1.0]
        at oracle.net.ns.NetInputStream.getNextPacket(NetInputStream.java:227) ~[ojdbc6-ojdbc6-11.1.0.7.0-jar.jar:11.2.0.1.0]
        at oracle.net.ns.NetInputStream.read(NetInputStream.java:175) ~[ojdbc6-ojdbc6-11.1.0.7.0-jar.jar:11.2.0.1.0]
        at oracle.net.ns.NetInputStream.read(NetInputStream.java:100) ~[ojdbc6-ojdbc6-11.1.0.7.0-jar.jar:11.2.0.1.0]
        at oracle.net.ns.NetInputStream.read(NetInputStream.java:85) ~[ojdbc6-ojdbc6-11.1.0.7.0-jar.jar:11.2.0.1.0]
        at oracle.jdbc.driver.T4CSocketInputStreamWrapper.readNextPacket(T4CSocketInputStreamWrapper.java:122) ~[ojdbc6-ojdbc6-11.1.0.7.0-jar.jar:11.2.0.1.0]
        at oracle.jdbc.driver.T4CSocketInputStreamWrapper.read(T4CSocketInputStreamWrapper.java:78) ~[ojdbc6-ojdbc6-11.1.0.7.0-jar.jar:11.2.0.1.0]
        at oracle.jdbc.driver.T4CMAREngine.unmarshalUB1(T4CMAREngine.java:1179) ~[ojdbc6-ojdbc6-11.1.0.7.0-jar.jar:11.2.0.1.0]
        at oracle.jdbc.driver.T4CMAREngine.unmarshalSB1(T4CMAREngine.java:1155) ~[ojdbc6-ojdbc6-11.1.0.7.0-jar.jar:11.2.0.1.0]
        at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:279) ~[ojdbc6-ojdbc6-11.1.0.7.0-jar.jar:11.2.0.1.0]
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:186) ~[ojdbc6-ojdbc6-11.1.0.7.0-jar.jar:11.2.0.1.0]
        at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:366) ~[ojdbc6-ojdbc6-11.1.0.7.0-jar.jar:11.2.0.1.0]
        at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:752) ~[ojdbc6-ojdbc6-11.1.0.7.0-jar.jar:11.2.0.1.0]
        at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:359) ~[ojdbc6-ojdbc6-11.1.0.7.0-jar.jar:11.2.0.1.0]
`
2、如果initialSize为0，则启动会很快，不报错

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.4
请使用新版本，新加了一个配置asyncInit，看是否是你想要的
```java
dataSource.setAsyncInit(true);
```
