### ISSUE TITLE
druid1.0.29长时间不访问应用，再访问就连接不上数据库了，不会自动重连

### ISSUE THREAD

**Issue by daaao** [alibaba/druid#2010]
druid版本：1.0.29
数据库版本：MySQL5.7.14

有用搜索引擎找过解决方法，但没有效果，只能来求助了，谢谢了
MySQL的wait_timeout值是：2147483

连接池配置如下：

> jdbc.maxActive = 20
jdbc.initialSize = 1
jdbc.maxWait = 60000
jdbc.minIdle = 10
jdbc.maxIdle = 15
jdbc.timeBetweenEvictionRunsMillis = 60000
jdbc.minEvictableIdleTimeMillis = 300000
jdbc.validationQuery = SELECT 'x'
jdbc.testWhileIdle = true
jdbc.testOnBorrow = false
jdbc.testOnReturn = false
jdbc.maxOpenPreparedStatements = 20
jdbc.removeAbandoned = true
jdbc.removeAbandonedTimeout = 1800
jdbc.logAbandoned = true

错误信息如下：
`2017-09-26 00:00:02 ERROR com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(2103) : create connection error, url: jdbc:mysql://192.168.1.111:3306/app-dev?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull, errorCode 0, state 08S01
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.GeneratedConstructorAccessor76.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:981)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:339)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2253)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2286)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2085)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:795)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
	at sun.reflect.GeneratedConstructorAccessor74.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:327)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:148)
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:220)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:142)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1463)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1525)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2100)
Caused by: java.net.SocketException: No buffer space available (maximum connections reached?): connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:298)
	... 17 more`

**Comment by gradysong** [comment]
加 keepAlive  试试，保持下链接

**Comment by izhijian** [comment]
@gradysong 好的，谢谢，但 keepAlive 应该夹在哪里呢？连接池配置吗？

**Comment by winters1224** [comment]
我遇到过类似问题，把testOnBorrow和testOnIdle都设置为true之后解决了。你可以试试看。druid版本1.1.1

**Comment by izhijian** [comment]
@winters1224 我试试看，谢谢

**Comment by baixiaodong** [comment]
@izhijian  试了么，好用不

**Comment by izhijian** [comment]
@baixiaodong 现在暂时没出现这个错误，我后面把服务器重装了一下，参数也按那个改了

**Comment by dawangdedawang5** [comment]
@winters1224 不推荐将这两个参数设置为true,会影响性能。具体可以查看http://www.litianhua.net/blog/druid-monitor.html。

**Comment by lizongbo** [comment]
请升级到最新版验证
