### ISSUE TITLE
druid-spring-boot-starter 1.1.3

### ISSUE THREAD

**Issue by fyname** [alibaba/druid#2012]
Caused by: java.lang.ClassNotFoundException: com.alibaba.druid.filter.logging.Log4j2Filter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by wenshao** [comment]
没有依赖druid？

**Comment by radishlee** [comment]
解决了吗？同遇到这个问题

**Comment by pengshoulian** [comment]
druid版本太低了
