### ISSUE TITLE
SELECT t_aid, t_title, t_path, t_datetime, t_total FROM t_article WHERE t_state = ? order by t_total desc limit ?,?  这个语法哪里错了， 结果很正常，什么都正常，就是平白无故的报个语法错误！

### ISSUE THREAD

**Issue by thousmile** [alibaba/druid#2016]
2017-09-29 00:55:44.070 |-ERROR [http-nio-8080-exec-9] com.alibaba.druid.filter.stat.StatFilter [151] -| merge sql error, dbType com.alibaba.druid.pool.DruidDataSource, sql : SELECT t_aid, t_title, t_path, t_datetime, t_total FROM t_article WHERE t_state = ? order by t_total desc limit ?,?
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'desc limit ?,?',expect IDENTIFIER, actual IDENTIFIER limit
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:239)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:362)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:79)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:74)
	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:49)
	at com.alibaba.druid.filter.stat.StatFilter.mergeSql(StatFilter.java:149)
	at com.alibaba.druid.filter.stat.StatFilter.createSqlStat(StatFilter.java:638)
	at com.alibaba.druid.filter.stat.StatFilter.statementPrepareAfter(StatFilter.java:314)
	at com.alibaba.druid.filter.FilterEventAdapter.connection_prepareStatement(FilterEventAdapter.java:124)
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:448)
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.prepareStatement(ConnectionProxyImpl.java:342)
	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:346)

**Comment by wenshao** [comment]
你这个是手动配置dbType错误了吧？

**Comment by thousmile** [comment]
我是手动配置的！但是为什么报错了。但是结果正常，什么都正常。就是报个错！说我语法错误！ 而我的语法在 其他mysql 客户端执行都正常！

**Comment by thousmile** [comment]
还有就是，我只要我用 
 SELECT t_cid,t_aid,t_content,t_datetime,t_father,t_uid,t_total
		FROM t_comment
		WHERE t_father = ? ORDER BY t_total DESC LIMIT
		?
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'DESC LIMIT
		?',expect IDENTIFIER, actual IDENTIFIER LIMIT
好像只要我用  DESC LIMIT 这两个，就会报错。但是结果都是正常的！

**Comment by wenshao** [comment]
dbType能配置为mysql或者不配置么
