### ISSUE TITLE
不支持 MySQL 建表时存在索引

### ISSUE THREAD

**Issue by lg-Cat73** [alibaba/druid#2028]
我在单元测试的时候用的会重新初始化测试数据库已便保证是测试所需的结构和数据。

然而在建表的时候抛错了，语句如下：

```sql
DROP TABLE IF EXISTS `admin`;
CREATE TABLE `admin` (
  `id` char(20) NOT NULL,
  `username` varchar(16) NOT NULL COMMENT '用户名',
  `password` varchar(32) NOT NULL COMMENT '密码',
  `permission` varchar(255) NOT NULL DEFAULT '' COMMENT '权限',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='管理员';
```
错误如下：
```sql
Caused by: java.sql.SQLException: sql injection violation, syntax error: syntax error, error in :'id`) USING BTREE ) ENGINE=InnoDB DE', expect RPAREN, actual IDENTIFIER pos 224, line 1, column 219, token IDENTIFIER USING : CREATE TABLE `admin` ( `id` char(20) NOT NULL, `username` varchar(16) NOT NULL COMMENT '用户名', `password` varchar(32) NOT NULL COMMENT '密码', `permission` varchar(255) NOT NULL DEFAULT '' COMMENT '权限', PRIMARY KEY (`id`) USING BTREE ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='管理员'
	at com.alibaba.druid.wall.WallFilter.checkInternal(WallFilter.java:798)
	at com.alibaba.druid.wall.WallFilter.check(WallFilter.java:780)
	at com.alibaba.druid.wall.WallFilter.statement_execute(WallFilter.java:413)
	at com.alibaba.druid.filter.FilterChainImpl.statement_execute(FilterChainImpl.java:2598)
	at com.alibaba.druid.filter.FilterAdapter.statement_execute(FilterAdapter.java:2473)
	at com.alibaba.druid.filter.FilterEventAdapter.statement_execute(FilterEventAdapter.java:188)
	at com.alibaba.druid.filter.FilterChainImpl.statement_execute(FilterChainImpl.java:2598)
	at com.alibaba.druid.proxy.jdbc.StatementProxyImpl.execute(StatementProxyImpl.java:147)
	at com.alibaba.druid.pool.DruidPooledStatement.execute(DruidPooledStatement.java:497)
	at org.springframework.jdbc.datasource.init.ScriptUtils.executeSqlScript(ScriptUtils.java:470)
	... 116 more
Caused by: com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'id`) USING BTREE ) ENGINE=InnoDB DE', expect RPAREN, actual IDENTIFIER pos 224, line 1, column 219, token IDENTIFIER USING
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:285)
	at com.alibaba.druid.sql.parser.SQLParser.accept(SQLParser.java:293)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlCreateTableParser.parseCreateTable(MySqlCreateTableParser.java:189)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseCreate(MySqlStatementParser.java:224)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:157)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:79)
	at com.alibaba.druid.wall.WallProvider.checkInternal(WallProvider.java:622)
	at com.alibaba.druid.wall.WallProvider.check(WallProvider.java:576)
	at com.alibaba.druid.wall.WallFilter.checkInternal(WallFilter.java:785)
	... 125 more
```
Druid 版本：
```
<dependency>
    <groupId>com.alibaba</groupId>
    <artifactId>druid-spring-boot-starter</artifactId>
    <version>1.1.4</version>
    <scope>runtime</scope>
</dependency>
```

**Comment by Cat7373** [comment]
说不定 ALERT 增加索引也有这问题，我没测，可以一起测一下

**Comment by wenshao** [comment]
问题重现并修复，谢谢反馈，等下一个版本发布吧，预计在两个星期后。如果着急，可以自行编译一个版本。

**Comment by lg-Cat73** [comment]
我这个是 Navicat 直接导出来的 SQL。。
感谢 0.0
