### ISSUE TITLE
hql 解析报错

### ISSUE THREAD

**Issue by mechine** [alibaba/druid#2051]
脚本内容：
```
drop table if EXISTS test.test;
create table if not EXISTS test.test stored as parquet as
select *  from test.test;
```
程序片段：
```
 String dbType = JdbcConstants.HIVE; 
 List<SQLStatement> stmtList = SQLUtils.parseStatements(sql, dbType);
```
错误信息：
```
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'e if EXISTS test.test;
create table', expect EXISTS, actual EXISTS pos 21, line 2, column 15, token EXISTS
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:285)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:395)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:68)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:461)
	at com.sf.open.tools.DruidTest.main(DruidTest.java:38)
```
版本：
 <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid</artifactId>
            <version>1.1.4</version>
        </dependency>

**Comment by wenshao** [comment]
已支持，等下一个版本吧，也许在下个周末发布新版本

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.5 问题已修复，请用新版本

**Comment by thorntree** [comment]
@wenshao 你好，能帮忙看一下[#3575 ](https://github.com/alibaba/druid/issues/3575)
