### ISSUE TITLE
postgresql   ANY(ARRAY[n,m,.....]) ParserException

### ISSUE THREAD

**Issue by isbogey** [alibaba/druid#2063]
version : 1.1.4
 SELECT COL1 from TABLE where NID = ANY(ARRAY[1,2,3])

error:
com.alibaba.druid.sql.parser.ParserException: syntax error, expect RPAREN, actual ARRAY pos 44, line 1, column 40, token ARRAY
	at com.alibaba.druid.sql.parser.SQLExprParser.accept(SQLExprParser.java:2249)
	at com.alibaba.druid.sql.parser.SQLExprParser.parseAny(SQLExprParser.java:772)
	at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:682)
	at com.alibaba.druid.sql.dialect.postgresql.parser.PGExprParser.primary(PGExprParser.java:114)
	at com.alibaba.druid.sql.parser.SQLExprParser.bitXor(SQLExprParser.java:134)
	at com.alibaba.druid.sql.parser.SQLExprParser.multiplicative(SQLExprParser.java:214)
	at com.alibaba.druid.sql.parser.SQLExprParser.additive(SQLExprParser.java:1632)
	at com.alibaba.druid.sql.parser.SQLExprParser.shift(SQLExprParser.java:1662)
	at com.alibaba.druid.sql.parser.SQLExprParser.bitAnd(SQLExprParser.java:1509)
	at com.alibaba.druid.sql.parser.SQLExprParser.bitOr(SQLExprParser.java:1523)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseWhere(SQLSelectParser.java:345)
	at com.alibaba.druid.sql.dialect.postgresql.parser.PGSelectParser.query(PGSelectParser.java:136)
	at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:58)
	at com.alibaba.druid.sql.dialect.postgresql.parser.PGSQLStatementParser.parseSelect(PGSQLStatementParser.java:234)
	at com.alibaba.druid.sql.dialect.postgresql.parser.PGSQLStatementParser.parseSelect(PGSQLStatementParser.java:38)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:145)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:68)
	at com.druid.TestDruidSqlParser.main(TestDruidSqlParser.java:14)

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.5 问题已修复，请用新版本

**Comment by iamlufy** [comment]
使用最新版本还是会出现这个啊。。

**Comment by qrqhuang** [comment]
我想知道， 有没有方式，单独屏蔽掉某条SQL的解析。
