### ISSUE TITLE
不能解析DDL语句中的CHECK 和 FOREIGN KEY 

### ISSUE THREAD

**Issue by long187** [alibaba/druid#2065]
```
CREATE TABLE IF NOT EXISTS `test_table_normal`(  
scoreID INTEGER NOT NULL PRIMARY KEY,  
stuID     INTEGER NOT NULL,  
KEMUID     INTEGER NOT NULL,  
score     FLOAT,  
FOREIGN KEY SCORE_ID_FK (stuID) REFERENCES students (stuid),  
CONSTRAINT CHK_SCORE_ZIP CHECK (SCORE > 0)  
);  
```
报错：
```
com.alibaba.druid.sql.parser.ParserException: TODO. pos 263, line 7, column 26, token CHECK

	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlCreateTableParser.parseConstraint(MySqlCreateTableParser.java:862)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlCreateTableParser.parseCreateTable(MySqlCreateTableParser.java:125)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseCreate(MySqlStatementParser.java:224)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:157)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:68)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:461)
```

```
ALTER TABLE test_table_normal
ADD FOREIGN KEY (stuID)
REFERENCES Persons(stuID);
```

报错：
```
com.alibaba.druid.sql.parser.ParserException: error pos 41, line 2, column 5, token FOREIGN

	at com.alibaba.druid.sql.parser.SQLExprParser.name(SQLExprParser.java:1210)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.parseColumn(MySqlExprParser.java:472)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseAlterTableAddColumn(MySqlStatementParser.java:2980)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseAlterTable(MySqlStatementParser.java:2583)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseAlter(MySqlStatementParser.java:2455)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:187)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:68)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:461)
```

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.5 问题已修复，请用新版本
