### ISSUE TITLE
format mysql建表语句遇到索引有注释报错

### ISSUE THREAD

**Issue by honganan** [alibaba/druid#2080]
```sql
CREATE TABLE `g_platform_payway` (
	`id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'id', 
	`platform_code` varchar(45) NOT NULL, 
	`pay_way` varchar(32) NOT NULL, 
	PRIMARY KEY (`id`), 
	UNIQUE `uniq_playform_payway` USING BTREE (`platform_code`, `pay_way`) COMMENT '平台code和支付方式应该唯一'
) ENGINE = InnoDB CHARSET = utf8 COMMENT = '配置表'
```
如上sql中唯一索引后带有comment...时会格式化出错，格式化代码如下所示：
```java
MySqlStatementParser parser = new MySqlStatementParser(sql3);
SQLStatement statement = parser.parseStatement();
```
报错信息如下所示：
```
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'TREE COMMENT '平台code和支付方式应该唯一'
) EN',expect RPAREN, actual COMMENT COMMENT
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:239)
	at com.alibaba.druid.sql.parser.SQLParser.accept(SQLParser.java:247)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlCreateTableParser.parseCrateTable(MySqlCreateTableParser.java:182)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseCreate(MySqlStatementParser.java:341)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:193)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:2036)
```

**Comment by wenshao** [comment]
问题重现并修复，等下一个版本发布吧，如果着急可以自行编译一个版本。
```
mvn clean install -Dmaven.test.skip
```

**Comment by honganan** [comment]
@wenshao 我在做一个SQL审核平台和数据查询平台，其中多处用到druid格式化工具类，这个场景在jsqlparser中也不支持
