### ISSUE TITLE
连接10版本的postgresql报错：Error creating bean with name 'dataSource' defined in class path resource [spring-jdbc.xml]: Invocation of init method failed; nested exception is org.postgresql.util.PSQLException: 这个 ResultSet 已经被关闭。

### ISSUE THREAD

**Issue by gisdream** [alibaba/druid#2081]
使用druid版本：1.1.5，连接postgresql 10.0-1版本的数据库时报错
环境：win7-64
语言：java
Error creating bean with name 'dataSource' defined in class path resource [spring-jdbc.xml]: Invocation of init method failed; nested exception is org.postgresql.util.PSQLException: 这个 ResultSet 已经被关闭。
查看paAdmin，可以看到有pg driver的连接，但是无法在项目中启动，换org.apache.commons.dbcp.BasicDataSource就没问题，怀疑是druid无法初始化这个postgresql的版本为datasource，有时间调试源码确认下，在这先提交个issues

**Comment by wenshao** [comment]
能提供一下完整堆栈么？

**Comment by gisdream** [comment]
[ERROR] 2017-11-03 14:40:54,347 method:com.alibaba.druid.pool.DruidDataSource.put(DruidDataSource.java:1808)
create connection holder error
org.postgresql.util.PSQLException: 这个 ResultSet 已经被关闭。
	at org.postgresql.jdbc2.AbstractJdbc2ResultSet.checkClosed(AbstractJdbc2ResultSet.java:2852)
	at org.postgresql.jdbc2.AbstractJdbc2ResultSet.setFetchSize(AbstractJdbc2ResultSet.java:1875)
	at org.postgresql.jdbc4.Jdbc4Statement.createResultSet(Jdbc4Statement.java:37)
	at org.postgresql.jdbc2.AbstractJdbc2Statement$StatementResultHandler.handleResultRows(AbstractJdbc2Statement.java:221)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1853)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.execSQLUpdate(AbstractJdbc2Connection.java:382)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.getTransactionIsolation(AbstractJdbc2Connection.java:904)
	at com.alibaba.druid.filter.FilterChainImpl.connection_getTransactionIsolation(FilterChainImpl.java:347)
	at com.alibaba.druid.filter.FilterAdapter.connection_getTransactionIsolation(FilterAdapter.java:871)
	at com.alibaba.druid.filter.FilterChainImpl.connection_getTransactionIsolation(FilterChainImpl.java:344)
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.getTransactionIsolation(ConnectionProxyImpl.java:260)
	at com.alibaba.druid.pool.DruidConnectionHolder.<init>(DruidConnectionHolder.java:116)
	at com.alibaba.druid.pool.DruidConnectionHolder.<init>(DruidConnectionHolder.java:75)
	at com.alibaba.druid.pool.DruidDataSource.put(DruidDataSource.java:1798)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2041)
[INFO ] 2017-11-03 14:40:54,367 method:com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2044)
put physical connection to pool failed.
[ERROR] 2017-11-03 14:40:54,471 method:com.alibaba.druid.pool.DruidDataSource.put(DruidDataSource.java:1808)
create connection holder error
org.postgresql.util.PSQLException: 这个 ResultSet 已经被关闭。
	at org.postgresql.jdbc2.AbstractJdbc2ResultSet.checkClosed(AbstractJdbc2ResultSet.java:2852)
	at org.postgresql.jdbc2.AbstractJdbc2ResultSet.setFetchSize(AbstractJdbc2ResultSet.java:1875)
	at org.postgresql.jdbc4.Jdbc4Statement.createResultSet(Jdbc4Statement.java:37)
	at org.postgresql.jdbc2.AbstractJdbc2Statement$StatementResultHandler.handleResultRows(AbstractJdbc2Statement.java:221)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1853)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.execSQLUpdate(AbstractJdbc2Connection.java:382)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.getTransactionIsolation(AbstractJdbc2Connection.java:904)
	at com.alibaba.druid.filter.FilterChainImpl.connection_getTransactionIsolation(FilterChainImpl.java:347)
	at com.alibaba.druid.filter.FilterAdapter.connection_getTransactionIsolation(FilterAdapter.java:871)
	at com.alibaba.druid.filter.FilterChainImpl.connection_getTransactionIsolation(FilterChainImpl.java:344)
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.getTransactionIsolation(ConnectionProxyImpl.java:260)
	at com.alibaba.druid.pool.DruidConnectionHolder.<init>(DruidConnectionHolder.java:116)
	at com.alibaba.druid.pool.DruidConnectionHolder.<init>(DruidConnectionHolder.java:75)
	at com.alibaba.druid.pool.DruidDataSource.put(DruidDataSource.java:1798)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2041)
[INFO ] 2017-11-03 14:40:54,476 method:com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2044)
put physical connection to pool failed.

**Comment by targei** [comment]
请问这个问题解决了吗？ 我今天调试了一下午，用的是1.1.6/5/4等多个版本。连接postgresql10的时候有问题，但是连接postgresql 9.6 就没有问题。异常与上面相同。 

我的调查发现： 在调用“select 'x' ”测试连接时，这个请求时没有问题的，能够正常返回结果。 
然后连接池会调用“com.alibaba.druid.filter.FilterChainImpl.connection_getTransactionIsolation“是，发起了一个sql查询”SHOW TRANSACTION ISOLATION level“。 但是这个sql查询设置的类型是 ”no data“，实际上在查询时正确的返回了结果 ”read commit“ ，但是由于这个标记的原因，后续处理就乱了，在new resultset的时候，没有，结果tuples为空。导致爆出了上面的按个错误”org.postgresql.util.PSQLException: 这个 ResultSet 已经被关闭“。 实际上这个错误是一个假象。 

我做了一下猜测并进行验证：
1. 怀疑postgresq驱动有问题，我看到druid使用的是9.3.  我在DBeaver上使用9.3驱动配置连接，可以连接成功。且执行命令 ”SHOW TRANSACTION ISOLATION level“ 也能正确返回 ”read commit“
所以确定驱动没有问题。 
2. 以为druid新版本没有问题了，尝试了最新的1.1.6，依然有问题。

**Comment by targei** [comment]
自己顶一下，修改为postgresql jdbc的最新驱动就可以了。 如果使用maven维护工程的话，在pom.xml中加上：
    
    <dependency>
      <groupId>com.alibaba</groupId>
      <artifactId>druid</artifactId>
      <version>1.1.6</version>
    </dependency>
    
    
    <dependency>
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>
      <version>42.1.4</version>
    </dependency>

**Comment by gisdream** [comment]
楼上的方法可行，但是需要jdk1.8版本，否则报错：
Exception sending context initialized event to listener instance of class org.springframework.web.context.ContextLoaderListener
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [spring-jdbc.xml]: Invocation of init method failed; nested exception is java.lang.UnsupportedClassVersionError: org/postgresql/Driver : Unsupported major.minor version 52.0 (unable to load class org.postgresql.Driver)

**Comment by gisdream** [comment]
然后我又试了druid版本：1.1.6，jdk1.7，
我用的驱动为：
<dependency>
			<groupId>postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<version>9.4.1208-jdbc42-atlassian-hosted</version>
</dependency>
下又报错如下：
[DEBUG] 2017-12-11 17:06:16,093 method:org.mybatis.spring.SqlSessionUtils.getSqlSession(SqlSessionUtils.java:99)
Creating a new SqlSession
[DEBUG] 2017-12-11 17:06:16,101 method:org.mybatis.spring.SqlSessionUtils.registerSessionHolder(SqlSessionUtils.java:150)
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@3ea3f4a1] was not registered for synchronization because synchronization is not active
[DEBUG] 2017-12-11 17:06:16,202 method:org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:110)
Fetching JDBC Connection from DataSource
[ERROR] 2017-12-11 17:06:16,361 method:com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2484)
create connection Error
java.lang.NoClassDefFoundError: java/time/temporal/TemporalField
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:320)
	at org.postgresql.Driver.makeConnection(Driver.java:406)
	at org.postgresql.Driver.connect(Driver.java:274)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:149)
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:218)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:143)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1512)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1575)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2450)
Caused by: java.lang.ClassNotFoundException: java.time.temporal.TemporalField
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1891)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1734)
	... 9 more
[DEBUG] 2017-12-11 17:06:24,509 method:org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:230)
Service http request on thread: Thread[http-bio-8090-exec-4,5,main]
[DEBUG] 2017-12-11 17:06:24,509 method:org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:243)
Create a new message for processing
[DEBUG] 2017-12-11 17:06:24,511 method:org.apache.cxf.transport.http.Headers.copyFromRequest(Headers.java:459)
Request Headers: {Accept=[*/*], accept-encoding=[gzip, deflate], accept-language=[zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2], Authorization=[***], connection=[keep-alive], content-type=[text/plain; charset=utf-8], host=[192.168.0.147:8090], origin=[http://192.168.0.147], Proxy-Authorization=[***], referer=[http://192.168.0.147/KDUMClient/MapClient/index.html], user-agent=[Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0]}
[DEBUG] 2017-12-11 17:06:24,512 method:org.apache.cxf.phase.PhaseInterceptorChain.add(PhaseInterceptorChain.java:243)
Adding interceptor org.apache.cxf.transport.https.CertConstraintsInterceptor@3f5108b2 to phase pre-stream
[DEBUG] 2017-12-11 17:06:24,512 method:org.apache.cxf.phase.PhaseInterceptorChain.outputChainToLog(PhaseInterceptorChain.java:733)
Chain org.apache.cxf.phase.PhaseInterceptorChain@15247231 was created. Current flow:
  pre-stream [CertConstraintsInterceptor]
  unmarshal [JAXRSInInterceptor]
  pre-logical [OneWayProcessorInterceptor]
  invoke [ServiceInvokerInterceptor]
  post-invoke [OutgoingChainInterceptor]

**Comment by targei** [comment]
@gisdream 是的，我现在都是用1.8的。那个驱动也是jdk1.8下的驱动。 如果环境是1.7的，没法变更，只能再找找1.7的最新jdbc驱动。 
据我了解，jdbc的驱动分成支持1.6，1.7，1.8的，都是分开的。 每个系列都应该有最新的版本吧。

**Comment by wenshao** [comment]
看起来像是PG Driver的问题，我手上没有PG10的环境，要晚些时间跟进
