### ISSUE TITLE
Mysql parser 对 Alter table add foreign key报错

### ISSUE THREAD

**Issue by long187** [alibaba/druid#2082]
```
ALTER TABLE test_table_normal
ADD FOREIGN KEY (stuID)
REFERENCES Persons(stuID);
```

```
com.alibaba.druid.sql.parser.ParserException: error pos 41, line 2, column 5, token FOREIGN

	at com.alibaba.druid.sql.parser.SQLExprParser.name(SQLExprParser.java:1320)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.parseColumn(MySqlExprParser.java:492)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseAlterTableAddColumn(MySqlStatementParser.java:3865)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseAlterTable(MySqlStatementParser.java:3457)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseAlter(MySqlStatementParser.java:2699)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:189)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:70)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:461)
```

**Comment by wenshao** [comment]
问题重现并修复，等下一个版本发布吧，如果着急可以自行编译一个版本。
```
mvn clean install -Dmaven.test.skip
```

**Comment by long187** [comment]
让分库分表proxy支持DDL

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.6
问题已修复，请用新版本

**Comment by ryanwang21** [comment]
CREATE TABLE `gsp_order` (

  `id` int(11) NOT NULL AUTO_INCREMENT,

  `spare_num` int(11) NOT NULL COMMENT '????',

  `coupon` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT '????',

  `remark` varchar(255) DEFAULT NULL COMMENT '??',

  `creator_id` int(11) NOT NULL COMMENT '???ID',

  `last_operator` varchar(16) DEFAULT NULL COMMENT '???????',

  `createtime` datetime NOT NULL COMMENT '????',

  `updatetime` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '????????',

  `is_del` tinyint(1) NOT NULL DEFAULT '0' COMMENT '?????0????1?????',

  PRIMARY KEY (`id`),

  KEY `creator_id` (`creator_id`),

  KEY `id` (`id`,`is_del`),

  KEY `order_id` (`order_id`),

  CONSTRAINT `gsp_order2_details_ibfk_2` FOREIGN KEY (`creator_id`) REFERENCES `gsp_sys_users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION

) ENGINE=InnoDB AUTO_INCREMENT=84608 DEFAULT CHARSET=utf8

com.alibaba.druid.sql.parser.ParserException: syntax error, expect ACTION, actual IDENTIFIER pos 1878, line 33, column 113, token IDENTIFIER NO

        at com.alibaba.druid.sql.parser.SQLExprParser.parseReferenceOption(SQLExprParser.java:2688) ~[druid-1.1.7-preview_0.jar:1.1.7-preview_0]

        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.parseForeignKey(MySqlExprParser.java:824) ~[druid-1.1.7-preview_0.jar:1.1.7-prev

iew_0]
wen shao ,还是有外键这个问题，这个是我使用的cannal，他使用的druid-1.1.7-preview，我看到你这边是1.1.6版本支持外键。请文是因为Cannal使用的druid(1.1.7-preview)是自己限制了外键的一个版本吗
谢谢

**Comment by wenshao** [comment]
@ryanwang21  问题已经修复，我争取在周末发布新版本

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.7
问题修复，请用新版本
