### ISSUE TITLE
线上一直出现execute() is called on closed statement问题求助

### ISSUE THREAD

**Issue by smileMrLee** [alibaba/druid#2098]
#### 线上频繁出现error日志
![image](https://user-images.githubusercontent.com/10806592/32485518-546b1484-c369-11e7-8077-fd303c5b843a.png)
#### 已定位到是由于连接关闭造成
![image](https://user-images.githubusercontent.com/10806592/32485570-85b41478-c369-11e7-9c2e-5bd1c7f1d8b7.png)
#### 求助
+ 怎么预防这个问题，是配置用得不对吗？看起来问题是因为数据库连接池没有把已经关闭的连接回收掉，造成的。而且不重启应用的话，坏掉的连接一直不会被回收。
druid版本：1.0.28
mysql：阿里云rds mysql 5.6
多谢了！

**Comment by wenshao** [comment]
升级到druid-1.1.5版本试试看

**Comment by paomian** [comment]
我觉得这个问题在 1.1.5 并没有修复，我同样的配置，在 1.1.5 上遇见了同样的错误。

```
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 79,381 milliseconds ago.  The last packet sent successfully to the server was 19,366 milliseconds ago.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:989)
	at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3746)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2509)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
```

和这个一样 https://github.com/alibaba/druid/issues/2046

**Comment by SummerSunC** [comment]
这个是druid老版本的bug ,druid使用了preparedStatementPool,当发生异常时而没有及时释放preparedStatement导致的，这个问题已经在1.0.29中修复了
