### ISSUE TITLE
StackOverflowError occured while active stat or wall filter and execute batch insert action in Oracle

### ISSUE THREAD

**Issue by wanwaner** [alibaba/druid#2101]
#filters: stat,wall,slf4j
      filters: slf4j
   
UNION ALL 
      select ?,?,?,?,?,?,?,?,'HDY',sysdate,'HDY',sysdate,'1',null from dual
     UNION ALL 
      select ?,?,?,?,?,?,?,?,'HDY',sysdate,'HDY',sysdate,'1',null from dual
     UNION ALL 
      select ?,?,?,?,?,?,?,?,'HDY',sysdate,'HDY',sysdate,'1',null from dual
     UNION ALL 
      select ?,?,?,?,?,?,?,?,'HDY',sysdate,'HDY',sysdate,'1',null from dual
     UNION ALL 
      select ?,?,?,?,?,?,?,?,'HDY',sysdate,'HDY',sysdate,'1',null from dual
     UNION ALL 
      select ?,?,?,?,?,?,?,?,'HDY',sysdate,'HDY',sysdate,'1',null from dual
     UNION ALL 
      select ?,?,?,?,?,?,?,?,'HDY',sysdate,'HDY',sysdate,'1',null from dual
     UNION ALL 
      select ?,?,?,?,?,?,?,?,'HDY',sysdate,'HDY',sysdate,'1',null from dual
     UNION ALL 
      select ?,?,?,?,?,?,?,?,'HDY',sysdate,'HDY',sysdate,'1',null from dual
     UNION ALL 
      select ?,?,?,?,?,?,?,?,'HDY',sysdate,'HDY',sysdate,'1',null from dual
     UNION ALL 
      select ?,?,?,?,?,?,?,?,'HDY',sysdate,'HDY',sysdate,'1',null from dual
     UNION ALL 
      select ?,?,?,?,?,?,?,?,'HDY',sysdate,'HDY',sysdate,'1',null from dual
     UNION ALL 
      select ?,?,?,?,?,?,?,?,'HDY',sysdate,'HDY',sysdate,'1',null from dual
     UNION ALL 
      select ?,?,?,?,?,?,?,?,'HDY',sysdate,'HDY',sysdate,'1',null from dual
     UNION ALL 
      select ?,?,?,?,?,?,?,?,'HDY',sysdate,'HDY',sysdate,'1',null from dual
     UNION ALL 
      select ?,?,?,?,?,?,?,?,'HDY',sysdate,'HDY',sysdate,'1',null from dual
     UNION ALL 
      select ?,?,?,?,?,?,?,?,'HDY',sysdate,'HDY',sysdate,'1',null from dual
     UNION ALL 
      select ?,?,?,?,?,?,?,?,'HDY',sysdate,'HDY',sysdate,'1',null from dual
     UNION ALL 
      select ?,?,?,?,?,?,?,?,'HDY',sysdate,'HDY',sysdate,'1',null from dual
     UNION ALL 
      select ?,?,?,?,?,?,?,?,'HDY',sysdate,'HDY',sysdate,'1',null from dual
     UNION ALL 
      select ?,?,?,?,?,?,?,?,'HDY',sysdate,'HDY',sysdate,'1',null from dual
     UNION ALL 
      select ?,?,?,?,?,?,?,?,'HDY',sysdate,'HDY',sysdate,'1',null from dual
     UNION ALL 
      select ?,?,?,?,?,?,?,?,'HDY',sysdate,'HDY',sysdate,'1',null from dual
     UNION ALL 
      select ?,?,?,?,?,?,?,?,'HDY',sysdate,'HDY',sysdate,'1',null from dual
     UNION ALL 
      select ?,?,?,?,?,?,?,?,'HDY',sysdate,'HDY',sysdate,'1',null from dual
     UNION ALL 
      select ?,?,?,?,?,?,?,?,'HDY',sysdate,'HDY',sysdate,'1',null from dual
     UNION ALL 
      select ?,?,?,?,?,?,?,?,'HDY',sysdate,'HDY',sysdate,'1',null from dual
     UNION ALL 
      select ?,?,?,?,?,?,?,?,'HDY',sysdate,'HDY',sysdate,'1',null from dual
     UNION ALL 
      select ?,?,?,?,?,?,?,?,'HDY',sysdate,'HDY',sysdate,'1',null from dual
     UNION ALL 
      select ?,?,?,?,?,?,?,?,'HDY',sysdate,'HDY',sysdate,'1',null from dual
     UNION ALL 
      select ?,?,?,?,?,?,?,?,'HDY',sysdate,'HDY',sysdate,'1',null from dual
     UNION ALL 
      select ?,?,?,?,?,?,?,?,'HDY',sysdate,'HDY',sysdate,'1',null from dual
     UNION ALL 
      select ?,?,?,?,?,?,?,?,'HDY',sysdate,'HDY',sysdate,'1',null from dual
     UNION ALL 
      select ?,?,?,?,?,?,?,?,'HDY',sysdate,'HDY',sysdate,'1',null from dual
     UNION ALL 
      select ?,?,?,?,?,?,?,?,'HDY',sysdate,'HDY',sysdate,'1',null from dual
     UNION ALL 
      select ?,?,?,?,?,?,?,?,'HDY',sysdate,'HDY',sysdate,'1',null from dual
     UNION ALL 
      select ?,?,?,?,?,?,?,?,'HDY',sysdate,'HDY',sysdate,'1',null from dual
     UNION ALL 
      select ?,?,?,?,?,?,?,?,'HDY',sysdate,'HDY',sysdate,'1',null from dual
     UNION ALL 
      select ?,?,?,?,?,?,?,?,'HDY',sysdate,'HDY',sysdate,'1',null from dual
     UNION ALL 
      select ?,?,?,?,?,?,?,?,'HDY',sysdate,'HDY',sysdate,'1',null from dual
     )

java.lang.StackOverflowError
  at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:484)
  at java.lang.StringBuilder.append(StringBuilder.java:166)
  at java.lang.StringBuilder.append(StringBuilder.java:76)
  at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.print0(SQLASTOutputVisitor.java:292)
  at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.visit(SQLASTOutputVisitor.java:2106)
  at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.printExpr(SQLASTOutputVisitor.java:885)
  at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.visit(SQLASTOutputVisitor.java:1874)
  at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.printSelectList(SQLASTOutputVisitor.java:386)
  at com.alibaba.druid.sql.dialect.oracle.visitor.OracleOutputVisitor.visit(OracleOutputVisitor.java:399)
  at com.alibaba.druid.sql.dialect.oracle.ast.stmt.OracleSelectQueryBlock.accept0(OracleSelectQueryBlock.java:121)
  at com.alibaba.druid.sql.dialect.oracle.ast.stmt.OracleSelectQueryBlock.accept0(OracleSelectQueryBlock.java:113)
  at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:41)
  at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.visit(SQLASTOutputVisitor.java:2619)
  at com.alibaba.druid.sql.ast.statement.SQLUnionQuery.accept0(SQLUnionQuery.java:90)
  at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:41)
  at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.visit(SQLASTOutputVisitor.java:2633)
  at com.alibaba.druid.sql.ast.statement.SQLUnionQuery.accept0(SQLUnionQuery.java:90)
  at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:41)
  at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.visit(SQLASTOutputVisitor.java:2633)
  at com.alibaba.druid.sql.ast.statement.SQLUnionQuery.accept0(SQLUnionQuery.java:90)
  at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:41)
  at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.visit(SQLASTOutputVisitor.java:2633)
  at com.alibaba.druid.sql.ast.statement.SQLUnionQuery.accept0(SQLUnionQuery.java:90)
  at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:41)
  at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.visit(SQLASTOutputVisitor.java:2633)
  at com.alibaba.druid.sql.ast.statement.SQLUnionQuery.accept0(SQLUnionQuery.java:90)

**Comment by wenshao** [comment]
which version?
