### ISSUE TITLE
获取连接时java.sql.SQLException: interrupt

### ISSUE THREAD

**Issue by hunterwangwang** [alibaba/druid#2132]
@wenshao 你好，请帮忙看下，谢谢，druid1.1.5
Caused by: java.sql.SQLException: interrupt
	at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1356)
	at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1241)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4619)
	at com.alibaba.druid.filter.stat.StatFilter.dataSource_getConnection(StatFilter.java:680)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4615)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1219)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1211)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:105)
	at com.dangdang.ddframe.rdb.sharding.jdbc.ShardingConnection.getConnectionInternal(ShardingConnection.java:107)
	at com.dangdang.ddframe.rdb.sharding.jdbc.ShardingConnection.getConnection(ShardingConnection.java:64)
	at com.dangdang.ddframe.rdb.sharding.jdbc.ShardingPreparedStatement.routeSQL(ShardingPreparedStatement.java:167)
	at com.dangdang.ddframe.rdb.sharding.jdbc.ShardingPreparedStatement.execute(ShardingPreparedStatement.java:115)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:63)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at sun.reflect.GeneratedMethodAccessor155.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
	at com.sun.proxy.$Proxy146.query(Unknown Source)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:136)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at sun.reflect.GeneratedMethodAccessor394.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
----------------------------------------------------------------------------------
源码为DruidDataSource#getConnectionInternal 
      try {
            lock.lockInterruptibly();
        } catch (InterruptedException e) {
            connectErrorCount.incrementAndGet();
            throw new SQLException("interrupt", e);
        }
-----------------------------------------------------------
https://github.com/alibaba/druid/pull/1777 这个是类似的问题，已经把lock.lockInterruptibly()改成lock.lock()了， 请问这个是bug么？ 怎么办？

**Comment by wenshao** [comment]
申请连接的线程有调用interrupt，这个可以算bug，也可以不算哈

**Comment by hunterwangwang** [comment]
没看出来哪个地方调用了interrupt，能明示一下么，谢谢

**Comment by hunterwangwang** [comment]
@wenshao

**Comment by wenshao** [comment]
看一下堆栈的每个地方

**Comment by hunterwangwang** [comment]
好的 我看看 谢谢

**Comment by hunterwangwang** [comment]
@wenshao 如果我自己把lock.lockInterruptibly()改成lock.lock()， 会不会有什么影响？

**Comment by wenshao** [comment]
没影响

**Comment by hunterwangwang** [comment]
好的，多谢

**Comment by chenyanwork** [comment]
> @wenshao 如果我自己把lock.lockInterruptibly()改成lock.lock()， 会不会有什么影响？

这个你们改的源码吗，我也遇到了这个问题
