### ISSUE TITLE
sql

### ISSUE THREAD

**Issue by freeman983** [alibaba/druid#2140]
版本:1.1.3
d.sql.ast.statement.SQLUnionQuery.accept0(SQLUnionQuery.java:87) ~[stormjar.jar:na]
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:41) ~[stormjar.jar:na]
	at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.visit(SQLASTOutputVisitor.java:2477) ~[stormjar.jar:na]
	at com.alibaba.druid.sql.ast.statement.SQLUnionQuery.accept0(SQLUnionQuery.java:87) ~[stormjar.jar:na]
	...........省略n行
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:41) ~[stormjar.jar:na]
	at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.visit(SQLASTOutputVisitor.java:2477) ~[stormjar.jar:na]
[INFO 2017-11-27 03:00:38 c.a.j.u.JStormUtils:186 sa_bolt:36-BoltExecutors] Halting process: Async loop died!

版本: 1.1.5
at com.alibaba.druid.sql.ast.expr.SQLBinaryOpExpr.merge(SQLBinaryOpExpr.java:553) ~[stormjar.jar:na]
	at com.alibaba.druid.sql.ast.expr.SQLBinaryOpExpr.merge(SQLBinaryOpExpr.java:553) ~[stormjar.jar:na]
	.......省略n行
	at com.alibaba.druid.sql.ast.expr.SQLBinaryOpExpr.merge(SQLBinaryOpExpr.java:553) ~[stormjar.jar:na]
[INFO 2017-11-28 15:40:00 c.a.j.u.JStormUtils:186 sa_bolt:36-BoltExecutors] Halting process: Async loop died

我们是利用druid的 WallProvider.check 接口在jstorm中一些sql的防注入检测功能,由于sql数量比较大没有打印,应该是某个特殊的sql触发了这个bug,请温少看下.

**Comment by wenshao** [comment]
不提供SQL不好做诊断，能否提供一下SQL？
