### ISSUE TITLE
druid连接mysql时报错,连接不上

### ISSUE THREAD

**Issue by simonHome** [alibaba/druid#2143]
[2017-11-29 17:57:39.752 [1;31mERROR[0;39m Druid-ConnectionPool-Create-1824116547(com.alibaba.druid.pool.DruidDataSource)] create connection SQLException, url: jdbc:microsoft://192.168.0.1:1433;DatabaseName=test, errorCode 0, state null
java.sql.SQLException: connect error, url jdbc:microsoft://192.168.0.1:1433;DatabaseName=test, driverClass com.microsoft.sqlserver.jdbc.SQLServerDriver
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1537) ~[druid-1.1.5.jar:1.1.5]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2333) ~[druid-1.1.5.jar:1.1.5]

使用druid连接mysql数据库一直提示连接不上。
使用的druid版本是 1.0.29, 后来又升级到
<version>1.1.5</version> 
使用的驱动包是
<groupId>com.microsoft.sqlserver</groupId>
<artifactId>sqljdbc4</artifactId>
 <version>4.0</version>
连接配置是
jdbc:microsoft://192.168.0.1:1433;DatabaseName=test
配置的驱动是
 <property name="driverClassName" value="com.microsoft.sqlserver.jdbc.SQLServerDriver"/>
启动时获取不到d

**Comment by simonHome** [comment]
配置的驱动是
 <property name="driverClassName" value="com.microsoft.sqlserver.jdbc.SQLServerDriver"/>

**Comment by simonHome** [comment]
现在是不支持sqlserver了吗？

**Comment by CrackRen** [comment]
升级到1.1.6，配置写全他看看，我记得昨天我也碰到这个错误，后来升级后配置写完报了 超速值-1无效的错误，然后看了看源代码，配置还有一个没写，你把这个validationQueryTimeout加上试试

**Comment by zhangdong1024** [comment]
![Uploading image.png…]()
