### ISSUE TITLE
druid1.1.5版本不支持达梦数据吗？报错 dbType not support : dm

### ISSUE THREAD

**Issue by jxf114208** [alibaba/druid#2150]
`java.lang.IllegalStateException: dbType not support : dm, url jdbc:dm://127.0.0.1:5236/SYSDBA?useUnicode=true&characterEncoding=UTF-8
	at com.alibaba.druid.wall.WallFilter.init(WallFilter.java:159)
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:770)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1215)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1211)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:105)`

**Comment by wenshao** [comment]
只是SQL防火墙WallFilter不支持达梦

**Comment by smile-everyday** [comment]
那这个怎么解决啊？

**Comment by jinkunaier** [comment]
> 那这个怎么解决啊？
上面有说答案，配置druid时把filters配置项中的wall去掉就要以了。虽然不完美，但是还能用，还是希望druid能原生支持一下。

**Comment by jinkunaier** [comment]
> @smile-everyday 那这个怎么解决啊？
上面有说答案，配置druid时把filters配置项中的wall去掉就要以了。虽然不完美，但是还能用，还是希望druid能原生支持一下。

**Comment by hchdream** [comment]
1.1.9可以使用druid监控，但是我的服务是ssm，dm数据库会间歇性报错：网络通信异常，还在找问题

**Comment by yxd179** [comment]
spring:
    druid:
    filters: stat,wall,sfl4j
温馨提示* 可将wall不做配置，或者拓展DbType.class中init方法，将DbType中dm做为switch中case项......
