### ISSUE TITLE
sql parser 解析出错 ， DB2数据库中执行通过  

### ISSUE THREAD

**Issue by qifnegdie** [alibaba/druid#2169]
select to_char(current date **- 7 day** ,'yyyymmdd') from sysibm.dual
这个SQL语句在DB2 v9.7 执行通过。
经调试，这个SQL语句中 【-7 day】 会引起解析出错（不加的话不会报错）  ，报错信息：

```
com.alibaba.druid.sql.parser.ParserException: syntax error, expect RPAREN, actual IDENTIFIER pos 37, line 1, column 34, token IDENTIFIER day
	at com.alibaba.druid.sql.parser.SQLExprParser.accept(SQLExprParser.java:2375)
	at com.alibaba.druid.sql.parser.SQLExprParser.methodRest(SQLExprParser.java:1080)
	at com.alibaba.druid.sql.parser.SQLExprParser.parseSelectItem(SQLExprParser.java:2928)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseSelectList(SQLSelectParser.java:508)
	at com.alibaba.druid.sql.dialect.db2.parser.DB2SelectParser.query(DB2SelectParser.java:77)
	at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:59)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseSelect(SQLStatementParser.java:2371)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:147)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:70)
	at com.alibaba.druid.sql.SQLUtils.format(SQLUtils.java:255)
	at com.alibaba.druid.sql.SQLUtils.format(SQLUtils.java:241)
	at parse.db2.SelectParser.main(SelectParser.java:61)
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: syntax error, expect RPAREN, actual IDENTIFIER pos 37, line 1, column 34, token IDENTIFIER day
	at com.alibaba.druid.sql.parser.SQLExprParser.accept(SQLExprParser.java:2375)
	at com.alibaba.druid.sql.parser.SQLExprParser.methodRest(SQLExprParser.java:1080)
	at com.alibaba.druid.sql.parser.SQLExprParser.parseSelectItem(SQLExprParser.java:2928)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseSelectList(SQLSelectParser.java:508)
	at com.alibaba.druid.sql.dialect.db2.parser.DB2SelectParser.query(DB2SelectParser.java:77)
	at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:59)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseSelect(SQLStatementParser.java:2371)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:147)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:70)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:461)
	at parse.db2.SelectParser.main(SelectParser.java:63)
```

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.7
问题修复，请用新版本
