### ISSUE TITLE
PostgreSQL & MySQL 无法识别BEGIN 语法

### ISSUE THREAD

**Issue by blueswhisper** [alibaba/druid#2182]
**BEGIN** 语法是PostgreSQL的方言，[语法说明](https://www.postgresql.org/docs/9.6/static/sql-begin.html)

复现代码
```java
PGSQLStatementParser parser = new PGSQLStatementParser("BEGIN");
List<SQLStatement> statements = parser.parseStatementList();
```
直接抛错
```
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'BEGIN;', expect BEGIN, actual BEGIN pos 5, line 1, column 1, token BEGIN
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:284)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:421)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:70)
```

这是很基础的语法，PostgreSQL JDBC开启事务就是使用的**BEGIN**而不是**START TRANSACTION**
期待支持。

**Comment by blueswhisper** [comment]
不止PostgreSQL，MySQL的BEGIN语法也不支持。 

从代码看，是对MySQL的[BEGIN语法](https://dev.mysql.com/doc/refman/5.7/en/commit.html)理解错误，BEGIN和START TRANSACTION之间是或的关系，而不是START TRANSACTION包含BEGIN的关系，[出错代码](https://github.com/alibaba/druid/blob/master/src/main/java/com/alibaba/druid/sql/dialect/mysql/parser/MySqlStatementParser.java#L1966) 将BEGIN假定为了START TRANSACTION的后继SQL。

[这个PR](https://github.com/alibaba/druid/pull/1746) 提到的将BEGIN和START TRANSACTION拆开的事情，在最新的代码中没有看到。

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.8
问题已修复，请使用新版本
