### ISSUE TITLE
quartz连druid报错。应该如何配置烦请大神指点

### ISSUE THREAD

**Issue by chenhongdi** [alibaba/druid#2186]
[ERROR][2017-12-12 14:21:46.012][scheduler_QuartzSchedulerThread]:[An error occurred while scanning for the next triggers to fire.][org.quartz.core.ErrorLogger:2425]
org.quartz.JobPersistenceException: Couldn't acquire next trigger: Error [See nested exception: java.sql.SQLException: Error]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2860)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$40.execute(JobStoreSupport.java:2759)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$40.execute(JobStoreSupport.java:2757)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3799)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTriggers(JobStoreSupport.java:2756)
	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:272)
Caused by: java.sql.SQLException: Error
	at com.alibaba.druid.pool.DruidDataSource.handleConnectionException(DruidDataSource.java:1442)
	at com.alibaba.druid.pool.DruidPooledConnection.handleException(DruidPooledConnection.java:136)
	at com.alibaba.druid.pool.DruidPooledStatement.checkException(DruidPooledStatement.java:71)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:239)
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.selectTriggerToAcquire(StdJDBCDelegate.java:2613)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2800)
	... 5 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 9
	at oracle.jdbc.driver.T4CVarcharAccessor.saveDataFromOldDefineBuffers(T4CVarcharAccessor.java:358)
	at oracle.jdbc.driver.T4CPreparedStatement.saveDefineBuffersIfRequired(T4CPreparedStatement.java:485)
	at oracle.jdbc.driver.OracleStatement.prepareAccessors(OracleStatement.java:919)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1039)
	at oracle.jdbc.driver.T4CPreparedStatement.executeMaybeDescribe(T4CPreparedStatement.java:836)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1124)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3285)
	at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3329)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeQuery(FilterChainImpl.java:2830)
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_executeQuery(FilterEventAdapter.java:465)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeQuery(FilterChainImpl.java:2827)
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.executeQuery(PreparedStatementProxyImpl.java:182)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:228)
	... 7 more
[ERROR][2017-12-12 14:22:15.221][scheduler_QuartzSchedulerThread]:[An error occurred while scanning for the next triggers to fire.][org.quartz.core.ErrorLogger:2425]
org.quartz.JobPersistenceException: Couldn't acquire next trigger: Error [See nested exception: java.sql.SQLException: Error]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2860)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$40.execute(JobStoreSupport.java:2759)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$40.execute(JobStoreSupport.java:2757)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3799)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTriggers(JobStoreSupport.java:2756)
	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:272)
Caused by: java.sql.SQLException: Error
	at com.alibaba.druid.pool.DruidDataSource.handleConnectionException(DruidDataSource.java:1442)
	at com.alibaba.druid.pool.DruidPooledConnection.handleException(DruidPooledConnection.java:136)
	at com.alibaba.druid.pool.DruidPooledStatement.checkException(DruidPooledStatement.java:71)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:239)
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.selectTriggerToAcquire(StdJDBCDelegate.java:2613)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2800)
	... 5 more

**Comment by cc4dogman** [comment]
给个我的配置你参考下
<property name="quartzProperties">
            <props>
                <prop key="org.quartz.scheduler.instanceName">rank-scheduler</prop>
                <prop key="org.quartz.scheduler.instanceId">AUTO</prop>
                <prop key="org.quartz.dataSource">csy</prop>

                <prop key="org.quartz.dataSource.csy.connectionProvider.class">com.alibaba.druid.support.quartz.DruidQuartzConnectionProvider</prop>
                <prop key="org.quartz.dataSource.csy.url">${jdbc.url}</prop>
                <prop key="org.quartz.dataSource.csy.username" >${jdbc.username}</prop>
                <prop key="org.quartz.dataSource.csy.password">${jdbc.password}</prop>
                <prop key="org.quartz.dataSource.csy.maxActive">20</prop>
                <prop key="org.quartz.dataSource.csy.validationQuery">SELECT 'x'</prop>

                
                <prop key="org.quartz.threadPool.class">org.quartz.simpl.SimpleThreadPool</prop>
                <prop key="org.quartz.threadPool.threadCount">${job.threadpool.size:20}</prop>
                <prop key="org.quartz.threadPool.threadPriority">${job.threadpool.priority:5}</prop>
                
                <prop key="org.quartz.jobStore.driverDelegateClass">org.quartz.impl.jdbcjobstore.StdJDBCDelegate</prop>
                <prop key="org.quartz.jobStore.class">org.quartz.impl.jdbcjobstore.JobStoreTX</prop>
                <prop key="org.quartz.jobStore.dataSource">csy</prop>
                

                <prop key="org.quartz.jobStore.isClustered">true</prop>
                <prop key="org.quartz.jobStore.clusterCheckinInterval">15000</prop>
                <prop key="org.quartz.jobStore.maxMisfiresToHandleAtATime">${job.misfires.size:20}</prop>
                
                <prop key="org.quartz.jobStore.misfireThreshold">86400000000</prop>

                <prop key="org.quartz.jobStore.tablePrefix">QRTZ_</prop>

                <prop key="org.quartz.scheduler.batchTriggerAcquisitionMaxCount">5</prop>
                <prop key="org.quartz.scheduler.batchTriggerAcquisitionFireAheadTimeWindow">60000</prop>
                <prop key="org.quartz.scheduler.skipUpdateCheck">true</prop>

            </props>

        </property>


注意把csy改成你自己应用的名字，建议用JobStoreTX管理事务，CMT会使用当前的应用事务，如果任务多了这块会对本身应用的性能造成影响，唯一不好的是这块会面临应用事务失败，但任务还是添加成功，这块可以写个aop拦截下把对应逻辑放到Spring事务之后，代码我就不贴了，这块自行实现哈

**Comment by deguo** [comment]
@chenhongdi 请教下你最后如何解决的该问题

**Comment by lizongbo** [comment]
这个是数据库jdbc的问题，不是druid的问题
