### ISSUE TITLE
偶尔出现communications link failure during rollback(). transaction resolution unknown.

### ISSUE THREAD

**Issue by gundamff** [alibaba/druid#2197]
从1.1.3升级到1.1.6后 大概每10几分钟就会出现一次异常
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_131]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_131]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_131]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.40.jar!/:5.1.40]
        at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.40.jar!/:5.1.40]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:918) ~[mysql-connector-java-5.1.40.jar!/:5.1.40]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:897) ~[mysql-connector-java-5.1.40.jar!/:5.1.40]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:886) ~[mysql-connector-java-5.1.40.jar!/:5.1.40]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860) ~[mysql-connector-java-5.1.40.jar!/:5.1.40]
        at com.mysql.jdbc.ConnectionImpl.rollback(ConnectionImpl.java:4602) ~[mysql-connector-java-5.1.40.jar!/:5.1.40]
        at com.mysql.jdbc.ConnectionImpl.realClose(ConnectionImpl.java:4233) ~[mysql-connector-java-5.1.40.jar!/:5.1.40]
        at com.mysql.jdbc.ConnectionImpl.close(ConnectionImpl.java:1531) ~[mysql-connector-java-5.1.40.jar!/:5.1.40]
        at com.alibaba.druid.filter.FilterChainImpl.connection_close(FilterChainImpl.java:175) ~[druid-1.1.6.jar!/:1.1.6]
        at com.alibaba.druid.filter.stat.StatFilter.connection_close(StatFilter.java:261) ~[druid-1.1.6.jar!/:1.1.6]
        at com.alibaba.druid.filter.FilterChainImpl.connection_close(FilterChainImpl.java:171) ~[druid-1.1.6.jar!/:1.1.6]
        at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.close(ConnectionProxyImpl.java:115) ~[druid-1.1.6.jar!/:1.1.6]
        at com.alibaba.druid.util.JdbcUtils.close(JdbcUtils.java:73) [druid-1.1.6.jar!/:1.1.6]

-----------------------------
配置:
defaultAutoCommit=false
timeBetweenEvictionRunsMillis=60000
minEvictableIdleTimeMillis=30000
validationQuery=SELECT 'x'
testWhileIdle=true
testOnBorrow=true
testOnReturn=true

MySql5.7.17 wait_timeout  100

**Comment by xielaixiaohun** [comment]
看看加上autoReconnect=true&failOverReadOnly=false能不能解决，我配置的validation-query=SELECT 1 FROM DUAL，test-while-idle=true

**Comment by zongxingy** [comment]
1.1.9也会出现这个问题，请问有解决方法吗？

**Comment by cc4dogman** [comment]
1.1.10也有这个问题

**Comment by xielaixiaohun** [comment]
> 请问此问题有解决方案吗？

有的，我当时打印连接池信息发现默认是tomcat连接池，需要在启动是定义使用druid连接池

**Comment by xielaixiaohun** [comment]
我的解决方法：
1.打印连接池信息，看看是否是druid连接池 log.info("-----数据库连接池-----" + dataSource.getClass().toString());
2. /**
     * 初始化数据库连接池为Druid
     */
    @Bean
    @ConfigurationProperties("spring.datasource")
    @Primary
    public DataSource druidDataSource() {
        return new DruidDataSource();
    }

**Comment by gundamff** [comment]
打开auto commit会改善一点

**Comment by zhuojl** [comment]
版本：1.0.27
我们系统的情况是：服务器改了wait_timeout，而程序中的timeBetweenEvictionRunsMillis 和 minEvictableIdleTimeMillis 都没有相应的改低，所以当程序检测到链接失效进行关闭时，报了链接异常，本来这个异常日志是debug，而系统中的日志级别就是debug，所以有这样的日志，其实只要调高级别就行了？

**Comment by zhuojl** [comment]
defaultAutoCommit=true 能解决这个异常日志，具体原因，没有debug。
