### ISSUE TITLE
druid连接pg卡在testConnection

### ISSUE THREAD

**Issue by sunjun-csu** [alibaba/druid#2206]
我用mybatis+druid连接postgresql，之后会一直卡住，没有返回
线程堆栈如下:

 at java.net.SocketInputStream.socketRead0(Native Method)
 322         at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
 323         at java.net.SocketInputStream.read(SocketInputStream.java:171)
 324         at java.net.SocketInputStream.read(SocketInputStream.java:141)
 325         at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:143)
 326         at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:112)
 327         at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:71)
 328         at org.postgresql.core.PGStream.ReceiveChar(PGStream.java:272)
 329         at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1753)
 330         at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:348)
 331         - locked <0x00000000fd156378> (a org.postgresql.core.v3.QueryExecutorImpl)
 332         at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:545)
 333         at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:405)
 334         at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:285)
 335         at com.alibaba.druid.pool.vendor.PGValidConnectionChecker.isValidConnection(PGValidConnectionChecker.java:71)
 336         at com.alibaba.druid.pool.DruidAbstractDataSource.testConnectionInternal(DruidAbstractDataSource.java:1285)
 337         at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1052)
 338         at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4544)
 339         at com.alibaba.druid.filter.stat.StatFilter.dataSource_getConnection(StatFilter.java:662)
 340         at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4540)
 341         at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:990)
 342         at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:982)
 343         at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:102)
 344         at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111)
 345         at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:77)
 346         at org.mybatis.spring.transaction.SpringManagedTransaction.openConnection(SpringManagedTransaction.java:81)
 347         at org.mybatis.spring.transaction.SpringManagedTransaction.getConnection(SpringManagedTransaction.java:67)
 348         at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:315)
 349         at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:75)
 350         at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:48)
 351         at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:115)
 352         at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:75)
 353         at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:170)
 354         at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:157)

**Comment by sunjun-csu** [comment]
this is not caused by druid
