### ISSUE TITLE
1.1.6版本Druid连接MSSQLServer 2008 R2报错The query timeout value -1 is not valid.

### ISSUE THREAD

**Issue by xhhwc** [alibaba/druid#2210]
1.1.6版本Druid连接MSSQL Server 2008 R2报错：com.microsoft.sqlserver.jdbc.SQLServerException: The query timeout value -1 is not valid.经测试1.1.5版本的Druid无此问题；而1.1.6版本Druid连接MySQL数据库也没有问题。以下是完整的错误日志：
com.microsoft.sqlserver.jdbc.SQLServerException: The query timeout value -1 is not valid.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:227)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.setQueryTimeout(SQLServerStatement.java:1112)
	at com.alibaba.druid.pool.vendor.MSSQLValidConnectionChecker.isValidConnection(MSSQLValidConnectionChecker.java:47)
	at com.alibaba.druid.pool.DruidAbstractDataSource.validateConnection(DruidAbstractDataSource.java:1304)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1585)
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:854)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1221)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1217)

**Comment by beykery** [comment]
这个错误我也遇到了，我现在不得已使用1.1.5版本，这个版本没这个问题。

**Comment by ky2c** [comment]
配置一下**validationQueryTimeout**参数就可以了。

**Comment by caodianlong** [comment]
我也遇到了， 坑了好久

**Comment by wuyan2018** [comment]
我加了validationQueryTimeout也不起作用，spring boot 1.5.9 会循环不停的报错： ERROR c.alibaba.druid.pool.DruidDataSource - create connection SQLException, url: jdbc:sqlserver://localhost:1433;integratedSecurity=true;databaseName=checkinginMS, errorCode 0, state null
com.microsoft.sqlserver.jdbc.SQLServerException: The query timeout value -1 is not valid.
我连接是sql server ，windows 方式登录访问integratedSecurity=true，druid 1.1.5 没有这个问题。

**Comment by softboy99** [comment]
我也遇到了，设置了validationQueryTimeout，也不起作用

**Comment by Justonly5** [comment]
1.1.7 版本未配置validationQueryTimeout 会报相同错误.配置了validationQueryTimeout就OK了.

**Comment by wenshao** [comment]
以前也是不好的吧？

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.8
问题已修复，请使用新版本
