### ISSUE TITLE
mysql parser不支持对enum的解析

### ISSUE THREAD

**Issue by jasonhx140** [alibaba/druid#2220]
CREATE TABLE `public_history` (
  `id` int(10) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `v_id` int(11) DEFAULT NULL COMMENT 'version ID',
  `name` char(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL COMMENT '名称',
  `type` enum('日策略','周策略') CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL COMMENT '类型策略',
  `update_uid` int(10) NOT NULL,
  `update_time` datetime DEFAULT NULL,
  `create_uid` int(11) NOT NULL,
  `create_time` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COMMENT='历史'
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'策略') CHARACTER SET utf8 COLLATE utf', expect RPAREN, actual IDENTIFIER pos 327, line 5, column 49, token IDENTIFIER CHARACTER
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:284) ~[druid-1.1.6.jar:1.1.6]
	at com.alibaba.druid.sql.parser.SQLParser.accept(SQLParser.java:292) ~[druid-1.1.6.jar:1.1.6]
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlCreateTableParser.parseCreateTable(MySqlCreateTableParser.java:191) ~[druid-1.1.6.jar:1.1.6]
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseCreate(MySqlStatementParser.java:244) ~[druid-1.1.6.jar:1.1.6]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:159) ~[druid-1.1.6.jar:1.1.6]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:70) ~[druid-1.1.6.jar:1.1.6]
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:464) ~[druid-1.1.6.jar:1.1.6]
	at com.alibaba.druid.sql.repository.SchemaRepository.console(SchemaRepository.java:295) ~[druid-1.1.6.jar:1.1.6]

**Comment by jasonhx140** [comment]
版本：1.1.6

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.7
问题修复，请用新版本
