### ISSUE TITLE
 Bad URL format: Multiple values for property transportMode

### ISSUE THREAD

**Issue by Aubergines** [alibaba/druid#2246]
org.apache.hive.jdbc.JdbcUriParseException: Bad URL format: Multiple values for property ransportMode
	at org.apache.hive.jdbc.Utils.parseURL(Utils.java:350)
	at org.apache.hive.jdbc.HiveConnection.<init>(HiveConnection.java:132)
	at org.apache.hive.jdbc.HiveDriver.connect(HiveDriver.java:107)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)

url  jdbc:hive2://192.168.1.113:10001/default;transportMode=http;httpPath=cliservice

hive创建连接失败，使用DriverManager.getConnection(jdbc:hive2://192.168.1.113:10001/default;transportMode=http;httpPath=cliservice, USER, PASSWORD)  是没有问题的

**Comment by lizongbo** [comment]
应该是url拼写被转义导致，是hive的检查校验，与druid无关。
