### ISSUE TITLE
解析mysql重命名索引语句报错

### ISSUE THREAD

**Issue by JackEggie** [alibaba/druid#2251]
sql：
```
alter table test.table rename index idx_status to idx_status_2
```

exception：
```
com.alibaba.druid.sql.parser.ParserException: error pos 35, line 1, column 30, token INDEX
	at com.alibaba.druid.sql.parser.SQLExprParser.name(SQLExprParser.java:1081)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseAlterTable(MySqlStatementParser.java:2651)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseAlter(MySqlStatementParser.java:2429)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:185)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:78)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:419)
	at name.jacktang.JsqlparserTest.parse(JsqlparserTest.java:31)
	at name.jacktang.JsqlparserTest.access$000(JsqlparserTest.java:17)
	at name.jacktang.JsqlparserTest$1.load(JsqlparserTest.java:24)
	at name.jacktang.JsqlparserTest$1.load(JsqlparserTest.java:21)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3522)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2315)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2193)
	... 4 more
```

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.7
问题修复，请用新版本
