### ISSUE TITLE
SQLUtils解析mysql alter database、create schema、alter schema报错

### ISSUE THREAD

**Issue by JackEggie** [alibaba/druid#2258]
sql:
```
alter database test CHARACTER SET='big5' COLLATE='big5_chinese_ci'
```
error:
```
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'CTER SET='big5' COLLATE='big5_chine',expect IDENTIFIER, actual IDENTIFIER pos 29, line 1, column 30, token IDENTIFIER SET
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:280)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:385)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:78)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:419)
	at name.jacktang.JsqlparserTest.parse(JsqlparserTest.java:31)
	at name.jacktang.JsqlparserTest.access$000(JsqlparserTest.java:17)
	at name.jacktang.JsqlparserTest$1.load(JsqlparserTest.java:24)
	at name.jacktang.JsqlparserTest$1.load(JsqlparserTest.java:21)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3522)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2315)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2193)
	... 4 more
```

sql:
```
create schema src
```
error:
```
com.alibaba.druid.sql.parser.ParserException: TODO pos 13, line 1, column 7, token SCHEMA
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseCreate(MySqlStatementParser.java:365)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:155)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:78)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:419)
	at name.jacktang.JsqlparserTest.parse(JsqlparserTest.java:31)
	at name.jacktang.JsqlparserTest.access$000(JsqlparserTest.java:17)
	at name.jacktang.JsqlparserTest$1.load(JsqlparserTest.java:24)
	at name.jacktang.JsqlparserTest$1.load(JsqlparserTest.java:21)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3522)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2315)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2193)
	... 4 more
```

sql:
```
ALTER schema src CHARACTER SET='big5' COLLATE='big5_chinese_ci'
```
error:
```
com.alibaba.druid.sql.parser.ParserException: TODO pos 12, line 1, column 6, token SCHEMA
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseAlter(MySqlStatementParser.java:2436)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:185)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:78)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:419)
	at name.jacktang.JsqlparserTest.parse(JsqlparserTest.java:31)
	at name.jacktang.JsqlparserTest.access$000(JsqlparserTest.java:17)
	at name.jacktang.JsqlparserTest$1.load(JsqlparserTest.java:24)
	at name.jacktang.JsqlparserTest$1.load(JsqlparserTest.java:21)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3522)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2315)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2193)
	... 4 more
```

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.7
问题修复，请用新版本
