### ISSUE TITLE
sql parse不支持 mysql set数据类型

### ISSUE THREAD

**Issue by xiaoma20082008** [alibaba/druid#2260]
druid version 1.1.6:

```java
public class DruidTest {

    public static void main(String[] args) {
        String sql = "create table t(id int, name set('a','b','c') not null default 'a' );";
        List<SQLStatement> sqlStatements = SQLUtils.parseStatements(sql, JdbcConstants.MYSQL);
        for (SQLStatement statement : sqlStatements) {
            System.out.println(statement);
        }
    }
}
```

报错:

```java
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: error pos 31, line 1, column 28, token SET
	at com.alibaba.druid.sql.parser.SQLExprParser.name(SQLExprParser.java:1334)
	at com.alibaba.druid.sql.parser.SQLExprParser.parseDataType(SQLExprParser.java:2310)
	at com.alibaba.druid.sql.parser.SQLExprParser.parseDataType(SQLExprParser.java:2301)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.parseColumn(MySqlExprParser.java:493)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlCreateTableParser.parseCreateTable(MySqlCreateTableParser.java:115)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseCreate(MySqlStatementParser.java:244)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:159)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:70)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:464)
	at DruidTest.main(DruidTest.java:11)

```

**Comment by wenshao** [comment]
不要发图发文本好么？

**Comment by xiaoma20082008** [comment]
sorry，已修改 @wenshao

**Comment by wenshao** [comment]
问题已经修复，等下一个版本吧，预计在周末

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.7
问题修复，请用新版本
