### ISSUE TITLE
SQLUtils解析mysql partition相关操作报错

### ISSUE THREAD

**Issue by JackEggie** [alibaba/druid#2263]
sql:
```
ALTER TABLE src.`part_tab` DISCARD PARTITION p10 TABLESPACE
```
error:
```
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :' p10 TABLESPACE',expect TABLESPACE, actual TABLESPACE pos 59, line 1, column 49, token TABLESPACE
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:280)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:385)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:78)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:419)
	at name.jacktang.JsqlparserTest.parse(JsqlparserTest.java:31)
	at name.jacktang.JsqlparserTest.access$000(JsqlparserTest.java:17)
	at name.jacktang.JsqlparserTest$1.load(JsqlparserTest.java:24)
	at name.jacktang.JsqlparserTest$1.load(JsqlparserTest.java:21)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3522)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2315)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2193)
	... 4 more
```

sql:
```
ALTER TABLE src.`part_tab` EXCHANGE PARTITION p9 WITH TABLE test_create_table without validation
```
error:
```
com.alibaba.druid.sql.parser.ParserException: TODO pos 35, line 1, column 27, token IDENTIFIER EXCHANGE
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseAlterTable(MySqlStatementParser.java:2779)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseAlter(MySqlStatementParser.java:2429)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:185)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:78)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:419)
	at name.jacktang.JsqlparserTest.parse(JsqlparserTest.java:31)
	at name.jacktang.JsqlparserTest.access$000(JsqlparserTest.java:17)
	at name.jacktang.JsqlparserTest$1.load(JsqlparserTest.java:24)
	at name.jacktang.JsqlparserTest$1.load(JsqlparserTest.java:21)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3522)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2315)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2193)
	... 4 more
```

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.7
问题修复，请用新版本
