### ISSUE TITLE
oracle设置poolPreparedStatements=true报错..

### ISSUE THREAD

**Issue by Ryoui** [alibaba/druid#2266]
`### The error occurred while handling results
### Cause: java.lang.NullPointerException] with root cause
java.lang.NullPointerException
	at oracle.jdbc.driver.PhysicalConnection.cacheBuffer(PhysicalConnection.java:6811)
	at oracle.jdbc.driver.OraclePreparedStatement.releaseBuffers(OraclePreparedStatement.java:3012)
	at oracle.jdbc.driver.T4CPreparedStatement.releaseBuffers(T4CPreparedStatement.java:241)
	at oracle.jdbc.driver.OraclePreparedStatement.enterImplicitCache(OraclePreparedStatement.java:3094)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.enterImplicitCache(OraclePreparedStatementWrapper.java:1588)
	at com.alibaba.druid.util.OracleUtils.enterImplicitCache(OracleUtils.java:66)
	at com.alibaba.druid.pool.PreparedStatementPool.put(PreparedStatementPool.java:91)
	at com.alibaba.druid.pool.DruidPooledConnection.closePoolableStatement(DruidPooledConnection.java:171)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.close(DruidPooledPreparedStatement.java:202)
	at org.apache.ibatis.executor.BaseExecutor.closeStatement(BaseExecutor.java:285)`

+++++++++++
设置poolPreparedStatements=false就ok，druid-1.1.5.jar

**Comment by lizongbo** [comment]
请使用最新版验证
