### ISSUE TITLE
SQLUtils解析mysql创建表语句报错

### ISSUE THREAD

**Issue by JackEggie** [alibaba/druid#2267]
sql:
```
CREATE TABLE IF NOT EXISTS testTable
(
  `id` BIGINT(20) NOT NULL,
  `queue_id` BIGINT(20) NOT NULL DEFAULT '-1',
  `status` TINYINT(4) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT 10 AVG_ROW_LENGTH 10 DEFAULT CHARACTER SET=utf8 DEFAULT COLLATE = utf8_general_ci
CHECKSUM=0 CONNECTION = 'connect_string'  DELAY_KEY_WRITE = 0 ENCRYPTION='N' INSERT_METHOD FIRST
MAX_ROWS 1000 MIN_ROWS=10 PACK_KEYS DEFAULT PASSWORD '12345678' STATS_AUTO_RECALC 0 STATS_PERSISTENT 0 
STATS_SAMPLE_PAGES 10
```
error:
```
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :' = 0 ENCRYPTION='N' INSERT_METHOD F',expect IDENTIFIER, actual IDENTIFIER pos 364, line 8, column 74, token IDENTIFIER ENCRYPTION
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:280)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:385)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:78)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:419)
	at name.jacktang.JsqlparserTest.parse(JsqlparserTest.java:31)
	at name.jacktang.JsqlparserTest.access$000(JsqlparserTest.java:17)
	at name.jacktang.JsqlparserTest$1.load(JsqlparserTest.java:24)
	at name.jacktang.JsqlparserTest$1.load(JsqlparserTest.java:21)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3522)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2315)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2193)
	... 4 more
```

sql:
```
CREATE TABLE IF NOT EXISTS srcTable
(
  `id` BIGINT(20) NOT NULL,
  `queue_id` BIGINT(20) NOT NULL DEFAULT '-1',
  `status` TINYINT(4) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT 10 AVG_ROW_LENGTH 10 DEFAULT CHARACTER SET=utf8 DEFAULT COLLATE = utf8_general_ci
CHECKSUM=0 COMPRESSION='NONE' CONNECTION = 'connect_string'  DELAY_KEY_WRITE = 0 ENCRYPTION 'N' INSERT_METHOD FIRST
MAX_ROWS 1000 MIN_ROWS=10 PACK_KEYS DEFAULT PASSWORD '12345678' STATS_AUTO_RECALC 0 STATS_PERSISTENT 0 
STATS_SAMPLE_PAGES 10
```
error:
```
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'UM=0 COMPRESSION='NONE' CONNECTION ',expect IDENTIFIER, actual IDENTIFIER pos 313, line 8, column 24, token IDENTIFIER COMPRESSION
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:280)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:385)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:78)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:419)
	at name.jacktang.JsqlparserTest.parse(JsqlparserTest.java:31)
	at name.jacktang.JsqlparserTest.access$000(JsqlparserTest.java:17)
	at name.jacktang.JsqlparserTest$1.load(JsqlparserTest.java:24)
	at name.jacktang.JsqlparserTest$1.load(JsqlparserTest.java:21)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3522)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2315)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2193)
	... 4 more
```

**Comment by JackEggie** [comment]
sql:
```
CREATE TABLE IF NOT EXISTS ttable
(
`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
`queue_id` varchar(20) NOT NULL DEFAULT '-1',
`status` TINYINT(4) NOT NULL DEFAULT '1',
`geometry` geometry not null,
CONSTRAINT PRIMARY KEY (`id`),
CONSTRAINT UNIQUE KEY `uk_queue_id` USING BTREE (`queue_id`) KEY_BLOCK_SIZE=10,
FULLTEXT KEY `ft_status` (`queue_id`),
spatial index `spatial` (`geometry`),
CONSTRAINT FOREIGN KEY `fk_test`(`queue_id`) REFERENCES `test`(`id`)
) ENGINE=INNODB
```
error:
```
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'id`) KEY_BLOCK_SIZE=10,
FULLTEXT KE',expect RPAREN, actual IDENTIFIER pos 301, line 8, column 62, token IDENTIFIER KEY_BLOCK_SIZE
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:280)
	at com.alibaba.druid.sql.parser.SQLParser.accept(SQLParser.java:288)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlCreateTableParser.parseCrateTable(MySqlCreateTableParser.java:185)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseCreate(MySqlStatementParser.java:305)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:155)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:78)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:419)
	at name.jacktang.JsqlparserTest.parse(JsqlparserTest.java:31)
	at name.jacktang.JsqlparserTest.access$000(JsqlparserTest.java:17)
	at name.jacktang.JsqlparserTest$1.load(JsqlparserTest.java:24)
	at name.jacktang.JsqlparserTest$1.load(JsqlparserTest.java:21)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3522)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2315)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2193)
	... 4 more
```

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.7
问题修复，请用新版本
