### ISSUE TITLE
数据库密码加密时，长时间未访问数据库，报errorCode 1045, state 28000

### ISSUE THREAD

**Issue by lihongchun** [alibaba/druid#2268]
异常信息如下（）：

 create connection SQLException, url: jdbc:mysql://**********/****, errorCode 1045, state 28000
java.sql.SQLException: Access denied for user '*******'@'*********' (using password: YES)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
        at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
        at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
        at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2194)
        at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2225)
        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2024)
        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:779)
        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
        at sun.reflect.GeneratedConstructorAccessor84.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:389)
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
        at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:149)
        at com.alibaba.druid.filter.FilterAdapter.connection_connect(FilterAdapter.java:786)
        at com.alibaba.druid.filter.FilterEventAdapter.connection_connect(FilterEventAdapter.java:38)
        at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:143)
        at com.alibaba.druid.filter.FilterAdapter.connection_connect(FilterAdapter.java:786)
        at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:143)
        at com.alibaba.druid.filter.FilterAdapter.connection_connect(FilterAdapter.java:786)
        at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:143)
        at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:218)
        at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:143)
        at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1470)
        at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1533)
        at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2333)

**Comment by 7040210** [comment]
我也遇到这样的问题，环境是SpringBoot，在项目启动的时候是没问题的，打断点能看到运行到MySQL的连接是密码是解密过的，但是当连接断开后，目前Druid设置的是7小时，重新获取连接的时候并没有执行数据解密操作，不知道是我设置的问题还是怎么回事，数据库拿到的就是密文，所有就无法连接数据库了。

**Comment by wenshao** [comment]
比较奇怪哦

**Comment by lihongchun** [comment]
spring boot 项目，启动时（org.springframework.beans.factory.InitializingBean#afterPropertiesSet中）查询数据库数据，会存在该问题，启动时不加载数据库数据时无该问题

**Comment by singAllSong** [comment]
我擦，终于找到了一个志同道合的，你这问题跟我那问题一样
#2302

**Comment by ChenBravery** [comment]
我也有类似问题：
https://github.com/alibaba/druid/issues/2312

**Comment by hackeryutu** [comment]
我也有类似问题。

**Comment by nibaohua** [comment]
那现在又解决方案吗？ 之前我也没有遇到，最近有一台机器也一直会出现这个问题

**Comment by chenkline** [comment]
最好的方式是不要使用druid的加密配置功能，使用spring-cloud-config本身的加密配置功能，从而绕过这个bug

**Comment by Anyzm** [comment]
我也碰到了，怎么解决？为啥没有大佬出来解答啊？

**Comment by Anyzm** [comment]
> 我也碰到了，怎么解决？为啥没有大佬出来解答啊？

我是springboot+apollo

**Comment by pigbayspy** [comment]
同问这个问题，这个问题在 1.2.8 中存在

**Comment by Anyzm** [comment]
感谢您的来件，邮件已收到。
