### ISSUE TITLE
wallfilter 启用时，执行alter sequence 会报错，即使打开了设置noneBaseStatementAllow也不行

### ISSUE THREAD

**Issue by a1576471428** [alibaba/druid#2275]
主要报错如下：
Caused by: java.sql.SQLException: sql injection violation, syntax error: TODO : pos 14, line 1, column 6, token SEQUENCE : ALTER SEQUENCE SEQ_XXX INCREMENT BY 2
	at com.alibaba.druid.wall.WallFilter.checkInternal(WallFilter.java:798)
	at com.alibaba.druid.wall.WallFilter.connection_prepareStatement(WallFilter.java:251)
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:473)
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.prepareStatement(ConnectionProxyImpl.java:342)
	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:350)
	at com.jfinal.plugin.activerecord.DbPro.update(DbPro.java:283)
	at com.jfinal.plugin.activerecord.DbPro.update(DbPro.java:302)
	... 47 more
Caused by: com.alibaba.druid.sql.parser.ParserException: TODO : pos 14, line 1, column 6, token SEQUENCE
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleStatementParser.parserAlter(OracleStatementParser.java:1414)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleStatementParser.parseStatementList(OracleStatementParser.java:140)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:81)
	at com.alibaba.druid.wall.WallProvider.checkInternal(WallProvider.java:622)
	at com.alibaba.druid.wall.WallProvider.check(WallProvider.java:576)
	at com.alibaba.druid.wall.WallFilter.checkInternal(WallFilter.java:785)
	... 53 more

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/commit/ca601e9a89a97aa777c6a36f32dbe6712fc80362

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.7
问题修复，请用新版本
