### ISSUE TITLE
SQLUtils无法解析 postgresql的 jsonb操作: select '[1,2,3]'::jsonb ?| array['1']

### ISSUE THREAD

**Issue by beiyu** [alibaba/druid#2285]
## 环境
jdk 8
PostgreSQL 10.1
postgresql(驱动) 9.4.1212.jre7

## SQL
`select '[1,2,3]'::jsonb ?| array['1']`

## 在psql中可以正常运行，结果
```
test=# select '[1,2,3]'::jsonb ?| array['1'];
 ?column?
----------
 f
(1 row)
```
## 测试代码
```
        String sql = "select '[1,2,3]'::jsonb ?| array['1']";
        String dbType = JdbcConstants.POSTGRESQL;
        String result = SQLUtils.format(sql, dbType);
```

## 异常内容
16:26:50.813 [main] WARN com.alibaba.druid.sql.SQLUtils - format error
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'3]'::jsonb ?| array['1']',expect QUES, actual QUES jsonb
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:230)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:324)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:120)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:115)
	at com.alibaba.druid.sql.SQLUtils.toStatementList(SQLUtils.java:216)
	at com.alibaba.druid.sql.SQLUtils.format(SQLUtils.java:229)
	at com.alibaba.druid.sql.SQLUtils.format(SQLUtils.java:224)
	at org.beiyu.study.parser_test.DruidParserTest.main(DruidParserTest.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
select '[1,2,3]'::jsonb ?| array['1']

请确认下是否为bug，谢谢！

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.7
问题修复，请用新版本
