### ISSUE TITLE
SELECT CURRENT TIME FROM SYSIBM.SYSDUMMY1解析后多出as

### ISSUE THREAD

**Issue by xuanang** [alibaba/druid#2288]
执行的sql：SELECT CURRENT TIME FROM SYSIBM.SYSDUMMY1，在db2数据库下通过druid解析后会多出AS
SELECT CURRENT  AS TIME FROM SYSIBM.SYSDUMMY1然后传入到数据库底层报错。错误信息如下:
Exception in thread "main" com.ibm.db2.jcc.am.vo: DB2 SQL Error: SQLCODE=-206, SQLSTATE=42703, SQLERRMC=CURRENT, DRIVER=4.8.87
	at com.ibm.db2.jcc.am.gd.a(gd.java:676)
	at com.ibm.db2.jcc.am.gd.a(gd.java:60)
	at com.ibm.db2.jcc.am.gd.a(gd.java:127)
	at com.ibm.db2.jcc.am.wm.c(wm.java:2510)

**Comment by wenshao** [comment]
什么版本？

**Comment by xuanang** [comment]
1.1.4版本

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.9
问题已修复，请用新版本
