### ISSUE TITLE
druid分布式事物mysql8小时 超时无法使用

### ISSUE THREAD

**Issue by abc127890** [alibaba/druid#2299]
配置：

	<bean id="abstractXADataSource" class="com.atomikos.jdbc.AtomikosDataSourceBean"
		init-method="init" destroy-method="close" abstract="true">
		<property name="xaDataSourceClassName" value="com.alibaba.druid.pool.xa.DruidXADataSource" />
		<property name="reapTimeout" value="60" />
		<property name="maxIdleTime" value="120" />
		<property name="loginTimeout" value="10" />
		<property name="maintenanceInterval" value="60" />
		<property name="borrowConnectionTimeout" value="30" />
		<property name="maxLifetime" value="300" />
	</bean>

	
	<bean id="sysDataSource"   parent="abstractXADataSource">
		<property name="uniqueResourceName" value="ds-1" />
		<property name="xaProperties">
			<props>
				<prop key="url">${sys.jdbc.url}</prop>
				<prop key="username">${sys.jdbc.username}</prop>
				<prop key="password">${sys.jdbc.password}</prop>
				<prop key="maxWait">60000</prop>
				<prop key="timeBetweenEvictionRunsMillis">50000</prop>
				<prop key="minEvictableIdleTimeMillis">300000</prop>
				<prop key="maxEvictableIdleTimeMillis">600000</prop>
				<prop key="validationQuery">SELECT 'x'</prop>
				<prop key="testWhileIdle">true</prop>
				<prop key="testOnBorrow">false</prop>
				<prop key="testOnReturn">false</prop>
				<prop key="filters">wall,stat</prop>
				
				<prop key="poolPreparedStatements">false</prop>
				<prop key="initialSize">${sys.jdbc.init.pool.size}</prop>
				<prop key="minIdle">${sys.jdbc.idle.pool.size}</prop>
				<prop key="maxActive">${sys.jdbc.max.pool.size}</prop>
			</props>
		</property>
		<property name="poolSize" value="${sys.jdbc.init.pool.size}" />
		<property name="minPoolSize" value="${sys.jdbc.idle.pool.size}" />
		<property name="maxPoolSize" value="${sys.jdbc.max.pool.size}" />
	</bean

一个晚上后就会报错
com.mysql.cj.jdbc.exceptions.CommunicationsException: The last packet successfully received from the server was 54,534,404 milliseconds ago.  The last packet sent successfully to the server was 54,534,408 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.

修改<property name="xaDataSourceClassName" value="com.alibaba.druid.pool.xa.DruidXADataSource" />为
<property name="xaDataSourceClassName" value="com.mysql.cj.jdbc.MysqlXADataSource" />
可以
这个应该是bug

**Comment by wenshao** [comment]
druid什么版本？估计是你用了mysql 6.0 driver导致的

**Comment by abc127890** [comment]
温少
<druid-version>1.1.6</druid-version>
<mysql.version>6.0.6</mysql.version>

mysql 6.0 driver 有这个问题吗 ？

**Comment by abc127890** [comment]
换成mysql 5.x也是一样得,这个真得是druid得bug

**Comment by abc127890** [comment]
@wenshao

**Comment by yuxing1994** [comment]
我也遇到这个问题了不知道是 atomikos的问题还是druid，mysql这个参数wait_timeout一晚上导致连接出错

**Comment by CQ-Harry** [comment]
朋友，我也遇到同样的问题，请问最终解决了嘛？

**Comment by CQ-Harry** [comment]
@abc127890 
我改了`XaDataSourceClassName`之后报错，朋友，请问对应各种jar的版本是？
```
com.atomikos.beans.PropertyException: no writeable property 'minEvictableIdleTimeMillis' in class 'com.mysql.cj.jdbc.MysqlXADataSource'
	at com.atomikos.beans.PropertyUtils.getSetter(PropertyUtils.java:290)
	at com.atomikos.beans.PropertyUtils.setDirectProperty(PropertyUtils.java:200)
	at com.atomikos.beans.PropertyUtils.setProperty(PropertyUtils.java:110)
	at com.atomikos.beans.PropertyUtils.setProperties(PropertyUtils.java:186)
	at com.atomikos.jdbc.AtomikosDataSourceBean.doInit(AtomikosDataSourceBean.java:196)
	at com.atomikos.jdbc.AbstractDataSourceBean.init(AbstractDataSourceBean.java:296)
	at com.atomikos.jdbc.AbstractDataSourceBean.getConnection(AbstractDataSourceBean.java:339)
	at com.atomikos.jdbc.AbstractDataSourceBean.getConnection(AbstractDataSourceBean.java:394)
	at com.baomidou.mybatisplus.toolkit.GlobalConfigUtils.setMetaData(GlobalConfigUtils.java:187)
	at com.baomidou.mybatisplus.spring.MybatisSqlSessionFactoryBean.buildSqlSessionFactory(MybatisSqlSessionFactoryBean.java:560)
	at com.baomidou.mybatisplus.spring.MybatisSqlSessionFactoryBean.afterPropertiesSet(MybatisSqlSessionFactoryBean.java:385)
	at com.baomidou.mybatisplus.spring.MybatisSqlSessionFactoryBean.getObject(MybatisSqlSessionFactoryBean.java:608)
	at com.cn.iot.webos.common.datasources.MultiSqlSessionFactoryConfig.createSqlSessionFactory(MultiSqlSessionFactoryConfig.java:136)
	at com.cn.iot.webos.common.datasources.MultiSqlSessionFactoryConfig.sqlSessionFactoryPrimary(MultiSqlSessionFactoryConfig.java:69)
	at com.cn.iot.webos.common.datasources.MultiSqlSessionFactoryConfig$$EnhancerBySpringCGLIB$$3a4a42d9.CGLIB$sqlSessionFactoryPrimary$3(<generated>)
	at com.cn.iot.webos.common.datasources.MultiSqlSessionFactoryConfig$$EnhancerBySpringCGLIB$$3a4a42d9$$FastClassBySpringCGLIB$$3b6f10c5.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358)
	at com.cn.iot.webos.common.datasources.MultiSqlSessionFactoryConfig$$EnhancerBySpringCGLIB$$3a4a42d9.sqlSessionFactoryPrimary(<generated>)
	at sun.reflect.GeneratedMethodAccessor114.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:45005)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1181)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1075)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireByType(AbstractAutowireCapableBeanFactory.java:1350)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1257)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:585)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1272)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:585)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1272)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:585)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1272)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.__refresh(AbstractApplicationContext.java:543)
	at org.springframework.context.support.AbstractApplicationContext.jrLockAndRefresh(AbstractApplicationContext.java:40002)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:41008)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	at com.cn.iot.webos.OsApplication.main(OsApplication.java:16)
```

**Comment by yuxing1994** [comment]
@CQ-Harry  换mysql  jdbc的jar包 或者换 druid版本 直到有一个适配的，然后更改mysql超时时间可以改长，或者改让druid心跳时长小于mysql超时时间

**Comment by CQ-Harry** [comment]
@yuxing1994 在另一个朋友的帮助下解决了

**Comment by CQ-Harry** [comment]
> @yuxing1994 在另一个朋友的帮助下解决了

`atomikosDataSourceBean.setMinPoolSize(0);`，不过还是谢谢了

**Comment by gaomingpeng** [comment]
> @yuxing1994 在另一个朋友的帮助下解决了

怎么解决的

**Comment by yuxing1994** [comment]
> > @yuxing1994 在另一个朋友的帮助下解决了
> 
> 怎么解决的

楼上哥们说设置atomikosDataSourceBean.setMinPoolSize(0);

**Comment by CQ-Harry** [comment]
> > @yuxing1994 在另一个朋友的帮助下解决了
> 
> 怎么解决的

那个朋友：atomikosDataSourceBean.setMinPoolSize(0);

**Comment by ioandy** [comment]
我也遇到了同样问题，搞了好几天，心累。。。
请教下楼上说更新mysql-connector-java，哪个版本会正常啊？ 还有设置setMinPoolSize(0), 没有起作用..

**Comment by shuiZzz** [comment]
> 我也遇到了同样问题，搞了好几天，心累。。。
> 请教下楼上说更新mysql-connector-java，哪个版本会正常啊？ 还有设置setMinPoolSize(0), 没有起作用..

你搞出来了么？spring-boot-starter-jta-atomikos升级了么？我也是各种方法都试了…心好累

**Comment by y2601** [comment]
我这是这个问题，过了一个晚上就报错。

**Comment by wenshao** [comment]
使用1.2.1版本，并配置keepAlive=true试试看

**Comment by liyapu** [comment]
https://www.cnblogs.com/qingyibusi/p/8243826.html
我参照这篇文章，设置 在配置 AtomikosDataSourceBean 时 配上 连接检查解决了
