### ISSUE TITLE
PGSQL:Connected to db_2 解析出错

### ISSUE THREAD

**Issue by xuanang** [alibaba/druid#2309]
master版本下，pgsql执行“Connected to db_2”语句解析出错，测试代码如下:
public void  testConnectionToDB(){
		PGSQLStatementParser parser = new PGSQLStatementParser(
				"Connected to db_2");
		List<SQLStatement> statementList = parser.parseStatementList();
		System.out.println(statementList.get(0).toString());
	}
错误信息：
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'Connected to db_2', expect IDENTIFIER, actual IDENTIFIER pos 9, line 1, column 1, token IDENTIFIER Connected
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:283)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:421)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:70)
	at com.alibaba.druid.SqlParserTest.testConnectionToDB(SqlParserTest.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by wenshao** [comment]
这个不是PG的SQL语句吧
