### ISSUE TITLE
H2 分页错误

### ISSUE THREAD

**Issue by JaynLau** [alibaba/druid#2313]
H2 分页的时候报错，SQL 语句的解析应该有点问题，在解析 H2 SQL 的时候并没有把 SQLSelectQueryBlock 解析为 MySqlSelectQueryBlock。
测试了 1.1.4 - 1.1.6，都有这个问题。

`
PagerUtils.limit("SELECT * FROM test", JdbcUtils.H2, 0, 10);
`

报类型转换错误

```
java.lang.ClassCastException: com.alibaba.druid.sql.ast.statement.SQLSelectQueryBlock cannot be cast to com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlSelectQueryBlock
	at com.alibaba.druid.sql.PagerUtils.limitQueryBlock(PagerUtils.java:108)
	at com.alibaba.druid.sql.PagerUtils.limit(PagerUtils.java:97)
	at com.alibaba.druid.sql.PagerUtils.limit(PagerUtils.java:76)
	at com.alibaba.druid.sql.PagerUtils.limit(PagerUtils.java:72)
```

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.7
问题修复，请用新版本
