### ISSUE TITLE
postgresql:解析alter table t_user rename flag1 to flag出错

### ISSUE THREAD

**Issue by zlspirit** [alibaba/druid#2365]
测试用例：
public class PgAltersqlTest {
	public static void main(String[] args) {
		String sql = "alter table t_user rename flag1 to flag";
		SQLStatementParser parser = new PGSQLStatementParser(sql);
		System.out.println(parser.parseStatementList().get(0).toString()); 
	}
}
报错信息：
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: TODO pos 31, line 1, column 26, token IDENTIFIER flag1
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseAlterTableRename(SQLStatementParser.java:1353)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseAlter(SQLStatementParser.java:1218)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:191)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:72)
	at com.alibaba.druid.not_support.sql.postgresql.PgAltersqlTest.main(PgAltersqlTest.java:19)

**Comment by ljluestc** [comment]
import com.alibaba.druid.sql.parser.PGStatementParser;
import com.alibaba.druid.sql.parser.SQLStatement;
import com.alibaba.druid.sql.parser.SQLStatementParser;

public class PgAltersqlTest {
    public static void main(String[] args) {
        String sql = "alter table t_user rename flag1 to flag";
        SQLStatementParser parser = new PGStatementParser(sql);
        SQLStatement statement = parser.parseStatement();

        System.out.println(statement.toString());
    }
}
