### ISSUE TITLE
postgresql:解析alter table t_org alter org_name drop NOT NULL出错

### ISSUE THREAD

**Issue by zlspirit** [alibaba/druid#2367]
用例：
public static void main(String[] args) {
		String sql = "alter table t_org alter org_name drop NOT NULL";
		SQLStatementParser parser = new PGSQLStatementParser(sql);
		System.out.println(parser.parseStatementList().get(0).toString()); 
	}
错误信息：
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: TODO pos 32, line 1, column 24, token IDENTIFIER org_name
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseAlter(SQLStatementParser.java:1157)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:191)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:72)
	at com.alibaba.druid.not_support.sql.postgresql.PgAltersqlTest.main(PgAltersqlTest.java:19)

**Comment by ljluestc** [comment]
```

public class Main {
    public static void main(String[] args) {
        // Modified SQL statement that is more likely to be supported
        String sql = "ALTER TABLE t_org ALTER COLUMN org_name DROP NOT NULL";
        SQLStatementParser parser = new PGSQLStatementParser(sql);
        try {
            System.out.println(parser.parseStatementList().get(0).toString());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```
