### ISSUE TITLE
Mysql union all 进行分页（PageHelper） 出现java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by heroLi** [alibaba/druid#2411]
Caused by: java.lang.UnsupportedOperationException
	at com.alibaba.druid.sql.PagerUtils.limit(PagerUtils.java:100)
	at com.alibaba.druid.wall.spi.MySqlWallVisitor.visit(MySqlWallVisitor.java:190)
	at com.alibaba.druid.sql.ast.statement.SQLSelectStatement.accept0(SQLSelectStatement.java:63)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:42)
	at com.alibaba.druid.wall.WallProvider.checkInternal(WallProvider.java:659)
	at com.alibaba.druid.wall.WallProvider.check(WallProvider.java:574)
	at com.alibaba.druid.wall.WallFilter.check(WallFilter.java:712)
	at com.alibaba.druid.wall.WallFilter.connection_prepareStatement(WallFilter.java:253)
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:473)
	at com.alibaba.druid.filter.FilterAdapter.connection_prepareStatement(FilterAdapter.java:929)
	at com.alibaba.druid.filter.FilterEventAdapter.connection_prepareStatement(FilterEventAdapter.java:122)
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:473)
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.prepareStatement(ConnectionProxyImpl.java:342)
	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:350)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.bull.javamelody.JdbcWrapper$ConnectionInvocationHandler.invoke(JdbcWrapper.java:197)
	at net.bull.javamelody.JdbcWrapper$DelegatingInvocationHandler.invoke(JdbcWrapper.java:294)
	at com.sun.proxy.$Proxy124.prepareStatement(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.instantiateStatement(PreparedStatementHandler.java:87)
	at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:88)
	... 124 more

**Comment by heroLi** [comment]
public static boolean limit(SQLSelect select, String dbType, int offset, int count, boolean check) {
        SQLSelectQuery query = select.getQuery();

        if (JdbcConstants.ORACLE.equals(dbType)) {
            return limitOracle(select, dbType, offset, count, check);
        }

        if (JdbcConstants.DB2.equals(dbType)) {
            return limitDB2(select, dbType, offset, count, check);
        }

        if (JdbcConstants.SQL_SERVER.equals(dbType) || JdbcUtils.JTDS.equals(dbType)) {
            return limitSQLServer(select, dbType, offset, count, check);
        }

        if (query instanceof SQLSelectQueryBlock) {
            return limitQueryBlock(select, dbType, offset, count, check);
        }

        throw new UnsupportedOperationException();
    }

这里会报错  query 为 SQLUnionQuery

**Comment by heroLi** [comment]
wall 开启 limit

**Comment by wenshao** [comment]
能提供报错的sql么？

**Comment by heroLi** [comment]
select
  a.main_card_no as card_no, a.city, a.bussiness_type, 'main' as card_type,
  c.company_name as company, a.status_flag,
  a.card_balance as balance from oil_card_main a left join oil_company c on c.company_id=a.company_id
  
  union all
 
  select
  b.card_no,b.city,b.bussiness_type,'secon' as card_type,c.company_name as company,
  b.status_flag,b.card_balance as balance
  from oil_card_associate b left join oil_card_main a
  on a.main_card_no = b.main_card_no
  left join oil_company c on c.company_id=a.company_id
@wenshao

**Comment by heroLi** [comment]
mysql

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.10
问题修复，请用新版本
