### ISSUE TITLE
druid不支持解析阿里的drds分库分表语法！！！

### ISSUE THREAD

**Issue by fjfyitian** [alibaba/druid#2433]
## 如下，为一个drds数据库分库分表的建表语句：

_create table ARCHIVE_ERR_RECORD
(
   SUBS_ORDER_ID        numeric(18,0) not null comment '订单编号',
   ERR_MSG              text comment '失败的消息结构',
   ERR_REASON           varchar(255) comment '失败原因',
   PART_ID              integer not null comment '分区标识（取订单编号中的月份）'
)
DBPARTITION BY HASH(SUBS_ORDER_ID)
TBPARTITION BY UNI_HASH(PART_ID) TBPARTITIONS 12;_

## 调用druid的sql解析方法：
List<SQLStatement> stmtList = SQLUtils.parseStatements(sql, JdbcConstants.ALIYUN_DRDS);

## 执行抛出异常：

Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'）'
)
DBPARTITION BY HASH(SUBS_ORDER', expect IDENTIFIER, actual IDENTIFIER pos 278, line 7, column 3, token IDENTIFIER DBPARTITION
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:284)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:423)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:72)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:464)
	at org.dts.test.TestSql.splitSql(TestSql.java:27)
	at org.dts.test.TestSql.main(TestSql.java:40)

**Comment by wenshao** [comment]
druid什么版本？

**Comment by fjfyitian** [comment]
非常感谢！！！

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.10
问题修复，请用新版本
