### ISSUE TITLE
这个SQL可以在sql客户端执行 , 不知道拦截是因为效率还是因为解析SQL出错. 

### ISSUE THREAD

**Issue by easywudi** [alibaba/druid#2474]
最新的jar包: druid:1.1.9
<pre>
SELECT id,
  MAX(myRank) area
FROM
  (SELECT t2.id ,
    wmsys.wm_concat(t2.name) over (partition BY t2.id order by to_number(t2.cc) ASC ) myRank
  FROM
    (SELECT adr.name,
      t1.*
    FROM
      (SELECT t.id,
        t.addresscode,
        regexp_substr(t.addresscode, '[^_]+', 1, x.n) cc
      FROM
        ( SELECT id,addresscode FROM srm1.CONSIGNEE_ADDRESS ca
        ) t,
        (SELECT ROWNUM n FROM dual CONNECT BY ROWNUM <= 5
        ) x
      ORDER BY 1
      ) t1
    LEFT JOIN srm1.address adr
    ON adr.id    = t1.cc
    WHERE t1.cc IS NOT NULL
    ) t2
  )
GROUP BY id
</pre>

一个列转行  然后 关联翻译 最后wm_concat再行转列
加入 over  partition by 是为了正确的排序

例如:
16_1303_1312_48816

福建,福州市,罗源县,罗源湾

这个SQL可以在sql客户端执行 , 不知道拦截是因为效率还是因为解析SQL出错.   

PS:这段只是一部分. 由主表根据ID来JOIN.

Caused by: com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'ame) over (partition by t2.id order',expect RPAREN, actual OVER over
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:230)
	at com.alibaba.druid.sql.parser.SQLParser.accept(SQLParser.java:239)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.parseTableSource(OracleSelectParser.java:717)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseFrom(SQLSelectParser.java:316)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.query(OracleSelectParser.java:272)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.select(OracleSelectParser.java:88)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.parseTableSource(OracleSelectParser.java:711)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.parseTableSourceRest(OracleSelectParser.java:954)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.parseTableSourceRest(OracleSelectParser.java:966)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.parseTableSourceRest(OracleSelectParser.java:966)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.parseTableSourceRest(OracleSelectParser.java:966)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.parseTableSourceRest(OracleSelectParser.java:966)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.parseTableSource(OracleSelectParser.java:741)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseFrom(SQLSelectParser.java:316)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.query(OracleSelectParser.java:272)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.select(OracleSelectParser.java:88)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.parseTableSource(OracleSelectParser.java:711)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseFrom(SQLSelectParser.java:316)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.query(OracleSelectParser.java:272)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.select(OracleSelectParser.java:88)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.parseTableSource(OracleSelectParser.java:711)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseFrom(SQLSelectParser.java:316)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.query(OracleSelectParser.java:272)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.select(OracleSelectParser.java:88)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleStatementParser.parseStatementList(OracleStatementParser.java:164)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:121)
	at com.alibaba.druid.wall.WallProvider.checkInternal(WallProvider.java:620)
	at com.alibaba.druid.wall.WallProvider.check(WallProvider.java:574)
	at com.alibaba.druid.wall.WallFilter.check(WallFilter.java:699)
	... 85 more

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.10
问题修复，请用新版本
