### ISSUE TITLE
语法解析，DB2 不支持 SELECT INTO

### ISSUE THREAD

**Issue by IRoye** [alibaba/druid#2487]
版本1.1.9
如下语句解析出错
`SQLUtils.parseStatements("SELECT * INTO Persons_backup FROM Persons", JdbcConstants.DB2);`
异常
`Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'CT * INTO Persons_backup FROM Perso', expect INTO, actual INTO pos 13, line 1, column 9, token INTO
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:284)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:423)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:72)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:464)`

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.10
问题修复，请用新版本
