### ISSUE TITLE
Cause: java.sql.SQLException: ORA-02399: exceeded maximum connect time, you are being logged off

### ISSUE THREAD

**Issue by LesterDong** [alibaba/druid#2492]
程序中报数据库的异常，错误栈如下：
java.sql.SQLException: ORA-01012: not logged on

	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:331)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:288)
	at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:745)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:216)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:810)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1039)
	at oracle.jdbc.driver.T4CPreparedStatement.executeMaybeDescribe(T4CPreparedStatement.java:850)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1134)
--
	at com.chinagpay.notifyer.listener.NotifyMerListener$1.run(NotifyMerListener.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

经排查，发现有另外一个异常： SQL []; ORA-02399: exceeded maximum connect time, you are being logged off
; nested exception is java.sql.SQLException: ORA-02399: exceeded maximum connect time, you are being logged off ，我在想是不是连接池中某些连接在调用时发现oracle服务端已经将该连接物理关闭了，但是在druid连接池中还是alived，druid参数配置如下：
`<property name="driverClassName" value="${kydb.db.driver}" />
		<property name="url" value="${kydb.db.writer.url}" />
		<property name="username" value="${kydb.db.writer.username}" />
		<property name="password" value="${kydb.db.writer.password}" />
		<property name="connectionProperties"
			value="config.decrypt=true;config.decrypt.key=${db.publicKey}" />
		<property name="initialSize" value="${kydb.db.initialSize}" />
		<property name="maxActive" value="${kydb.db.maxActive}" />
		<property name="minIdle" value="${kydb.db.minIdle}" />
		<property name="maxWait" value="${kydb.db.maxWait}" />
		<property name="defaultReadOnly" value="false" />
		<property name="proxyFilters">
			<list>
				<ref bean="stat-filter" />
			</list>
		</property>
		<property name="filters" value="${druid.filters}" />
		<property name="testWhileIdle" value="true" />
		<property name="testOnBorrow" value="false" />
		<property name="testOnReturn" value="false" />
		<property name="validationQuery" value="select 1 from dual" />
		<property name="minEvictableIdleTimeMillis" value="3000000" />
		<property name="timeBetweenEvictionRunsMillis" value="3000" />
		<property name="timeBetweenLogStatsMillis" value="1000" />
		<property name="statLogger" ref="myStatLogger" />`

**Comment by wenshao** [comment]
这儿是服务器的问题，不对druid的问题

**Comment by LesterDong** [comment]
怎么解决呢大神？

**Comment by LesterDong** [comment]
@wenshao 大神 这个大概什么问题 怎么解决呢 可否指点一下
