### ISSUE TITLE
解析Oracle SQL报错

### ISSUE THREAD

**Issue by longxm** [alibaba/druid#2497]
Druid Version: 1.1.9

SQL：
SELECT
	J01.COL_A,
	J01.COL_B,
	"SUM"(J01.COL_C) OVER (
		PARTITION BY J01.COL_A ORDER BY J01.COL_B NULLS FIRST ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
	) AS COL_C
FROM
	TAB_A J01

java：
package com.xiaolong.druid;

import com.alibaba.druid.sql.ast.SQLStatement;
import com.alibaba.druid.sql.dialect.oracle.parser.OracleStatementParser;
import com.alibaba.druid.sql.dialect.oracle.visitor.OracleSchemaStatVisitor;
import com.alibaba.druid.sql.parser.SQLStatementParser;

// 测试druid
public class Test_Druid_Sql {

	public static void main(String[] args) {
		String sql = "		SELECT\r\n" + 
				"			J01.COL_A,\r\n" + 
				"			J01.COL_B,\r\n" + 
				"			\"SUM\"(J01.COL_C) OVER (\r\n" + 
				"				PARTITION BY J01.COL_A ORDER BY J01.COL_B NULLS FIRST ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\r\n" + 
				"			) AS COL_C\r\n" + 
				"		FROM\r\n" + 
				"			TAB_A J01\r\n" + 
				"";

		// 新建 ORACLE Parser
		SQLStatementParser parser = new OracleStatementParser(sql);

		// 使用Parser解析生成AST，这里SQLStatement就是AST
		SQLStatement statement = parser.parseStatement();

		// 使用visitor来访问AST
		OracleSchemaStatVisitor visitor = new OracleSchemaStatVisitor();
		statement.accept(visitor);

		System.out.println(visitor.getTables());
	}

}

报错：
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: ERROR. pos 138, line 5, column 64, token BETWEEN
	at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:793)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleExprParser.primary(OracleExprParser.java:462)
	at com.alibaba.druid.sql.parser.SQLExprParser.expr(SQLExprParser.java:86)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleExprParser.parseAggregateExpr(OracleExprParser.java:834)
	at com.alibaba.druid.sql.parser.SQLExprParser.methodRest(SQLExprParser.java:1051)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleExprParser.methodRest(OracleExprParser.java:500)
	at com.alibaba.druid.sql.parser.SQLExprParser.primaryRest(SQLExprParser.java:960)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleExprParser.primaryRest(OracleExprParser.java:668)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleExprParser.primary(OracleExprParser.java:314)
	at com.alibaba.druid.sql.parser.SQLExprParser.expr(SQLExprParser.java:86)
	at com.alibaba.druid.sql.parser.SQLExprParser.parseSelectItem(SQLExprParser.java:3061)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseSelectList(SQLSelectParser.java:508)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.query(OracleSelectParser.java:299)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.select(OracleSelectParser.java:75)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseSelect(SQLStatementParser.java:2412)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:2686)
	at com.xiaolong.druid.Test_Druid_Sql.main(Test_Druid_Sql.java:26)

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.10
问题修复，请用新版本
