### ISSUE TITLE
看了下源码，List集合这样remove，这难道不会发生数组越界么

### ISSUE THREAD

**Issue by bosen365** [alibaba/druid#2525]
![image](https://user-images.githubusercontent.com/6869773/39169801-c47c632c-47cb-11e8-96a0-840d70027435.png)

**Comment by bosen365** [comment]
在关connection的时候报这个错，汗
`java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.fastRemove(ArrayList.java:550)
	at java.util.ArrayList.remove(ArrayList.java:533)
	at com.alibaba.druid.pool.DruidConnectionHolder.removeTrace(DruidConnectionHolder.java:199)
	at com.alibaba.druid.pool.DruidPooledStatement.close(DruidPooledStatement.java:435)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.closeInternal(DruidPooledPreparedStatement.java:210)
	at com.alibaba.druid.pool.DruidPooledConnection.closePoolableStatement(DruidPooledConnection.java:189)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.close(DruidPooledPreparedStatement.java:202)
	at com.tydic.tysc.job.sink.JDBCAppendTableSinkDef.insertRowIntoJDBC(JDBCAppendTableSinkDef.java:166)`
