### ISSUE TITLE
使用wall过滤器后，出现sql injection violation错误

### ISSUE THREAD

**Issue by bluven** [alibaba/druid#2544]
版本信息
```
       <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid-spring-boot-starter</artifactId>
            <version>1.1.9</version>
        </dependency>
```

sql语句如下
```
select count(0) from (SELECT * FROM auth_tenant WHERE type = 'tenant' AND name LIKE ?"%") tmp_count 
```

错误如下
```
### Error querying database.  Cause: java.sql.SQLException: sql injection violation, syntax error: syntax error, error in :'name LIKE ?"%") tmp_count', expect RPAREN, actual LITERAL_ALIAS pos 162, line 8, column 29, token LITERAL_ALIAS "%" : select count(0) from (SELECT
            *
        FROM
            auth_tenant
        WHERE
            type = 'tenant'
         
            AND name LIKE ?"%") tmp_count
```

以及部分异常堆栈信息
```
Caused by: java.sql.SQLException: sql injection violation, syntax error: syntax error, error in :'name LIKE ?"%") tmp_count', expect RPAREN, actual LITERAL_ALIAS pos 162, line 8, column 29, token LITERAL_ALIAS "%" : select count(0) from (SELECT
            *
        FROM
            auth_tenant
        WHERE
            type = 'tenant'
         
            AND name LIKE ?"%") tmp_count
	at com.alibaba.druid.wall.WallFilter.checkInternal(WallFilter.java:798)
	at com.alibaba.druid.wall.WallFilter.connection_prepareStatement(WallFilter.java:251)
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:473)
	at com.alibaba.druid.filter.FilterAdapter.connection_prepareStatement(FilterAdapter.java:929)
	at com.alibaba.druid.filter.FilterEventAdapter.connection_prepareStatement(FilterEventAdapter.java:122)
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:473)
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.prepareStatement(ConnectionProxyImpl.java:342)
	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:349)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.ConnectionLogger.invoke(ConnectionLogger.java:55)
	at com.sun.proxy.$Proxy162.prepareStatement(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.instantiateStatement(PreparedStatementHandler.java:87)
	at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:88)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.prepare(RoutingStatementHandler.java:59)
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:85)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:326)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at com.github.pagehelper.PageInterceptor.executeAutoCount(PageInterceptor.java:201)
	at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:113)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy161.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 81 common frames omitted
Caused by: com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'name LIKE ?"%") tmp_count', expect RPAREN, actual LITERAL_ALIAS pos 162, line 8, column 29, token LITERAL_ALIAS "%"
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:284)
	at com.alibaba.druid.sql.parser.SQLParser.accept(SQLParser.java:292)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlSelectParser.parseTableSource(MySqlSelectParser.java:229)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlSelectParser.parseFrom(MySqlSelectParser.java:75)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlSelectParser.query(MySqlSelectParser.java:174)
	at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:59)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseSelect(MySqlStatementParser.java:113)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:149)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:83)
	at com.alibaba.druid.wall.WallProvider.checkInternal(WallProvider.java:624)
	at com.alibaba.druid.wall.WallProvider.check(WallProvider.java:578)
	at com.alibaba.druid.wall.WallFilter.checkInternal(WallFilter.java:785)
	... 113 common frames omitted

```

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.10
问题修复，请用新版本

**Comment by sanwancoder** [comment]
```
SELECT id,archive_name,archive_source,alarm_judge_time,alarm_place_type,alarm_place_detail,archive_time,archive_address,archive_org_id,archive_org_name,has_companion,clue_count,catch_count,policeman_id,policeman_name,policeman_org_id,policeman_org_name,ctime,utime,sid,deleted  FROM fc_archive  where id in (6f22587d-e6a0-41fa-9b48-d28f9256b46c,94e27cf4-c42e-43d7-95c5-1599b04b9fa6)
```
使用1.1.10 版本 这句话还是报错了

```
Caused by: java.sql.SQLException: sql injection violation, syntax error: syntax error, expect RPAREN, actual IDENTIFIER pos 353, line 1, column 351, token IDENTIFIER cf4 : SELECT id,archive_name,archive_source,alarm_judge_time,alarm_place_type,alarm_place_detail,archive_time,archive_address,archive_org_id,archive_org_name,has_companion,clue_count,catch_count,policeman_id,policeman_name,policeman_org_id,policeman_org_name,ctime,utime,sid,deleted  FROM fc_archive  where id in (6f22587d-e6a0-41fa-9b48-d28f9256b46c,94e27cf4-c42e-43d7-95c5-1599b04b9fa6)
	at com.alibaba.druid.wall.WallFilter.checkInternal(WallFilter.java:798)
	at com.alibaba.druid.wall.WallFilter.connection_prepareStatement(WallFilter.java:286)
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:610)
	at com.alibaba.druid.filter.FilterAdapter.connection_prepareStatement(FilterAdapter.java:942)
	at com.alibaba.druid.filter.FilterEventAdapter.connection_prepareStatement(FilterEventAdapter.java:143)
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:610)
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.prepareStatement(ConnectionProxyImpl.java:375)
```
