### ISSUE TITLE
1.0.26-merge sql error, dbType mysql, sql : expect LITERAL_FLOAT, actual LITERAL_FLOAT

### ISSUE THREAD

**Issue by sixawn** [alibaba/druid#2545]
update am_activity_prize set lock_left_count=lock_left_count-120.0, lock_count=lock_count+0.0 where id=?
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'t-120.0, lock_count=lock_count+0.0 ',expect LITERAL_FLOAT, actual LITERAL_FLOAT lock_left_count-12
        at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:239)
        at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:424)
        at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:147)
        at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:142)
        at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:53)
        at com.alibaba.druid.filter.stat.StatFilter.mergeSql(StatFilter.java:145)

**Comment by wenshao** [comment]
你用的druid什么版本？
