### ISSUE TITLE
H2数据库 Merge 语法解析异常

### ISSUE THREAD

**Issue by jeping** [alibaba/druid#2555]
@wenshao 

2018-05-07 20:42:16,051 [Quartz Scheduler [adminQuartzScheduler]] INFO  o.s.scheduling.quartz.SchedulerFactoryBean -[SchedulerFactoryBean.java:708]- Starting Quartz Scheduler now, after delay of 10 seconds
2018-05-07 20:42:16,097 [Quartz Scheduler [adminQuartzScheduler]] ERROR com.alibaba.druid.filter.stat.StatFilter -[StatFilter.java:149]- merge sql error, dbType h2, druid-1.1.8, sql : SELECT * FROM QRTZ_LOCKS WHERE SCHED_NAME = 'adminQuartzScheduler' AND LOCK_NAME = ? FOR UPDATE
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :' = ? FOR UPDATE', expect FOR, actual FOR pos 88, line 1, column 85, token FOR
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:284)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:423)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:72)
	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:88)
	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:50)
	at com.alibaba.druid.filter.stat.StatFilter.mergeSql(StatFilter.java:147)
	at com.alibaba.druid.filter.stat.StatFilter.createSqlStat(StatFilter.java:648)
	at com.alibaba.druid.filter.stat.StatFilter.statementPrepareAfter(StatFilter.java:311)
	at com.alibaba.druid.filter.FilterEventAdapter.connection_prepareStatement(FilterEventAdapter.java:124)
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:473)
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.prepareStatement(ConnectionProxyImpl.java:342)
	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:349)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler.invoke(AttributeRestoringConnectionInvocationHandler.java:73)
	at com.sun.proxy.$Proxy140.prepareStatement(Unknown Source)
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:88)
	at org.quartz.impl.jdbcjobstore.DBSemaphore.obtainLock(DBSemaphore.java:113)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doCheckin(JobStoreSupport.java:3320)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.manage(JobStoreSupport.java:3920)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.initialize(JobStoreSupport.java:3905)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.schedulerStarted(JobStoreSupport.java:692)
	at org.quartz.core.QuartzScheduler.start(QuartzScheduler.java:539)
	at org.quartz.impl.StdScheduler.start(StdScheduler.java:142)
	at org.springframework.scheduling.quartz.SchedulerFactoryBean$1.run(SchedulerFactoryBean.java:711)
2018-05-07 20:42:16,129 [Quartz Scheduler [adminQuartzScheduler]] INFO  o.s.scheduling.quartz.LocalDataSourceJobStore -[JobStoreSupport.java:3629]- ClusterManager: detected 1 failed or restarted instances.
2018-05-07 20:42:16,129 [Quartz Scheduler [adminQuartzScheduler]] INFO  o.s.scheduling.quartz.LocalDataSourceJobStore -[JobStoreSupport.java:3488]- ClusterManager: Scanning for instance "Jeping-PC1525681694826"'s failed in-progress jobs.
2018-05-07 20:42:16,144 [Quartz Scheduler [adminQuartzScheduler]] INFO  org.quartz.core.QuartzScheduler -[QuartzScheduler.java:547]- Scheduler adminQuartzScheduler_$_jiaenping1525696922924 started.

**Comment by jeping** [comment]
@wenshao 截图无法上传

**Comment by jeping** [comment]
@wenshao 您好，会在下一版本进行更新解决的问题吗？

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.10
问题修复，请用新版本
