### ISSUE TITLE
请问在jdk7 boot1.X环境下，那个版本可以用？ 

### ISSUE THREAD

**Issue by Zweyer** [alibaba/druid#2560]
由于某些原因，使用的是jdk7，所以不能使用boot2.X。
在使用druid-starter1.1.9发现不兼容，所以尝试降低到1.1.8_20180212和1.1.8，发现好像无法拉取maven包。
网上看到1.1.7有一些问题，所以现在的环境下可以使用哪个版本？谢谢！

下面是使用jdk7、boot 1.5.12.RELEASE、druid-starter1.1.9 报错信息

org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure]; nested exception is java.lang.ClassCastException: java.lang.UnsupportedClassVersionError cannot be cast to [Ljava.lang.Object;
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:618) ~[spring-context-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:301) ~[spring-context-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:247) ~[spring-context-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:608) ~[spring-context-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.processDeferredImportSelectors(ConfigurationClassParser.java:550) ~[spring-context-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:187) ~[spring-context-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:308) ~[spring-context-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:228) ~[spring-context-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:272) ~[spring-context-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:92) ~[spring-context-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:687) ~[spring-context-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:525) ~[spring-context-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.12.RELEASE.jar:1.5.12.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.12.RELEASE.jar:1.5.12.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.12.RELEASE.jar:1.5.12.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.12.RELEASE.jar:1.5.12.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.12.RELEASE.jar:1.5.12.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.12.RELEASE.jar:1.5.12.RELEASE]

**Comment by libindest** [comment]
如果你的jdk是1.7 那么得使用  druid 1.1.8 同时 druid 1.1.8 数据源的配置需要你在Java类中编写。我的写法是 
 @Getter
@Setter
@Configuration
@PropertySource("classpath:application-druid.properties")
//在同样的DataSource中，首先使用被标注的DataSource
@Primary
public class DruidDataSourceConfig extends DataSourceProperties {

    private Logger logger = LoggerFactory.getLogger( DruidDataSourceConfig.class );

    @Value("${spring.datasource.url}")
    private String dbUrl;

    @Value("${spring.datasource.username}")
    private String username;

    @Value("${spring.datasource.password}")
    private String password;

    @Value("${spring.datasource.driver-class-name}")
    private String driverClassName;

    @Value("${spring.datasource.initialSize}")
    private int initialSize;

    @Value("${spring.datasource.minIdle}")
    private int minIdle;

    @Value("${spring.datasource.maxActive}")
    private int maxActive;

    @Value("${spring.datasource.maxWait}")
    private int maxWait;

    @Value("${spring.datasource.timeBetweenEvictionRunsMillis}")
    private int timeBetweenEvictionRunsMillis;

    @Value("${spring.datasource.minEvictableIdleTimeMillis}")
    private int minEvictableIdleTimeMillis;

    @Value("${spring.datasource.validationQuery}")
    private String validationQuery;

    @Value("${spring.datasource.testWhileIdle}")
    private boolean testWhileIdle;

    @Value("${spring.datasource.testOnBorrow}")
    private boolean testOnBorrow;

    @Value("${spring.datasource.testOnReturn}")
    private boolean testOnReturn;

    @Value("${spring.datasource.poolPreparedStatements}")
    private boolean poolPreparedStatements;

    @Value("${spring.datasource.maxPoolPreparedStatementPerConnectionSize}")
    private int maxPoolPreparedStatementPerConnectionSize;

    @Value("${spring.datasource.filters}")
    private String filters;

    @Value("{spring.datasource.connectionProperties}")
    private String connectionProperties;

    //声明其为Bean实例
    @Bean("dataSourceDruid")
    public DataSource getDataSource() {
        DruidDataSource datasource = new DruidDataSource();
        datasource.setUrl( dbUrl );
        datasource.setUsername( username );
        datasource.setPassword( password );
        datasource.setDriverClassName( driverClassName );

        //configuration
        datasource.setInitialSize( initialSize );
        datasource.setMinIdle( minIdle );
        datasource.setMaxActive( maxActive );
        datasource.setMaxWait( maxWait );
        datasource.setTimeBetweenEvictionRunsMillis( timeBetweenEvictionRunsMillis );
        datasource.setMinEvictableIdleTimeMillis( minEvictableIdleTimeMillis );
        datasource.setValidationQuery( validationQuery );
        datasource.setTestWhileIdle( testWhileIdle );
        datasource.setTestOnBorrow( testOnBorrow );
        datasource.setTestOnReturn( testOnReturn );
        datasource.setPoolPreparedStatements( poolPreparedStatements );
        datasource.setMaxPoolPreparedStatementPerConnectionSize( maxPoolPreparedStatementPerConnectionSize );
        try {
            datasource.setFilters( filters );
        } catch (SQLException e) {
            logger.error( "druid configuration initialization filter", e );
        }
        datasource.setConnectionProperties( connectionProperties );

        return datasource;
    }
}

**Comment by lihengming** [comment]
耐心等下下个版本，兼容JDK7，最近就会发掉。
