### ISSUE TITLE
SQL解析异常；MySQL drop多个字段，带有after关键字的语句，添加字段同时添加主键 报错！

### ISSUE THREAD

**Issue by iduanyingjie** [alibaba/druid#2582]
Version:1.1.9

API：

```java
SQLUtils.parseStatements(sql, JdbcConstants.MYSQL);
```

------

sql1:

```mysql
ALTER TABLE test.student DROP Column9, DROP Column10;
```

exception1:

```java
com.alibaba.druid.sql.parser.ParserException: error pos 43, line 1, column 39, token DROP

	at com.alibaba.druid.sql.parser.SQLExprParser.name(SQLExprParser.java:1348)
	at com.alibaba.druid.sql.parser.SQLExprParser.names(SQLExprParser.java:1237)
	at com.alibaba.druid.sql.parser.SQLExprParser.names(SQLExprParser.java:1218)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseAlterDrop(MySqlStatementParser.java:4104)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseAlterTable(MySqlStatementParser.java:3438)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseAlter(MySqlStatementParser.java:2789)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:191)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:72)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:464)
```

------

sq2:

```mysql
ALTER TABLE `user_movement_log` ADD COLUMN GatewayId INT NOT NULL DEFAULT 0 AFTER `Regionid`;
```

exception2:

```java
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'LT 0 AFTER `Regionid`;', expect IDENTIFIER, actual IDENTIFIER pos 81, line 1, column 76, token IDENTIFIER AFTER

	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:284)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:423)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:72)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:464)
```

------

sql3:

```mysql
ALTER TABLE `user_movement_log` CHANGE `GatewayId` `GatewayId` INT NOT NULL DEFAULT 0 AFTER RegionID;
```

exception3:

```java
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'ANGE `GatewayId` `GatewayId` INT NO', expect COLUMN, actual IDENTIFIER pos 50, line 1, column 39, token IDENTIFIER `GatewayId`

	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:284)
	at com.alibaba.druid.sql.parser.SQLParser.accept(SQLParser.java:292)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseAlter(SQLStatementParser.java:1180)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:191)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:72)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:464)
```

------

sql4:

```mysql
ALTER TABLE test.student ADD c INT UNSIGNED NOT NULL AUTO_INCREMENT, ADD PRIMARY KEY (c);
ALTER TABLE test.student ADD c INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY;
```

exception4:

```java
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :' INT UNSIGNED NOT NULL AUTO_INCREME', expect IDENTIFIER, actual IDENTIFIER pos 43, line 1, column 35, token IDENTIFIER UNSIGNED

	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:284)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:423)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:72)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:464)
```

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.10
问题修复，请用新版本
