### ISSUE TITLE
 connection holder is null

### ISSUE THREAD

**Issue by wangyan1218** [alibaba/druid#2587]
Mysql:5.6.16, druid:1.1.8,Mysql驱动: 5.1.45 ,断开所有数据库会话大致出现大量java.sql.SQLException: connection holder is null

**Comment by hellopower** [comment]
开始执行查询的时候遇到同样错误
`
java.sql.SQLException: connection holder is null
        at com.alibaba.druid.pool.DruidPooledConnection.checkStateInternal(DruidPooledConnection.java:1112)
        at com.alibaba.druid.pool.DruidPooledConnection.checkState(DruidPooledConnection.java:1105)
        at com.alibaba.druid.pool.DruidPooledConnection.getHoldability(DruidPooledConnection.java:961)
        at com.dianping.zebra.single.jdbc.SingleConnection.getHoldability(SingleConnection.java:182)
        at com.dianping.zebra.group.jdbc.GroupPreparedStatement.createPreparedStatementInternal(GroupPreparedStatement.java:76)
        at com.dianping.zebra.group.jdbc.GroupPreparedStatement.executeQueryOnConnection(GroupPreparedStatement.java:144)
        at com.dianping.zebra.group.jdbc.GroupPreparedStatement.executeQuery(GroupPreparedStatement.java:140)
        at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeQuery(ParamLoggingPreparedStatement.java:375)
        at org.datanucleus.store.rdbms.SQLController.executeStatementQuery(SQLController.java:552)
`

**Comment by jiaqiang-coder** [comment]
解决了吗
