### ISSUE TITLE
java.lang.ClassCastException: com.alibaba.druid.proxy.jdbc.ClobProxyImpl cannot be cast to oracle.sql.CLOB

### ISSUE THREAD

**Issue by FightSCJP** [alibaba/druid#2588]
项目使用JPA 的hibernate实现，在进行EntityManager.merge时报错：
`Caused by: java.lang.ClassCastException: com.alibaba.druid.proxy.jdbc.ClobProxyImpl cannot be cast to oracle.sql.CLOB
	at oracle.jdbc.driver.OraclePreparedStatement.setClob(OraclePreparedStatement.java:6805)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.setClob(OraclePreparedStatementWrapper.java:162)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_setClob(FilterChainImpl.java:3100)
	at com.alibaba.druid.filter.FilterAdapter.preparedStatement_setClob(FilterAdapter.java:1217)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_setClob(FilterChainImpl.java:3097)
	at com.alibaba.druid.filter.FilterAdapter.preparedStatement_setClob(FilterAdapter.java:1217)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_setClob(FilterChainImpl.java:3097)
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.setClob(PreparedStatementProxyImpl.java:328)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.setClob(DruidPooledPreparedStatement.java:614)
	... 34 more`

**Comment by FightSCJP** [comment]
Druid版本：1.1.9
数据库：oracle数据库，驱动ojdbc6-11.2.0.4.0
Hibernate版本：3.6.8.Final

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.10
问题修复，请用新版本
