### ISSUE TITLE
 No operations allowed after statement closed

### ISSUE THREAD

**Issue by QuanGangDeng** [alibaba/druid#2599]
程序运执行数据插入操作的时候报了这个,请教一下各位大神，是偶现的一个问题。
druid 版本是 1.0.28
Caused by: org.apache.ibatis.type.TypeException: Error setting non null for parameter #1 with JdbcType VARCHAR . Try setting a different JdbcType for this parameter or a different configuration property. Cause: java.sql.SQLException: No operations allowed after statement closed.
        at org.apache.ibatis.type.BaseTypeHandler.setParameter(BaseTypeHandler.java:55)
        at org.apache.ibatis.scripting.defaults.DefaultParameterHandler.setParameters(DefaultParameterHandler.java:87)
        ... 154 common frames omitted
Caused by: java.sql.SQLException: No operations allowed after statement closed.
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
        at com.mysql.jdbc.StatementImpl.checkClosed(StatementImpl.java:442)
        at com.mysql.jdbc.PreparedStatement.setString(PreparedStatement.java:3875)
        at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_setString(FilterChainImpl.java:2823)
        at com.alibaba.druid.filter.FilterAdapter.preparedStatement_setString(FilterAdapter.java:1340)
        at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_setString(FilterChainImpl.java:2820)
        at com.alibaba.druid.filter.FilterAdapter.preparedStatement_setString(FilterAdapter.java:1340)
        at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_setString(FilterChainImpl.java:2820)
        at com.alibaba.druid.filter.FilterAdapter.preparedStatement_setString(FilterAdapter.java:1340)
        at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_setString(FilterChainImpl.java:2820)
        at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.setString(PreparedStatementProxyImpl.java:560)
        at com.alibaba.druid.pool.DruidPooledPreparedStatement.setString(DruidPooledPreparedStatement.java:365)
        at org.apache.ibatis.type.StringTypeHandler.setNonNullParameter(StringTypeHandler.java:31)
        at org.apache.ibatis.type.StringTypeHandler.setNonNullParameter(StringTypeHandler.java:26)
        at org.apache.ibatis.type.BaseTypeHandler.setParameter(BaseTypeHandler.java:53)
        ... 155 common frames omitted

**Comment by iamlinhui** [comment]
同样的问题

**Comment by iamlinhui** [comment]
> 程序运执行数据插入操作的时候报了这个,请教一下各位大神，是偶现的一个问题。
> druid 版本是 1.0.28
> Caused by: org.apache.ibatis.type.TypeException: Error setting non null for parameter #1 with JdbcType VARCHAR . Try setting a different JdbcType for this parameter or a different configuration property. Cause: java.sql.SQLException: No operations allowed after statement closed.
> at org.apache.ibatis.type.BaseTypeHandler.setParameter(BaseTypeHandler.java:55)
> at org.apache.ibatis.scripting.defaults.DefaultParameterHandler.setParameters(DefaultParameterHandler.java:87)
> ... 154 common frames omitted
> Caused by: java.sql.SQLException: No operations allowed after statement closed.
> at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
> at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
> at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
> at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
> at com.mysql.jdbc.StatementImpl.checkClosed(StatementImpl.java:442)
> at com.mysql.jdbc.PreparedStatement.setString(PreparedStatement.java:3875)
> at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_setString(FilterChainImpl.java:2823)
> at com.alibaba.druid.filter.FilterAdapter.preparedStatement_setString(FilterAdapter.java:1340)
> at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_setString(FilterChainImpl.java:2820)
> at com.alibaba.druid.filter.FilterAdapter.preparedStatement_setString(FilterAdapter.java:1340)
> at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_setString(FilterChainImpl.java:2820)
> at com.alibaba.druid.filter.FilterAdapter.preparedStatement_setString(FilterAdapter.java:1340)
> at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_setString(FilterChainImpl.java:2820)
> at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.setString(PreparedStatementProxyImpl.java:560)
> at com.alibaba.druid.pool.DruidPooledPreparedStatement.setString(DruidPooledPreparedStatement.java:365)
> at org.apache.ibatis.type.StringTypeHandler.setNonNullParameter(StringTypeHandler.java:31)
> at org.apache.ibatis.type.StringTypeHandler.setNonNullParameter(StringTypeHandler.java:26)
> at org.apache.ibatis.type.BaseTypeHandler.setParameter(BaseTypeHandler.java:53)
> ... 155 common frames omitted

这个问题解决了么

**Comment by blitzpan** [comment]
1.0.28，出现同样的问题。我的场景是第一次由于数据存在超长导致入库失败，第二次的合法数据入库就会报这个错误。升级druid版本之后解决了问题。

**Comment by QuanGangDeng** [comment]
嗯。升级了后问题解决了
