### ISSUE TITLE
格式化sql报StackOverflow

### ISSUE THREAD

**Issue by xili** [alibaba/druid#2635]
数据库：SQL server
druid版本：1.1.9

sql(比较长，截取部分):`INSERT dbo.TSPopedom (UserID,FunctionID,Popedom,Description,Status)  Select N'666993','KYLMS',1,N'测试使用',1  UNION ALL  Select N'666993','M_LogisticsCW',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWPrepayManage',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWPrepayManagemyButton1',1,N'测试使用',1  UNION ALL  Select N'666993','Frm_TA_CWPrepayManageButton02',1,N'测试使用',1  UNION ALL  Select N'666993','Frm_TA_CWPrepayManageButton01',1,N'测试使用',1  UNION ALL  Select N'666993','Frm_TA_CWPrepayManageButton03',1,N'测试使用',1  UNION ALL  Select N'666993','Frm_TA_CWPrepayManageButton05',1,N'测试使用',1  UNION ALL  Select N'666993','Frm_TA_CWPrepayManageButton06',1,N'测试使用',1  UNION ALL  Select N'666993','Frm_TA_CWPrepayManageButton07',1,N'测试使用',1  UNION ALL  Select N'666993','Frm_TA_CWPrepayManageButton04',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWPrepayManageButton100',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWPrepayManagebtn_NoDeposit',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWPrepayManageButton08',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWPrepayManageButton09',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWPrepayManageButton12',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWPrepayManageButton13',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWPrepayManageButton14',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWPrepayManageButton15',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWPrepayManageButton10',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWPrepayManageButton11',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWPrepayManageBtn_Sum_Q',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWPrepayManagebtn_Update',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWPrepayManagebtn_CodeReplace',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWPrepayManagebtn_LocationQ',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWPrepayRepayment',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWPrepayRepaymentmyButton1',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWPrepayRepaymentButton02',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWPrepayRepaymentButton01',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWPrepayRepaymentButton03',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWPrepayRepaymentButton05',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWPrepayRepaymentButton06',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWPrepayRepaymentButton07',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWPrepayRepaymentButton04',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWPrepayRepaymentmyButton4',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWPrepayRepaymentmyButton2',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWPrepayRepaymentButton12',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWPrepayRepaymentButton13',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWPrepayRepaymentButton08',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWPrepayRepaymentButton09',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWPrepayRepaymentButton10',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWPrepayRepaymentButton11',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWPrepayRepaymentBtn_Sum_Q',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWExpenseManage',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWExpenseManagebtn_InvoiceArea',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWExpenseManagebtn_NoAuditToFrist',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWExpenseManagebtn_workshopUpdate',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWExpenseManagemyButton1',1,N'测试使用',1  UNION ALL  Select N'666993','Frm_TA_CWExpenseManageButton02',1,N'测试使用',1  UNION ALL  Select N'666993','Frm_TA_CWExpenseManageButton01',1,N'测试使用',1  UNION ALL  Select N'666993','Frm_TA_CWExpenseManageButton03',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWExpenseManagemyButton9',1,N'测试使用',1  UNION ALL  Select N'666993','Frm_TA_CWExpenseManageButton05',1,N'测试使用',1  UNION ALL  Select N'666993','Frm_TA_CWExpenseManageButton06',1,N'测试使用',1  UNION ALL  Select N'666993','Frm_TA_CWExpenseManageButton07',1,N'测试使用',1  UNION ALL  Select N'666993','Frm_TA_CWExpenseManageButton04',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWExpenseManagebtn_Check',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWExpenseManagebtn_Confirm',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWExpenseManagebtnRList',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWExpenseManagebtn_jkxz',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWExpenseManageBtn_MarketSubsidy',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWExpenseManagebtn_Reset',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWExpenseManagebtn_SpecialUser',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWExpenseManageBtn_wtdj',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWExpenseManageButton16',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWExpenseManageButton15',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWExpenseManageBtn_OnlineBkExport',1,N'测试使用',1  UNION ALL  Select N'666993','FRM_TA_CWExpenseManageButton100',1,N'测试使用' `

错误：`java.lang.StackOverflowError
	at com.alibaba.druid.sql.parser.Lexer.charAt(Lexer.java:126)
	at com.alibaba.druid.sql.parser.Lexer.scanChar(Lexer.java:232)
	at com.alibaba.druid.sql.parser.Lexer.nextToken(Lexer.java:595)
	at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:384)
	at com.alibaba.druid.sql.dialect.sqlserver.parser.SQLServerExprParser.primary(SQLServerExprParser.java:90)
	at com.alibaba.druid.sql.parser.SQLExprParser.expr(SQLExprParser.java:86)
	at com.alibaba.druid.sql.dialect.sqlserver.parser.SQLServerExprParser.parseSelectItem(SQLServerExprParser.java:234)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseSelectList(SQLSelectParser.java:508)
	at com.alibaba.druid.sql.dialect.sqlserver.parser.SQLServerSelectParser.query(SQLServerSelectParser.java:150)
	at com.alibaba.druid.sql.parser.SQLSelectParser.queryRest(SQLSelectParser.java:116)
	at com.alibaba.druid.sql.dialect.sqlserver.parser.SQLServerSelectParser.query(SQLServerSelectParser.java:170)
	at com.alibaba.druid.sql.parser.SQLSelectParser.queryRest(SQLSelectParser.java:116)
	at com.alibaba.druid.sql.dialect.sqlserver.parser.SQLServerSelectParser.query(SQLServerSelectParser.java:170)
	at com.alibaba.druid.sql.parser.SQLSelectParser.queryRest(SQLSelectParser.java:116)
	at com.alibaba.druid.sql.dialect.sqlserver.parser.SQLServerSelectParser.query(SQLServerSelectParser.java:170)
	at com.alibaba.druid.sql.parser.SQLSelectParser.queryRest(SQLSelectParser.java:116)
	at com.alibaba.druid.sql.dialect.sqlserver.parser.SQLServerSelectParser.query(SQLServerSelectParser.java:170)
	at com.alibaba.druid.sql.parser.SQLSelectParser.queryRest(SQLSelectParser.java:116)
	at com.alibaba.druid.sql.dialect.sqlserver.parser.SQLServerSelectParser.query(SQLServerSelectParser.java:170)
	at com.alibaba.druid.sql.parser.SQLSelectParser.queryRest(SQLSelectParser.java:116)
	at com.alibaba.druid.sql.dialect.sqlserver.parser.SQLServerSelectParser.query(SQLServerSelectParser.java:170)
	at com.alibaba.druid.sql.parser.SQLSelectParser.queryRest(SQLSelectParser.java:116)
	at com.alibaba.druid.sql.dialect.sqlserver.parser.SQLServerSelectParser.query(SQLServerSelectParser.java:170)
	at com.alibaba.druid.sql.parser.SQLSelectParser.queryRest(SQLSelectParser.java:116)
	at com.alibaba.druid.sql.dialect.sqlserver.parser.SQLServerSelectParser.query(SQLServerSelectParser.java:170)
	at com.alibaba.druid.sql.parser.SQLSelectParser.queryRest(SQLSelectParser.java:116)
	at com.alibaba.druid.sql.dialect.sqlserver.parser.SQLServerSelectParser.query(SQLServerSelectParser.java:170)
	at com.alibaba.druid.sql.parser.SQLSelectParser.queryRest(SQLSelectParser.java:116)
	at com.alibaba.druid.sql.dialect.sqlserver.parser.SQLServerSelectParser.query(SQLServerSelectParser.java:170)`

**Comment by guoyi8** [comment]
@xili 您好，我也遇到了这个问题，请求您是解决了么？
