### ISSUE TITLE
druid-SQLStatementParser 解析带注释的create失败

### ISSUE THREAD

**Issue by joyken** [alibaba/druid#2637]
mysql> CREATE DATABASE /*!32312 IF NOT EXISTS*/ `abcc` /*!40100 DEFAULT CHARACTER SET utf8 */;
抛了异常如下，
ERROR 4001 (HY000): com.alibaba.druid.sql.parser.ParserException: error pos 40, line 1, column 16, token HINT
	at com.alibaba.druid.sql.parser.SQLExprParser.name(SQLExprParser.java:1334)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseCreateDatabase(MySqlStatementParser.java:4079)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseCreate(MySqlStatementParser.java:259)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:159)
	at com.a

**Comment by navee** [comment]
`--`注释不会有问题
`/*  */`注释会报错
