### ISSUE TITLE
【1.1.10】Mysql：SQL解析报错

### ISSUE THREAD

**Issue by shanyuxiyun** [alibaba/druid#2644]
SQL语句：
```

CREATE TABLE IF NOT EXISTS `t_category` (
  `id` varchar(32) COLLATE utf8_bin NOT NULL,
  `name` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '名称',
  `code` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '编码',
  `description` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '介绍',
  `parentId` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '父类节点',
  `preset` tinyint(1) NOT NULL COMMENT '是否预置',
  `beId` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '分销商Id',
  `beCode` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '分销商编码',
  `targetBeId` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '目标分销商Id',
  `targetBeCode` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '目标分销商编码',
  `spu` text COLLATE utf8_bin,
  `createTime` datetime COLLATE utf8_bin DEFAULT NULL COMMENT '创建时间',
  `updateTime` datetime COLLATE utf8_bin DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


```

错误：
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'time COLLATE utf8_bin DEFAULT NULL ', expect RPAREN, actual IDENTIFIER pos 755, line 14, column 25, token IDENTIFIER COLLATE
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:284)
	at com.alibaba.druid.sql.parser.SQLParser.accept(SQLParser.java:292)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlCreateTableParser.parseCreateTable(MySqlCreateTableParser.java:268)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseCreate(MySqlStatementParser.java:243)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:161)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:72)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:464)

```

**Comment by wenshao** [comment]
druid什么版本？
