### ISSUE TITLE
如何关闭掉druid心跳检测的日志

### ISSUE THREAD

**Issue by woniu4500** [alibaba/druid#2646]
14:15:05.180 [http-nio-20000-exec-2] ERROR druid.sql.Statement
                                - {conn-10003, stmt-20079} execute error. SELECT 1 FROM DUAL
java.sql.SQLRecoverableException: IO Error: Connection reset
        at oracle.jdbc.driver.T4CStatement.executeForDescribe(T4CStatement.java:886)
        at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1167)
        at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1289)
        at oracle.jdbc.driver.OracleStatement.executeQuery(OracleStatement.java:1491)
        at oracle.jdbc.driver.OracleStatementWrapper.executeQuery(OracleStatementWrapper.java:406)
        at com.alibaba.druid.filter.FilterChainImpl.statement_executeQuery(FilterChainImpl.java:2363)
        at com.alibaba.druid.filter.FilterAdapter.statement_executeQuery(FilterAdapter.java:2481)
        at com.alibaba.druid.filter.FilterEventAdapter.statement_executeQuery(FilterEventAdapter.java:302)
        at com.alibaba.druid.filter.FilterChainImpl.statement_executeQuery(FilterChainImpl.java:2360)
        at com.alibaba.druid.wall.WallFilter.statement_executeQuery(WallFilter.java:511)
        at com.alibaba.druid.filter.FilterChainImpl.statement_executeQuery(FilterChainImpl.java:2360)

**Comment by dchack** [comment]
如果你是配置了spring.datasource.validationQuery=SELECT 1 FROM DUAL
删除 validationQuery 配置即可
