### ISSUE TITLE
Communications link failure during rollback(). Transaction resolution unknown.

### ISSUE THREAD

**Issue by zongxingy** [alibaba/druid#2651]
2018-06-06 at 00:05:20 CST ERROR com.alibaba.druid.util.JdbcUtils 75 close - close connection error com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown.
        at sun.reflect.GeneratedConstructorAccessor73.newInstance(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.7.0_85]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[?:1.7.0_85]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.40.jar:5.1.40]
        at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.40.jar:5.1.40]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:918) ~[mysql-connector-java-5.1.40.jar:5.1.40]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:897) ~[mysql-connector-java-5.1.40.jar:5.1.40]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:886) ~[mysql-connector-java-5.1.40.jar:5.1.40]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860) ~[mysql-connector-java-5.1.40.jar:5.1.40]
        at com.mysql.jdbc.ConnectionImpl.rollback(ConnectionImpl.java:4602) ~[mysql-connector-java-5.1.40.jar:5.1.40]
        at com.mysql.jdbc.ConnectionImpl.realClose(ConnectionImpl.java:4233) ~[mysql-connector-java-5.1.40.jar:5.1.40]
        at com.mysql.jdbc.ConnectionImpl.close(ConnectionImpl.java:1531) ~[mysql-connector-java-5.1.40.jar:5.1.40]
        at com.alibaba.druid.util.JdbcUtils.close(JdbcUtils.java:73) [druid-1.1.9.jar:1.1.9]
        at com.alibaba.druid.pool.DruidDataSource.discardConnection(DruidDataSource.java:1338) [druid-1.1.9.jar:1.1.9]
        at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1273) [druid-1.1.9.jar:1.1.9]
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1233) [druid-1.1.9.jar:1.1.9]
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1223) [druid-1.1.9.jar:1.1.9]
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:90) [druid-1.1.9.jar:1.1.9]
        at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:246) [spring-jdbc-4.3.15.RELEASE.jar:4.3.15.RELEASE]
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:377) [spring-tx-4.3.15.RELEASE.jar:4.3.15.RELEASE]
        at com.cnc.xdr.etl.load.datatarget.db.jdbc.JdbcIncrementDataTarget.load(JdbcIncrementDataTarget.java:40) [cdt-xdr-node-1.5.1-1.jar:?]
        at com.cnc.xdr.etl.load.datatarget.db.jdbc.JdbcDataTargetDelegate.load(JdbcDataTargetDelegate.java:56) [cdt-xdr-node-1.5.1-1.jar:?]
        at com.cnc.xdr.etl.load.datatarget.DataTargetFactory$DataTargetDelegate.load(DataTargetFactory.java:84) [cdt-xdr-node-1.5.1-1.jar:?]

**Comment by zongxingy** [comment]
durid版本1.1.9

**Comment by zongxingy** [comment]
设置keepAlive=true后修复
