### ISSUE TITLE
请问SQL解析后的对象怎么再转成sql

### ISSUE THREAD

**Issue by bugmeng** [alibaba/druid#2655]
比如说       
 OracleStatementParser oracleStatementParser = new OracleStatementParser(sql);
        List<SQLStatement> statementList = oracleStatementParser.parseStatementList();
            OracleSchemaStatVisitor visitor = new OracleSchemaStatVisitor();

visitor 如何转成Mysql的一段（新）sql？

谢谢！

**Comment by wenshao** [comment]
stmt.toString()

**Comment by wenshao** [comment]
com.alibaba.druid.sql.SQLUtils#toSQLString(java.util.List<com.alibaba.fastsql.sql.ast.SQLStatement>, com.alibaba.fastsql.DbType)

**Comment by bugmeng** [comment]
com.alibaba.fastsql 这个包要引是么？
看toSQLString 没有fastsql 的参数
`
        sql = "update a set a.c = '1' ,a.e = '2' where a.b = '\"bbbbb' and a.d = '3'";
        OracleStatementParser oracleStatementParser = new OracleStatementParser(sql);
        List<SQLStatement> statementList = oracleStatementParser.parseStatementList();
        System.out.println(SQLUtils.toSQLString(statementList,JdbcConstants.MYSQL));

`
执行之后
Exception in thread "main" java.lang.StackOverflowError
	at com.alibaba.druid.sql.dialect.oracle.ast.stmt.OracleUpdateStatement.accept0(OracleUpdateStatement.java:55)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:41)
	at com.alibaba.druid.sql.dialect.oracle.ast.stmt.OracleUpdateStatement.accept0(OracleUpdateStatement.java:55)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:41)
	at com.alibaba.druid.sql.dialect.oracle.ast.stmt.OracleUpdateStatement.accept0(OracleUpdateStatement.java:55)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:41)
	at com.alibaba.druid.sql.dialect.oracle.ast.stmt.OracleUpdateStatement.accept0(OracleUpdateStatement.java:55)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:41)
	at com.alibaba.druid.sql.dialect.oracle.ast.stmt.OracleUpdateStatement.accept0(OracleUpdateStatement.java:55)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:41)
	at com.alibaba.druid.sql.dialect.oracle.ast.stmt.OracleUpdateStatement.accept0(OracleUpdateStatement.java:55)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:41)
	at com.alibaba.druid.sql.dialect.oracle.ast.stmt.OracleUpdateStatement.accept0(OracleUpdateStatement.java:55)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:41)
	at com.alibaba.druid.sql.dialect.oracle.ast.stmt.OracleUpdateStatement.accept0(OracleUpdateStatement.java:55)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:41)
	at com.alibaba.druid.sql.dialect.oracle.ast.stmt.OracleUpdateStatement.accept0(OracleUpdateStatement.java:55)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:41)
	at com.alibaba.druid.sql.dialect.oracle.ast.stmt.OracleUpdateStatement.accept0(OracleUpdateStatement.java:55)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:41)
	at com.alibaba.druid.sql.dialect.oracle.ast.stmt.OracleUpdateStatement.accept0(OracleUpdateStatement.java:55)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:41)

**Comment by bugmeng** [comment]
@wenshao 

谢谢！
