### ISSUE TITLE
testWhileIdle 检测疑似bug？

### ISSUE THREAD

**Issue by imperio-wxm** [alibaba/druid#2670]
![image](https://user-images.githubusercontent.com/8111349/42032327-cee669b6-7b0b-11e8-845b-5b97c517d8b2.png)

如图，开启了testWhileIdle，检测时间30s。

从debug日志看，只有第一次初始化的时候对20个连接全部做了检测，之后每次只对调用的连接座做检测？

- 初始化

```java
2018-06-28 19:38:45.884 DEBUG 23137 --- [o-19200-exec-10] druid.sql.Connection                     : {conn-10001} connected
2018-06-28 19:38:45.886 DEBUG 23137 --- [o-19200-exec-10] druid.sql.Connection                     : {conn-10001} setAutoCommit true
2018-06-28 19:38:45.888 DEBUG 23137 --- [o-19200-exec-10] druid.sql.Statement                      : {conn-10001, stmt-20000} created
2018-06-28 19:38:45.959 DEBUG 23137 --- [o-19200-exec-10] druid.sql.Statement                      : {conn-10001, stmt-20000, rs-50000} query executed. 70.329535 millis. SELECT 1
2018-06-28 19:38:45.961 DEBUG 23137 --- [o-19200-exec-10] druid.sql.Statement                      : {conn-10001, stmt-20000} closed
2018-06-28 19:38:45.963 DEBUG 23137 --- [o-19200-exec-10] druid.sql.Connection                     : {conn-10002} connected
2018-06-28 19:38:45.963 DEBUG 23137 --- [o-19200-exec-10] druid.sql.Connection                     : {conn-10002} setAutoCommit true
2018-06-28 19:38:45.963 DEBUG 23137 --- [o-19200-exec-10] druid.sql.Statement                      : {conn-10002, stmt-20001} created
2018-06-28 19:38:45.964 DEBUG 23137 --- [o-19200-exec-10] druid.sql.Statement                      : {conn-10002, stmt-20001, rs-50001} query executed. 0.467656 millis. SELECT 1
2018-06-28 19:38:45.964 DEBUG 23137 --- [o-19200-exec-10] druid.sql.Statement                      : {conn-10002, stmt-20001} closed
2018-06-28 19:38:45.965 DEBUG 23137 --- [o-19200-exec-10] druid.sql.Connection                     : {conn-10003} connected
2018-06-28 19:38:45.966 DEBUG 23137 --- [o-19200-exec-10] druid.sql.Connection                     : {conn-10003} setAutoCommit true
2018-06-28 19:38:45.966 DEBUG 23137 --- [o-19200-exec-10] druid.sql.Statement                      : {conn-10003, stmt-20002} created
2018-06-28 19:38:45.966 DEBUG 23137 --- [o-19200-exec-10] druid.sql.Statement                      : {conn-10003, stmt-20002, rs-50002} query executed. 0.240108 millis. SELECT 1
2018-06-28 19:38:45.967 DEBUG 23137 --- [o-19200-exec-10] druid.sql.Statement                      : {conn-10003, stmt-20002} closed
2018-06-28 19:38:45.967 DEBUG 23137 --- [o-19200-exec-10] druid.sql.Connection                     : {conn-10004} connected
2018-06-28 19:38:45.968 DEBUG 23137 --- [o-19200-exec-10] druid.sql.Connection                     : {conn-10004} setAutoCommit true
2018-06-28 19:38:45.968 DEBUG 23137 --- [o-19200-exec-10] druid.sql.Statement                      : {conn-10004, stmt-20003} created
2018-06-28 19:38:45.969 DEBUG 23137 --- [o-19200-exec-10] druid.sql.Statement                      : {conn-10004, stmt-20003, rs-50003} query executed. 0.260042 millis. SELECT 1
2018-06-28 19:38:45.969 DEBUG 23137 --- [o-19200-exec-10] druid.sql.Statement                      : {conn-10004, stmt-20003} closed
2018-06-28 19:38:45.969 DEBUG 23137 --- [o-19200-exec-10] druid.sql.Connection                     : {conn-10005} connected
2018-06-28 19:38:45.970 DEBUG 23137 --- [o-19200-exec-10] druid.sql.Connection                     : {conn-10005} setAutoCommit true
2018-06-28 19:38:45.970 DEBUG 23137 --- [o-19200-exec-10] druid.sql.Statement                      : {conn-10005, stmt-20004} created
2018-06-28 19:38:45.971 DEBUG 23137 --- [o-19200-exec-10] druid.sql.Statement                      : {conn-10005, stmt-20004, rs-50004} query executed. 0.278098 millis. SELECT 1
2018-06-28 19:38:45.971 DEBUG 23137 --- [o-19200-exec-10] druid.sql.Statement                      : {conn-10005, stmt-20004} closed
2018-06-28 19:38:45.971 DEBUG 23137 --- [o-19200-exec-10] druid.sql.Connection                     : {conn-10006} connected
2018-06-28 19:38:45.972 DEBUG 23137 --- [o-19200-exec-10] druid.sql.Connection                     : {conn-10006} setAutoCommit true
2018-06-28 19:38:45.972 DEBUG 23137 --- [o-19200-exec-10] druid.sql.Statement                      : {conn-10006, stmt-20005} created
2018-06-28 19:38:45.973 DEBUG 23137 --- [o-19200-exec-10] druid.sql.Statement                      : {conn-10006, stmt-20005, rs-50005} query executed. 0.294172 millis. SELECT 1
2018-06-28 19:38:45.973 DEBUG 23137 --- [o-19200-exec-10] druid.sql.Statement                      : {conn-10006, stmt-20005} closed
2018-06-28 19:38:45.974 DEBUG 23137 --- [o-19200-exec-10] druid.sql.Connection                     : {conn-10007} connected
2018-06-28 19:38:45.974 DEBUG 23137 --- [o-19200-exec-10] druid.sql.Connection                     : {conn-10007} setAutoCommit true
2018-06-28 19:38:45.974 DEBUG 23137 --- [o-19200-exec-10] druid.sql.Statement                      : {conn-10007, stmt-20006} created
2018-06-28 19:38:45.975 DEBUG 23137 --- [o-19200-exec-10] druid.sql.Statement                      : {conn-10007, stmt-20006, rs-50006} query executed. 0.258402 millis. SELECT 1
2018-06-28 19:38:45.975 DEBUG 23137 --- [o-19200-exec-10] druid.sql.Statement                      : {conn-10007, stmt-20006} closed
............
```

- 对使用的做检测

```java
2018-06-28 19:46:42.417 DEBUG 23137 --- [io-19200-exec-2] druid.sql.Statement                      : {conn-10018, stmt-20040} created
2018-06-28 19:46:42.417 DEBUG 23137 --- [io-19200-exec-5] druid.sql.Statement                      : {conn-10020, stmt-20041} created
2018-06-28 19:46:42.418 DEBUG 23137 --- [io-19200-exec-5] druid.sql.Statement                      : {conn-10020, stmt-20041, rs-50040} query executed. 0.419687 millis. SELECT 1
2018-06-28 19:46:42.418 DEBUG 23137 --- [io-19200-exec-2] druid.sql.Statement                      : {conn-10018, stmt-20040, rs-50041} query executed. 0.703617 millis. SELECT 1
2018-06-28 19:46:42.419 DEBUG 23137 --- [io-19200-exec-5] druid.sql.Statement                      : {conn-10020, stmt-20041} closed
2018-06-28 19:46:42.419 DEBUG 23137 --- [io-19200-exec-2] druid.sql.Statement                      : {conn-10018, stmt-20040} closed
```

一旦拿到了一个从来没有用过的连接，而且底层已经由于某种原因关闭了，testWhileIdle又不做检测，这时会有问题！

**Comment by nanquanyuhao** [comment]
配置的有问题吧

**Comment by imperio-wxm** [comment]
@nanquanyuhao 

请问下这个配置有问题？
而且空闲的18个连接在7个小时候自动销毁，这7小时是什么默认配置？Destroy？：

- 初始化debug

```java
2018-06-28 19:38:45.884 DEBUG 23137 --- [http-nio-19200-exec-10] druid.sql.Connection                     : {conn-10001} connected
2018-06-28 19:38:45.886 DEBUG 23137 --- [http-nio-19200-exec-10] druid.sql.Connection                     : {conn-10001} setAutoCommit true
2018-06-28 19:38:45.888 DEBUG 23137 --- [http-nio-19200-exec-10] druid.sql.Statement                      : {conn-10001, stmt-20000} created
2018-06-28 19:38:45.959 DEBUG 23137 --- [http-nio-19200-exec-10] druid.sql.Statement                      : {conn-10001, stmt-20000, rs-50000} query executed. 70.329535 millis. SELECT 1
2018-06-28 19:38:45.961 DEBUG 23137 --- [http-nio-19200-exec-10] druid.sql.Statement                      : {conn-10001, stmt-20000} closed
2018-06-28 19:38:45.963 DEBUG 23137 --- [http-nio-19200-exec-10] druid.sql.Connection                     : {conn-10002} connected
2018-06-28 19:38:45.963 DEBUG 23137 --- [http-nio-19200-exec-10] druid.sql.Connection                     : {conn-10002} setAutoCommit true
2018-06-28 19:38:45.963 DEBUG 23137 --- [http-nio-19200-exec-10] druid.sql.Statement                      : {conn-10002, stmt-20001} created
2018-06-28 19:38:45.964 DEBUG 23137 --- [http-nio-19200-exec-10] druid.sql.Statement                      : {conn-10002, stmt-20001, rs-50001} query executed. 0.467656 millis. SELECT 1
2018-06-28 19:38:45.964 DEBUG 23137 --- [http-nio-19200-exec-10] druid.sql.Statement                      : {conn-10002, stmt-20001} closed
2018-06-28 19:38:45.965 DEBUG 23137 --- [http-nio-19200-exec-10] druid.sql.Connection                     : {conn-10003} connected
2018-06-28 19:38:45.966 DEBUG 23137 --- [http-nio-19200-exec-10] druid.sql.Connection                     : {conn-10003} setAutoCommit true
2018-06-28 19:38:45.966 DEBUG 23137 --- [http-nio-19200-exec-10] druid.sql.Statement                      : {conn-10003, stmt-20002} created
2018-06-28 19:38:45.966 DEBUG 23137 --- [http-nio-19200-exec-10] druid.sql.Statement                      : {conn-10003, stmt-20002, rs-50002} query executed. 0.240108 millis. SELECT 1
2018-06-28 19:38:45.967 DEBUG 23137 --- [http-nio-19200-exec-10] druid.sql.Statement                      : {conn-10003, stmt-20002} closed
2018-06-28 19:38:45.967 DEBUG 23137 --- [http-nio-19200-exec-10] druid.sql.Connection                     : {conn-10004} connected
2018-06-28 19:38:45.968 DEBUG 23137 --- [http-nio-19200-exec-10] druid.sql.Connection                     : {conn-10004} setAutoCommit true
2018-06-28 19:38:45.968 DEBUG 23137 --- [http-nio-19200-exec-10] druid.sql.Statement                      : {conn-10004, stmt-20003} created
2018-06-28 19:38:45.969 DEBUG 23137 --- [http-nio-19200-exec-10] druid.sql.Statement                      : {conn-10004, stmt-20003, rs-50003} query executed. 0.260042 millis. SELECT 1
2018-06-28 19:38:45.969 DEBUG 23137 --- [http-nio-19200-exec-10] druid.sql.Statement                      : {conn-10004, stmt-20003} closed
2018-06-28 19:38:45.969 DEBUG 23137 --- [http-nio-19200-exec-10] druid.sql.Connection                     : {conn-10005} connected
2018-06-28 19:38:45.970 DEBUG 23137 --- [http-nio-19200-exec-10] druid.sql.Connection                     : {conn-10005} setAutoCommit true
2018-06-28 19:38:45.970 DEBUG 23137 --- [http-nio-19200-exec-10] druid.sql.Statement                      : {conn-10005, stmt-20004} created
2018-06-28 19:38:45.971 DEBUG 23137 --- [http-nio-19200-exec-10] druid.sql.Statement                      : {conn-10005, stmt-20004, rs-50004} query executed. 0.278098 millis. SELECT 1
2018-06-28 19:38:45.971 DEBUG 23137 --- [http-nio-19200-exec-10] druid.sql.Statement                      : {conn-10005, stmt-20004} closed
2018-06-28 19:38:45.971 DEBUG 23137 --- [http-nio-19200-exec-10] druid.sql.Connection                     : {conn-10006} connected
......
......
......
```

- 销毁debug

```java
2018-06-29 02:38:46.105 DEBUG 23137 --- [Druid-ConnectionPool-Destroy-727978154] druid.sql.Connection                     : {conn-10001} closed
2018-06-29 02:38:46.143 DEBUG 23137 --- [Druid-ConnectionPool-Destroy-727978154] druid.sql.Connection                     : {conn-10002} closed
2018-06-29 02:38:46.144 DEBUG 23137 --- [Druid-ConnectionPool-Destroy-727978154] druid.sql.Connection                     : {conn-10003} closed
2018-06-29 02:38:46.144 DEBUG 23137 --- [Druid-ConnectionPool-Destroy-727978154] druid.sql.Connection                     : {conn-10004} closed
2018-06-29 02:38:46.144 DEBUG 23137 --- [Druid-ConnectionPool-Destroy-727978154] druid.sql.Connection                     : {conn-10005} closed
2018-06-29 02:38:46.144 DEBUG 23137 --- [Druid-ConnectionPool-Destroy-727978154] druid.sql.Connection                     : {conn-10006} closed
2018-06-29 02:38:46.144 DEBUG 23137 --- [Druid-ConnectionPool-Destroy-727978154] druid.sql.Connection                     : {conn-10007} closed
2018-06-29 02:38:46.144 DEBUG 23137 --- [Druid-ConnectionPool-Destroy-727978154] druid.sql.Connection                     : {conn-10008} closed
2018-06-29 02:38:46.144 DEBUG 23137 --- [Druid-ConnectionPool-Destroy-727978154] druid.sql.Connection                     : {conn-10009} closed
2018-06-29 02:38:46.145 DEBUG 23137 --- [Druid-ConnectionPool-Destroy-727978154] druid.sql.Connection                     : {conn-10010} closed
2018-06-29 02:38:46.145 DEBUG 23137 --- [Druid-ConnectionPool-Destroy-727978154] druid.sql.Connection                     : {conn-10011} closed
2018-06-29 02:38:46.145 DEBUG 23137 --- [Druid-ConnectionPool-Destroy-727978154] druid.sql.Connection                     : {conn-10012} closed
2018-06-29 02:38:46.145 DEBUG 23137 --- [Druid-ConnectionPool-Destroy-727978154] druid.sql.Connection                     : {conn-10013} closed
2018-06-29 02:38:46.145 DEBUG 23137 --- [Druid-ConnectionPool-Destroy-727978154] druid.sql.Connection                     : {conn-10014} closed
2018-06-29 02:38:46.145 DEBUG 23137 --- [Druid-ConnectionPool-Destroy-727978154] druid.sql.Connection                     : {conn-10015} closed
2018-06-29 02:38:46.145 DEBUG 23137 --- [Druid-ConnectionPool-Destroy-727978154] druid.sql.Connection                     : {conn-10016} closed
2018-06-29 02:39:16.145 DEBUG 23137 --- [Druid-ConnectionPool-Destroy-727978154] druid.sql.Connection                     : {conn-10019} closed
2018-06-29 02:39:16.146 DEBUG 23137 --- [Druid-ConnectionPool-Destroy-727978154] druid.sql.Connection                     : {conn-10017} closed
```

```java
spring:
  datasource:
    driverClass: org.apache.phoenix.jdbc.PhoenixDriver
    url: 
    initialSize: 20
    maxActive: 64
    minIdle: 20
    validationQuery: SELECT 1
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 30000
    testOnBorrow: false
    testOnReturn: false
    keepAlive: true
    minEvictableIdleTimeMillis: 60000
    maxEvictableIdleTimeMillis: 120000
    webUserName: admin
    webPassword: admin123
    filters: stat,log4j
    logSlowSql: true
    dateFormatTimeZone: GMT+8:00
```

**Comment by JhonwillBao** [comment]
看你的配置里把keepAlive打开了，那么KACheckCnt应该要大于0才对。我现在也遇到类似问题，配置了MySQL和Oracle数据源，在连接池连接（未知原因，不排除服务器的配置）不可用的情况下，不会新建连接。
通过监控看到池内连接在一段时间后最终都会小时，数量小于设置的minIdle值。
并且KACheckCnt数值一直为0。感觉所有的可用检测都没有生效。只是在连接池空一段时间之后，又会新建出minIdle数量的连接。

我的配置应该没问题
> spring:
    datasource:
        druid:
            opt:
                type: com.alibaba.druid.pool.DruidDataSource
                driverClassName: com.mysql.jdbc.Driver
                url: 
                username: d
                password: p
                initial-size: 10
                max-active: 100
                min-idle: 10
                max-wait: 60000
                pool-prepared-statements: true
                max-pool-prepared-statement-per-connection-size: 20
                time-between-eviction-runs-millis: 60000
                min-evictable-idle-time-millis: 300000
                validation-query: SELECT 1 FROM DUAL
                test-while-idle: true
                test-on-borrow: true
                test-on-return: false
                stat-view-servlet:
                    enabled: true
                    url-pattern: /druid/*
            pms:
                driverClassName: oracle.jdbc.OracleDriver
                url:
                username: s
                password: s
                initial-size: 10
                max-active: 100
                min-idle: 10
                max-wait: 60000
                keep-alive: true
                pool-prepared-statements: true
                max-pool-prepared-statement-per-connection-size: 20
                time-between-eviction-runs-millis: 60000
                min-evictable-idle-time-millis: 300000
                validation-query: SELECT 1 FROM DUAL
                test-while-idle: true
                test-on-borrow: true
                test-on-return: false
                stat-view-servlet:
                    enabled: true
                    url-pattern: /druid/*


jstack 查看了进程信息， 发现所有的连接都在runnable

`"http-nio-11080-exec-30" #75 daemon prio=5 os_prio=0 tid=0x00007fac9af60800 nid=0x2590 runnable [0x00007fac085ca000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at oracle.net.ns.Packet.receive(Packet.java:300)
	at oracle.net.ns.DataPacket.receive(DataPacket.java:106)
	at oracle.net.ns.NetInputStream.getNextPacket(NetInputStream.java:315)
	at oracle.net.ns.NetInputStream.read(NetInputStream.java:260)
	at oracle.net.ns.NetInputStream.read(NetInputStream.java:185)
	at oracle.net.ns.NetInputStream.read(NetInputStream.java:102)
	at oracle.jdbc.driver.T4CSocketInputStreamWrapper.readNextPacket(T4CSocketInputStreamWrapper.java:124)
        ...
`
tomcat日志在连接超时之后JdbcUtils.close()会抛出 close statement error

`2018-07-27 14:28:04,130 [ERROR] [http-nio-11080-exec-26] com.alibaba.druid.util.JdbcUtils [JdbcUtils.java : 86] close statement error
java.sql.SQLRecoverableException: Closed Connection
	at oracle.jdbc.driver.PhysicalConnection.needLine(PhysicalConnection.java:5389)
	at oracle.jdbc.driver.OracleStatement.closeOrCache(OracleStatement.java:1578)
	at oracle.jdbc.driver.OracleStatement.close(OracleStatement.java:1563)
	at oracle.jdbc.driver.OracleStatementWrapper.close(OracleStatementWrapper.java:94)
	at com.alibaba.druid.util.JdbcUtils.close(JdbcUtils.java:84)
	at com.alibaba.druid.pool.vendor.OracleValidConnectionChecker.isValidConnection(OracleValidConnectionChecker.java:88)
	at com.alibaba.druid.pool.DruidAbstractDataSource.testConnectionInternal(DruidAbstractDataSource.java:1361)
	at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1266)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4619)
	at com.alibaba.druid.filter.stat.StatFilter.dataSource_getConnection(StatFilter.java:680)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4615)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1231)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1223)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:90)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:151)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:115)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:78)
	at org.mybatis.spring.transaction.SpringManagedTransaction.openConnection(SpringManagedTransaction.java:82)
	at org.mybatis.spring.transaction.SpringManagedTransaction.getConnection(SpringManagedTransaction.java:68)
	at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:336)
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:84)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)`

**Comment by lizongbo** [comment]
请使用最新版验证
