### ISSUE TITLE
ParserException: ERROR 

### ISSUE THREAD

**Issue by zhuam** [alibaba/druid#2716]
SELECT `SCHEMA_NAME` FROM `INFORMATION_SCHEMA`.`SCHEMATA` WHERE TRUE ORDER BY `SCHEMA_NAME` ASC LIMIT , 250

The above sql parse is error ,  stacktreace:

com.alibaba.druid.sql.parser.ParserException: ERROR. token : COMMA, pos : 103
        at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:603)
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.primary(MySqlExprParser.java:177)
        at com.alibaba.druid.sql.parser.SQLExprParser.expr(SQLExprParser.java:85)
        at com.alibaba.druid.sql.parser.SQLExprParser.parseLimit(SQLExprParser.java:2302)
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlSelectParser.query(MySqlSelectParser.java:172)
        at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:59)
        at

**Comment by zhuam** [comment]
SELECT (COUNT(`SCHEMA_NAME`) DIV 250) * 250 FROM `INFORMATION_SCHEMA`.`SCHEMATA` WHERE `SCHEMA_NAME` < 'cdev' ORDER BY `SCHEMA_NAME` ASC

com.alibaba.druid.sql.parser.ParserException: syntax error, expect RPAREN, actual IDENTIFIER DIV
        at com.alibaba.druid.sql.parser.SQLExprParser.accept(SQLExprParser.java:1878)
        at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:220)
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.primary(MySqlExprParser.java:177)
        at com.alibaba.druid.sql.parser.SQLExprParser.expr(SQLExprParser.java:85)
        at com.alibaba.druid.sql.parser.SQLExprParser.parseSelectItem(SQLExprParser.java:2209)
        at com.alibaba.druid.sql.parser.SQLSelectParser.parseSelectList(SQLSelectParser.java:373)
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlSelectParser.query(MySqlSelectParser.java:156)
        at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:59)
        at com.feeyo.route.parser.druid.MycatStatementParser.parseSelect(MycatStatementParser.java:39)
        at com.feeyo.route.parser.druid.MycatStatementParser.parseSelect(MycatStatementParser.java:1)
        at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:119)
        at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:84)
        at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:2094)
        at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:2084)

**Comment by zhuam** [comment]
druid-1.0.31.jar

**Comment by wenshao** [comment]
升级到1.1.10试试看
http://repo1.maven.org/maven2/com/alibaba/druid/1.1.10/
