### ISSUE TITLE
Hive类型split函数语句解析报错

### ISSUE THREAD

**Issue by liufanxiao** [alibaba/druid#2757]
Version : 1.1.10

SQL : 
select split(column01,'-')[0] from table01;

code :
String dbType = JdbcConstants.HIVE;
List<SQLStatement> stmtList = SQLUtils.parseStatements(sql, dbType);

Exception :
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'mn01,'-')[0] from table01 ', expect LBRACKET, actual LBRACKET pos 27, line 1, column 27, token LBRACKET
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:284)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:426)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:72)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:464)

**Comment by youngchow** [comment]
try to use substring_index

**Comment by l568288g** [comment]
Is it fixed?
