### ISSUE TITLE
Hive类型以数字开头的别名语句解析报错

### ISSUE THREAD

**Issue by liufanxiao** [alibaba/druid#2765]
Version : 1.1.10

SQL :
select column01 1a from table01;

code :
String dbType = JdbcConstants.HIVE;
List stmtList = SQLUtils.parseStatements(sql, dbType);

Exception :
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'mn01 1a from table01', expect LITERAL_INT, actual LITERAL_INT pos 17, line 1, column 17, token LITERAL_INT
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:284)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:426)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:72)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:464)
	
PS:
SQL在各版本Hive可以正常执行，测试版本分别为Hive 0.14,Hive 1.2,Hive 2.3

**Comment by photogamerun** [comment]
同问，我这里也发现这个问题
