### ISSUE TITLE
Hive类型row_number() over()函数使用distribute by时语句解析报错

### ISSUE THREAD

**Issue by liufanxiao** [alibaba/druid#2767]
Version : 1.1.10

SQL :
select column01,column02,row_number() over (distribute by column01 sort by column02 desc) rownum from table01;

code :
String dbType = JdbcConstants.HIVE;
List stmtList = SQLUtils.parseStatements(sql, dbType);

Exception :
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: syntax error, expect RPAREN, actual IDENTIFIER pos 54, line 1, column 45, token IDENTIFIER distribute
	at com.alibaba.druid.sql.parser.SQLExprParser.accept(SQLExprParser.java:2639)
	at com.alibaba.druid.sql.parser.SQLExprParser.over(SQLExprParser.java:1579)
	at com.alibaba.druid.sql.parser.SQLExprParser.over(SQLExprParser.java:1466)
	at com.alibaba.druid.sql.parser.SQLExprParser.parseAggregateExpr(SQLExprParser.java:1449)
	at com.alibaba.druid.sql.parser.SQLExprParser.methodRest(SQLExprParser.java:1051)
	at com.alibaba.druid.sql.parser.SQLExprParser.parseSelectItem(SQLExprParser.java:3236)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseSelectList(SQLSelectParser.java:646)
	at com.alibaba.druid.sql.parser.SQLSelectParser.query(SQLSelectParser.java:265)
	at com.alibaba.druid.sql.parser.SQLSelectParser.query(SQLSelectParser.java:207)
	at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:59)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseSelect(SQLStatementParser.java:2436)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:149)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:72)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:464)

**Comment by wenshao** [comment]
应该是partition by而不是distribute by吧

**Comment by liufanxiao** [comment]
Hive官网关于OVER窗口函数的使用介绍和大部分应用场景确实是partition by，但是线上环境有很多用户使用distribute by能正常执行，江湖上关于这两种写法的博客都有，但是没有找到关于两者区别的介绍。

**Comment by liufanxiao** [comment]
好的，谢谢关注此issue。
