### ISSUE TITLE
DB2语法解析报错

### ISSUE THREAD

**Issue by IRoye** [alibaba/druid#2769]
环境： 
druid版本： 1.1.10
DB: DB2
SQL: ` select * from final table ( update audit.user2 set USERPASS='2' where id in (1,21) )`
报错信息：
`Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'inal table ( update audit.user2 set', expect TABLE, actual TABLE pos 25, line 1, column 20, token TABLE
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:284)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:433)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:72)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:464)
	at cn.newdt.audit.MyTest.main(MyTest.java:117)`

**Comment by IRoye** [comment]
@wenshao

**Comment by wenshao** [comment]
这个一个特别的语法，你们用在什么场景？

**Comment by IRoye** [comment]
@wenshao  谢谢温老师:). 这个是抓取的客户DB上的一条SQL，我们拿来做的解析，具体场景目前还不清楚。
