### ISSUE TITLE
在weblogic 12c 启动工程报错

### ISSUE THREAD

**Issue by tungSing** [alibaba/druid#2786]
1.项目为非spring项目，所以没有引用任何spring的包
2.依赖druid-0.2.23版本启动不报错
3.依赖druid-1.0.20版本启动报错
4.tomcat 下启动不报错
错误如下：
``` xml
weblogic.management.DeploymentException: java.lang.ClassNotFoundException: org.springframework.beans.factory.BeanFactoryAware
	at weblogic.application.internal.BaseDeployment.throwAppException(BaseDeployment.java:131)
	at weblogic.application.internal.BaseDeployment.prepare(BaseDeployment.java:245)
	at weblogic.application.internal.SingleModuleDeployment.prepare(SingleModuleDeployment.java:53)
	at weblogic.application.internal.DeploymentStateChecker.prepare(DeploymentStateChecker.java:158)
	at weblogic.deploy.internal.targetserver.AppContainerInvoker.prepare(AppContainerInvoker.java:61)
	Truncated. see log file for complete stacktrace
Caused By: java.lang.ClassNotFoundException: org.springframework.beans.factory.BeanFactoryAware
	at weblogic.utils.classloaders.GenericClassLoader.findLocalClass(GenericClassLoader.java:981)
	at weblogic.utils.classloaders.GenericClassLoader.findClass(GenericClassLoader.java:942)
	at weblogic.utils.classloaders.ChangeAwareClassLoader.findClass(ChangeAwareClassLoader.java:83)
	at weblogic.utils.classloaders.GenericClassLoader.doFindClass(GenericClassLoader.java:564)
	at weblogic.utils.classloaders.GenericClassLoader.loadClass(GenericClassLoader.java:500)
	Truncated. see log file for complete stacktrace
```

**Comment by ranbest** [comment]
我也报这个错误，怎么解决

**Comment by tungSing** [comment]
> 我也报这个错误，怎么解决

我目前是换了一个低版本的

**Comment by kaige9at** [comment]
我也遇到了这个问题，非spring项目，druid版本是1.0.17，weblogic版本是12.2.1.3.0。

**Comment by qmzhangyan** [comment]
这个问题现在也没有解决吗？

**Comment by ranbest** [comment]
好像解决了

**Comment by qmzhangyan** [comment]
如何解决的？

**Comment by nicobeyond** [comment]
暂时采用druid-0.2.23版本解决。
