### ISSUE TITLE
syntax error, expect RPAREN, actual IDENTIFIER INT

### ISSUE THREAD

**Issue by internetafei** [alibaba/druid#2791]
select temp.bizoptid
		from (select  CAST(t.BIZ_OPT_ID AS UNSIGNED INT) bizoptid 
			  from t_oc_bsoption t
			  where t.BIZ_TYPE_CD = ?
			  order by bizoptid desc) temp LIMIT 1
当前用的版本是1.0.16
代码是
String sql="select temp.bizoptid\r\n" + 
				"		from (select  CAST(t.BIZ_OPT_ID AS UNSIGNED INT) bizoptid \r\n" + 
				"			  from t_oc_bsoption t\r\n" + 
				"			  where t.BIZ_TYPE_CD = ?\r\n" + 
				"			  order by bizoptid desc) temp LIMIT 1";
MySqlStatementParser parser = new MySqlStatementParser(sql);
		parser.parseStatementList();
druid 对int 不支持

**Comment by internetafei** [comment]
错误信息：
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: syntax error, expect RPAREN, actual IDENTIFIER bigint
	at com.alibaba.druid.sql.parser.SQLExprParser.accept(SQLExprParser.java:1531)
	at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:408)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.primary(MySqlExprParser.java:166)
	at com.alibaba.druid.sql.parser.SQLExprParser.expr(SQLExprParser.java:121)
	at com.alibaba.druid.sql.parser.SQLExprParser.parseSelectItem(SQLExprParser.java:1827)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseSelectList(SQLSelectParser.java:295)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlSelectParser.query(MySqlSelectParser.java:134)
	at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:60)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlSelectParser.parseTableSource(MySqlSelectParser.java:181)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseFrom(SQLSelectParser.java:314)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlSelectParser.query(MySqlSelectParser.java:139)
	at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:60)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseSelect(MySqlStatementParser.java:215)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:180)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:145)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:140)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:384)
	at M2.main(M2.java:14)
