### ISSUE TITLE
java.sql.SQLException: not support oracle driver 5.1

### ISSUE THREAD

**Issue by lunabird** [alibaba/druid#2792]
您好，请教个问题。
SpringBoot项目，使用druid连接池连接oracle数据库，oracle版本11.2.0.1.0，报错信息如下：
`
java.sql.SQLException: not support oracle driver 5.1
	at com.alibaba.druid.pool.DruidDataSource.initCheck(DruidDataSource.java:1079) [druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:825) [druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1229) [druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1225) [druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:90) [druid-1.1.10.jar:1.1.10]
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111) [spring-jdbc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:77) [spring-jdbc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:394) [spring-jdbc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:474) [spring-jdbc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:484) [spring-jdbc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.queryForList(JdbcTemplate.java:510) [spring-jdbc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
`

pom文件中的相关依赖如下：
`
 
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid</artifactId>
            <version>1.1.10</version>
        </dependency>
        <dependency>
            <groupId>com.oracle</groupId>
            <artifactId>ojdbc6</artifactId>
            <version>11.2.0.1.0</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jdbc</artifactId>
        </dependency>
`

不知道5.1这个版本号是怎么来的？ojdbc6的版本号已经是11.2.0.1.0了，不知道还需要怎样配置才能解决？

**Comment by lunabird** [comment]
是我本地配置文件有误，问题已解决。

**Comment by heppytt** [comment]
请问你是怎么改的配置文件啊

**Comment by lprofession** [comment]
我也遇到这个问题，是什么问题呢？

**Comment by hapitoku** [comment]
应该是mysql 和 oracle 的驱动写错了

**Comment by liu165** [comment]
坑啊，这楼主
