### ISSUE TITLE
关于报SQLRecoverableException异常，

### ISSUE THREAD

**Issue by iamzhangxin** [alibaba/druid#2815]
### 最近在未执行业务操作的情况下，有时候会突然报出这个异常，请问什么时候有可能会引发这个异常

<pre><code>2018-09-18 05:44:32.876 -[ERROR] 28581 [troy-1673266508] com.alibaba.druid.util.JdbcUtils         : close connection error
java.sql.SQLRecoverableException: IO Error: Connection timed out
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:919)
	at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:2005)
	at com.alibaba.druid.filter.FilterChainImpl.connection_close(FilterChainImpl.java:186)
	at com.alibaba.druid.filter.FilterAdapter.connection_close(FilterAdapter.java:776)
	at com.alibaba.druid.filter.FilterChainImpl.connection_close(FilterChainImpl.java:181)
	at com.alibaba.druid.filter.FilterAdapter.connection_close(FilterAdapter.java:776)
	at com.alibaba.druid.filter.FilterChainImpl.connection_close(FilterChainImpl.java:181)
	at com.alibaba.druid.filter.stat.StatFilter.connection_close(StatFilter.java:261)
	at com.alibaba.druid.filter.FilterChainImpl.connection_close(FilterChainImpl.java:181)
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.close(ConnectionProxyImpl.java:115)
	at com.alibaba.druid.util.JdbcUtils.close(JdbcUtils.java:73)
	at com.alibaba.druid.pool.DruidDataSource.shrink(DruidDataSource.java:2797)
	at com.alibaba.druid.pool.DruidDataSource$DestroyTask.run(DruidDataSource.java:2562)
	at com.alibaba.druid.pool.DruidDataSource$DestroyConnectionThread.run(DruidDataSource.java:2549)
Caused by: java.io.IOException: Connection timed out
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at oracle.net.nt.TimeoutSocketChannel.read(TimeoutSocketChannel.java:144)
	at oracle.net.ns.NIOHeader.readHeaderBuffer(NIOHeader.java:82)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:139)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:101)
	at oracle.net.ns.NIONSDataChannel.readDataFromSocketChannel(NIONSDataChannel.java:80)
	at oracle.jdbc.driver.T4CMAREngineNIO.prepareForReading(T4CMAREngineNIO.java:98)
	at oracle.jdbc.driver.T4CMAREngineNIO.unmarshalUB1(T4CMAREngineNIO.java:534)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:485)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:252)
	at oracle.jdbc.driver.T4C7Ocommoncall.doOLOGOFF(T4C7Ocommoncall.java:62)
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:908)
	... 13 common frames omitted
</code></pre>

**Comment by iamzhangxin** [comment]
> 关闭空闲连接

这个是说我有空闲连接没有关闭么

**Comment by iamzhangxin** [comment]
> 关闭空闲连接

这个是说我有空闲连接没有关闭么

**Comment by iamzhangxin** [comment]
@wenshao 这个是说我有空闲连接没有关闭么
