### ISSUE TITLE
升级到1.1.10后，日志中报错IO 错误 socket read time out，连接的是oracle数据源

### ISSUE THREAD

**Issue by kondruz** [alibaba/druid#2816]
升级到1.1.10后，日志中报错IO 错误 socket read time out，连接的是oracle数据源

**Comment by iamzhangxin** [comment]
我也有这个问题

**Comment by oh-jy** [comment]
九月 27, 2018 9:45:39 上午 com.alibaba.druid.util.JdbcUtils close
严重: close connection error
java.sql.SQLRecoverableException: IO 错误: Socket read timed out
也有这个问题

**Comment by CroceIt** [comment]
我也是，Oracle数据库，服务一段时间后就出现报错：IO 错误: Socket read timed out，请问是什么问题？
具体报错如下：
java.sql.SQLRecoverableException: IO 错误: Socket read timed out
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:458)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:546)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:236)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:32)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:521)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:156)
	at com.alibaba.druid.filter.FilterAdapter.connection_connect(FilterAdapter.java:786)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150)
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:218)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1560)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468)
Caused by: oracle.net.ns.NetException: Socket read timed out
	at oracle.net.ns.Packet.receive(Packet.java:339)
	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:296)
	at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1102)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:320)
	... 12 more

**Comment by lurenj** [comment]
大佬，问一下解决了吗？

**Comment by canglangX** [comment]
com.alibaba.druid.pool.DruidAbstractDataSource#DEFAULT_TIME_CONNECT_TIMEOUT_MILLIS
新增了默认超时时间设置，需要覆盖这个配置com.alibaba.druid.pool.DruidAbstractDataSource#setSocketTimeout(int)

**Comment by canglangX** [comment]
原因是升级后新增了默认读超时时间设置com.alibaba.druid.pool.DruidAbstractDataSource#DEFAULT_TIME_CONNECT_TIMEOUT_MILLIS是十秒

想要修改，需要覆盖这个配置com.alibaba.druid.pool.DruidAbstractDataSource#setSocketTimeout(int)

**Comment by wangwufan** [comment]
我用的springboot3，先把druid-spring-boot-starter换成了druid-spring-boot-3-starter，druid升到了最高版本，然后在yml文件里设置connect-timeout和socket-timeout，终于生效了。

**Comment by zhangteng0720** [comment]
如果不设置connect-timeout和socket-timeout默认时间是多少
