### ISSUE TITLE
com.mysql.cj.conf.PropertySet do not have getBooleanReadableProperty

### ISSUE THREAD

**Issue by 1715640858** [alibaba/druid#2823]
I used the latest version：

		<dependency>
			<groupId>com.alibaba</groupId>
			<artifactId>druid</artifactId>
			<version>1.1.11</version>
		</dependency>
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<version>8.0.12</version>
		</dependency>

and error happened when start:
```
java.lang.NoSuchMethodException: com.mysql.cj.conf.PropertySet.getBooleanReadableProperty(java.lang.String)
	at java.lang.Class.getMethod(Unknown Source)
	at com.alibaba.druid.util.MySqlUtils.createXAConnection(MySqlUtils.java:119)
```
and `PropertySet` do not have `getBooleanReadableProperty`

**Comment by 1715640858** [comment]
Permission to this denied to me

**Comment by cmonkey** [comment]
mysql-connector-java 8.0.11 这个方法还是存在的，没有问题

比这个版本高的，没有看到这个方法了，你需要暂时降级版本到8.0.11

**Comment by pigxcloud** [comment]
emmm 降版本也不是个解决办法( ⊙ o ⊙ )！

**Comment by yuanshichao1988** [comment]
mysql降到8.0.11确实启动不报错了，还是希望官方修复issue

**Comment by Redliver** [comment]
mysql-connector-java 8.0.15 和之前的版本有级别为高的[CVE漏洞](https://web.nvd.nist.gov/view/vuln/search-results?adv_search=true&cves=on&cpe_version=cpe%3A%2Fa%3Aoracle%3Aconnector%252fj)
