### ISSUE TITLE
ERROR:"Refresh MATERIALIZED VIEW CONCURRENTLY vw_m_aaa_user_details WITH DATA

### ISSUE THREAD

**Issue by qingyilei** [alibaba/druid#2830]
ERROR com.alibaba.druid.filter.stat.StatFilter - merge sql error, dbType postgresql, druid-1.1.11, sql : Refresh MATERIALIZED VIEW CONCURRENTLY vw_m_aaa_user_details WITH DATA
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'Refresh MATERIALIZED VIEW CONC', expect IDENTIFIER, actual IDENTIFIER pos 7, line 1, column 1, token IDENTIFIER Refresh
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:284)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:433)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:72)
	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:94)
	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:77)
	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:50)

**Comment by DemoCap** [comment]
Caused by: java.sql.SQLException: sql injection violation, dbType postgresql, , druid-version 1.2.5, syntax error: syntax error, error in :'VIEW CONCURRENTLY ?  , pos 40, line 1, column 40, token ? : REFRESH MATERIALIZED VIEW CONCURRENTLY ?
