### ISSUE TITLE
线上运行一段时间后，报Could not initialize class java.sql.SQLException

### ISSUE THREAD

**Issue by chenk818** [alibaba/druid#2833]
CentOS release 6.7 (Final)
java version "1.8.0_73"
druid:1.1.10
一段时间后，一个简单的查询，就会报以下堆栈。应用重启后恢复正常

Caused by: java.lang.NoClassDefFoundError: Could not initialize class java.sql.SQLException
        at com.alibaba.druid.pool.DruidDataSource.handleConnectionException(DruidDataSource.java:1545)
        at com.alibaba.druid.pool.DruidPooledConnection.handleException(DruidPooledConnection.java:133)
        at com.alibaba.druid.pool.DruidPooledStatement.checkException(DruidPooledStatement.java:77)
        at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:502)
        at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:63)
        at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
        at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
        at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
        at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)

**Comment by shixiangwei** [comment]
解决了吗？我们也遇到同样的问题

**Comment by chenk818** [comment]
> 解决了吗？我们也遇到同样的问题

这个错误就是在字段是Timestamp型时出现的，后来也没整明白问题出在哪，把这个字段类型改成非时间型的没再报了

**Comment by 9-sun** [comment]
> > 解决了吗？我们也遇到同样的问题
> 
> 这个错误就是在字段是Timestamp型时出现的，后来也没整明白问题出在哪，把这个字段类型改成非时间型的没再报了

有继续追查下根因不？
