### ISSUE TITLE
mysql语句解析时陷入死循环，程序崩溃

### ISSUE THREAD

**Issue by bensilent** [alibaba/druid#2859]
在使用过程中发现当下条语句在获取列名时，程序会陷入死循环进而崩溃。
```
DELETE c, cm FROM `wp_88comments` c LEFT JOIN `wp_88commentmeta` cm ON c.comment_ID = cm.comment_id WHERE comment_approved = '0'
```
该条语句为一条存在语法错误的sql语句，即where后的条件没有指明归属的表。
希望了解一下遇到这个问题应该如何解决？druid中有可以事先检查sql是否正确的方法提供吗？

具体代码即崩溃提示如下：

```
String sql = "DELETE c, cm FROM `wp_88comments` c LEFT JOIN `wp_88commentmeta` cm ON c.comment_ID = cm.comment_id WHERE comment_approved = '0'";
SQLStatementParser parser = new MySqlStatementParser(sql);
SQLStatement statement = parser.parseStatement();
MySqlSchemaStatVisitor visitor = new MySqlSchemaStatVisitor();
statement.accept(visitor);
Iterator<Column> it = visitor.getColumns().iterator();
while (it.hasNext()) {
    Column c = it.next();
    System.out.println(c.getTable());
    System.out.println(c.getName());
}
```

崩溃提示：
```
at com.alibaba.druid.sql.ast.statement.SQLExprTableSource.findTableSourceWithColumn(SQLExprTableSource.java:271)
at com.alibaba.druid.sql.ast.statement.SQLExprTableSource.findTableSourceWithColumn(SQLExprTableSource.java:271)
at com.alibaba.druid.sql.ast.statement.SQLExprTableSource.findTableSourceWithColumn(SQLExprTableSource.java:271)
at com.alibaba.druid.sql.ast.statement.SQLExprTableSource.findTableSourceWithColumn(SQLExprTableSource.java:271)
at com.alibaba.druid.sql.ast.statement.SQLExprTableSource.findTableSourceWithColumn(SQLExprTableSource.java:271)
at com.alibaba.druid.sql.ast.statement.SQLExprTableSource.findTableSourceWithColumn(SQLExprTableSource.java:271)
at com.alibaba.druid.sql.ast.statement.SQLExprTableSource.findTableSourceWithColumn(SQLExprTableSource.java:271)
at com.alibaba.druid.sql.ast.statement.SQLExprTableSource.findTableSourceWithColumn(SQLExprTableSource.java:271)
at com.alibaba.druid.sql.ast.statement.SQLExprTableSource.findTableSourceWithColumn(SQLExprTableSource.java:271)
at com.alibaba.druid.sql.ast.statement.SQLExprTableSource.findTableSourceWithColumn(SQLExprTableSource.java:271)
at com.alibaba.druid.sql.ast.statement.SQLExprTableSource.findTableSourceWithColumn(SQLExprTableSource.java:271)
at com.alibaba.druid.sql.ast.statement.SQLExprTableSource.findTableSourceWithColumn(SQLExprTableSource.java:271)
at com.alibaba.druid.sql.ast.statement.SQLExprTableSource.findTableSourceWithColumn(SQLExprTableSource.java:271)
at com.alibaba.druid.sql.ast.statement.SQLExprTableSource.findTableSourceWithColumn(SQLExprTableSource.java:271)
...
```

**Comment by lizongbo** [comment]
最新版druid运行正常

```


    @Test
    public void test_del() throws Exception {
        String sql = "DELETE c, cm FROM `wp_88comments` c LEFT JOIN `wp_88commentmeta` cm ON c.comment_ID = cm.comment_id WHERE comment_approved = '0'";
        SQLStatementParser parser = new MySqlStatementParser(sql);
        SQLStatement statement = parser.parseStatement();
        MySqlSchemaStatVisitor visitor = new MySqlSchemaStatVisitor();
        statement.accept(visitor);
        Iterator<Column> it = visitor.getColumns().iterator();
        while (it.hasNext()) {
            Column c = it.next();
            System.out.println(c.getTable());
            System.out.println(c.getName());
        }
    }

```
