### ISSUE TITLE
druid占用CPU比较高

### ISSUE THREAD

**Issue by wangjia2016** [alibaba/druid#2870]
druid版本1.1.0

`"ContainerBackgroundProcessor[StandardEngine[Catalina]]" #28 daemon prio=5 os_prio=0 tid=0x00007f55f80b8000 nid=0x753b waiting on condition [0x00007f55d88c4000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1355)
	at java.lang.Thread.run(Thread.java:745)

"Druid-ConnectionPool-Destroy-30430326" #27 daemon prio=5 os_prio=0 tid=0x00007f55a56b4800 nid=0x7539 waiting on condition [0x00007f559a1f4000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)  
	at java.lang.Thread.sleep(Native Method)
	at com.alibaba.druid.pool.DruidDataSource$DestroyConnectionThread.run(DruidDataSource.java:2250)

"Druid-ConnectionPool-Create-30430326" #26 daemon prio=5 os_prio=0 tid=0x00007f55a56e1000 nid=0x7538 waiting on condition [0x00007f559a2f5000]
   java.lang.Thread.State: WAITING (parking)  
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006ccc69ba0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2157)

"Abandoned connection cleanup thread" #25 daemon prio=5 os_prio=0 tid=0x00007f55a55a1000 nid=0x7537 in Object.wait() [0x00007f559a5f6000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor) 
	at java.lang.Object.wait(Native Method)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x00000006ce458758> (a java.lang.ref.ReferenceQueue$Lock)
	at com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:43)
`
![image](https://user-images.githubusercontent.com/16084076/47196706-75379e80-d394-11e8-8b12-74b39cd3a5dc.png)

**Comment by dscxieyong** [comment]
请问这个问题最后有解决吗
