### ISSUE TITLE
Druid-ConnectionPool-Destroy 是bug吗？

### ISSUE THREAD

**Issue by qskm** [alibaba/druid#2888]
程序总是因为数据源的问题，导致web应用重启，貌似很多人都出现了这个问题，但查阅资料都没有很好的解决掉。

警告: The web application [start] appears to have started a thread named [Abandoned connection cleanup thread] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 java.lang.ref.ReferenceQueue.remove(Unknown Source)
 com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:64)
 java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
 java.lang.Thread.run(Unknown Source)
十一月 01, 2018 10:54:36 上午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
警告: The web application [start] appears to have started a thread named [Druid-ConnectionPool-Create-714918429] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(Unknown Source)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
 com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2480)
十一月 01, 2018 10:54:36 上午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
警告: The web application [start] appears to have started a thread named [Druid-ConnectionPool-Destroy-714918429] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Thread.sleep(Native Method)
 com.alibaba.druid.pool.DruidDataSource$DestroyConnectionThread.run(DruidDataSource.java:2576)
十一月 01, 2018 10:54:36 上午 org.apache.catalina.loader.WebappClassLoaderBase checkStateForResourceLoading
信息: Illegal access: this web application instance has been stopped already. Could not load []. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load []. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1295)
	at org.apache.catalina.loader.WebappClassLoaderBase.getResource(WebappClassLoaderBase.java:972)
	at com.mysql.jdbc.AbandonedConnectionCleanupThread.checkContextClassLoaders(AbandonedConnectionCleanupThread.java:90)
	at com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

邮件：123689178@qq.com

**Comment by wenshao** [comment]
参考配置看这个：
https://github.com/alibaba/druid/wiki/DruidDataSource%E9%85%8D%E7%BD%AE

**Comment by wenshao** [comment]
removeAbandoned仅用于调试，不建议在生产环境中使用

**Comment by xianwei** [comment]
> removeAbandoned仅用于调试，不建议在生产环境中使用

这个参数不能用的话，那么数据库连接闪断重连还有什么好的办法吗
