### ISSUE TITLE
parser 解析 desc 语句出错

### ISSUE THREAD

**Issue by zhanwh9** [alibaba/druid#2951]
当数据库中有名为 user 的表时，`desc user;` 命令在 mysql 中可以正常执行；
但是使用 parser 解析的时候报错：

```
Caused by: com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'user;', expect USER, actual USER pos 9, line 1, column 5, token USER
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:284)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:433)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:2754)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseExplain(MySqlStatementParser.java:1204)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseDescribe(MySqlStatementParser.java:1146)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseStatementListDialect(MySqlStatementParser.java:791)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:418)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:72)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:464)
```
应该是把作为表名的 user 当成 token了。
druid 版本：1.1.12

**Comment by aiic03** [comment]
@zhanwh9 
desc / describe / explain 在 mysql 看来是相同的语法。

https://dev.mysql.com/doc/refman/5.7/en/explain.html

com/alibaba/druid/sql/dialect/mysql/parser/MySqlStatementParser.java:1173

代码此处只做了对IDENTIFIER的表名识别，未对其他（如USER token）做识别处理。
可以在这里做一下加工，将com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser#parseExplain(com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlExplainStatement) 函数实现改为 :

```java
private MySqlExplainStatement parseExplain(MySqlExplainStatement explain) {

    if (lexer.token() == Token.HINT) {
        List<SQLCommentHint> hints = this.exprParser.parseHints();
        explain.setHints(hints);
    }
    // see https://dev.mysql.com/doc/refman/5.7/en/explain.html

    boolean table = false;
    if (lexer.token() == Token.IDENTIFIER) {
         String stringVal = lexer.stringVal();

         if (stringVal.equalsIgnoreCase(EXTENDED)
                 || stringVal.equalsIgnoreCase(PARTITIONS)) {
             explain.setType(stringVal);
             lexer.nextToken();
         } else if (stringVal.equalsIgnoreCase(FORMAT)) {
             explain.setType(stringVal);
             lexer.nextToken();
             accept(Token.EQ);

             String format = lexer.stringVal();
             explain.setFormat(format);
             accept(Token.IDENTIFIER);
         } else {
             explain.setTableName(exprParser.name());
             if (lexer.token() == Token.IDENTIFIER) {
                 explain.setColumnName(exprParser.name());
             } else if (lexer.token() == Token.LITERAL_CHARS) {
                 explain.setWild(exprParser.expr());
             }
             table = true;
         }
    } else if (!table && 
            (lexer.token() != Token.SELECT && lexer.token() != Token.INSERT
            && lexer.token() != Token.DELETE && lexer.token() != Token.UPDATE)) {
        explain.setTableName(exprParser.name());
        if (lexer.token() == Token.IDENTIFIER) {
            explain.setColumnName(exprParser.name());
        } else if (lexer.token() == Token.LITERAL_CHARS) {
            explain.setWild(exprParser.expr());
        }
        table = true;
    }

    if (lexer.token() == Token.FOR) {
        lexer.nextToken();
        acceptIdentifier(CONNECTION);
        explain.setConnectionId(exprParser.expr());
    } else if (!table) {
        explain.setStatement(this.parseStatement());
    }

    return explain;
}
```

测试代码：
```java
public void test_1() throws Exception {
    String sql = "desc user host";

    MySqlStatementParser parser = new MySqlStatementParser(sql);
    List<SQLStatement> statementList = parser.parseStatementList();
    SQLStatement stmt = statementList.get(0);

    Assert.assertEquals(1, statementList.size());

    MySqlSchemaStatVisitor visitor = new MySqlSchemaStatVisitor();
    stmt.accept(visitor);

    Assert.assertEquals(1, visitor.getTables().size());
    Assert.assertEquals(1, visitor.getColumns().size());
    Assert.assertEquals(0, visitor.getConditions().size());

    Assert.assertTrue(visitor.getColumns().contains(new Column("user", "host")));
}
```
