### ISSUE TITLE
oracle无法添加主键

### ISSUE THREAD

**Issue by taolive** [alibaba/druid#2965]
Caused by: java.sql.SQLException: sql injection violation, syntax error: error pos 51, line 1, column 44, token PRIMARY : ALTER TABLE TEST.state ADD CONSTRAINT PRIMARY PRIMARY KEY (id)

durid版本：1.1.9

**Comment by taolive** [comment]
使用了最新的druid 1.1.12 问题依旧

Caused by: java.sql.SQLException: sql injection violation, syntax error: error pos 51, line 1, column 44, token PRIMARY : ALTER TABLE REPORT_MGR.state ADD CONSTRAINT PRIMARY PRIMARY KEY (id)
	at com.alibaba.druid.wall.WallFilter.checkInternal(WallFilter.java:799) ~[druid-1.1.12.jar:1.1.12]
	at com.alibaba.druid.wall.WallFilter.check(WallFilter.java:781) ~[druid-1.1.12.jar:1.1.12]
	at com.alibaba.druid.wall.WallFilter.statement_execute(WallFilter.java:414) ~[druid-1.1.12.jar:1.1.12]
	at com.alibaba.druid.filter.FilterChainImpl.statement_execute(FilterChainImpl.java:2956) ~[druid-1.1.12.jar:1.1.12]
	at com.alibaba.druid.proxy.jdbc.StatementProxyImpl.execute(StatementProxyImpl.java:147) ~[druid-1.1.12.jar:1.1.12]
	at com.alibaba.druid.pool.DruidPooledStatement.execute(DruidPooledStatement.java:619) ~[druid-1.1.12.jar:1.1.12]
