### ISSUE TITLE
1.0.31 版本 生产环境偶尔报错： statement is closed

### ISSUE THREAD

**Issue by partys88** [alibaba/druid#2988]
`java.sql.SQLException: statement is closed
  at com.alibaba.druid.pool.DruidPooledStatement.checkOpen(DruidPooledStatement.java:86)
  at com.alibaba.druid.pool.DruidPooledStatement.getConnection(DruidPooledStatement.java:585)
  at com.dangdang.ddframe.rdb.sharding.executor.ExecutorEngine.executeInternal(ExecutorEngine.java:160)
  at com.dangdang.ddframe.rdb.sharding.executor.ExecutorEngine.access$000(ExecutorEngine.java:61)
  at com.dangdang.ddframe.rdb.sharding.executor.ExecutorEngine$1.call(ExecutorEngine.java:147)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)`

**Comment by wenshao** [comment]
应该是有场景把Statement关闭。没有更多信息无法诊断，要不你升级到最新版本1.1.12看是否能报更多错误信息。

**Comment by partys88** [comment]
> 应该是有场景把Statement关闭。没有更多信息无法诊断，要不你升级到最新版本1.1.12看是否能报更多错误信息。

我用的链接池 statement是链接池自动开启和关闭的吧 代码中没有主动关闭的地方。另外1.1.12版本有什么特质吗 错误信息会很详细吗
