### ISSUE TITLE
derby分页时druid的StatFilter报错

### ISSUE THREAD

**Issue by 269941633** [alibaba/druid#3020]
druid的版本是1.1.10，derby的版本是10.13.1.1。分页查询时使用offset #{startIndex} rows fetch next #{pageSize} rows only,有正确的结果返回，druid的sql监控中也有sql语句，但是控制台却有异常信息。
`2019-01-10 15:46:41.459 [http-nio-80-exec-7] ERROR c.a.druid.filter.stat.StatFilter - merge sql error, dbType com.alibaba.druid.pool.DruidDataSource, druid-1.1.10, sql : select * from sys_user offset ? rows fetch next ? rows only
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'user offset ? rows fetch next ? row', expect QUES, actual QUES pos 31, line 1, column 30, token QUES
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:284)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:426)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:72)
	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:94)
	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:77)
	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:50)
	at com.alibaba.druid.filter.stat.StatFilter.mergeSql(StatFilter.java:147)
	at com.alibaba.druid.filter.stat.StatFilter.createSqlStat(StatFilter.java:648)
	at com.alibaba.druid.filter.stat.StatFilter.statementPrepareAfter(StatFilter.java:311)`

**Comment by 269941633** [comment]
connectionProperties: druid.stat.mergeSql=true; 不进行mergeSql就不报错了
