### ISSUE TITLE
运行时偶发InterruptedException

### ISSUE THREAD

**Issue by saigu** [alibaba/druid#3053]
Caused by: java.sql.SQLException: interrupt
	at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1412) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1255) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1235) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1225) ~[druid-1.1.10.jar:1.1.10]
	at com.taobao.tddl.atom.jdbc.TDataSourceWrapper.getConnectionByTargetDataSource(TDataSourceWrapper.java:322) ~[tddl-atom-5.2.1.jar:?]
	... 140 more
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1220) ~[?:1.8.0_122-ea]
	at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:335) ~[?:1.8.0_122-ea]
	at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1409) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1255) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1235) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1225) ~[druid-1.1.10.jar:1.1.10]
	at com.taobao.tddl.atom.jdbc.TDataSourceWrapper.getConnectionByTargetDataSource(TDataSourceWrapper.java:322) ~[tddl-atom-5.2.1.jar:?]
	... 140 more

可能会是什么原因导致的？

**Comment by greenHard** [comment]
我们线上也遇到了相同的问题。定时任务跑个几天就会出现一次错误。错误原因如下:
我们使用的版本是: 1.0.2

2019-06-03 10:00:00 [com.cupdata.pointpay.resource.service.handler.RefreshCacheHandler#execute]-[32]-[Thread-4696] org.springframework.jdbc.UncategorizedSQLException: 
### Error querying database.  Cause: java.sql.SQLException: interrupt
### The error may exist in class path resource [mappers/SysConfigMapper.xml]
### The error may involve com.cupdata.pointpay.common.dao.SysConfigMapper.selectAll
### The error occurred while executing a query
### SQL: select * from UPP_SYS_CONFIG     WHERE TRUE
### Cause: java.sql.SQLException: interrupt
; uncategorized SQLException for SQL []; SQL state [null]; error code [0]; interrupt; nested exception is java.sql.SQLException: interrupt
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:90)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:82)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:82)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:75)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:447)
	at com.sun.proxy.$Proxy177.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:231)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:137)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:75)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy267.selectAll(Unknown Source)
	at com.cupdata.pointpay.common.mybatis.service.impl.BaseServiceImpl.selectAll(BaseServiceImpl.java:76)
	at sun.reflect.GeneratedMethodAccessor809.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy268.selectAll(Unknown Source)
	at com.cupdata.pointpay.resource.cache.CacheManager.refreshAllCache(CacheManager.java:122)
	at com.cupdata.pointpay.resource.service.handler.RefreshCacheHandler.execute(RefreshCacheHandler.java:28)
	at com.xxl.job.core.thread.JobThread.run(JobThread.java:152)
Caused by: java.sql.SQLException: interrupt
	at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1006)
	at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:898)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4544)
	at com.alibaba.druid.filter.stat.StatFilter.dataSource_getConnection(StatFilter.java:661)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4540)
	at com.alibaba.druid.filter.FilterAdapter.dataSource_getConnection(FilterAdapter.java:2724)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4540)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:880)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:872)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:97)
	at io.shardingsphere.core.jdbc.adapter.AbstractConnectionAdapter.getConnection(AbstractConnectionAdapter.java:65)
	at io.shardingsphere.core.jdbc.core.statement.MasterSlavePreparedStatement.(MasterSlavePreparedStatement.java:62)
	at io.shardingsphere.core.jdbc.core.statement.MasterSlavePreparedStatement.(MasterSlavePreparedStatement.java:49)
	at io.shardingsphere.core.jdbc.core.connection.MasterSlaveConnection.prepareStatement(MasterSlaveConnection.java:72)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.instantiateStatement(PreparedStatementHandler.java:87)
	at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:88)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.prepare(RoutingStatementHandler.java:59)
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:85)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
	at sun.reflect.GeneratedMethodAccessor406.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
	at com.cupdata.pointpay.resource.interceptor.MybatisInterceptor.intercept(MybatisInterceptor.java:60)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy360.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at sun.reflect.GeneratedMethodAccessor420.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:434)
	... 20 more
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1220)
	at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:335)
	at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1003)
	... 55 more

**Comment by jiangwangfa** [comment]
有解决办法吗？我们项目也遇到这个问题，增加连接数也不行

**Comment by zxfendoubuzhi** [comment]
> 有解决办法吗？我们项目也遇到这个问题，增加连接数也不行

您好有解决么?

**Comment by chenyanwork** [comment]
我也遇到了这个问题，偶尔报这个，我这是多数据源

**Comment by luodl1991** [comment]
> 我们线上也遇到了相同的问题。定时任务跑个几天就会出现一次错误。错误原因如下：
> 我们使用的版本是：1.0.2
> 
> 2019-06-03 10:00:00 [com.cupdata.pointpay.resource.service.handler.RefreshCacheHandler＃execute]-[32]-[Thread-4696] org.springframework.jdbc.UncategorizedSQLException：
> 
> ### 查询数据库时出错。原因：java.sql.SQLException：中断
> ### 该错误可能存在于类路径资源[mappers / SysConfigMapper.xml]中
> ### 该错误可能涉及com.cupdata.pointpay.common.dao.SysConfigMapper.selectAll
> ### 执行查询时发生错误
> ### SQL：从UPP_SYS_CONFIG选择*，其中TRUE
> ### 原因：java.sql.SQLException：中断
> ; 未分类的SQLException for SQL []; SQL状态[null]; 错误代码[0]；打断; 嵌套异常是java.sql.SQLException：
> 在org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate（AbstractFallbackSQLExceptionTranslator.java:82）
> 处的org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate（AbstractFallbackSQLExceptionTranslator.java:82）
> 处的org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate（AbstractFallbackSQLExceptionTranslator.java:90）中断
> org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible（MyBatisExceptionTranslator.java:75）
> 上的.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate（AbstractFallbackSQLExceptionTranslator.java:82）在org.mybatis.spring.SqlSessionTemplate $ SqlSessionInterceptor.invoke ：447）
> 在com.sun.proxy。$ Proxy177.selectList（未知源）
> 在org.mybatis.spring.SqlSessionTemplate.selectList（SqlSessionTemplate.java:231）
> 在org.apache.ibatis.binding.MapperMethod.executeForMany（MapperMethod.java:137） ）
> 于org.apache.ibatis.binding.MapperProxy.invoke（MapperProxy.java:59）
> 于org.apache.ibatis.binding.MapperMethod.execute（MapperMethod.java:75）
> 于com.sun.proxy。$ Proxy267.selectAll （未知来源）
> 在com.cupdata.pointpay.common.mybatis.service.impl.BaseServiceImpl.selectAll（BaseServiceImpl.java:76）
> 在sun.reflect.GeneratedMethodAccessor809.invoke（未知来源）
> 在sun.reflect.DelegatingMethodAccessorImpl.invoke（ DelegatingMethodAccessorImpl.java:43），
> 位于java.lang.reflect.Method.invoke（Method.java:498）
> 在org.springframework.aop.framework.ReflectedMethodIn上org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection（AopUtils.java:333）
> 在org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint（ReflectiveMethodInvocation.java:190）
> 在org.springframework.aop.framework.ReflectedMethodIn （ReflectiveMethodInvocation.java:157）
> 在org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke（ExposeInvocationInterceptor.java:92）
> 在org.springframework.aop.framework.ReflectiveMethodInvocation.proceed（ReflectiveMethodInvocation.java:179）
> 在org.springframework。 aop.framework.JdkDynamicAopProxy.invoke（JdkDynamicAopProxy.java:213）
> 在com.sun.proxy。$ Proxy268.selectAll（来源不明）
> 在com.cupdata.pointpay.repay.resource.service.handler.RefreshCacheHandler.execute（
> RefreshCacheHandler.java:28）
> 在com.cupdata.pointpay.resource.service.handler.com.xxl.job在com.cupdata.pointpay.resource.cache.CacheManager.refreshAllCache（CacheManager.java:122）.core.thread.JobThread.run（JobThread.java:152）
> 原因：java.sql.SQLException：
> com.alibaba.druid.pool.DruidDataSource.getConnectionInternal（DruidDataSource.java:1006）
> 处的com.alibaba.druid处的中断com.alibaba.druid.filter.FilterChainImpl.dataSource_connect（
> FilterChainImpl.java:4544）
> 上的.pool.DruidDataSource.getConnectionDirect（DruidDataSource.java:898 ）com.alibaba.druid.filter.stat.StatFilter.dataSource_getConnection（StatFilter.java ：661）
> 在com.alibaba.druid.filter.FilterChainImpl.dataSource_connect（FilterChainImpl.java:4540）
> 在com.alibaba.druid.filter.FilterAdapter.dataSource_getConnection（FilterAdapter.java:2724）
> 在com.alibaba.druid.filter.FilterChainImpl.dataSource （FilterChainImpl.java:4540）
> 在com.alibaba.druid.pool.DruidDataSource.getConnection（DruidDataSource.java:880）
> 在com.alibaba.druid.pool.DruidDataSource.getConnection（DruidDataSource.java:872）
> 在com.alibaba。
> 位于io.shardingsphere.core.jdbc.adapter.AbstractConnectionAdapter.getConnection（AbstractConnectionAdapter.java:65）的druid.pool.DruidDataSource.getConnection（DruidDataSource.java:97 ）
> 位于io.shardingsphere.core.jdbc.core.statement.MasterSlavePreparedStatement。 （MasterSlavePreparedStatement.java:62）
> 在io.shardingsphere.core.jdbc.core.connection.MasterSlaveConnection.prepareStatement（MasterSlaveConnection.java:72）
> 上的io.shardingsphere.core.jdbc.core.connection.MasterSlaveConnection.prepareStatement（MasterSlaveConnection.java:72）
> 上的io.shardingsphere.core.jdbc.core.statement.MasterSlavePreparedStatement 。
> org.apache.ibatis.executor.statement.BaseStatementHandler.prepare（BaseStatementHandler.java:88）上的ibatis.executor.statement.PreparedStatementHandler.instantiateStatement（PreparedStatementHandler.java:87）在org.apache.ibatis.executor.statement.RoutingStatementHandler
> 处。
> 在org.apache.ibatis.executor.SimpleExecutor.prepareStatement（SimpleExecutor.java:85）
> 处的prepare（RoutingStatementHandler.java:59）在org.apache.ibatis.executor.SimpleExecutor.doQuery（SimpleExecutor.java:62）处
> 在org.apache.ibatis.executor.BaseExecutor.query（BaseExecutor.java:156）
> 在org.apache.ibatis.executor.BaseExecutor.query（BaseExecutor.java:156）
> 在org.apache.ibatis.executor.CachingExecutor.query （CachingExecutor.java:109）
> 在org.apache.ibatis.executor.CachingExecutor.query（CachingExecutor.java:83）
> 在sun.reflect.GeneratedMethodAccessor406.invoke（未知源）
> 在sun.reflect.DelegatingMethodAccessorImpl.invoke（DelegatingMethodAccessorImpl.java ：43）
> ，
> 位于org.apache.ibatis.plugin.Invocation.proceed（Invocation.java:49），
> 位于com.cupdata.pointpay.resource.interceptor的java.lang.reflect.Method.invoke（Method.java:498）。 MybatisInterceptor.intercept（MybatisInterceptor.java:60）
> 在org.apache.ibatis.session.defaults.DefaultSqlSession.selectList（DefaultSqlSession）
> 的com.sun.proxy。$ Proxy360.query（未知源）
> 的org.apache.ibatis.plugin.Plugin.invoke（Plugin.java:61）.java：148），
> 位于org.apache.ibatis.session.defaults.DefaultSqlSession.selectList（DefaultSqlSession.java:141），
> 位于sun.reflect.GeneratedMethodAccessor420.invoke（未知源），
> 位于sun.reflect.DelegatingMethodAccessorImpl.invoke（DelegatingMethodAccessorImpl.java ：43）
> 位于
> org.mybatis.spring.SqlSessionTemplate $ SqlSessionInterceptor.invoke（SqlSessionTemplate.java:434 ）处的java.lang.reflect.Method.invoke（Method.java:498 ）
> ... 20多
> 原因由：java.lang .InterruptedException
> 在java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptible（AbstractQueuedSynchronizer.java:1220）
> 在java.util.concurrent.locks.ReentrantLock.lockInterruptible（ReentrantLock.java:335）
> 在com.alibaba.druid.pool.DruidDataSource.getConnectionInternal （DruidDataSource.java:1003）
> ...还有55个



> 我们线上也遇到了相同的问题。定时任务跑个几天就会出现一次错误。错误原因如下:
> 我们使用的版本是: 1.0.2
> 
> 2019-06-03 10:00:00 [com.cupdata.pointpay.resource.service.handler.RefreshCacheHandler#execute]-[32]-[Thread-4696] org.springframework.jdbc.UncategorizedSQLException:
> 
> ### Error querying database. Cause: java.sql.SQLException: interrupt
> ### The error may exist in class path resource [mappers/SysConfigMapper.xml]
> ### The error may involve com.cupdata.pointpay.common.dao.SysConfigMapper.selectAll
> ### The error occurred while executing a query
> ### SQL: select * from UPP_SYS_CONFIG WHERE TRUE
> ### Cause: java.sql.SQLException: interrupt
> ; uncategorized SQLException for SQL []; SQL state [null]; error code [0]; interrupt; nested exception is java.sql.SQLException: interrupt
> at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:90)
> at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:82)
> at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:82)
> at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:75)
> at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:447)
> at com.sun.proxy.$Proxy177.selectList(Unknown Source)
> at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:231)
> at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:137)
> at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:75)
> at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
> at com.sun.proxy.$Proxy267.selectAll(Unknown Source)
> at com.cupdata.pointpay.common.mybatis.service.impl.BaseServiceImpl.selectAll(BaseServiceImpl.java:76)
> at sun.reflect.GeneratedMethodAccessor809.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
> at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
> at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
> at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
> at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
> at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
> at com.sun.proxy.$Proxy268.selectAll(Unknown Source)
> at com.cupdata.pointpay.resource.cache.CacheManager.refreshAllCache(CacheManager.java:122)
> at com.cupdata.pointpay.resource.service.handler.RefreshCacheHandler.execute(RefreshCacheHandler.java:28)
> at com.xxl.job.core.thread.JobThread.run(JobThread.java:152)
> Caused by: java.sql.SQLException: interrupt
> at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1006)
> at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:898)
> at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4544)
> at com.alibaba.druid.filter.stat.StatFilter.dataSource_getConnection(StatFilter.java:661)
> at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4540)
> at com.alibaba.druid.filter.FilterAdapter.dataSource_getConnection(FilterAdapter.java:2724)
> at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4540)
> at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:880)
> at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:872)
> at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:97)
> at io.shardingsphere.core.jdbc.adapter.AbstractConnectionAdapter.getConnection(AbstractConnectionAdapter.java:65)
> at io.shardingsphere.core.jdbc.core.statement.MasterSlavePreparedStatement.(MasterSlavePreparedStatement.java:62)
> at io.shardingsphere.core.jdbc.core.statement.MasterSlavePreparedStatement.(MasterSlavePreparedStatement.java:49)
> at io.shardingsphere.core.jdbc.core.connection.MasterSlaveConnection.prepareStatement(MasterSlaveConnection.java:72)
> at org.apache.ibatis.executor.statement.PreparedStatementHandler.instantiateStatement(PreparedStatementHandler.java:87)
> at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:88)
> at org.apache.ibatis.executor.statement.RoutingStatementHandler.prepare(RoutingStatementHandler.java:59)
> at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:85)
> at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62)
> at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
> at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
> at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
> at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
> at sun.reflect.GeneratedMethodAccessor406.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
> at com.cupdata.pointpay.resource.interceptor.MybatisInterceptor.intercept(MybatisInterceptor.java:60)
> at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
> at com.sun.proxy.$Proxy360.query(Unknown Source)
> at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
> at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
> at sun.reflect.GeneratedMethodAccessor420.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:434)
> ... 20 more
> Caused by: java.lang.InterruptedException
> at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1220)
> at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:335)
> at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1003)
> ... 55 more

请问这个问题解决了吗？啥原因导致的额

**Comment by iamcyw** [comment]
我们也在定时任务中遇到了同样的问题

**Comment by wangshengji** [comment]
我们也遇到这个问题了，俩数据源，有什么好的解决办法吗？（ 1.1.24版本）。另外就是这个问题在19年就提出了，马上22年了。。。

**Comment by book-yao** [comment]
Hi，I have received your mail!

**Comment by XinyuSimov** [comment]
连接跑在localhost的docker里面的mysql都会跳InterruptedException 开发环境都死的不能再死了……

**Comment by ChengHoHang** [comment]
长时间的调度任务偶现这个问题，目前有解决方案吗..

**Comment by book-yao** [comment]
Hi，I have received your mail!

**Comment by kslex** [comment]
Thread.interrupt()并非Druid本身调用的，原因一般在外部，例如上面用的xxl-job，可能配置了超时时间，超时之后被xxl-job中断了线程

**Comment by book-yao** [comment]
Hi，I have received your mail!
