### ISSUE TITLE
高并发情况下初始化数据源报错--版本1.0.17

### ISSUE THREAD

**Issue by Percy0601** [alibaba/druid#3078]
https://github.com/alibaba/druid/blob/2245a6e451dd9233eba0853dbc3d28eddfc9bf0f/src/main/java/com/alibaba/druid/pool/DruidDataSource.java#L766

java.sql.SQLExceptionat com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:680)at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:951)at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:947)at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:102)
--

at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1302)
at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:668)
... 63 more

版本1.0.17

**Comment by wenshao** [comment]
升级到1.1.16版本试试看
