### ISSUE TITLE
格式化hive create语句，当库名为default时报错

### ISSUE THREAD

**Issue by hanbingde** [alibaba/druid#3090]
```java
String dbType = JdbcConstants.HIVE;
String sql = "CREATE TABLE IF NOT EXISTS default.create_test (id int COMMENT '学号', name string COMMENT '姓名');";
String sqlBeauty = SQLUtils.format(sql , dbType);
System.out.println(sqlBeauty);
```

报错：
```
[2019-02-22 17:18:36,783] WARN    
     format error
com.alibaba.druid.sql.parser.ParserException: error pos 34, line 1, column 27, token DEFAULT
	at com.alibaba.druid.sql.parser.SQLExprParser.name(SQLExprParser.java:1370)
	at com.alibaba.druid.sql.dialect.hive.parser.HiveCreateTableParser.parseCreateTable(HiveCreateTableParser.java:71)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseCreate(SQLStatementParser.java:2028)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:161)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:72)
	at com.alibaba.druid.sql.SQLUtils.format(SQLUtils.java:255)
	at com.alibaba.druid.sql.SQLUtils.format(SQLUtils.java:241)
	at com.inspur.tax.sjjggl.common.util.SqlParserUtil.main(SqlParserUtil.java:75)
CREATE TABLE IF NOT EXISTS default.create_test (id int COMMENT '学号', name string COMMENT '姓名');

Process finished with exit code 0
```

其他库名格式化正常

**Comment by wenshao** [comment]
问题已修复，请用新版本 https://github.com/alibaba/druid/releases/tag/1.1.14
