### ISSUE TITLE
druid-1.1.13-flyway-5.2.4-postgres对“set role” 解析报错

### ISSUE THREAD

**Issue by xxfad** [alibaba/druid#3091]
druid 1.1.13
flyway 5.2.4
postgres 9.6

~~~java
2019-02-22 17:43:18.031 ERROR 13456 --- [           main] c.a.d.f.s.StatFilter                     : merge sql error, dbType postgresql, druid-1.1.13, sql : SET ROLE 'postgres'

com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'ROLE 'postgres'', expect LITERAL_CHARS, actual LITERAL_CHARS pos 19, line 1, column 9, token LITERAL_CHARS postgres
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:288) ~[druid-1.1.13.jar:1.1.13]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:433) ~[druid-1.1.13.jar:1.1.13]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:72) ~[druid-1.1.13.jar:1.1.13]
	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:94) ~[druid-1.1.13.jar:1.1.13]
	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:77) ~[druid-1.1.13.jar:1.1.13]
	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:50) ~[druid-1.1.13.jar:1.1.13]
	at com.alibaba.druid.filter.stat.StatFilter.mergeSql(StatFilter.java:147) ~[druid-1.1.13.jar:1.1.13]
	at com.alibaba.druid.filter.stat.StatFilter.createSqlStat(StatFilter.java:648) ~[druid-1.1.13.jar:1.1.13]
	at com.alibaba.druid.filter.stat.StatFilter.statementPrepareAfter(StatFilter.java:311) ~[druid-1.1.13.jar:1.1.13]
	at com.alibaba.druid.filter.FilterEventAdapter.connection_prepareStatement(FilterEventAdapter.java:124) ~[druid-1.1.13.jar:1.1.13]
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:568) ~[druid-1.1.13.jar:1.1.13]
~~~

**Comment by wenshao** [comment]
问题已修复，请用新版本 https://github.com/alibaba/druid/releases/tag/1.1.14
