### ISSUE TITLE
druid1.1.0整合atomikos报错

### ISSUE THREAD

**Issue by JsonBiao** [alibaba/druid#3104]
MySqlUtils类createXAConnection方法的
 **boolean pinGlobTx = (Boolean)getPinGlobalTxToPhysicalConnectionMethod.invoke(physicalConn);**
这行代码报错，physicalConn变量找不到getPinGlobalTxToPhysicalConnection方法的原因。
getPinGlobalTxToPhysicalConnectionMethod变量初始化是
connectionClass = Class.forName("com.mysql.jdbc.Connection");
                    getPinGlobalTxToPhysicalConnectionMethod = connectionClass.getMethod("getPinGlobalTxToPhysicalConnection");

**Comment by wenshao** [comment]
mysql是什么驱动版本？druid又是什么版本呢？

**Comment by JsonBiao** [comment]
mysql驱动版本5.1.45，druid版本1.1.0

**Comment by aboutdever** [comment]
2020-04-28 16:52:44.983  WARN 15756 --- [  restartedMain] c.a.jdbc.AtomikosXAConnectionFactory     : XAConnectionFactory: failed to create pooled connection - DBMS down or unreachable?

java.sql.SQLFeatureNotSupportedException: null
	at com.alibaba.druid.util.MySqlUtils.createXAConnection(MySqlUtils.java:185) ~[druid-1.1.22.jar:1.1.22]
	at com.alibaba.druid.pool.xa.DruidXADataSource.createPhysicalXAConnection(DruidXADataSource.java:73) ~[druid-1.1.22.jar:1.1.22]
	at com.alibaba.druid.pool.xa.DruidXADataSource.getXAConnection(DruidXADataSource.java:49) ~[druid-1.1.22.jar:1.1.22]
	at com.atomikos.jdbc.AtomikosXAConnectionFactory.createPooledConnection(AtomikosXAConnectionFactory.java:43) ~[transactions-jdbc-4.0.6.jar:na]
	at com.atomikos.datasource.pool.ConnectionPool.createPooledConnection(ConnectionPool.java:98) [transactions-jta-4.0.6.jar:na]

mysql 8.0 druid 1.1.22
