### ISSUE TITLE
v1.14 使用XA事务报null

### ISSUE THREAD

**Issue by minteliu** [alibaba/druid#3116]
mysql 驱动包版本为8.015 使用XA事务时，找不到com.mysql.cj.conf.PropertySet.getBooleanReadableProperty(String) 方法

**Comment by empireghost** [comment]
java.lang.NoSuchMethodException: com.mysql.cj.conf.PropertySet.getBooleanReadableProperty(java.lang.String)
	at java.lang.Class.getMethod(Class.java:1786)
	at com.alibaba.druid.util.MySqlUtils.createXAConnection(MySqlUtils.java:120)

**Comment by RunJavaCode** [comment]
Druid数据源在创建mysql的XA连接时，产生的错误。
具体的源码在 druid的 util 包中的MySqlUtils 类中的 createXAConnection 方法。

将 mysql 驱动包版本切换为8.0.11，在该版本中，getBooleanReadableProperty(String)方法是还存在的。
