### ISSUE TITLE
连接oracle一段时间后提示关闭的连接

### ISSUE THREAD

**Issue by zhanghongke123** [alibaba/druid#3131]
java.sql.SQLRecoverableException: 关闭的连接
	at oracle.jdbc.driver.PhysicalConnection.needLine(PhysicalConnection.java:5416)
	at oracle.jdbc.driver.OracleStatement.closeOrCache(OracleStatement.java:1585)
	at oracle.jdbc.driver.OracleStatement.close(OracleStatement.java:1570)
	at oracle.jdbc.driver.OracleStatementWrapper.close(OracleStatementWrapper.java:94)
	at com.alibaba.druid.util.JdbcUtils.close(JdbcUtils.java:84)
	at com.alibaba.druid.pool.vendor.OracleValidConnectionChecker.isValidConnection(OracleValidConnectionChecker.java:88)
	at com.alibaba.druid.pool.DruidAbstractDataSource.testConnectionInternal(DruidAbstractDataSource.java:1400)
	at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1299)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5007)
	at com.alibaba.druid.filter.stat.StatFilter.dataSource_getConnection(StatFilter.java:680)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5003)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1233)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1225)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:90)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:157)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:115)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:78)
	at org.mybatis.spring.transaction.SpringManagedTransaction.openConnection(SpringManagedTransaction.java:82)
	at org.mybatis.spring.transaction.SpringManagedTransaction.getConnection(SpringManagedTransaction.java:68)
	at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:338)
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:84)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:326)

**Comment by liuqingshuai** [comment]
这个问题我也遇到了，有没有解决啊？兄弟

**Comment by liuqingshuai** [comment]
我的问题解决了，是我拿 session的方式有问题，更druid没有关系

**Comment by lurenj** [comment]
你好，问一下，这个问题你解决了吗？

**Comment by liuqingshuai** [comment]
我重新搭一个就行了。原来的还是不行，换了个持久层框架我换成了mybatis，用hibernate的时候一直都不行。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lurenj"<notifications@github.com&gt;; 
发送时间: 2020年3月17日(星期二) 中午11:05
收件人: "alibaba/druid"<druid@noreply.github.com&gt;; 
抄送: "清明雨上"<849797290@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [alibaba/druid] 连接oracle一段时间后提示关闭的连接 (#3131)





 
你好，问一下，这个问题你解决了吗？

**Comment by lurenj** [comment]
我就是用的mybatis,出现的问题。但我其他相同框架的项目都没有问题，就是这个项目，一直出现。不过，我有点怀疑是因为网络波动的问题。现在还在继续测试了。。。



在 2020-03-17 11:23:09，"liuqingshuai" <notifications@github.com> 写道：

我重新搭一个就行了。原来的还是不行，换了个持久层框架我换成了mybatis，用hibernate的时候一直都不行。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lurenj"<notifications@github.com&gt;;
发送时间: 2020年3月17日(星期二) 中午11:05
收件人: "alibaba/druid"<druid@noreply.github.com&gt;;
抄送: "清明雨上"<849797290@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;;
主题: Re: [alibaba/druid] 连接oracle一段时间后提示关闭的连接 (#3131)






你好，问一下，这个问题你解决了吗？
