### ISSUE TITLE
关于java.sql.SQLRecoverableException: Closed Connection的疑问？

### ISSUE THREAD

**Issue by zhugw** [alibaba/druid#3195]
查看线上日志 发现偶尔会有如下的错误日志

```
java.sql.SQLRecoverableException: Closed Connection
        at oracle.jdbc.driver.PhysicalConnection.needLine(PhysicalConnection.java:3247) ~[ojdbc8-18.3.0.0.jar!/:12.2.0.1.0]
        at oracle.jdbc.driver.OracleStatement.closeOrCache(OracleStatement.java:1392) ~[ojdbc8-18.3.0.0.jar!/:12.2.0.1.0]
        at oracle.jdbc.driver.OracleStatement.close(OracleStatement.java:1375) ~[ojdbc8-18.3.0.0.jar!/:12.2.0.1.0]
        at oracle.jdbc.driver.OracleStatementWrapper.close(OracleStatementWrapper.java:119) ~[ojdbc8-18.3.0.0.jar!/:12.2.0.1.0]
        at com.alibaba.druid.util.JdbcUtils.close(JdbcUtils.java:84) ~[druid-1.1.10.jar!/:1.1.10]
        at com.alibaba.druid.pool.vendor.OracleValidConnectionChecker.isValidConnection(OracleValidConnectionChecker.java:88) [druid-1.1.10.jar!/:1.1.10]
        at com.alibaba.druid.pool.DruidAbstractDataSource.testConnectionInternal(DruidAbstractDataSource.java:1400) [druid-1.1.10.jar!/:1.1.10]
        at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1299) [druid-1.1.10.jar!/:1.1.10]
        at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5007) [druid-1.1.10.jar!/:1.1.10]
        at com.alibaba.druid.filter.stat.StatFilter.dataSource_getConnection(StatFilter.java:680) [druid-1.1.10.jar!/:1.1.10]
        at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5003) [druid-1.1.10.jar!/:1.1.10]
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1233) [druid-1.1.10.jar!/:1.1.10]
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1225) [druid-1.1.10.jar!/:1.1.10]
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:90) [druid-1.1.10.jar!/:1.1.10]
        at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:157) [spring-jdbc-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:115) [spring-jdbc-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:78) [spring-jdbc-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.mybatis.spring.transaction.SpringManagedTransaction.openConnection(SpringManagedTransaction.java:82) [mybatis-spring-2.0.0.jar!/:2.0.0]
        at org.mybatis.spring.transaction.SpringManagedTransaction.getConnection(SpringManagedTransaction.java:68) [mybatis-spring-2.0.0.jar!/:2.0.0]
        at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:336) [mybatis-3.5.0.jar!/:3.5.0]
        at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:85) [mybatis-3.5.0.jar!/:3.5.0]
        at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62) [mybatis-3.5.0.jar!/:3.5.0]
        at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324) [mybatis-3.5.0.jar!/:3.5.0]
        at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156) [mybatis-3.5.0.jar!/:3.5.0]
        at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109) [mybatis-3.5.0.jar!/:3.5.0]
```

跟踪了下代码 发现应该是执行到`oracle.jdbc.driver.OracleStatement#closeOrCache`的时候 
不巧此时connection被关闭了（如被销毁线程给销毁了）导致 报了如上的错误 于是在执行到此处的时候 人工显式关闭connection 如下所示
<img width="733" alt="Screen Shot 2019-04-20 at 22 00 23" src="https://user-images.githubusercontent.com/4953871/56458543-bf88ef00-63ba-11e9-98ce-74267ee96b1c.png">

确实制造了和线上的同样的错误 **但是紧接着会有更多额外的错误日志** 如下所示
```
2019-04-20 22:02:48.595 ERROR 26660 --- [nio-8081-exec-6] com.alibaba.druid.pool.DruidDataSource   : recyle error

java.sql.SQLRecoverableException: Closed Connection
	at oracle.jdbc.driver.PhysicalConnection.clearWarnings(PhysicalConnection.java:2573) ~[ojdbc8-18.3.0.0.jar:12.2.0.1.0]
	at com.alibaba.druid.filter.FilterChainImpl.connection_clearWarnings(FilterChainImpl.java:174) [druid-1.1.10.jar:1.1.10]
...


2019-04-20 22:03:34.134 ERROR 26660 --- [nio-8081-exec-6] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.dao.RecoverableDataAccessException: 
### Error querying database.  Cause: java.sql.SQLRecoverableException: Closed Connection
### The error may exist in file [/Users/zhugw/workspace/target/classes/mybatis/OpportunityMapper.xml]
### The error may involve com.opportunity.mappers.OpportunityMapper.getAllCountry
### The error occurred while executing a query
### Cause: java.sql.SQLRecoverableException: Closed Connection
; Closed Connection; nested exception is java.sql.SQLRecoverableException: Closed Connection] with root cause

java.sql.SQLRecoverableException: Closed Connection
	at oracle.jdbc.driver.PhysicalConnection.getAutoCommit(PhysicalConnection.java:1828) ~[ojdbc8-18.3.0.0.jar:12.2.0.1.0]
	at com.alibaba.druid.filter.FilterChainImpl.connection_getAutoCommit(FilterChainImpl.java:349) ~[druid-1.1.10.jar:1.1.10]
```
而线上并没有这些额外的错误日志 **问线上的错误日志到底是个什么情况呢**？

**Comment by 786951355** [comment]
遇到同样的问题，在阿里云上，隔几天会有这样的异常抛出。

**Comment by lishaoning** [comment]
我也遇到了，正百思不得其解

**Comment by breakenknife** [comment]
@zhugw 你好,请问你用的哪个druid版本呢? 我用1.1.14没有问题,1.1.18就有这个异常,概率很低, 后来回滚了.
https://github.com/alibaba/druid/issues/3355

**Comment by zhugw** [comment]
@breakenknife 
从日志中可以知道是1.1.10
```
        at com.alibaba.druid.util.JdbcUtils.close(JdbcUtils.java:84) ~[druid-1.1.10.jar!/:1.1.10]
```
另外刚刚线上部署了一个应用 发现存在同样的问题
```
        at com.alibaba.druid.util.JdbcUtils.close(JdbcUtils.java:100) ~[druid-1.1.17.jar!/:1.1.17]
```

**Comment by breakenknife** [comment]
@zhugw 有没试过关闭pscache ? 我以前关了就好了.

**Comment by zhugw** [comment]
@breakenknife 
1.1.10对应的应用并未配置pscache
```
poolPreparedStatements
maxPoolPreparedStatementPerConnectionSize
```

**Comment by breakenknife** [comment]
那只能等群主解决了, @wenshao ,我看1.1.14到1.1.18确实改了很多oracle有关的代码,回滚就好了,要不你也试试1.1.14?

**Comment by zhugw** [comment]
**原因：**

发现连接大概空闲5分钟左右 服务端会发一个RST包给客户端 此时连接就中断了（Oracle默认空闲超时机制？）
![image](https://user-images.githubusercontent.com/4953871/62833157-8ed00c80-bc6c-11e9-8b34-828180262871.png)

```
java    77423 zhugw  165u  IPv6 0x6f7b8bf50d1a967      0t0  TCP 172.30.60.66:60141->10.10.201.98:ncube-lm (ESTABLISHED)

==>

java    77423 zhugw  165u  IPv6 0x6f7b8bf50d1a967      0t0  TCP [::172.30.60.66]:60141->[::10.10.201.98]:ncube-lm (CLOSED)
```
于是关闭一个已经关闭了的连接 就会报上述错误

**解决：**
设置keepAlive=true 则会每隔`minEvictableIdleTimeMillis`发送心跳保活
但是奇怪的是 一段时间后 仍有2个连接关闭了（minIdle=5）不知为什么没能保活？
```
java    84132 zhugw  172u  IPv6 0x6f7b8bf48492767      0t0  TCP 172.30.60.66:60263->10.10.201.98:ncube-lm (ESTABLISHED)
java    84132 zhugw  175u  IPv6 0x6f7b8bf48490aa7      0t0  TCP 172.30.60.66:60264->10.10.201.98:ncube-lm (ESTABLISHED)
java    84132 zhugw  176u  IPv6 0x6f7b8bf484932e7      0t0  TCP 172.30.60.66:60265->10.10.201.98:ncube-lm (ESTABLISHED)
java    84132 zhugw  177u  IPv6 0x6f7b8bf48491067      0t0  TCP [::172.30.60.66]:60266->[::10.10.201.98]:ncube-lm (CLOSED)
java    84132 zhugw  178u  IPv6 0x6f7b8bf48491be7      0t0  TCP [::172.30.60.66]:60267->[::10.10.201.98]:ncube-lm (CLOSED)
```

**补充**
受到了下面文章的启发
https://tech.youzan.com/shu-ju-ku-lian-jie-chi-pei-zhi/

**Comment by 15168326318** [comment]
@zhugw 原因：

发现连接大概空闲5分钟左右 服务端会发一个RST包给客户端 此时连接就中断了（Oracle默认空闲超时机制？）


可是你的问题是在isValidConnection方法了，已经查询正常，在关闭OracleStatement的时候发现连接关闭了。这个过程是很快的啊，不可能有几分钟。

**Comment by zhengboning** [comment]
保或策略失效，引起连接池泄露，继而引发一系列异常，如：应用假死，锁表，nio异常，连接关闭，抓包时出现有tcp只有握手没有挥手动作。
打开druid看下KeepAlive是否为true，KeepAlive检测次数有没有值，逻辑打开数和关闭数是否对等，起码不能差别太大。
升级**1.1.24**，配置文件**<property name="keepAlive" value="true"/>**。
