### ISSUE TITLE
批量插入数据Application run failed java.lang.StackOverflowError: null

### ISSUE THREAD

**Issue by ldw-gitHub** [alibaba/druid#3202]
java.lang.StackOverflowError: null
	at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.print0(SQLASTOutputVisitor.java:311)
	at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.visit(SQLASTOutputVisitor.java:2223)
	at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.printExpr(SQLASTOutputVisitor.java:958)
	at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.visit(SQLASTOutputVisitor.java:1985)
	at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.printSelectList(SQLASTOutputVisitor.java:405)
	at com.alibaba.druid.sql.dialect.oracle.visitor.OracleOutputVisitor.visit(OracleOutputVisitor.java:400)
	at com.alibaba.druid.sql.dialect.oracle.ast.stmt.OracleSelectQueryBlock.accept0(OracleSelectQueryBlock.java:102)
	at com.alibaba.druid.sql.dialect.oracle.ast.stmt.OracleSelectQueryBlock.accept0(OracleSelectQueryBlock.java:94)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:41)
	at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.visit(SQLASTOutputVisitor.java:2861)
	at com.alibaba.druid.sql.ast.statement.SQLUnionQuery.accept0(SQLUnionQuery.java:90)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:41)
	at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.visit(SQLASTOutputVisitor.java:2889)
	at com.alibaba.druid.sql.ast.statement.SQLUnionQuery.accept0(SQLUnionQuery.java:90)

**Comment by zhugleo** [comment]
遇到了同样的问题
