### ISSUE TITLE
druid without spring

### ISSUE THREAD

**Issue by vipcxj** [alibaba/druid#3222]
这个项目对spring是强依赖？没spring直接杯具
Failed to link com/alibaba/druid/support/spring/stat/DruidStatInterceptor
运行环境是纯的wildfly 13

**Comment by vipcxj** [comment]
搞了1天没搞定，看来只能换hikaricp了，一个数据库连接池为什么要强依赖于spring这样一个重型框架呢，两者根本没有什么强关联吧，虽然spring确实有够流行，但人家的默认数据库连接池不是hikaricp吗

**Comment by wenshao** [comment]
报什么错？Druid不依赖Spring的

**Comment by vipcxj** [comment]
Failed to link com/alibaba/druid/support/spring/stat/DruidStatInterceptor
然后报org.aopalliance.intercept.MethodInterceptor的NoClassDefFoundError错误

我最奇怪的是为什么会加载到`com/alibaba/druid/support/spring/stat/DruidStatInterceptor`这个类。这个错误只要将druid作为依赖打包进war就会发生，直接发生在部署阶段，即使不new DruidDataSource也会发生，因为发生在部署阶段，我也调试不了~ 我一开始怀疑是不是CDI的问题，所以在beans.xml里配置了`com.alibaba.druid.**`的scan例外，但并没有什么卵用，接着干脆把druid.jar里的spring.handler给删了，还是不行。关键不知道为什么会自动加载到这个类的机制~

**Comment by vipcxj** [comment]
```
03:52:58,532 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-2) MSC000001: Failed to start service jboss.deployment.unit."app.war".POST_MODULE: org.jboss.msc.service.StartException in service jboss.deployment.unit."app.war".POST_MODULE: WFLYSRV0153: Failed to process phase POST_MODULE of deployment "app.war"
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:150)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1736)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1698)
	at org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1556)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1378)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: Failed to link com/alibaba/druid/support/spring/stat/DruidStatInterceptor (Module "deployment.app.war" from Service Module Loader): org/aopalliance/intercept/MethodInterceptor
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:839)
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:424)
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:519)
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:339)
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:126)
	at org.jboss.modules.Module.loadModuleClass(Module.java:731)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:247)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	at org.jboss.as.ee.component.deployers.ResourceInjectionAnnotationParsingProcessor.isEnvEntryType(ResourceInjectionAnnotationParsingProcessor.java:278)
	at org.jboss.as.ee.component.deployers.ResourceInjectionAnnotationParsingProcessor.process(ResourceInjectionAnnotationParsingProcessor.java:219)
	at org.jboss.as.ee.component.deployers.ResourceInjectionAnnotationParsingProcessor.processFieldResource(ResourceInjectionAnnotationParsingProcessor.java:175)
	at org.jboss.as.ee.component.deployers.ResourceInjectionAnnotationParsingProcessor.deploy(ResourceInjectionAnnotationParsingProcessor.java:137)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:143)
	... 8 more
```
这是服务器报的错
···
03:52:07,202 INFO  [org.jboss.modules] (main) JBoss Modules version 1.8.5.Final
03:52:09,110 INFO  [org.jboss.msc] (main) JBoss MSC version 1.4.2.Final
03:52:09,135 INFO  [org.jboss.threads] (main) JBoss Threads version 2.3.2.Final
03:52:09,450 INFO  [org.jboss.as] (MSC service thread 1-2) WFLYSRV0049: WildFly Full 13.0.0.Final (WildFly Core 5.0.0.Final) starting
···
这是服务器版本。
这是部署阶段报错，和druid相关代码已经被移除，所以程序并没有主动调用druid的地方
