### ISSUE TITLE
Oracle：SET DEFINE OFF语句解析不支持 

### ISSUE THREAD

**Issue by RookieBa** [alibaba/druid#3231]

**Comment by RookieBa** [comment]
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: syntax error, expect EQ, actual IDENTIFIER pos 14, line 1, column 11, token IDENTIFIER off
	at com.alibaba.druid.sql.parser.SQLExprParser.accept(SQLExprParser.java:2467)
	at com.alibaba.druid.sql.parser.SQLExprParser.parseAssignItem(SQLExprParser.java:2797)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseAssignItems(SQLStatementParser.java:1972)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleStatementParser.parseSet(OracleStatementParser.java:1226)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleStatementParser.parseStatementList(OracleStatementParser.java:383)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:72)
