### ISSUE TITLE
postgres9.6 查询union递归时报错

### ISSUE THREAD

**Issue by gangbanbro** [alibaba/druid#3233]
sql解析异常，而实际sql在navicat中执行正常。报错sql如下：
SELECT
	place_type_code,
	parent_place_type_code,
	place_type_name,
	place_type_level
FROM
	place_type
WHERE
	place_type_code IN (
		'10101',
		'10120',
		'10103',
		'10112',
		'10104',
		'10114',
		'10119',
		'10110',
		'10117'
	)
UNION ALL
	(
		WITH RECURSIVE rs (
			place_type_code,
			parent_place_type_code,
			place_type_name,
			place_type_level
		) AS (
			SELECT
				place_type_code,
				parent_place_type_code,
				place_type_name,
				place_type_level
			FROM
				place_type
			WHERE
				place_type_code IN (
					'10101001',
					'10101004',
					'10102002',
					'10103002',
					'10104002',
					'10110001',
					'10110004',
					'10112004',
					'10112005',
					'10114001',
					'10117002',
					'10117003',
					'10119001',
					'10119002',
					'10120001'
				)
			UNION ALL
				SELECT
					p1.place_type_code,
					p1.parent_place_type_code,
					p1.place_type_name,
					p1.place_type_level
				FROM
					place_type p1
				JOIN rs ON p1.parent_place_type_code = rs.place_type_code
		) SELECT
			place_type_code,
			parent_place_type_code,
			place_type_name,
			place_type_level
		FROM
			rs
	)
ORDER BY
	place_type_code

报错信息为：
Caused by: java.sql.SQLException: sql injection violation, syntax error: syntax error, error in :'	(
		WITH RECURSIVE rs (
			place_t', expect RPAREN, actual WITH pos 247, line 21, column 4, token WITH : SELECT
	place_type_code,
	parent_place_type_code,
	place_type_name,
	place_type_level
FROM
	place_type
WHERE
	place_type_code IN (
		'10101',
		'10120',
		'10103',
		'10112',
		'10104',
		'10114',
		'10119',
		'10110',
		'10117'
	)
UNION
	(
		WITH RECURSIVE rs (
			place_type_code,
			parent_place_type_code,
			place_type_name,
			place_type_level
		) AS (
			SELECT
				place_type_code,
				parent_place_type_code,
				place_type_name,
				place_type_level
			FROM
				place_type
			WHERE
				place_type_code IN (
					'10101001',
					'10101004',
					'10102002',
					'10103002',
					'10104002',
					'10110001',
					'10110004',
					'10112004',
					'10112005',
					'10114001',
					'10117002',
					'10117003',
					'10119001',
					'10119002',
					'10120001'
				)
			UNION ALL
				SELECT
					p1.place_type_code,
					p1.parent_place_type_code,
					p1.place_type_name,
					p1.place_type_level
				FROM
					place_type p1
				JOIN rs ON p1.parent_place_type_code = rs.place_type_code
		) SELECT
			place_type_code,
			parent_place_type_code,
			place_type_name,
			place_type_level
		FROM
			rs
	)
ORDER BY
	place_type_code
	at com.alibaba.druid.wall.WallFilter.checkInternal(WallFilter.java:806)
	at com.alibaba.druid.wall.WallFilter.connection_prepareStatement(WallFilter.java:259)
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:568)
	at com.alibaba.druid.filter.FilterAdapter.connection_prepareStatement(FilterAdapter.java:930)
	at com.alibaba.druid.filter.FilterEventAdapter.connection_prepareStatement(FilterEventAdapter.java:122)
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:568)
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.prepareStatement(ConnectionProxyImpl.java:341)
	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:349)
	at sun.reflect.GeneratedMethodAccessor261.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.ConnectionLogger.invoke(ConnectionLogger.java:55)
	at com.sun.proxy.$Proxy155.prepareStatement(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.instantiateStatement(PreparedStatementHandler.java:87)
	at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:88)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.prepare(RoutingStatementHandler.java:59)
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:85)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:326)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 105 common frames omitted
Caused by: com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'	(
		WITH RECURSIVE rs (
			place_t', expect RPAREN, actual WITH pos 247, line 21, column 4, token WITH
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:287)
	at com.alibaba.druid.sql.parser.SQLParser.accept(SQLParser.java:295)
	at com.alibaba.druid.sql.parser.SQLSelectParser.query(SQLSelectParser.java:248)
	at com.alibaba.druid.sql.parser.SQLSelectParser.queryRest(SQLSelectParser.java:158)
	at com.alibaba.druid.sql.parser.SQLSelectParser.queryRest(SQLSelectParser.java:132)
	at com.alibaba.druid.sql.dialect.postgresql.parser.PGSelectParser.query(PGSelectParser.java:247)
	at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:88)
	at com.alibaba.druid.sql.dialect.postgresql.parser.PGSQLStatementParser.parseSelect(PGSQLStatementParser.java:348)
	at com.alibaba.druid.sql.dialect.postgresql.parser.PGSQLStatementParser.parseSelect(PGSQLStatementParser.java:57)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:248)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:182)
	at com.alibaba.druid.wall.WallProvider.checkInternal(WallProvider.java:624)
	at com.alibaba.druid.wall.WallProvider.check(WallProvider.java:578)
	at com.alibaba.druid.wall.WallFilter.checkInternal(WallFilter.java:793)
	... 133 common frames omitted

**Comment by gangbanbro** [comment]
将递归和前面的select调换位置union就可以正常执行

**Comment by gangbanbro** [comment]
经过多次测试验证。发现（  加上with就会报错。
同样的sql，使用jdbc直接执行不会报错，采用druid连接池就会报错
然后换连接池（使用HikariCP连接池）后不会报错
