### ISSUE TITLE
SQLServer SQL syntax error problem :  parseException 

### ISSUE THREAD

**Issue by Hyunsuk-Baek** [alibaba/druid#3241]
IF (SELECT COUNT(TEST) FROM Tabex) >= 2
BEGIN
**SELECT TEST FROM TAB1**
END
 (Parsing error)

IF (SELECT COUNT(TEST) FROM Tabex) >= 2
BEGIN
SELECT TEST FROM TAB1 **WHERE A=1**
END
 (Parsing OK)

Druid has parserException when i parse the above sql (MSSQL) like this

com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'TAB1
END', expect END, actual EOF pos 71, line 4, column 5, token EOF
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:287)
	at com.alibaba.druid.sql.parser.SQLParser.accept(SQLParser.java:295)
	at com.alibaba.druid.sql.dialect.sqlserver.parser.SQLServerStatementParser.parseBlock(SQLServerStatementParser.java:526)
	at

If i put some token as alias or WHERE or Group By, and so on after TAB1, 
then it has no error(ok), i guess some token must gives after TAB1.

Please fix this error ~~

**Comment by RockyLOMO** [comment]
+1
