### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: oracle/jdbc/internal/OraclePreparedStatement

### ISSUE THREAD

**Issue by zhanglei-1987** [alibaba/druid#3275]
druid-1.1.9.jar放在tomcat/lib目录中，应用中放入WEB-INF/libojdbc6-11.2.0.3.jar，配置PSCache为
poolPreparedStatements="true"
maxOpenPreparedStatements="128"

执行SQL时报错，感觉是ClassLoader的问题：

Caused by: java.lang.NoClassDefFoundError: oracle/jdbc/internal/OraclePreparedStatement
	at com.alibaba.druid.util.OracleUtils.unwrapInternal(OracleUtils.java:85)
	at com.alibaba.druid.util.OracleUtils.enterImplicitCache(OracleUtils.java:64)
	at com.alibaba.druid.pool.PreparedStatementPool.put(PreparedStatementPool.java:91)
	at com.alibaba.druid.pool.DruidPooledConnection.closePoolableStatement(DruidPooledConnection.java:170)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.close(DruidPooledPreparedStatement.java:202)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:78)
	at com.sun.proxy.$Proxy244.close(Unknown Source)
	at org.apache.ibatis.executor.BaseExecutor.closeStatement(BaseExecutor.java:286)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:65)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:326)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at cn.quickly.dao.mybatis.execute.SimplePageInvoker.invoke(SimplePageInvoker.java:28)
	at cn.quickly.dao.mybatis.execute.SimplePageInvoker.invoke(SimplePageInvoker.java:17)
	at cn.quickly.dao.mybatis.execute.AddinInvoker.execute(AddinInvoker.java:42)
	at cn.quickly.dao.mybatis.execute.PageInvoker.execute(PageInvoker.java:46)
	at cn.quickly.dao.mybatis.execute.PageInvoker.execute(PageInvoker.java:13)
	at cn.quickly.dao.mybatis.MybatisDao.execute(MybatisDao.java:126)
	at cn.quickly.dao.mybatis.MybatisDao.page(MybatisDao.java:88)
	at cn.quickly.dao.AbstractRelationDao.list(AbstractRelationDao.java:78)
	at cn.quickly.project.easyui.service.internal.DefaultGlobalDataService.page(DefaultGlobalDataService.java:146)
	at cn.quickly.project.easyui.service.internal.DefaultGlobalDataService$$FastClassBySpringCGLIB$$e36845b3.invoke()
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at cn.quickly.project.aspect.ValidationAspect.validate(ValidationAspect.java:57)
	... 130 more

**Comment by innovationmech** [comment]
我遇到了同样的问题，请问你解决了吗？
