### ISSUE TITLE
impala 使用druid 获取连接时有时候报错

### ISSUE THREAD

**Issue by 120003808** [alibaba/druid#3315]
java.sql.SQLNonTransientConnectionException: [Simba][JDBC](10060) Connection has been closed.
	at com.cloudera.exceptions.ExceptionConverter.toSQLException(Unknown Source) ~[impala-4.1.jar:ImpalaJDBC_2.5.43.1063]
	at com.cloudera.jdbc.common.SConnection.closeConnection(Unknown Source) ~[impala-4.1.jar:ImpalaJDBC_2.5.43.1063]
	at com.cloudera.jdbc.common.SConnection.abortInternal(Unknown Source) ~[impala-4.1.jar:ImpalaJDBC_2.5.43.1063]
	at com.cloudera.jdbc.common.SConnection.close(Unknown Source) ~[impala-4.1.jar:ImpalaJDBC_2.5.43.1063]
	at com.alibaba.druid.util.JdbcUtils.close(JdbcUtils.java:73) ~[druid-1.1.13.jar:1.1.13]
	at com.alibaba.druid.pool.DruidDataSource.discardConnection(DruidDataSource.java:1391) [druid-1.1.13.jar:1.1.13]
	at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1326) [druid-1.1.13.jar:1.1.13]
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1286) [druid-1.1.13.jar:1.1.13]
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1276) [druid-1.1.13.jar:1.1.13]
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:89) [druid-1.1.13.jar:1.1.13]
	at com.xg.common.sql.datasource.AbstractJDBCDataSource.openConnection(AbstractJDBCDataSource.java:42) [xg-common-sql-1.0.1-SNAPSHOT.jar:1.0.1-SNAPSHOT]
	at com.xg.datasource.query.DbQuery.openConnection(DbQuery.java:75) [app.jar:1.0.1-SNAPSHOT]

**Comment by ergouliang** [comment]
请问您解决了这个问题了么？我也也到这个问题了
2021-05-24 13:48:00.553 ERROR 82059 --- [ XNIO-1 task-37] com.alibaba.druid.util.JdbcUtils         : close connection error

java.sql.SQLNonTransientConnectionException: [Cloudera][JDBC](10060) Connection has been closed.
	at com.cloudera.impala.exceptions.ExceptionConverter.toSQLException(Unknown Source)
	at com.cloudera.impala.jdbc.common.SConnection.closeConnection(Unknown Source)
	at com.cloudera.impala.jdbc.common.SConnection.abortInternal(Unknown Source)
	at com.cloudera.impala.jdbc.common.SConnection.close(Unknown Source)
	at com.alibaba.druid.filter.FilterChainImpl.connection_close(FilterChainImpl.java:186)
	at com.alibaba.druid.filter.FilterAdapter.connection_close(FilterAdapter.java:777)
	at com.alibaba.druid.filter.logging.LogFilter.connection_close(LogFilter.java:451)
	at com.alibaba.druid.filter.FilterChainImpl.connection_close(FilterChainImpl.java:181)
	at com.alibaba.druid.filter.stat.StatFilter.connection_close(StatFilter.java:270)
	at com.alibaba.druid.filter.FilterChainImpl.connection_close(FilterChainImpl.java:181)
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.close(ConnectionProxyImpl.java:114)
	at com.alibaba.druid.util.JdbcUtils.close(JdbcUtils.java:85)
	at com.alibaba.druid.pool.DruidDataSource.discardConnection(DruidDataSource.java:1534)
	at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1434)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5059)
	at com.alibaba.druid.filter.logging.LogFilter.dataSource_getConnection(LogFilter.java:887)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5055)
	at com.alibaba.druid.filter.stat.StatFilter.dataSource_getConnection(StatFilter.java:689)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5055)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1393)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1385)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:100)
