### ISSUE TITLE
druid 是否支持 hbase -phoenix

### ISSUE THREAD

**Issue by FangHongDa** [alibaba/druid#3319]
phoenix-core：5.0.0-HBase-2.0

druid：1.1.9

![image](https://user-images.githubusercontent.com/18757923/60428936-8bd50b80-9c2c-11e9-8f8d-13501bdb7018.png)
Caused by: java.lang.IllegalStateException: dbType not support : phoenix, url jdbc:phoenix:10.211.55.10:2181
	at com.alibaba.druid.wall.WallFilter.init(WallFilter.java:159)
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:760)
	at com.jinshi.datasource.config.DynamicDataSourceFactory.buildDruidDataSource(DynamicDataSourceFactory.java:47)
	at com.jinshi.datasource.config.DynamicDataSourceConfig.lambda$getDynamicDataSource$0(DynamicDataSourceConfig.java:52)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at com.jinshi.datasource.config.DynamicDataSourceConfig.getDynamicDataSource(DynamicDataSourceConfig.java:51)
	at com.jinshi.datasource.config.DynamicDataSourceConfig.dynamicDataSource(DynamicDataSourceConfig.java:39)
	at com.jinshi.datasource.config.DynamicDataSourceConfig$$EnhancerBySpringCGLIB$$d2c91c06.CGLIB$dynamicDataSource$1(<generated>)
	at com.jinshi.datasource.config.DynamicDataSourceConfig$$EnhancerBySpringCGLIB$$d2c91c06$$FastClassBySpringCGLIB$$2d1bf02e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
	at com.jinshi.datasource.config.DynamicDataSourceConfig$$EnhancerBySpringCGLIB$$d2c91c06.dynamicDataSource(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 136 common frames omitted

**Comment by 1336721059** [comment]
兄弟 搞定了吗
