### ISSUE TITLE
java.sql.SQLRecoverableException: Connection reset

### ISSUE THREAD

**Issue by N8O-N8O** [alibaba/druid#3381]
druid版本：1.0.11
oracle-drive：ojdbc6

```
INFO   | jvm 1    | 2019/07/31 15:46:08 | 2019-07-31 15:46:08,312 ERROR - com.alibaba.druid.util.JdbcUtils - close connection error
INFO   | jvm 1    | 2019/07/31 15:46:08 | java.sql.SQLRecoverableException: IO ´íÎó: Connection reset
INFO   | jvm 1    | 2019/07/31 15:46:08 | 	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:504) ~[ojdbc6-11.2.0.1.0.jar:11.2.0.1.0]
INFO   | jvm 1    | 2019/07/31 15:46:08 | 	at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:3754) ~[ojdbc6-11.2.0.1.0.jar:11.2.0.1.0]
INFO   | jvm 1    | 2019/07/31 15:46:08 | 	at com.alibaba.druid.filter.FilterChainImpl.connection_close(FilterChainImpl.java:175) ~[druid-1.1.9.jar:1.1.9]
INFO   | jvm 1    | 2019/07/31 15:46:08 | 	at com.alibaba.druid.filter.stat.StatFilter.connection_close(StatFilter.java:261) ~[druid-1.1.9.jar:1.1.9]
INFO   | jvm 1    | 2019/07/31 15:46:08 | 	at com.alibaba.druid.filter.FilterChainImpl.connection_close(FilterChainImpl.java:171) ~[druid-1.1.9.jar:1.1.9]
INFO   | jvm 1    | 2019/07/31 15:46:08 | 	at com.alibaba.druid.filter.FilterAdapter.connection_close(FilterAdapter.java:776) ~[druid-1.1.9.jar:1.1.9]
INFO   | jvm 1    | 2019/07/31 15:46:08 | 	at com.alibaba.druid.filter.logging.LogFilter.connection_close(LogFilter.java:440) ~[druid-1.1.9.jar:1.1.9]
INFO   | jvm 1    | 2019/07/31 15:46:08 | 	at com.alibaba.druid.filter.FilterChainImpl.connection_close(FilterChainImpl.java:171) ~[druid-1.1.9.jar:1.1.9]
INFO   | jvm 1    | 2019/07/31 15:46:08 | 	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.close(ConnectionProxyImpl.java:115) ~[druid-1.1.9.jar:1.1.9]
INFO   | jvm 1    | 2019/07/31 15:46:08 | 	at com.alibaba.druid.util.JdbcUtils.close(JdbcUtils.java:73) [druid-1.1.9.jar:1.1.9]
INFO   | jvm 1    | 2019/07/31 15:46:08 | 	at com.alibaba.druid.pool.DruidDataSource.shrink(DruidDataSource.java:2795) [druid-1.1.9.jar:1.1.9]
INFO   | jvm 1    | 2019/07/31 15:46:08 | 	at com.alibaba.druid.pool.DruidDataSource$DestroyTask.run(DruidDataSource.java:2560) [druid-1.1.9.jar:1.1.9]
INFO   | jvm 1    | 2019/07/31 15:46:08 | 	at com.alibaba.druid.pool.DruidDataSource$DestroyConnectionThread.run(DruidDataSource.java:2547) [druid-1.1.9.jar:1.1.9]
INFO   | jvm 1    | 2019/07/31 15:46:08 | Caused by: java.net.SocketException: Connection reset
INFO   | jvm 1    | 2019/07/31 15:46:08 | 	at java.net.SocketInputStream.read(SocketInputStream.java:209) ~[?:1.8.0_66]
INFO   | jvm 1    | 2019/07/31 15:46:08 | 	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_66]
INFO   | jvm 1    | 2019/07/31 15:46:08 | 	at oracle.net.ns.Packet.receive(Packet.java:282) ~[ojdbc6-11.2.0.1.0.jar:11.2.0.1.0]
INFO   | jvm 1    | 2019/07/31 15:46:08 | 	at oracle.net.ns.DataPacket.receive(DataPacket.java:103) ~[ojdbc6-11.2.0.1.0.jar:11.2.0.1.0]
INFO   | jvm 1    | 2019/07/31 15:46:08 | 	at oracle.net.ns.NetInputStream.getNextPacket(NetInputStream.java:230) ~[ojdbc6-11.2.0.1.0.jar:11.2.0.1.0]
INFO   | jvm 1    | 2019/07/31 15:46:08 | 	at oracle.net.ns.NetInputStream.read(NetInputStream.java:175) ~[ojdbc6-11.2.0.1.0.jar:11.2.0.1.0]
INFO   | jvm 1    | 2019/07/31 15:46:08 | 	at oracle.net.ns.NetInputStream.read(NetInputStream.java:100) ~[ojdbc6-11.2.0.1.0.jar:11.2.0.1.0]
INFO   | jvm 1    | 2019/07/31 15:46:08 | 	at oracle.net.ns.NetInputStream.read(NetInputStream.java:85) ~[ojdbc6-11.2.0.1.0.jar:11.2.0.1.0]
INFO   | jvm 1    | 2019/07/31 15:46:08 | 	at oracle.jdbc.driver.T4CSocketInputStreamWrapper.readNextPacket(T4CSocketInputStreamWrapper.java:122) ~[ojdbc6-11.2.0.1.0.jar:11.2.0.1.0]
INFO   | jvm 1    | 2019/07/31 15:46:08 | 	at oracle.jdbc.driver.T4CSocketInputStreamWrapper.read(T4CSocketInputStreamWrapper.java:78) ~[ojdbc6-11.2.0.1.0.jar:11.2.0.1.0]
INFO   | jvm 1    | 2019/07/31 15:46:08 | 	at oracle.jdbc.driver.T4CMAREngine.unmarshalUB1(T4CMAREngine.java:1179) ~[ojdbc6-11.2.0.1.0.jar:11.2.0.1.0]
INFO   | jvm 1    | 2019/07/31 15:46:08 | 	at oracle.jdbc.driver.T4CMAREngine.unmarshalSB1(T4CMAREngine.java:1155) ~[ojdbc6-11.2.0.1.0.jar:11.2.0.1.0]
INFO   | jvm 1    | 2019/07/31 15:46:08 | 	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:279) ~[ojdbc6-11.2.0.1.0.jar:11.2.0.1.0]
INFO   | jvm 1    | 2019/07/31 15:46:08 | 	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:186) ~[ojdbc6-11.2.0.1.0.jar:11.2.0.1.0]
INFO   | jvm 1    | 2019/07/31 15:46:08 | 	at oracle.jdbc.driver.T4C7Ocommoncall.doOLOGOFF(T4C7Ocommoncall.java:61) ~[ojdbc6-11.2.0.1.0.jar:11.2.0.1.0]
INFO   | jvm 1    | 2019/07/31 15:46:08 | 	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:491) ~[ojdbc6-11.2.0.1.0.jar:11.2.0.1.0]
INFO   | jvm 1    | 2019/07/31 15:46:08 | 	... 12 more
```
```
2019-07-31 02:59:13,658 INFO - com.alibaba.druid.pool.DruidDataSourceStatLoggerImpl - {"url":"jdbc:oracle:thin:@10.208.19.195:1521:ctsdb","dbType":"oracle","name":"DataSource-226369544","activeCount":0,"poolingCount":5,"connectCount":0,"closeCount":0}
2019-07-31 02:59:43,659 INFO - com.alibaba.druid.pool.DruidDataSourceStatLoggerImpl - {"url":"jdbc:oracle:thin:@10.208.19.195:1521:ctsdb","dbType":"oracle","name":"DataSource-226369544","activeCount":0,"poolingCount":5,"connectCount":0,"closeCount":0}
2019-07-31 03:00:13,660 INFO - com.alibaba.druid.pool.DruidDataSourceStatLoggerImpl - {"url":"jdbc:oracle:thin:@10.208.19.195:1521:ctsdb","dbType":"oracle","name":"DataSource-226369544","activeCount":0,"poolingCount":0,"connectCount":0,"closeCount":0,"physicalCloseCount":5}
2019-07-31 03:00:43,660 INFO - com.alibaba.druid.pool.DruidDataSourceStatLoggerImpl - {"url":"jdbc:oracle:thin:@10.208.19.195:1521:ctsdb","dbType":"oracle","name":"DataSource-226369544","activeCount":0,"poolingCount":0,"connectCount":0,"closeCount":0}
2019-07-31 03:01:13,661 INFO - com.alibaba.druid.pool.DruidDataSourceStatLoggerImpl - {"url":"jdbc:oracle:thin:@10.208.19.195:1521:ctsdb","dbType":"oracle","name":"DataSource-226369544","activeCount":0,"poolingCount":0,"connectCount":0,"closeCount":0}
2019-07-31 03:01:43,663 INFO - com.alibaba.druid.pool.DruidDataSourceStatLoggerImpl - {"url":"jdbc:oracle:thin:@10.208.19.195:1521:ctsdb","dbType":"oracle","name":"DataSource-226369544","activeCount":0,"poolingCount":0,"connectCount":0,"closeCount":0}
```

报错如截图。。。请问physicalCloseCount到底代表了什么。感觉像是网络闪断导致的，但是同一台机器上的另一个系统同样用druid链接Oracle，就没有报这样的错误。推测的原因是？

**Comment by WangChangJuan** [comment]
这个应该是连接池的后台扫描线程把，发现了断网的连接而报的错误? 如果不是调用时抛出的异常，可以忽略不管？

**Comment by taofei1** [comment]
我也是的，同一台机器上的oracle连接就没问题，远程连接过段时间不操作就关闭了
