### ISSUE TITLE
PGSQLStatementParser 不支持匿名代码块

### ISSUE THREAD

**Issue by Duncan-tree-zhou** [alibaba/druid#3450]
PGSQLStatementParser不支持匿名代码块的解析，丢进去报错了。

执行如下代码
``` java
      String sql = "DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 't_gl_myoperation') THEN\n"
          + "CREATE TABLE T_GL_MYOPERATION (fid BIGINT NOT NULL, fcreatorid BIGINT NOT NULL DEFAULT 0, forgid BIGINT NOT NULL DEFAULT 0, fmenuid CHARACTER VARYING (36) DEFAULT ' ', fcreatetime TIMESTAMP WITHOUT TIME ZONE, fbizappid CHARACTER VARYING (36));\n"
          + "END IF; END $do$;";
      List<SQLStatement> sqlStatements = SQLUtils.parseStatements(sql, JdbcUtils.POSTGRESQL);
      String druidsql = SQLUtils.toSQLString(sqlStatements, JdbcUtils.POSTGRESQL);
      System.out.println(druidsql);
```

报错
``` 
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'DO $do$ BEGIN IF NOT EXISTS (S', expect DO, actual DO pos 2, line 1, column 1, token DO
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:287)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:532)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:171)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:495)
	at com.alibaba.druid.MainTest.main(MainTest.java:14)
```

PGSQLStatementParser 能否提供下更多的支持，或者讨论下给你们提个pr也可以。

**Comment by 13567436138** [comment]
确实是不支持

**Comment by Duncan-tree-zhou** [comment]
> 确实是不支持

看PGSQLStatementParser 里面有好多todo exception，是否有计划实现以下代码？

**Comment by 13567436138** [comment]
我来实现试试，有点难度

**Comment by 13567436138** [comment]
if 语句不支持啊，不好弄

**Comment by Duncan-tree-zhou** [comment]
> if 语句不支持啊，不好弄

谢谢这位兄弟，我再自己想想办法
