### ISSUE TITLE
Mysql ADD COLUMN语句中带After结尾解析异常

### ISSUE THREAD

**Issue by KolorYan** [alibaba/druid#3453]
`String sqlExp = "ALTER TABLE `my_table` ADD COLUMN `ref_id` bigint(0) NULL COMMENT 'xxxxx' AFTER `user_id`;";
        List<SQLStatement> stats = SQLUtils.parseStatements(sqlExp, MYSQL);`

Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'xxx' AFTER `user_id`;', expect IDENTIFIER, actual IDENTIFIER pos 81, line 2, column 52, token IDENTIFIER AFTER
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:287)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:532)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:171)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:495)

**Comment by 13567436138** [comment]
我看看

**Comment by 13567436138** [comment]
String sqlExp = "ALTER TABLE my_table ADD COLUMN ref_id bigint(0) NULL COMMENT 'xxxxx' AFTER user_id;";
            List<SQLStatement> stats = SQLUtils.parseStatements(sqlExp, JdbcConstants.MYSQL);

没问题，最新代码不报错。
user_id`为啥有个`
