### ISSUE TITLE
Mysql 函数脚本不支持return 语句

### ISSUE THREAD

**Issue by taolive** [alibaba/druid#3455]
```sql
CREATE function getVal() RETURNS int(11)
BEGIN
    DECLARE VALUE INTEGER;
    SET VALUE = 0;
    RETURN VALUE;
END;

```

mysql：5.7
druid：1.1.20
```xml
<dependency>
   <groupId>com.alibaba</groupId>
   <artifactId>druid</artifactId>
   <version>1.1.20</version>
</dependency>
```

异常信息：
```java
Caused by: java.sql.SQLException: sql injection violation, class com.alibaba.druid.sql.dialect.mysql.ast.clause.MySqlDeclareStatement not allow : CREATE function getVal() RETURNS int(11)
BEGIN
    DECLARE VALUE INTEGER;
    SET VALUE = 0;
    RETURN VALUE;
END;
	at com.alibaba.druid.wall.WallFilter.checkInternal(WallFilter.java:800)
	at com.alibaba.druid.wall.WallFilter.check(WallFilter.java:780)
	at com.alibaba.druid.wall.WallFilter.statement_execute(WallFilter.java:413)
	at com.alibaba.druid.filter.FilterChainImpl.statement_execute(FilterChainImpl.java:2598)
	at com.alibaba.druid.filter.FilterAdapter.statement_execute(FilterAdapter.java:2473)
	at com.alibaba.druid.filter.FilterEventAdapter.statement_execute(FilterEventAdapter.java:188)
	at com.alibaba.druid.filter.FilterChainImpl.statement_execute(FilterChainImpl.java:2598)
	at com.alibaba.druid.filter.FilterAdapter.statement_execute(FilterAdapter.java:2473)
	at com.alibaba.druid.filter.FilterChainImpl.statement_execute(FilterChainImpl.java:2598)
	at com.alibaba.druid.filter.FilterAdapter.statement_execute(FilterAdapter.java:2473)
	at com.alibaba.druid.filter.FilterEventAdapter.statement_execute(FilterEventAdapter.java:188)
	at com.alibaba.druid.filter.FilterChainImpl.statement_execute(FilterChainImpl.java:2598)
	at com.alibaba.druid.proxy.jdbc.StatementProxyImpl.execute(StatementProxyImpl.java:147)
	at com.alibaba.druid.pool.DruidPooledStatement.execute(DruidPooledStatement.java:558)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:307)
	... 55 common frames omitted
```

**Comment by 13567436138** [comment]
检测到sql注入了

**Comment by 13567436138** [comment]
https://github.com/alibaba/druid/pull/3419/commits/f39d64c684f982e66387af7017126c0ff31443af
已提交代码
