### ISSUE TITLE
oracle 批量插入3000+条数据 导致StackOverflowError

### ISSUE THREAD

**Issue by liumeijian** [alibaba/druid#3459]
oracle版本: 12g
驱动版本: ojdbc8(12.2.0.1.0)
druid版本 1.1.20

```
java.lang.StackOverflowError: null
	at com.alibaba.druid.sql.parser.Lexer.scanIdentifier(Lexer.java:1766)
	at com.alibaba.druid.sql.parser.Lexer.nextToken(Lexer.java:641)
	at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:385)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleExprParser.primary(OracleExprParser.java:516)
	at com.alibaba.druid.sql.parser.SQLExprParser.expr(SQLExprParser.java:154)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.parseTableSourceQueryTableExpr(OracleSelectParser.java:686)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.parseTableSourcePrimary(OracleSelectParser.java:678)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.parseTableSource(OracleSelectParser.java:624)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseFrom(SQLSelectParser.java:695)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.query(OracleSelectParser.java:321)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.queryRest(OracleSelectParser.java:351)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.query(OracleSelectParser.java:333)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.queryRest(OracleSelectParser.java:351)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.query(OracleSelectParser.java:333)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.queryRest(OracleSelectParser.java:351)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.query(OracleSelectParser.java:333)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.queryRest(OracleSelectParser.java:351)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.query(OracleSelectParser.java:333)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.queryRest(OracleSelectParser.java:351)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.query(OracleSelectParser.java:333)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.queryRest(OracleSelectParser.java:351)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.query(OracleSelectParser.java:333)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.queryRest(OracleSelectParser.java:351)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.query(OracleSelectParser.java:333)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.queryRest(OracleSelectParser.java:351)
```

插入语句(mybatis)
```
 insert into bst_sow_breed_data (data_id,ec_id, batch_id, pig_farm,
        pig_house, data_date, breed_group_no,
        pig_pen, sow_no, farm_inside_no,
        parity, issue, breed_no,
        relation_state, rut_situation, grade,
        time, boar_no, boar_farm_inside_no,
        breed_way, breeder, descendant,
        remark, create_user, create_date,
        update_user, update_date, update_time,
        user_voucher_no)
        select SEQ_BST_SOW_BREED_DATA_ID.nextval data_id,cd.* from(
        <foreach collection="list" item="item" index="index" close=")" open="(" separator="union">
            select
            #{item.ecId,jdbcType=VARCHAR}, #{item.batchId,jdbcType=VARCHAR}, #{item.pigFarm,jdbcType=VARCHAR},
            #{item.pigHouse,jdbcType=VARCHAR}, #{item.dataDate,jdbcType=TIMESTAMP}, #{item.breedGroupNo,jdbcType=VARCHAR},
            #{item.pigPen,jdbcType=VARCHAR}, #{item.sowNo,jdbcType=VARCHAR}, #{item.farmInsideNo,jdbcType=VARCHAR},
            #{item.parity,jdbcType=INTEGER}, #{item.issue,jdbcType=INTEGER}, #{item.breedNo,jdbcType=INTEGER},
            #{item.relationState,jdbcType=VARCHAR}, #{item.rutSituation,jdbcType=VARCHAR},
            #{item.grade,jdbcType=INTEGER},
            #{item.time,jdbcType=INTEGER}, #{item.boarNo,jdbcType=VARCHAR}, #{item.boarFarmInsideNo,jdbcType=VARCHAR},
            #{item.breedWay,jdbcType=VARCHAR}, #{item.breeder,jdbcType=VARCHAR}, #{item.descendant,jdbcType=VARCHAR},
            #{item.remark,jdbcType=VARCHAR}, #{item.createUser,jdbcType=VARCHAR}, #{item.createDate,jdbcType=TIMESTAMP},
            #{item.updateUser,jdbcType=VARCHAR}, #{item.updateDate,jdbcType=TIMESTAMP},
            #{item.updateTime,jdbcType=TIMESTAMP},
            #{item.userVoucherNo,jdbcType=VARCHAR}
            from dual
        </foreach>
        ) cd
```

**Comment by Imagoodboy** [comment]
请问close是解决了吗?遇到了同样的问题
