### ISSUE TITLE
mysql ddl alter语句解析报错

### ISSUE THREAD

**Issue by ogaryo** [alibaba/druid#3481]
调用代码
```java

        String sql="ALTER TABLE `my_dev`.`test_info` \n" +
                "DROP COLUMN `b`,\n" +
                "MODIFY COLUMN `a` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '111' AFTER `d`,\n" +
                "ADD COLUMN `c` varchar(255) NULL COMMENT '333' AFTER `a`";

List<SQLStatement> stmtList = SQLUtils.parseStatements(sql, JdbcConstants.MYSQL);

```

报错信息如下
```
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'DIFY COLUMN `a` varchar(255) CHARAC', expect COLUMN, actual COLUMN pos 78, line 1, column 72, token COLUMN
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:287)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:532)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:171)
	at com.alibaba.druid.sql.SQLUtils.parseSingleStatement(SQLUtils.java:513)
	at com.alibaba.druid.sql.SQLUtils.parseSingleMysqlStatement(SQLUtils.java:526)
```
使用的sql语句
```sql
ALTER TABLE `my_dev`.`test_info` 
DROP COLUMN `b`,
MODIFY COLUMN `a` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '111' AFTER `d`,
ADD COLUMN `c` varchar(255) NULL COMMENT '333' AFTER `a`
```
druid版本号
druid version 1.1.20、1.1.19、1.1.18 后面的没有继续试了

**Comment by yanchangyou** [comment]
遇到同样问题
