### ISSUE TITLE
不能解析DDL语句中的CHECK TABLE

### ISSUE THREAD

**Issue by lAndRaxeE** [alibaba/druid#3509]
之前有一个bug #2065, 显示已经修复，但是查看代码修改历史，发现只是支持了建表时的foreign key，而并没有支持check。使用1.1.20版本测试

`check table table_test fast quick`

报错
`com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'check table report_cache_3a45a', expect CHECK, actual CHECK pos 5, line 1, column 1, token CHECK

	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:287)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:532)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:2853)`

**Comment by lAndRaxeE** [comment]
@wenshao
