### ISSUE TITLE
druid的oracle数据源密码配置错误，导致用户被锁

### ISSUE THREAD

**Issue by 903452746** [alibaba/druid#3528]
你好，
oracle数据源配置中，密码配置错误， druid的创建连接的后台守护线程在不断的尝试，导致用户被锁。

建议增加重试的判断条件，对于特定的SQLException错误，不进行重试。

我采用的动态创建的数据源，运行状态下，可以增删数据源，这种场景下，数据源密码配置错概率高，却不易发现

`[ERROR][2019-10-25 09:16:37][Druid-ConnectionPool-Create-154468798][com.alibaba.druid.pool.DruidDataSource] create connection SQLException, url: jdbc:mysql://192.168.3.28:3306/dd?useUnicode=true&characterEncoding=utf-8, errorCode 1045, state 28000
java.sql.SQLException: Access denied for user 'dongdong'@'192.168.80.206' (using password: YES)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.15.jar:8.0.15]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.15.jar:8.0.15]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.15.jar:8.0.15]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:835) ~[mysql-connector-java-8.0.15.jar:8.0.15]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455) ~[mysql-connector-java-8.0.15.jar:8.0.15]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240) ~[mysql-connector-java-8.0.15.jar:8.0.15]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[mysql-connector-java-8.0.15.jar:8.0.15]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1643) ~[druid-1.1.20.jar:1.1.20]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1709) ~[druid-1.1.20.jar:1.1.20]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2715) ~[druid-1.1.20.jar:1.1.20]`

**Comment by 6LWa6ZKx** [comment]
同样的问题，我们是通过前端配置不同的数据源，然后取数据。
