### ISSUE TITLE
无法建立新连接， 1.1.20版本 ，默认配置

### ISSUE THREAD

**Issue by airshiplay** [alibaba/druid#3531]
java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000086c44650> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at com.alibaba.druid.pool.DruidDataSource.takeLast(DruidDataSource.java:2111)
	at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1620)
	at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1395)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1375)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1365)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:109)

**Comment by airshiplay** [comment]
![image](https://user-images.githubusercontent.com/3456719/67831348-fcc3fb80-fb18-11e9-8f60-49509d6f65f9.png)

![image](https://user-images.githubusercontent.com/3456719/67831378-1a916080-fb19-11e9-807a-0f3d3334f550.png)
