### ISSUE TITLE
apollo 作为配置中心 通过 “actuator/refresh” 第一次刷新成功了，但是我设置的password 为错误的，需要第二次刷新密码，但是不工作了。一直再报第一个认证错误。

### ISSUE THREAD

**Issue by WERNERWAN1** [alibaba/druid#3615]
Caused by: java.sql.SQLException: Access denied for user 'root'@'10.11.11.112' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2037)
	... 20 common frames omitted

**Comment by WERNERWAN1** [comment]
本地开发环境(windows)有问题，测试环境（linux）没有问题
