### ISSUE TITLE
transactionRecord null

### ISSUE THREAD

**Issue by thineagle** [alibaba/druid#3632]
调试发现在执行execute()方法的时候，将sql保存在transactionInfo中, 但是偶尔会出现java.lang.ArrayIndexOutOfException:null的错误，堆栈信息如下， 请问这能是什么原因？
ava.lang.ArrayIndexOutOfBoundsException: null
	at java.util.ArrayList.add(ArrayList.java:474) ~[?:1.8.0]
	at com.alibaba.druid.pool.DruidPooledConnection.transactionRecord(DruidPooledConnection.java:730) ~[druid-1.1.20.jar:1.1.20]
	at com.alibaba.druid.pool.DruidPooledStatement.transactionRecord(DruidPooledStatement.java:285) ~[druid-1.1.20.jar:1.1.20]
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:491) ~[druid-1.1.20.jar:1.1.20]

**Comment by ghf704694314** [comment]
又找到解决办法吗
