### ISSUE TITLE
druid 1.0.20版本在高并发下会出现大量statement is closed.

### ISSUE THREAD

**Issue by yichuanfeixu** [alibaba/druid#3642]
**发生的情况：**
在高并发下会出现Error querying database.  Cause: java.sql.SQLException: statement is closed...
mysql版本：5.7.21
使用的框架是：springboot2.1.6+mybatis1.3.2+mysql-connector-java5.1.44
我们1.0.20的配置如下：
        dataSource.setInitialSize(5);
        dataSource.setMinIdle(5);
        dataSource.setMaxActive(100);
        dataSource.setMaxWait(600000);
        dataSource.setTimeBetweenEvictionRunsMillis(60000);
        dataSource.setMinEvictableIdleTimeMillis(60000);
        dataSource.setKeepAlive(true);
        dataSource.setTestOnBorrow(true);
        dataSource.setTestWhileIdle(true);
dataSource.setValidConnectionCheckerClassName("com.alibaba.druid.pool.vendor.MySqlValidConnectionChecker");
        dataSource.setValidationQuery("SELECT 1");
        dataSource.setPoolPreparedStatements(false);

**详细的异常：**
org.springframework.jdbc.UncategorizedSQLException: 
Error querying database.  Cause: java.sql.SQLException: statement is closed
The error may exist in class path resource [mapper/xxxMapper.xml]
The error may involve com.sftccd.sms.sender.mapper.SmsTemplateMapper.findChannelsByTemplateId
The error occurred while handling results
SQL: select * from table .......... 
Cause: java.sql.SQLException: statement is closed; uncategorized SQLException; SQL state [null]; error code [0]; statement is closed; nested exception is java.sql.SQLException: statement is closed
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:89)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy61.selectOne(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:166)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:83)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy65.findChannelsByTemplateId(Unknown Source)
	at com.sftccd.sms.sender.consumer.sender.SmsProxy.send(SmsProxy.java:33)
	at com.sftccd.sms.sender.consumer.service.MsgService.sendMsg(MsgService.java:109)
	at com.sftccd.sms.sender.consumer.service.MarketService.executeMsgTask(MarketService.java:33)
	at com.sftccd.sms.sender.consumer.service.MarketService$$FastClassBySpringCGLIB$$c9c189ce.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: statement is closed
	at com.alibaba.druid.pool.DruidPooledStatement.checkOpen(DruidPooledStatement.java:182)
	at com.alibaba.druid.pool.DruidPooledStatement.getResultSet(DruidPooledStatement.java:643)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.getFirstResultSet(DefaultResultSetHandler.java:239)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSets(DefaultResultSetHandler.java:189)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:64)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:326)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:77)
	at sun.reflect.GeneratedMethodAccessor108.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 17 more

还请大神解惑下，小弟不胜感激。

**Comment by LiemLin** [comment]
@yichuanfeixu 这个问题解决了吗

**Comment by BruceZhangXL** [comment]
这个问题解决了么

**Comment by hylyLLL** [comment]
> **发生的情况：**
> 在高并发下会出现Error querying database. Cause: java.sql.SQLException: statement is closed...
> mysql版本：5.7.21
> 使用的框架是：springboot2.1.6+mybatis1.3.2+mysql-connector-java5.1.44
> 我们1.0.20的配置如下：
> dataSource.setInitialSize(5);
> dataSource.setMinIdle(5);
> dataSource.setMaxActive(100);
> dataSource.setMaxWait(600000);
> dataSource.setTimeBetweenEvictionRunsMillis(60000);
> dataSource.setMinEvictableIdleTimeMillis(60000);
> dataSource.setKeepAlive(true);
> dataSource.setTestOnBorrow(true);
> dataSource.setTestWhileIdle(true);
> dataSource.setValidConnectionCheckerClassName("com.alibaba.druid.pool.vendor.MySqlValidConnectionChecker");
> dataSource.setValidationQuery("SELECT 1");
> dataSource.setPoolPreparedStatements(false);
> 
> **详细的异常：**
> org.springframework.jdbc.UncategorizedSQLException:
> Error querying database. Cause: java.sql.SQLException: statement is closed
> The error may exist in class path resource [mapper/xxxMapper.xml]
> The error may involve com.sftccd.sms.sender.mapper.SmsTemplateMapper.findChannelsByTemplateId
> The error occurred while handling results
> SQL: select * from table ..........
> Cause: java.sql.SQLException: statement is closed; uncategorized SQLException; SQL state [null]; error code [0]; statement is closed; nested exception is java.sql.SQLException: statement is closed
> at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:89)
> at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
> at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
> at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
> at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
> at com.sun.proxy.$Proxy61.selectOne(Unknown Source)
> at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:166)
> at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:83)
> at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
> at com.sun.proxy.$Proxy65.findChannelsByTemplateId(Unknown Source)
> at com.sftccd.sms.sender.consumer.sender.SmsProxy.send(SmsProxy.java:33)
> at com.sftccd.sms.sender.consumer.service.MsgService.sendMsg(MsgService.java:109)
> at com.sftccd.sms.sender.consumer.service.MarketService.executeMsgTask(MarketService.java:33)
> at com.sftccd.sms.sender.consumer.service.MarketService$$FastClassBySpringCGLIB$$c9c189ce.invoke()
> at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
> at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
> at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
> at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
> at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> at java.lang.Thread.run(Thread.java:748)
> Caused by: java.sql.SQLException: statement is closed
> at com.alibaba.druid.pool.DruidPooledStatement.checkOpen(DruidPooledStatement.java:182)
> at com.alibaba.druid.pool.DruidPooledStatement.getResultSet(DruidPooledStatement.java:643)
> at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.getFirstResultSet(DefaultResultSetHandler.java:239)
> at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSets(DefaultResultSetHandler.java:189)
> at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:64)
> at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
> at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
> at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:326)
> at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
> at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
> at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
> at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
> at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
> at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:77)
> at sun.reflect.GeneratedMethodAccessor108.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
> ... 17 more
> 
> 还请大神解惑下，小弟不胜感激。

你好，我在使用1.1.10的druid的时候，也出现这个问题，后面经常性出现：
### The error may exist in URL [jar:file:/app/datasync.jar!/BOOT-INF/classes!/mapper/ak/AKSynRecordMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: select  * from syn_record  order by syn_time asc
### Cause: java.sql.SQLException: Error
; uncategorized SQLException; SQL state [null]; error code [0]; Error; nested exception is java.sql.SQLException: Error
类似于这中错误，sql是正常的

**Comment by yichuanfeixu** [comment]
配置的问题：看了源码testWhileIdle和testOnBorrow是互斥的。
      testOnBorrow设置为默认值false        
        dataSource.setInitialSize(2);
        dataSource.setMinIdle(2);
        dataSource.setMaxActive(100);
        dataSource.setMaxWait(60000);
        dataSource.setTimeBetweenEvictionRunsMillis(60000);
        dataSource.setMinEvictableIdleTimeMillis(250000); 后面就没出现过类似的问题了

**Comment by hylyLLL** [comment]
> 配置的问题：看了源码testWhileIdle和testOnBorrow是互斥的。
> testOnBorrow设置为默认值false
> dataSource.setInitialSize(2);
> dataSource.setMinIdle(2);
> dataSource.setMaxActive(100);
> dataSource.setMaxWait(60000);
> dataSource.setTimeBetweenEvictionRunsMillis(60000);
> dataSource.setMinEvictableIdleTimeMillis(250000); 后面就没出现过类似的问题了

也就是说testWhileIdle和testOnBorrow都让其保持默认值吗？

**Comment by beyondhc** [comment]
> 配置的问题：看了源码testWhileIdle和testOnBorrow是互斥的。 testOnBorrow设置为默认值false dataSource.setInitialSize(2); dataSource.setMinIdle(2); dataSource.setMaxActive(100); dataSource.setMaxWait(60000); dataSource.setTimeBetweenEvictionRunsMillis(60000); dataSource.setMinEvictableIdleTimeMillis(250000); 后面就没出现过类似的问题了

@yichuanfeixu 请教下配置互斥为啥会出现这样的问题呢？我看了下源码testWhileIdle和testOnBorrow都是true的话只会执行一个优先testOnBorrow

**Comment by BruceZhangXL** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
