### ISSUE TITLE
建表语句字段中只有COLLATE 没有CHARACTER SET会导致ParserException

### ISSUE THREAD

**Issue by HessianZ** [alibaba/druid#3649]
版本：1.1.21

调用堆栈
```
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: syntax error, error in :''n') COLLATE utf8_unicode_ci NOT NU', expect RPAREN, actual IDENTIFIER pos 306, line 6, column 29, token IDENTIFIER COLLATE
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:344)
	at com.alibaba.druid.sql.parser.SQLParser.accept(SQLParser.java:352)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlCreateTableParser.parseCreateTable(MySqlCreateTableParser.java:322)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseCreate(MySqlStatementParser.java:415)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:260)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:171)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:495)
	at MainKt.main(Main.kt:26)

```

测试SQL

```
CREATE TABLE `jd_activity_manager` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '编号',
  `activity_id` int(10) unsigned NOT NULL COMMENT '邮件ID',
  `manager_id` int(10) unsigned NOT NULL COMMENT '人员ID',
  `company_id` int(10) unsigned NOT NULL COMMENT '单位ID',
  `receipted` enum('y','n') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'n' COMMENT '回执',
  `receipt_content` text COLLATE utf8_unicode_ci COMMENT '回执内容',
  `receipt_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '回执时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `activity_id` (`activity_id`,`manager_id`),
  KEY `activity_id_2` (`activity_id`),
  KEY `manager_id` (`manager_id`),
  CONSTRAINT `jd_activity_manager_ibfk_1` FOREIGN KEY (`activity_id`) REFERENCES `jd_activity` (`id`),
  CONSTRAINT `jd_activity_manager_ibfk_2` FOREIGN KEY (`manager_id`) REFERENCES `jd_managers` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='活动-人员'
```

**Comment by lizongbo** [comment]
请使用最新版验证。
