### ISSUE TITLE
1.1.18版本，在DB2 对时间多次增减、且增减单位不相同时会解析错误

### ISSUE THREAD

**Issue by cremin-dong** [alibaba/druid#3700]
版本：1.1.18

Druid-1.1.7及其前期版本已经修复了db2日期相关的部分问题https://github.com/alibaba/druid/issues/2169 ，即：

SELECT current timestamp - 7 day FROM sysibm.dual 是正常的
SELECT current timestamp - 7 day - 8 day - 9 day FROM sysibm.dual 当增减的单位相同时，也是正常的

但是当对时间多次操作、且操作的单位不相同时，仍旧转换出错
SELECT current timestamp - 1 **month** + 1 **day** cycleStartTime FROM sysibm.dual

Caused by: com.alibaba.druid.sql.parser.ParserException: syntax error, error in :' - 1 month + 1 day cycleStartTime F', expect PLUS, actual PLUS pos 36, line 1, column 35, token PLUS
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:287) ~[druid-1.1.18.jar:1.1.18]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:532) ~[druid-1.1.18.jar:1.1.18]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:182) ~[druid-1.1.18.jar:1.1.18]
	at com.alibaba.druid.wall.WallProvider.checkInternal(WallProvider.java:624) ~[druid-1.1.18.jar:1.1.18]
	at com.alibaba.druid.wall.WallProvider.check(WallProvider.java:578) ~[druid-1.1.18.jar:1.1.18]
	at com.alibaba.druid.wall.WallFilter.checkInternal(WallFilter.java:793) ~[druid-1.1.18.jar:1.1.18]
	at com.alibaba.druid.wall.WallFilter.connection_prepareStatement(WallFilter.java:259) ~[druid-1.1.18.jar:1.1.18]
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:568) ~[druid-1.1.18.jar:1.1.18]
	at com.alibaba.druid.filter.FilterAdapter.connection_prepareStatement(FilterAdapter.java:930) ~[druid-1.1.18.jar:1.1.18]
	at com.alibaba.druid.filter.FilterEventAdapter.connection_prepareStatement(FilterEventAdapter.java:122) ~[druid-1.1.18.jar:1.1.18]
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:568) ~[druid-1.1.18.jar:1.1.18]
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.prepareStatement(ConnectionProxyImpl.java:341) ~[druid-1.1.18.jar:1.1.18]
	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:349) ~[druid-1.1.18.jar:1.1.18]
	at sun.reflect.GeneratedMethodAccessor120.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at org.apache.ibatis.logging.jdbc.ConnectionLogger.invoke(ConnectionLogger.java:55) ~[mybatis-3.4.0.jar:3.4.0]
	at com.sun.proxy.$Proxy280.prepareStatement(Unknown Source) ~[?:?]
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.instantiateStatement(PreparedStatementHandler.java:87) ~[mybatis-3.4.0.jar:3.4.0]
	at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:88) ~[mybatis-3.4.0.jar:3.4.0]
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.prepare(RoutingStatementHandler.java:59) ~[mybatis-3.4.0.jar:3.4.0]
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:85) ~[mybatis-3.4.0.jar:3.4.0]
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62) ~[mybatis-3.4.0.jar:3.4.0]

**Comment by cremin-dong** [comment]
无意中发现改成各个单位的复数形式竟然可以通过，而且在DB2中直接执行结果一致
SELECT current timestamp - 1 months + 1 days cycleStartTime FROM sysibm.dual
