### ISSUE TITLE
Oracle脚本中有子查询时SQLUtils.toSQLString抛出类型转换异常

### ISSUE THREAD

**Issue by CONGBULUANGAO** [alibaba/druid#3713]
@wenshao 
sql:` select col1,col2 from table where name='name' and age=(select age from table2);`
错误堆栈
`java.lang.ClassCastException: com.alibaba.druid.sql.visitor.SQLASTOutputVisitor cannot be cast to com.alibaba.druid.sql.dialect.oracle.visitor.OracleASTVisitor
	at com.alibaba.druid.sql.dialect.oracle.ast.stmt.OracleSelect.accept0(OracleSelect.java:58)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:41)
	at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.visit(SQLASTOutputVisitor.java:665)
	at com.alibaba.druid.sql.ast.expr.SQLQueryExpr.accept0(SQLQueryExpr.java:54)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:41)
	at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.visitorBinaryRight(SQLASTOutputVisitor.java:371)
	at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.visit(SQLASTOutputVisitor.java:336)
	at com.alibaba.druid.sql.ast.expr.SQLBinaryOpExpr.accept0(SQLBinaryOpExpr.java:98)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:41)
	at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.visitorBinaryRight(SQLASTOutputVisitor.java:368)
	at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.visit(SQLASTOutputVisitor.java:336)
	at com.alibaba.druid.sql.ast.expr.SQLBinaryOpExpr.accept0(SQLBinaryOpExpr.java:98)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:41)
	at com.alibaba.druid.sql.SQLUtils.toSQLString(SQLUtils.java:89)
	at com.demo.Main.where(Main.java:15)`

**Comment by CONGBULUANGAO** [comment]
> @wenshao
> sql:` select col1,col2 from table where name='name' and age=(select age from table2);`
> 错误堆栈
> `java.lang.ClassCastException: com.alibaba.druid.sql.visitor.SQLASTOutputVisitor cannot be cast to com.alibaba.druid.sql.dialect.oracle.visitor.OracleASTVisitor at com.alibaba.druid.sql.dialect.oracle.ast.stmt.OracleSelect.accept0(OracleSelect.java:58) at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:41) at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.visit(SQLASTOutputVisitor.java:665) at com.alibaba.druid.sql.ast.expr.SQLQueryExpr.accept0(SQLQueryExpr.java:54) at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:41) at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.visitorBinaryRight(SQLASTOutputVisitor.java:371) at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.visit(SQLASTOutputVisitor.java:336) at com.alibaba.druid.sql.ast.expr.SQLBinaryOpExpr.accept0(SQLBinaryOpExpr.java:98) at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:41) at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.visitorBinaryRight(SQLASTOutputVisitor.java:368) at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.visit(SQLASTOutputVisitor.java:336) at com.alibaba.druid.sql.ast.expr.SQLBinaryOpExpr.accept0(SQLBinaryOpExpr.java:98) at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:41) at com.alibaba.druid.sql.SQLUtils.toSQLString(SQLUtils.java:89) at com.demo.Main.where(Main.java:15)`
