### ISSUE TITLE
查询一百万数据的时候，executeQuery的时候报数组下标越界，是要配置什么参数，是因为并发执行的问题吗

### ISSUE THREAD

**Issue by nikexu** [alibaba/druid#3745]
[ERROR] 2020-03-18 14:32:17.906  - [taskAppId=TASK-1266-145730-18939]:[368] - java.lang.ArrayIndexOutOfBoundsException: 5
java.sql.SQLException: java.lang.ArrayIndexOutOfBoundsException: 5
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:810)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2020)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:227)
	at org.apache.dolphinscheduler.server.worker.task.sql.SqlTaskFetchMode.fetchData(SqlTaskFetchMode.java:49)
	at org.apache.dolphinscheduler.server.worker.task.sql.SqlTaskFetchMode.process(SqlTaskFetchMode.java:39)
	at org.apache.dolphinscheduler.server.worker.task.sql.SqlTask.executeFuncAndSql(SqlTask.java:356)
	at org.apache.dolphinscheduler.server.worker.task.sql.SqlTask.handle(SqlTask.java:193)
	at org.apache.dolphinscheduler.server.worker.runner.TaskScheduleThread.run(TaskScheduleThread.java:158)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 5
	at com.mysql.jdbc.Buffer.readLongLong(Buffer.java:370)
	at com.mysql.jdbc.Buffer.readFieldLength(Buffer.java:298)
	at com.mysql.jdbc.Buffer.fastSkipLenString(Buffer.java:164)
	at com.mysql.jdbc.MysqlIO.unpackField(MysqlIO.java:657)
	at com.mysql.jdbc.MysqlIO.getResultSet(MysqlIO.java:412)
	at com.mysql.jdbc.MysqlIO.readResultsForQueryOrUpdate(MysqlIO.java:3070)
	at com.mysql.jdbc.MysqlIO.readAllResults(MysqlIO.java:2338)
	at com.mysql.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:1337)
	at com.mysql.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:787)
	... 12 common frames omitted

**Comment by wenshao** [comment]
升级mysql驱动试试看

**Comment by nikexu** [comment]
> 升级mysql驱动试试看

谢谢
还有就是druid monitor 的一些链接的历史信息是存在内存里的么  ，那会出现内存溢出的风险吗？我是不是每次都要手动的去执行页面上的reset All 才能去解决这个问题，还是说druid自己内部解决了这个问题

**Comment by oszhugc** [comment]
@nikexu 请问下, 升级驱动后, 这个异常还出现过吗
