### ISSUE TITLE
集成hive、mybaits发现sqlSession关闭的时候会报rollback错误

### ISSUE THREAD

**Issue by benxiaohai061** [alibaba/druid#3751]
`java.sql.SQLException: Method not supported
	at org.apache.hive.jdbc.HiveConnection.rollback(HiveConnection.java:1094) ~[hive-jdbc-1.1.0-cdh5.14.0.jar:1.1.0-cdh5.14.0]
	at com.alibaba.druid.filter.FilterChainImpl.connection_rollback(FilterChainImpl.java:714) [druid-1.1.21.jar:1.1.21]
	at com.alibaba.druid.filter.FilterAdapter.connection_rollback(FilterAdapter.java:974) ~[druid-1.1.21.jar:1.1.21]
	at com.alibaba.druid.filter.logging.LogFilter.connection_rollback(LogFilter.java:414) [druid-1.1.21.jar:1.1.21]
	at com.alibaba.druid.filter.FilterChainImpl.connection_rollback(FilterChainImpl.java:709) [druid-1.1.21.jar:1.1.21]
	at com.alibaba.druid.filter.stat.StatFilter.connection_rollback(StatFilter.java:275) [druid-1.1.21.jar:1.1.21]
	at com.alibaba.druid.filter.FilterChainImpl.connection_rollback(FilterChainImpl.java:709) [druid-1.1.21.jar:1.1.21]
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.rollback(ConnectionProxyImpl.java:399) ~[druid-1.1.21.jar:1.1.21]
	at com.alibaba.druid.pool.DruidPooledConnection.rollback(DruidPooledConnection.java:787) [druid-1.1.21.jar:1.1.21]
	at com.alibaba.druid.pool.DruidDataSource.recycle(DruidDataSource.java:1880) ~[druid-1.1.21.jar:1.1.21]
	at com.alibaba.druid.pool.DruidPooledConnection.recycle(DruidPooledConnection.java:324) [druid-1.1.21.jar:1.1.21]
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_recycle(FilterChainImpl.java:5049) [druid-1.1.21.jar:1.1.21]
	at com.alibaba.druid.filter.logging.LogFilter.dataSource_releaseConnection(LogFilter.java:876) [druid-1.1.21.jar:1.1.21]
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_recycle(FilterChainImpl.java:5045) [druid-1.1.21.jar:1.1.21]
	at com.alibaba.druid.filter.stat.StatFilter.dataSource_releaseConnection(StatFilter.java:665) [druid-1.1.21.jar:1.1.21]
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_recycle(FilterChainImpl.java:5045) [druid-1.1.21.jar:1.1.21]
	at com.alibaba.druid.pool.DruidPooledConnection.close(DruidPooledConnection.java:267) [druid-1.1.21.jar:1.1.21]
	at org.apache.ibatis.transaction.jdbc.JdbcTransaction.close(JdbcTransaction.java:92) [mybatis-3.5.3.jar:3.5.3]
	at org.apache.ibatis.executor.BaseExecutor.close(BaseExecutor.java:90) [mybatis-3.5.3.jar:3.5.3]
	at org.apache.ibatis.executor.CachingExecutor.close(CachingExecutor.java:64) [mybatis-3.5.3.jar:3.5.3]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.close(DefaultSqlSession.java:263) [mybatis-3.5.3.jar:3.5.3]`

**Comment by benxiaohai061** [comment]
![image](https://user-images.githubusercontent.com/27911721/77637598-dfdd0880-6f90-11ea-92aa-9e12b3e170e1.png)
