### ISSUE TITLE
SQLStatementParser解析mysql create database报错

### ISSUE THREAD

**Issue by kenlee1988** [alibaba/druid#3752]
sql:
> create DATABASE if not exists schema CHARACTER SET = 'utf8' COLLATE = 'utf8_general_ci';

error:
> 2020-03-27 13:37:58,979 [WARN ][$_NIOREACTOR-1-RW] caught err: com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'CTER SET = 'utf8' COLLATE = 'utf8_g', expect IDENTIFIER, actual LITERAL_CHARS pos 61, line 1, column 55, token LITERAL_CHARS utf8
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:344)
	at com.alibaba.druid.sql.parser.SQLParser.accept(SQLParser.java:352)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseCreateDatabase(MySqlStatementParser.java:4439)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseCreate(MySqlStatementParser.java:430)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:260)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:2853)
	at io.mycat.server.util.SchemaUtil.parseSchema(SchemaUtil.java:23)
	at io.mycat.server.ServerConnection.execute(ServerConnection.java:235)
	at io.mycat.server.ServerQueryHandler.query(ServerQueryHandler.java:169)
	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:376)
	at io.mycat.net.FrontendConnection.query(FrontendConnection.java:396)
	at io.mycat.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:76)
	at io.mycat.net.FrontendConnection.rawHandle(FrontendConnection.java:570)
	at io.mycat.net.FrontendConnection.handle(FrontendConnection.java:552)
	at io.mycat.net.AbstractConnection.onReadData(AbstractConnection.java:327)
	at io.mycat.net.NIOSocketWR.asynRead(NIOSocketWR.java:216)
	at io.mycat.net.AbstractConnection.asynRead(AbstractConnection.java:279)
	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:113)
	at java.lang.Thread.run(Unknown Source)
 (io.mycat.net.NIOReactor$RW:NIOReactor.java:118)

**Comment by kenlee1988** [comment]
版本是1.1.21

**Comment by lizongbo** [comment]
这个sql本身就是错的

mysql里运行结果如下 
[Code: 1064, SQL State: 42000]  (conn=849) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'schema CHARACTER SET = 'utf8' COLLATE = 'utf8_general_ci'' at line 1  [Script position: 467 - 554]
