### ISSUE TITLE
StatFilter中对ADB的update into语法识别失败报错

### ISSUE THREAD

**Issue by liujiankd** [alibaba/druid#3757]
使用druid连接阿里云的ADB，其中ADB的更新语法是update into，当有更新数据时，会报如下错误。推断是druid以mysql协议连接时，只能识别mysql的语法update xxx_table？

ERROR stat.StatFilter - merge sql error, dbType mysql, sql :
update into xxx_table (c1,c2,c3) values (?,?,?)
com.alibaba.druid.sql.parser.ParserException: ERROR. token : INTO, pos : 11
  at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:605)
  at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.primary(MySqlExprParser.java:167)
  at com.alibaba.druid.sql.parser.SQLExprParser.expr(SQLExprParser.java:126)
  at com.alibaba.druid.sql.parser.SQLSelectParser.expr(SQLSelectParser.java:526)
  at com.alibaba.druid.sql.parser.SQLSelectParser.parseTableSourceQueryTableExpr(SQLSelectParser.java:430)
  at com.alibaba.druid.sql.dialect.mysql.parser.MySqlSelectParser.parseTableSource(MySqlSelectParser.java:239)
  at com.alibaba.druid.sql.dialect.mysql.parser.MySqlSelectParser.parseUpdateStatment(MySqlSelectParser.java:286)
  at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseUpdateStatement(MySqlStatementParser.java:246)
  at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:187)
  at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:147)
  at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:142)
  at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:53)
  at com.alibaba.druid.filter.stat.StatFilter.mergeSql(StatFilter.java:145)
  at com.alibaba.druid.filter.stat.StatFilter.createSqlStat(StatFilter.java:630)
  at com.alibaba.druid.filter.stat.StatFilter.statementPrepareAfter(StatFilter.java:305)
  at com.alibaba.druid.filter.FilterEventAdapter.connection_prepareStatement(FilterEventAdapter.java:124)
  at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:448)
  at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.prepareStatement(ConnectionProxyImpl.java:342)
  at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:331)
  at org.apache.ibatis.executor.statement.PreparedStatementHandler.instantiateStatement(PreparedStatementHandler.java:87)
  at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:88)
  at org.apache.ibatis.executor.statement.RoutingStatementHandler.prepare(RoutingStatementHandler.java:59)
  at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:85)
  at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:49)
  at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
  at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
  at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198)
  at sun.reflect.GeneratedMethodAccessor399.invoke(Unknown Source)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:434)
  at com.sun.proxy.$Proxy231.update(Unknown Source)
  at org.mybatis.spring.SqlSessionTemplate.update(SqlSessionTemplate.java:295)
  at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:62)
  at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:53)
  at com.sun.proxy.$Proxy232.update(Unknown Source)

**Comment by liujiankd** [comment]
在配置中注释掉filters之后，还是会类似如上报错，貌似并不能达到”不需要任何统计监控“的效果
