### ISSUE TITLE
syntax error, error in :'long varbinary ...'

### ISSUE THREAD

**Issue by constanine** [alibaba/druid#3773]
建表语句
> CREATE TABLE `QRTZ_JOB_DETAILS` (
    `SCHED_NAME` VARCHAR(120),
    `JOB_NAME` VARCHAR(200),
    `JOB_GROUP` VARCHAR(200),
    `DESCRIPTION` VARCHAR(250),
    `JOB_CLASS_NAME` VARCHAR(250),
    `IS_DURABLE` VARCHAR(1),
    `IS_NONCONCURRENT` VARCHAR(1),
    `IS_UPDATE_DATA` VARCHAR(1),
    `REQUESTS_RECOVERY` VARCHAR(1),
    `JOB_DATA` LONG VARBINARY,
    `Slock` INT,
    PRIMARY KEY (`SCHED_NAME` , `JOB_NAME` , `JOB_GROUP`)
)  ENGINE=INNODB

当出现`column`类型为`long varbinary`时,会报错:
`syntax error, error in :'long varbinary...' `
报错`stackTrace`:
> Caused by: com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'long varbinary ,`Slock` int , PRIMA', expect RPAREN, actual IDENTIFIER pos 312, line 1, column 303, token IDENTIFIER varbinary
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:284)
	at com.alibaba.druid.sql.parser.SQLParser.accept(SQLParser.java:292)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlCreateTableParser.parseCreateTable(MySqlCreateTableParser.java:268)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseCreate(MySqlStatementParser.java:243)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:161)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:83)
	at com.alibaba.druid.wall.WallProvider.checkInternal(WallProvider.java:624)
	at com.alibaba.druid.wall.WallProvider.check(WallProvider.java:578)
	at com.alibaba.druid.wall.WallFilter.checkInternal(WallFilter.java:785)
	... 30 common frames omitted

**Comment by constanine** [comment]
补充下,这个报错是在`spring.datasource.druid.filter.wall.enabled=true`的情况下,才会出现

**Comment by thinkbase** [comment]
我在使用 1.2.18 版本的时候同样出这个错误，情况如下：

----


序号 | SQL | 样本 | violationMessage | 执行数 | 读取行数 | 更新行数
-- | -- | -- | -- | -- | -- | --
1 | create table `QRTZ_JOB_DETAILS` (`SCHED_NAME` varchar(120) ,`JOB_NAME` varchar(200) ,`JOB_GROUP` varchar(200) ,`DESCRIPTION` varchar(250) ,`JOB_CLASS_NAME` varchar(250) ,`IS_DURABLE` varchar(1) ,`IS_NONCONCURRENT` varchar(1) ,`IS_UPDATE_DATA` varchar(1) ,`REQUESTS_RECOVERY` varchar(1) ,`JOB_DATA` long varbinary ,`Slock` int , PRIMARY KEY(`SCHED_NAME`,`JOB_NAME`,`JOB_GROUP`) )ENGINE=INNODB |   | syntax error: syntax error, error in :'long varbinary ,`Slock` int , PRIMA', expect ), actual null, pos 312, line 1, column 304, token IDENTIFIER varbinary | 2 |
