### ISSUE TITLE
Postgresql 使用INSERT INTO *** SELECT *** FROM ** 被Wall认为是SQL注入拦截

### ISSUE THREAD

**Issue by NianDUI** [alibaba/druid#3783]
org.springframework.jdbc.UncategorizedSQLException: 
### Error updating database.  Cause: java.sql.SQLException: sql injection violation, syntax error: com.alibaba.druid.sql.ast.expr.SQLMethodInvokeExpr cannot be cast to com.alibaba.druid.sql.ast.expr.SQLQueryExpr : 
	INSERT INTO "***"(***)
        SELECT ?,ROW_NUMBER() OVER(),REPLACE(***),?,1,1,"FD_CITY","FD_TEMPLATEID"
        FROM (
            SELECT a."FD_MSISDN",ah."FD_CITY"
            FROM ***
            WHERE
                a."***" = ?
        ) a,(
            VALUES
              
                (?,?)
             , 
                (?,?)
             , 
                (?,?)
             
        ) b("FD_LINECMD","FD_TEMPLATEID");
### SQL: 
INSERT INTO "***"(***)         SELECT ?,ROW_NUMBER() OVER(),REPLACE(***),?,1,1,"FD_CITY","FD_TEMPLATEID"         FROM (             SELECT a."FD_MSISDN",ah."FD_CITY"             FROM ***             WHERE                 a."***" = ?             ) a,(             VALUES                                (?,?)              ,                  (?,?)              ,                  (?,?)                       ) b("FD_LINECMD","FD_TEMPLATEID");
### Cause: java.sql.SQLException: sql injection violation, syntax error: com.alibaba.druid.sql.ast.expr.SQLMethodInvokeExpr cannot be cast to com.alibaba.druid.sql.ast.expr.SQLQueryExpr : 
	INSERT INTO "***"(***)
        SELECT ?,ROW_NUMBER() OVER(),REPLACE(***),?,1,1,"FD_CITY","FD_TEMPLATEID"
        FROM (
            SELECT a."FD_MSISDN",ah."FD_CITY"
            FROM ***
            WHERE
                a."***" = ?
        ) a,(
            VALUES
              
                (?,?)
             , 
                (?,?)
             , 
                (?,?)
             
        ) b("FD_LINECMD","FD_TEMPLATEID");
; uncategorized SQLException; SQL state [null]; error code [0]; sql injection violation, syntax error: com.alibaba.druid.sql.ast.expr.SQLMethodInvokeExpr cannot be cast to com.alibaba.druid.sql.ast.expr.SQLQueryExpr : 
		INSERT INTO "***"(***)
        SELECT ?,ROW_NUMBER() OVER(),REPLACE(***),?,1,1,"FD_CITY","FD_TEMPLATEID"
        FROM (
            SELECT a."FD_MSISDN",ah."FD_CITY"
            FROM ***
            WHERE
                a."***" = ?
        ) a,(
            VALUES
              
                (?,?)
             , 
                (?,?)
             , 
                (?,?)
             
        ) b("FD_LINECMD","FD_TEMPLATEID");; 
nested exception is java.sql.SQLException: sql injection violation, syntax error: com.alibaba.druid.sql.ast.expr.SQLMethodInvokeExpr cannot be cast to com.alibaba.druid.sql.ast.expr.SQLQueryExpr : 
	INSERT INTO "***"(***)
        SELECT ?,ROW_NUMBER() OVER(),REPLACE(***),?,1,1,"FD_CITY","FD_TEMPLATEID"
        FROM (
            SELECT a."FD_MSISDN",ah."FD_CITY"
            FROM ***
            WHERE
                a."***" = ?
        ) a,(
            VALUES
              
                (?,?)
             , 
                (?,?)
             , 
                (?,?)
             
        ) b("FD_LINECMD","FD_TEMPLATEID");
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:89)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy139.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:278)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:62)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:58)
	at com.sun.proxy.$Proxy194.generateZXIMSHSSInst(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.__invoke(DelegatingMethodAccessorImpl.java:43)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:45009)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:45012)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy195.generateZXIMSHSSInst(Unknown Source)
	at com.synqnc.service.ims.impl.TDOPENHSSROAMServiceImpl.lambda$MAKE_OPENHSS_ROAM_new$26(TDOPENHSSROAMServiceImpl.java:876)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: sql injection violation, syntax error: com.alibaba.druid.sql.ast.expr.SQLMethodInvokeExpr cannot be cast to com.alibaba.druid.sql.ast.expr.SQLQueryExpr : 
	INSERT INTO "***"(***)
        SELECT ?,ROW_NUMBER() OVER(),REPLACE(***),?,1,1,"FD_CITY","FD_TEMPLATEID"
        FROM (
            SELECT a."FD_MSISDN",ah."FD_CITY"
            FROM ***
            WHERE
                a."***" = ?
        ) a,(
            VALUES
              
                (?,?)
             , 
                (?,?)
             , 
                (?,?)
             
        ) b("FD_LINECMD","FD_TEMPLATEID");
	at com.alibaba.druid.wall.WallFilter.checkInternal(WallFilter.java:806)
	at com.alibaba.druid.wall.WallFilter.connection_prepareStatement(WallFilter.java:259)
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:568)
	at com.alibaba.druid.filter.FilterAdapter.connection_prepareStatement(FilterAdapter.java:930)
	at com.alibaba.druid.filter.FilterEventAdapter.connection_prepareStatement(FilterEventAdapter.java:122)
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:568)
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.prepareStatement(ConnectionProxyImpl.java:341)
	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:350)
	at sun.reflect.GeneratedMethodAccessor252.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.__invoke(DelegatingMethodAccessorImpl.java:43)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:45009)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:45012)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.ConnectionLogger.invoke(ConnectionLogger.java:55)
	at com.sun.proxy.$Proxy286.prepareStatement(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.instantiateStatement(PreparedStatementHandler.java:86)
	at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:88)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.prepare(RoutingStatementHandler.java:59)
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:86)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:49)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.__invoke(DelegatingMethodAccessorImpl.java:43)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:45009)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:45012)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
	at com.sun.proxy.$Proxy285.update(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.__invoke(DelegatingMethodAccessorImpl.java:43)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:45009)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:45012)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 20 more
Caused by: java.lang.ClassCastException: com.alibaba.druid.sql.ast.expr.SQLMethodInvokeExpr cannot be cast to com.alibaba.druid.sql.ast.expr.SQLQueryExpr
	at com.alibaba.druid.sql.dialect.postgresql.parser.PGSQLStatementParser.parseInsert(PGSQLStatementParser.java:170)
	at com.alibaba.druid.sql.dialect.postgresql.parser.PGSQLStatementParser.parseInsert(PGSQLStatementParser.java:57)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:266)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:182)
	at com.alibaba.druid.wall.WallProvider.checkInternal(WallProvider.java:624)
	at com.alibaba.druid.wall.WallProvider.check(WallProvider.java:578)
	at com.alibaba.druid.wall.WallFilter.checkInternal(WallFilter.java:793)
	... 58 more

**Comment by blankhang** [comment]
我也遇到了..类型的 问题...
sql中直接执行 正常
代码中就报
```java
Caused by: com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'   ) view
        LEFT JOIN compens', expect VIEW, actual VIEW pos 977, line 33, column 11, token VIEW
```
发现 好像不让用`view` 的别名关键字 改名后OK

**Comment by NianDUI** [comment]
> 我也遇到了..类型的 问题...
> sql中直接执行 正常
> 代码中就报
> 
> ```java
> Caused by: com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'   ) view
>         LEFT JOIN compens', expect VIEW, actual VIEW pos 977, line 33, column 11, token VIEW
> ```
> 
> 发现 好像不让用`view` 的别名关键字 改名后OK

我的SQL里面也没有使用view关键字。
