### ISSUE TITLE
dump文件执行报错

### ISSUE THREAD

**Issue by yydzxz** [alibaba/druid#3804]
mysql dump命令生成的sql
```
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */
```
报错日志
```
[STDOUT] 2020-05-16 19:05:18.752 ERROR com.alibaba.druid.filter.stat.StatFilter [] [restartedMain] [] - merge sql error, dbType mysql, druid-1.1.22, sql : /*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */
java.lang.StringIndexOutOfBoundsException: String index out of range: 64
	at java.lang.String.charAt(String.java:658)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlLexer.skipFirstHintsOrMultiCommentAndNextToken(MySqlLexer.java:432)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.<init>(MySqlExprParser.java:136)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.<init>(MySqlStatementParser.java:254)
	at com.alibaba.druid.sql.parser.SQLParserUtils.createSQLStatementParser(SQLParserUtils.java:84)
	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:92)
	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:81)
	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:54)
	at com.alibaba.druid.filter.stat.StatFilter.mergeSql(StatFilter.java:147)
	at com.alibaba.druid.filter.stat.StatFilter.createSqlStat(StatFilter.java:648)
	at com.alibaba.druid.filter.stat.StatFilter.internalBeforeStatementExecute(StatFilter.java:403)
	at com.alibaba.druid.filter.stat.StatFilter.statementExecuteBefore(StatFilter.java:351)
	at com.alibaba.druid.filter.FilterEventAdapter.statement_execute(FilterEventAdapter.java:185)
	at com.alibaba.druid.filter.FilterChainImpl.statement_execute(FilterChainImpl.java:3008)
	at com.alibaba.druid.wall.WallFilter.statement_execute(WallFilter.java:421)
	at com.alibaba.druid.filter.FilterChainImpl.statement_execute(FilterChainImpl.java:3008)
	at com.alibaba.druid.proxy.jdbc.StatementProxyImpl.execute(StatementProxyImpl.java:147)
	at com.alibaba.druid.pool.DruidPooledStatement.execute(DruidPooledStatement.java:633)
	at org.flywaydb.core.internal.util.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:265)
	at org.flywaydb.core.internal.database.StandardSqlStatement.execute(StandardSqlStatement.java:41)
	at org.flywaydb.core.internal.database.ExecutableSqlScript.execute(ExecutableSqlScript.java:128)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:75)
	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:363)
	at org.flywaydb.core.internal.command.DbMigrate.access$400(DbMigrate.java:52)
	at org.flywaydb.core.internal.command.DbMigrate$5.call(DbMigrate.java:297)
	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:75)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:294)
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:259)
	at org.flywaydb.core.internal.command.DbMigrate.access$300(DbMigrate.java:52)
	at org.flywaydb.core.internal.command.DbMigrate$4.call(DbMigrate.java:179)
	at org.flywaydb.core.internal.command.DbMigrate$4.call(DbMigrate.java:176)
	at org.flywaydb.core.internal.database.mysql.MySQLNamedLockTemplate.execute(MySQLNamedLockTemplate.java:60)
	at org.flywaydb.core.internal.database.mysql.MySQLConnection.lock(MySQLConnection.java:78)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:148)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:176)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:145)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1206)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1168)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1655)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1168)
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1753)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1690)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:573)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:304)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:759)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:548)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:386)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1242)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1230)
	at cn.ce.appstore.AppStoreServiceApplication.run(AppStoreServiceApplication.java:33)
	at cn.ce.appstore.AppStoreServiceApplication.main(AppStoreServiceApplication.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
```

druid版本
```xml
<dependency>
    <groupId>com.alibaba</groupId>
    <artifactId>druid-spring-boot-starter</artifactId>
    <version>1.1.22</version>
</dependency>
```

debug到相应代码
```java
com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser
if (c0 == '/' && c1 == '*' && isEnabled(SQLParserFeature.OptimizedForParameterized)) {
     MySqlLexer mySqlLexer = (MySqlLexer) lexer;
     mySqlLexer.skipFirstHintsOrMultiCommentAndNextToken();
     return;
}
```
看样子`/*!`的处理和`/*`是不一样的, 这个地方把`/*!`当成`/*`处理了

**Comment by yydzxz** [comment]
由于源代码中这里没有任何注释,所以我不太确定这里是干嘛的,所以不知道该如何修改
