### ISSUE TITLE
解析 SQL 错误，添加 where 条件 中，原条件中有in的话会报错

### ISSUE THREAD

**Issue by KANLON** [alibaba/druid#3839]
解析 SQL 错误。给 Mysql 的 SQL 语句 添加 in 条件，如果 原条件中有该字段 in 条件的话会报错，错误例子代码如下：

```
import com.alibaba.druid.sql.SQLUtils;
import com.alibaba.druid.sql.ast.SQLExpr;
import com.alibaba.druid.sql.ast.SQLStatement;
import com.alibaba.druid.sql.ast.statement.SQLSelectQuery;
import com.alibaba.druid.sql.ast.statement.SQLSelectQueryBlock;
import com.alibaba.druid.sql.ast.statement.SQLSelectStatement;
import com.alibaba.druid.util.JdbcConstants;
import org.junit.Test;

import java.util.List;


    /**
     * 测试原条件有in，和添加in 条件
     */
    @Test
    public void testWhereInCondition() {
        String sql1 = "select a , b ,c from test where a in ('中')";
        List<SQLStatement> sqlStatements = SQLUtils.parseStatements(sql1, JdbcConstants.MYSQL);
        SQLStatement sqlStatement = sqlStatements.iterator().next();
        SQLSelectQuery query = ((SQLSelectStatement) sqlStatement).getSelect().getQuery();
        SQLSelectQueryBlock queryBlock = (SQLSelectQueryBlock) query;
        SQLExpr sqlExpr1 = SQLUtils.toSQLExpr("a = '国'");
        // 这里会报错
        SQLExpr sqlExpr2 = SQLUtils.toSQLExpr("a in ('国')");
        queryBlock.addWhere(sqlExpr1);
        queryBlock.addWhere(sqlExpr2);
        System.out.println(SQLUtils.toMySqlString(queryBlock));
    }
```

报错信息

```
java.lang.ClassCastException: com.alibaba.druid.sql.ast.expr.SQLCharExpr cannot be cast to java.lang.Comparable

	at java.util.TreeMap.compare(TreeMap.java:1294)
	at java.util.TreeMap.put(TreeMap.java:538)
	at java.util.TreeSet.add(TreeSet.java:255)
	at java.util.AbstractCollection.addAll(AbstractCollection.java:344)
	at java.util.TreeSet.addAll(TreeSet.java:312)
	at com.alibaba.druid.sql.ast.statement.SQLSelectQueryBlock.addWhere(SQLSelectQueryBlock.java:169)
	at com.hiido.SqlParserTest.testWhereInCondition(SqlParserTest.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:64)
```

依赖的 druid 的 版本
```
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid-spring-boot-starter</artifactId>
            <version>1.1.22</version>
        </dependency>

```

**Comment by lizongbo** [comment]
最新版本已经解析正常。
