### ISSUE TITLE
Druid解析SQL出现错误：using nextval('jv_snapshot_pk_seq') * 100 for insert SQL

### ISSUE THREAD

**Issue by mac8088** [alibaba/druid#3840]
出现此问题的技术条件：
基于Seata1.2.0 + Druid 1.12 or Druid 1.22 + Javers 5.8.13 + PostgreSQL 11.6

目前判断是：Seata所仰仗的Druid是无法处理类似 Insert SQL:

INSERT INTO jv_snapshot ( type, global_id_fk, commit_fk, version, state, changed_properties, managed_type, snapshot_pk ) VALUES  ( ?,?,?,?,?,?,?,nextval('jv_snapshot_pk_seq') * 100 )

上面的SQL语句，打开一个SQL client 通过手工调整数据的方式，是可以被成功执行的。

2020-06-20 16:20:11.466 ERROR 5304 --- [  XNIO-1 task-2] o.z.problem.spring.common.AdviceTraits   : Internal Server Error

org.javers.common.exception.JaversException: SQL_EXCEPTION: io.seata.sqlparser.SQLParsingException: Unknown SQLExpr: class com.alibaba.druid.sql.ast.expr.SQLBinaryOpExpr nextval('jv_snapshot_pk_seq') * 100
while executing sql: INSERT INTO jv_snapshot ( type, global_id_fk, commit_fk, version, state, changed_properties, managed_type, snapshot_pk ) VALUES  ( ?,?,?,?,?,?,?,nextval('jv_snapshot_pk_seq') * 100 )
	at org.javers.repository.sql.session.PreparedStatementExecutor.wrapExceptionAndCall(PreparedStatementExecutor.java:120)
	at org.javers.repository.sql.session.PreparedStatementExecutor.runVoidSql(PreparedStatementExecutor.java:110)
	at org.javers.repository.sql.session.PreparedStatementExecutor.execute(PreparedStatementExecutor.java:39)
	at org.javers.repository.sql.session.Session.execute(Session.java:105)
	at org.javers.repository.sql.session.Session.executeInsert(Session.java:75)
	at org.javers.repository.sql.session.InsertBuilder.execute(InsertBuilder.java:58)
	at org.javers.repository.sql.repositories.CdoSnapshotRepository.save(CdoSnapshotRepository.java:37)
	at org.javers.repository.sql.JaversSqlRepository.persist(JaversSqlRepository.java:87)
	at org.javers.repository.api.JaversExtendedRepository.persist(JaversExtendedRepository.java:154)
	at org.javers.core.JaversCore.persist(JaversCore.java:105)
	at org.javers.core.JaversCore.commit(JaversCore.java:86)
	at org.javers.spring.jpa.JaversTransactionalDecorator.commit(JaversTransactionalDecorator.java:82)
	at org.javers.spring.jpa.JaversTransactionalDecorator$$FastClassBySpringCGLIB$$acb40bd0.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at org.javers.spring.jpa.JaversTransactionalDecorator$$EnhancerBySpringCGLIB$$1830d8ca.commit(<generated>)
	at org.javers.spring.auditable.aspect.JaversCommitAdvice.commitObject(JaversCommitAdvice.java:81)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085)
	at org.javers.spring.auditable.aspect.springdata.AbstractSpringAuditableRepositoryAspect.lambda$onSave$0(AbstractSpringAuditableRepositoryAspect.java:28)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)

**Comment by mac8088** [comment]
类似的SIR给Seata: https://github.com/seata/seata/issues/2821

**Comment by mac8088** [comment]
this is seata issue, so close it
