### ISSUE TITLE
当数据库地址配错时，死循环狂刷日志，版本：1.1.22

### ISSUE THREAD

**Issue by lujijiang** [alibaba/druid#3854]
2020-06-28 16:42:01.042 ERROR com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread:2781 - create connection SQLException, url: jdbc:mysql://mysqldb.saasxx:3306/center_data?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf8&useFastDateParsing=false&pinGlobalTxToPhysicalConnection=true&serverTimezone=Hongkong, errorCode 0, state 08S01 com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) ~[mysql-connector-java-8.0.20.jar:8.0.20]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[mysql-connector-java-8.0.20.jar:8.0.20]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:836) ~[mysql-connector-java-8.0.20.jar:8.0.20]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456) ~[mysql-connector-java-8.0.20.jar:8.0.20]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.20.jar:8.0.20]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:197) ~[mysql-connector-java-8.0.20.jar:8.0.20]
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:156) ~[druid-1.1.22.jar:1.1.22]
	at com.alibaba.druid.filter.FilterAdapter.connection_connect(FilterAdapter.java:787) ~[druid-1.1.22.jar:1.1.22]
	at com.alibaba.druid.filter.FilterEventAdapter.connection_connect(FilterEventAdapter.java:38) ~[druid-1.1.22.jar:1.1.22]
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150) ~[druid-1.1.22.jar:1.1.22]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1646) ~[druid-1.1.22.jar:1.1.22]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1710) ~[druid-1.1.22.jar:1.1.22]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2779) [druid-1.1.22.jar:1.1.22]
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.GeneratedConstructorAccessor107.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_251]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_251]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.20.jar:8.0.20]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.20.jar:8.0.20]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.20.jar:8.0.20]
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167) ~[mysql-connector-java-8.0.20.jar:8.0.20]
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:91) ~[mysql-connector-java-8.0.20.jar:8.0.20]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:144) ~[mysql-connector-java-8.0.20.jar:8.0.20]
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:956) ~[mysql-connector-java-8.0.20.jar:8.0.20]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:826) ~[mysql-connector-java-8.0.20.jar:8.0.20]
	... 10 more
Caused by: java.net.UnknownHostException: mysqldb.saasxx
	at java.net.InetAddress.getAllByName0(InetAddress.java:1281) ~[?:1.8.0_251]
	at java.net.InetAddress.getAllByName(InetAddress.java:1193) ~[?:1.8.0_251]
	at java.net.InetAddress.getAllByName(InetAddress.java:1127) ~[?:1.8.0_251]
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:132) ~[mysql-connector-java-8.0.20.jar:8.0.20]
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:65) ~[mysql-connector-java-8.0.20.jar:8.0.20]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:144) ~[mysql-connector-java-8.0.20.jar:8.0.20]
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:956) ~[mysql-connector-java-8.0.20.jar:8.0.20]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:826) ~[mysql-connector-java-8.0.20.jar:8.0.20]
	... 10 more

**Comment by lujijiang** [comment]
数据源配置如下：
```java
Slf4jLogFilter slf4jLogFilter = new Slf4jLogFilter();
            slf4jLogFilter.setStatementCreateAfterLogEnabled(false);
            slf4jLogFilter.setStatementCloseAfterLogEnabled(false);
            slf4jLogFilter.setStatementExecuteAfterLogEnabled(false);
            slf4jLogFilter.setStatementExecuteQueryAfterLogEnabled(false);
            slf4jLogFilter.setStatementExecuteUpdateAfterLogEnabled(false);
            slf4jLogFilter.setStatementExecuteBatchAfterLogEnabled(false);
            slf4jLogFilter.setStatementParameterSetLogEnabled(false);
            slf4jLogFilter.setStatementPrepareAfterLogEnabled(false);
            slf4jLogFilter.setResultSetLogEnabled(false);

            slf4jLogFilter.setStatementExecutableSqlLogEnable(true);
            DruidDataSource dataSource = new DruidDataSource();
            dataSource.setUrl(source.getJdbcUrl());
            dataSource.setUsername(source.getUsername());
            dataSource.setPassword(source.getPassword());
            dataSource.setMaxActive(source.getMaxActive());
            dataSource.setTestWhileIdle(true);
            dataSource.setBreakAfterAcquireFailure(true);
            dataSource.setProxyFilters(Arrays.asList(slf4jLogFilter));
```

**Comment by shenshaoming** [comment]
这个似乎也不算个bug，就是这么设计的吧，连接不上说明配置有问题

**Comment by chenh930330** [comment]
我觉得设置重连次数connectionErrorRetryAttempts和重连校验间隔时间timeBetweenConnectErrorMillis

**Comment by 78Coder** [comment]
> 我觉得设置重连次数connectionErrorRetryAttempts和重连校验间隔时间timeBetweenConnectErrorMillis

大哥  太牛了 冲日志的问题我找了好几天解决方案 你这个可行

**Comment by xiaopujun** [comment]
如果是动态创建数据源的场景，而且由于是动态创建的，整个应用不会停。死循环刷日志直接导致CPU拉满。 @shenshaoming

**Comment by wxy2015** [comment]
> 我觉得设置重连次数connectionErrorRetryAttempts和重连校验间隔时间timeBetweenConnectErrorMillis

同1.2.22版本，同样的问题，最关键的是设置的timeBetweenConnectErrorMillis不生效，更新到最新版1.2.25同样配置不生效。
配置如下：
datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      druid:
        max-wait: 2000
        connection-error-retry-attempts: 1
        test-while-idle: false
        time-between-connect-error-millis: 300000
