### ISSUE TITLE
druid 多数据源 整合 Atomikos 事务高版本mysql启动报错

### ISSUE THREAD

**Issue by blankhang** [alibaba/druid#3880]
druid version 1.1.23

如果用springboot 自带的高版本则启动报错
mysql 必须降级到 8.0.11 版本才能正常启动
麻烦修复下

```java
2020-07-22 17:56:40.942  WARN 10136 --- [           main] c.a.jdbc.AtomikosXAConnectionFactory     : XAConnectionFactory: failed to create pooled connection - DBMS down or unreachable?

java.sql.SQLFeatureNotSupportedException: null
	at com.alibaba.druid.util.MySqlUtils.createXAConnection(MySqlUtils.java:179)
	at com.alibaba.druid.pool.xa.DruidXADataSource.createPhysicalXAConnection(DruidXADataSource.java:73)
	at com.alibaba.druid.pool.xa.DruidXADataSource.getXAConnection(DruidXADataSource.java:49)
	at com.atomikos.jdbc.AtomikosXAConnectionFactory.createPooledConnection(AtomikosXAConnectionFactory.java:43)
	at com.atomikos.datasource.pool.ConnectionPool.createPooledConnection(ConnectionPool.java:98)
	at com.atomikos.datasource.pool.ConnectionPool.growPool(ConnectionPool.java:205)
	at com.atomikos.datasource.pool.ConnectionPool.retrieveFirstAvailableConnectionAndGrowPoolIfNecessary(ConnectionPool.java:155)
	at com.atomikos.datasource.pool.ConnectionPool.findOrWaitForAnAvailableConnection(ConnectionPool.java:141)
	at com.atomikos.datasource.pool.ConnectionPool.borrowConnection(ConnectionPool.java:132)
	at com.atomikos.jdbc.AbstractDataSourceBean.getConnection(AbstractDataSourceBean.java:346)
	at org.springframework.scheduling.quartz.LocalDataSourceJobStore$2.getConnection(LocalDataSourceJobStore.java:135)
	at org.quartz.utils.DBConnectionManager.getConnection(DBConnectionManager.java:108)
	at org.quartz.impl.jdbcjobstore.JobStoreCMT.getNonManagedTXConnection(JobStoreCMT.java:165)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doCheckin(JobStoreSupport.java:3322)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.manage(JobStoreSupport.java:3935)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.initialize(JobStoreSupport.java:3920)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.schedulerStarted(JobStoreSupport.java:692)
	at org.quartz.core.QuartzScheduler.start(QuartzScheduler.java:539)
	at org.quartz.impl.StdScheduler.start(StdScheduler.java:142)
	at org.springframework.scheduling.quartz.SchedulerFactoryBean.startScheduler(SchedulerFactoryBean.java:728)
	at org.springframework.scheduling.quartz.SchedulerFactoryBean.start(SchedulerFactoryBean.java:800)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:894)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
```

**Comment by blankhang** [comment]
https://dev.mysql.com/doc/relnotes/connector-j/8.0/en/

Changes in MySQL Connector/J 8.0.21 (2020-07-13, General Availability)
Changes in MySQL Connector/J 8.0.20 (2020-04-27, General Availability)
Changes in MySQL Connector/J 8.0.19 (2020-01-13, General Availability)
Changes in MySQL Connector/J 8.0.18 (2019-10-14, General Availability)
Changes in MySQL Connector/J 8.0.17 (2019-07-22, General Availability)
Changes in MySQL Connector/J 8.0.16 (2019-04-25, General Availability)
Changes in MySQL Connector/J 8.0.15 (2019-02-01, General Availability)
Changes in MySQL Connector/J 8.0.14 (2019-01-21, General Availability)
Changes in MySQL Connector/J 8.0.13 (2018-10-22, General Availability)
Changes in MySQL Connector/J 8.0.12 (2018-07-27, General Availability)
Changes in MySQL Connector/J 8.0.11 (2018-04-19, General Availability)

**Comment by blankhang** [comment]
https://dev.mysql.com/doc/relnotes/connector-j/8.0/en/

https://github.com/mysql/mysql-connector-j/blob/release/8.0/CHANGES

**Comment by xzf520** [comment]
这是降mysql版本还是jar包版本
