### ISSUE TITLE
在打开PSCache时偶现Closed Statement错误

### ISSUE THREAD

**Issue by linweiyu** [alibaba/druid#3911]
druid版本为1.1.21
配置为：
                <property name="maxActive" value="50"/>
                <property name="initialSize" value="5"/>
                <property name="minIdle" value="30"/>
                <property name="maxWait" value="10000"/>
                <property name="minEvictableIdleTimeMillis" value="90000"/>
                <property name="testWhileIdle" value="true"/>
                <property name="validationQuery" value="select 1 from dual"/>
                <property name="keepAlive" value="true"/>
                <property name="poolPreparedStatements" value="true"/>
                <property name="maxPoolPreparedStatementPerConnectionSize" value="10"/>
                <property name="fastFail" value="true"/>
驱动版本为：
<dependency>
            <groupId>com.oracle</groupId>
            <artifactId>ojdbc6</artifactId>
            <version>11.2.0.3</version>
            <scope>runtime</scope>
</dependency>
报错信息：
### The error occurred while handling results

**Comment by wenshao** [comment]
数据库修改过表结构

**Comment by treest** [comment]
我们目前也遇到了这个问题，500并发情况下，打开PSCache，就会报错：
![image](https://user-images.githubusercontent.com/7970760/129691627-d9b25934-8378-4c0b-b46e-a0a337b2e6b2.png)
14:15:29,069 ERROR - exitImplicitCacheToClose error
java.sql.SQLRecoverableException: Closed Statement
	at oracle.jdbc.driver.OracleClosedStatement.exitImplicitCacheToClose(OracleClosedStatement.java:4687)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.exitImplicitCacheToClose(OraclePreparedStatementWrapper.java:1623)
	at com.alibaba.druid.util.OracleUtils.exitImplicitCacheToClose(OracleUtils.java:87)
	at com.alibaba.druid.pool.PreparedStatementPool.closeRemovedStatement(PreparedStatementPool.java:170)
	at com.alibaba.druid.pool.PreparedStatementPool.clear(PreparedStatementPool.java:138)
	at com.alibaba.druid.pool.DruidConnectionHolder.clearStatementCache(DruidConnectionHolder.java:255)
	at com.alibaba.druid.pool.DruidPooledConnection.disable(DruidPooledConnection.java:223)
	at com.alibaba.druid.pool.DruidDataSource.handleFatalError(DruidDataSource.java:1818)
	at com.alibaba.druid.pool.DruidDataSource.handleConnectionException(DruidDataSource.java:1780)
	at com.alibaba.druid.pool.DruidPooledConnection.handleException(DruidPooledConnection.java:137)
	at com.alibaba.druid.pool.DruidPooledStatement.checkException(DruidPooledStatement.java:81)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:240)

网上也查了一下资料，刚开始怀疑是ojdbc驱动问题，我们用的Oracle18c，更换了匹配的ojdbc8之后，问题依然出现。
然后我又怀疑是druid版本问题，然后从1.1.22升级到1.2.6，问题依旧。
之后就考虑到是不是PS缓存问题，就把2个缓存参数注释掉，这时候500并发情况下，问题消失了。
<druid>
        <prop name="maxWait">10000</prop>
        <prop name="keepAlive">true</prop>
        <prop name="timeBetweenEvictionRunsMillis">18800</prop>
        <prop name="testOnBorrow">true</prop>
        <prop name="filters">stat</prop>
        <prop name="initialSize">20</prop>    
        <prop name="maxActive">500</prop>    
        <prop name="minIdle">20</prop>    
        
        <prop name="druidServlet.allow"></prop>
        <prop name="validationQuery">SELECT 1 FROM DUAL</prop>
        <prop name="testWhileIdle">true</prop>
        <prop name="timeBetweenEvictionRunsMillis">60000</prop>
    </druid>

然后我又测试了druid1.1.22 以及ojdbc6，发现只要注释掉这两个参数，500并发都没有问题。
所以目前来看大概率还是这两个参数导致了高并发下的这种问题。
我们的处理方式暂时是注释掉了PS缓存。
希望我的补充能有所帮助。

**Comment by xmt1139057136** [comment]
> 我们目前也遇到了这个问题，500并发情况下，打开PSCache，就会报错：
> ![image](https://user-images.githubusercontent.com/7970760/129691627-d9b25934-8378-4c0b-b46e-a0a337b2e6b2.png)
> 14:15:29,069 ERROR - exitImplicitCacheToClose error
> java.sql.SQLRecoverableException: Closed Statement
> at oracle.jdbc.driver.OracleClosedStatement.exitImplicitCacheToClose(OracleClosedStatement.java:4687)
> at oracle.jdbc.driver.OraclePreparedStatementWrapper.exitImplicitCacheToClose(OraclePreparedStatementWrapper.java:1623)
> at com.alibaba.druid.util.OracleUtils.exitImplicitCacheToClose(OracleUtils.java:87)
> at com.alibaba.druid.pool.PreparedStatementPool.closeRemovedStatement(PreparedStatementPool.java:170)
> at com.alibaba.druid.pool.PreparedStatementPool.clear(PreparedStatementPool.java:138)
> at com.alibaba.druid.pool.DruidConnectionHolder.clearStatementCache(DruidConnectionHolder.java:255)
> at com.alibaba.druid.pool.DruidPooledConnection.disable(DruidPooledConnection.java:223)
> at com.alibaba.druid.pool.DruidDataSource.handleFatalError(DruidDataSource.java:1818)
> at com.alibaba.druid.pool.DruidDataSource.handleConnectionException(DruidDataSource.java:1780)
> at com.alibaba.druid.pool.DruidPooledConnection.handleException(DruidPooledConnection.java:137)
> at com.alibaba.druid.pool.DruidPooledStatement.checkException(DruidPooledStatement.java:81)
> at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:240)
> 
> 网上也查了一下资料，刚开始怀疑是ojdbc驱动问题，我们用的Oracle18c，更换了匹配的ojdbc8之后，问题依然出现。
> 然后我又怀疑是druid版本问题，然后从1.1.22升级到1.2.6，问题依旧。
> 之后就考虑到是不是PS缓存问题，就把2个缓存参数注释掉，这时候500并发情况下，问题消失了。
> 
> 10000
> true
> 18800
> true
> stat
> 20
> 500
> 20
> 
> 
> SELECT 1 FROM DUAL
> true
> 60000
> 然后我又测试了druid1.1.22 以及ojdbc6，发现只要注释掉这两个参数，500并发都没有问题。
> 所以目前来看大概率还是这两个参数导致了高并发下的这种问题。
> 我们的处理方式暂时是注释掉了PS缓存。
> 希望我的补充能有所帮助。

能否描述一下，具体是哪两个参数？

**Comment by treest** [comment]
> > 我们目前也遇到了这个问题，500并发情况下，打开PSCache，就会报错：
> > ![image](https://user-images.githubusercontent.com/7970760/129691627-d9b25934-8378-4c0b-b46e-a0a337b2e6b2.png)
> > 14:15:29,069 ERROR - exitImplicitCacheToClose error
> > java.sql.SQLRecoverableException: Closed Statement
> > at oracle.jdbc.driver.OracleClosedStatement.exitImplicitCacheToClose(OracleClosedStatement.java:4687)
> > at oracle.jdbc.driver.OraclePreparedStatementWrapper.exitImplicitCacheToClose(OraclePreparedStatementWrapper.java:1623)
> > at com.alibaba.druid.util.OracleUtils.exitImplicitCacheToClose(OracleUtils.java:87)
> > at com.alibaba.druid.pool.PreparedStatementPool.closeRemovedStatement(PreparedStatementPool.java:170)
> > at com.alibaba.druid.pool.PreparedStatementPool.clear(PreparedStatementPool.java:138)
> > at com.alibaba.druid.pool.DruidConnectionHolder.clearStatementCache(DruidConnectionHolder.java:255)
> > at com.alibaba.druid.pool.DruidPooledConnection.disable(DruidPooledConnection.java:223)
> > at com.alibaba.druid.pool.DruidDataSource.handleFatalError(DruidDataSource.java:1818)
> > at com.alibaba.druid.pool.DruidDataSource.handleConnectionException(DruidDataSource.java:1780)
> > at com.alibaba.druid.pool.DruidPooledConnection.handleException(DruidPooledConnection.java:137)
> > at com.alibaba.druid.pool.DruidPooledStatement.checkException(DruidPooledStatement.java:81)
> > at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:240)
> > 网上也查了一下资料，刚开始怀疑是ojdbc驱动问题，我们用的Oracle18c，更换了匹配的ojdbc8之后，问题依然出现。
> > 然后我又怀疑是druid版本问题，然后从1.1.22升级到1.2.6，问题依旧。
> > 之后就考虑到是不是PS缓存问题，就把2个缓存参数注释掉，这时候500并发情况下，问题消失了。
> > 10000
> > true
> > 18800
> > true
> > stat
> > 20
> > 500
> > 20
> > SELECT 1 FROM DUAL
> > true
> > 60000
> > 然后我又测试了druid1.1.22 以及ojdbc6，发现只要注释掉这两个参数，500并发都没有问题。
> > 所以目前来看大概率还是这两个参数导致了高并发下的这种问题。
> > 我们的处理方式暂时是注释掉了PS缓存。
> > 希望我的补充能有所帮助。
> 
> 能否描述一下，具体是哪两个参数？
这两个参数：poolPreparedStatements  & maxPoolPreparedStatementPerConnectionSize
刚才我copy的xml配置项，传上去之后估计不支持，乱了
![image](https://user-images.githubusercontent.com/7970760/129697625-384a9f8d-2815-41e6-9ab7-5e941ee371d8.png)

**Comment by linweiyu** [comment]
> 数据库修改过表结构

谢谢回复，这个现象是生产上发现的，数据库在这期间没有修改过表结构

**Comment by Korov** [comment]
使用Mariadb时也遇到过这个问题，问题原因是使用了游标查询，每次执行完毕之后关闭游标的时候会顺带关闭Statement，但是因为开启了PSCache，导致下次相同的查询过来的时候会从Cache中拿到被关闭了的Statement，这就导致异常出来了，希望对你有帮助
