### ISSUE TITLE
多数据源下 druid   报错

### ISSUE THREAD

**Issue by iojyggfhkkluygv** [alibaba/druid#3927]
[ ERROR] [2020-09-02 16:40:20] com.alibaba.druid.util.JdbcUtils [91] - close connection error
java.sql.SQLRecoverableException: IO 错误: Software caused connection abort: recv failed
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:556)
	at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:3984)
	at com.alibaba.druid.util.JdbcUtils.close(JdbcUtils.java:89)
	at com.alibaba.druid.pool.DruidDataSource.shrink(DruidDataSource.java:3067)
	at com.alibaba.druid.pool.DruidDataSource$DestroyTask.run(DruidDataSource.java:2811)
	at com.alibaba.druid.pool.DruidDataSource$DestroyConnectionThread.run(DruidDataSource.java:2795)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at oracle.net.ns.Packet.receive(Packet.java:300)
	at oracle.net.ns.DataPacket.receive(DataPacket.java:106)
	at oracle.net.ns.NetInputStream.getNextPacket(NetInputStream.java:315)
	at oracle.net.ns.NetInputStream.read(NetInputStream.java:260)
	at oracle.net.ns.NetInputStream.read(NetInputStream.java:185)
	at oracle.net.ns.NetInputStream.read(NetInputStream.java:102)
	at oracle.jdbc.driver.T4CSocketInputStreamWrapper.readNextPacket(T4CSocketInputStreamWrapper.java:124)
	at oracle.jdbc.driver.T4CSocketInputStreamWrapper.read(T4CSocketInputStreamWrapper.java:80)
	at oracle.jdbc.driver.T4CMAREngine.unmarshalUB1(T4CMAREngine.java:1137)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:290)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:192)
	at oracle.jdbc.driver.T4C7Ocommoncall.doOLOGOFF(T4C7Ocommoncall.java:61)
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:543)
	... 5 common frames omitted

**Comment by ganlf** [comment]
url: jdbc:oracle:thin:@14.23.114.74:1521:orcl
        username: system
        password: 123456
        driver-class-name: oracle.jdbc.driver.OracleDriver
        initialSize: 5
        minIdle: 5
        maxActive: 20
        # 获取数据库连接等待的超时时间
        maxWait: 60000
        # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
        timeBetweenEvictionRunsMillis: 60000
        validationQuery: SELECT 1 FROM dual
        testWhileIdle: true
        testOnBorrow: true
        testOnReturn: true

**Comment by ganlf** [comment]
有人遇到吗

**Comment by hylyLLL** [comment]
> 有人遇到吗

你好，请问你解决了这个问题吗？
