### ISSUE TITLE
druid连接达梦数据库用到了xa，还是报错，希望可以提供一下支持

### ISSUE THREAD

**Issue by a57681403** [alibaba/druid#3944]
java.sql.SQLException: xa not support dbType : dm

**Comment by a57681403** [comment]
at com.alibaba.druid.pool.xa.DruidXADataSource.createPhysicalXAConnection(DruidXADataSource.java:88)
	at com.alibaba.druid.pool.xa.DruidXADataSource.getXAConnection(DruidXADataSource.java:49)
	at com.atomikos.jdbc.AtomikosXAConnectionFactory.createPooledConnection(AtomikosXAConnectionFactory.java:43)
	at com.atomikos.datasource.pool.ConnectionPool.createPooledConnection(ConnectionPool.java:98)
	at com.atomikos.datasource.pool.ConnectionPool.addConnectionsIfMinPoolSizeNotReached(ConnectionPool.java:86)
	at com.atomikos.datasource.pool.ConnectionPool.init(ConnectionPool.java:60)
	at com.atomikos.datasource.pool.ConnectionPool.<init>(ConnectionPool.java:49)
	at com.atomikos.datasource.pool.ConnectionPoolWithConcurrentValidation.<init>(ConnectionPoolWithConcurrentValidation.java:23)
	at com.atomikos.jdbc.AbstractDataSourceBean.init(AbstractDataSourceBean.java:294)

**Comment by wenshao** [comment]
dm没有驱动，不知道怎么支持

**Comment by kyohaha** [comment]
我也遇到这个问题了...有办法解决吗？

**Comment by a57681403** [comment]
我用的1.1.21版本，引用达梦的驱动
import dm.jdbc.driver.DmdbXAConnection;

DruidXADataSource加
if ("dm".equals(this.dbType)) {
                return new DmdbXAConnection(physicalConn);
            }
