### ISSUE TITLE
连接postgresql 12 问题 Cannot open connection

### ISSUE THREAD

**Issue by allloveend** [alibaba/druid#3949]
近期在对老项目做升级和迁移，原数据库postgresql 9+druid 1.0.25 +spring jdbc 可以正常运行。
代码迁移到新服务器 ubuntu20.04 + postgresql 12 + druid 1.0.25 时就不行了，连接时提示Cannot open connection

本地代码启动也连接不了DB，尝试更换duid最新的1.1.24版本，使用DruidDataSource仍然Cannot open connection
我将druidDataSource更换为org.apache.commons.dbcp.BasicDataSource就可以启动并连接成功。

可以肯定DB没有IP/防火墙的限制，因为查询工具可以正常连接，本地其他连接方式的项目也可以启动并连接到新DB。

部分错误代码

信息: Initializing Spring root WebApplicationContext
org.hibernate.exception.GenericJDBCException: Cannot open connection
	at org.hibernate.exception.SQLStateConverter.handledNonSpecificException(SQLStateConverter.java:140)
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:128)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:66)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:52)
	at org.hibernate.jdbc.ConnectionManager.openConnection(ConnectionManager.java:449)
	at org.hibernate.jdbc.ConnectionManager.getConnection(ConnectionManager.java:167)
	at org.hibernate.jdbc.AbstractBatcher.prepareQueryStatement(AbstractBatcher.java:161)
	at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1700)
	at org.hibernate.loader.Loader.doQuery(Loader.java:801)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:274)
	at org.hibernate.loader.Loader.doList(Loader.java:2533)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2276)
	at org.hibernate.loader.Loader.list(Loader.java:2271)
	at org.hibernate.loader.custom.CustomLoader.list(CustomLoader.java:316)
	at org.hibernate.impl.SessionImpl.listCustomQuery(SessionImpl.java:1842)
	at org.hibernate.impl.AbstractSessionImpl.list(AbstractSessionImpl.java:165)
	at org.hibernate.impl.SQLQueryImpl.list(SQLQueryImpl.java:157)

Caused by: com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 10002, active 0, maxActive 20
	at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1192)
	at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1014)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4544)
	at com.alibaba.druid.filter.logging.LogFilter.dataSource_getConnection(LogFilter.java:831)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4540)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:992)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:984)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:103)
	at org.springframework.orm.hibernate3.LocalDataSourceConnectionProvider.getConnection(LocalDataSourceConnectionProvider.java:81)
	at org.hibernate.jdbc.ConnectionManager.openConnection(ConnectionManager.java:446)
	... 74 more

**Comment by allloveend** [comment]
spring 连接配置

	<bean id="dataSource" class="com.alibaba.druid.pool.DruidDataSource">
		<property name="driverClassName">
			<value>org.postgresql.Driver</value>
		</property>
		<property name="url">
			<value>jdbc:postgresql://ip:5432/xxxxx</value>
		</property>
		<property name="username">
			<value>postgres</value>
		</property>
		<property name="password">
			<value>postgres</value>
		</property>
		<property name="maxActive">
			<value>20</value>
		</property>
		<property name="maxIdle">
			<value>5</value>
		</property>
		<property name="maxWait">
			<value>10000</value>
		</property>
		<property name="filters">
			<value>stats,log4j</value>
		</property>
	</bean>

**Comment by allloveend** [comment]
oh,我想我找到问题原因了。差异在postgresql的jdbc驱动版本，将这个项目的驱动版本换到42.2就可以了。
因为其他项目是将驱动放在tomcat中调用，而这个项目是放在lib下，项目使用了旧版本的jdbc驱动，尴尬。
