### ISSUE TITLE
druid 1.1.20 版本长时间不操作报Operation not allowed after ResultSet closed

### ISSUE THREAD

**Issue by kexianjun** [alibaba/druid#3967]
druid 版本 1.1.20 
长时间不操作报如下异常
```
Caused by: java.sql.SQLException: Operation not allowed after ResultSet closed
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:996)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:935)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:924)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:870)
        at com.mysql.jdbc.ResultSetImpl.checkClosed(ResultSetImpl.java:734)
        at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1025)
        at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5201)
        at com.alibaba.druid.filter.FilterChainImpl.resultSet_getString(FilterChainImpl.java:1129)
        at com.alibaba.druid.filter.FilterAdapter.resultSet_getString(FilterAdapter.java:1787)
        at com.alibaba.druid.filter.FilterChainImpl.resultSet_getString(FilterChainImpl.java:1126)
        at com.alibaba.druid.proxy.jdbc.ResultSetProxyImpl.getString(ResultSetProxyImpl.java:693)
        at com.alibaba.druid.pool.DruidPooledResultSet.getString(DruidPooledResultSet.java:257)
        at org.apache.ibatis.type.StringTypeHandler.getNullableResult(StringTypeHandler.java:37)
        at org.apache.ibatis.type.StringTypeHandler.getNullableResult(StringTypeHandler.java:26)
        at org.apache.ibatis.type.BaseTypeHandler.getResult(BaseTypeHandler.java:66)
        at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.getPropertyMappingValue(DefaultResultSetHandler.java:471)
        at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.applyPropertyMappings(DefaultResultSetHandler.java:440)
        at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.getRowValue(DefaultResultSetHandler.java:403)
        at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleRowValuesForSimpleResultMap(DefaultResultSetHandler.java:355)
        at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleRowValues(DefaultResultSetHandler.java:330)
        at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSet(DefaultResultSetHandler.java:303)
        at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSets(DefaultResultSetHandler.java:196)
        at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:64)
        at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
        at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
        at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:326)
        at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
        at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
        at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:108)
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
        at com.sun.proxy.$Proxy108.query(Unknown Source)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
        at sun.reflect.GeneratedMethodAccessor180.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
        ... 17 common frames omitted
```

**Comment by helloyaoge** [comment]
我也遇到了，不知道怎么解决， 感觉druid不太稳定

**Comment by 15222835160** [comment]
我也遇到了，开始以为是版本问题，升级到了1.2.6还是有问题

**Comment by 1019199441** [comment]
同遇到，大家是怎么解决的啊

**Comment by cooker** [comment]
我也遇到了，什么情况。这么奇葩

**Comment by yangmengmeng01** [comment]
同问，怎么解决的？

> druid 版本 1.1.20 长时间不操作报如下异常
> 
> ```
> Caused by: java.sql.SQLException: Operation not allowed after ResultSet closed
>         at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:996)
>         at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:935)
>         at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:924)
>         at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:870)
>         at com.mysql.jdbc.ResultSetImpl.checkClosed(ResultSetImpl.java:734)
>         at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1025)
>         at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5201)
>         at com.alibaba.druid.filter.FilterChainImpl.resultSet_getString(FilterChainImpl.java:1129)
>         at com.alibaba.druid.filter.FilterAdapter.resultSet_getString(FilterAdapter.java:1787)
>         at com.alibaba.druid.filter.FilterChainImpl.resultSet_getString(FilterChainImpl.java:1126)
>         at com.alibaba.druid.proxy.jdbc.ResultSetProxyImpl.getString(ResultSetProxyImpl.java:693)
>         at com.alibaba.druid.pool.DruidPooledResultSet.getString(DruidPooledResultSet.java:257)
>         at org.apache.ibatis.type.StringTypeHandler.getNullableResult(StringTypeHandler.java:37)
>         at org.apache.ibatis.type.StringTypeHandler.getNullableResult(StringTypeHandler.java:26)
>         at org.apache.ibatis.type.BaseTypeHandler.getResult(BaseTypeHandler.java:66)
>         at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.getPropertyMappingValue(DefaultResultSetHandler.java:471)
>         at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.applyPropertyMappings(DefaultResultSetHandler.java:440)
>         at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.getRowValue(DefaultResultSetHandler.java:403)
>         at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleRowValuesForSimpleResultMap(DefaultResultSetHandler.java:355)
>         at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleRowValues(DefaultResultSetHandler.java:330)
>         at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSet(DefaultResultSetHandler.java:303)
>         at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSets(DefaultResultSetHandler.java:196)
>         at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:64)
>         at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
>         at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
>         at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:326)
>         at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
>         at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
>         at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:108)
>         at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
>         at com.sun.proxy.$Proxy108.query(Unknown Source)
>         at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
>         at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
>         at sun.reflect.GeneratedMethodAccessor180.invoke(Unknown Source)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
>         ... 17 common frames omitted
> ```

同问，怎么解决的？
