### ISSUE TITLE
rds 主备切换后  连接未被废弃

### ISSUE THREAD

**Issue by zjzhiqian** [alibaba/druid#3974]
druid 版本  1.1.9

主备切换后一段时间，持续性报错，无法恢复，设置的socketTimeout 15秒
经sql 洞察核实  查询请求没有打到新的rds上

message:  discard connection

stack_trace:  com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 931,296 milliseconds ago.  The last packet sent successfully to the server was 13,843 milliseconds ago.
	at jdk.internal.reflect.GeneratedConstructorAccessor79.newInstance(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[na:na]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411) ~[mysql-connector-java-5.1.22.jar:na]
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1117) ~[mysql-connector-java-5.1.22.jar:na]
	at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3851) ~[mysql-connector-java-5.1.22.jar:na]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2471) ~[mysql-connector-java-5.1.22.jar:na]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651) ~[mysql-connector-java-5.1.22.jar:na]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2734) ~[mysql-connector-java-5.1.22.jar:na]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155) ~[mysql-connector-java-5.1.22.jar:na]
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2322) ~[mysql-connector-java-5.1.22.jar:na]
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:228) ~[druid-1.1.9.jar:1.1.9]
	
	......

	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: java.net.SocketException: Broken pipe (Write failed)
	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method) ~[na:na]
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110) ~[na:na]
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150) ~[na:na]
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81) ~[na:na]
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142) ~[na:na]
	at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3832) ~[mysql-connector-java-5.1.22.jar:na]
	... 113 common frames omitted

**Comment by wenshao** [comment]
升级到最新版本1.1.24试试看
