### ISSUE TITLE
clickhouse global  final 一些关键字需要支持一下

### ISSUE THREAD

**Issue by kiwimg** [alibaba/druid#3977]
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'code global not in (SELECT raw', expect ), actual null, pos 1908, line 13, column 32, token IDENTIFIER global
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:558) ~[druid-1.2.1.jar!/:1.2.1]
	at com.alibaba.druid.sql.parser.SQLParser.accept(SQLParser.java:566) ~[druid-1.2.1.jar!/:1.2.1]
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseTableSource(SQLSelectParser.java:1003) ~[druid-1.2.1.jar!/:1.2.1]
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseFrom(SQLSelectParser.java:993) ~[druid-1.2.1.jar!/:1.2.1]
	at com.alibaba.druid.sql.parser.SQLSelectParser.query(SQLSelectParser.java:441) ~[druid-1.2.1.jar!/:1.2.1]
	at com.alibaba.druid.sql.parser.SQLSelectParser.query(SQLSelectParser.java:372) ~[druid-1.2.1.jar!/:1.2.1]
	at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:61) ~[druid-1.2.1.jar!/:1.2.1]
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseTableSource(SQLSelectParser.java:1002) ~[druid-1.2.1.jar!/:1.2.1]
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseFrom(SQLSelectParser.java:993) ~[druid-1.2.1.jar!/:1.2.1]
	at com.alibaba.druid.sql.parser.SQLSelectParser.query(SQLSelectParser.java:441) ~[druid-1.2.1.jar!/:1.2.1]
	at com.alibaba.druid.sql.parser.SQLSelectParser.query(SQLSelectParser.java:372) ~[druid-1.2.1.jar!/:1.2.1]
	at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:61) ~[druid-1.2.1.jar!/:1.2.1]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseSelect(SQLStatementParser.java:4112) ~[druid-1.2.1.jar!/:1.2.1]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:204) ~[druid-1.2.1.jar!/:1.2.1]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:113) ~[druid-1.2.1.jar!/:1

**Comment by wenshao** [comment]
贴一下sql

**Comment by kiwimg** [comment]
SELECT uniq(UserID) FROM distributed_table WHERE CounterID = 101500 AND UserID GLOBAL IN (SELECT UserID FROM distributed_table WHERE CounterID = 34)

**Comment by kiwimg** [comment]
clickhouse 的 global 和 final 是关键字

**Comment by kiwimg** [comment]
牛逼  速度啊 感谢

**Comment by kiwimg** [comment]
1.2.2 什么时候发布
