### ISSUE TITLE
jdbc链接不合法触发死循环

### ISSUE THREAD

**Issue by toroy** [alibaba/druid#3979]
报错如下
```com.alibaba.druid.pool.DruidDataSource.run:2782|create connection RuntimeException
java.lang.IllegalArgumentException: Illegal character in path at index 24: hive2://dummyhost:00000/ dw_dws;hive.mapred.supports.subdirectories=true;mapreduce.input.fileinputformat.input.dir.recursive=true;
	at java.net.URI.create(URI.java:852)
	at org.apache.hive.jdbc.Utils.parseURL(Utils.java:332)
	at org.apache.hive.jdbc.HiveConnection.<init>(HiveConnection.java:141)
	at org.apache.hive.jdbc.HiveDriver.connect(HiveDriver.java:107)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1644)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1710)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2753)
```

hive2://dummyhost:00000/ dw_dws 中间多了个空格， 解析不合法触发代码死循环
```
DruidDataSource.java
public void run() {
            initedLatch.countDown();

            long lastDiscardCount = 0;
            int errorCount = 0;
            for (;;) {
                  ......
		          try {
		                   connection = createPhysicalConnection();
		           } catch (SQLException e) {
		                  ......
		           } catch (RuntimeException e) {
		                    LOG.error("create connection RuntimeException", e);
		                    setFailContinuous(true);
		                    continue;
		           } 
           }
}
 ```

**Comment by yzhang921** [comment]
不知道，RuntimeException没有办法破

**Comment by hihuhu** [comment]
what ??????

**Comment by lizongbo** [comment]
这个启动就会报错的问题，druid也没有别的方法，自己遇到问题自行解决即可
