### ISSUE TITLE
SQLUtils.parseStatements解析ADS sql异常

### ISSUE THREAD

**Issue by jsagui** [alibaba/druid#4009]
下面sql在ADB中执行没问题，通过SQLUtils.parseStatements解析异常，dbType 选择ALIYUN_ADS、MYSQL 都不行
sql如下:
`SELECT
	t1.col2,
	t1.col3,
	t2.col 
FROM
	(
	SELECT
		split ( col1, '\\|' ) AS x,
		col2,
		col3 
	FROM
		table1 
	) t1
	CROSS JOIN unnest ( t1.x ) AS t2 ( col ) 
ORDER BY
	t1.col2;`

异常：
`com.alibaba.druid.sql.parser.ParserException: TODO pos 159, line 14, column 37, token IDENTIFIER col
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:413)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:72)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:464)`

**Comment by JohnCailj** [comment]
收到，我来处理一下；
PS：ALIYUN_ADS已经不推荐使用，建议是用MySQL；

**Comment by jsagui** [comment]
> 收到，我来处理一下；
> PS：ALIYUN_ADS已经不推荐使用，建议是用MySQL；

感谢， 请问预计会在什么时候会有的版本？
