### ISSUE TITLE
[com.alibaba.druid.util.JdbcUtils:75] ERROR - close connection error

### ISSUE THREAD

**Issue by crain3705** [alibaba/druid#4036]
版本信息    
 <groupId>com.oracle</groupId>
<artifactId>ojdbc6</artifactId>
<version>11.2.0.3</version>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid-spring-boot-starter</artifactId>
            <version>1.1.9</version>
        </dependency>

报错日志
2020-11-12 09:00:34 [com.alibaba.druid.util.JdbcUtils:75] ERROR - close connection error
java.sql.SQLRecoverableException: IO Error: Connection reset
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:556)
	at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:3984)
	at com.alibaba.druid.util.JdbcUtils.close(JdbcUtils.java:73)
	at com.alibaba.druid.pool.DruidDataSource.shrink(DruidDataSource.java:2795)
	at com.alibaba.druid.pool.DruidDataSource$DestroyTask.run(DruidDataSource.java:2560)
	at com.alibaba.druid.pool.DruidDataSource$DestroyConnectionThread.run(DruidDataSource.java:2547)

所有的属性基本都设置过一遍了，还是不能解决该报错信息，虽然对使用影响不大，但是程序狗看着很烦。
也升级过对应的版本进行测试，还是不能解决
我看之前的几个issue也提交了该问题，但未得到答复（如：issue#3385等），希望大佬们给个回复！
         致，
  敬！

**Comment by wenshao** [comment]
升级到1.2.3试试看，修改了log级别

**Comment by yisiliang** [comment]
估计是应用和数据库之间的防火墙把连接断开了。
可以看看防火墙的配置，或者在sqlnet.ora里面加上DCD参数：SQLNET.EXPIRE_TIME。

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.2.5
问题已修复，请用新版本
