### ISSUE TITLE
unsupport hive struct

### ISSUE THREAD

**Issue by zhangzichu** [alibaba/druid#4047]
```
public static void main(String[] args) {
        String text = "CREATE TABLE if not exists iteblog_06(name struct<guo:string,sheng:string,shi:string>, value string)";
        MySqlCreateTableParser mySqlCreateTableParser = new MySqlCreateTableParser(text);
        SQLCreateTableStatement sqlCreateTableStatement = mySqlCreateTableParser.parseCreateTable();
        String tableName = sqlCreateTableStatement.getTableName();
    }
```
-------------------------------------------------------------------------------------
```
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: syntax error, expect :, actual VARIANT pos 60, line 1, column 54, token VARIANT
	at com.alibaba.druid.sql.parser.SQLExprParser.accept(SQLExprParser.java:3980)
	at com.alibaba.druid.sql.parser.SQLExprParser.parseDataType(SQLExprParser.java:3643)
	at com.alibaba.druid.sql.parser.SQLExprParser.parseDataType(SQLExprParser.java:3557)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.parseColumn(MySqlExprParser.java:988)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlCreateTableParser.parseCreateTable(MySqlCreateTableParser.java:272)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlCreateTableParser.parseCreateTable(MySqlCreateTableParser.java:42)
	at org.example.App.getTableName(App.java:108)
	at org.example.App.createHbaseTable(App.java:58)
	at org.example.App.main(App.java:30)
```

**Comment by wenshao** [comment]
1.2.3我测试是好的，请更新版本
