### ISSUE TITLE
hive ddl语句格式化报错com.alibaba.druid.sql.parser.ParserException: syntax error

### ISSUE THREAD

**Issue by thorntree** [alibaba/druid#4050]
- 问题简单描述
hive ddl语句通过SQLUtils.formatHive方法进行格式转换时报com.alibaba.druid.sql.parser.ParserException: syntax error

- 使用版本
1.hive ddl语句由hive 2.1.1版本HiveMetaStoreClient获取。
2.druid版本1.2.3

- 示例
```
String createDdl = "create external table `ods.ods_dc_test_df` ( `id` bigint comment 'id',  `name` string comment '名称' ) " +
                "comment '测试表' partitioned by ( `dt` string ) " +
                "row format serde 'org.apache.hadoop.hive.ql.io.parquet.serde.parquethiveserde' " +
                "stored as inputformat 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat' " +
                "          outputformat 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat' " +
                "location 'hdfs://dc/user/hive/warehouse/ods.db/ods_dc_test_df'" +
                " tblproperties ( parquet.compression = 'snappy' , transient_lastDdlTime = '1603362950' )";

        String format = SQLUtils.formatHive(createDdl);

        System.out.println(format);
```

- 报错
```
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'es ( parquet.compression = 'snappy'', expect =, actual ., pos 486, line 1, column 486, token .
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:558)
	at com.alibaba.druid.sql.parser.SQLParser.accept(SQLParser.java:566)
	at com.alibaba.druid.sql.dialect.hive.parser.HiveCreateTableParser.parseCreateTable(HiveCreateTableParser.java:299)
	at com.alibaba.druid.sql.parser.SQLCreateTableParser.parseCreateTable(SQLCreateTableParser.java:45)
	at com.alibaba.druid.sql.dialect.hive.parser.HiveStatementParser.parseCreateTable(HiveStatementParser.java:355)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseCreate(SQLStatementParser.java:3332)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:249)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:113)
	at com.alibaba.druid.sql.SQLUtils.format(SQLUtils.java:341)
	at com.alibaba.druid.sql.SQLUtils.format(SQLUtils.java:334)
	at com.alibaba.druid.sql.SQLUtils.format(SQLUtils.java:322)
	at com.alibaba.druid.sql.SQLUtils.formatHive(SQLUtils.java:213)
	at com.thorntree.bigdata.Sql.HiveParseSql.main(HiveParseSql.java:16)
```

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.2.4
请用新版本
