### ISSUE TITLE
通过Druid解析sql，出现某些关键字在token中没有的异常问题

### ISSUE THREAD

**Issue by Joe192168** [alibaba/druid#4055]
描述：使用的oracle数据库
sql：包含FIRST_VALUE和last_VALUE以及over

根据断点查看，token中没有FIRST_VALUE和last_VALUE关键字

异常：
com.alibaba.druid.sql.parser.ParserException: syntax error. pos 1631, line 1, column 1623, token IDENTIFIER following
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleExprParser.parseAggregateExpr(OracleExprParser.java:878) ~[druid-1.2.3.jar:1.2.3]
	at com.alibaba.druid.sql.parser.SQLExprParser.methodRest(SQLExprParser.java:1554) ~[druid-1.2.3.jar:1.2.3]
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleExprParser.methodRest(OracleExprParser.java:495) ~[druid-1.2.3.jar:1.2.3]
	at com.alibaba.druid.sql.parser.SQLExprParser.parseSelectItem(SQLExprParser.java:5432) ~[druid-1.2.3.jar:1.2.3]
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseSelectList(SQLSelectParser.java:973) ~[druid-1.2.3.jar:1.2.3]
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.query(OracleSelectParser.java:284) ~[druid-1.2.3.jar:1.2.3]
	at com.alibaba.druid.sql.parser.SQLSelectParser.query(SQLSelectParser.java:368) ~[druid-1.2.3.jar:1.2.3]
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.select(OracleSelectParser.java:51) ~[druid-1.2.3.jar:1.2.3]

**Comment by wenshao** [comment]
请提供SQL语句

**Comment by Joe192168** [comment]
公司中的sql，不能提供，上面描述的很清楚了，使用oracle，sql中有FIRST_VALUE，last_VALUE关键函数
