### ISSUE TITLE
MySQL集群中宕掉一个节点后连接异常wait millis 5000, active 20, maxActive 20, creating 0

### ISSUE THREAD

**Issue by kervin521** [alibaba/druid#4078]
org.springframework.transaction.CannotCreateTransactionException: Could not open JDBC Connection for transaction; nested exception is com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 5000, active 20, maxActive 20, creating 0

	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:305) ~[spring-jdbc-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]

	at org.springframework.transaction.support.AbstractPlatformTransactionManager.startTransaction(AbstractPlatformTransactionManager.java:400) ~[spring-tx-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]

	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373) ~[spring-tx-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]

	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:574) ~[spring-tx-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]

	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:361) ~[spring-tx-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]

	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118) ~[spring-tx-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]

	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]

	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]

	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) ~[spring-aop-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]

**Comment by kervin521** [comment]
spring.datasource.url=jdbc:mysql:loadbalance://172.21.32.80:3306,172.21.32.81:3306,172.21.32.82:3306/cps_platform?useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&allowMultiQueries=true

MySQL集群：
3个管理节点(172.21.32.80、172.21.32.81、172.21.32.82)
3个数据节点(172.21.32.80、172.21.32.81、172.21.32.82)
3个SQL节点(172.21.32.80、172.21.32.81、172.21.32.82)

宕掉一个节点(172.21.32.82)包含：一个管理节点、一个数据节点、一个SQL节点

druid-spring-boot-starter版本：1.2.3

**Comment by EliLiu-YF** [comment]
大佬，知道是啥原因吗，我也出现了这个问题
