### ISSUE TITLE
Druid 怎么连接AS400库？

### ISSUE THREAD

**Issue by peiyawei** [alibaba/druid#4086]
配置完jt400 后，怎么都连接不上
java.sql.SQLException: The application requester cannot establish the connection. (Connection was dropped unexpectedly.)
	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:882)
	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:609)
	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:567)
	at com.ibm.as400.access.AS400JDBCConnectionImpl.setProperties(AS400JDBCConnectionImpl.java:3522)
	at com.ibm.as400.access.AS400JDBCDriver.prepareConnection(AS400JDBCDriver.java:1426)
	at com.ibm.as400.access.AS400JDBCDriver.initializeConnection(AS400JDBCDriver.java:1280)
	at com.ibm.as400.access.AS400JDBCDriver.connect(AS400JDBCDriver.java:403)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:156)
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:218)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1580)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1644)
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:918)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1920)

**Comment by lizongbo** [comment]
这个报错是jdbc的异常，与druid无关。
