### ISSUE TITLE
Mysql check not enforce语法无法正常识别-2 

### ISSUE THREAD

**Issue by WillsonYip** [alibaba/druid#4089]
续#4082

环境：mysql 8.0.22 ， druid 1.2.4

经过#4082修复之后，现在能识别/*!80016 NOT ENFORCED */ ，解释并格式化出来的SQL：

```sql
CREATE TABLE `t12` (
	`c1` int DEFAULT NULL,
	`c2` int DEFAULT NULL,
	`c3` int DEFAULT NULL,
	CONSTRAINT `c12_positive` CHECK (`c2` > 0) NOT ENFORCED,
	CONSTRAINT `c21_nonzero` CHECK (`c1` <> 0),
	CONSTRAINT `t12_chk_1` CHECK (`c1` <> `c2`),
	CONSTRAINT `t12_chk_2` CHECK (`c1` > 10),
	CONSTRAINT `t12_chk_3` CHECK (`c3` < 100),
	CONSTRAINT `t12_chk_4` CHECK (`c1` > `c3`)
) ENGINE = InnoDB CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

```

这条SQL mysql能正常识别，但同样用druid 1.2.4 去解释，依然有问题:

测试代码：
```java
public static void main(String[] args) {
        String sql ="CREATE TABLE `t12` (\n" +
                "\t`c1` int DEFAULT NULL,\n" +
                "\t`c2` int DEFAULT NULL,\n" +
                "\t`c3` int DEFAULT NULL,\n" +
                "\tCONSTRAINT `c12_positive` CHECK (`c2` > 0) NOT ENFORCED,\n" +
                "\tCONSTRAINT `c21_nonzero` CHECK (`c1` <> 0),\n" +
                "\tCONSTRAINT `t12_chk_1` CHECK (`c1` <> `c2`),\n" +
                "\tCONSTRAINT `t12_chk_2` CHECK (`c1` > 10),\n" +
                "\tCONSTRAINT `t12_chk_3` CHECK (`c3` < 100),\n" +
                "\tCONSTRAINT `t12_chk_4` CHECK (`c1` > `c3`)\n" +
                ") ENGINE = InnoDB CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;";
        MySqlStatementParser parser = new MySqlStatementParser(sql);
        SQLStatement createTableStatement =  parser.parseStatement();
        System.out.println(createTableStatement);
    }
```

控制台打印的信息：
```
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'(`c2` > 0) NOT ENFORCED,
	CONSTRAINT `c21_non', expect ), actual null, pos 149, line 5, column 50, token IDENTIFIER ENFORCED
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:558)
	at com.alibaba.druid.sql.parser.SQLParser.accept(SQLParser.java:566)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlCreateTableParser.parseCreateTable(MySqlCreateTableParser.java:362)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseCreate(MySqlStatementParser.java:301)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:249)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:4469)
```

**Comment by WillsonYip** [comment]
check 相关的还有其他语句：

```sql
# 新增check 约束
ALTER TABLE t1 ADD CONSTRAINT chk1 CHECK((a>1));

# 删除check 约束
ALTER TABLE t1 DROP CONSTRAINT t1_check ;

# 让check约束不生效
alter table t1 ALTER CHECK  t1_check  NOT ENFORCED;
```

其中除了删check约束是能正常识别，新增和修改check约束是不能正常识别的
