### ISSUE TITLE
druid-spring-boot-starter 无法使用

### ISSUE THREAD

**Issue by 9monsters** [alibaba/druid#4108]
druid-spring-boot-starter： 1.2.4
spring boot：2.3.2.RELEASE

```
Caused by: java.lang.IllegalAccessError: class com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceWrapper$$EnhancerBySpringCGLIB$$48b7bdc9 cannot access its superclass com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceWrapper
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:535)
	... 203 common frames omitted
```

**Comment by NineSwordsMonster** [comment]
非常严重

**Comment by Guangxi-OldWu** [comment]
我也遇到了 解决了吗

**Comment by NineSwordsMonster** [comment]
> 我也遇到了 解决了吗

降低stater版本

**Comment by lizongbo** [comment]
请使用最新版验证
