### ISSUE TITLE
SchemaStatVisitor 转PGDeleteStatement失败

### ISSUE THREAD

**Issue by asfakkk** [alibaba/druid#4109]
对postgresql的Delete语句进行解析时出现报错
```
2020-12-23 14:18:15.284 ERROR 9424 --- [io-9081-exec-10] e.d.e.CustomHttpExceptionHandler         : com.alibaba.druid.sql.visitor.SchemaStatVisitor cannot be cast to com.alibaba.druid.sql.dialect.postgresql.visitor.PGASTVisitor

java.lang.ClassCastException: com.alibaba.druid.sql.visitor.SchemaStatVisitor cannot be cast to com.alibaba.druid.sql.dialect.postgresql.visitor.PGASTVisitor
	at com.alibaba.druid.sql.dialect.postgresql.ast.stmt.PGDeleteStatement.accept0(PGDeleteStatement.java:51) ~[druid-1.2.4.jar:1.2.4]
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:49) ~[druid-1.2.4.jar:1.2.4]
	at esun.dbhelper.utils.DataSourceUtil.checkIndex(DataSourceUtil.java:74) ~[classes/:na]
	at esun.dbhelper.aspect.ControllerAspect.ControllerAop(ControllerAspect.java:57) ~[classes/:na]
```
解析语句:
```
SQLStatement sqlStatement=sqlStatementList.get(i);
SchemaStatVisitor visitor=new SchemaStatVisitor();
sqlStatement.accept(visitor);
```
SQL语句为简单的delete语句。
dbType为postgresql

**Comment by wenshao** [comment]
用PGSchemaStatVisitor
