### ISSUE TITLE
使用1.2.3版本仍然有以下error

### ISSUE THREAD

**Issue by zr920303** [alibaba/druid#4111]
[com.alibaba.druid.util.JdbcUtils:97]--- close connection error
java.sql.SQLRecoverableException: IO 閿欒: Software caused connection abort: recv failed
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:556)
	at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:3984)
	at com.alibaba.druid.filter.FilterChainImpl.connection_close(FilterChainImpl.java:186)
	at com.alibaba.druid.filter.FilterAdapter.connection_close(FilterAdapter.java:777)
	at com.alibaba.druid.filter.FilterChainImpl.connection_close(FilterChainImpl.java:181)
	at com.alibaba.druid.filter.stat.StatFilter.connection_close(StatFilter.java:270)
	at com.alibaba.druid.filter.FilterChainImpl.connection_close(FilterChainImpl.java:181)
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.close(ConnectionProxyImpl.java:114)
	at com.alibaba.druid.util.JdbcUtils.close(JdbcUtils.java:95)
	at com.alibaba.druid.pool.DruidDataSource.shrink(DruidDataSource.java:3141)
	at com.alibaba.druid.pool.DruidDataSource$DestroyTask.run(DruidDataSource.java:2885)
	at com.alibaba.druid.pool.DruidDataSource$DestroyConnectionThread.run(DruidDataSource.java:2869)
Caused by: java.net.SocketException: Software caused connection abort: recv failed

**Comment by hylyLLL** [comment]
我的也是这样的，请问你这个解决了吗？

**Comment by ergouliang** [comment]
1.2.5版本也还是会出现
2021-05-24 13:48:00.553 ERROR 82059 --- [ XNIO-1 task-37] com.alibaba.druid.util.JdbcUtils         : close connection error

java.sql.SQLNonTransientConnectionException: [Cloudera][JDBC](10060) Connection has been closed.
	at com.cloudera.impala.exceptions.ExceptionConverter.toSQLException(Unknown Source)
	at com.cloudera.impala.jdbc.common.SConnection.closeConnection(Unknown Source)
	at com.cloudera.impala.jdbc.common.SConnection.abortInternal(Unknown Source)
	at com.cloudera.impala.jdbc.common.SConnection.close(Unknown Source)
	at com.alibaba.druid.filter.FilterChainImpl.connection_close(FilterChainImpl.java:186)
	at com.alibaba.druid.filter.FilterAdapter.connection_close(FilterAdapter.java:777)
	at com.alibaba.druid.filter.logging.LogFilter.connection_close(LogFilter.java:451)
	at com.alibaba.druid.filter.FilterChainImpl.connection_close(FilterChainImpl.java:181)
	at com.alibaba.druid.filter.stat.StatFilter.connection_close(StatFilter.java:270)
	at com.alibaba.druid.filter.FilterChainImpl.connection_close(FilterChainImpl.java:181)
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.close(ConnectionProxyImpl.java:114)
	at com.alibaba.druid.util.JdbcUtils.close(JdbcUtils.java:85)
	at com.alibaba.druid.pool.DruidDataSource.discardConnection(DruidDataSource.java:1534)
	at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1434)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5059)
	at com.alibaba.druid.filter.logging.LogFilter.dataSource_getConnection(LogFilter.java:887)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5055)
	at com.alibaba.druid.filter.stat.StatFilter.dataSource_getConnection(StatFilter.java:689)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5055)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1393)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1385)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:100)
