### ISSUE TITLE
调用ps.execute()报NPE

### ISSUE THREAD

**Issue by meitianxiaoyixiao** [alibaba/druid#4151]
java.lang.NullPointerException
	at com.alibaba.druid.pool.DruidPooledConnection.transactionRecord(DruidPooledConnection.java:726)
	at com.alibaba.druid.pool.DruidPooledStatement.transactionRecord(DruidPooledStatement.java:285)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:491)
	at com.dmall.tm.TransactionServerRecord.setClientStatus(TransactionServerRecord.java:139)
	at com.dmall.tm.TransactionServerRecord.commit(TransactionServerRecord.java:86)
	at com.dmall.netty.server.ServerHandler.channelRead(ServerHandler.java:50)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)

	String sql = "update client_log set branch_status = ? where transactional_id = ? and branch_id = ?";
	ps = connection.prepareStatement(sql);
	ps.setInt(1, status);
	ps.setString(2, transactionalId);
	ps.setString(3, branchId);
	ps.execute();
调用ps.execute()时，报这个异常，找了很久，不知道什么原因

**Comment by wenshao** [comment]
连接已经关闭后才会有这个问题的

**Comment by meitianxiaoyixiao** [comment]
嗯，打断点时，有时又不会出现，我本地没有显式的调用过connection.close()，这个可能是哪里关闭的呢
