### ISSUE TITLE
postgreSQL解析报错

### ISSUE THREAD

**Issue by 52assert** [alibaba/druid#4154]
2021-01-29 17:35:00,200 [taskScheduler-5] ERROR [com.alibaba.druid.filter.stat.StatFilter] - merge sql error, dbType postgresql, druid-1.1.24, sql : select * from msg.msg_pool where status=? order by create_time limit 100 for update skip locked
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'date skip locked', expect IDENTIFIER, actual IDENTIFIER pos 88, line 1, column 84, token IDENTIFIER skip
 at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:344) ~[druid-1.1.24.jar!/:1.1.24]
 at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:532) ~[druid-1.1.24.jar!/:1.1.24]
 at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:171) ~[druid-1.1.24.jar!/:1.1.24]
 at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:98) ~[druid-1.1.24.jar!/:1.1.24]
 at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:81) ~[druid-1.1.24.jar!/:1.1.24]
 at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:54) ~[druid-1.1.24.jar!/:1.1.24]
 at com.alibaba.druid.filter.stat.StatFilter.mergeSql(StatFilter.java:147) ~[druid-1.1.24.jar!/:1.1.24]
 at com.alibaba.druid.filter.stat.StatFilter.createSqlStat(StatFilter.java:648) ~[druid-1.1.24.jar!/:1.1.24]
 at com.alibaba.druid.filter.stat.StatFilter.statementPrepareAfter(StatFilter.java:311) ~[druid-1.1.24.jar!/:1.1.24]
 at com.alibaba.druid.filter.FilterEventAdapter.connection_prepareStatement(FilterEventAdapter.java:124) ~[druid-1.1.24.jar!/:1.1.24]
 at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:568) ~[druid-1.1.24.jar!/:1.1.24]
 at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.prepareStatement(ConnectionProxyImpl.java:341) ~[druid-1.1.24.jar!/:1.1.24]
 at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:350)

**Comment by 52assert** [comment]
升级到1.2.4也解析报错

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.2.5
问题已修复，请用新版本

**Comment by 52assert** [comment]
thanks

温绍锦 <notifications@github.com> 于2021年2月17日周三 下午7:20写道：
