### ISSUE TITLE
No operations allowed after statement closed

### ISSUE THREAD

**Issue by BruceZhangXL** [alibaba/druid#4181]
druid 版本 1.1.22
mysql-connector-java 版本 8.0.17

Caused by: java.sql.SQLException: No operations allowed after statement closed.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:82)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute$original$0pR0wqEt(ClientPreparedStatement.java:396)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute$original$0pR0wqEt$accessor$S7UnOOkP(ClientPreparedStatement.java)
	at com.mysql.cj.jdbc.ClientPreparedStatement$auxiliary$0deVZ5iu.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3461)
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_execute(FilterEventAdapter.java:440)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3459)
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.execute(PreparedStatementProxyImpl.java:167)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:497)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.MasterSlavePreparedStatement.execute(MasterSlavePreparedStatement.java:118)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:64)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
	at sun.reflect.GeneratedMethodAccessor191.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy115.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at sun.reflect.GeneratedMethodAccessor190.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426)
	... 61 common frames omitted
Caused by: com.mysql.cj.exceptions.StatementIsClosedException: No operations allowed after statement closed.
	at sun.reflect.GeneratedConstructorAccessor96.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:85)
	at com.mysql.cj.jdbc.StatementImpl.checkClosed(StatementImpl.java:340)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute$original$0pR0wqEt(ClientPreparedStatement.java:313)
	... 91 common frames omitted

**Comment by BruceZhangXL** [comment]
@wenshao  active为啥还会大于maxActive

**Comment by RekaDowney** [comment]
@wenshao @BruceZhangXL 请问后面有结果了嘛？我们这边也遇到这个问题了。使用的是druid 1.2.3。同样的代码，预发布环境报这个问题，生产和开发测试环境都没有这问题。

我用 arthas 修改了 maxActive 之后 getConnection 就能正常获取了，一会后 activeCount  - 1 （达到回收时间）。

![image](https://user-images.githubusercontent.com/24631388/119922624-c4113000-bfa2-11eb-8170-997e1905680b.png)

**Comment by RekaDowney** [comment]
> @wenshao @BruceZhangXL 请问后面有结果了嘛？我们这边也遇到这个问题了。使用的是druid 1.2.3。同样的代码，预发布环境报这个问题，生产和开发测试环境都没有这问题。
> 
> 我用 arthas 修改了 maxActive 之后 getConnection 就能正常获取了，一会后 activeCount - 1 （达到回收时间）。
> 
> ![image](https://user-images.githubusercontent.com/24631388/119922624-c4113000-bfa2-11eb-8170-997e1905680b.png)

我使用 jmap 或者 arthas 的 vmtool 统计了连接实例始终没有 11 个，就 1~2个，druidDataSource 里的 connection 也是只有 2 个，但 activeCount 确是 11。

![image](https://user-images.githubusercontent.com/24631388/119938377-e618ab80-bfbe-11eb-8621-f63cf15381d6.png)

我又继续看了一下，从 druid 1.1.21 版本开始，新增了一个 discardConnection(DruidConnectionHolder holder) 方法，所有连接废弃操作都改成调用这个方法，但是有个问题就是方法传入 null 的时候不会将 activeCount - 1。而是直接结束方法执行。

我会考虑将 druid 版本降低到 1.1.20 尝试验证是否依然存在此问题。

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.2.6
=========
1.2.6版本已修复这个问题，原因是是其中的第4个issue ： 修复连接池在timeBetweenEvictionRunsMillis大于keepAliveBetweenTimeMillis时异步使用连接会导致连接池不可用的问题。

**Comment by BruceZhangXL** [comment]
https://github.com/alibaba/druid/issues/4438
