### ISSUE TITLE
有解决方案吗？

### ISSUE THREAD

**Issue by safestar** [alibaba/druid#4188]
有解决方案吗？

Caused by: java.sql.SQLException: connection disabled
	at com.alibaba.druid.pool.DruidPooledConnection.checkStateInternal(DruidPooledConnection.java:1162)
	at com.alibaba.druid.pool.DruidPooledConnection.checkState(DruidPooledConnection.java:1147)
	at com.alibaba.druid.pool.DruidPooledConnection.getAutoCommit(DruidPooledConnection.java:735)
	at sun.reflect.GeneratedMethodAccessor272.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.atomikos.jdbc.AtomikosConnectionProxy.invoke(AtomikosConnectionProxy.java:141)
	at com.sun.proxy.$Proxy159.getAutoCommit(Unknown Source)
	at org.mybatis.spring.transaction.SpringManagedTransaction.openConnection(SpringManagedTransaction.java:83)
	at org.mybatis.spring.transaction.SpringManagedTransaction.getConnection(SpringManagedTransaction.java:68)
	at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:336)
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:85)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at sun.reflect.GeneratedMethodAccessor281.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 82 common frames omitted

_Originally posted by @myVictor in https://github.com/alibaba/druid/issues/2404#issuecomment-483253408_

**Comment by safestar** [comment]
Caused by: java.sql.SQLException: connection closed
at com.alibaba.druid.pool.DruidPooledConnection.checkStateInternal(DruidPooledConnection.java:1157)
at com.alibaba.druid.pool.DruidPooledConnection.checkState(DruidPooledConnection.java:1148)
at com.alibaba.druid.pool.DruidPooledConnection.getHoldability(DruidPooledConnection.java:997)
at com.dianping.zebra.single.jdbc.SingleConnection.getHoldability(SingleConnection.java:167)
at com.dianping.zebra.group.jdbc.GroupPreparedStatement.createPreparedStatementInternal(GroupPreparedStatement.java:120)
at com.dianping.zebra.group.jdbc.GroupPreparedStatement.executeQueryOnConnection(GroupPreparedStatement.java:188)
at com.dianping.zebra.group.jdbc.GroupPreparedStatement.executeQuery(GroupPreparedStatement.java:184)
at com.dianping.zebra.group.jdbc.GroupPreparedStatement.execute(GroupPreparedStatement.java:139)
at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:63)
at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
at sun.reflect.GeneratedMethodAccessor430.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
at com.sun.proxy.$Proxy334.query(Unknown Source)
at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
at sun.reflect.GeneratedMethodAccessor428.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
at com.ymm.security.thaad.mybatis.SqlRewriteInterceptor.initThreadLocalAndExecute(SqlRewriteInterceptor.java:66)
at com.ymm.security.thaad.mybatis.SqlRewriteInterceptor.intercept(SqlRewriteInterceptor.java:47)
at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
at com.sun.proxy.$Proxy333.query(Unknown Source)
at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:153)
at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
at com.sun.proxy.$Proxy333.query(Unknown Source)
at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:77)
at sun.reflect.GeneratedMethodAccessor426.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)

**Comment by wenshao** [comment]
连接关闭后重用连接了

**Comment by varyuan** [comment]
配置个检查连接是否可用的sql看看可不可以解决

**Comment by 734456387** [comment]
有解决方案吗，被折腾好久了

**Comment by 734456387** [comment]
> 连接关闭后重用连接了

配置检查连接也不行,Druid 使用的是  1.2.8
spring.datasource.druid.maindb.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.druid.maindb.url=jdbc:mysql://xxxxxx/xxxx?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
spring.datasource.druid.maindb.username=xxxxx
spring.datasource.druid.maindb.password=xxxxx
spring.datasource.druid.maindb.initialSize=5
spring.datasource.druid.maindb.minIdle=5
spring.datasource.druid.maindb.maxActive=80
spring.datasource.druid.maindb.maxWait=120000
spring.datasource.druid.maindb.timeBetweenEvictionRunsMillis=1000
spring.datasource.druid.maindb.minEvictableIdleTimeMillis=30000
spring.datasource.druid.maindb.validationQuery=SELECT 1 FROM DUAL
spring.datasource.druid.maindb.validationQueryTimeout=1
spring.datasource.druid.maindb.testOnBorrow=false
spring.datasource.druid.maindb.testOnReturn=false
spring.datasource.druid.maindb.testWhileIdle=true
spring.datasource.druid.maindb.keepAlive=true
spring.datasource.druid.maindb.socketTimeout=6000
spring.datasource.druid.maindb.poolPreparedStatements=true

**Comment by wj20190913** [comment]
解决了吗？

**Comment by linghengqian** [comment]
- I have opened #6143 .
- By setting `closeConnOnFatalError` to `false`, Druid's behavior will align with HikariCP, that is, the connection will no longer be closed when a fatal error defined by Druid occurs. This solves a series of controversies surrounding Hibernate, Flyway, and ShardingSphere. This is a huge regret introduced from https://github.com/alibaba/druid/commit/882470b1ce7a51a94f3525beceec91384ccd425f 7 years ago.
