### ISSUE TITLE
Exception: java.lang.StackOverflowError occurred while parsing this query

### ISSUE THREAD

**Issue by seed47** [alibaba/druid#4214]
select a.id, a.name from (select a.* from table1) a

Exception in thread "main" java.lang.StackOverflowError
	at com.alibaba.druid.sql.ast.statement.SQLSelectQueryBlock.resolveColum(SQLSelectQueryBlock.java:1202)
	at com.alibaba.druid.sql.ast.statement.SQLSelectQueryBlock.findColumn(SQLSelectQueryBlock.java:1189)
	at com.alibaba.druid.sql.ast.statement.SQLSubqueryTableSource.findColumn(SQLSubqueryTableSource.java:157)
	at com.alibaba.druid.sql.ast.statement.SQLSelectItem.match(SQLSelectItem.java:280)
	at com.alibaba.druid.sql.ast.statement.SQLSelectQueryBlock.findSelectItem(SQLSelectQueryBlock.java:1091)
	at com.alibaba.druid.sql.ast.statement.SQLSelectQueryBlock.resolveColum(SQLSelectQueryBlock.java:1202)
	at com.alibaba.druid.sql.ast.statement.SQLSelectQueryBlock.findColumn(SQLSelectQueryBlock.java:1189)
	at com.alibaba.druid.sql.ast.statement.SQLSubqueryTableSource.findColumn(SQLSubqueryTableSource.java:157)
	at com.alibaba.druid.sql.ast.statement.SQLSelectItem.match(SQLSelectItem.java:280)
	at com.alibaba.druid.sql.ast.statement.SQLSelectQueryBlock.findSelectItem(SQLSelectQueryBlock.java:1091)
	at com.alibaba.druid.sql.ast.statement.SQLSelectQueryBlock.resolveColum(SQLSelectQueryBlock.java:1202)
	at com.alibaba.druid.sql.ast.statement.SQLSelectQueryBlock.findColumn(SQLSelectQueryBlock.java:1189)
	at com.alibaba.druid.sql.ast.statement.SQLSubqueryTableSource.findColumn(SQLSubqueryTableSource.java:157)
	at com.alibaba.druid.sql.ast.statement.SQLSelectItem.match(SQLSelectItem.java:280)

**Comment by Tanyz-LEZ** [comment]
SQL写的错了。你应该是想写
“select a.id, a.name from (select table1.* from table1) a”
吧
