### ISSUE TITLE
网上说是数据库连接的问题，是在不知道怎么解决，求大佬帮忙看一下。

### ISSUE THREAD

**Issue by luozuyi** [alibaba/druid#4219]
ERROR[0;39m [35m8[0;39m [2m[ http-nio-8034-exec-9][0;39m [36mc.a.druid.pool.DruidPooledStatement [0;39m 357 [2m:[0;39m CommunicationsException, druid version 1.1.10, jdbcUrl : jdbc:mysql://10.200.16.111:3306/work?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&nullCatalogMeansCurrent=true&zeroDateTimeBehavior=convertToNull&socketTimeout=15000, testWhileIdle true, idle millis 15030, minIdle 10, poolingCount 9, timeBetweenEvictionRunsMillis 30000000, lastValidIdleMillis 15030, driver com.mysql.cj.jdbc.Driver, exceptionSorter com.alibaba.druid.pool.vendor.MySqlExceptionSorter
-199[2m2021-03-16 09:47:31.402[0;39m [31m-ERROR[0;39m [35m8[0;39m [2m[ http-nio-8034-exec-9][0;39m [36mcom.alibaba.druid.pool.DruidDataSource [0;39m 1602 [2m:[0;39m discard connection
-198
-197com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
-196
-195The last packet successfully received from the server was 15,021 milliseconds ago. The last packet sent successfully to the server was 15,023 milliseconds ago.
-194        at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
-193        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
-192        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
-191        at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
-190        at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeQuery(FilterChainImpl.java:3188) ~[druid-1.1.10.jar!/:1.1.10]
-189        at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_executeQuery(FilterEventAdapter.java:465) ~[druid-1.1.10.jar!/:1.1.10]
-188        at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeQuery(FilterChainImpl.java:3185) ~[druid-1.1.10.jar!/:1.1.10]
-187        at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.executeQuery(PreparedStatementProxyImpl.java:181) ~[druid-1.1.10.jar!/:1.1.10]
-186        at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:228) ~[druid-1.1.10.jar!/:1.1.10]
-185        at sun.reflect.GeneratedMethodAccessor913.invoke(Unknown Source) ~[na:na]
-184        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
-183        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
-182        at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:56) [mybatis-3.5.2.jar!/:3.5.2]
-181        at com.sun.proxy.$Proxy205.executeQuery(Unknown Source) [na:na]
-180        at com.baomidou.mybatisplus.extension.plugins.PaginationInterceptor.queryTotal(PaginationInterceptor.java:233) [mybatis-plus-extension-3.2.0.jar!/:3.2.0]
-179        at com.baomidou.mybatisplus.extension.plugins.PaginationInterceptor.intercept(PaginationInterceptor.java:202) [mybatis-plus-extension-3.2.0.jar!/:3.2.0]
-178        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61) [mybatis-3.5.2.jar!/:3.5.2]
-177        at com.sun.proxy.$Proxy203.prepare(Unknown Source) [na:na]
-176        at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.prepareStatement(MybatisSimpleExecutor.java:94) [mybatis-plus-core-3.2.0.jar!/:3.2.0]
-175        at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doQuery(MybatisSimpleExecutor.java:66) [mybatis-plus-core-3.2.0.jar!/:3.2.0]
-174        at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324) [mybatis-3.5.2.jar!/:3.5.2]
-173        at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156) [mybatis-3.5.2.jar!/:3.5.2]
-172        at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109) [mybatis-3.5.2.jar!/:3.5.2]
-171        at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83) [mybatis-3.5.2.jar!/:3.5.2]
-170        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147) [mybatis-3.5.2.jar!/:3.5.2]
-169        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140) [mybatis-3.5.2.jar!/:3.5.2]
-168        at sun.reflect.GeneratedMethodAccessor475.invoke(Unknown Source) ~[na:na]
-167        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
-166        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
-165        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426) [mybatis-spring-2.0.2.jar!/:2.0.2]
-164        at com.sun.proxy.$Proxy95.selectList(Unknown Source) [na:na]
-163        at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:223) [mybatis-spring-2.0.2.jar!/:2.0.2]
-162        at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.executeForIPage(MybatisMapperMethod.java:115) [mybatis-plus-core-3.2.0.jar!/:3.2.0]
-161        at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:86) [mybatis-plus-core-3.2.0.jar!/:3.2.0]
-160        at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:61) [mybatis-plus-core-3.2.0.jar!/:3.2.0]
-159        at com.sun.proxy.$Proxy101.selectPage(Unknown Source) [na:na]
-158        at com.baomidou.mybatisplus.extension.service.impl.ServiceImpl.page(ServiceImpl.java:276) [mybatis-plus-extension-3.2.0.jar!/:3.2.0]
-157        at com.baomidou.mybatisplus.extension.service.impl.ServiceImpl$$FastClassBySpringCGLIB$$76535273.invoke(<generated>) [mybatis-plus-extension-3.2.0.jar!/:3.2.0]
-156        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) [spring-core-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
-155        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687) [spring-aop-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
-154        at com.whwater.server.order.service.impl.WorkSheetServiceImpl$$EnhancerBySpringCGLIB$$72287cfe.page(<generated>) [classes!/:1.0]
-153        at com.whwater.server.order.controller.api.WorkSheetApiController.cscList(WorkSheetApiController.java:332) [classes!/:1.0]
-152        at sun.reflect.GeneratedMethodAccessor1526.invoke(Unknown Source) ~[na:na]
-151        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
-150        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
-149        at org.apache.servicecomb.core.handler.impl.ProducerOperationHandler.doInvoke(ProducerOperationHandler.java:121) [java-chassis-core-2.1.5.jar!/:2.1.5]
-148        at org.apache.servicecomb.core.handler.impl.ProducerOperationHandler.syncInvoke(ProducerOperationHandler.java:106) [java-chassis-core-2.1.5.jar!/:2.1.5]
-147        at org.apache.servicecomb.core.handler.impl.ProducerOperationHandler.invoke(ProducerOperationHandler.java:60) [java-chassis-core-2.1.5.jar!/:2.1.5]
-146        at org.apache.servicecomb.core.handler.impl.ProducerOperationHandler.handle(ProducerOperationHandler.java:51) [java-chassis-core-2.1.5.jar!/:2.1.5]
-145        at org.apache.servicecomb.core.Invocation.next(Invocation.java:307) [java-chassis-core-2.1.5.jar!/:2.1.5]
-144        at org.apache.servicecomb.bizkeeper.BizkeeperCommand.lambda$construct$2(BizkeeperCommand.java:79) [handler-bizkeeper-2.1.5.jar!/:2.1.5]
-143        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.3.8.jar!/:1.3.8]
-142        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.3.8.jar!/:1.3.8]
-141        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.3.8.jar!/:1.3.8]
-140        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.3.8.jar!/:1.3.8]
-139        at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar!/:1.3.8]
-138        at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51) ~[rxjava-1.3.8.jar!/:1.3.8]
-137        at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35) ~[rxjava-1.3.8.jar!/:1.3.8]
-136        at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar!/:1.3.8]
-135        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41) ~[rxjava-1.3.8.jar!/:1.3.8]
-134        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30) ~[rxjava-1.3.8.jar!/:1.3.8]
-133        at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar!/:1.3.8]
-132        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41) ~[rxjava-1.3.8.jar!/:1.3.8]
-131        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30) ~[rxjava-1.3.8.jar!/:1.3.8]
-130        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.3.8.jar!/:1.3.8]
-129        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.3.8.jar!/:1.3.8]
-128        at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar!/:1.3.8]
-127        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41) ~[rxjava-1.3.8.jar!/:1.3.8]
-126        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30) ~[rxjava-1.3.8.jar!/:1.3.8]
-125        at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar!/:1.3.8]
-124        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41) ~[rxjava-1.3.8.jar!/:1.3.8]
-123        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30) ~[rxjava-1.3.8.jar!/:1.3.8]
-122        at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar!/:1.3.8]
-121        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41) ~[rxjava-1.3.8.jar!/:1.3.8]
-120        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30) ~[rxjava-1.3.8.jar!/:1.3.8]
-119        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.3.8.jar!/:1.3.8]
-118        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.3.8.jar!/:1.3.8]
-117        at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar!/:1.3.8]
-116        at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51) ~[rxjava-1.3.8.jar!/:1.3.8]
-115        at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35) ~[rxjava-1.3.8.jar!/:1.3.8]
-114        at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar!/:1.3.8]
-113        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) ~[rxjava-1.3.8.jar!/:1.3.8]
-112        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) ~[rxjava-1.3.8.jar!/:1.3.8]
-111        at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar!/:1.3.8]
-110        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41) ~[rxjava-1.3.8.jar!/:1.3.8]
-109        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30) ~[rxjava-1.3.8.jar!/:1.3.8]
-108        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.3.8.jar!/:1.3.8]
-107        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.3.8.jar!/:1.3.8]
-106        at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar!/:1.3.8]
-105        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41) ~[rxjava-1.3.8.jar!/:1.3.8]
-104        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30) ~[rxjava-1.3.8.jar!/:1.3.8]
-103        at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar!/:1.3.8]
-102        at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51) ~[rxjava-1.3.8.jar!/:1.3.8]
-101        at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35) ~[rxjava-1.3.8.jar!/:1.3.8]
-100        at rx.Observable.subscribe(Observable.java:10423) ~[rxjava-1.3.8.jar!/:1.3.8]
-99        at rx.Observable.subscribe(Observable.java:10390) ~[rxjava-1.3.8.jar!/:1.3.8]
-98        at rx.Observable.subscribe(Observable.java:10271) ~[rxjava-1.3.8.jar!/:1.3.8]
-97        at org.apache.servicecomb.bizkeeper.BizkeeperHandler.handle(BizkeeperHandler.java:78) ~[handler-bizkeeper-2.1.5.jar!/:2.1.5]
-96        at org.apache.servicecomb.core.Invocation.next(Invocation.java:307) [java-chassis-core-2.1.5.jar!/:2.1.5]
-95        at org.apache.servicecomb.qps.ProviderQpsFlowControlHandler.handle(ProviderQpsFlowControlHandler.java:35) ~[handler-flowcontrol-qps-2.1.5.jar!/:2.1.5]
-94        at org.apache.servicecomb.core.Invocation.next(Invocation.java:307) [java-chassis-core-2.1.5.jar!/:2.1.5]
-93        at org.apache.servicecomb.common.rest.AbstractRestInvocation.doInvoke(AbstractRestInvocation.java:245) ~[common-rest-2.1.5.jar!/:2.1.5]
-92        at org.apache.servicecomb.common.rest.AbstractRestInvocation.invoke(AbstractRestInvocation.java:219) ~[common-rest-2.1.5.jar!/:2.1.5]
-91        at org.apache.servicecomb.common.rest.AbstractRestInvocation.runOnExecutor(AbstractRestInvocation.java:203) ~[common-rest-2.1.5.jar!/:2.1.5]
-90        at org.apache.servicecomb.common.rest.AbstractRestInvocation.lambda$scheduleInvocation$0(AbstractRestInvocation.java:162) ~[common-rest-2.1.5.jar!/:2.1.5]
-89        at org.apache.servicecomb.core.executor.ReactiveExecutor.execute(ReactiveExecutor.java:30) ~[java-chassis-core-2.1.5.jar!/:2.1.5]
-88        at org.apache.servicecomb.common.rest.AbstractRestInvocation.scheduleInvocation(AbstractRestInvocation.java:147) ~[common-rest-2.1.5.jar!/:2.1.5]
-87        at org.apache.servicecomb.common.rest.RestProducerInvocation.invoke(RestProducerInvocation.java:52) ~[common-rest-2.1.5.jar!/:2.1.5]
-86        at org.apache.servicecomb.transport.rest.servlet.ServletRestDispatcher.service(ServletRestDispatcher.java:72) ~[transport-rest-servlet-2.1.5.jar!/:2.1.5]
-85        at org.apache.servicecomb.transport.rest.servlet.RestServlet.service(RestServlet.java:47) ~[transport-rest-servlet-2.1.5.jar!/:2.1.5]
-84        at javax.servlet.http.HttpServlet.service(HttpServlet.java:584) ~[jakarta.servlet-api-4.0.4.jar!/:4.0.4]
-83        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.38.jar!/:9.0.38]
-82        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.38.jar!/:9.0.38]
-81        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.38.jar!/:9.0.38]
-80        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.38.jar!/:9.0.38]
-79        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.38.jar!/:9.0.38]
-78        at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:92) ~[spring-web-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
-77        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
-76        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.38.jar!/:9.0.38]
-75        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.38.jar!/:9.0.38]
-74        at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123) ~[druid-1.1.10.jar!/:1.1.10]
-73        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.38.jar!/:9.0.38]
-72        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.38.jar!/:9.0.38]
-71        at com.whwater.server.order.config.CharsetFilter.doFilter(CharsetFilter.java:29) ~[classes!/:1.0]
-70        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.38.jar!/:9.0.38]
-69        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.38.jar!/:9.0.38]
-68        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
-67        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
-66        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.38.jar!/:9.0.38]
-65        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.38.jar!/:9.0.38]
-64        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
-63        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
-62        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.38.jar!/:9.0.38]
-61        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.38.jar!/:9.0.38]
-60        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
-59        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
-58        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.38.jar!/:9.0.38]
-57        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.38.jar!/:9.0.38]
-56        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.38.jar!/:9.0.38]
-55        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.38.jar!/:9.0.38]
-54        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) ~[tomcat-embed-core-9.0.38.jar!/:9.0.38]
-53        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) ~[tomcat-embed-core-9.0.38.jar!/:9.0.38]
-52        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.38.jar!/:9.0.38]
-51        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.38.jar!/:9.0.38]
-50        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747) ~[tomcat-embed-core-9.0.38.jar!/:9.0.38]
-49        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[tomcat-embed-core-9.0.38.jar!/:9.0.38]
-48        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) ~[tomcat-embed-core-9.0.38.jar!/:9.0.38]
-47        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.38.jar!/:9.0.38]
-46        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) ~[tomcat-embed-core-9.0.38.jar!/:9.0.38]
-45        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) ~[tomcat-embed-core-9.0.38.jar!/:9.0.38]
-44        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.38.jar!/:9.0.38]
-43        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_111]
-42        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_111]
-41        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.38.jar!/:9.0.38]
-40        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111]
-39Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
-38
-37The last packet successfully received from the server was 15,021 milliseconds ago. The last packet sent successfully to the server was 15,023 milliseconds ago.
-36        at sun.reflect.GeneratedConstructorAccessor150.newInstance(Unknown Source) ~[na:na]
-35        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_111]
-34        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_111]
-33        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
-32        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
-31        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
-30        at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
-29        at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:538) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
-28        at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:702) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
-27        at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:641) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
-26        at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:940) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
-25        at com.mysql.cj.NativeSession.execSQL(NativeSession.java:1075) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
-24        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:930) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
-23        ... 152 common frames omitted
-22Caused by: java.net.SocketTimeoutException: Read timed out
-21        at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.8.0_111]
-20        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[na:1.8.0_111]
-19        at java.net.SocketInputStream.read(SocketInputStream.java:170) ~[na:1.8.0_111]
-18        at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_111]
-17        at com.mysql.cj.protocol.ReadAheadInputStream.fill(ReadAheadInputStream.java:107) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
-16        at com.mysql.cj.protocol.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:150) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
-15        at com.mysql.cj.protocol.ReadAheadInputStream.read(ReadAheadInputStream.java:180) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
-14        at java.io.FilterInputStream.read(FilterInputStream.java:133) ~[na:1.8.0_111]
-13        at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:64) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
-12        at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:63) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
-11        at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:45) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
-10        at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:52) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
-9        at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:41) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
-8        at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:54) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
-7        at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:44) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
-6        at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:532) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
-5        ... 157 common frames omitted

**Comment by luozuyi** [comment]
![test1](https://user-images.githubusercontent.com/29859621/112791112-63916f80-9093-11eb-8d86-4f13a8a09a74.png)

**Comment by luozuyi** [comment]
![test2](https://user-images.githubusercontent.com/29859621/112791259-b9feae00-9093-11eb-8fa4-24e4ff9636a7.png)
这是连接池的的配置

**Comment by CHYinYiHang** [comment]
大哥您这个问题解决了吗，我也出现了同样的问题

**Comment by luozuyi** [comment]
没有 一直都有问题

**Comment by luozuyi** [comment]
> 大哥您这个问题解决了吗，我也出现了同样的问题

大哥您解决了吗 我这边是偶然几天才会出现一次

**Comment by Chris2018998** [comment]
推荐有机会可以试试这个
https://github.com/Chris2018998/BeeCP

**Comment by mfl0918** [comment]
看了网上的文章，有部分说是因为数据库读写分离造成的问题，我这边也有这样的问题，偶尔出现，没有弄读写分离，具体问题还没找到

**Comment by cgyqu** [comment]
设置下`phyTimeoutMillis`

**Comment by wudidehuangtiandi** [comment]
大哥解决了吗？

**Comment by ozw999** [comment]
同问。有解决方案嘛

**Comment by kenshin614** [comment]
> 没有 一直都有问题

现在解决了没？
