### ISSUE TITLE
ClickHouse不支持group by ... limit by语法

### ISSUE THREAD

**Issue by stone5751** [alibaba/druid#4236]
查询语句如下：
`SELECT asset_id, statistics_year, statistics_month, rent_rate, average_rent
                        FROM dw_asset_operating_summary
                        WHERE rent_rate IS NOT NULL AND average_rent IS NOT NULL AND is_del = toInt8(0)
                        GROUP BY asset_id, statistics_year, statistics_month, rent_rate, average_rent
                        ORDER BY asset_id, statistics_year DESC, statistics_month DESC
                        LIMIT 1 BY asset_id`
报错如下：
`Caused by: com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'                      LIMIT 1 BY asset_id) t4 ON t3.asset_id', expect ), actual BY, pos 1630, line 21, column 34, token BY
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:573)
	at com.alibaba.druid.sql.parser.SQLParser.accept(SQLParser.java:581)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseTableSourceRest(SQLSelectParser.java:1324)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseTableSourceRest(SQLSelectParser.java:1189)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseTableSource(SQLSelectParser.java:1100)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseFrom(SQLSelectParser.java:1002)
	at com.alibaba.druid.sql.parser.SQLSelectParser.query(SQLSelectParser.java:447)
	at com.alibaba.druid.sql.parser.SQLSelectParser.query(SQLSelectParser.java:378)
	at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:61)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseTableSource(SQLSelectParser.java:1011)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseFrom(SQLSelectParser.java:1002)
	at com.alibaba.druid.sql.parser.SQLSelectParser.query(SQLSelectParser.java:447)
	at com.alibaba.druid.sql.parser.SQLSelectParser.query(SQLSelectParser.java:378)
	at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:61)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseSelect(SQLStatementParser.java:4190)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:204)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:124)
	at com.alibaba.druid.wall.WallProvider.checkInternal(WallProvider.java:630)
	at com.alibaba.druid.wall.WallProvider.check(WallProvider.java:584)
	at com.alibaba.druid.wall.WallFilter.checkInternal(WallFilter.java:826)
	... 134 common frames omitted`

**Comment by wenshao** [comment]
问题已修复，请用新版本
https://github.com/alibaba/druid/releases/tag/1.2.6
