### ISSUE TITLE
select 语句中的 参数值被当成关键字了

### ISSUE THREAD

**Issue by bingSea** [alibaba/druid#4239]
sql查询语句(SELECT account_id FROM `taobao_office`.`cloud_yunpan` WHERE dt='2021-04-12' AND target='update')中的 ’update‘ 参数值被当成关键字了，把’update‘ 换成其它值就不报错，最新版(druid-1.2.5.jar)也存在bug

**出错方法：**
com.alibaba.druid.sql.SQLUtils#parseStatements(java.lang.String, com.alibaba.druid.DbType)

**错误详情：**
`com.alibaba.druid.sql.parser.ParserException: ERROR. pos 87, line 1, column 82, token UPDATE

	at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:1093)
	at com.alibaba.druid.sql.dialect.hive.parser.HiveExprParser.primary(HiveExprParser.java:147)
	at com.alibaba.druid.sql.parser.SQLExprParser.bitXor(SQLExprParser.java:129)
	at com.alibaba.druid.sql.parser.SQLExprParser.multiplicative(SQLExprParser.java:225)
	at com.alibaba.druid.sql.parser.SQLExprParser.additive(SQLExprParser.java:2779)
	at com.alibaba.druid.sql.parser.SQLExprParser.shift(SQLExprParser.java:2825)
	at com.alibaba.druid.sql.parser.SQLExprParser.bitAnd(SQLExprParser.java:2572)
	at com.alibaba.druid.sql.parser.SQLExprParser.bitOr(SQLExprParser.java:2591)
	at com.alibaba.druid.sql.parser.SQLExprParser.relationalRest(SQLExprParser.java:3080)
	at com.alibaba.druid.sql.parser.SQLExprParser.relational(SQLExprParser.java:3068)
	at com.alibaba.druid.sql.parser.SQLExprParser.andRest(SQLExprParser.java:2919)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseWhere(SQLSelectParser.java:681)
	at com.alibaba.druid.sql.parser.SQLSelectParser.query(SQLSelectParser.java:449)
	at com.alibaba.druid.sql.parser.SQLSelectParser.query(SQLSelectParser.java:378)
	at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:61)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseSelect(SQLStatementParser.java:4190)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:204)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:562)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:584)`

**Comment by bingSea** [comment]
同一条SQL语句：
`String sql3 = "SELECT account_id FROM `taobao_logs`.`x_view` WHERE ip = '192.168.1.1' AND dt = '2021-04-14'";`

此种方式报错：
```
List<SQLStatement> stmtList = SQLUtils.parseStatements(sql, JdbcConstants.HIVE);
SQLStatement sqlStatement = stmtList.get(0);
SQLSelectStatement stmt = (SQLSelectStatement) sqlStatement;
List<SQLSelectItem> list = ((SQLSelectQueryBlock) stmt.getSelect().getQuery()).getSelectList();
```

此种方式不报错：
```
HiveSelectParser parser = new HiveSelectParser(sql);
SQLSelect select = parser.select();
List<SQLSelectItem> list = ((SQLSelectQueryBlock) select.getQuery()).getSelectList();
```


但对SQL
`SELECT account_id FROM taobao_office.cloud_yunpan WHERE dt='2021-04-12' AND target='update'`
无论使用哪种方式都报错，错误详情如下：
```
com.alibaba.druid.sql.parser.ParserException: ERROR. pos 93, line 1, column 88, token UPDATE

	at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:1093)
	at com.alibaba.druid.sql.dialect.hive.parser.HiveExprParser.primary(HiveExprParser.java:147)
	at com.alibaba.druid.sql.parser.SQLExprParser.bitXor(SQLExprParser.java:129)
	at com.alibaba.druid.sql.parser.SQLExprParser.multiplicative(SQLExprParser.java:225)
	at com.alibaba.druid.sql.parser.SQLExprParser.additive(SQLExprParser.java:2779)
	at com.alibaba.druid.sql.parser.SQLExprParser.shift(SQLExprParser.java:2825)
	at com.alibaba.druid.sql.parser.SQLExprParser.bitAnd(SQLExprParser.java:2572)
	at com.alibaba.druid.sql.parser.SQLExprParser.bitOr(SQLExprParser.java:2591)
	at com.alibaba.druid.sql.parser.SQLExprParser.relationalRest(SQLExprParser.java:3080)
	at com.alibaba.druid.sql.parser.SQLExprParser.relational(SQLExprParser.java:3068)
	at com.alibaba.druid.sql.parser.SQLExprParser.andRest(SQLExprParser.java:2919)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseWhere(SQLSelectParser.java:681)
	at com.alibaba.druid.sql.parser.SQLSelectParser.query(SQLSelectParser.java:449)
	at com.alibaba.druid.sql.parser.SQLSelectParser.query(SQLSelectParser.java:378)
	at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:61)
```

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.2.6
问题已修复，请用新版本
