### ISSUE TITLE
Druid OracleStatementParser解析oracle函数报错，请大神解决。

### ISSUE THREAD

**Issue by xuchang86** [alibaba/druid#4259]
SQL代码如下：
        String sql = "select po.device_id deviceId,to_char(xmlagg(xmlparse(content dc.full_name || ';' wellformed) order by dc.full_name).getclobval()) as classify_full_names from TABLE_A po,TABLE_B dc where po.classify_id =dc.id";
        SQLStatementParser parser = new OracleStatementParser(sql);
        List<SQLStatement> statementList = new ArrayList<SQLStatement>(2);
        parser.parseStatementList(statementList, 2);

异常信息如下：PS：试了各种版本的druid都不行，急需温少大神看看！！！个人分析了原因是因为SQL里的(content dc.full_name || ';' wellformed)这段SQL引起的报错，不知道该怎么解决，业务SQL还不能改！
com.alibaba.druid.sql.parser.ParserException: syntax error, expect ), actual IDENTIFIER pos 63, line 1, column 62, token IDENTIFIER dc
	at com.alibaba.druid.sql.parser.SQLExprParser.accept(SQLExprParser.java:4074)
	at com.alibaba.druid.sql.parser.SQLExprParser.methodRest(SQLExprParser.java:1687)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleExprParser.methodRest(OracleExprParser.java:532)
	at com.alibaba.druid.sql.parser.SQLExprParser.primaryRest(SQLExprParser.java:1382)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleExprParser.primaryRest(OracleExprParser.java:718)
	at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:1162)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleExprParser.primary(OracleExprParser.java:494)
	at com.alibaba.druid.sql.parser.SQLExprParser.expr(SQLExprParser.java:95)
	at com.alibaba.druid.sql.parser.SQLExprParser.exprList(SQLExprParser.java:1915)
	at com.alibaba.druid.sql.parser.SQLExprParser.methodRest(SQLExprParser.java:1609)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleExprParser.methodRest(OracleExprParser.java:532)
	at com.alibaba.druid.sql.parser.SQLExprParser.primaryRest(SQLExprParser.java:1382)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleExprParser.primaryRest(OracleExprParser.java:718)
	at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:1162)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleExprParser.primary(OracleExprParser.java:494)
	at com.alibaba.druid.sql.parser.SQLExprParser.expr(SQLExprParser.java:95)
	at com.alibaba.druid.sql.parser.SQLExprParser.exprList(SQLExprParser.java:1915)
	at com.alibaba.druid.sql.parser.SQLExprParser.methodRest(SQLExprParser.java:1609)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleExprParser.methodRest(OracleExprParser.java:532)
	at com.alibaba.druid.sql.parser.SQLExprParser.parseSelectItem(SQLExprParser.java:5553)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseSelectList(SQLSelectParser.java:982)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.query(OracleSelectParser.java:284)
	at com.alibaba.druid.sql.parser.SQLSelectParser.query(SQLSelectParser.java:374)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.select(OracleSelectParser.java:51)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleStatementParser.parseStatementList(OracleStatementParser.java:95)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:128)
	at com.comtop.druid.test.DruidTest.testSQL(DruidTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by fssgh** [comment]
在 application.yml中配置如下，有效。
```
dynamic:
  druid:
          wall:
            strict-syntax-check: false
```

**Comment by zhuhj1989** [comment]
> 
还是无效啊。
wall:
                  config:
                    strict-syntax-check: false
