### ISSUE TITLE
mybatis使用${}传入动态表名参数报错merge sql error

### ISSUE THREAD

**Issue by ieayoio** [alibaba/druid#4262]
使用数据库为Phoenix重客户端，
mapper内容如下
```xml
    <select id="createDataTable">
        CREATE TABLE IF NOT EXISTS hn.his_${stationId}_${year} (
            upload_time TIMESTAMP NOT NULL,
            point_id VARCHAR(100) NOT NULL,
            update_time TIMESTAMP NOT NULL,
            val DOUBLE,
        CONSTRAINT UNION_PK PRIMARY KEY (upload_time,point_id,update_time)
        ) COMPRESSION = 'SNAPPY' ,COLUMN_ENCODED_BYTES = 0, SALT_BUCKETS = 6
    </select>
```
报错信息如下：
```
merge sql error, dbType phoenix, druid-1.2.5, sql : CREATE TABLE IF NOT EXISTS hn.his_06020_2021 (
upload_time TIMESTAMP NOT NULL,
point_id VARCHAR(100) NOT NULL,
update_time TIMESTAMP NOT NULL,
val DOUBLE,
CONSTRAINT UNION_PK PRIMARY KEY (upload_time,point_id,update_time)
) COMPRESSION = 'SNAPPY' ,COLUMN_ENCODED_BYTES = 0, SALT_BUCKETS = 6
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :' ) COMPRESSION = 'SNAPPY' ,COLUMN, pos 299, line 7, column 12, token IDENTIFIER COMPRESSION
at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:576)
at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:602)
at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:113)
at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:153)
at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:126)
at com.alibaba.druid.filter.stat.StatFilter.mergeSql(StatFilter.java:156)
at com.alibaba.druid.filter.stat.StatFilter.createSqlStat(StatFilter.java:657)
at com.alibaba.druid.filter.stat.StatFilter.statementPrepareAfter(StatFilter.java:320)
at com.alibaba.druid.filter.FilterEventAdapter.connection_prepareStatement(FilterEventAdapter.java:124)
at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:568)
at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.prepareStatement(ConnectionProxyImpl.java:341)
at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:366)
at org.apache.ibatis.executor.statement.PreparedStatementHandler.instantiateStatement(PreparedStatementHandler.java:86)
at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:88)
at org.apache.ibatis.executor.statement.RoutingStatementHandler.prepare(RoutingStatementHandler.java:59)
at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:87)
at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62)
at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:325)
at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:89)
at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:76)
at jdk.internal.reflect.GeneratedMethodAccessor161.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:427)
at com.sun.proxy.$Proxy70.selectOne(Unknown Source)
at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:160)
at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:87)
at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:152)
at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:85)
at com.sun.proxy.$Proxy86.createDataTable(Unknown Source)
```

**Comment by jack-love-rose** [comment]
你这是语法问题和druid连接池没关系吧

**Comment by ieayoio** [comment]
> 你这是语法问题和druid连接池没关系吧

不是的，语法没问题，建表语句成功执行，但是后台日志会有error log
