### ISSUE TITLE
线上服务最近出现异常：GetConnectionTimeoutException: wait millis 60000, active 0, maxActive 100, creating 1

### ISSUE THREAD

**Issue by ZeroMing** [alibaba/druid#4288]
### 异常信息如下： 
```

org.springframework.transaction.CannotCreateTransactionException: Could not open JDBC Connection for transaction; nested exception is com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 60000, active 0, maxActive 100, creating 1
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:308)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.startTransaction(AbstractPlatformTransactionManager.java:400)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:572)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:360)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at com.msb.uc.admin.controller.UcLoginController$$FastClassBySpringCGLIB$$78ab8a05.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:120)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at com.msb.uc.admin.controller.UcLoginController$$EnhancerBySpringCGLIB$$41baa350.listPermissions(<generated>)
	at sun.reflect.GeneratedMethodAccessor516.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.github.xiaoymin.knife4j.spring.filter.ProductionSecurityFilter.doFilter(ProductionSecurityFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.github.xiaoymin.knife4j.spring.filter.SecurityBasicAuthFilter.doFilter(SecurityBasicAuthFilter.java:90)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:141)
	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:82)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 60000, active 0, maxActive 100, creating 1
	at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1512)
	at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1255)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1235)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1225)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:90)
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:264)
	... 120 common frames omitted
```

### 连接池配置：
```
#连接池的配置信息
    initialSize: 50
    minIdle: 5
    maxActive: 100
    ## 配置获取连接等待超时的时间
    maxWait: 60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    #validationQuery: SELECT 1 FROM DUAL
    validationQueryTimeout: 10000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
```

### 查看DB的连接数

`select substring_index(host,':' ,1) as client_ip,Command,Time from information_schema.processlist;`
```
121.89.190.206	Sleep	307
43.226.237.247	Sleep	7526
43.226.237.247	Sleep	6317
43.226.237.247	Sleep	3274
43.226.237.247	Sleep	1485
39.100.124.52	Sleep	148
121.89.190.206	Sleep	422
43.226.237.247	Sleep	2228
43.226.237.247	Sleep	4661
43.226.237.247	Sleep	210
43.226.237.247	Sleep	400
43.226.237.247	Sleep	4253
103.85.167.138	Sleep	1097
43.226.237.247	Query	0
121.89.190.206	Sleep	314
43.226.237.247	Sleep	6093
103.85.167.138	Sleep	1097
121.89.190.206	Sleep	390
43.226.237.247	Sleep	1403
43.226.237.247	Sleep	4305
43.226.237.247	Sleep	1978
43.226.237.247	Sleep	18
43.226.237.247	Sleep	18
43.226.237.247	Sleep	6837
43.226.237.247	Sleep	1306
43.226.237.247	Sleep	4939
121.89.190.206	Sleep	353
43.226.237.247	Sleep	973
43.226.237.247	Sleep	3283
103.85.167.138	Sleep	928
43.226.237.247	Sleep	2229
43.226.237.247	Sleep	971
43.226.237.247	Sleep	6795
43.226.237.247	Sleep	1787
43.226.237.247	Sleep	451
43.226.237.247	Sleep	5695
121.89.190.206	Sleep	423
43.226.237.247	Sleep	546
43.226.237.247	Sleep	388
43.226.237.247	Sleep	3997
43.226.237.247	Sleep	729
43.226.237.247	Sleep	3750
43.226.237.247	Sleep	7862
43.226.237.247	Sleep	2689
43.226.237.247	Sleep	4447
43.226.237.247	Sleep	4852
39.100.124.52	Sleep	636
43.226.237.247	Sleep	5106
43.226.237.247	Sleep	6735
43.226.237.247	Sleep	3158
43.226.237.247	Sleep	6842
121.89.190.206	Sleep	422
43.226.237.247	Sleep	447
43.226.237.247	Sleep	4490
43.226.237.247	Sleep	7854
43.226.237.247	Sleep	698
43.226.237.247	Sleep	6018
43.226.237.247	Sleep	3755
43.226.237.247	Sleep	3748
39.100.124.52	Sleep	1335
43.226.237.247	Sleep	6877
43.226.237.247	Sleep	5075
103.85.167.138	Sleep	1374
43.226.237.247	Sleep	5487
43.226.237.247	Sleep	1177
43.226.237.247	Sleep	5781
43.226.237.247	Sleep	4699
43.226.237.247	Sleep	6493
	Connect	21768026
43.226.237.247	Sleep	4951
43.226.237.247	Sleep	7856
43.226.237.247	Sleep	2476
43.226.237.247	Sleep	4029
43.226.237.247	Sleep	7005
121.89.190.206	Sleep	269
43.226.237.247	Sleep	7558
43.226.237.247	Sleep	3067
43.226.237.247	Sleep	2734
43.226.237.247	Sleep	3963
43.226.237.247	Sleep	5522
43.226.237.247	Sleep	7579
43.226.237.247	Sleep	362
43.226.237.247	Sleep	3932
43.226.237.247	Sleep	6746
43.226.237.247	Sleep	1709
43.226.237.247	Sleep	5817
43.226.237.247	Sleep	5765
43.226.237.247	Sleep	5035
43.226.237.247	Sleep	2888
39.100.124.52	Sleep	1065
43.226.237.247	Sleep	7862
121.89.190.206	Sleep	287
39.100.124.52	Sleep	875
39.100.124.52	Sleep	1244
43.226.237.247	Sleep	1181
39.99.205.213	Sleep	2515
121.89.190.206	Sleep	229
43.226.237.247	Sleep	3192
43.226.237.247	Sleep	4467
43.226.237.247	Sleep	5073
121.89.190.206	Sleep	339
39.100.124.52	Sleep	879
43.226.237.247	Sleep	7527
43.226.237.247	Sleep	3308
43.226.237.247	Sleep	3343
43.226.237.247	Sleep	430
43.226.237.247	Sleep	7850
43.226.237.247	Sleep	1168
43.226.237.247	Sleep	4717
43.226.237.247	Sleep	4708
39.100.124.52	Sleep	274
43.226.237.247	Sleep	3931
43.226.237.247	Sleep	2179
39.99.205.213	Sleep	2515
43.226.237.247	Sleep	6267
39.100.124.52	Sleep	1466
39.100.124.52	Sleep	1138
43.226.237.247	Sleep	6645
43.226.237.247	Sleep	3468
43.226.237.247	Sleep	6253
43.226.237.247	Sleep	2507
43.226.237.247	Sleep	1151
43.226.237.247	Sleep	1524
121.89.190.206	Sleep	178
43.226.237.247	Sleep	3992
43.226.237.247	Sleep	179
43.226.237.247	Sleep	1745
43.226.237.247	Sleep	5730
121.89.190.206	Sleep	363
43.226.237.247	Sleep	5241
43.226.237.247	Sleep	7309
43.226.237.247	Sleep	1544
43.226.237.247	Sleep	2943
43.226.237.247	Sleep	2215
43.226.237.247	Sleep	1752
43.226.237.247	Sleep	2743
43.226.237.247	Sleep	1490
```

> select count(1) from information_schema.processlist WHERE Command = 'sleep' and Host like  '43.226.237.247%';
看到有101个连接都是处于Sleep状态的
```
101
```

> select client_ip,count(client_ip) as client_num from (select substring_index(host,':' ,1) as client_ip from information_schema.processlist ) as connect_info group by client_ip order by client_num desc;

```
43.226.237.247	103
121.89.190.206	13
39.100.124.52	10
103.85.167.138	4
39.99.205.213	2
```

### mysql的错误日志：
基本就是Got timeout reading communication packets异常
```
2021-05-27T17:33:14.277254Z 1517805 [Note] Aborted connection 1517805 to db: 'xxxxx' user: 'xxxxx' host: '43.226.237.247' (Got timeout reading communication packets)
2021-05-27T17:33:41.422182Z 1517719 [Note] Aborted connection 1517719 to db: 'xxxxx' user: 'xxxxx' host: '103.85.167.138' (Got an error reading communication packets)
2021-05-27T17:34:52.581244Z 1517807 [Note] Aborted connection 1517807 to db: 'xxxxx' user: 'xxxxx' host: '43.226.237.247' (Got timeout reading communication packets)
2021-05-27T17:36:30.885265Z 1517810 [Note] Aborted connection 1517810 to db: 'xxxxx' user: 'xxxxx' host: '43.226.237.247' (Got timeout reading communication packets)
2021-05-27T17:37:03.653254Z 1517811 [Note] Aborted connection 1517811 to db: 'xxxxx' user: 'xxxxx' host: '43.226.237.247' (Got timeout reading communication packets)
2021-05-27T17:37:03.653254Z 1517812 [Note] Aborted connection 1517812 to db: 'xxxxx' user: 'xxxxx' host: '43.226.237.247' (Got timeout reading communication packets)
2021-05-27T17:37:36.421233Z 1517813 [Note] Aborted connection 1517813 to db: 'xxxxx' user: 'xxxxx' host: '43.226.237.247' (Got timeout reading communication packets)
2021-05-27T17:40:53.029263Z 1517815 [Note] Aborted connection 1517815 to db: 'xxxxx' user: 'xxxxx' host: '43.226.237.247' (Got timeout reading communication packets)
2021-05-27T17:41:35.013302Z 1517816 [Note] Aborted connection 1517816 to db: 'xxxxx' user: 'xxxxx' host: '43.226.237.247' (Got timeout reading communication packets)
2021-05-27T17:42:47.717251Z 1517800 [Note] Aborted connection 1517800 to db: 'xxxxx' user: 'xxxxx' host: '43.226.237.247' (Got timeout reading communication packets)

```

### 一些前提：
1. 看有些资料说处于sleep状态的连接，是由于客户端没有释放连接，但是连接池的配置应该是没啥问题的，就正常的配置
2. 之前看到有人提过类似的issue，但是没有关掉，希望大佬给看看

**Comment by ZeroMing** [comment]
追加一下，版本信息：
Druid: 1.1.10
mysql：7.7.30
jdbc驱动： 6.0.6

**Comment by haien** [comment]
同样的问题
版本1.1.9

**Comment by majinding** [comment]
同样的问题 
版本 1.0.11

**Comment by ZeroMing** [comment]
> 同样的问题
> 版本1.1.9

后来什么结果了，我这边后续没发现问题，可能也是物理连接的问题，或者网络问题

**Comment by ZeroMing** [comment]
> 同样的问题
> 版本 1.0.11

后来什么结果，有排查到框架问题么，还是网络延迟问题

**Comment by majinding** [comment]
没办法, 我已经弃用druid, 脱离苦海了

**Comment by ZeroMing** [comment]
> 没办法, 我已经弃用druid, 脱离苦海了

改用什么框架了，Spring官方的的那个么

**Comment by majinding** [comment]
Hikari

> > 没办法, 我已经弃用druid, 脱离苦海了
> 
> 改用什么框架了，Spring官方的的那个么

**Comment by Elietio** [comment]
创建连接的线程socket阻塞了，导致无法获取创建新的连接
可以试一下设一下jdbc timeout
Oracle
`connectionProperties: oracle.net.CONNECT_TIMEOUT=60000;oracle.jdbc.ReadTimeout=300000
`
MySQL
`url: jdbc:mysql://ip:port/db?connectTimeout=60000&socketTimeout=300000`
不太好复现，没法验证实际效果，开启KeepAlive和配置timeout之后反正是没遇到过了

**Comment by ieayoio** [comment]
Apache Phoenix

**Comment by ieayoio** [comment]
项目已经出现很多次，也升级到最新的1.2.8了， Apache Phoenix

**Comment by ieayoio** [comment]
```
PersistenceException:
### Error querying database. Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 60000, active 7, maxActive 400, creating 1, createElapseMillis 120063, runningSqlCount 2
```

**Comment by peak-wind** [comment]
升级之后，还有出现这个问题吗？

**Comment by peak-wind** [comment]
> 项目已经出现很多次，也升级到最新的1.2.8了， Apache Phoenix

最后解决了吗？

**Comment by kiwimg** [comment]
最后解决了吗？

**Comment by ZeroMing** [comment]
> 最后解决了吗？

没有，感觉和物理环境有点关系。可以追一下源码。或者换其他连接池吧

**Comment by wenshao** [comment]
从出错信息来看，无法创建链接，这种情况看下网络环境，数据库连不上了
