### ISSUE TITLE
sql injection violation, dbType mysql, druid-version 1.2.5, comment not allow 

### ISSUE THREAD

**Issue by ipengyo** [alibaba/druid#4295]
filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            enable: true
            multi-statement-allow: true
            comment-allow: true

----------

无效

**Comment by wenshao** [comment]
完整SQL发一下

**Comment by javase** [comment]
我也遇到了类似的问题，报错如下：`Caused by: java.sql.SQLException: sql injection violation, dbType mysql, druid-version 1.2.11, comment not allow : SELECT info.* FROM   app_product_info info, app_product_redeem_rule_config rule LEFT JOIN app_product_user user ON rule.id = user.rule_id WHERE info.id = rule.product_id AND info.del_flag = 0 AND rule.del_flag = 0       AND rule.show_end_time >= now() AND rule.type = ? AND rule.show_start_time <= now()       AND if(user.uid IS NOT NULL, ? = user.uid, 1 = 1) GROUP BY info.id ORDER BY rule.sort DESC, info.update_time DESC 
-- #pageable

	at com.alibaba.druid.wall.WallFilter.checkInternal(WallFilter.java:835)
	at com.alibaba.druid.wall.WallFilter.connection_prepareStatement(WallFilter.java:324)`
配置了：comment-allow，没有效果。

**Comment by javase** [comment]
我也遇到了类似的问题，报错如下：
```sql
Caused by: java.sql.SQLException: sql injection violation, dbType mysql, druid-version 1.2.11, comment not allow :
```
尝试设置了：comment-allow: true，不起作用

**Comment by javase** [comment]
后来把`Jpa Pageable`分页里的`-- #pageable`给删除掉，然后恢复了正常。

**Comment by MisterPan** [comment]
filter:
    stat:
      enabled: true
      log-slow-sql: true
      slow-sql-millis: 1000
      merge-sql: false
    wall:
      config:
        multi-statement-allow: true
        comment-allow: true
      enabled: true
我这样修改之后配置生效了

**Comment by MisterPan** [comment]
`  filter:
    stat:
      enabled: true
      log-slow-sql: true
      slow-sql-millis: 1000
      merge-sql: false
    wall:
      config:
        enable: true
        multi-statement-allow: true
        comment-allow: true
      enabled: true`
我这样修改之后生效了

**Comment by MisterPan** [comment]
```
 filter:
    stat:
      enabled: true
      log-slow-sql: true
      slow-sql-millis: 1000
      merge-sql: false
    wall:
      config:
        multi-statement-allow: true
        comment-allow: true
      enabled: true ```

**Comment by MisterPan** [comment]
```
 filter:
    stat:
      enabled: true
      log-slow-sql: true
      slow-sql-millis: 1000
      merge-sql: false
    wall:
      config:
        multi-statement-allow: true
        comment-allow: true
      enabled: true
```
可以这样修改试试
