### ISSUE TITLE
parser.parseStatement() 支持Hive的 cache 解析吗

### ISSUE THREAD

**Issue by gbsmd** [alibaba/druid#4323]
sql = cache table table1 as select * from table3;
----------------------------------------------------
code:
SQLStatementParser parser = SQLParserUtils.createSQLStatementParser(sql, JdbcUtils.HIVE);
SQLStatement sqlStatement = parser.parseStatement();
----------------------------------------------------
error:
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'cache table table1 as select *, pos 5, line 1, column 1, token IDENTIFIER cache
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:576) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:602) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:4535) ~[druid-1.2.6.jar:1.2.6]

**Comment by wenshao** [comment]
语法文档链接提供一下

**Comment by gbsmd** [comment]
> 语法文档链接提供一下

不好意思，cache table 和 uncache table 好像不属于 Hive，是Spark SQL的语法
语法文档：http://spark.apache.org/docs/latest/sql-ref-syntax-aux-cache-cache-table.html
不知道类似这种如何处理
