### ISSUE TITLE
为什么这个sql解析失败了呢， ON DUPLICATE KEY UPDATE

### ISSUE THREAD

**Issue by xuancheng1996** [alibaba/druid#4352]
Caused by: java.sql.SQLException: sql injection violation, dbType postgresql, , druid-version 1.2.5, syntax error: syntax error, error in :'?, ?) ON DUPLICATE KEY UPDATE login_tim, pos 95, line 1, column 87, token IDENTIFIER DUPLICATE : insert into sys_web_common_device (user_id, device_ip, login_time) values(?, ?, ?) ON DUPLICATE KEY UPDATE login_time = ?
	at com.alibaba.druid.wall.WallFilter.checkInternal(WallFilter.java:849) ~[druid-1.2.5.jar:1.2.5]
	at com.alibaba.druid.wall.WallFilter.connection_prepareStatement(WallFilter.java:292) ~[druid-1.2.5.jar:1.2.5]
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:568) ~[druid-1.2.5.jar:1.2.5]
	at com.alibaba.druid.filter.FilterAdapter.connection_prepareStatement(FilterAdapter.java:930) ~[druid-1.2.5.jar:1.2.5]
	at com.alibaba.druid.filter.FilterEventAdapter.connection_prepareStatement(FilterEventAdapter.java:122) ~[druid-1.2.5.jar:1.2.5]
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:568) ~[druid-1.2.5.jar:1.2.5]
	at com.alibaba.druid.filter.FilterAdapter.connection_prepareStatement(FilterAdapter.java:930) ~[druid-1.2.5.jar:1.2.5]
	at com.alibaba.druid.filter.FilterEventAdapter.connection_prepareStatement(FilterEventAdapter.java:122) ~[druid-1.2.5.jar:1.2.5]
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:568) ~[druid-1.2.5.jar:1.2.5]
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.prepareStatement(ConnectionProxyImpl.java:341) ~[druid-1.2.5.jar:1.2.5]
	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:351) ~[druid-1.2.5.jar:1.2.5]
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.instantiateStatement(PreparedStatementHandler.java:86) ~[mybatis-3.5.6.jar:3.5.6]
	at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:88) ~[mybatis-3.5.6.jar:3.5.6]
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.prepare(RoutingStatementHandler.java:59) ~[mybatis-3.5.6.jar:3.5.6]
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:87) ~[mybatis-3.5.6.jar:3.5.6]
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:49) ~[mybatis-3.5.6.jar:3.5.6]
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117) ~[mybatis-3.5.6.jar:3.5.6]
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76) ~[mybatis-3.5.6.jar:3.5.6]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197) ~[mybatis-3.5.6.jar:3.5.6]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:184) ~[mybatis-3.5.6.jar:3.5.6]
	at sun.reflect.GeneratedMethodAccessor384.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426) ~[mybatis-spring-2.0.4.jar:2.0.4]
	... 119 common frames omitted
Caused by: com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'?, ?) ON DUPLICATE KEY UPDATE login_tim, pos 95, line 1, column 87, token IDENTIFIER DUPLICATE
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:573) ~[druid-1.2.5.jar:1.2.5]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:602) ~[druid-1.2.5.jar:1.2.5]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:124) ~[druid-1.2.5.jar:1.2.5]
	at com.alibaba.druid.wall.WallProvider.checkInternal(WallProvider.java:630) ~[druid-1.2.5.jar:1.2.5]
	at com.alibaba.druid.wall.WallProvider.check(WallProvider.java:584) ~[druid-1.2.5.jar:1.2.5]
	at com.alibaba.druid.wall.WallFilter.checkInternal(WallFilter.java:826) ~[druid-1.2.5.jar:1.2.5]
	at com.alibaba.druid.wall.WallFilter.connection_prepareStatement(WallFilter.java:292) ~[druid-1.2.5.jar:1.2.5]

**Comment by xuancheng1996** [comment]
postgresql不支持
