### ISSUE TITLE
PG

### ISSUE THREAD

**Issue by zycgit** [alibaba/druid#4417]
java.lang.ClassCastException: com.alibaba.druid.sql.visitor.SQLASTOutputVisitor cannot be cast to com.alibaba.druid.sql.dialect.postgresql.visitor.PGASTVisitor
	at com.alibaba.druid.sql.dialect.postgresql.ast.stmt.PGCreateSchemaStatement.accept0(PGCreateSchemaStatement.java:64)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:49)
	at com.alibaba.druid.sql.SQLUtils.toSQLString(SQLUtils.java:112)
	at com.alibaba.druid.sql.SQLUtils.toSQLString(SQLUtils.java:83)
	at com.alibaba.druid.sql.ast.SQLStatementImpl.toString(SQLStatementImpl.java:48)

**Comment by newbens** [comment]
请问解决了吗
