### ISSUE TITLE
SqlServer driver validateConnection false

### ISSUE THREAD

**Issue by deadwind4** [alibaba/druid#4451]
`		<dependency>
			<groupId>com.microsoft.sqlserver</groupId>
			<artifactId>mssql-jdbc</artifactId>
			<version>9.2.1.jre8</version>
		</dependency
		<dependency>
			<groupId>com.alibaba</groupId>
			<artifactId>druid</artifactId>
			<version>1.2.6</version>
		</dependency
`

2021-09-13 16:01:24,849 ERROR com.alibaba.druid.pool.DruidDataSource                       [] - create connection SQLException, url: jdbc:sqlserver://172.16.101.246:1433;DatabaseName=db_test, errorCode 0, state null
java.sql.SQLException: validateConnection false
at com.alibaba.druid.pool.DruidAbstractDataSource.validateConnection(DruidAbstractDataSource.java:1418) ~[flinkx-connector-sqlserver-1.12_test_4.3.x.jar:?]
at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1733) ~[flinkx-connector-sqlserver-1.12_test_4.3.x.jar:?]
at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2801) [flinkx-connector-sqlserver-1.12_test_4.3.x.jar:?]
Caused by: java.lang.NullPointerException
at com.microsoft.sqlserver.jdbc.SQLServerStatement.ensureSQLSyntax(SQLServerStatement.java:778) ~[flinkx-connector-sqlserver-1.12_test_4.3.x.jar:?]
at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:822) ~[flinkx-connector-sqlserver-1.12_test_4.3.x.jar:?]
at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:767) ~[flinkx-connector-sqlserver-1.12_test_4.3.x.jar:?]
at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7418) ~[flinkx-connector-sqlserver-1.12_test_4.3.x.jar:?]
at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3272) ~[flinkx-connector-sqlserver-1.12_test_4.3.x.jar:?]
at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247) ~[flinkx-connector-sqlserver-1.12_test_4.3.x.jar:?]
at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222) ~[flinkx-connector-sqlserver-1.12_test_4.3.x.jar:?]
at com.microsoft.sqlserver.jdbc.SQLServerStatement.execute(SQLServerStatement.java:743) ~[flinkx-connector-sqlserver-1.12_test_4.3.x.jar:?]
at com.alibaba.druid.pool.vendor.MSSQLValidConnectionChecker.isValidConnection(MSSQLValidConnectionChecker.java:50) ~[flinkx-connector-sqlserver-1.12_test_4.3.x.jar:?]
at com.alibaba.druid.pool.DruidAbstractDataSource.validateConnection(DruidAbstractDataSource.java:1398) ~[flinkx-connector-sqlserver-1.12_test_4.3.x.jar:?]
... 2 more

**Comment by TryBin03** [comment]
今天也遇到了，druid版本换成 1.2.5 解决

**Comment by smile2014** [comment]
今天也遇到了，druid版本换成低版本就完事，这个项目是不是已经没人维护了。

**Comment by Johnson-Jia** [comment]
一样的问题，重启后就好了。


[2025-09-18 19:17:14.471 ERROR] [] [Druid-ConnectionPool-Create-1027228057] {com.alibaba.druid.pool.DruidDataSource:2592}-create connection SQLException, url: jdbc:postgresql://10.12.7.130:5432/main05, errorCode 0, state null
java.sql.SQLException: validateConnection false
	at com.alibaba.druid.pool.DruidAbstractDataSource.validateConnection(DruidAbstractDataSource.java:1460)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1828)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2590)
Caused by: java.lang.IllegalStateException: Timer already cancelled.
	at java.base/java.util.Timer.sched(Timer.java:409)
	at java.base/java.util.Timer.schedule(Timer.java:205)
	at org.postgresql.jdbc.PgConnection.addTimerTask(PgConnection.java:1363)
	at org.postgresql.jdbc.PgStatement.startTimer(PgStatement.java:993)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:517)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:435)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:357)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:342)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:318)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:267)
	at com.alibaba.druid.pool.ValidConnectionCheckerAdapter.execValidQuery(ValidConnectionCheckerAdapter.java:68)
	at com.alibaba.druid.pool.vendor.PGValidConnectionChecker.isValidConnection(PGValidConnectionChecker.java:48)
	at com.alibaba.druid.pool.DruidAbstractDataSource.validateConnection(DruidAbstractDataSource.java:1436)
	... 2 common frames omitted
