### ISSUE TITLE
报nullpointexception异常

### ISSUE THREAD

**Issue by yanghaoustc** [alibaba/druid#4570]
Caused by: java.lang.NullPointerException
        at com.mysql.cj.AbstractQuery.stopQueryTimer(AbstractQuery.java:217)
        at com.mysql.cj.jdbc.StatementImpl.stopQueryTimer(StatementImpl.java:657)
        at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1229)
        at com.alibaba.druid.pool.DruidPooledStatement.executeQuery(DruidPooledStatement.java:297)
看着像是获取connection的session在stopQueryTimer中去执行getCancelTimer()时因为session为null报的异常，好奇什么情况下connection的session会为null导致这个异常，求解答，谢谢！！

**Comment by yanghaoustc** [comment]
是个偶发异常

**Comment by yanghaoustc** [comment]
版本是8.0.11

**Comment by wenshao** [comment]
升级mysql驱动版本试试看

**Comment by yanghaoustc** [comment]
> 升级mysql驱动版本试试看

偶发异常，已经无法复现了，但还是谢谢回答

**Comment by jathams** [comment]
如果数据库服务宕机，是不是session可能为空

**Comment by acmcee** [comment]
我也遇到了

druidDataSource.setQueryTimeout(30);
druidDataSource.setSocketTimeout(2000);


当SocketTime 小于 QueryTime ，且SQL执行超过了SocketTime 就会出现上面的异常。

建议将SocketTimeout设置的比QueryTimeout 大一点

**Comment by zongbintu** [comment]
我也遇到了这个问题，查看官方文档后
发现在Connector/J 9.1.0修复了
[MySQL bug](https://bugs.mysql.com/bug.php?id=108415)
[PR](https://github.com/mysql/mysql-connector-j/commit/1b317cf2eded59e946234dbc729a42d7a5698114#diff-aac07aefec754086f5c344e2c233862f6a611c739b5647fd456c1b77d3577c79)
