### ISSUE TITLE
ClickHouse WITH 语句SQL Parser报错

### ISSUE THREAD

**Issue by ffffffcode** [alibaba/druid#4579]
Caused by: com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'                                 arrayFilter(x -> x != 0, array', expect ), actual (, pos 138, line 4, column 47, token (
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:841) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.sql.parser.SQLParser.accept(SQLParser.java:849) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseWith(SQLSelectParser.java:597) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:57) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseTableSource(SQLSelectParser.java:1078) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseFrom(SQLSelectParser.java:1069) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.sql.parser.SQLSelectParser.query(SQLSelectParser.java:470) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:61) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseSelect(SQLStatementParser.java:4334) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:213) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:125) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.wall.WallProvider.checkInternal(WallProvider.java:630) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.wall.WallProvider.check(WallProvider.java:584) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.wall.WallFilter.checkInternal(WallFilter.java:829) ~[druid-1.2.8.jar:1.2.8]
	... 174 common frames omitted

---
WITH
    arrayReduce('min',
                arrayFilter(x -> x != 0, array(indexOf(router, 'banner_click'), indexOf(router, 'zone_click'),
                                               indexOf(router, 'popups_click'),
                                               indexOf(router, 'user_share')))) AS shortest_index

**Comment by nanjsun** [comment]
同遇到此问题，请问是怎么解决的呢？
