### ISSUE TITLE
1.2.5版本，线上应用假死，线程卡在notEmpty.await()方法

### ISSUE THREAD

**Issue by Delics** [alibaba/druid#4584]
druid参数均为默认，jstack线程信息如下：

> "XNIO-1 task-89" #187 prio=5 os_prio=0 cpu=953.53ms elapsed=2033.25s tid=0x00007fed2801d800 nid=0x528d waiting on condition  [0x00007feac47bd000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.12/Native Method)
	- parking to wait for  <0x00000000c0cb4220> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.12/LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@11.0.12/AbstractQueuedSynchronizer.java:2081)
	at com.alibaba.druid.pool.DruidDataSource.takeLast(DruidDataSource.java:2185)
	at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1678)
	at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1415)

求教如何解决此问题 ，多谢！（配置maxWait参数，或升级版本是否可以避免）

**Comment by zhangshuai0220** [comment]
怎么解决的啊 也遇到这个问题

**Comment by cuianbing** [comment]
maxWait默认值是-1，会一直等待导致线程假死。设置一个超时时间就可以了。还有根据业务设置maxActive参数为一个合适的数值，这个值默认为8
