### ISSUE TITLE
Parsing some SQL statements resulted in stack errors

### ISSUE THREAD

**Issue by lzx4627** [alibaba/druid#4587]
```
String sql = "  select  * from (select distinct x.* from cdr_ss_yw0000  a where  to_char(to_date(a.ssqsrq, 'yyyy-MM-dd'), 'yyyyMMdd') between to_char(to_date('2021-07-01', 'yyyy-MM-dd'), 'yyyyMMdd') AND to_char(to_date('2021-09-30', 'YYYY-MM-DD'), 'yyyyMMdd') ) x ,  cdr_bm_brxxb0 y where x.brid00=y.brid00";
MySqlStatementParser parser = new MySqlStatementParser(sql);
SQLStatement sqlStatement = parser.parseStatement();
MySqlSchemaStatVisitor visitor = new MySqlSchemaStatVisitor();
sqlStatement.accept(visitor);
Map<TableStat.Name, TableStat> tableStatMap = visitor.getTables();
for(Map.Entry<TableStat.Name, TableStat> tableStatEntry: tableStatMap.entrySet()){
    System.out.println("表名：" + tableStatEntry.getKey().getName());
    System.out.println("操作名：" + tableStatEntry.getValue());
}
```
I found through debugging that there was a stack error when `sqlStatement.accept(visitor);`

**Comment by lzx4627** [comment]
error msg

> Exception in thread "main" java.lang.StackOverflowError
> at com.alibaba.druid.sql.ast.statement.SQLSelectQueryBlock.findSelectItem(SQLSelectQueryBlock.java:1090)
> at com.alibaba.druid.sql.ast.statement.SQLSelectQueryBlock.resolveColum(SQLSelectQueryBlock.java:1202)
> at com.alibaba.druid.sql.ast.statement.SQLSelectQueryBlock.findColumn(SQLSelectQueryBlock.java:1189)
> at com.alibaba.druid.sql.ast.statement.SQLSubqueryTableSource.findColumn(SQLSubqueryTableSource.java:157)
> at com.alibaba.druid.sql.ast.statement.SQLSelectItem.match(SQLSelectItem.java:280)
