### ISSUE TITLE
执行语句 desc station name  报错了

### ISSUE THREAD

**Issue by musingsz** [alibaba/druid#463]
filters=mergeStat,slf4j   执行语句 desc station name  报错了

view sourceprint?
01
14:23:45.519 [main] [ERROR](StatFilter.java:147) merge sql error, dbType mysql, sql :
02
desc station name
03
com.alibaba.druid.sql.parser.ParserException: syntax error, IDENTIFIER name, pos 17
04
at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:299) ~[druid-2.10.jar:na]
05
at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:107) ~[druid-2.10.jar:na]
06
at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:102) ~[druid-2.10.jar:na]
07
at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:53) ~[druid-2.10.jar:na]
08
at com.alibaba.druid.filter.stat.StatFilter.mergeSql(StatFilter.java:145) [druid-2.10.jar:na]
09
at com.alibaba.druid.filter.stat.StatFilter.createSqlStat(StatFilter.java:629) [druid-2.10.jar:na]
10
at com.alibaba.druid.filter.stat.StatFilter.internalBeforeStatementExecute(StatFilter.java:397) [druid-2.10.jar:na]
11
at com.alibaba.druid.filter.stat.StatFilter.statementExecuteQueryBefore(StatFilter.java:335) [druid-2.10.jar:na]
12
at com.alibaba.druid.filter.FilterEventAdapter.statement_executeQuery(FilterEventAdapter.java:299) [druid-2.10.jar:na]
13
at com.alibaba.druid.filter.FilterChainImpl.statement_executeQuery(FilterChainImpl.java:2358) [druid-2.10.jar:na]
14
at com.alibaba.druid.proxy.jdbc.StatementProxyImpl.executeQuery(StatementProxyImpl.java:211) [druid-2.10.jar:na]
15
at com.alibaba.druid.pool.DruidPooledStatement.executeQuery(DruidPooledStatement.java:143) [druid-2.10.jar:na]

**Comment by lizongbo** [comment]
请使用最新版验证，解析功能正常。
` ` `
@Test
    public void test_desc() throws Exception {
        for (DbType dbType : new DbType[]{DbType.mysql}) {
            String sql = "desc station name";
            SQLStatementParser parser = SQLParserUtils.createSQLStatementParser(sql, dbType);
            SQLStatement statement = parser.parseStatement();
           // OracleMultiInsertStatement multiInsertStatement = (OracleMultiInsertStatement) statement;
            System.out.println("原始的sql===" + sql);
            System.out.println("statement===" + statement.getClass());
            String newSql = statement.toString();
            System.out.println("生成的sql===" + newSql);

        }
    } 
  @Test
    public void test_create() throws Exception {
        for (DbType dbType : new DbType[]{DbType.mysql}) {
            String sql = "create table if not exists logback_2013_11 (\n"
                + "id int(11) NOT NULL AUTO_INCREMENT ,\n"
                + "msg varchar(5000) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,\n"
                + "logger varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,\n"
                + "thread varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,\n"
                + "time datetime NULL DEFAULT NULL ,\n"
                + "lv int(11) NULL DEFAULT NULL ,\n"
                + "PRIMARY KEY (id),\n"
                + "INDEX lv (lv) USING BTREE\n"
                + ")\n"
                + "ENGINE=MyISAM\n"
                + "DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci\n"
                + "AUTO_INCREMENT=1\n"
                + "CHECKSUM=0\n"
                + "ROW_FORMAT=DYNAMIC\n"
                + "DELAY_KEY_WRITE=0\n"
                + ";";
            SQLStatementParser parser = SQLParserUtils.createSQLStatementParser(sql, dbType);
            SQLStatement statement = parser.parseStatement();
           // OracleMultiInsertStatement multiInsertStatement = (OracleMultiInsertStatement) statement;
            System.out.println("原始的sql===" + sql);
            System.out.println("statement===" + statement.getClass());
            String newSql = statement.toString();
            System.out.println("生成的sql===" + newSql);

        }
    }
` ` `
执行结果
` ` `
生成的sql===DESC station name
生成的sql===CREATE TABLE IF NOT EXISTS logback_2013_11 (
	id int(11) NOT NULL AUTO_INCREMENT,
	msg varchar(5000) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
	logger varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
	thread varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
	time datetime NULL DEFAULT NULL,
	lv int(11) NULL DEFAULT NULL,
	PRIMARY KEY (id),
	INDEX lv USING BTREE(lv)
) ENGINE = MyISAM CHARACTER SET = utf8 COLLATE = utf8_general_ci AUTO_INCREMENT = 1 CHECKSUM = 0 ROW_FORMAT = DYNAMIC DELAY_KEY_WRITE = 0

` ` `
