### ISSUE TITLE
Function quantile(level)(field) in clickhouse is not supported 

### ISSUE THREAD

**Issue by aronica** [alibaba/druid#4646]
Original SQL
`SELECT quantile(0.25)(1) AS p25_t1`

SQL parse exception stacktrace.

```
com.alibaba.druid.sql.parser.ParserException: TODO pos 23, line 1, column 23, token LITERAL_INT
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:593)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:114)
```

**Comment by aronica** [comment]
> Original SQL `SELECT quantile(0.25)(1) AS p25_t1`
> 
> SQL parse exception stacktrace.
> 
> ```
> com.alibaba.druid.sql.parser.ParserException: TODO pos 23, line 1, column 23, token LITERAL_INT
> 	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:593)
> 	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:114)
> ```

Version-1.2.8
