### ISSUE TITLE
JSONWriter 不支持java.time.LocalDateTime

### ISSUE THREAD

**Issue by MyDreaming** [alibaba/druid#4700]
版本1.2.8   
Caused by: java.lang.IllegalArgumentException: not support type : class java.time.LocalDateTime
	at com.alibaba.druid.support.json.JSONWriter.writeObject(JSONWriter.java:138)
	at com.alibaba.druid.support.json.JSONWriter.writeMap(JSONWriter.java:298)
	at com.alibaba.druid.support.json.JSONWriter.writeObject(JSONWriter.java:129)
	at com.alibaba.druid.support.json.JSONUtils.toJSONString(JSONUtils.java:22)

![image](https://user-images.githubusercontent.com/3348780/156513089-d4477244-cfb6-4527-a29e-794c8032aa6a.png)

**Comment by lizongbo** [comment]
这个看上去是你用错类了，这个json组件是很轻量的仅供druid自身使用的，你应该是使用fastjson这些组件来序列化对象。
