### ISSUE TITLE
pgsql 的百分号下划线查询处理 escape 关键字

### ISSUE THREAD

**Issue by imkyoei** [alibaba/druid#4703]
因为要实现pgSql中的百分号和下划线的字符的查询处理，所以使用了escape 关键字。但是druid 不能识别这个关键字，直接报错了.
所以有什么其他方式实现这个功能的吗？

### Cause: com.alibaba.druid.sql.parser.ParserException: syntax error, error in :''%') escape '/'
         
         , pos 984, line 33, column 58, token ESCAPE
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:96)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
	at com.sun.proxy.$Proxy89.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:224)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:147)

**Comment by AlexiosYan** [comment]
请问有解决方案了吗 我也遇到了一样的问题

**Comment by wuyuweixin** [comment]
https://github.com/alibaba/druid/issues/6413
