### ISSUE TITLE
SQLUtils.parseStatements无法解析clickhouse语法GLOBAL JOIN

### ISSUE THREAD

**Issue by Sirius7zs** [alibaba/druid#4755]
版本：1.2.8

sql:
 select * from test1 s
        global join test2 o
        on s.org_id = o.org_id
        where s.verson =1
        and o.state in (0,3)
        limit 50;

Caused by: java.sql.SQLException: sql injection violation, dbType clickhouse, , druid-version 1.2.8, syntax error: not supported.pos 60, line 2, column 10, token GLOBAL :
        at com.alibaba.druid.wall.WallFilter.checkInternal(WallFilter.java:852)
        at com.alibaba.druid.wall.WallFilter.connection_prepareStatement(WallFilter.java:295)
        at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:568)
        at com.alibaba.druid.filter.FilterAdapter.connection_prepareStatement(FilterAdapter.java:930)
        at com.alibaba.druid.filter.FilterEventAdapter.connection_prepareStatement(FilterEventAdapter.java:122)
        at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:568)
        at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.prepareStatement(ConnectionProxyImpl.java:341)
        at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:377)
        at org.apache.ibatis.executor.statement.PreparedStatementHandler.instantiateStatement(PreparedStatementHandler.java:86)
        at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:88)
        at org.apache.ibatis.executor.statement.RoutingStatementHandler.prepare(RoutingStatementHandler.java:59)
        at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:87)
        at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62)
        at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
        at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
        at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
        at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
        at sun.reflect.GeneratedMethodAccessor166.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
        at com.xiaomi.youpin.cat.plugins.mybatis.CatMybatisInterceptor.intercept(CatMybatisInterceptor.java:58)
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
        at com.sun.proxy.$Proxy190.query(Unknown Source)
        ... 26 common frames omitted
Caused by: com.alibaba.druid.sql.parser.ParserException: not supported.pos 60, line 2, column 10, token GLOBAL
        at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:623)
        at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:125)
        at com.alibaba.druid.wall.WallProvider.checkInternal(WallProvider.java:630)
        at com.alibaba.druid.wall.WallProvider.check(WallProvider.java:584)
        at com.alibaba.druid.wall.WallFilter.checkInternal(WallFilter.java:829)
        at com.alibaba.druid.wall.WallFilter.connection_prepareStatement(WallFilter.java:295)
        at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:568)
        at com.alibaba.druid.filter.FilterAdapter.connection_prepareStatement(FilterAdapter.java:930)
        at com.alibaba.druid.filter.FilterEventAdapter.connection_prepareStatement(FilterEventAdapter.java:122)
        at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:568)
        at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.prepareStatement(ConnectionProxyImpl.java:341)
        at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:377)

**Comment by Gaobutian** [comment]
一样的问题，不是说1.2.8修复了吗
