### ISSUE TITLE
Pgsql ParserExecption 

### ISSUE THREAD

**Issue by capitalR** [alibaba/druid#4762]
sql语句:SELECT n.nspname, c.relname, c.relkind FROM pg_class c LEFT JOIN pg_namespace n ON n.oid = c.relnamespace WHERE c.relkind = ANY ('{r,v,m}'::char[])  ORDER BY n.nspname, c.relname

com.alibaba.druid.sql.parser.ParserException: syntax error, expect ), actual LITERAL_CHARS pos 138, line 1, column 130, token LITERAL_CHARS {r,v,m}
	at com.alibaba.druid.sql.parser.SQLExprParser.accept(SQLExprParser.java:4567) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.sql.parser.SQLExprParser.parseAny(SQLExprParser.java:1407) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:1066) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.sql.dialect.postgresql.parser.PGExprParser.primary(PGExprParser.java:152) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.sql.parser.SQLExprParser.bitXor(SQLExprParser.java:130) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.sql.parser.SQLExprParser.multiplicative(SQLExprParser.java:226) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.sql.parser.SQLExprParser.additive(SQLExprParser.java:3211) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.sql.parser.SQLExprParser.shift(SQLExprParser.java:3257) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.sql.parser.SQLExprParser.bitAnd(SQLExprParser.java:2987) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.sql.parser.SQLExprParser.bitOr(SQLExprParser.java:3006) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseWhere(SQLSelectParser.java:677) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.sql.dialect.postgresql.parser.PGSelectParser.query(PGSelectParser.java:133) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:61) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.sql.dialect.postgresql.parser.PGSQLStatementParser.parseSelect(PGSQLStatementParser.java:418) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.sql.dialect.postgresql.parser.PGSQLStatementParser.parseSelect(PGSQLStatementParser.java:30) ~[druid-1.2.8.jar:1.2.8]

**Comment by capitalR** [comment]
数据库能成功执行
![image](https://user-images.githubusercontent.com/18274486/164396673-f380d1fe-11b7-4ce6-b4ad-8513df5352be.png)

**Comment by Lijiaqi1992** [comment]
我也遇到了类似的问题，这个报错是因为语法解析错误，syntax error, expect ), actual LITERAL_CHARS ，它期望是右括号，但是却拿到了 字符串。看你的durid应该是老版本，可以先升级到最新版试试。还有一种掩耳盗铃的处理方法，就是不启用 stat和wall过滤器

**Comment by Lijiaqi1992** [comment]
我也遇到了类似的问题，这个报错是因为语法解析错误，syntax error, expect ), actual LITERAL_CHARS ，它期望是右括号，但是却拿到了 字符串。看你的durid应该是老版本，可以先升级到最新版试试。还有一种掩耳盗铃的处理方法，就是不启用 stat和wall过滤器

**Comment by capitalR** [comment]
> 

没有办法掩耳盗铃,我不是用druid的sqlparser来做stat和wall,而是用来做sql分析后的改写,所以它没办法解析我就谈不上改写了.老哥知道有啥更靠谱的sqlparser吗?在考虑antlr

**Comment by Lijiaqi1992** [comment]
> > 
> 
> 没有办法掩耳盗铃,我不是用druid的sqlparser来做stat和wall,而是用来做sql分析后的改写,所以它没办法解析我就谈不上改写了.老哥知道有啥更靠谱的sqlparser吗?在考虑antlr
听说过jsqlparser，但是没用过，你可以试试

**Comment by wenshao** [comment]
PG的语法太多，也没有类似mysql/hive/odps那样做过大量的测试验证，收到需求，但最近在忙fastjson2，能花时间修复看5月份吧
