### ISSUE TITLE
Oracle数据库的XMLAGG和XMLPARSE解析失败

### ISSUE THREAD

**Issue by yadedoo** [alibaba/druid#4781]
## 1、执行的sql：
``` sql
SELECT 
  T.WORKCODE, 
  CASE  
  WHEN COUNT(T.KHNM)>50  
  THEN XMLAGG(XMLPARSE(CONTENT SUBSTR(T1.YXKHZD_KHMC,1,20)||'; ' WELLFORMED) ORDER BY T.WORKCODE, T.VISITDATE).GETCLOBVAL() 
  ELSE XMLAGG(XMLPARSE(CONTENT T1.YXKHZD_KHMC||'; ' WELLFORMED) ORDER BY T.WORKCODE, T.VISITDATE).GETCLOBVAL() 
  END VISIT_CUSTOMER_NAME 
FROM SFA_T_PERSONNELVISITINGSTORES T, DRP_YXKHZD T1 
WHERE T.KHNM = T1.YXKHZD_NM  
GROUP BY TO_NUMBER(TO_CHAR(T.VISITDATE,'YYYYMM')), TO_NUMBER(TO_CHAR(T.VISITDATE,'YYYYMMDD')), T.WORKCODE
```
## 2、报错信息
```
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: syntax error, expect ), actual IDENTIFIER pos 95, line 1, column 90, token IDENTIFIER SUBSTR
	at com.alibaba.druid.sql.parser.SQLExprParser.accept(SQLExprParser.java:4567)
	at com.alibaba.druid.sql.parser.SQLExprParser.methodRest(SQLExprParser.java:1909)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleExprParser.methodRest(OracleExprParser.java:532)
	at com.alibaba.druid.sql.parser.SQLExprParser.primaryRest(SQLExprParser.java:1604)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleExprParser.primaryRest(OracleExprParser.java:718)
	at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:1314)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleExprParser.primary(OracleExprParser.java:494)
	at com.alibaba.druid.sql.parser.SQLExprParser.expr(SQLExprParser.java:96)
	at com.alibaba.druid.sql.parser.SQLExprParser.exprList(SQLExprParser.java:2151)
	at com.alibaba.druid.sql.parser.SQLExprParser.methodRest(SQLExprParser.java:1831)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleExprParser.methodRest(OracleExprParser.java:532)
	at com.alibaba.druid.sql.parser.SQLExprParser.primaryRest(SQLExprParser.java:1604)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleExprParser.primaryRest(OracleExprParser.java:718)
	at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:1314)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleExprParser.primary(OracleExprParser.java:494)
	at com.alibaba.druid.sql.parser.SQLExprParser.expr(SQLExprParser.java:96)
	at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:756)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleExprParser.primary(OracleExprParser.java:494)
	at com.alibaba.druid.sql.parser.SQLExprParser.expr(SQLExprParser.java:96)
	at com.alibaba.druid.sql.parser.SQLExprParser.parseSelectItem(SQLExprParser.java:6256)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseSelectList(SQLSelectParser.java:1049)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.query(OracleSelectParser.java:284)
	at com.alibaba.druid.sql.parser.SQLSelectParser.query(SQLSelectParser.java:397)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleSelectParser.select(OracleSelectParser.java:51)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseSelect(SQLStatementParser.java:4379)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:4760)
	at ParseSQL.main(ParseSQL.java:27)
```

**Comment by fssgh** [comment]
在 application.yml中配置如下，有效。
```
dynamic:
  druid:
          wall:
            strict-syntax-check: false
```
