### ISSUE TITLE
没找到链接没有关闭代码，版本1.2.8。请看看什么原因呢

### ISSUE THREAD

**Issue by kiwimg** [alibaba/druid#4800]
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 60000, active 100, maxActive 100, creating 0 
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30) ~[mybatis-3.5.5.jar!/:3.5.5] 
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:149) ~[mybatis-3.5.5.jar!/:3.5.5] 
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140) ~[mybatis-3.5.5.jar!/:3.5.5] 
	at jdk.internal.reflect.GeneratedMethodAccessor88.invoke(Unknown Source) ~[na:na] 
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na] 
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na] 
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426) ~[mybatis-spring-2.0.5.jar!/:2.0.5] 
	... 27 common frames omitted

**Comment by wenshao** [comment]
连接申请了没关闭或者慢SQL了

**Comment by kiwimg** [comment]
申请了没关闭 怎么理解 ，申请不应该管吗，没明白

**Comment by guochunjiang** [comment]
> 连接申请了没关闭或者慢SQL了

比如我在程序初始化的时候配置了最大20个连接.
然后sql里面有很多慢sql语句，也导致了出现上面com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 60000, active 100, maxActive 100, creating 0的情况。请问对于这种有很多慢sql的情况，能不能连接池也正常响应啊.比如强制回收.应该怎么配置喃.
