### ISSUE TITLE
在被调用lexer.reset相关后报错的lexer.info()信息不正确 reset 没有设置startPos 和stringval

### ISSUE THREAD

**Issue by ShenFeng312** [alibaba/druid#4812]
```java
 public void test_lexer_error_info(){
        String line1 ="SELECT *";
        String line2 ="FORM a";
        String sql = line1 + "\n"+line2;
        MySqlStatementParser parser=new MySqlStatementParser(sql);
        Exception exception = null;
        try {
            parser.parseStatementList();
        } catch (Exception e) {
            exception = e;
        }
        assert exception != null;
        Assert.assertEquals("not supported.pos 13, line 2, column 2, token IDENTIFIER FORM", exception.getMessage());



    }
```
输出
```java
org.junit.ComparisonFailure: 
Expected :not supported.pos 13, line 2, column 2, token IDENTIFIER FORM
Actual   :not supported.pos 13, line 2, column 7, token IDENTIFIER a
<Click to see difference>


	at org.junit.Assert.assertEquals(Assert.java:117)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at com.alibaba.druid.bvt.sql.SQLSelectListCacheTest.test_lexer_error_info(SQLSelectListCacheTest.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:177)
	at junit.framework.TestCase.runBare(TestCase.java:142)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

**Comment by ShenFeng312** [comment]
部分非mysql部分不是特别了解 没有fix

**Comment by ShenFeng312** [comment]
@wenshao
