### ISSUE TITLE
关闭的语句: getMetaData

### ISSUE THREAD

**Issue by ocean262** [alibaba/druid#4814]
Caused by: java.sql.SQLException: 关闭的语句: getMetaData
        at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
        at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
        at oracle.jdbc.driver.OracleResultSetImpl.getMetaData(OracleResultSetImpl.java:128)
        at com.alibaba.druid.filter.FilterChainImpl.resultSet_getMetaData(FilterChainImpl.java:1337)
        at com.alibaba.druid.filter.FilterAdapter.resultSet_getMetaData(FilterAdapter.java:1660)
        at com.alibaba.druid.filter.FilterChainImpl.resultSet_getMetaData(FilterChainImpl.java:1333)
        at com.alibaba.druid.proxy.jdbc.ResultSetProxyImpl.getMetaData(ResultSetProxyImpl.java:516)
        at com.alibaba.druid.pool.DruidPooledResultSet.getMetaData(DruidPooledResultSet.java:429)
        at org.apache.ibatis.executor.resultset.FastResultSetHandler.loadMappedAndUnmappedColumnNames(FastResultSetHandler.java:309)
        at org.apache.ibatis.executor.resultset.FastResultSetHandler.getRowValue(FastResultSetHandler.java:230)
        at org.apache.ibatis.executor.resultset.FastResultSetHandler.handleRowValues(FastResultSetHandler.java:181)
        at org.apache.ibatis.executor.resultset.FastResultSetHandler.handleResultSet(FastResultSetHandler.java:152)
        at org.apache.ibatis.executor.resultset.FastResultSetHandler.handleResultSets(FastResultSetHandler.java:117)
        at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:40)
        at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:55)
        at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:41)
        at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:238)
        at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:112)
        at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:72)
        at sun.reflect.GeneratedMethodAccessor206.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:38)
        at com.risen.base.page.ExecutorInterceptor.handAll(ExecutorInterceptor.java:155)
        at com.risen.base.page.ExecutorInterceptor.intercept(ExecutorInterceptor.java:127)

**Comment by ShenFeng312** [comment]
这个是oracle JDBC 的异常

**Comment by ShenFeng312** [comment]
看起来链接被关闭了

**Comment by ShenFeng312** [comment]
#1614 和这个一致吗?

**Comment by ocean262** [comment]
> #1614 和这个一致吗?

好像不一致，
