### ISSUE TITLE
【异常处理机制的疑问】Access denied for user 'xxxx_user'@'172.16.9.152' (using password: YES) to database 'xxxx_dbName'

### ISSUE THREAD

**Issue by gongzh021** [alibaba/druid#4815]
Exception in thread "main" java.sql.SQLException: Access denied for user 'xxxx_user'@'172.16.9.152' (using password: YES) to database 'xxxx_dbName'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:836)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:197)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at com.xxxx.xxxx.util.JdbcUtil.main(JdbcUtil.java:17)

---------

为什么连接密码错误之后，抛出这样的异常，172.16.9.152是本机IP，我看到这个错误的第一反应是 连接 172.16.9.152 这个地址出现了密码不正确，误导了我排错的方向

这样的提示错误，是否可以改一下，

**Comment by ocean262** [comment]
这是jdbc的异常啊

**Comment by gongzh021** [comment]
sorry 这个问题 跑错片场了
