### ISSUE TITLE
数据查询偶发数组下标越界异常ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by xiahaobo2022** [alibaba/druid#4909]
druid版本：1.2.8，
数据库：ORACL
<groupId>com.oracle.jdbc</groupId>
<artifactId>ojdbc7</artifactId>
<version>12.1.0.2</version>

查询语句：SELECT A, B, C, D  FROM  TABLE_A WHERE C = ?
TABLE_A为分表

Caused by: java.sql.SQLException: Error
        at com.alibaba.druid.pool.DruidDataSource.handleConnectionException(DruidDataSource.java:1811)
        at com.alibaba.druid.pool.DruidPooledConnection.handleException(DruidPooledConnection.java:137)
        at com.alibaba.druid.pool.DruidPooledStatement.checkException(DruidPooledStatement.java:93)
        at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:501)
        at io.shardingsphere.core.executor.prepared.PreparedStatementExecutor$3.executeSQL(PreparedStatementExecutor.java:105)
        at io.shardingsphere.core.executor.prepared.PreparedStatementExecutor$3.executeSQL(PreparedStatementExecutor.java:101)
        at io.shardingsphere.core.executor.sql.execute.SQLExecuteCallback.execute0(SQLExecuteCallback.java:81)
        at io.shardingsphere.core.executor.sql.execute.SQLExecuteCallback.execute(SQLExecuteCallback.java:59)
        at io.shardingsphere.core.executor.sql.execute.SQLExecuteCallback.execute(SQLExecuteCallback.java:46)
        at io.shardingsphere.core.executor.ShardingExecuteEngine$1.call(ShardingExecuteEngine.java:98)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
        ... 3 common frames omitted
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
        at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:388)
        at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:397)
        at com.alibaba.druid.filter.FilterChainImpl.nextFilter(FilterChainImpl.java:490)
        at com.alibaba.druid.filter.FilterChainImpl.connection_getAutoCommit(FilterChainImpl.java:344)
        at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.getAutoCommit(ConnectionProxyImpl.java:211)
        at com.alibaba.druid.filter.stat.StatFilter.internalBeforeStatementExecute(StatFilter.java:448)
        at com.alibaba.druid.filter.stat.StatFilter.statementExecuteBefore(StatFilter.java:384)
        at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_execute(FilterEventAdapter.java:438)
        at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3459)
        at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.execute(PreparedStatementProxyImpl.java:167)
        at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:497)
        ... 12 common frames omitted

**Comment by lizongbo** [comment]
请升级使用 druid 1.2.20验证核实。
