### ISSUE TITLE
版本1.10，druid连接sqlserver过几天就会出现获取连接阻塞

### ISSUE THREAD

**Issue by leishenglong** [alibaba/druid#4920]
"http-nio-8282-exec-444" #499 daemon prio=5 os_prio=0 tid=0x00007f6b60360000 nid=0xc135 waiting on condition [0x00007f6b15555000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000b0250fe0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at com.alibaba.druid.pool.DruidDataSource.takeLast(DruidDataSource.java:1899)
	at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1460)
	at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1255)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5007)
所有的查询都会阻塞到这儿，

**Comment by wenshao** [comment]
链接泄露了吧

**Comment by leishenglong** [comment]
> 链接泄露了吧

连接数和并发其实不高，具体怎么看泄露呢？

**Comment by lizongbo** [comment]
请升级到1.2.20版本再验证核实。
