### ISSUE TITLE
clickhouse语法解析支持quantileExact函数

### ISSUE THREAD

**Issue by AOKI123** [alibaba/druid#4959]
clickhouse分位数函数语法为`quantileExact(level)(expr)`

但是目前在sql中使用`quantileExact`函数, 使用`SQLUtils.parseStatements(sql, 'clickhouse')`会无法解析

报错如下
`Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: TODO pos 32, line 2, column 22, token IDENTIFIER col_1
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:578)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:596)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:590)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:613)`

我的sql
`SELECT
 quantileExact(0.9)(col_1) AS "col_p90"
FROM
 test.test_table_1
WHERE col_2 = 1
GROUP BY
 col_2, col_3
ORDER BY
col_2 DESC
Limit 10`

**Comment by zhujing1-ola** [comment]
+1 similar like `windowFunnel(86400, 'strict_increase')(time_filed, cond1, cond2 ...)`

**Comment by zhujing0227** [comment]
+1 similar like `windowFunnel(86400, 'strict_increase')(time_field, cond1, cond2 ...)`
