### ISSUE TITLE
jdeps 分析报错，影响进一步精简打包

### ISSUE THREAD

**Issue by xfl12345** [alibaba/druid#4965]
```text
C:\Users\xfl666\.gradle\caches\modules-2\files-2.1\com.alibaba.fastjson2\fastjson2\2.0.14\15aafba518aa2ab423c762fb4d9d5619ba81bda0>"C:\Program Files\Java\graalvm-ce-java17-22.2.0\bin\jdeps" --multi-release 17 .\fastjson2-2.0.14.jar
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Exception in thread "main" java.lang.module.FindException: Error reading module: .\fastjson2-2.0.14.jar
        at java.base/jdk.internal.module.ModulePath.readModule(ModulePath.java:350)
        at java.base/jdk.internal.module.ModulePath.scan(ModulePath.java:237)
        at java.base/jdk.internal.module.ModulePath.scanNextEntry(ModulePath.java:190)
        at java.base/jdk.internal.module.ModulePath.findAll(ModulePath.java:166)
        at jdk.jdeps/com.sun.tools.jdeps.JdepsConfiguration$Builder.build(JdepsConfiguration.java:521)
        at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.buildConfig(JdepsTask.java:603)
        at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:557)
        at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:533)
        at jdk.jdeps/com.sun.tools.jdeps.Main.main(Main.java:49)
Caused by: java.lang.module.InvalidModuleDescriptorException: Package com.alibaba.fastjson2.support not found in module
        at java.base/jdk.internal.module.ModuleInfo.invalidModuleDescriptor(ModuleInfo.java:1212)
        at java.base/jdk.internal.module.ModuleInfo.doRead(ModuleInfo.java:330)
        at java.base/jdk.internal.module.ModuleInfo.read(ModuleInfo.java:129)
        at java.base/jdk.internal.module.ModulePath.readJar(ModulePath.java:652)
        at java.base/jdk.internal.module.ModulePath.readModule(ModulePath.java:331)
        ... 8 more
```

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.2.14
问题已修复，请用新版本
