### ISSUE TITLE
连接池运行10多天就会被占满

### ISSUE THREAD

**Issue by gnixkuang** [alibaba/druid#4970]
问题描述: 应用长时间不重启的吧,每天都会增加几个活动连接,直接到活动连接达到最大值,应用开始报错,提示不能获取连接,在活动连接到达最大值时,从oracle看,并没有活动回话.导出应用线程栈可以看到30个线程都在进行db操作,结合日志,有些线程居然跑了20多天,所有操作db的线程都卡在 FileDispatcherImpl.read0 位置.

druid版本:1.1.23

druid配置:
spring.datasource.url=jdbc:oracle:thin:@****:**/db
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.druid.initial-size=5
spring.datasource.druid.min-idle=5
spring.datasource.druid.max-active=30
spring.datasource.druid.max-wait=60000
spring.datasource.druid.time-between-eviction-runs-millis=60000
spring.datasource.druid.min-evictable-idle-time-millis=300000
spring.datasource.druid.validation-query=SELECT 1 FROM DUAL
spring.datasource.druid.test-while-idle=true
spring.datasource.druid.test-on-borrow=true
spring.datasource.druid.test-on-return=false
spring.datasource.druid.pool-prepared-statements=true
spring.datasource.druid.max-pool-prepared-statement-per-connection-size=30
spring.datasource.druid.use-unfair-lock=true
spring.datasource.druid.remove-abandoned=true
spring.datasource.druid.remove-abandoned-timeout=1800
spring.datasource.druid.log-abandoned=false
spring.datasource.druid.validation-query-timeout=1
spring.datasource.druid.keep-alive=true

线程栈信息:

"http-nio-8157-exec-4180" #84683 daemon prio=5 os_prio=0 tid=0x00007fa480044000 nid=0x12e9 runnable [0x00007fa41684c000]
   java.lang.Thread.State: RUNNABLE
 at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
 at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
 at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
 at sun.nio.ch.IOUtil.read(IOUtil.java:197)
 at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:378)
 - locked <0x00000007284ff458> (a java.lang.Object)
 at oracle.net.nt.TimeoutSocketChannel.read(TimeoutSocketChannel.java:174)
 at oracle.net.ns.NSProtocolNIO.doSocketRead(NSProtocolNIO.java:555)
 at oracle.net.ns.NIOPacket.readHeader(NIOPacket.java:258)
 at oracle.net.ns.NIOPacket.readPacketFromSocketChannel(NIOPacket.java:190)
 at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:132)
 at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:105)
 at oracle.net.ns.NIONSDataChannel.readDataFromSocketChannel(NIONSDataChannel.java:91)
 at oracle.jdbc.driver.T4CMAREngineNIO.prepareForUnmarshall(T4CMAREngineNIO.java:764)
 at oracle.jdbc.driver.T4CMAREngineNIO.unmarshalUB1(T4CMAREngineNIO.java:429)
 at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:407)
 at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:268)
 at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655)
 at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:270)
 at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:91)
 at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:807)
 at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:983)
 at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1168)
 at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3666)
 at oracle.jdbc.driver.T4CPreparedStatement.executeInternal(T4CPreparedStatement.java:1426)
 at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3778)
 - locked <0x0000000721f24ce0> (a oracle.jdbc.driver.T4CConnection)
 at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1081)
 at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3461)
 at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_execute(FilterEventAdapter.java:440)
 at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3459)
 at com.alibaba.druid.wall.WallFilter.preparedStatement_execute(WallFilter.java:626)
 at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3459)
 at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_execute(FilterEventAdapter.java:440)
 at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3459)
 at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.execute(PreparedStatementProxyImpl.java:167)
 at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:497)
....

**Comment by fgsqme** [comment]
老哥找到问题了吗

**Comment by kimmking** [comment]
请使用最新版本
