### ISSUE TITLE
druid 解析修改列类型sql报错，expect USING, actual USING pos 80, line 1, column 75, token USING

### ISSUE THREAD

**Issue by ScyBernate** [alibaba/druid#4998]
** 1.环境**
数据库：PG 9.3.23
DRUID:1.1.22(1.2.22)
2. alter table dwd_order_sodr_po_line_1d alter column ospl_status type BIGINT using ospl_status::BIGINT;
使用1.1.22的jar包报错入下
报错信息如下
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'GINT using ospl_status::BIGINT;', expect USING, actual USING pos 80, line 1, column 75, token USING
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:344)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:532)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:171)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:492)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:487)
	at c.p.t.database.SqlParserTest.main(SqlParserTest.java:15)

使用1.2.14的jar包报错如下 
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: not supported.pos 80, line 1, column 76, token USING
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:615)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:596)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:590)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:613)
	at c.p.t.database.SqlParserTest.main(SqlParserTest.java:15)

**Comment by ScyBernate** [comment]
<img width="1673" alt="iShot_2022-11-13_15 33 47" src="https://user-images.githubusercontent.com/18066831/201511238-073fe4c8-e7de-4244-b2a1-c89369663b13.png">
