### ISSUE TITLE
druid 捕获中断异常后未重置中断标志 导致业务方法无法正确响应中断的问题 java.sql.SQLException: interrupt

### ISSUE THREAD

**Issue by yukunqi** [alibaba/druid#5002]
Druid版本：1.2.3

使用场景：

while (!Thread.interrupted()) {
                try {
                    //业务逻辑操作 包含数据库操作
                }catch (InterruptException e){
                    Thread.currentThread().interrupt();
                }catch (Exception e) {
                    log.error("exception", e);
                }
 }

在服务重启的时候，外部会调用线程中断来停止当前线程的执行逻辑。但是当执行到数据库部分，会抛出SQLException，并且中断标志位已经清除。导致无法正常退出。

报错日志信息：
java.sql.SQLException: interrupt
	at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1616)
	at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1408)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5059)

相关代码行：
https://github.com/alibaba/druid/blob/32492da97c7fd2391dd3dcfcfe115917f2c8b6d9/src/main/java/com/alibaba/druid/pool/DruidDataSource.java#L1613

**Comment by yukunqi** [comment]
看了一下 有的issue 也遇到这个问题，请问一下大佬们 对这个问题 有什么计划吗？ @wenshao
