### ISSUE TITLE
com.alibaba.druid.filter.stat.StatFilter 对postgresql语句异常。

### ISSUE THREAD

**Issue by 283883031** [alibaba/druid#5019]
druid版本:1.2.14
select *
from (select *
      from (WITH RECURSIVE t(level) AS (VALUES (1) UNION ALL SELECT level + 1 FROM t WHERE level < 99)
            select '6d84dd29-26f8-40aa-b90e-7efe46608540', '300f9bf9-d059-4239-bb26-a961161af45a',
                   '00000002',
                   level as CATEGORY_CODE,
                   '套餐二'
            from t) a
      where not exists(select 1 from T_XF_ORDER_CATEGORY t where a.CATEGORY_CODE = cast(t.CATEGORY_CODE as integer))
      order by CATEGORY_CODE) t
limit 1;

打印异常信息:
 stat.StatFilter - merge sql error, dbType postgresql, druid-1.2.14, sql : insert into T_XF_ORDER_CATEGORY(
					ID,
					ORG_ID,
					ORG_NAME,
					CATEGORY_CODE,
					CATEGORY_NAME
		)
         
         
            select * from (select * from (
            WITH RECURSIVE t(level) AS (
            VALUES (1)
            UNION ALL
            SELECT level + 1
            FROM t
            WHERE level < 99)
            select ?,
            ?,
            ?,
            level as CATEGORY_CODE,
            ?
            from t
            ) a where not exists(select 1 from T_XF_ORDER_CATEGORY t where a.CATEGORY_CODE=cast(t.CATEGORY_CODE as integer))
            order by CATEGORY_CODE) t limit 1
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'AS (
            VALUES (1)
            UNION A', expect ), actual VALUES, pos 235, line 12, column 14, token VALUES
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:838) ~[druid-1.2.14.jar:?]
	at com.alibaba.druid.sql.parser.SQLParser.accept(SQLParser.java:846) ~[druid-1.2.14.jar:?]
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseWith(SQLSelectParser.java:617) ~[druid-1.2.14.jar:?]
	at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:57) ~[druid-1.2.14.jar:?]
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseTableSource(SQLSelectParser.java:1089) ~[druid-1.2.14.jar:?]
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseFrom(SQLSelectParser.java:1080) ~[druid-1.2.14.jar:?]
	at com.alibaba.druid.sql.dialect.postgresql.parser.PGSelectParser.query(PGSelectParser.java:129) ~[druid-1.2.14.jar:?]
	at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:61) ~[druid-1.2.14.jar:?]
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseTableSource(SQLSelectParser.java:1089) ~[druid-1.2.14.jar:?]
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseFrom(SQLSelectParser.java:1080) ~[druid-1.2.14.jar:?]
	at com.alibaba.druid.sql.dialect.postgresql.parser.PGSelectParser.query(PGSelectParser.java:129) ~[druid-1.2.14.jar:?]
	at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:61) ~[druid-1.2.14.jar:?]
	at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:840) ~[druid-1.2.14.jar:?]
	at com.alibaba.druid.sql.dialect.postgresql.parser.PGExprParser.primary(PGExprParser.java:150) ~[druid-1.2.14.jar:?]
	at com.alibaba.druid.sql.parser.SQLExprParser.expr(SQLExprParser.java:95) ~[druid-1.2.14.jar:?]
	at com.alibaba.druid.sql.dialect.postgresql.parser.PGSQLStatementParser.parseInsert(PGSQLStatementParser.java:143) ~[druid-1.2.14.jar:?]
	at com.alibaba.druid.sql.dialect.postgresql.parser.PGSQLStatementParser.parseInsert(PGSQLStatementParser.java:30) ~[druid-1.2.14.jar:?]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:251) ~[druid-1.2.14.jar:?]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:101) ~[druid-1.2.14.jar:?]
	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:163) ~[druid-1.2.14.jar:?]
	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:134) ~[druid-1.2.14.jar:?]
	at com.alibaba.druid.filter.stat.StatFilter.mergeSql(StatFilter.java:148) ~[druid-1.2.14.jar:?]
	at com.alibaba.druid.filter.stat.StatFilter.createSqlStat(StatFilter.java:672) ~[druid-1.2.14.jar:?]
	at com.alibaba.druid.filter.stat.StatFilter.statementPrepareAfter(StatFilter.java:325) ~[druid-1.2.14.jar:?]
	at com.alibaba.druid.filter.FilterEventAdapter.connection_prepareStatement(FilterEventAdapter.java:118) ~[druid-1.2.14.jar:?]
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:531) ~[druid-1.2.14.jar:?]
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.prepareStatement(ConnectionProxyImpl.java:326) ~[druid-1.2.14.jar:?]
	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:362) ~[druid-1.2.14.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_73]
	at org.apache.ibatis.logging.jdbc.ConnectionLogger.invoke(ConnectionLogger.java:54) ~[mybatis-3.2.7.jar:3.2.7]
	at com.sun.proxy.$Proxy520.prepareStatement(Unknown Source) ~[?:?]
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.instantiateStatement(PreparedStatementHandler.java:75) ~[mybatis-3.2.7.jar:3.2.7]
	at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:85) ~[mybatis-3.2.7.jar:3.2.7]
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.prepare(RoutingStatementHandler.java:57) ~[mybatis-3.2.7.jar:3.2.7]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_73]
	at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49) ~[mybatis-3.2.7.jar:3.2.7]

**Comment by 283883031** [comment]
public static void main(String[] args) {
        String sql="select *\n" +
                "from (select *\n" +
                "      from (WITH RECURSIVE t(level) AS (VALUES (1) UNION ALL SELECT level + 1 FROM t WHERE level < 99)\n" +
                "            select '6d84dd29-26f8-40aa-b90e-7efe46608540', '300f9bf9-d059-4239-bb26-a961161af45a',\n" +
                "                   '00000002',\n" +
                "                   level as CATEGORY_CODE,\n" +
                "                   '套餐二'\n" +
                "            from t) a\n" +
                "      where not exists(select 1 from T_XF_ORDER_CATEGORY t where a.CATEGORY_CODE = cast(t.CATEGORY_CODE as integer))\n" +
                "      order by CATEGORY_CODE) t\n" +
                "limit 1";
        try {
            sql = ParameterizedOutputVisitorUtils.parameterize(sql, DbType.postgresql, null, null, null);
        } catch (Exception e) {
           e.printStackTrace();
        }
    }
