### ISSUE TITLE
版本呢1.2.12, 报错:  connectionReset  及 Communications link failure 报错。

### ISSUE THREAD

**Issue by wangxuewei614** [alibaba/druid#5024]
连接池配置：
`source.setPassword(password);
        source.setSocketTimeout(30000);
        source.setConnectTimeout(30000);
        source.setInitialSize(10);
        source.setMinIdle(2);
        source.setMaxWait(60000);
        source.setMaxActive(100);
        source.setKeepAlive(false);
        source.setPhyMaxUseCount(500);
        source.setTimeBetweenEvictionRunsMillis(60000);
        source.setMinEvictableIdleTimeMillis(160000);
        source.setValidationQuery("select 1");
        source.setTestWhileIdle(true);
        source.setTestOnBorrow(false);
        source.setTestOnReturn(false);
        source.setPoolPreparedStatements(false);
        source.setMaxPoolPreparedStatementPerConnectionSize(-1);
        source.setValidationQueryTimeout(1000);`

报错日志如下：
[ERROR][2022-11-25T17:31:31.287+0800][com.alibaba.druid.pool.DruidPooledStatement:370][19:http-nio-9203-exec-8] _undef||traceid=00a9f113638089de0001062d00000220||spanid=a1
a00033a854918||msg=CommunicationsException, druid version 1.2.1
2, jdbcUrl : jdbc:mysql://xxx:3306/db_demo?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai, testWhileIdle true, idle millis 40476
9, minIdle 10, poolingCount 9, timeBetweenEvictionRunsMillis 2000, lastValidIdleMillis 404769, driver com.mysql.jdbc.Driver, exceptionSorter com.alibaba.druid.pool.vendor.
MySqlExceptionSorter
[ERROR][2022-11-25T17:31:31.287+0800][com.alibaba.druid.pool.DruidDataSource:1879][19:http-nio-9203-exec-8] _undef||traceid=00a9f113638089de0001062d00000220||spanid=a1a000
33a854918||msg={conn-10010} discard com.mysql.cj.jdbc.exception
s.CommunicationsException: Communications link failure 

caused by: java.net.SocketException: Connection reset
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:115)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at com.mysql.cj.protocol.a.SimplePacketSender.send(SimplePacketSender.java:55)
        at com.mysql.cj.protocol.a.TimeTrackingPacketSender.send(TimeTrackingPacketSender.java:50)
        at com.mysql.cj.protocol.a.NativeProtocol.send(NativeProtocol.java:584)
        ... 155 more

**Comment by jrt324** [comment]
druid版本号1.2.15， 我也遇到同样的问题，回退到1.2.11就没问题

**Comment by gogojames** [comment]
配置connectTimeout和socketTimeout为0无限等待，默认为：10000ms

**Comment by liangling627** [comment]
在druid-spring-boot-starter 1.2.15 中同样有Communications link failure 报错 报错， 我退回到原版本1.2.5 正常了
