### ISSUE TITLE
请问数据库类型枚举中的dm是指达梦吗？如果是的话达梦TOP语句不支持，解析报错

### ISSUE THREAD

**Issue by DiaoWang** [alibaba/druid#5026]
SQL: SELECT TOP 0,4  "ID", "NAME" FROM "SYSDBA"."TEST1"

代码: `SQLUtils.parseStatements("SELECT TOP 0,4  \"ID\", \"NAME\" FROM \"SYSDBA\".\"TEST1\"", DbType.valueOf("dm"));`

报错: 
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: not supported.pos 12, line 1, column 12, token LITERAL_INT
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:615)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:596)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:617)
	at com.idss.DDMTestApplication.main(DDMTestApplication.java:18)

Process finished with exit code 1

**Comment by DiaoWang** [comment]
使用了最新的1.2.14版

**Comment by DiaoWang** [comment]
请问Druid SQL Parser是否支持达梦呢？如果dm不是达梦，请问达梦应该使用哪个类型呢？
