### ISSUE TITLE
stat、wall 开启后的sql检查无法通过clickhouse any left Join的写法

### ISSUE THREAD

**Issue by hengdii** [alibaba/druid#5047]
错误信息：
Cause: java.sql.SQLException: sql injection violation, dbType clickhouse, , druid-version 1.2.14, syntax error: not supported.pos 220, line 6, column 10, token ANY :
Caused by: com.alibaba.druid.sql.parser.ParserException: not supported.pos 220, line 6, column 10, token ANY
at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:615)
at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:112)
at com.alibaba.druid.wall.WallProvider.checkInternal(WallProvider.java:618)
at com.alibaba.druid.wall.WallProvider.check(WallProvider.java:572)
at com.alibaba.druid.wall.WallFilter.checkInternal(WallFilter.java:805)
... 149 common frames omitted

我的SQL大概是这样的
select
sum(sign)
from
A a
ANY LEFT JOIN
(select id from B final) b on b.id = a.bid
ANY LEFT JOIN
(select id from C final) c on c.id = a.cid
WHERE
a.id between 10 and 100
HAVING sum(sign) > 0;

版本：1.2.8，1.2.14均有此问题，其他版本未测试
数据库：clickhouse
配置的filters : stat,wall

**Comment by hengdii** [comment]
请问这个写法会在后续的版本中会支持吗？或者有什么办法能让any left join 通过校验？
