### ISSUE TITLE
与mariadb配合关闭连接失败

### ISSUE THREAD

**Issue by zhangfan791** [alibaba/druid#5053]
关闭连接失败
配置如下：
        druid.setInitialSize(0);
        druid.setMinIdle(0);
        druid.setMaxActive(10);
        druid.setMaxWait(5000);
        druid.setValidationQuery(connectionSpec.getValidationQuery());
        druid.setTestOnBorrow(true); // 影响效率
        druid.setTestOnReturn(false);
        druid.setTestWhileIdle(true);
        druid.setKeepAlive(true);
        druid.setTimeBetweenEvictionRunsMillis(60000);
        druid.setMinEvictableIdleTimeMillis(300000);

        druid.setBreakAfterAcquireFailure(false); // 默认false,如果数据库异常，DRUID会一直获取连接
        druid.setConnectionErrorRetryAttempts(1); // 设置获取连接出错时的自动重连次数
        druid.setTimeBetweenConnectErrorMillis(30000); // 两次重试的休眠时间
        // 设置FailFast为true，获取连接失败后不阻塞
        druid.setFailFast(true);
        druid.setLogAbandoned(true);
        druid.setQueryTimeout(1800);

[2022-11-22 18:23:11.826][ERROR][][1262595][incre_capture_45e7b03e-9660-4ad6-a586-20f59f87550c][recyle error][DruidDataSource.java recycle 2044]
java.sql.SQLSyntaxErrorException: (conn=1619345) Connection.clearWarnings cannot be called on a closed connection
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62) ~[mariadb-java-client-2.7.5.jar:?]
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:176) ~[mariadb-java-client-2.7.5.jar:?]
        at org.mariadb.jdbc.MariaDbConnection.clearWarnings(MariaDbConnection.java:1024) ~[mariadb-java-client-2.7.5.jar:?]
        at com.alibaba.druid.pool.DruidConnectionHolder.reset(DruidConnectionHolder.java:331) ~[druid-1.2.10.jar:1.2.10]
        at com.alibaba.druid.pool.DruidDataSource.recycle(DruidDataSource.java:1951) ~[druid-1.2.10.jar:1.2.10]
        at com.alibaba.druid.pool.DruidPooledConnection.recycle(DruidPooledConnection.java:351) ~[druid-1.2.10.jar:1.2.10]
        at com.alibaba.druid.pool.DruidPooledConnection.close(DruidPooledConnection.java:288) ~[druid-1.2.10.jar:1.2.10]

**Comment by kimmking** [comment]
请检查在这个close调用之前，连接是否已经关闭了（调用过close？）？

**Comment by xiezhenye** [comment]
碰到了类似的问题。

```java
try (Connection connection = dataSource.getConnection();
                Statement statement = connection.createStatement()) {
            // ...
        }
```

在 try 关闭 connection 的时候报错。类似这样的代码。肯定不会提前关闭连接。

**Comment by xiezhenye** [comment]
看起来是某个版本引入的bug

**Comment by superchangme** [comment]
请问这个问题 有进展吗 ，我们用的mariadb ,报错信息是 
### Error querying database.  Cause: java.sql.SQLNonTransientConnectionException: (conn=69528773) Socket error
