### ISSUE TITLE
[Bug] 解析 ddl 报java.lang.NullPointerException: null 错误

### ISSUE THREAD

**Issue by mjzfrank** [alibaba/druid#5062]
@wenshao 
当表ddl 包含 ```CONSTRAINT``` 执行 schema.findTable(table).getStatemen() 报 java.lang.NullPointerException: null
```
java.lang.NullPointerException: null
	at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.visit(SQLASTOutputVisitor.java:5397) ~[druid-1.2.11.jar:1.2.11]
	at com.alibaba.druid.sql.ast.statement.SQLCheck.accept0(SQLCheck.java:47) ~[druid-1.2.11.jar:1.2.11]
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:48) ~[druid-1.2.11.jar:1.2.11]
	at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.printTableElements(SQLASTOutputVisitor.java:3530) ~[druid-1.2.11.jar:1.2.11]
	at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.visit(SQLASTOutputVisitor.java:9568) ~[druid-1.2.11.jar:1.2.11]
	at com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlCreateTableStatement.accept0(MySqlCreateTableStatement.java:133) ~[druid-1.2.11.jar:1.2.11]
	at com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlCreateTableStatement.accept0(MySqlCreateTableStatement.java:93) ~[druid-1.2.11.jar:1.2.11]
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:48) ~[druid-1.2.11.jar:1.2.11]
	at com.alibaba.druid.sql.ast.SQLObjectImpl.output(SQLObjectImpl.java:89) ~[druid-1.2.11.jar:1.2.11]
	at com.alibaba.druid.sql.ast.SQLObjectImpl.output(SQLObjectImpl.java:74) ~[druid-1.2.11.jar:1.2.11]
```

关联issue 
https://github.com/alibaba/canal/issues/4547#issuecomment-1367673546

测试表ddl 为
```
CREATE TABLE `test` (
  `id` bigint NOT NULL DEFAULT '0',
  `test_no` bigint NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  CONSTRAINT `test_chk_1` CHECK ((`test_no` is not null))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs
```

**Comment by zhaoshengbo** [comment]
![image](https://user-images.githubusercontent.com/4787922/213355462-2ed9c646-d4db-440e-9860-dbefc93f5733.png)
 
sqlcheck 进行clone时expr表达式赋值错误

**Comment by lizongbo** [comment]
没看懂具体是怎么触发的异常，我写测试用例验证sql解析是正常的。。

```

  @Test
    public void test_create_table() throws Exception {
        for (DbType dbType : new DbType[]{DbType.mysql}) {
            for (String sql : new String[]{
                "CREATE TABLE `test` (\n"
                    + "  `id` bigint NOT NULL DEFAULT '0',\n"
                    + "  `test_no` bigint NOT NULL DEFAULT '0',\n"
                    + "  PRIMARY KEY (`id`),\n"
                    + "  CONSTRAINT `test_chk_1` CHECK ((`test_no` is not null))\n"
                    + ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs",
            }) {
                SQLStatementParser parser = SQLParserUtils.createSQLStatementParser(sql, dbType);
                SQLStatement statement = parser.parseStatement();
                System.out.println(dbType + "原始的sql===" + sql);
                System.out.println(dbType + "归一化的sql===" + Issue5421.normalizeSql(sql));
                String newSql = statement.toString() + ";";
                System.out.println(dbType + "生成的sql归一化===" + Issue5421.normalizeSql(newSql));
                parser = SQLParserUtils.createSQLStatementParser(newSql, dbType);
                statement = parser.parseStatement();
                System.out.println(dbType + "再次解析对象得到sql===" + Issue5421.normalizeSql(statement.toString()));
            }
        }
    }

```

请使用最新版验证，有问题再反馈，反馈的时候提供一下详细的复现异常的java测试代码。
