### ISSUE TITLE
自定义允许访问监控页面的参数remoteAddress为X-Forwarded-For以后导致获取ip失败

### ISSUE THREAD

**Issue by 503203440** [alibaba/druid#5072]
在升级之前，我使用的版本是1.1.22，这个版本获取远程ip地址是直接getRemoteAddr，即如果是代理设备则会获取到代理的ip
所以这个版本我重写了StatViewServlet的isPermittedRequest

```java
@Deprecated
public class CustomStatViewServlet extends StatViewServlet {

    @Override
    public boolean isPermittedRequest(HttpServletRequest request) {
        // 自定义工具获取到客户端ip
        String ipAddr = RequestUtil.getIpAddr(request);
        return super.isPermittedRequest(ipAddr);
    }
}
```

在升级到1.2.15后，上面的方法已经不生效了，我通过查看源代码得知，自定义远程地址的http请求头参数为remoteAddress，大多数情况下，项目是运行在nginx代理之后的，所以我们是通过X-Forwarded-For获取用户真实ip的，我的ServletRegistrationBean配置如下：

```java
public ServletRegistrationBean statViewServlet() {
//        ServletRegistrationBean bean = new ServletRegistrationBean(new CustomStatViewServlet(), "/druid/*");
        ServletRegistrationBean bean = new ServletRegistrationBean(new StatViewServlet(), "/druid/*");
        Map<String, String> initParams = new HashMap<>();

        initParams.put("loginUsername", "admin");
        initParams.put("loginPassword", "123456");
        initParams.put("allow", "127.0.0.1,10.0.25.22");
        initParams.put("resetEnable", "false");
        initParams.put("remoteAddress", "X-Forwarded-For");// 指定获取远程地址的http头,原来重写的CustomStatViewServlet在druid1.2.15已经没用了
//        initParams.put("deny","192.168.20.176");

        bean.setInitParameters(initParams);
        return bean;
    }
```
这段代码在本机运行时没有任何问题，我可以访问到druid的监控页面，当发布到生产环境后，访问druid监控页面出现http500错误，通过日志输出我发现，因为代理后X-Forwarded-For的内容为116.228.20.212, 10.0.25.22 
异常信息如下:

```log
o.s.boot.web.servlet.support.ErrorPageFilter:190 - Forwarding to error page from request [/druid/login.html] due
to exception [Invalid IP Address [116.228.20.212, 10.0.25.22 ]]
java.lang.IllegalArgumentException: Invalid IP Address [116.228.20.212, 10.0.25.22 ]
        at com.alibaba.druid.support.http.util.IPAddress.parseIPAddress(IPAddress.java:174)
        at com.alibaba.druid.support.http.util.IPAddress.<init>(IPAddress.java:31)
        at com.alibaba.druid.support.http.ResourceServlet$ResourceHandler.isPermittedRequest(ResourceServlet.java:258)
        at com.alibaba.druid.support.http.ResourceServlet$ResourceHandler.isPermittedRequest(ResourceServlet.java:248)
        at com.alibaba.druid.support.http.ResourceServlet$ResourceHandler.service(ResourceServlet.java:296)
        at com.alibaba.druid.support.http.ResourceServlet.service(ResourceServlet.java:129)
        at com.alibaba.druid.support.http.StatViewServlet.service(StatViewServlet.java:232)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
```
因为com.alibaba.druid.support.http.util.IPAddress.parseIPAddress方法没有截取第一个ip地址,
而我没有找到重写任何方法来跳过这一段校验客户端ip的方法,请问我该怎么做

**Comment by lizongbo** [comment]
你可以重载getRemoteAddress方法，传入HttpServletRequestWrapper，将getRemoteAddress的调用重写即可。

```
public class CustomStatViewServlet extends StatViewServlet {

    @Override
    public String getRemoteAddress(HttpServletRequest request) {
        HttpServletRequest requesNew = new HttpServletRequestWrapper(request) {
            @Override
            public String getRemoteAddr() {
                return "这里想怎么返回就怎么返回";
            }
        };
        return super.getRemoteAddress(requesNew);
    }

}

```
