### ISSUE TITLE
报错 Communications link failure during rollback(). Transaction resolution unknown

### ISSUE THREAD

**Issue by dongFeng179** [alibaba/druid#5129]
2023-02-22 12:58:11,002 ERROR 167616170 --- [Druid-ConnectionPool-Destroy-426868901] [com.alibaba.druid.util.JdbcUtils        ] [com.alibaba.druid.util.JdbcUtils:75] : [0] close connection error
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.rollback(ConnectionImpl.java:4561)
	at com.mysql.jdbc.ConnectionImpl.realClose(ConnectionImpl.java:4187)
	at com.mysql.jdbc.ConnectionImpl.close(ConnectionImpl.java:1464)
	at com.alibaba.druid.util.JdbcUtils.close(JdbcUtils.java:73)
	at com.alibaba.druid.pool.DruidDataSource.shrink(DruidDataSource.java:2662)
	at com.alibaba.druid.pool.DruidDataSource$DestroyTask.run(DruidDataSource.java:2427)
	at com.alibaba.druid.pool.DruidDataSource$DestroyConnectionThread.run(DruidDataSource.java:2414)

**Comment by dongFeng179** [comment]
麻烦各位大神，帮忙确认下这个报错是什么原因，参数配置如下：
        username: xxxx
        password: xxxxx
        jdbc-url: jdbc:mysql://xxxx:3306/xxx?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
        # 配置初始化大小、最小、最大线程数
        initialSize: 5
        minIdle: 5
        #     CPU核数+1，也可以大些但不要超过20，数据库加锁时连接过多性能下降
        maxActive: 15
        #     最大等待时间，内网：800，外网：1200（三次握手1s）
        maxWait: 60000
        validationQuery: SELECT 1
        maxPoolPreparedStatementPerConnectionSize: 15

**Comment by kimmking** [comment]
事务等待时间超过了连接失效时间。
排查和修改timeout配置即可。
https://github.com/awslabs/aws-mysql-jdbc/issues/203
