### ISSUE TITLE
druid 1.2.16 解析SQL，建表语句中的UNIQUE KEY，ENGINE= InnoDB DEFAULT CHARSET = utf8 COLLATE= utf8_bin COMMENT '包信息表' 都会导致解析报错

### ISSUE THREAD

**Issue by d891320478** [alibaba/druid#5141]
CREATE TABLE IF NOT EXISTS pkg_info
(
   id bigint (20) NOT NULL AUTO_INCREMENT,
   gmt_create datetime NOT NULL,
   gmt_modified datetime NOT NULL,
   app_name varchar (128) NOT NULL COMMENT '应用名',
   pkg_name varchar (128) NOT NULL COMMENT '文件名',
   pkg_type varchar (16) NOT NULL COMMENT 'front, server',
   version varchar (128) NOT NULL COMMENT '包版本号',
   tag varchar (128) DEFAULT NULL COMMENT '代码tag，commitId',
   branch varchar (128) DEFAULT NULL COMMENT '代码分支',
   arch varchar (16) NOT NULL COMMENT 'cpu架构，x86_64, aarch64, mips64le',
   file_path varchar (256) DEFAULT NULL COMMENT '文件存储位置',
   md5 varchar (32) DEFAULT NULL,
   PRIMARY KEY (id),
   UNIQUE KEY uk_appname_pkgtype_version_arch
   (
      app_name,
      pkg_type,
      version,
      arch
   )
)
ENGINE= InnoDB DEFAULT CHARSET = utf8 COLLATE= utf8_bin COMMENT '包信息表';

代码：
List<SQLStatement> list = getStatements(sb.toString(), "mysql");
private static List<SQLStatement> getStatements(String sqls, String dbType) {
        SQLStatementParser parser = new SQLStatementParser(sqls, DbType.of(dbType));
        return parser.parseStatementList();
    }

报错：
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: syntax error, expect (, actual KEY pos 670, line 16, column 12, token KEY
	at com.alibaba.druid.sql.parser.SQLExprParser.accept(SQLExprParser.java:4610)

把UNIQUE KEY换成UNIQUE的报错：
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: syntax error, expect (, actual IDENTIFIER pos 698, line 16, column 12, token IDENTIFIER uk_appname_pkgtype_version_arch
	at com.alibaba.druid.sql.parser.SQLExprParser.accept(SQLExprParser.java:4610)

ENGINE等关键词引起的报错：
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: not supported.pos 664, line 17, column 2, token IDENTIFIER ENGINE
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:615)

**Comment by d891320478** [comment]
把
SQLStatementParser parser = new SQLStatementParser(sqls, DbType.of(dbType));
这行换成
MySqlStatementParser parser = new MySqlStatementParser(sqls);
就都好了
