### ISSUE TITLE
获取连接池实例错误

### ISSUE THREAD

**Issue by nietaibing** [alibaba/druid#5167]
版本: 1.2.8
问题: 设置连接池报如下错误：
Caused by: java.lang.ClassCastException: class java.util.Collections$SynchronizedMap cannot be cast to class java.util.IdentityHashMap (java.util.Collections$SynchronizedMap and java.util.IdentityHashMap are in module java.base of loader 'bootstrap')
		at com.alibaba.druid.stat.DruidDataSourceStatManager.getInstances0(DruidDataSourceStatManager.java:113)
		at com.alibaba.druid.stat.DruidDataSourceStatManager.getInstances(DruidDataSourceStatManager.java:92)
		at com.alibaba.druid.stat.DruidDataSourceStatManager.addDataSource(DruidDataSourceStatManager.java:130)
		at com.alibaba.druid.pool.DruidDataSource$1.run(DruidDataSource.java:1395)
		at java.base/java.security.AccessController.doPrivileged(Native Method)
		at com.alibaba.druid.pool.DruidDataSource.registerMbean(DruidDataSource.java:1391)
		at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:654)
		at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:934)
		at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:930)
		at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:102)

**Comment by lizongbo** [comment]
可以先配置系统属性  -Ddruid.registerToSysProperty=false，不启用这个特性，这是很奇怪的特性，居然把map对象放到系统的properties.
