### ISSUE TITLE
表的别名不可使用identity，一旦表别名使用  identity ，就会报错

### ISSUE THREAD

**Issue by XinSuiNian** [alibaba/druid#5183]
![image](https://user-images.githubusercontent.com/13972318/228152131-62fdf8f7-5a6f-4e9e-ba12-763c94434d92.png)

sql
`select b.identity as identity from a a left join identity identity on a.id = identity.aid where a.name = 'xxx' and identity.identity = 'identity'; `

如上图所示一旦表的别名使用  identity，解析sql，就会出错

com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'tity identity on a.id = identity.ai', expect IDENTITY, actual IDENTITY pos 66, line 1, column 58, token IDENTITY

	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:284)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:423)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:72)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:464)

**Comment by lizongbo** [comment]
identity 是关键字，自己先从sql写法上来规避吧。
