### ISSUE TITLE
mysql8 stopQueryTimer throw NullPointerException

### ISSUE THREAD

**Issue by MilkWangStudio** [alibaba/druid#5185]
项目启动后访问一次，链接池里会初始化5个Connection，等10分钟后再访问api。这时候会连续报5次NullPointerException。
目前排查下来，感觉是druid没有定时器check链接池，而是在请求进来后，getConnection时才检查链接是否可用。此时会触发Conection.close，NativeSession的stopQueryTimer触发时，session关闭后是null才报空指针。

想了解有办法解决这个问题么。

1. MysqlServer的waitTimeout参数是600s。

2. druid配置检测逻辑如下：
# 是否执行空闲时的Connection检测，在获取时检测，没有定时任务
test-while-idle: true
# 是否每次获取Connection都检测
test-on-borrow: false
# 作为验证连接是否有效的时间周期
time-between-eviction-runs-millis: 1000
# 连接池中连接可空闲的时间
min-evictable-idle-time-millis: 300000

3. 使用skywalking监控项目

异常栈如下：
```java
error.kind:
java.lang.NullPointerException
message:
Cannot invoke "com.mysql.cj.NativeSession.getCancelTimer()" because "this.session" is null
stack:
java.lang.NullPointerException: Cannot invoke "com.mysql.cj.NativeSession.getCancelTimer()" because "this.session" is null
at com.mysql.cj.AbstractQuery.stopQueryTimer(AbstractQuery.java:228)
at com.mysql.cj.jdbc.StatementImpl.stopQueryTimer(StatementImpl.java:643)
at com.mysql.cj.jdbc.StatementImpl.executeQuery$original$f6wmXuCe(StatementImpl.java:1182)
at com.mysql.cj.jdbc.StatementImpl.executeQuery$original$f6wmXuCe$accessor$xlkMvLme(StatementImpl.java)
at com.mysql.cj.jdbc.StatementImpl$auxiliary$DQDWWtMH.call(Unknown Source)
at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java)
at com.alibaba.druid.pool.vendor.MySqlValidConnectionChecker.isValidConnection(MySqlValidConnectionChecker.java:140)
at com.alibaba.druid.pool.DruidAbstractDataSource.testConnectionInternal(DruidAbstractDataSource.java:1518)
at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1525)
at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1450)
at com.alibaba.druid.pool.DruidDataSource.getConnection$original$mUZB8uHb(DruidDataSource.java:1440)
at com.alibaba.druid.pool.DruidDataSource.getConnection$original$mUZB8uHb$accessor$b1h7POVm(DruidDataSource.java)
at com.alibaba.druid.pool.DruidDataSource$auxiliary$qmjP5GHq.call(Unknown Source)
at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java)
at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:83)
at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:159)
at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:117)
at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80)
at org.mybatis.spring.transaction.SpringManagedTransaction.openConnection(SpringManagedTransaction.java:80)
at org.mybatis.spring.transaction.SpringManagedTransaction.getConnection(SpringManagedTransaction.java:67)
at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:337)
at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:86)
at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62)
at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:325)
at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:89)
at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:151)
at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList$original$UA0I5fwK(DefaultSqlSession.java:145)
at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList$original$UA0I5fwK$accessor$b1q2ZMX0(DefaultSqlSession.java)
at org.apache.ibatis.session.defaults.DefaultSqlSession$auxiliary$sBmr098k.call(Unknown Source)
at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java)
at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList$original$UA0I5fwK(DefaultSqlSession.java:140)
at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList$original$UA0I5fwK$accessor$b1q2ZMX0(DefaultSqlSession.java)
at org.apache.ibatis.session.defaults.DefaultSqlSession$auxiliary$NqJs4pcr.call(Unknown Source)
at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.v2.InstMethodsInterV2.intercept(InstMethodsInterV2.java:67)
at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java)
at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne$original$UA0I5fwK(DefaultSqlSession.java:76)
```

**Comment by shanjuren** [comment]
This bug has not been fixed in the latest version(8.0.32), it can be circumvented by active detection

**Comment by MilkWangStudio** [comment]
> https://bugs.mysql.com/bug.php?id=108415

Thanks. It's mysql's bug.
