### ISSUE TITLE
数据库挂掉以后恢复后连接还是依旧无法使用必须重启

### ISSUE THREAD

**Issue by poisonduyao** [alibaba/druid#5208]
本身实现了一个数据库挂掉之后的一个缓存等待机制，但是出现了数据库恢复以后无法自主再次连接必须重启

堆栈信息
```
## Error updating database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 10000, active 0, maxActive 10, creating 0, createErrorCount 2
### The error may exist in com/sweetnight/erp/mapper/WmsInfoMapper.java (best guess)
### The error may involve com.sweetnight.erp.mapper.WmsInfoMapper.delete
### The error occurred while executing an update
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 10000, active 0, maxActive 10, creating 0, createErrorCount 2
        at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:96)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)

```

**Comment by lizongbo** [comment]
试一下用线程池方式去维护连接的创建与销毁。

```
 <bean id="Druid-CP-Create" class="java.util.concurrent.ScheduledThreadPoolExecutor">
    <constructor-arg value="3" index="0" />
  </bean>
  <bean id="Druid-CP-Destroy" class="java.util.concurrent.ScheduledThreadPoolExecutor">
    <constructor-arg value="3" index="0" />
  </bean>
 <!-- 数据库：连接池配置 -->
   <bean id="dataSource" class="com.alibaba.druid.pool.DruidDataSource" init-method="init" destroy-method="close">
 <property name="createScheduler" ref="Druid-CP-Create" />
    <property name="destroyScheduler" ref="Druid-CP-Destroy" />
   </bean>
```
