### ISSUE TITLE
Spring boot 3.x 数据库postgresql 分页查询错误

### ISSUE THREAD

**Issue by bolon-svg** [alibaba/druid#5225]
druid 版本1.2.16
Spring boot 3.0.5
postgresql 9.6.24
问题：由JPA生成的语句“SELECT	xxx  FROM	sys.USER    OFFSET 0 ROWS FETCH FIRST 1 rows only”在直接执行无问题。但是使用druid 执行时，提示错误
Caused by: java.sql.SQLException: sql injection violation, dbType postgresql, , druid-version 1.2.16, syntax error: ERROR. pos 517, line 1, column 513, token FIRST : select u1_0.id,u1_0.u_architecture_id,u1_0.u_part,u1_0.u_part_leader,u1_0.u_branch_genus,u1_0.u_category,u1_0.u_code,u1_0.u_company_id,u1_0.x_createby,u1_0.x_insert,u1_0.x_deleteby,u1_0.x_delete,u1_0.u_depart,u1_0.u_email,u1_0.x_flag,u1_0.u_mobile,u1_0.u_name,u1_0.u_organization_id,u1_0.u_phone,u1_0.u_qq,u1_0.x_receive,u1_0.x_send,u1_0.u_sex,u1_0.u_status,u1_0.x_times,u1_0.x_updateby,u1_0.x_update,u1_0.x_version,u1_0.u_wechat,u1_0.u_work_company_id from sys.user u1_0 where u1_0.x_flag=? offset ? rows fetch first ? rows only
	at com.alibaba.druid.wall.WallFilter.checkInternal(WallFilter.java:828) ~[druid-1.2.16.jar:na]
	at com.alibaba.druid.wall.WallFilter.connection_prepareStatement(WallFilter.java:270) ~[druid-1.2.16.jar:na]
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:531) ~[druid-1.2.16.jar:na]
	at com.alibaba.druid.filter.FilterAdapter.connection_prepareStatement(FilterAdapter.java:908) ~[druid-1.2.16.jar:na]
	at com.alibaba.druid.filter.FilterEventAdapter.connection_prepareStatement(FilterEventAdapter.java:116) ~[druid-1.2.16.jar:na]
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:531) ~[druid-1.2.16.jar:na]
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.prepareStatement(ConnectionProxyImpl.java:326) ~[druid-1.2.16.jar:na]
	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:362) ~[druid-1.2.16.jar:na]
	at com.p6spy.engine.wrapper.ConnectionWrapper.prepareStatement(ConnectionWrapper.java:118) ~[p6spy-3.9.1.jar:na]
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$1.doPrepare(StatementPreparerImpl.java:90) ~[hibernate-core-6.1.7.Final.jar:6.1.7.Final]
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:176) ~[hibernate-core-6.1.7.Final.jar:6.1.7.Final]
	... 200 common frames omitted
Caused by: com.alibaba.druid.sql.parser.ParserException: ERROR. pos 517, line 1, column 513, token FIRST
	at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:1325) ~[druid-1.2.16.jar:na]
	at com.alibaba.druid.sql.dialect.postgresql.parser.PGExprParser.primary(PGExprParser.java:150) ~[druid-1.2.16.jar:na]
	at com.alibaba.druid.sql.parser.SQLExprParser.expr(SQLExprParser.java:104) ~[druid-1.2.16.jar:na]
	at com.alibaba.druid.sql.parser.SQLSelectParser.expr(SQLSelectParser.java:1866) ~[druid-1.2.16.jar:na]
	at com.alibaba.druid.sql.dialect.postgresql.parser.PGSelectParser.query(PGSelectParser.java:184) ~[druid-1.2.16.jar:na]
	at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:61) ~[druid-1.2.16.jar:na]
	at com.alibaba.druid.sql.dialect.postgresql.parser.PGSQLStatementParser.parseSelect(PGSQLStatementParser.java:416) ~[druid-1.2.16.jar:na]
	at com.alibaba.druid.sql.dialect.postgresql.parser.PGSQLStatementParser.parseSelect(PGSQLStatementParser.java:30) ~[druid-1.2.16.jar:na]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:200) ~[druid-1.2.16.jar:na]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:112) ~[druid-1.2.16.jar:na]
	at com.alibaba.druid.wall.WallProvider.checkInternal(WallProvider.java:618) ~[druid-1.2.16.jar:na]
	at com.alibaba.druid.wall.WallProvider.check(WallProvider.java:572) ~[druid-1.2.16.jar:na]
	at com.alibaba.druid.wall.WallFilter.checkInternal(WallFilter.java:805) ~[druid-1.2.16.jar:na]

**Comment by lizongbo** [comment]
验证了一下bug属实，我顺手提交了修复bug的代码，详情可以参考：
https://github.com/alibaba/druid/pull/5223
具体代码在：
https://github.com/alibaba/druid/pull/5223/commits/e40032696e126e33b578203e382aed68de42f753

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.2.20
请用新版本
