### ISSUE TITLE
不支持Oracle的CREATE OR REPLACE TYPE TYPE4 as ENUM语法

### ISSUE THREAD

**Issue by lv88** [alibaba/druid#5267]
解析如下的创建类型语句报错
`CREATE OR REPLACE TYPE TYPE4 as ENUM( 'Lane', 'Junction', 'Area', 'TrafficLight' )`
异常信息如下：

> com.alibaba.druid.sql.parser.ParserException: illegal name, pos 37, line 1, column 37, token (
	at com.alibaba.druid.sql.parser.SQLExprParser.name(SQLExprParser.java:2373)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleExprParser.name(OracleExprParser.java:1116)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleExprParser.parseDataType(OracleExprParser.java:189)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleStatementParser.parserParameters(OracleStatementParser.java:2120)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleStatementParser.parseCreateType(OracleStatementParser.java:3003)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseCreate(SQLStatementParser.java:3538)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleStatementParser.parseStatementList(OracleStatementParser.java:108)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:599)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:593)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:616)

**Comment by lizongbo** [comment]
使用1.2.21 验证
