### ISSUE TITLE
The last packet sent successfully

### ISSUE THREAD

**Issue by sliqiao** [alibaba/druid#5283]
1、druid版本：1.2.17
2、springboot版本：1.5.22-Release
3、druid配置：
               spring.datasource.druid.test-while-idle                                  = true
                spring.datasource.druid.min-idle                                           = 1
		spring.datasource.druid.initial-size                                       = 1
		spring.datasource.druid.max-active                                         = 55
		spring.datasource.druid.time-between-eviction-runs-millis                  = 20000  20s
		spring.datasource.druid.min-evictable-idle-time-millis                     = 180000  180s 3min
		spring.datasource.druid.max-evictable-idle-time-millis                     = 180000  180s 3min
		spring.datasource.druid.phyTimeoutMillis                                   = 480000  480s 8min
		spring.datasource.druid.keepAlive                                          = false
		spring.datasource.druid.socketTimeout                                      = 480000  480s 8min
其它无关配置就不粘贴出来了

4、程序运行过程中堆栈
   com.mysql.cj.jdbc.exceptions.CommunicationsException: The last packet successfully received from the server was 625,790 milliseconds ago. The last packet sent successfully to the server was 626,002 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1200)
	at com.alibaba.druid.filter.FilterChainImpl.statement_executeQuery(FilterChainImpl.java:2866)
	at com.alibaba.druid.filter.FilterAdapter.statement_executeQuery(FilterAdapter.java:2513)
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
	at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:67)
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:63)
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:45)
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:52)
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:41)
5、mysql服务端配置 wait_timeout=600         10分钟

这个问题已经困扰我2天了，找不到原因，我在本机也试过了，怀疑DetroyTask并没有回收这个连接

**Comment by jiehao2019** [comment]
没有添加validationQuery

**Comment by lnexin** [comment]
https://github.com/alibaba/druid/issues/5262#issuecomment-1689455343

**Comment by lizongbo** [comment]
你自己的配置问题，没配validationQuery，也没开keepAlive ,建立连接之后，因为db操作量小，导致这个脸接创建之后没有db操作，也没有保活触发validate，等到业务使用的时候，自然已经被服务端认为超时给断开了。
dba配置也有有问题，服务端限制wait_timeout为600秒就很坑爹。
