### ISSUE TITLE
c.alibaba.druid.filter.stat.StatFilter   : merge sql error, dbType highgo

### ISSUE THREAD

**Issue by wanghan2018** [alibaba/druid#5304]
2023-05-31 10:00:23.089 ERROR 3432 --- [4-1685498417769] c.alibaba.druid.filter.stat.StatFilter   : merge sql error, dbType highgo, druid-1.2.16, sql : SELECT replace(id,'-','') id,
            ? `type`,
            catalog_id,
            catalog_name,
            items,
            supply_dept_name,
            apply_number,
            catalog_update_time
        FROM
            (
            SELECT

                 
                        cast(gen_random_uuid() as text) id,
                     
                a.id catalog_id,
                a.catalog_name,
                GROUP_CONCAT( b.item_name SEPARATOR '、' ) items,
                a.dept_name supply_dept_name,
                case when a.apply_number is null then 0 else a.apply_number end apply_number,
                a.update_time catalog_update_time
            FROM
                tsds_resource_catalog a
                LEFT JOIN tsds_resource_catalog_item b ON a.id = b.catalog_id
                AND b.is_deleted = '0'
                where a.is_deleted='0' and a.is_offline='0'
            GROUP BY
                a.id
            ) t
        ORDER BY
            apply_number DESC
            LIMIT 5

com.alibaba.druid.sql.parser.ParserException: syntax error, expect ), actual IDENTIFIER pos 472, line 18, column 44, token IDENTIFIER SEPARATOR
	at com.alibaba.druid.sql.parser.SQLExprParser.accept(SQLExprParser.java:4610)
	at com.alibaba.druid.sql.parser.SQLExprParser.methodRest(SQLExprParser.java:1925)
	at com.alibaba.druid.sql.parser.SQLExprParser.parseSelectItem(SQLExprParser.java:6290)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseSelectList(SQLSelectParser.java:1068)
	at com.alibaba.druid.sql.parser.SQLSelectParser.query(SQLSelectParser.java:462)
	at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:61)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseTableSource(SQLSelectParser.java:1105)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseFrom(SQLSelectParser.java:1096)
	at com.alibaba.druid.sql.parser.SQLSelectParser.query(SQLSelectParser.java:473)
	at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:61)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseSelect(SQLStatementParser.java:4380)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:200)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:101)
	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:163)
	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:134)
	at com.alibaba.druid.filter.stat.StatFilter.mergeSql(StatFilter.java:148)
	at com.alibaba.druid.filter.stat.StatFilter.createSqlStat(StatFilter.java:672)
	at com.alibaba.druid.filter.stat.StatFilter.statementPrepareAfter(StatFilter.java:325)
	at com.alibaba.druid.filter.FilterEventAdapter.connection_prepareStatement(FilterEventAdapter.java:118)
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:531)
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.prepareStatement(ConnectionProxyImpl.java:326)
	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:362)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.instantiateStatement(PreparedStatementHandler.java:86)
	at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:88)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.prepare(RoutingStatementHandler.java:59)
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:87)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:325)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:89)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:151)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:145)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:427)
	at com.sun.proxy.$Proxy92.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:224)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:147)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:80)
	at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:145)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86)
	at com.sun.proxy.$Proxy178.list(Unknown Source)
	at com.xxl.job.executor.biz.service.impl.PortalServiceImpl.updatePortalCatalog(PortalServiceImpl.java:65)
	at com.xxl.job.executor.biz.service.impl.PortalServiceImpl$$FastClassBySpringCGLIB$$5da5636a.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at com.alibaba.druid.support.spring.stat.DruidStatInterceptor.invoke(DruidStatInterceptor.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at com.xxl.job.executor.biz.service.impl.PortalServiceImpl$$EnhancerBySpringCGLIB$$9bfe1a2e.updatePortalCatalog(<generated>)
	at com.xxl.job.executor.job.PortalExecutorXxlJob.updatePortalCatalog(PortalExecutorXxlJob.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.xxl.job.core.handler.impl.MethodJobHandler.execute(MethodJobHandler.java:31)
	at com.xxl.job.core.thread.JobThread.run(JobThread.java:166)

**Comment by wanghan2018** [comment]
不支持  这种写法吗  GROUP_CONCAT( b.item_name SEPARATOR '、' ) items

**Comment by zidieq** [comment]
遇到了同样的问题，也是瀚高数据库
`
select o.sku_id skuId,o.`sku_name` skuName,o.order_type orderType,o.sort, group_concat(si.supplier_name order by si.sort separator '、') as supplierName 
from orders as o  
left join sku_items as si on o.id = si.contract_id  
group by o.sku_id,o.`sku_name`,o.order_type,o.sort  
order by o.sort
`
`
Caused by: com.alibaba.druid.sql.parser.ParserException: syntax error, expect ), actual IDENTIFIER pos 132, line 1, column 132, token IDENTIFIER separator
	at com.alibaba.druid.sql.parser.SQLExprParser.accept(SQLExprParser.java:4616)
	at com.alibaba.druid.sql.parser.SQLExprParser.methodRest(SQLExprParser.java:1931)
	at com.alibaba.druid.sql.parser.SQLExprParser.parseSelectItem(SQLExprParser.java:6296)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseSelectList(SQLSelectParser.java:1068)
	at com.alibaba.druid.sql.dialect.postgresql.parser.PGSelectParser.query(PGSelectParser.java:103)
	at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:61)
	at com.alibaba.druid.sql.dialect.postgresql.parser.PGSQLStatementParser.parseSelect(PGSQLStatementParser.java:416)
	at com.alibaba.druid.sql.dialect.postgresql.parser.PGSQLStatementParser.parseSelect(PGSQLStatementParser.java:30)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:200)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:112)
	at com.alibaba.druid.wall.WallProvider.checkInternal(WallProvider.java:618)
	at com.alibaba.druid.wall.WallProvider.check(WallProvider.java:572)
	at com.alibaba.druid.wall.WallFilter.checkInternal(WallFilter.java:806)
	... 225 more
`
