### ISSUE TITLE
SQL select b.order + 1 as order from book b 解析失败

### ISSUE THREAD

**Issue by wangkaish** [alibaba/druid#5362]
Testcase: 
```java
String sql = "select b.order + 1 as order from book b";
SQLStatementParser parser = new SQLStatementParser(sql);
parser.parseStatement();
```
Exception:
```java
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: syntax error, expect BY, actual FROM pos 33, line 1, column 30, token FROM
	at com.alibaba.druid.sql.parser.SQLExprParser.accept(SQLExprParser.java:4616)
	at com.alibaba.druid.sql.parser.SQLExprParser.parseOrderBy(SQLExprParser.java:2738)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseOrderBy(SQLSelectParser.java:1872)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseSortBy(SQLSelectParser.java:745)
	at com.alibaba.druid.sql.parser.SQLSelectParser.query(SQLSelectParser.java:483)
	at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:61)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseSelect(SQLStatementParser.java:4430)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:4817)
	at test.my.TestSqlParser.testSQLSelectOrder(TestSqlParser.java:121)
	at test.my.TestSqlParser.main(TestSqlParser.java:38)
```

**Comment by wangkaish** [comment]
> 

@wenshao 这个能否处理下？
