### ISSUE TITLE
不支持connect by语法

### ISSUE THREAD

**Issue by Jenyow** [alibaba/druid#5369]
配置链接达梦DM8时，报connect by语法解析错误，但是语句是能正确在达梦数据库中执行
````
ERROR c.a.druid.filter.stat.StatFilter - merge sql error, dbType dm, druid-1.2.16, sql : SELECT days.createTime "key", nvl(m.cn, 0) "value"
        FROM (SELECT to_char(SYSDATE - LEVEL + 1, 'yyyymmdd') createTime
        FROM DUAL
        connect BY LEVEL <= 10) days
        LEFT JOIN (select to_char(a.jb_date, 'yyyymmdd') jbdate, count(1) cn
        from businesslog a
        group by to_char(a.jb_date, 'yyyymmdd')) m
        ON days.createTime = m.jbdate
        GROUP BY days.createTime, m.cn
        ORDER BY days.createTime
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'        FROM DUAL
        connect BY LEVEL <= 10) days
 ', expect ), actual null, pos 157, line 4, column 10, token IDENTIFIER connect
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:857)
	at com.alibaba.druid.sql.parser.SQLParser.accept(SQLParser.java:865)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseTableSource(SQLSelectParser.java:1106)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseFrom(SQLSelectParser.java:1096)
	at com.alibaba.druid.sql.parser.SQLSelectParser.query(SQLSelectParser.java:473)
```

**Comment by chestnutes** [comment]
请问 你是怎么解决这个问题的

**Comment by hanyuekidd** [comment]
请问如何解决？除了把SQL换成mysql的递归方式以外，能放行检查一些关键字吗
