### ISSUE TITLE
能帮忙分析一下这个错误是什么原因导致的吗？生产环境偶发性会抛出这个异常

### ISSUE THREAD

**Issue by LiZheng1992123** [alibaba/druid#5405]
### Cause: java.sql.SQLRecoverableException: IO Error: Socket read interrupted
; IO Error: Socket read interrupted; nested exception is java.sql.SQLRecoverableException: IO Error: Socket read interrupted
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:100)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:88)
	at com.baomidou.mybatisplus.extension.toolkit.SqlHelper.executeBatch(SqlHelper.java:189)
	at com.baomidou.mybatisplus.extension.toolkit.SqlHelper.executeBatch(SqlHelper.java:211)
	at com.baomidou.mybatisplus.extension.toolkit.SqlHelper.saveOrUpdateBatch(SqlHelper.java:239)
	at com.baomidou.mybatisplus.extension.service.impl.ServiceImpl.saveOrUpdateBatch(ServiceImpl.java:171)
	at com.baomidou.mybatisplus.extension.service.IService.saveOrUpdateBatch(IService.java:89)
	at com.hisense.scm.bdm.service.impl.BsMaterielCapacityServiceImpl.saveOrUpdateBatchWithCache(BsMaterielCapacityServiceImpl.java:1228)
	at com.hisense.scm.bdm.service.impl.BsMaterielCapacityServiceImpl$$FastClassBySpringCGLIB$$38164e34.invoke()
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685)
	at com.hisense.scm.bdm.service.impl.BsMaterielCapacityServiceImpl$$EnhancerBySpringCGLIB$$e984b781.saveOrUpdateBatchWithCache()
	at com.hisense.scm.bdm.service.impl.SystemInterfaceServiceImpl.syncMesUphData(SystemInterfaceServiceImpl.java:350)
	at com.hisense.scm.bdm.service.xxljob.SyncMesUphHandler.getMesUph(SyncMesUphHandler.java:39)
	... 5 more
Caused by: java.sql.SQLRecoverableException: IO Error: Socket read interrupted
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:761)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:904)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1082)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3780)
	at oracle.jdbc.driver.T4CPreparedStatement.executeInternal(T4CPreparedStatement.java:1343)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3887)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1079)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:497)
	at sun.reflect.GeneratedMethodAccessor294.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:59)
	at com.sun.proxy.$Proxy817.execute(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:64)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at sun.reflect.GeneratedMethodAccessor293.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
	at com.sun.proxy.$Proxy815.query(Unknown Source)
	at com.baomidou.mybatisplus.core.executor.MybatisBatchExecutor.doQuery(MybatisBatchExecutor.java:103)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:325)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at com.baomidou.mybatisplus.core.executor.MybatisCachingExecutor.query(MybatisCachingExecutor.java:165)
	at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:111)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy814.query(Unknown Source)
	at com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor.intercept(MybatisPlusInterceptor.java:64)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy814.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at com.baomidou.mybatisplus.extension.service.impl.ServiceImpl.lambda$saveOrUpdateBatch$1(ServiceImpl.java:174)
	at com.baomidou.mybatisplus.extension.toolkit.SqlHelper.lambda$saveOrUpdateBatch$1(SqlHelper.java:240)
	at com.baomidou.mybatisplus.extension.toolkit.SqlHelper.lambda$executeBatch$0(SqlHelper.java:215)
	at com.baomidou.mybatisplus.extension.toolkit.SqlHelper.executeBatch(SqlHelper.java:179)
	... 16 more
Caused by: java.net.SocketTimeoutException: Socket read interrupted
	at oracle.net.nt.TimeoutSocketChannel.read(TimeoutSocketChannel.java:152)
	at oracle.net.ns.NIOHeader.readHeaderBuffer(NIOHeader.java:82)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:139)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:101)
	at oracle.net.ns.NIONSDataChannel.readDataFromSocketChannel(NIONSDataChannel.java:80)
	at oracle.jdbc.driver.T4CMAREngineNIO.prepareForReading(T4CMAREngineNIO.java:98)
	at oracle.jdbc.driver.T4CMAREngineNIO.unmarshalUB1(T4CMAREngineNIO.java:534)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:485)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:252)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:612)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:226)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:59)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:747)
	... 51 more

----------- xxl-job job execute end(error) -----------
2023-08-18 12:32:53 [com.xxl.job.core.thread.TriggerCallbackThread#callbackLog]-[197]-[xxl-job, executor TriggerCallbackThread] 
----------- xxl-job job callback finish.

**Comment by LiZheng1992123** [comment]
生产环境xxljob定时任务是不是会有这个异常抛出，求帮忙分析下原因及如何解决这个问题？

**Comment by lizongbo** [comment]
你这个报错明显是oracle 驱动的，需要找dba一起分析
```

Caused by: java.net.SocketTimeoutException: Socket read interrupted
at oracle.net.nt.TimeoutSocketChannel.read(TimeoutSocketChannel.java:152)
at oracle.net.ns.NIOHeader.readHeaderBuffer(NIOHeader.java:82)
at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:139)
at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:101)
at oracle.net.ns.NIONSDataChannel.readDataFromSocketChannel(NIONSDataChannel.java:80)
at oracle.jdbc.driver.T4CMAREngineNIO.prepareForReading(T4CMAREngineNIO.java:98)

```

**Comment by LiZheng1992123** [comment]
非常感谢您的回复。
麻烦您帮忙看下，下面这个错误是不是也是跟oracle的驱动有关系？还是因为我们druid的配置不合理导致的？
另外，发生这个错误的时候，跟dba反馈过，dba说当时最大的连接数才不到10。
以下为生产环境druid配置：
druid:
  initialSize: 5
  minIdle: 10
  maxActive: 20
  maxWait: 6000
  timeBetweenEvictionRunsMillis: 2000
  minEvictableIdleTimeMillis: 600000
  maxEvictableIdleTimeMillis: 900000
  removeAbandoned: true
  removeAbandonedTimeout: 80
  validationQuery: SELECT 1 FROM DUAL
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 50
  filters: stat
  slave:
    enabled: false
  keep-alive: true
以下为错误信息：
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 8756, active 20, maxActive 20, creating 0
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:149)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at sun.reflect.GeneratedMethodAccessor689.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426)
	... 122 common frames omitted





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/druid"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月26日(星期六) 中午11:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/druid] 能帮忙分析一下这个错误是什么原因导致的吗？生产环境偶发性会抛出这个异常 (Issue #5405)





 
你这个报错明显是oracle 驱动的，需要找dba一起分析
  Caused by: java.net.SocketTimeoutException: Socket read interrupted at oracle.net.nt.TimeoutSocketChannel.read(TimeoutSocketChannel.java:152) at oracle.net.ns.NIOHeader.readHeaderBuffer(NIOHeader.java:82) at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:139) at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:101) at oracle.net.ns.NIONSDataChannel.readDataFromSocketChannel(NIONSDataChannel.java:80) at oracle.jdbc.driver.T4CMAREngineNIO.prepareForReading(T4CMAREngineNIO.java:98)

**Comment by lizongbo** [comment]
> wait millis 8756, active 20, maxActive 20, creating 0

这个提示说明连接池已经用满20个了，是你的应用此刻对db的并发操作比较多，但是连接池上限太小。调大maxActive，比如调成100之类的

**Comment by LiZheng1992123** [comment]
好的，非常感谢您的回复



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: LiZongbo ***@***.***&gt;
发送时间: 2023年8月27日 14:17
收件人: alibaba/druid ***@***.***&gt;
抄送: LiZheng1992123 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [alibaba/druid] 能帮忙分析一下这个错误是什么原因导致的吗？生产环境偶发性会抛出这个异常 (Issue #5405)





  
wait millis 8756, active 20, maxActive 20, creating 0
  
这个提示说明连接池已经用满20个了，是你的应用此刻对db的并发操作比较多，但是连接池上限太小。调大maxActive，比如调成100之类的
