### ISSUE TITLE
SQL解析错误

### ISSUE THREAD

**Issue by CharlesWone** [alibaba/druid#5417]
`

      String sql = "WITH a AS(SELECT 1),b AS(SELECT 1)SELECT * FROM a,b";
      ParameterizedOutputVisitorUtils.parameterize(sql, DbType.clickhouse, null, null, null);
`

Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: not supported.pos 24, line 1, column 24, token )
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:615)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:101)
	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:163)
	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:134)
	at com.nantian.swindler.api.TransferDataApiImpl.main(TransferDataApiImpl.java:80)

**Comment by lizongbo** [comment]
发完整的能重现问题的sql出来。

**Comment by CharlesWone** [comment]
> 发完整的能重现问题的sql出来。

        String sql = "WITH a AS(SELECT 1),b AS(SELECT 1) SELECT * FROM a,b";
        ParameterizedOutputVisitorUtils.parameterize(sql, DbType.clickhouse, null, null, null);

这种sql，这个方法这里报错

**Comment by lizongbo** [comment]
> > 发完整的能重现问题的sql出来。
> 
> ```
>     String sql = "WITH a AS(SELECT 1) SELECT * FROM a";
>     ParameterizedOutputVisitorUtils.parameterize(sql, DbType.clickhouse, null, null, null);
> ```
> 
> with as这种sql，这个方法这里报错

看官方语法是 as后面的变量名，确认sql没有写错吗？
是不是应该这样写：

```
WITH (SELECT 1)  AS a  SELECT * FROM a
```
这样解析是没有问题的。

https://clickhouse.com/docs/zh/sql-reference/statements/select/with

**Comment by CharlesWone** [comment]
> > > 发完整的能重现问题的sql出来。
> > 
> > 
> > ```
> >     String sql = "WITH a AS(SELECT 1) SELECT * FROM a";
> >     ParameterizedOutputVisitorUtils.parameterize(sql, DbType.clickhouse, null, null, null);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > with as这种sql，这个方法这里报错
> 
> 看官方语法是 as后面的变量名，确认sql没有写错吗？ 是不是应该这样写：
> 
> ```
> WITH (SELECT 1)  AS a  SELECT * FROM a
> ```
> 
> 这样解析是没有问题的。
> 
> https://clickhouse.com/docs/zh/sql-reference/statements/select/with

你个sql有问题，解析虽然不报错，查询报错，DBeaver都执行不了
