### ISSUE TITLE
线上环境运行一段时间就会出现以下报错信息，求大佬解答一下

### ISSUE THREAD

**Issue by jialiu123** [alibaba/druid#5467]
Caused by: org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:109)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:136)
	at org.hibernate.internal.SessionImpl.connection(SessionImpl.java:541)
	at sun.reflect.GeneratedMethodAccessor235.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:282)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:266)
	at org.springframework.orm.jpa.vendor.WinningHibernateJpaDialect$HibernateConnectionHandle.doGetConnection(WinningHibernateJpaDialect.java:340)
	at org.springframework.orm.jpa.vendor.WinningHibernateJpaDialect.beginTransaction(WinningHibernateJpaDialect.java:101)
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:402)
	... 143 common frames omitted
Caused by:**com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 30001, active 0, maxActive 200, creating 1, createElapseMillis 258994534, createErrorCount 191**
	at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1682)
	at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1395)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5059)
	at com.alibaba.druid.filter.logging.LogFilter.dataSource_getConnection(LogFilter.java:886)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5055)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1373)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1365)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:109)
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)
	at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:35)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:106)
	... 153 common frames omitted

**Comment by lizongbo** [comment]
升级到最新版本再看会不会出现这个问题。

**Comment by zhouxianling** [comment]
> 升级到最新版本再看会不会出现这个问题。

你好解决了吗

**Comment by jialiu123** [comment]
没解决哦，准备出门左拐了哦

**Comment by felixren-poloniex** [comment]
建议在 GetConnectionTimeoutException 异常中，将 host ，端口等不敏感的信息输出，以方便排查问题。

**Comment by zrlw** [comment]
查一下数据服务端的最大连接数配置，maxActive搞成200，如果有100个客户端，峰值就是2万个连接，数据库和网络吃的下么。
短耗时sql（毫秒级）应用场景下，配置这个参数时通常都不会超过5。

**Comment by lizongbo** [comment]
请用最新版 1.2.22进行验证
