### ISSUE TITLE
not supported.pos 104, line 1, column 98, token IDENTIFIER EXECUTE

### ISSUE THREAD

**Issue by vinvis** [alibaba/druid#5474]
postgresql有些语法不支持，sql语句如下：
CREATE TRIGGER "update_time" BEFORE UPDATE ON "poit_cloud"."ent_i_checking_analyze" FOR EACH ROW EXECUTE PROCEDURE poit_cloud.modify_timestamp();
执行代码
SQLUtils.parseStatements(targetSql, DbType.postgresql);
报错信息
Caused by: com.alibaba.druid.sql.parser.ParserException: not supported.pos 104, line 1, column 98, token IDENTIFIER EXECUTE
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:623)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:114)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseCreateTrigger(SQLStatementParser.java:4063)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseCreate(SQLStatementParser.java:3506)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:258)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:566)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:588)
	at com.poit.release.platform.deploy.service.TestingSqlService.validate(TestingSqlService.java:74)
	... 104 common frames omitted

这种情况应该怎么处理

**Comment by lizongbo** [comment]
这个是不支持，我看下怎么加上解析
