### ISSUE TITLE
SQLStatementParser cannot parse INSERT ALL statements

### ISSUE THREAD

**Issue by oicq1699** [alibaba/druid#5486]
## Run Environment
- jdk:1.8
- druid:1.2.20

## Exception  StackTrace
```java
com.alibaba.druid.sql.parser.ParserException: not supported.pos 10, line 1, column 8, token ALL
        at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:616)
        at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:102)
        at com.alibaba.druid.sql.SQLUtils.format(SQLUtils.java:366)
        at com.alibaba.druid.sql.SQLUtils.format(SQLUtils.java:359)
        at org.springblade.core.mp.plugins.SqlLogInterceptor.statement_close(SqlLogInterceptor.java:128)
        at com.alibaba.druid.filter.FilterChainImpl.statement_close(FilterChainImpl.java:2887)
```
## Exception Sql
```sql
INSERT ALL
          
            INTO ACT_HI_VARINST (ID_, PROC_INST_ID_, EXECUTION_ID_, TASK_ID_, NAME_, REV_, VAR_TYPE_, SCOPE_ID_, SUB_SCOPE_ID_, SCOPE_TYPE_, 
                BYTEARRAY_ID_, DOUBLE_, LONG_ , TEXT_, TEXT2_, CREATE_TIME_, LAST_UPDATED_TIME_) VALUES
            (
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?
            )
          
            INTO ACT_HI_VARINST (ID_, PROC_INST_ID_, EXECUTION_ID_, TASK_ID_, NAME_, REV_, VAR_TYPE_, SCOPE_ID_, SUB_SCOPE_ID_, SCOPE_TYPE_, 
                BYTEARRAY_ID_, DOUBLE_, LONG_ , TEXT_, TEXT2_, CREATE_TIME_, LAST_UPDATED_TIME_) VALUES
            (
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?
            )
          
            INTO ACT_HI_VARINST (ID_, PROC_INST_ID_, EXECUTION_ID_, TASK_ID_, NAME_, REV_, VAR_TYPE_, SCOPE_ID_, SUB_SCOPE_ID_, SCOPE_TYPE_, 
                BYTEARRAY_ID_, DOUBLE_, LONG_ , TEXT_, TEXT2_, CREATE_TIME_, LAST_UPDATED_TIME_) VALUES
            (
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?
            )
          
            INTO ACT_HI_VARINST (ID_, PROC_INST_ID_, EXECUTION_ID_, TASK_ID_, NAME_, REV_, VAR_TYPE_, SCOPE_ID_, SUB_SCOPE_ID_, SCOPE_TYPE_, 
                BYTEARRAY_ID_, DOUBLE_, LONG_ , TEXT_, TEXT2_, CREATE_TIME_, LAST_UPDATED_TIME_) VALUES
            (
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?
            )
          
            INTO ACT_HI_VARINST (ID_, PROC_INST_ID_, EXECUTION_ID_, TASK_ID_, NAME_, REV_, VAR_TYPE_, SCOPE_ID_, SUB_SCOPE_ID_, SCOPE_TYPE_, 
                BYTEARRAY_ID_, DOUBLE_, LONG_ , TEXT_, TEXT2_, CREATE_TIME_, LAST_UPDATED_TIME_) VALUES
            (
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?
            )
          
            INTO ACT_HI_VARINST (ID_, PROC_INST_ID_, EXECUTION_ID_, TASK_ID_, NAME_, REV_, VAR_TYPE_, SCOPE_ID_, SUB_SCOPE_ID_, SCOPE_TYPE_, 
                BYTEARRAY_ID_, DOUBLE_, LONG_ , TEXT_, TEXT2_, CREATE_TIME_, LAST_UPDATED_TIME_) VALUES
            (
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?
            )
          
            INTO ACT_HI_VARINST (ID_, PROC_INST_ID_, EXECUTION_ID_, TASK_ID_, NAME_, REV_, VAR_TYPE_, SCOPE_ID_, SUB_SCOPE_ID_, SCOPE_TYPE_, 
                BYTEARRAY_ID_, DOUBLE_, LONG_ , TEXT_, TEXT2_, CREATE_TIME_, LAST_UPDATED_TIME_) VALUES
            (
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?
            )
```

**Comment by lizongbo** [comment]
我查了下是Oracle的语法，我用DbType.oracle验证解析是ok的，你反馈的信息没有给出DbType是啥，请核实你的配置是不是配错了，把DbType配成其它类型的了。

Oracle 语法说明： https://www.oracletutorial.com/oracle-basics/oracle-insert-all/

测试代码：

```

 @Test
    public void test_insert_all() throws Exception {
        for (DbType dbType : new DbType[]{DbType.oracle}) {
            String sql = "INSERT ALL\n"
                + "          \n"
                + "            INTO ACT_HI_VARINST (ID_, PROC_INST_ID_, EXECUTION_ID_, TASK_ID_, NAME_, REV_, VAR_TYPE_, SCOPE_ID_, SUB_SCOPE_ID_, SCOPE_TYPE_, \n"
                + "                BYTEARRAY_ID_, DOUBLE_, LONG_ , TEXT_, TEXT2_, CREATE_TIME_, LAST_UPDATED_TIME_) VALUES\n"
                + "            (\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?\n"
                + "            )\n"
                + "          \n"
                + "            INTO ACT_HI_VARINST (ID_, PROC_INST_ID_, EXECUTION_ID_, TASK_ID_, NAME_, REV_, VAR_TYPE_, SCOPE_ID_, SUB_SCOPE_ID_, SCOPE_TYPE_, \n"
                + "                BYTEARRAY_ID_, DOUBLE_, LONG_ , TEXT_, TEXT2_, CREATE_TIME_, LAST_UPDATED_TIME_) VALUES\n"
                + "            (\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?\n"
                + "            )\n"
                + "          \n"
                + "            INTO ACT_HI_VARINST (ID_, PROC_INST_ID_, EXECUTION_ID_, TASK_ID_, NAME_, REV_, VAR_TYPE_, SCOPE_ID_, SUB_SCOPE_ID_, SCOPE_TYPE_, \n"
                + "                BYTEARRAY_ID_, DOUBLE_, LONG_ , TEXT_, TEXT2_, CREATE_TIME_, LAST_UPDATED_TIME_) VALUES\n"
                + "            (\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?\n"
                + "            )\n"
                + "          \n"
                + "            INTO ACT_HI_VARINST (ID_, PROC_INST_ID_, EXECUTION_ID_, TASK_ID_, NAME_, REV_, VAR_TYPE_, SCOPE_ID_, SUB_SCOPE_ID_, SCOPE_TYPE_, \n"
                + "                BYTEARRAY_ID_, DOUBLE_, LONG_ , TEXT_, TEXT2_, CREATE_TIME_, LAST_UPDATED_TIME_) VALUES\n"
                + "            (\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?\n"
                + "            )\n"
                + "          \n"
                + "            INTO ACT_HI_VARINST (ID_, PROC_INST_ID_, EXECUTION_ID_, TASK_ID_, NAME_, REV_, VAR_TYPE_, SCOPE_ID_, SUB_SCOPE_ID_, SCOPE_TYPE_, \n"
                + "                BYTEARRAY_ID_, DOUBLE_, LONG_ , TEXT_, TEXT2_, CREATE_TIME_, LAST_UPDATED_TIME_) VALUES\n"
                + "            (\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?\n"
                + "            )\n"
                + "          \n"
                + "            INTO ACT_HI_VARINST (ID_, PROC_INST_ID_, EXECUTION_ID_, TASK_ID_, NAME_, REV_, VAR_TYPE_, SCOPE_ID_, SUB_SCOPE_ID_, SCOPE_TYPE_, \n"
                + "                BYTEARRAY_ID_, DOUBLE_, LONG_ , TEXT_, TEXT2_, CREATE_TIME_, LAST_UPDATED_TIME_) VALUES\n"
                + "            (\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?\n"
                + "            )\n"
                + "          \n"
                + "            INTO ACT_HI_VARINST (ID_, PROC_INST_ID_, EXECUTION_ID_, TASK_ID_, NAME_, REV_, VAR_TYPE_, SCOPE_ID_, SUB_SCOPE_ID_, SCOPE_TYPE_, \n"
                + "                BYTEARRAY_ID_, DOUBLE_, LONG_ , TEXT_, TEXT2_, CREATE_TIME_, LAST_UPDATED_TIME_) VALUES\n"
                + "            (\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?,\n"
                + "                ?\n"
                + "            )";

            SQLStatementParser parser = SQLParserUtils.createSQLStatementParser(sql, dbType);
            SQLStatement statement = parser.parseStatement();
            System.out.println("原始的sql===" + sql);
            String newSql = statement.toString();
            System.out.println("生成的sql===" + newSql);

        }
    } 

```

**Comment by oicq1699** [comment]
不好意思，没仔细阅读mybatis-plus的源码，漏了DbType，我的DbType是dm，达梦数据库

我是开启了mybatis-plus的语句打印功能，它以下的代码涉及了dbtype的获取
```
		String dbType = statement.getConnectionProxy().getDirectDataSource().getDbType();
		String formattedSql = SQLUtils.format(sql, DbType.of(dbType), parameters, FORMAT_OPTION);
```
我在该段代码上打了断点，返回dbType是dm

**Comment by lizongbo** [comment]
> 不好意思，没仔细阅读mybatis-plus的源码，漏了DbType，我的DbType是dm，达梦数据库
> 
> 我是开启了mybatis-plus的语句打印功能，它以下的代码涉及了dbtype的获取
> 
> ```
> 		String dbType = statement.getConnectionProxy().getDirectDataSource().getDbType();
> 		String formattedSql = SQLUtils.format(sql, DbType.of(dbType), parameters, FORMAT_OPTION);
> ```
> 
> 我在该段代码上打了断点，返回dbType是dm

网上找不到达梦数据库支持 Oracle insert all的语法介绍，只有介绍兼容mysql语法，你看下你到底用的什么数据库，如果真的是达梦数据库，提供一下达梦数据库支持 Oracle insert all的语法的说明资料。

**Comment by oicq1699** [comment]
> > 不好意思，没仔细阅读mybatis-plus的源码，漏了DbType，我的DbType是dm，达梦数据库
> > 我是开启了mybatis-plus的语句打印功能，它以下的代码涉及了dbtype的获取
> > ```
> > 		String dbType = statement.getConnectionProxy().getDirectDataSource().getDbType();
> > 		String formattedSql = SQLUtils.format(sql, DbType.of(dbType), parameters, FORMAT_OPTION);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我在该段代码上打了断点，返回dbType是dm
> 
> 网上找不到达梦数据库支持 Oracle insert all的语法介绍，只有介绍兼容mysql语法，你看下你到底用的什么数据库，如果真的是达梦数据库，提供一下达梦数据库支持 Oracle insert all的语法的说明资料。

这个是达梦的insert 语法说明资料
https://eco.dameng.com/document/dm/zh-cn/pm/insertion-deletion-modification.html

我感觉这个数据可能更兼容oracle一些，当然，我说这话并没有经过充分论证

**Comment by lizongbo** [comment]
看了下是 达梦支持Orace的 insert all的语法，但是目前Oracle的解析类的实体类都绑定实现了Oracle类型相关接口，不好直接按dm的dbtype来解析，如果是直接复制代码重命名成dm的dialet相关的类，感觉代码又比较冗余。
@zrlw 看下有没有简洁的实现方式。

**Comment by zrlw** [comment]
能不能先从配置上解决，像ocenbase那样把dbType配置成oracle，如果dm有自己提供的驱动，驱动还配dm自己的。
否则要重用oracle的代码，当前oracle类型的相关接口应该要改成泛型了。
可以让 @shenjianeng 看看有没有其他方式。

**Comment by shenjianeng** [comment]
如果可以通过将 dbType 配置成 oracle 来解决，那是不是可以直接 druid 内部处理一下，让 oracle 和 dm 用同一个 SQLParser

**Comment by lizongbo** [comment]
dm是混合了oracle和mysql的语法，我没有用过达梦数据库。有愿意贡献代码的话，欢迎大家贡献，我来合入。
