### ISSUE TITLE
1%概率出现GetConnectionTimeoutException: wait millis 5000, active 0, maxActive 60, creating 1

### ISSUE THREAD

**Issue by Bughue** [alibaba/druid#5492]
- 用的druid 1.2.3(有自己包装后写了个datasourceProxy，但目前分析的情况看来关系不大)
- 设置的maxActive=60，没有开removeabandon
线上应用偶发会出现GetConnectionTimeoutException（全都是active=0），并且一出现就有点停不下来（有时候持续几分钟，有时候持续几个小时）出现这个问题都比较偶然，跟流量大小似乎关系不大。而且出现这个问题后在这段时间内的getconnection()有1%的概率会出现这个超时，其他的情况正常。
另外我有实现FilterEventAdapter，发现connection_connect的时候是很快的（都在5ms左右）。

现在这几个问题非常费解

1. active=0证明现在应该没有其他线程在用，也就是busy=0，但同时有很多线程来获取连接是成功的，也能执行sql
2. 持续出现这个情况很奇怪，尤其是看监控似乎池子也没用满
3. connect速度很快，应该不会阻塞这么久
4. connect的次数很平缓（1分钟只有十次左右），如果连接不够用应该会一直在创建才对

### Cause: com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 5000, active 0, maxActive 60, creating 1, createElapseMillis 7051063
; wait millis 5000, active 0, maxActive 60, creating 1, createElapseMillis 7051063; nested exception is com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 5000, active 0, maxActive 60, creating 1, createElapseMillis 7051063
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:120)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)

**Comment by xiaomagor** [comment]
+1，同样的问题，也有datasourceProxy ，版本 1.2.5
![image](https://github.com/alibaba/druid/assets/12425345/2fcea5ea-61bc-42bc-9af5-48409cb024f8)

**Comment by zrlw** [comment]
通常是每台客户端的maxActive设置太大了，全部客户端加起来的active连接总数超过了数据库服务端配置的最大连接数，获取连接一直等到超时也没有等到可用的连接。

**Comment by Bughue** [comment]
> 通常是每台客户端的maxActive设置太大了，全部客户端加起来的active连接总数超过了数据库服务端配置的最大连接数，获取连接一直等到超时也没有等到可用的连接。

服务端那边也问了，说是没有特别大的压力。而且客户端这边进行创建连接的时候是成功的，这个监控是有的

**Comment by xiaomagor** [comment]
> 通常是每台客户端的maxActive设置太大了，全部客户端加起来的active连接总数超过了数据库服务端配置的最大连接数，获取连接一直等到超时也没有等到可用的连接。

在控制台看了MySQL的配置，目前最大消耗连接数4000左右，数据库支持最大连接50000个，肯定没超过数据库最大连接数。

**Comment by zrlw** [comment]
不是数据库自己配多少就行的，操作系统的tcp配置参数是否能支持这么多，不是数据库自己就确定的，需要tcpdump抓包分析数据库连接tcp报文，不是简单执行以下top看看cpu和内存就能判定的事情。

**Comment by Bughue** [comment]
> 不是数据库自己配多少就行的，操作系统的tcp配置参数是否能支持这么多，不是数据库自己就确定的，需要tcpdump抓包分析数据库连接tcp报文，不是简单执行以下top看看cpu和内存就能判定的事情。

我这边主要是监控druid建立连接的时候没有异常，而且都很快，所以应该不是你说这种情况？
@Override
    public ConnectionProxy connection_connect(FilterChain chain, Properties info) throws SQLException {

**Comment by zrlw** [comment]
1. GetConnectionTimeoutException wait millis 5000说明当前线程获取连接执行了pollLast方法尝试获取连接，但返回值为null没获取到连接，没有获取连接说明进入pollLast方法时的poolingCount为0，等到超时没有等到notEmpty信号时的poolingCount依然为0。
2. active=0说明当前activeCount=0没有正在执行sql的线程。
3. creating=1说明当前createCount=1只有一个线程正在执行createPhysicalConnection创建连接操作，createPhysicalConnection方法内部会调用creatingCountUpdater#incrementAndGet让createCount增1，如果有多个线程并行创建，这个值会叠加上去，而不是1，连接创建成功后，这个值才会被减下去。
4. createPhysicalConnection会执行filter。
你应该关注那个正在执行createPhysicalConnection创建连接操作的线程为什么没有在5ms内完成创建，等了5秒也没完成创建。
另外，之前版本的createPhysicalConnection调用filter之后没有重置filterChain的pos，filterchain只执行一次，你的filter统计值大概率只用了一次。

**Comment by zrlw** [comment]
1. GetConnectionTimeoutException wait millis 5000说明当前线程获取连接执行了pollLast方法尝试获取连接，但返回值为null没获取到连接，没有获取连接说明进入pollLast方法时的poolingCount为0，等到超时没有等到notEmpty信号时的poolingCount依然为0。
2. active=0说明当前activeCount=0没有正在执行sql的线程。
3. creating=1说明当前createCount=1只有一个线程正在执行createPhysicalConnection创建连接操作，createPhysicalConnection方法内部会调用creatingCountUpdater#incrementAndGet让createCount增1，如果有多个线程并行创建，这个值会叠加上去，而不是1，连接创建成功后，这个值才会被减下去。
4. createPhysicalConnection会执行filter。
你应该关注那个正在执行createPhysicalConnection创建连接操作的线程为什么没有在5ms内完成创建，等了5秒也没完成创建。
另外，老版本druid有缺陷，createPhysicalConnection调完filter并没有重置filterChain的起始位置，导致filterchain只会被执行一次。

**Comment by Bughue** [comment]
> 1. GetConnectionTimeoutException wait millis 5000说明当前线程获取连接执行了pollLast方法尝试获取连接，但返回值为null没获取到连接，没有获取连接说明进入pollLast方法时的poolingCount为0，等到超时没有等到notEmpty信号时的poolingCount依然为0。
> 2. active=0说明当前activeCount=0没有正在执行sql的线程。
> 3. creating=1说明当前createCount=1只有一个线程正在执行createPhysicalConnection创建连接操作，createPhysicalConnection方法内部会调用creatingCountUpdater#incrementAndGet让createCount增1，如果有多个线程并行创建，这个值会叠加上去，而不是1，连接创建成功后，这个值才会被减下去。
> 4. createPhysicalConnection会执行filter。
>    你应该关注那个正在执行createPhysicalConnection创建连接操作的线程为什么没有在5ms内完成创建，等了5秒也没完成创建。

请问一下之前说的“filter之后没有重置filterChain的pos，filterchain只执行一次，你的filter统计值大概率只用了一次”这个问题是存在的吗？因为connect监控到的数据确实少。但我看大佬你后面编辑了，所以是不是有这个问题呢？因为连接一直很快所以很困惑.
另外我发现有陈年issue说statFilter有内存泄漏问题的，在1.2.3是不是可能碰到，如果然后connect时候我的filter没执行导致我看不到异常？

**Comment by Bughue** [comment]
> 我看了一下druid 1.2.3代码，没有filterchain执行次数的问题，所以我改了回复内容。 建议你用arthas之类的工具抓一下你的filterchain，设置一下执行超时阈值，比如1s，查一下执行慢的环节。 从你的日志内容分析，那个负责创建连接的线程执行缓慢，如果创建连接没有问题，大概率就要查一下你的filter代码了。

这个问题最近两个月只出了2次，目前在本地没有重现。创建连接的task看起来很少日志，我全局搜了日志也没看到创建失败的，所以是不是可以认为创建就是没问题的？我的filter代码可以贴出来：


```
@Override
    public ConnectionProxy connection_connect(FilterChain chain, Properties info) throws SQLException {
        Transaction transaction = Cat.newTransaction(DATABASE, "connect");
        try {
            ConnectionProxy connection = chain.connection_connect(info);
            transaction.setSuccess();
            return connection;
        } catch (Throwable ex) {
            transaction.setStatus(ex);
            throw ex;
        } finally {
            transaction.complete();
        }
    }


    @Override
    public DruidPooledConnection dataSource_getConnection(FilterChain chain, DruidDataSource dataSource, long maxWaitMillis) throws SQLException {
        Transaction transaction = Cat.newTransaction(DATABASE, "getConnection");
        try {
            DruidPooledConnection conn = chain.dataSource_connect(dataSource, maxWaitMillis);
            long id = getConnectionId(conn);
            transaction.addData("id", id);
            if (id == 0L) {
                transaction.setFail();
            } else {
                transaction.setSuccess();
            }
            return conn;
        } catch (Throwable ex) {
            transaction.setStatus(ex);
            throw ex;
        } finally {
            transaction.complete();
        }
```

**Comment by zrlw** [comment]
建议在Cat.newTransaction和Cat.newTransaction方法调用前后获取一下当前时间戳，计算一下方法调用的耗时，耗时超过100ms写一条告警日志吧。
也可以考虑升级一下druid版本看看，druid之前的连接池管理的确有一些缺陷。
两个月只出现两次，说明问题偶发因素很大，如果还保存有同时段的数据库服务端日志，可以查一下数据库日志，也存在数据库服务因为自身部署环境出现资源瓶颈没有及时处理请求连接的可能性。

**Comment by Bughue** [comment]
> 建议在Cat.newTransaction和Cat.newTransaction方法调用前后获取一下当前时间戳，计算一下方法调用的耗时，耗时超过100ms写一条告警日志吧。 也可以考虑升级一下druid版本看看，druid之前的连接池管理的确有一些缺陷。 两个月只出现两次，说明问题偶发因素很大，如果还保存有同时段的数据库服务端日志，可以查一下数据库日志，也存在数据库服务因为自身部署环境出现资源瓶颈没有及时处理请求连接的可能性。

Cat.newTransaction就是new一个对象而已，目前看来没什么开销的。“druid之前的连接池管理的确有一些缺陷”能具体说说吗

**Comment by zrlw** [comment]
并发线程数多了会出现锁竞争，获取连接和返还连接都会变慢，受当前设计框架所限，druid适合的场景是每个客户端只有20个以下的并发数据库连接需求（maxActive < 20)，像你这种60个线程的，本身就不适合采用druid。
另外当前master分支的版本做了很多优化，尽量在现有框架体系下提高连接池响应速度，如果你的maxActive能调到20之内，或许可以试试最新的master分支。

**Comment by a97659096** [comment]
我也遇到了同样的问题，不知道为什么重启服务后就好了，也是偶发性

**Comment by Bughue** [comment]
> 我也遇到了同样的问题，不知道为什么重启服务后就好了，也是偶发性

你是什么版本？也是active=0吗？

**Comment by a97659096** [comment]
> > 我也遇到了同样的问题，不知道为什么重启服务后就好了，也是偶发性
> 
> 你是什么版本？也是active=0吗？
不太确定是否跟我连多个数据源有关系，默认连接的数据源没出现过问题，其他三个数据源会偶发性的出现这个错误，重启服务就又可以获取到连接了，druid版本是1.2.6

Caused by: com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 60000, active 0, maxActive 40, creating 1, createElapseMillis 1633095
	at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1749)
	at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1419)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5059)
	at com.alibaba.druid.filter.stat.StatFilter.dataSource_getConnection(StatFilter.java:689)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5055)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1397)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1389)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:100)
	at com.baomidou.dynamic.datasource.ds.ItemDataSource.getConnection(ItemDataSource.java:56)
	at com.baomidou.dynamic.datasource.ds.AbstractRoutingDataSource.getConnection(AbstractRoutingDataSource.java:48)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:159)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:117)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80)
	... 110 common frames omitted

**Comment by Bughue** [comment]
> > > 我也遇到了同样的问题，不知道为什么重启服务后就好了，也是偶发性
> > 
> > 
> > 你是什么版本？也是active=0吗？
> > 不太确定是否跟我连多个数据源有关系，默认连接的数据源没出现过问题，其他三个数据源会偶发性的出现这个错误，重启服务就又可以获取到连接了，druid版本是1.2.6
> 
> Caused by: com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 60000, active 0, maxActive 40, creating 1, createElapseMillis 1633095 at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1749) at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1419) at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5059) at com.alibaba.druid.filter.stat.StatFilter.dataSource_getConnection(StatFilter.java:689) at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5055) at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1397) at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1389) at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:100) at com.baomidou.dynamic.datasource.ds.ItemDataSource.getConnection(ItemDataSource.java:56) at com.baomidou.dynamic.datasource.ds.AbstractRoutingDataSource.getConnection(AbstractRoutingDataSource.java:48) at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:159) at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:117) at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80) ... 110 common frames omitted

amazing 简直一样。而且这个active=0应该是不准确的，因为我能检测到不停的有连接创建和回收，而且testwhileIdle的日志也有

**Comment by 13462249457** [comment]
GetConnectionTimeoutException 这个问题解决了吗？我也遇到了同样的问题，错误信息如下：
`Cause: com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 60000, active 0, maxActive 200, creating 1, createElapseMillis 7209773`

**Comment by justabug9394** [comment]
> GetConnectionTimeoutException 这个问题解决了吗？我也遇到了同样的问题，错误信息如下： `Cause: com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 60000, active 0, maxActive 200, creating 1, createElapseMillis 7209773`

没解决呢，最近好像发生概率比较低，你也是偶发的吗，什么版本？

**Comment by Bughue** [comment]
> GetConnectionTimeoutException 这个问题解决了吗？我也遇到了同样的问题，错误信息如下： `Cause: com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 60000, active 0, maxActive 200, creating 1, createElapseMillis 7209773`

没解决呢，最近好像发生概率比较低，你也是偶发的吗，什么版本？

**Comment by georgecao** [comment]
记录一个类似的情况，通过设置`initialSize=1`貌似能缓解一下。
 
```
12:03:22  Caused by: com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 13, active 0, maxActive 20, creating 1, createElapseMillis 114
12:03:22  
12:03:22  	at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1896)
12:03:22  
12:03:22  	at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1498)
12:03:22  
12:03:22  	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5074)
12:03:22  
12:03:22  	at com.alibaba.druid.filter.FilterAdapter.dataSource_getConnection(FilterAdapter.java:2759)
12:03:22  
12:03:22  	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5070)
12:03:22  
12:03:22  	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1473)
12:03:22  
12:03:22  	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1463)
12:03:22  
12:03:22  	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:83)
12:03:22  
12:03:22  	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:160)
12:03:22  
12:03:22  	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:118)
12:03:22  
12:03:22  	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:81)
12:03:22  
12:03:22  	... 34 common frames omitted
```

**Comment by awaichixigua** [comment]
我用的是postgres的驱动，通过抓包发现服务器并没有发起TCP端口。通过arthars抓取线程状态，停留在pg驱动内的enablessl方法，改方法没有设置超时时间，导致一直等待超时。通过升级pg驱动解决该问题

![Image](https://github.com/user-attachments/assets/1e4a3fc9-17a2-4a19-8ead-c911a243d431)

**Comment by Bughue** [comment]
xdm，我这有个新进展，貌似是建立连接正常，但是通信的时候卡死（因为是mysql而且没有设置connectTimeout，我们猜测是丢包之类，一直等待），导致connect那个线程一直不工作。所以active=0，creating=1  。
我们这有人重现过，现象基本一致，不过不能完全证明是这个问题。目前加了监控，可是后面又没出现过了

**Comment by awaichixigua** [comment]
> xdm，我这有个新进展，貌似是建立连接正常，但是通信的时候卡死（因为是mysql而且没有设置connectTimeout，我们猜测是丢包之类，一直等待），导致connect那个线程一直不工作。所以active=0，creating=1 。 我们这有人重现过，现象基本一致，不过不能完全证明是这个问题。目前加了监控，可是后面又没出现过了。 然后我就想问druid自己等待的时候，是不是应该有个超时才对？

dolphinscheduler 使用的Hikari 连接池，Hikari 连接池中的数据库连接，由独立的 connection adder 线程池进行创建，待创建完成后将数据库连接移交给连接池进行维护。
我们这边使用流控工具模拟丢包,复现了该问题。在postgres驱动程序中打断点(mysql的驱动应该类似)

![Image](https://github.com/user-attachments/assets/7d51e9bf-dadc-4a76-9636-b0bafd58dba7)
# 以 root 用户进入容器
docker exec -it --user root timescaledb bash
# 安装流控工具
apt-get install iproute2
# 流控配置 100% 丢包（此方案的流控并不完美，会导致 ACK 包一并丢失，但一下子想不到更好的方法了）
tc qdisc add dev eth0 root netem loss 100%

可以复现该问题

**Comment by awaichixigua** [comment]
> xdm，我这有个新进展，貌似是建立连接正常，但是通信的时候卡死（因为是mysql而且没有设置connectTimeout，我们猜测是丢包之类，一直等待），导致connect那个线程一直不工作。所以active=0，creating=1 。 我们这有人重现过，现象基本一致，不过不能完全证明是这个问题。目前加了监控，可是后面又没出现过了。 然后我就想问druid自己等待的时候，是不是应该有个超时才对？

dolphinscheduler 使用的Hikari 连接池，Hikari 连接池中的数据库连接，由独立的 connection adder 线程池进行创建，待创建完成后将数据库连接移交给连接池进行维护。

![Image](https://github.com/user-attachments/assets/a87a39c4-f359-4f15-b96f-55fb1205e524)

我们这边使用流控工具模拟丢包,复现了该问题。在postgres驱动程序中打断点(mysql的驱动应该类似)

![Image](https://github.com/user-attachments/assets/112a708e-9209-4752-962d-55c20a5e26f1)

#以 root 用户进入容器
docker exec -it --user root timescaledb bash
#安装流控工具
apt-get install iproute2
#流控配置 100% 丢包（此方案的流控并不完美，会导致 ACK 包一并丢失，但一下子想不到更好的方法了）
tc qdisc add dev eth0 root netem loss 100%

可以复现该问题

**Comment by awaichixigua** [comment]
> xdm，我这有个新进展，貌似是建立连接正常，但是通信的时候卡死（因为是mysql而且没有设置connectTimeout，我们猜测是丢包之类，一直等待），导致connect那个线程一直不工作。所以active=0，creating=1 。 我们这有人重现过，现象基本一致，不过不能完全证明是这个问题。目前加了监控，可是后面又没出现过了。 然后我就想问druid自己等待的时候，是不是应该有个超时才对？

我们使用流控工具在pg驱动程序中打断点模拟100%丢包可以复现该问题。使用 JDBC 参数 socketTimeout=30可以解决该问题。

**Comment by CantosSong** [comment]
https://github.com/alibaba/druid/issues/6521

https://github.com/alibaba/druid/wiki/Druid%E9%94%81%E7%9A%84%E5%85%AC%E5%B9%B3%E6%A8%A1%E5%BC%8F%E9%97%AE%E9%A2%98

我这边同样的问题，线上并发高的时候，会出现GetConnectionTimeoutException，经过排查是默认非公平锁，导致sql先入后出导致超时
