### ISSUE TITLE
解析MySQL外层含有双层括号的嵌套CTE语句的时候报错

### ISSUE THREAD

**Issue by yx91490** [alibaba/druid#5494]
mysql版本：8.0
druid版本：1.2.20

样例代码：
```
public static void main(String[] args) throws IOException {
    String sql = IOUtils.resourceToString("/input.sql", StandardCharsets.UTF_8);
    MySqlStatementParser mySqlStatementParser = new MySqlStatementParser(sql);
    mySqlStatementParser.parseSelect();
}
```

如下的SQL会报错：
```
with t2 as ((
    with t1 as (select 1)
    select * from t1
))
select * from t2;
```
报错日志：
```
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'t2 as ((
    with t1 as (select 1)
    sel', expect ), actual WITH, pos 23, line 2, column 6, token WITH
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:857)
	at com.alibaba.druid.sql.parser.SQLParser.accept(SQLParser.java:865)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlSelectParser.query(MySqlSelectParser.java:115)
	at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:61)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseWith(SQLSelectParser.java:611)
	at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:57)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseSelect(MySqlStatementParser.java:112)
	at DruidDemo.main(DruidDemo.java:14)
```

如果把t2的双层括号改为单层括号，既SQL如下则正常解析:
```
with t2 as (
    with t1 as (select 1)
    select * from t1
)
select * from t2;
```

**Comment by lizongbo** [comment]
这里没有支持多层括号解析了，自己调整sql写法吧
