### ISSUE TITLE
怎么处理springboot+mybatis

### ISSUE THREAD

**Issue by zhangl-w** [alibaba/druid#5528]
org.springframework.transaction.CannotCreateTransactionException: Could not open JDBC Connection for transaction; nested exception is com.alibaba.druid.pool.DataSourceClosedException: dataSource already closed at Tue Jun 20 16:08:14 CST 2017
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:245)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:427)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:276)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
	at com.nlp.service.WebService$$EnhancerBySpringCGLIB$$cd43518b.createWebURL(<generated>)
	at com.nlp.job.Standalone.parse(Standalone.java:105)
	at com.nlp.job.Consumer.run(ConcurrentJob.java:95)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.alibaba.druid.pool.DataSourceClosedException: dataSource already closed at Tue Jun 20 16:08:14 CST 2017
	at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1057)
	at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:960)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:940)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:930)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:102)
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:204)
	... 12 more

**Comment by zrlw** [comment]
#5435
一类问题？

**Comment by lizongbo** [comment]
是连接池关闭之后还有db操作没有停止，通常是停止进程的时候，没有先把定时任务这些停止掉。

**Comment by hessenberg007** [comment]
如何优雅的关闭，是在容器销毁的时候，先去判断下定时任务？
