### ISSUE TITLE
druid 1.2.19 还没有支持 tdengine

### ISSUE THREAD

**Issue by maxid** [alibaba/druid#5532]
Caused by: java.lang.NullPointerException: Cannot invoke "com.alibaba.druid.DbType.ordinal()" because "dbType" is null
	at com.alibaba.druid.wall.WallFilter.init(WallFilter.java:106)
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:849)

**Comment by lizongbo** [comment]
欢迎贡献代码进行支持适配

**Comment by Amanocino** [comment]
这个问题应该是druid中filters中包含wall防火墙导致，目前WallFilter1.2.22版本虽然dbType中支持了tdengine但是依据dbtype构建Provider的时候会归类到default中导致还是不支持该类型，所以目前我的方法是filters配置中移除wall来解决，若有好的解决方法欢迎补充。
