### ISSUE TITLE
SQLStatementParser不支持PostgreSQL的异或位运算符(#)

### ISSUE THREAD

**Issue by TrickIt** [alibaba/druid#5546]
Caused by: com.alibaba.druid.sql.parser.ParserException: not supported.pos 98, line 3, column 25, token #
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:615)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:112)
	at com.alibaba.druid.wall.WallProvider.checkInternal(WallProvider.java:618)
	at com.alibaba.druid.wall.WallProvider.check(WallProvider.java:572)
	at com.alibaba.druid.wall.WallFilter.checkInternal(WallFilter.java:805)

**Comment by lizongbo** [comment]
发完整的sql语句或测试代码来
