### ISSUE TITLE
snakeyaml出错

### ISSUE THREAD

**Issue by 2576834738** [alibaba/druid#5649]
Caused by: org.yaml.snakeyaml.error.YAMLException: Unable to find getter for property 'tenantColumn' on object com.alibaba.druid.wall.WallFilter@46c9ee28:java.lang.reflect.InvocationTargetException
![Uploading 截图 2023-12-26 11-07-48.png…]()

1.2.20版本的druid

**Comment by 2576834738** [comment]
![截图 2023-12-26 11-06-34](https://github.com/alibaba/druid/assets/51956233/044c2a34-ffad-4ce3-b049-3cb213a58fa7)

**Comment by lizongbo** [comment]
WallFilter 里没有 tenantColumn这个变量
WallFilter 的 config变量，对应 WallConfig类型，然后WallConfig才有tenantColumn这个变量。

核实一下配置是否有误。

**Comment by bolyage** [comment]
我的场景是 shardingsphere-jdbc 用yaml 初始化 数据源的时候出了一样的问题。

config还没有初始化导致的getTenantColumn 的时候报空指针了。

代码是WallFilter 的 
`
    public String getTenantColumn() {
        return this.config.getTenantColumn();
    }
`

**Comment by lizongbo** [comment]
看了下 get set方法都在的,发个能重现异常的demo工程来吧。

![image](https://github.com/alibaba/druid/assets/1670666/557b3f7a-7dda-40f6-9640-cd559f818161)

**Comment by define9527** [comment]
# 版本信息
SpringBoot Version => 2.7.18
shardingsphere-jdbc-core-spring-boot-starter => 5.2.1
druid-spring-boot-starter => 1.2.21

# 配置文件
spring:
  shardingsphere:
    datasource:
      ds0:
        connection-properties: druid.stat.merggSql=ture;druid.stat.slowSqlMillis=5000
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: com.alibaba.druid.filter.stat.StatFilter,com.alibaba.druid.wall.WallFilter,com.alibaba.druid.filter.logging.Log4j2Filter

![image](https://github.com/alibaba/druid/assets/65441709/ccc01ca8-1d39-4493-898f-1d1cec1927e8)

如图，报错的真正原因，并不是 get/set 方法不存在，而是 WallFilter 的 config 变量为 null 导致的空指针问题

麻烦大佬们看下为什么 WallFilter 的 config 变量此时没什么没有初始化

**Comment by define9527** [comment]
[shardingsphere-jdbc-demo.zip](https://github.com/alibaba/druid/files/14545865/shardingsphere-jdbc-demo.zip)

附件代码可复现此问题

如果不配置 WallFilter 则运行正常，反之则抛出异常

**Comment by lizongbo** [comment]
看了下是shardingsphere使用snakeyml在启动的时候dump了javabean的属性信息，而这个时候还没有把config设置进去，
我加一下兼容逻辑吧。


```

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'shardingSphereDataSource' threw exception; nested exception is org.yaml.snakeyaml.error.YAMLException: Unable to find getter for property 'tenantColumn' on object com.alibaba.druid.wall.WallFilter@8eeb4c5:java.lang.reflect.InvocationTargetException
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:648)
	... 61 common frames omitted
Caused by: org.yaml.snakeyaml.error.YAMLException: Unable to find getter for property 'tenantColumn' on object com.alibaba.druid.wall.WallFilter@8eeb4c5:java.lang.reflect.InvocationTargetException
	at org.yaml.snakeyaml.introspector.MethodProperty.get(MethodProperty.java:81)
	at org.yaml.snakeyaml.representer.Representer.representJavaBean(Representer.java:107)
	at org.yaml.snakeyaml.representer.Representer$RepresentJavaBean.representData(Representer.java:83)
	at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:122)
	at org.yaml.snakeyaml.representer.BaseRepresenter.representSequence(BaseRepresenter.java:151)
	at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentList.representData(SafeRepresenter.java:193)
	at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:111)
	at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:174)
	at org.apache.shardingsphere.infra.util.yaml.representer.ShardingSphereYamlRepresenter.representMapping(ShardingSphereYamlRepresenter.java:69)
	at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:337)
	at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:111)
	at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:174)
	at org.apache.shardingsphere.infra.util.yaml.representer.ShardingSphereYamlRepresenter.representMapping(ShardingSphereYamlRepresenter.java:69)
	at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:337)
	at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:111)
	at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:81)
	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:269)
	at org.yaml.snakeyaml.Yaml.dumpAs(Yaml.java:318)
	at org.yaml.snakeyaml.Yaml.dumpAsMap(Yaml.java:341)
	at org.apache.shardingsphere.infra.util.yaml.YamlEngine.marshal(YamlEngine.java:113)
	at org.apache.shardingsphere.mode.metadata.persist.service.config.database.DataSourcePersistService.persist(DataSourcePersistService.java:56)
	at org.apache.shardingsphere.mode.metadata.persist.service.config.database.DataSourcePersistService.conditionalPersist(DataSourcePersistService.java:46)
	at org.apache.shardingsphere.mode.metadata.persist.MetaDataPersistService.persistConfigurations(MetaDataPersistService.java:94)
	at org.apache.shardingsphere.mode.manager.standalone.StandaloneContextManagerBuilder.persistConfigurations(StandaloneContextManagerBuilder.java:55)
	at org.apache.shardingsphere.mode.manager.standalone.StandaloneContextManagerBuilder.build(StandaloneContextManagerBuilder.java:46)
	at org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource.createContextManager(ShardingSphereDataSource.java:76)
	at org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource.<init>(ShardingSphereDataSource.java:64)
	at org.apache.shardingsphere.driver.api.ShardingSphereDataSourceFactory.createDataSource(ShardingSphereDataSourceFactory.java:93)
	at org.apache.shardingsphere.spring.boot.ShardingSphereAutoConfiguration.shardingSphereDataSource(ShardingSphereAutoConfiguration.java:91)
	at org.apache.shardingsphere.spring.boot.ShardingSphereAutoConfiguration$$EnhancerBySpringCGLIB$$1eec713e.CGLIB$shardingSphereDataSource$2(<generated>)
	at org.apache.shardingsphere.spring.boot.ShardingSphereAutoConfiguration$$EnhancerBySpringCGLIB$$1eec713e$$FastClassBySpringCGLIB$$cecff963.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at org.apache.shardingsphere.spring.boot.ShardingSphereAutoConfiguration$$EnhancerBySpringCGLIB$$1eec713e.shardingSphereDataSource(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 62 common frames omitted

```

**Comment by lizongbo** [comment]
下周等1.2.22发布之后请再验证。
