### ISSUE TITLE
重启tomcat报错：ERROR DruidDataSourceStatManager  unregister mbean error

### ISSUE THREAD

**Issue by ghost** [alibaba/druid#570]
具体信息：
ERROR DruidDataSourceStatManager - 2014-06-27 17:36:24 - unregister mbean error
javax.management.InstanceNotFoundException: com.alibaba.druid:type=DruidDataSourceStat
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1095) ~[na:1.7.0_51]
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.exclusiveUnregisterMBean(DefaultMBeanServerInterceptor.java:427) ~[na:1.7.0_51]
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.unregisterMBean(DefaultMBeanServerInterceptor.java:415) ~[na:1.7.0_51]
        at com.sun.jmx.mbeanserver.JmxMBeanServer.unregisterMBean(JmxMBeanServer.java:546) ~[na:1.7.0_51]
        at com.alibaba.druid.stat.DruidDataSourceStatManager.removeDataSource(DruidDataSourceStatManager.java:202) ~[DruidDataSourceStatManager.class:1.0.1]
        at com.alibaba.druid.pool.DruidDataSource$2.run(DruidDataSource.java:1314) [DruidDataSource$2.class:1.0.1]
        at java.security.AccessController.doPrivileged(Native Method) [na:1.7.0_51]
        at com.alibaba.druid.pool.DruidDataSource.unregisterMbean(DruidDataSource.java:1310) [DruidDataSource.class:1.0.1]
        at com.alibaba.druid.pool.DruidDataSource.close(DruidDataSource.java:1271) [DruidDataSource.class:1.0.1]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_51]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_51]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_51]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_51]
        at org.springframework.beans.factory.support.DisposableBeanAdapter.invokeCustomDestroyMethod(DisposableBeanAdapter.java:327) [DisposableBeanAdapter.class:3.2.5.RELEASE]
        at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:253) [DisposableBeanAdapter.class:3.2.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:510) [DefaultSingletonBeanRegistry.class:3.2.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:486) [DefaultSingletonBeanRegistry.class:3.2.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:742) [DefaultListableBeanFactory.class:3.2.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:455) [DefaultSingletonBeanRegistry.class:3.2.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1090) [AbstractApplicationContext.class:3.2.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1064) [AbstractApplicationContext.class:3.2.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1010) [AbstractApplicationContext.class:3.2.5.RELEASE]
        at org.springframework.web.context.ContextLoader.closeWebApplicationContext(ContextLoader.java:559) [ContextLoader.class:3.2.5.RELEASE]
        at org.springframework.web.context.ContextLoaderListener.contextDestroyed(ContextLoaderListener.java:143) [ContextLoaderListener.class:3.2.5.RELEASE]
        at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:4779) [catalina.jar:8.0.3]
        at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5372) [catalina.jar:8.0.3]
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232) [catalina.jar:8.0.3]
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1403) [catalina.jar:8.0.3]
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1392) [catalina.jar:8.0.3]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_51]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_51]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_51]
        at java.lang.Thread.run(Thread.java:744) [na:1.7.0_51]
ERROR DruidStatService - 2014-06-27 17:36:24 - unregister mbean error
javax.management.InstanceNotFoundException: com.alibaba.druid:type=DruidStatService
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1095) ~[na:1.7.0_51]
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.exclusiveUnregisterMBean(DefaultMBeanServerInterceptor.java:427) ~[na:1.7.0_51]
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.unregisterMBean(DefaultMBeanServerInterceptor.java:415) ~[na:1.7.0_51]
        at com.sun.jmx.mbeanserver.JmxMBeanServer.unregisterMBean(JmxMBeanServer.java:546) ~[na:1.7.0_51]
        at com.alibaba.druid.stat.DruidStatService.unregisterMBean(DruidStatService.java:366) ~[DruidStatService.class:1.0.1]
        at com.alibaba.druid.stat.DruidDataSourceStatManager.removeDataSource(DruidDataSourceStatManager.java:207) [DruidDataSourceStatManager.class:1.0.1]
        at com.alibaba.druid.pool.DruidDataSource$2.run(DruidDataSource.java:1314) [DruidDataSource$2.class:1.0.1]
        at java.security.AccessController.doPrivileged(Native Method) [na:1.7.0_51]
        at com.alibaba.druid.pool.DruidDataSource.unregisterMbean(DruidDataSource.java:1310) [DruidDataSource.class:1.0.1]
        at com.alibaba.druid.pool.DruidDataSource.close(DruidDataSource.java:1271) [DruidDataSource.class:1.0.1]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_51]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_51]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_51]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_51]
        at org.springframework.beans.factory.support.DisposableBeanAdapter.invokeCustomDestroyMethod(DisposableBeanAdapter.java:327) [DisposableBeanAdapter.class:3.2.5.RELEASE]
        at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:253) [DisposableBeanAdapter.class:3.2.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:510) [DefaultSingletonBeanRegistry.class:3.2.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:486) [DefaultSingletonBeanRegistry.class:3.2.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:742) [DefaultListableBeanFactory.class:3.2.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:455) [DefaultSingletonBeanRegistry.class:3.2.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1090) [AbstractApplicationContext.class:3.2.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1064) [AbstractApplicationContext.class:3.2.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1010) [AbstractApplicationContext.class:3.2.5.RELEASE]
        at org.springframework.web.context.ContextLoader.closeWebApplicationContext(ContextLoader.java:559) [ContextLoader.class:3.2.5.RELEASE]
        at org.springframework.web.context.ContextLoaderListener.contextDestroyed(ContextLoaderListener.java:143) [ContextLoaderListener.class:3.2.5.RELEASE]
        at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:4779) [catalina.jar:8.0.3]
        at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5372) [catalina.jar:8.0.3]
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232) [catalina.jar:8.0.3]
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1403) [catalina.jar:8.0.3]
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1392) [catalina.jar:8.0.3]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_51]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_51]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_51]
        at java.lang.Thread.run(Thread.java:744) [na:1.7.0_51]

大家有什么解决办法吗？

**Comment by lizongbo** [comment]
请使用最新版验证
