### ISSUE TITLE
druid创建连接时报错

### ISSUE THREAD

**Issue by zhaoydo** [alibaba/druid#5701]
版本信息
druid 1.2.6
mysql-connector-java 8.0.22
mysql 8

错误栈信息，看起来是业务sql报错。但是不明白为什么会出现在Druid-ConnectionPool-Create-线程中
` [Druid-ConnectionPool-Create-1767672626] [DruidDataSource.java:2803] ERROR com.alibaba.druid.pool.DruidDataSource - create connection SQLException, url: jdbc:mysql://xxxx?zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useTimezone=true&serverTimezone=GMT%2B8, errorCode 1265, state 22001
com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data truncated for column 'listing_price' at row 1
	at com.mysql.cj.protocol.a.NativeProtocol.convertShowWarningsToSQLWarnings(NativeProtocol.java:2121)
	at com.mysql.cj.protocol.a.NativeProtocol.scanForAndThrowDataTruncation(NativeProtocol.java:1933)
	at com.mysql.cj.protocol.a.NativeProtocol.readAllResults(NativeProtocol.java:1665)
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:959)
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryString(NativeProtocol.java:892)
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:1073)
	at com.mysql.cj.jdbc.ConnectionImpl.setupServerForTruncationChecks(ConnectionImpl.java:2296)
	at com.mysql.cj.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:1341)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:967)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:826)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1657)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1723)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2801)`

**Comment by lizongbo** [comment]
使用最新版druid 1.2.21 + mysql jdbc 8.3.0
 验证，这个看上去更像是触发了mysql server的bug，把另外一个连接应该收取的异常信息缓存了，然后返回给了这个连接。

mysql jdbc 8.0.2x有不少坑的。
