### ISSUE TITLE
不支持 PG  SHOW search_path

### ISSUE THREAD

**Issue by cedooo** [alibaba/druid#5710]
druid 1.2.20 

```
2024-01-26 11:59:09.742 ERROR 5388 --- [           main] c.alibaba.druid.filter.stat.StatFilter   : merge sql error, dbType null, druid-1.2.20, sql : SHOW search_path
com.alibaba.druid.sql.parser.ParserException: not supported.pos 4, line 1, column 1, token IDENTIFIER SHOW
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:616) ~[druid-1.2.20.jar:na]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:102) ~[druid-1.2.20.jar:na]
	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:164) ~[druid-1.2.20.jar:na]
	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:135) ~[druid-1.2.20.jar:na]
	at com.alibaba.druid.filter.stat.StatFilter.mergeSql(StatFilter.java:148) [druid-1.2.20.jar:na]
	at com.alibaba.druid.filter.stat.StatFilter.createSqlStat(StatFilter.java:672) [druid-1.2.20.jar:na]
	at com.alibaba.druid.filter.stat.StatFilter.statementPrepareAfter(StatFilter.java:325) [druid-1.2.20.jar:na]
	at com.alibaba.druid.filter.FilterEventAdapter.connection_prepareStatement(FilterEventAdapter.java:118) [druid-1.2.20.jar:na]
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:531) [druid-1.2.20.jar:na]
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.prepareStatement(ConnectionProxyImpl.java:328) [druid-1.2.20.jar:na]
	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:369) [druid-1.2.20.jar:na]
```

**Comment by lizongbo** [comment]
1.2.21已经支持解析了，但是toString的话会报错，因此再优化一下，

楼主报错这个，明显dbType null，说明dbtype未能识别或配置有误，可以明确通过配置指定 dbType为postgresql避免报错。
