### ISSUE TITLE
postgres sql parse error

### ISSUE THREAD

**Issue by via-red** [alibaba/druid#5752]
example:
ALTER TABLE if exists ref_standard_indicator add column if not exists parent_code varchar(64);

error logs:
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: illegal name, pos 58, line 1, column 57, token IF
	at com.alibaba.druid.sql.parser.SQLExprParser.name(SQLExprParser.java:2385)
	at com.alibaba.druid.sql.parser.SQLExprParser.parseColumn(SQLExprParser.java:4639)
	at com.alibaba.druid.sql.parser.SQLExprParser.parseColumn(SQLExprParser.java:4633)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseAlterTableAddColumn(SQLStatementParser.java:4758)
	at com.alibaba.druid.sql.parser.SQLStatementParser.alterTableAdd(SQLStatementParser.java:2466)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseAlter(SQLStatementParser.java:1902)
	at com.alibaba.druid.sql.dialect.postgresql.parser.PGSQLStatementParser.parseAlter(PGSQLStatementParser.java:422)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:301)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:603)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:624)
	at com.miotech.Main.main(Main.java:14)

**Comment by lizongbo** [comment]
已经增强语法解析逻辑，等1.2.22构建之后再验证

**Comment by via-red** [comment]
感谢
