### ISSUE TITLE
druid 1.2.21连接数据库异常导致连接池关闭

### ISSUE THREAD

**Issue by genvyday** [alibaba/druid#5753]
出现类似错误，导致连接池关闭，实际上再次连接是可以连上，任何情况下不应该自动关闭连接池吧。自动关闭连接池这逻辑真是奇葩。

ERROR 20240229:000000:init datasource error, url: jdbc:oracle:thin:@1.1.1.1:1521/sid:DruidDataSource.java:940
java.sql.SQLRecoverableException: ORA-17002: I/O error: Connection reset by peer, Authentication lapse 128978 ms.
https://docs.oracle.com/error-help/db/ora-17002/

**Comment by lizongbo** [comment]
发完整的出错堆栈信息出来

**Comment by genvyday** [comment]
ERROR:20240229.000000:http-nio-8081-exec-1:init datasource error, url: jdbc:oracle:thin:@172.16.53.48:1566/gcptrx_vip:DruidDataSource.java:940
java.sql.SQLRecoverableException: ORA-17002: I/O error: Connection reset by peer, Authentication lapse 124324 ms.
https://docs.oracle.com/error-help/db/ora-17002/
        at oracle.jdbc.driver.T4CConnection.handleLogonIOException(T4CConnection.java:1425) ~[ojdbc8-23.3.0.23.09.jar:23.3.0.23.09]
        at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:978) ~[ojdbc8-23.3.0.23.09.jar:23.3.0.23.09]
        at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:1126) ~[ojdbc8-23.3.0.23.09.jar:23.3.0.23.09]
        at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:104) ~[ojdbc8-23.3.0.23.09.jar:23.3.0.23.09]
        at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:825) ~[ojdbc8-23.3.0.23.09.jar:23.3.0.23.09]
        at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:651) ~[ojdbc8-23.3.0.23.09.jar:23.3.0.23.09]
        at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:132) ~[druid-1.2.21.jar:?]
        at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:244) ~[druid-1.2.21.jar:?]
        at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:126) ~[druid-1.2.21.jar:?]
        at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1699) ~[druid-1.2.21.jar:?]
        at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1794) ~[druid-1.2.21.jar:?]
        at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:936) ~[druid-1.2.21.jar:?]
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1473) ~[druid-1.2.21.jar:?]
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1469) ~[druid-1.2.21.jar:?]
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:83) ~[druid-1.2.21.jar:?]

**Comment by codedad1983** [comment]
see #5771

我们是一个问题。能不能让 @zrlw 别瞎搞？这段逻辑你们是怎么想的？

**Comment by lizongbo** [comment]
1.2.22 已经发布，请升级验证。

**Comment by Datayaya** [comment]
me too ///
