### ISSUE TITLE
An exception occurs when the subquery contains a specific recursive CTE

### ISSUE THREAD

**Issue by h2cone** [alibaba/druid#5761]
This is the SQL that triggered the exception:

```shell
### Error querying database.  Cause: java.sql.SQLException: sql injection violation, dbType mysql, , druid-version 1.2.21, syntax error: syntax error, expect ), actual IDENTIFIER pos 55, line 4, column 18, token IDENTIFIER RECURSIVE : select
        id,
        (
            WITH RECURSIVE link_hierarchy AS (
                SELECT id, parent_id
                FROM tmp_link
                WHERE id = ?

                UNION ALL

                SELECT tl.id, tl.parent_id
                FROM tmp_link tl
                INNER JOIN link_hierarchy lh ON tl.id = lh.parent_id
            )
            SELECT CONCAT('/', GROUP_CONCAT(id ORDER BY id ASC SEPARATOR '/')) AS path
            FROM link_hierarchy
        ) as path
        from tmp_link
```

This is the exception stack:

```shell
Caused by: com.alibaba.druid.sql.parser.ParserException: syntax error, expect ), actual IDENTIFIER pos 55, line 4, column 18, token IDENTIFIER RECURSIVE
	at com.alibaba.druid.sql.parser.SQLExprParser.accept(SQLExprParser.java:4652)
	at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:394)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.primary(MySqlExprParser.java:527)
	at com.alibaba.druid.sql.parser.SQLExprParser.expr(SQLExprParser.java:109)
	at com.alibaba.druid.sql.parser.SQLExprParser.parseSelectItem(SQLExprParser.java:6369)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseSelectList(SQLSelectParser.java:1069)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlSelectParser.query(MySqlSelectParser.java:235)
	at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:62)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseSelect(MySqlStatementParser.java:112)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:220)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:117)
	at com.alibaba.druid.wall.WallProvider.checkInternal(WallProvider.java:494)
	at com.alibaba.druid.wall.WallProvider.check(WallProvider.java:446)
	at com.alibaba.druid.wall.WallFilter.checkInternal(WallFilter.java:808)
	... 140 common frames omitted
```
It works normally when I remove `wall` from `druid.filters`.

**Comment by lizongbo** [comment]
这个sql语句太复杂，目前还不太好解析支持。

```
  public void test_parse() throws Exception {
        String sql = "select\n"
            + "        id,\n"
            + "        (\n"
            + "            WITH RECURSIVE link_hierarchy AS (\n"
            + "                SELECT id, parent_id\n"
            + "                FROM tmp_link\n"
            + "                WHERE id = ?\n"
            + "\n"
            + "                UNION ALL\n"
            + "\n"
            + "                SELECT tl.id, tl.parent_id\n"
            + "                FROM tmp_link tl\n"
            + "                INNER JOIN link_hierarchy lh ON tl.id = lh.parent_id\n"
            + "            )\n"
            + "            SELECT CONCAT('/', GROUP_CONCAT(id ORDER BY id ASC SEPARATOR '/')) AS path\n"
            + "            FROM link_hierarchy\n"
            + "        ) as path\n"
            + "        from tmp_link";
        SQLStatementParser parser = SQLParserUtils.createSQLStatementParser(sql, JdbcConstants.MYSQL);
        SQLStatement statement = parser.parseStatement();
        System.out.println(statement);

    }
```

**Comment by lizongbo** [comment]
postgresql支持这个，mysql不支持，参考加上了支持
