### ISSUE TITLE
1.2.20版本出现 GetConnectionTimeoutException: wait millis 10000, active 0, maxActive 50, creating 1, createElapseMillis 20023

### ISSUE THREAD

**Issue by 184005306** [alibaba/druid#5775]
版本：1.2.20
正式环境运行1到2个月就会出现1次或者2次，重启就好，然后继续运行几个月还会出现
org.springframework.transaction.CannotCreateTransactionException: Could not open JDBC Connection for transaction; nested exception is com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 10000, active 0, maxActive 50, creating 1, createElapseMillis 20023
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:305)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:378)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:474)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:289)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at com.hrbcst.web.taskdata.service.impl.TaskDataServiceImpl$$EnhancerBySpringCGLIB$$ecab2f54.processSv(<generated>)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at com.xxl.job.service.handler.DemoGlueJobHandler.execute(Script_aeacec6b7eb4e15fda7e711076fc2055.groovy:21)
	at com.xxl.job.core.handler.impl.GlueJobHandler.execute(GlueJobHandler.java:26)
	at com.xxl.job.core.thread.JobThread.run(JobThread.java:166)
Caused by: com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 10000, active 0, maxActive 50, creating 1, createElapseMillis 20023
	at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1870)
	at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1493)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5058)
	at com.alibaba.druid.filter.logging.LogFilter.dataSource_getConnection(LogFilter.java:909)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5054)
	at com.alibaba.druid.filter.FilterAdapter.dataSource_getConnection(FilterAdapter.java:2759)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5054)
	at com.alibaba.druid.filter.stat.StatFilter.dataSource_getConnection(StatFilter.java:704)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5054)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1468)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1458)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:83)
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:262)
	... 11 common frames omitted

**Comment by lizongbo** [comment]
1.2.22已经发布，请使用1.2.22验证是否重现

**Comment by 001xinshijie** [comment]
在1.1.22 版本中同样出现该问题，前提是Oracle rac 集群重构，应用服务在数据库恢复后6小时候出现上述问题，不明白为什么createElapseMillis 会显示22433070 ，正常情况下这个参数是根据是什么条件累积的。在测试环境验证，在物理关闭网络并恢复后，复现了这个问题，就是在数据已经恢复正常的情况下，应用还是偶发出现etConnectionTimeoutException但是keepalive 设置的false，test-on-borrow 为true。

**Comment by pengjianbo** [comment]
遇到同样问题

**Comment by predator4ann** [comment]
遇到同样问题，版本1.2.21

**Comment by zangjunjie** [comment]
遇到同样的问题，等待解决，查了源码，也没有找到是什么原因导致的，怀疑数据库偶尔断开的策略，目前改了些参数，基本上是一周就会有问题，等待大佬解决下

**Comment by a97659096** [comment]
我也遇到了这个问题，断网恢复后报这个错误，然后重启服务恢复正常

**Comment by zhoutianzhe** [comment]
1.2.18 也碰到这个错。
![image](https://github.com/user-attachments/assets/34d77fc9-f260-45cf-9a9a-6a13676b735b)

**Comment by 001xinshijie** [comment]
配置connection timeout 和sockettimeout---- 回复的原邮件 ***@***.***>发送日期2024年11月5日 ***@***.***>***@***.***>***@***.***>主题Re: [alibaba/druid] 1.2.20版本出现 GetConnectionTimeoutException: wait millis 10000, active 0, maxActive 50, creating 1, createElapseMillis 20023 (Issue #5775)1.2.18 也碰到这个错。
image.png (view on web)—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by Caolin9** [comment]
遇到同样问题，场景是数据库主节点异常下电，主备切换后，一直报GetConnectionTimeoutException，同时createElapseMillis一直在增长，重启服务后正常。配置了socketTimeout，但是没配在jdbcurl上

**Comment by Caolin9** [comment]
socketTimeout配在jdbcurl上就好了
