### ISSUE TITLE
最新的版本1.2.22解析sql报错

### ISSUE THREAD

**Issue by nothingbj** [alibaba/druid#5780]
sql是：
`CREATE INDEX "index_log" ON "public"."check_log" USING btree (
  "t_no" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);`

版本是最新的 1.2.22
测试代码是：

```
String sql = "CREATE INDEX \"index_log\" ON \"public\".\"check_log\" USING btree (\n" +
                "  \"t_no\" COLLATE \"pg_catalog\".\"default\" \"pg_catalog\".\"text_ops\" ASC NULLS LAST\n" +
                ");";
        List<SQLStatement> sqlStatements = SQLUtils.parseStatements(sql, JdbcConstants.POSTGRESQL);

```
报错信息是：
`Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'btree (
  "t_no" COLLATE "pg_catalog"."default"', expect ), actual ., pos 93, line 2, column 30, token .
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:863)
	at com.alibaba.druid.sql.parser.SQLParser.accept(SQLParser.java:871)
	at com.alibaba.druid.sql.dialect.postgresql.parser.PGSQLStatementParser.parseCreateIndex(PGSQLStatementParser.java:781)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseCreate(SQLStatementParser.java:3602)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:278)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:600)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:621)
	at pd.key.main(key.java:78)`

**Comment by lizongbo** [comment]
确定这个sql语句是能正常在PostgreSQL执行的么？
我看官方示例里 COLLATE 对应的 "en_US" 这样的值。

**Comment by nothingbj** [comment]
> 确定这个sql语句是能正常在PostgreSQL执行的么？ 我看官方示例里 COLLATE 对应的 "en_US" 这样的值。

可以执行
![Uploading 319.png…]()

**Comment by nothingbj** [comment]
这个sql也解析失败了

`ALTER TABLE "public"."check_log" 
 ADD COLUMN "page_title_styl_desc" varchar(200),
ALTER COLUMN "version" TYPE varchar(10) USING "version"::varchar(10);
`
报错信息是：
`com.alibaba.druid.sql.parser.ParserException: not supported.pos 128, line 3, column 41, token USING
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:654)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:600)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:621)
	at pd.key.main(key.java:84)`

![3191](https://github.com/alibaba/druid/assets/7500295/5fb9878f-affa-4e8c-aeb2-7ed31593306c)

**Comment by lizongbo** [comment]
看了下解析逻辑，原来的写得有问题，而且还不好改，改了之后影响其它用例，需要再研究下看怎么修改比较好。

**Comment by lizongbo** [comment]
加上支持了，等新版本1.2.23出来再验证
