### ISSUE TITLE
不支持MySQL8.0 alter table tt ALTER COLUMN c1 SET VISIBLE语法

### ISSUE THREAD

**Issue by leezw2016** [alibaba/druid#5803]
dbtype: mysql
dbversion: 8.0.32
duird version: 1.2.22
error sql: alter table tt ALTER COLUMN c1 SET VISIBLE;
error info: 
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: syntax error, error in :' SET VISIBLE;
', expect DEFAULT, actual null, pos 42, line 1, column 36, token IDENTIFIER VISIBLE
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:863)
	at com.alibaba.druid.sql.parser.SQLParser.accept(SQLParser.java:871)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseAlterSpecification(MySqlStatementParser.java:6682)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseAlterTable(MySqlStatementParser.java:6914)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseAlter(MySqlStatementParser.java:5248)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:339)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:600)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:621)
	at com.baidu.dba.SqlParser.testNewParseSql(SqlParser.java:989)
	at com.baidu.dba.SqlParser.main(SqlParser.java:85)

**Comment by lizongbo** [comment]
等1.2.23验证
