### ISSUE TITLE
前后查询都正常，突然就发生"errorCode 17002"异常，造成后续数据库操作失败，然后内存溢出

### ISSUE THREAD

**Issue by MarcusMjk** [alibaba/druid#5830]
**dbtype:**  `oracle`
**dbversion:**   `11.2.0.4`
**druid verion:** `1.2.8`
**error sql:** `select COMMON_MSGID.nextval from dual`
**testcase code:**  
**stacktrace info:** ```
2024-04-08 09:41:23.339 ERROR [Druid-ConnectionPool-Create-936618636] com.alibaba.druid.pool.DruidDataSource       2840: create connection SQLException, url: jdbc:oracle:thin:@xx.xxx.xx.xxx:xxxx/xx, errorCode 17002, state 08006
java.sql.SQLRecoverableException: IO 错误: 远程主机强迫关闭了一个现有的连接。, Authentication lapse 25481 ms.
	at oracle.jdbc.driver.T4CConnection.handleLogonIOException(T4CConnection.java:915)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:680)
	at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:1039)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:90)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:728)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:649)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1657)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1723)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2838)
Caused by: java.io.IOException: 远程主机强迫关闭了一个现有的连接。, Authentication lapse 25481 ms.
	at oracle.jdbc.driver.T4CConnection.handleLogonIOException(T4CConnection.java:910)
	... 8 common frames omitted
Caused by: java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at oracle.net.nt.TimeoutSocketChannel.write(TimeoutSocketChannel.java:467)
	at oracle.net.ns.NIOPacket.writeToSocketChannel(NIOPacket.java:361)
	at oracle.net.ns.NIONSDataChannel.writeDataToSocketChannel(NIONSDataChannel.java:206)
	at oracle.net.ns.NIONSDataChannel.writeDataToSocketChannel(NIONSDataChannel.java:151)
	at oracle.jdbc.driver.T4CMAREngineNIO.flush(T4CMAREngineNIO.java:804)
	at oracle.jdbc.driver.T4CMAREngineNIO.prepareForUnmarshall(T4CMAREngineNIO.java:822)
	at oracle.jdbc.driver.T4CMAREngineNIO.unmarshalUB1(T4CMAREngineNIO.java:487)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:622)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:299)
	at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:390)
	at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTHWithO5Logon(T4CTTIoauthenticate.java:1471)
	at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:1220)
	at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:1174)
	at oracle.jdbc.driver.T4CConnection.authenticateUserForLogon(T4CConnection.java:1032)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:648)
	... 7 common frames omitted```
**error info:**   `create connection SQLException, url: jdbc:oracle:thin:@xx.xxx.xx.xxx:xxxx/xx, errorCode 17002, state 08006`

**Comment by MarcusMjk** [comment]
求各位大佬帮忙看下怎么解决，，

**Comment by lizongbo** [comment]
用1.2.22版本验证，你这个是创建连接时确实连不上oracle数据库。

**Comment by zangjunjie** [comment]
解决了，这个问题？？？
