### ISSUE TITLE
升级到druid1.2.22后调用getConnection接口报 Method not supported

### ISSUE THREAD

**Issue by niegl** [alibaba/druid#5837]
java.sql.SQLException: Method not supported
	at org.apache.hive.jdbc.HiveConnection.isValid(HiveConnection.java:1077)
	at com.alibaba.druid.pool.DruidStatementConnection.isValid(DruidStatementConnection.java:274)
	at com.alibaba.druid.pool.vendor.HiveValidConnectionChecker.isValidConnection(HiveValidConnectionChecker.java:20)
	at com.alibaba.druid.pool.DruidAbstractDataSource.validateConnection(DruidAbstractDataSource.java:1436)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1828)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2928)
---

**Comment by lizongbo** [comment]
hive jdbc版本太低？
https://github.com/apache/hive/blob/master/jdbc/src/java/org/apache/hive/jdbc/HiveConnection.java
 看官方是已经实现isValid方法了的。

**Comment by niegl** [comment]
不是 jdbc版本的问题。 同样的jdbc 升级druid1.2.22以前是没有问题的。应该是创建连接的代码逻辑变了

**Comment by lizongbo** [comment]
> 不是 jdbc版本的问题。 同样的jdbc 升级druid1.2.22以前是没有问题的。应该是创建连接的代码逻辑变了

首先，是jdbc版本有问题，你用的低版本hive jdbc，还没实现这个方法。
其次，1.2.22是有人提交了定制的HiveValidConnectionChecker，想优化成优先使用isValid方法来提示验证连接可用性的性能，但是没想到hive jdbc的低版本根本不支持这个方法。

因此从兼容性考虑，再去做hive jdbc版本探测然后做不同逻辑的必要性不大， 近期会把这个HiveValidConnectionChecker会移除掉，恢复成原来的样子。

**Comment by niegl** [comment]
> > 不是 jdbc版本的问题。 同样的jdbc 升级druid1.2.22以前是没有问题的。应该是创建连接的代码逻辑变了
> 
> 首先，是jdbc版本有问题，你用的低版本hive jdbc，还没实现这个方法。 其次，1.2.22是有人提交了定制的HiveValidConnectionChecker，想优化成优先使用isValid方法来提示验证连接可用性的性能，但是没想到hive jdbc的低版本根本不支持这个方法。
> 
> 因此从兼容性考虑，再去做hive jdbc版本探测然后做不同逻辑的必要性不大， 近期会把这个HiveValidConnectionChecker会移除掉，恢复成原来的样子。

那问题就比较清楚了，就是提交的定制HiveValidConnectionChecker有些低版本不支持。考虑兼容，能够恢复原来的样子最好

**Comment by niegl** [comment]
> > 不是 jdbc版本的问题。 同样的jdbc 升级druid1.2.22以前是没有问题的。应该是创建连接的代码逻辑变了
> 
> 首先，是jdbc版本有问题，你用的低版本hive jdbc，还没实现这个方法。 其次，1.2.22是有人提交了定制的HiveValidConnectionChecker，想优化成优先使用isValid方法来提示验证连接可用性的性能，但是没想到hive jdbc的低版本根本不支持这个方法。
> 
> 因此从兼容性考虑，再去做hive jdbc版本探测然后做不同逻辑的必要性不大， 近期会把这个HiveValidConnectionChecker会移除掉，恢复成原来的样子。

那问题就比较清楚了，就是提交的定制HiveValidConnectionChecker有些低版本不支持。考虑兼容，能够恢复原来的样子最好
