### ISSUE TITLE
spring boot  3.0.6 整合droid1.2.22报错

### ISSUE THREAD

**Issue by jaimyjie** [alibaba/druid#5841]
您好

环境：spring boot  3.0.6，druid-spring-boot-3-starter 1.2.22，spring-boot-starter-data-jpa 3.0.6, druid多数据源配置

在spring boot  2.7环境正常，升级到spring boot  3.0.6时报错，是还要配置什么吗？谢谢

报错信息：
	... 82 more
Caused by: org.hibernate.HibernateException: Unable to determine Dialect without JDBC metadata (please set 'javax.persistence.jdbc.url', 'hibernate.connection.url', or 'hibernate.dialect')
	at org.hibernate.engine.jdbc.dialect.internal.DialectFactoryImpl.determineDialect(DialectFactoryImpl.java:147)
	at org.hibernate.engine.jdbc.dialect.internal.DialectFactoryImpl.buildDialect(DialectFactoryImpl.java:60)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:244)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:36)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:119)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:255)

**Comment by lizongbo** [comment]
你这个看上去hibernae没有匹配到数据源，然后引导走hibernate的配置，检查下应该是hibernate的配置需要更新。

**Comment by jaimyjie** [comment]
> 你这个看上去hibernae没有匹配到数据源，然后引导走hibernate的配置，检查下应该是hibernate的配置需要更新。

感觉是升级到3.06后，都不到数据库配置文件，2.x场景是没有针对hibernate独立配置数据库连接配置哦

**Comment by xiangyunup** [comment]
我用1.2.20 正常，升级1.2.22之后 也是url 错误，回退之后就正常了；我用的springboot 2.7.18

**Comment by blankhang** [comment]
我用1.2.21 正常 1.2.22 也是url错误 springboot3.2.5版本

**Comment by lizongbo** [comment]
请使用1.2.23验证
