### ISSUE TITLE
1.2.22 开启filter后对sqlserver的空间函数报错

### ISSUE THREAD

**Issue by hanpijun-buhanpi** [alibaba/druid#5860]
报错SQL语句：
geometry::Point(vs.longitude, vs.latitude, 4326).STWithin(m.region) = 1

异常信息：
Caused by: com.alibaba.druid.sql.parser.ParserException: not supported.pos 832, line 14, column 28, token ::
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:654)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:117)
	at com.alibaba.druid.wall.WallProvider.checkInternal(WallProvider.java:494)
	at com.alibaba.druid.wall.WallProvider.check(WallProvider.java:446)
	at com.alibaba.druid.wall.WallFilter.checkInternal(WallFilter.java:853)

**Comment by lizongbo** [comment]
发完整的sql，这种半截sql无助于分析原因。
