### ISSUE TITLE
解析postgresql得删除函数语法报错

### ISSUE THREAD

**Issue by huangyao229328404** [alibaba/druid#5922]
**dbtype:**  postgresql
**dbversion:**  12
**druid verion:** 1.2.22
**error sql:** DROP FUNCTION IF EXISTS add_numbers(a integer)  或者 DROP FUNCTION add_numbers()
**testcase code:**

```java
String sql = "DROP FUNCTION IF EXISTS add_numbers(a integer)";

SQLStatementParser parser = new SQLStatementParser(sql, DbType.postgresql);
SQLStatement sqlStatement = parser.parseStatement();
```
**stacktrace info:**

```
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: not supported.pos 23, line 1, column 18, token EXISTS
	at com.alibaba.druid.sql.parser.SQLStatementParser.checkEndToken(SQLStatementParser.java:4983)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:4973)
```

和
```
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: not supported.pos 26, line 1, column 26, token (
	at com.alibaba.druid.sql.parser.SQLStatementParser.checkEndToken(SQLStatementParser.java:4983)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:4973)
```

**Comment by lizongbo** [comment]
等1.2.24版验证。
