### ISSUE TITLE
求救：项目刚启动的时候，业务访问就报错，后面的访问就正常了

### ISSUE THREAD

**Issue by MrXiaoLinZi** [alibaba/druid#5924]
在项目刚启动成功的时候，访问数据库就会报错，后面的访问就正常了

druid版本：1.1.10

mysql驱动：5.1.44

报错如下：

Caused by: org.apache.ibatis.exceptions.PersistenceException: 

### Cause: java.lang.NullPointerException

at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30) ~[mybatis-3.4.6.jar!/:3.4.6]

at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:150) ~[mybatis-3.4.6.jar!/:3.4.6]

at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141) ~[mybatis-3.4.6.jar!/:3.4.6]

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_192]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]

at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433) ~[mybatis-spring-1.3.2.jar!/:1.3.2]

at com.sun.proxy.$Proxy425.selectList(Unknown Source) ~[?:?]

at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:230) ~[mybatis-spring-1.3.2.jar!/:1.3.2]

at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:139) ~[mybatis-3.4.6.jar!/:3.4.6]

at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:76) ~[mybatis-3.4.6.jar!/:3.4.6]

at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59) ~[mybatis-3.4.6.jar!/:3.4.6]

at com.sun.proxy.$Proxy455.selectByExample(Unknown Source) ~[?:?]

配置如下：
 datasource:
    druid:
      validationQuery: select 1
      minIdle: 10
      filters: stat
      testOnBorrow: 'false'
      removeAbandoned: 'true'
      initialSize: 5
      driver-class-name: com.mysql.jdbc.Driver
      maxOpenPreparedStatements: 300
      type: com.alibaba.druid.pool.DruidDataSource
      testOnReturn: 'false'
      poolPreparedStatements: 'true'
      testWhileIdle: 'true'

**Comment by lizongbo** [comment]
你的堆栈里看不到跟druid有关的信息

升级到1.2.22来验证
