### ISSUE TITLE
用了这个之后，有一个很严重的问题，搞不懂

### ISSUE THREAD

**Issue by irwinai** [alibaba/druid#594]
现在用了之后，如果系统隔了一段时间不访问，这个时间大概是1-2个小时
第一次访问就会特别的慢，大概需要30-40秒，但是后面就快了
搞不懂原因
环境是SSH+oracle
配置按照给的实例的配置配的
他会抛出异常
java.sql.SQLRecoverableException: IO 错误: Connection reset by peer: socket write error
    at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:504)
    at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:3754)
    at com.alibaba.druid.filter.FilterChainImpl.connection_close(FilterChainImpl.java:169)
    at com.alibaba.druid.filter.stat.StatFilter.connection_close(StatFilter.java:254)
    at com.alibaba.druid.filter.FilterChainImpl.connection_close(FilterChainImpl.java:165)

**Comment by liwenbo** [comment]
我也遇到这个问题，请问你解决没有
