### ISSUE TITLE
空指针异常

### ISSUE THREAD

**Issue by jasonsuzhou** [alibaba/druid#5946]
dbtype: mysql
dbversion: 5.7
duird version: 1.2.20
error sql: delete from table_xxxx where id < 1231313
error info: 
error:org.springframework.jdbc.UncategorizedSQLException: StatementCallback; uncategorized SQLException for SQL [DELETE  FROM `t_job` WHERE `id` < 49710002]; SQL state [null]; error code [0]; Error; nested exception is java.sql.SQLException: Error
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1578)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:398)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:559)
	at com.xxxxxx.impl.ProcessorSqlService.delete(ProcessorSqlService.java:354)
	at com.xxxxxx.processor.impl.DefaultCleanProcessor.process(DefaultCleanProcessor.java:45)
	at comxxxxxx.CleanJobScheduler.process(CleanJobScheduler.java:209)
	at com.xxxxxx.CleanJobScheduler.access$100(CleanJobScheduler.java:40)
	at com.xxxxxx.CleanJobScheduler$ItemTask.run(CleanJobScheduler.java:190)
	at com.xxxxxx.TaskExecutorService$CommonTask.call(TaskExecutorService.java:260)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: Error
	at com.alibaba.druid.pool.DruidDataSource.handleConnectionException(DruidDataSource.java:1910)
	at com.alibaba.druid.pool.DruidPooledConnection.handleException(DruidPooledConnection.java:124)
	at com.alibaba.druid.pool.DruidPooledStatement.checkException(DruidPooledStatement.java:94)
	at com.alibaba.druid.pool.DruidPooledStatement.executeUpdate(DruidPooledStatement.java:332)
	at org.springframework.jdbc.core.JdbcTemplate$1UpdateStatementCallback.doInStatement(JdbcTemplate.java:547)
	at org.springframework.jdbc.core.JdbcTemplate$1UpdateStatementCallback.doInStatement(JdbcTemplate.java:544)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:383)
	... 11 more
Caused by: java.lang.NullPointerException

值得注意的是在这个报错之前还有一个 select 'x' 的空指针异常
{conn-10062, stmt-7974501} execute error. select 'x'
java.lang.NullPointerException: null

当时DB监控显示查询量瞬间减少， 连接释放很多
![image](https://github.com/alibaba/druid/assets/5878409/8778117d-2149-4132-9371-5cf625a9fe72)
![image](https://github.com/alibaba/druid/assets/5878409/0c5cc40c-ac45-4fff-8fbc-2b57c8e2630b)

**Comment by lizongbo** [comment]
首先不要用1.2.20，请使用最新的1.2.23.
其次你的空指针堆栈刚好把下面的堆栈贴出来，没法分析原因。
