### ISSUE TITLE
AbstractQuery.java:228 报错  java.lang.NullPointerException

### ISSUE THREAD

**Issue by jasonsuzhou** [alibaba/druid#5959]
please follow the issue template below for bug reports and feature requests
for example, if you are reporting a bug, please provide the following information:
dbtype: mysql
dbversion: 5.8
duird version: 1.2.23
error sql: select * from test
error info: 
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1578)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:398)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:559)
	at com.xxx.delete(ProcessorSqlService.java:354)
	at com.xxx.DefaultCleanProcessor.process(DefaultCleanProcessor.java:45)
	at com.xxx.process(CleanJobScheduler.java:209)
	at com.xxx.CleanJobScheduler.access$100(CleanJobScheduler.java:40)
	at com.xxx.CleanJobScheduler$ItemTask.run(CleanJobScheduler.java:190)
	at com.xxx.TaskExecutorService$CommonTask.call(TaskExecutorService.java:260)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: Error
	at com.alibaba.druid.pool.DruidDataSource.handleConnectionException(DruidDataSource.java:1933)
	at com.alibaba.druid.pool.DruidPooledConnection.handleException(DruidPooledConnection.java:124)
	at com.alibaba.druid.pool.DruidPooledStatement.checkException(DruidPooledStatement.java:94)
	at com.alibaba.druid.pool.DruidPooledStatement.executeUpdate(DruidPooledStatement.java:332)
	at org.springframework.jdbc.core.JdbcTemplate$1UpdateStatementCallback.doInStatement(JdbcTemplate.java:547)
	at org.springframework.jdbc.core.JdbcTemplate$1UpdateStatementCallback.doInStatement(JdbcTemplate.java:544)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:383)
	... 11 more
Caused by: java.lang.NullPointerException
	at com.mysql.cj.AbstractQuery.stopQueryTimer(AbstractQuery.java:228)
	at com.mysql.cj.jdbc.StatementImpl.stopQueryTimer(StatementImpl.java:643)
	at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1314)
	at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2084)
	at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1245)
	at com.alibaba.druid.filter.FilterChainImpl.statement_executeUpdate(FilterChainImpl.java:2897)
	at com.alibaba.druid.filter.FilterAdapter.statement_executeUpdate(FilterAdapter.java:2518)
	at com.alibaba.druid.filter.FilterEventAdapter.statement_executeUpdate(FilterEventAdapter.java:321)
	at com.alibaba.druid.filter.FilterChainImpl.statement_executeUpdate(FilterChainImpl.java:2895)
	at com.alibaba.druid.filter.FilterAdapter.statement_executeUpdate(FilterAdapter.java:2518)
	at com.alibaba.d

相关配置参数如下：
connectTimeout=4000
socketTimeout=30000
minIdle=12
maxActive=20
queryTimeout=10
maxWait=60000
timeBetweenEvictionRunsMillis=2000

**Comment by lizongbo** [comment]
这个是mysql jdbc里的异常，升级mysql jdbc验证吧
