### ISSUE TITLE
oracle 解析 alter add (CONSTRAINT) 语句失败

### ISSUE THREAD

**Issue by serendipity2223** [alibaba/druid#5969]
alter table POLL_JOB_DETAILS add (

    SCHED_NAME VARCHAR2(120) DEFAULT 'OCS_SCHEDULER' NOT NULL,

    IS_NONCONCURRENT VARCHAR2(1) default 'N' NOT NULL,

    IS_UPDATE_DATA VARCHAR2(1) default 'N'  NOT NULL,

    CONSTRAINT POLL_JOB_DETAILS_PK PRIMARY KEY (SCHED_NAME,JOB_NAME,JOB_GROUP)

);

```
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: illegal name, pos 225, line 9, column 5, token CONSTRAINT
	at com.alibaba.druid.sql.parser.SQLExprParser.name(SQLExprParser.java:2527)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleExprParser.name(OracleExprParser.java:1123)
	at com.alibaba.druid.sql.parser.SQLExprParser.parseColumn(SQLExprParser.java:4802)
	at com.alibaba.druid.sql.parser.SQLExprParser.parseColumn(SQLExprParser.java:4788)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseAlterTableAddColumn(SQLStatementParser.java:4890)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleStatementParser.parseAlterTable(OracleStatementParser.java:1560)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleStatementParser.parserAlter(OracleStatementParser.java:1324)
	at com.alibaba.druid.sql.dialect.oracle.parser.OracleStatementParser.parseStatementList(OracleStatementParser.java:147)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:106)
	at com.cyzhao.druidtest.DuridTest.main(DuridTest.java:683)
```

**Comment by serendipity2223** [comment]
durid版本： 1.2.23
