### ISSUE TITLE
tried to access private field com.alibaba.druid.pool.DruidPooledConnection.disable 

### ISSUE THREAD

**Issue by HuangChen2019** [alibaba/druid#5974]
dbtype: mysql
dbversion: 8.0.21
duird version: 1.2.20
error info: error message
升级duird 1.2.20版本springboot启动报错误：
tried to access private field com.alibaba.druid.pool.DruidPooledConnection.disable 

详细：
2024-06-12 11:33:08.704 ERROR [xxxxxxxx,devcloud-1] com.alibaba.druid.pool.DruidDataSource - recyle error
java.lang.IllegalAccessError: class com.alibaba.druid.pool.DruidPooledPreparedStatement tried to access private field com.alibaba.druid.pool.DruidPooledConnection.disable (com.alibaba.druid.pool.DruidPooledPreparedStatement and com.alibaba.druid.pool.DruidPooledConnection are in unnamed module of loader 'app')
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.close(DruidPooledPreparedStatement.java:158)
	at com.alibaba.druid.util.JdbcUtils.close(JdbcUtils.java:91)
	at com.alibaba.druid.pool.DruidConnectionHolder.reset(DruidConnectionHolder.java:384)
	at com.alibaba.druid.pool.DruidDataSource.recycle(DruidDataSource.java:2055)
	at com.alibaba.druid.pool.DruidPooledConnection.recycle(DruidPooledConnection.java:338)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_recycle(FilterChainImpl.java:5047)
	at com.alibaba.druid.filter.logging.LogFilter.dataSource_releaseConnection(LogFilter.java:899)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_recycle(FilterChainImpl.java:5043)
	at com.alibaba.druid.filter.stat.StatFilter.dataSource_releaseConnection(StatFilter.java:689)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_recycle(FilterChainImpl.java:5043)
	at com.alibaba.druid.pool.DruidPooledConnection.close(DruidPooledConnection.java:273)
	at org.springframework.jdbc.datasource.DataSourceUtils.doCloseConnection(DataSourceUtils.java:406)
	at org.springframework.jdbc.datasource.DataSourceUtils.doReleaseConnection(DataSourceUtils.java:393)
	at org.springframework.jdbc.datasource.DataSourceUtils.releaseConnection(DataSourceUtils.java:360)
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doCleanupAfterCompletion(DataSourceTransactionManager.java:395)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.cleanupAfterCompletion(AbstractPlatformTransactionManager.java:992)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:790)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:711)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:660)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:410)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:756)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:756)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by lizongbo** [comment]
com.alibaba.druid.pool.DruidPooledConnection.disable (com.alibaba.druid.pool.DruidPooledPreparedStatement and com.alibaba.druid.pool.DruidPooledConnection are in unnamed module of loader 'app')

从这个出错信息看是你启用了 jdk9 以上的模块化机制，调整一下jvm启动参数试一下。

**Comment by lizongbo** [comment]
检查一下你的工程里是不是存在同时存在 druid不同版本的jar包，导致class重复，我今天遇到类似的问题，其实就是class重复导致的
