### ISSUE TITLE
只读库状态下持续更新库poolingCount数量增长

### ISSUE THREAD

**Issue by icmdw** [alibaba/druid#6006]
**dbtype:mysql** mysql
**dbversion:** 5.7
**druid verion:** 1.2.16
**jdk verion:** 1.8.0
**error sql:** update / insert
**testcase code:**
**stacktrace info:**
`
java.sql.SQLException: The MySQL server is running with the --read-only option so it cannot execute this statement
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3970)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3906)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2677)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2549)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
        at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1192)
        at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3446)
        at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_execute(FilterEventAdapter.java:434)
        at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3444)
        at com.alibaba.druid.wall.WallFilter.preparedStatement_execute(WallFilter.java:638)
        at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3444)
        at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_execute(FilterEventAdapter.java:434)
        at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3444)
        at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.execute(PreparedStatementProxyImpl.java:152)
        at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:483)
        at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:46)
        at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
        at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
        at org.apache.ibatis.executor.BaseExecutor.update$original$AVH4eVIa(BaseExecutor.java:117)
        at org.apache.ibatis.executor.BaseExecutor.update$original$AVH4eVIa$accessor$ENOm0MkW(BaseExecutor.java)
...
`
**error info:**
---

只读库状态（SET GLOBAL READ_ONLY=1）下，有定时任务持续更新（update / insert）该库，监控发现poolingCount数量持续缓慢增长，直到最大池大小，此时查询类语句可正常执行，且总体语句执行并发不高。如何配置避免上述场景下池连接数不持续增长？

**Comment by lizongbo** [comment]
升级到1.2.23版，参考最新的wiki指引核实配置，
https://github.com/alibaba/druid/wiki/DruidDataSource%E9%85%8D%E7%BD%AE%E5%B1%9E%E6%80%A7%E5%88%97%E8%A1%A8

然后再看下是否复现该现象，
