### ISSUE TITLE
[BUG] 拉取Druid最新代码解析alter table t1 alter index 有误

### ISSUE THREAD

**Issue by GPF199541** [alibaba/druid#6036]
### Database Type

MySQL

### Database Version

MySQL5.7 8.0

### Druid Version

1.2.24

### JDK Version

jdk8

### Error SQL

alter table t1 alter index idx_1 invisible,alter index idx_2 invisible;

### Testcase Code

String sql = "alter table t1 alter index idx_1 invisible,alter index idx_2 invisible";
        SQLStatementParser parser = SQLParserUtils.createSQLStatementParser(sql, DbType.mysql);
        List<SQLStatement> sqlStatements = parser.parseStatementList();

### Error Info

Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: not supported.pos 43, line 1, column 43, token ,
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:654)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:106)
	at com.shein.dasx.setTest.main(setTest.java:24)

**Comment by fudianchn** [comment]
已定位并修复，详见 PR。**根因**：`MySqlStatementParser` VISIBLE/INVISIBLE 分支 `break` 跳出而非返回 true，外层逗号循环未继续解析后续 `ALTER INDEX` 子句。**修复**：改为 `return true`，1 行。
