### ISSUE TITLE
[BUG] connection disabled

### ISSUE THREAD

**Issue by dujiaolianglong** [alibaba/druid#6050]
### Database Type

Postgresql

### Database Version

无

### Druid Version

1.2.4

### JDK Version

JDK8

### Error SQL

无

### Stacktrace Info

Caused by: java.sql.SQLException: connection disabled
at com.alibaba.druid.pool.DruidPooledConnection.checkStateInternal(DruidPooledConnection.java:1170) ~[druid-1.2.4.jar:1.2.4]
at com.alibaba.druid.pool.DruidPooledConnection.checkState(DruidPooledConnection.java:1155) ~[druid-1.2.4.jar:1.2.4]
at com.alibaba.druid.pool.DruidPooledConnection.setAutoCommit(DruidPooledConnection.java:703) ~[druid-1.2.4.jar:1.2.4]
at org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor.begin(AbstractLogicalConnectionImplementor.java:72) ~[hibernate-core-5.6.9.Final.jar:5.6.9.Final]
... 95 more
Caused by: org.postgresql.util.PSQLException: This connection has been closed.
at org.postgresql.jdbc2.AbstractJdbc2Connection.checkClosed(AbstractJdbc2Connection.java:719) ~[gsjdbc4-V100R003C10SPC120B100.jar:?]
at org.postgresql.jdbc2.AbstractJdbc2Connection.rollback(AbstractJdbc2Connection.java:736) ~[gsjdbc4-V100R003C10SPC120B100.jar:?]

### 报错如下
Caused by: java.sql.SQLException: connection disabled
at com.alibaba.druid.pool.DruidPooledConnection.checkStateInternal(DruidPooledConnection.java:1170) ~[druid-1.2.4.jar:1.2.4]
at com.alibaba.druid.pool.DruidPooledConnection.checkState(DruidPooledConnection.java:1155) ~[druid-1.2.4.jar:1.2.4]
at com.alibaba.druid.pool.DruidPooledConnection.setAutoCommit(DruidPooledConnection.java:703) ~[druid-1.2.4.jar:1.2.4]
at org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor.begin(AbstractLogicalConnectionImplementor.java:72) ~[hibernate-core-5.6.9.Final.jar:5.6.9.Final]
... 95 more
Caused by: org.postgresql.util.PSQLException: This connection has been closed.
at org.postgresql.jdbc2.AbstractJdbc2Connection.checkClosed(AbstractJdbc2Connection.java:719) ~[gsjdbc4-V100R003C10SPC120B100.jar:?]
at org.postgresql.jdbc2.AbstractJdbc2Connection.rollback(AbstractJdbc2Connection.java:736) ~[gsjdbc4-V100R003C10SPC120B100.jar:?]

### 连接池配置如下
# 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
druid.initialSize=10
# 最大连接池数量
druid.maxActive=1000
# 最小连接池数量
druid.minIdle=50
# 获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
#druid.maxWait=60000

# 用来检测连接是否有效的sql，要求是一个查询语句，常用select 'x'。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用。
druid.validationQuery=select 1
# 建议配置为true，不影响性能，空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
druid.testWhileIdle=true
druid.timeBetweenEvictionRunsMillis=10000

# 连接保持空闲而不被销毁的最小时间
druid.minEvictableIdleTimeMillis=300000

# 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
druid.testOnBorrow=false
# 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
druid.testOnReturn=false

### 自定定位情况
看了获取连接的代码
连接已经获取到了，然后再hibernate开启事务时校验连接时报错”connection disabled“
从代码可以看出，先判断了 连接的状态，来凝结未关闭，但是开启事务时，发现druid维持的连接状态为disabled状态

### 疑问
这个问题在后续某个版本修复了吗？是在哪个版本修复的？ 
又或者 我的druid配置不当？

**Comment by taodamiao** [comment]
请问解决了吗？我也遇到了。

**Comment by linghengqian** [comment]
- I have opened #6143 .
- By setting `closeConnOnFatalError` to `false`, Druid's behavior will align with HikariCP, that is, the connection will no longer be closed when a fatal error defined by Druid occurs. This solves a series of controversies surrounding Hibernate, Flyway, and ShardingSphere. This is a huge regret introduced from https://github.com/alibaba/druid/commit/882470b1ce7a51a94f3525beceec91384ccd425f 7 years ago.
