### ISSUE TITLE
[BUG] pg12多种sql语法解析失败

### ISSUE THREAD

**Issue by tmaerd** [alibaba/druid#6064]
### Database Type

pg

### Database Version

12

### Druid Version

1.2.23

### JDK Version

jdk8

### Error SQL

1.语法解析报错
ALTER TABLE table_test ALTER COLUMN num TYPE int8 USING num::int8
2.不支持字段名为version
ALTER TABLE table_test ADD "version" int8 DEFAULT 1 NOT NULL;

### Testcase Code

String sql = "ALTER TABLE table_test ALTER COLUMN num TYPE int8 USING num::int8";
List<SQLStatement> list = SQLUtils.parseStatements(sql, DbType.postgresql);

### Stacktrace Info

1.ALTER TABLE table_test ALTER COLUMN num TYPE int8 USING num::int8

com.alibaba.druid.sql.parser.ParserException: not supported.pos 82, line 1, column 78, token USING

	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:654)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:600)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:621)

2.ALTER TABLE table_test ADD "version" int8 DEFAULT 1 NOT NULL;
com.alibaba.druid.sql.parser.ParserException: TODO pos 52, line 1, column 44, token LITERAL_ALIAS "version"

	at com.alibaba.druid.sql.parser.SQLStatementParser.alterTableAdd(SQLStatementParser.java:2625)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseAlter(SQLStatementParser.java:1955)
	at com.alibaba.druid.sql.dialect.postgresql.parser.PGSQLStatementParser.parseAlter(PGSQLStatementParser.java:524)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:339)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:600)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:621)

**Comment by liuwenjie** [comment]
版本1.2.23/1.2.22/1.2.21，都出现在这个问题，ERROR：com.alibaba.druid.sql.parser.ParserException: not supported.pos 63, line 1, column 40, token IDENTIFER
