### ISSUE TITLE
[BUG] 解析hive时如果  PARTITIONED BY  和 LOCATION 关键字之间有COMMENT解析失败

### ISSUE THREAD

**Issue by yeyeyuanyu** [alibaba/druid#6071]
### Database Type

hivi

### Database Version

无

### Druid Version

1.2.23

### JDK Version

jdk8

### Error SQL

CREATE TABLE IF NOT EXISTS test.dwr_whs_invt_dtl(
bat_no  string COMMENT '批号',
.................................................
)
USING hudi
PARTITIONED BY (acct_prd string comment '会计期') 
COMMENT '明细表'
LOCATION 'obs://xxxxxxxxxxxxxxxxxx'
TBLPROPERTIES (
  type = 'mor', 
  primaryKey = 'acct_prd' ,
  preCombineField = 'acct_prd'
);

**Comment by yeyeyuanyu** [comment]
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: not supported.pos 973, line 27, column 82, token IDENTIFIER LOCATION
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:654)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:600)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:621)

**Comment by yeyeyuanyu** [comment]
CREATE TABLE IF NOT EXISTS
	dwi.dwi_wms_addr (
		.............................................
		dwi_last_ins_time STRING COMMENT 'DWI数据插入时间',
		dwi_last_upd_time STRING COMMENT 'DWI数据更新时间'
	) USING hudi COMMENT '货位表' LOCATION 'obs://xxxxxxxxxxxxxxxxxxxxxxx' ---HUDI表存储路径
	OPTIONS (
		xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
	);
还有可能无法解析options
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: not supported.pos 2578, line 70, column 2, token IDENTIFIER OPTIONS
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:654)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:600)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:621)

**Comment by yeyeyuanyu** [comment]
PARTITIONED BY 在 LOCATION 后面也会失败

**Comment by fudianchn** [comment]
Root cause and fix in the PR linked above: `HiveCreateTableParser.parseCreateTableRest` is a linear chain of single-shot `if` guards, and COMMENT was only recognised before PARTITIONED BY and after LOCATION/TBLPROPERTIES — so a COMMENT between PARTITIONED BY and LOCATION was mis-consumed and the LOCATION token was left unhandled. Added a COMMENT recognition just before the LOCATION branch. Full core regression green.
