### ISSUE TITLE
[BUG]java.lang.ClassCastException: com.alibaba.druid.sql.visitor.SQLEvalVisitorImpl cannot be cast to com.alibaba.druid.sql.dialect.postgresql.visitor.PGASTVisitor

### ISSUE THREAD

**Issue by nemoEception** [alibaba/druid#6158]
### Database Type

PostgreSQL

### Database Version

PostgreSQL 15.2

### Druid Version

1.2.20

### JDK Version

JDK 1.8

### Error SQL

select t1."dfef" as "dfef",
       t2."dfefs" as "dfefs"
from (
  select 'aaa' as "dfef" 
  from test
where to_char(now() + INTERVAL '8 HOUR','yyyy-mm-dd')= '2024-10-10'
) t1
left join (
select 'aaa' as "dfefs" 
  from test
where to_char(now() + INTERVAL '8 HOUR','yyyy-mm-dd')>= (  
CASE  
    WHEN EXTRACT(DAY FROM CAST('2024-09-23' AS DATE)) >= 29 THEN  
        to_char(CAST('2024-09-23' AS DATE), 'yyyy-mm') || '-29'  
    WHEN EXTRACT(DAY FROM CAST('2024-09-23' AS DATE)) < 29 THEN  
        to_char(CAST('2024-09-23' AS DATE) - INTERVAL '1 month', 'yyyy-mm') || '-29'  
END )
and  to_char(now() + INTERVAL '8 HOUR','yyyy-mm-dd')<= '2024-10-10'
) t2
on t1."dfef" = t2."dfefs" 

### Stacktrace Info

java.lang.ClassCastException: com.alibaba.druid.sql.visitor.SQLEvalVisitorImpl cannot be cast to com.alibaba.druid.sql.dialect.postgresql.visitor.PGASTVisitor
	at com.alibaba.druid.sql.dialect.postgresql.ast.expr.PGExprImpl.accept0(PGExprImpl.java:29)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:48)
	at com.alibaba.druid.sql.visitor.SQLEvalVisitorUtils.visit(SQLEvalVisitorUtils.java:809)
	at com.alibaba.druid.sql.visitor.SQLEvalVisitorImpl.visit(SQLEvalVisitorImpl.java:68)
	at com.alibaba.druid.sql.ast.expr.SQLBinaryOpExpr.accept0(SQLBinaryOpExpr.java:162)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:48)
	at com.alibaba.druid.sql.visitor.SQLEvalVisitorUtils.visit(SQLEvalVisitorUtils.java:656)
	at com.alibaba.druid.sql.visitor.SQLEvalVisitorImpl.visit(SQLEvalVisitorImpl.java:85)
	at com.alibaba.druid.sql.ast.expr.SQLCaseExpr.accept0(SQLCaseExpr.java:74)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:48)
	at com.alibaba.druid.sql.visitor.SQLEvalVisitorUtils.visit(SQLEvalVisitorUtils.java:810)
	at com.alibaba.druid.sql.visitor.SQLEvalVisitorImpl.visit(SQLEvalVisitorImpl.java:68)
	at com.alibaba.druid.sql.ast.expr.SQLBinaryOpExpr.accept0(SQLBinaryOpExpr.java:162)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:48)
	at com.alibaba.druid.wall.spi.WallVisitorUtils.eval(WallVisitorUtils.java:1596)
	at com.alibaba.druid.wall.spi.WallVisitorUtils.getValue(WallVisitorUtils.java:1075)
	at com.alibaba.druid.wall.spi.WallVisitorUtils.getValue(WallVisitorUtils.java:1488)
	at com.alibaba.druid.wall.spi.WallVisitorUtils.getValue_and(WallVisitorUtils.java:1110)
	at com.alibaba.druid.wall.spi.WallVisitorUtils.getValue(WallVisitorUtils.java:997)
	at com.alibaba.druid.wall.spi.WallVisitorUtils.getValue(WallVisitorUtils.java:1488)
	at com.alibaba.druid.wall.spi.WallVisitorUtils.getConditionValue(WallVisitorUtils.java:1425)
	at com.alibaba.druid.wall.spi.WallVisitorUtils.checkSelelct(WallVisitorUtils.java:221)
	at com.alibaba.druid.wall.WallVisitor.visit(WallVisitor.java:80)
	at com.alibaba.druid.sql.dialect.postgresql.visitor.PGASTVisitor.visit(PGASTVisitor.java:31)
	at com.alibaba.druid.sql.dialect.postgresql.ast.stmt.PGSelectQueryBlock.accept0(PGSelectQueryBlock.java:63)
	at com.alibaba.druid.sql.dialect.postgresql.ast.stmt.PGSelectQueryBlock.accept0(PGSelectQueryBlock.java:55)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:48)
	at com.alibaba.druid.sql.ast.statement.SQLSelect.accept0(SQLSelect.java:116)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:48)
	at com.alibaba.druid.sql.ast.statement.SQLSubqueryTableSource.accept0(SQLSubqueryTableSource.java:67)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:48)
	at com.alibaba.druid.sql.ast.statement.SQLJoinTableSource.accept0(SQLJoinTableSource.java:65)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:48)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.acceptChild(SQLObjectImpl.java:70)
	at com.alibaba.druid.sql.dialect.postgresql.ast.stmt.PGSelectQueryBlock.accept0(PGSelectQueryBlock.java:67)
	at com.alibaba.druid.sql.dialect.postgresql.ast.stmt.PGSelectQueryBlock.accept0(PGSelectQueryBlock.java:55)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:48)
	at com.alibaba.druid.sql.ast.statement.SQLSelect.accept0(SQLSelect.java:116)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:48)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.acceptChild(SQLObjectImpl.java:70)
	at com.alibaba.druid.sql.dialect.postgresql.ast.stmt.PGSelectStatement.accept0(PGSelectStatement.java:43)
	at com.alibaba.druid.sql.dialect.postgresql.ast.stmt.PGSelectStatement.accept0(PGSelectStatement.java:35)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:48)
	at com.alibaba.druid.wall.WallProvider.checkInternal(WallProvider.java:657)
	at com.alibaba.druid.wall.WallProvider.check(WallProvider.java:572)
	at com.alibaba.druid.wall.WallFilter.checkInternal(WallFilter.java:806)

### Error Info

com.alibaba.druid.sql.visitor.SQLEvalVisitorImpl cannot be cast to com.alibaba.druid.sql.dialect.postgresql.visitor.PGASTVisitor

**Comment by nemoEception** [comment]
这里把两个子查询单独拿出来执行是可以的，但是放到一起就不行了
