### ISSUE TITLE
[BUG] holo DROP FOREIGN TABLE

### ISSUE THREAD

**Issue by alanlvle** [alibaba/druid#6180]
### Database Type

hologres

### Database Version

Hologres V1.3

### Druid Version

1.2.23

### JDK Version

Open JDK 8

### Error SQL

DROP FOREIGN TABLE odps_user_test;

### Stacktrace Info

com.alibaba.druid.sql.parser.ParserException: TODO pos 12, line 1, column 6, token FOREIGN
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseDrop(SQLStatementParser.java:920) ~[druid-1.2.24.1.jar:na]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:427) ~[druid-1.2.24.1.jar:na]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:108) ~[druid-1.2.24.1.jar:na]

### Error Info

TODO pos 12, line 1, column 6, token FOREIGN

**Comment by alanlvle** [comment]
Hao can I fix it?

**Comment by fudianchn** [comment]
Root cause: `SQLStatementParser.parseDrop()` has no `case FOREIGN`, so `DROP FOREIGN TABLE x` falls through to the default branch and raises `unsupported DROP target 'FOREIGN'`.

Fix in #6697: added a dedicated `foreign` flag to `SQLDropTableStatement` (mirrors the existing `external` flag), routed the FOREIGN token to `parseDropTable`, and rendered `FOREIGN` in the output visitor so the round-trip stays lossless (`DROP FOREIGN TABLE x` → `DROP FOREIGN TABLE x`) instead of rewriting it to the PostgreSQL-invalid `EXTERNAL TABLE`.

4 new tests; full core regression green (4376 tests, 0 failures).
