### ISSUE TITLE
[BUG] Druid 连接池ActiveCount大于了poolingCount

### ISSUE THREAD

**Issue by lawmansoft** [alibaba/druid#6193]
### Database Type

MySQL

### Database Version

MySQL5.7

### Druid Version

1.2.6

### JDK Version

OpenJDK 8

### Error SQL

****

**Comment by lawmansoft** [comment]
线上系统发生了大量的线程卡顿，通过 MAT 分析内存，查看连接池
maxActive=200   activeCount=40  poolingCount=15
<img width="308" alt="image" src="https://github.com/user-attachments/assets/58a9e600-e43b-41bb-b794-38f473abc761">
<img width="303" alt="image" src="https://github.com/user-attachments/assets/67861e30-01db-4e9b-9f0b-e827f9def244">

大量线程卡在等待连接池的lock.lock()
"http-nio-8089-exec-2380" #4614 daemon prio=5 os_prio=0 tid=0x00007fb0e04cc800 nid=0x789e waiting on condition [0x00007fb07b8f4000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000702050fd0> (a java.util.concurrent.locks.ReentrantLock$FairSync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
	at java.util.concurrent.locks.ReentrantLock$FairSync.lock(ReentrantLock.java:224)
	at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:285)
	at com.alibaba.druid.pool.DruidDataSource.getConnectCount(DruidDataSource.java:2325)
