### ISSUE TITLE
[BUG] com.google.common.collect.Lists 找不到

### ISSUE THREAD

**Issue by xiaomujin** [alibaba/druid#6263]
### Database Type

MySQL

### Database Version

MySQL 8

### Druid Version

1.2.24

### JDK Version

Open JDK 21

### Error SQL

select 

### Testcase Code

com.google.common.collect.Lists 找不到这个类

### Stacktrace Info

```java
wordCloudService.lambdaQuery()
                .select(WordCloud::getContent)
                .eq(userId != null, WordCloud::getSenderId, userId)
                .eq(WordCloud::getGroupId, groupId)
                .between(WordCloud::getTime, start, end)
                .list()
                .stream()
                .map(WordCloud::getContent)
                .toList();
```

**Comment by ddxl123** [comment]
一样

**Comment by luckytao** [comment]
升级到1.24同样的问题， 最后降为1.23了

Caused by: java.lang.NoClassDefFoundError: com/google/common/collect/Lists
	at com.alibaba.druid.sql.parser.SQLSelectParser.getReturningFunctions(SQLSelectParser.java:1411) ~[druid-1.2.24.jar:?]
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseGeneratedTableSource(SQLSelectParser.java:1382) ~[druid-1.2.24.jar:?]
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseTableSource(SQLSelectParser.java:1292) ~[druid-1.2.24.jar:?]
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseFrom(SQLSelectParser.java:1166) ~[druid-1.2.24.jar:?]
	at com.alibaba.druid.sql.parser.SQLSelectParser.query(SQLSelectParser.java:493) ~[druid-1.2.24.jar:?]
	at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:77) ~[druid-1.2.24.jar:?]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseSelect(SQLStatementParser.java:4740) ~[druid-1.2.24.jar:?]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:232) ~[druid-1.2.24.jar:?]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:108) ~[druid-1.2.24.jar:?]
	at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:167) ~[druid-1.2.24.jar:?]
