### ISSUE TITLE
[BUG] cannot parse presto sql with try_cast() function

### ISSUE THREAD

**Issue by ZhuangTang3** [alibaba/druid#6280]
### Database Type

Presto

### Database Version

Presto 0.283

### Druid Version

1.1.17

### JDK Version

OpenJDK17

### Error SQL

```sql
select try_cast(dt_day as int) 
from ads_test.employee_task_info_1d_f 
where dt_day = '$[yyyyMMdd-1]'
```

### Testcase Code

```java
String dbType = JdbcConstants.PRESTO;
List<SQLStatement> stmtList = com.alibaba.druid.sql.SQLUtils.parseStatements(querySQL, dbType);
SQLStatement stmt = stmtList.get(0);
```

### Stacktrace Info

syntax error, expect RPAREN, actual AS pos 25, line 1, column 23, token AS
com.alibaba.druid.sql.parser.ParserException: syntax error, expect RPAREN, actual AS pos 25, line 1, column 23, token AS
	at com.alibaba.druid.sql.parser.SQLExprParser.accept(SQLExprParser.java:2742)
	at com.alibaba.druid.sql.parser.SQLExprParser.methodRest(SQLExprParser.java:1192)
	at com.alibaba.druid.sql.parser.SQLExprParser.parseSelectItem(SQLExprParser.java:3339)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseSelectList(SQLSelectParser.java:675)
	at com.alibaba.druid.sql.parser.SQLSelectParser.query(SQLSelectParser.java:294)
	at com.alibaba.druid.sql.parser.SQLSelectParser.query(SQLSelectParser.java:236)
	at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:88)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseSelect(SQLStatementParser.java:2562)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:248)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:171)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:495)

**Comment by lingo-xp** [comment]
升级版本
