### ISSUE TITLE
使用最新版本1.0.9,打算使用log4jdbc打印sql语句,出现dbType not support问题

### ISSUE THREAD

**Issue by jptiancai** [alibaba/druid#684]
**pom.xml添加**

``` xml
        <!-- slf4j -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.7</version>
        </dependency>
        <!-- logback -->
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.1.2</version>
        </dependency>
        <!-- log4jdbc -->
        <dependency>
            <groupId>com.googlecode.log4jdbc</groupId>
            <artifactId>log4jdbc</artifactId>
            <version>1.2</version>
            <scope>runtime</scope>
        </dependency>
```

**配置文件的url为**

```
connection.url=jdbc:log4jdbc:mysql://localhost:3306/xxx
connection.username=root
connection.password=1234
```

其他的配置是参考[配置_DruidDataSource参考配置](https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_DruidDataSource%E5%8F%82%E8%80%83%E9%85%8D%E7%BD%AE)

**控制台输出信息**

``` java
Caused by: java.lang.IllegalStateException: dbType not support : log4jdbc, url jdbc:log4jdbc:mysql://localhost:3306/xxx
    at com.alibaba.druid.wall.WallFilter.init(WallFilter.java:156)
    at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:536)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1681)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1620)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1549)
```

**Comment by genericyzh** [comment]
@jptiancai 看不太懂呢，要如何配置呢？我也遇到同样的问题

**Comment by genericyzh** [comment]
阔以了，自己的配置写错了 0.0
