### ISSUE TITLE
 register mbean error 这个问题是由什么导致的？如何解决？

### ISSUE THREAD

**Issue by Rekoe** [alibaba/druid#747]
```
2014-12-11 16:35:33,509 [ERROR][com.alibaba.druid.stat.DruidDataSourceStatManager] - register mbean error
java.lang.NullPointerException
    at java.util.Hashtable.put(Hashtable.java:437)
    at com.caucho.jmx.MBeanContext.addMBean(MBeanContext.java:399)
    at com.caucho.jmx.MBeanContext.registerMBean(MBeanContext.java:261)
    at com.caucho.jmx.AbstractMBeanServer.registerMBean(AbstractMBeanServer.java:422)
    at com.alibaba.druid.stat.DruidDataSourceStatManager.addDataSource(DruidDataSourceStatManager.java:163)
    at com.alibaba.druid.pool.DruidDataSource$1.run(DruidDataSource.java:1393)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.alibaba.druid.pool.DruidDataSource.registerMbean(DruidDataSource.java:1389)
    at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:652)
    at com.myapp.db.conn.ConnectionFactory.getDataSource(ConnectionFactory.java:57)
    at com.myapp.db.conn.ConnectionFactory.<init>(ConnectionFactory.java:41)
    at com.myapp.db.conn.ConnectionFactory.getInstance(ConnectionFactory.java:27)
```

code

```
DruidDataSource dataSource = new DruidDataSource();
        dataSource.setFilters("config");
        dataSource.addConnectionProperty(ConfigFilter.CONFIG_FILE, file);
        dataSource.init();
        dataSource.getDriverClassName();
        dataSource.setDbType("mysql");
```

**Comment by orzjy** [comment]
@wenshao 
DruidDataSource implements MBeanRegistration

ObjectName preRegister(MBeanServer server, ObjectName name)
@return The name under which the MBean is to be registered. This value must not be null

**Comment by vk14311** [comment]
public ObjectName preRegister(MBeanServer server, ObjectName name) throws Exception {
        return null;
    }

这个return null 导致npe问题。
