### ISSUE TITLE
在开启日志的情况下，如果url错误会抛出NPE异常

### ISSUE THREAD

**Issue by pathfinder-name** [alibaba/druid#772]
异常信息如下：
.....
Caused by: java.lang.NullPointerException: null
 at com.alibaba.druid.filter.logging.LogFilter.connection_connectAfter(LogFilter.java:349)
 at com.alibaba.druid.filter.FilterEventAdapter.connection_connect(FilterEventAdapter.java:40)
 at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:142)
 at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:211)
 at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:142)
 at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1377)
 at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
 at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:618)

**Comment by pathfinder-name** [comment]
比如这种错误的url：

jdbc:sqlserver:thin:@192.168.1.66:1433:databaseName=webdb

**Comment by jacking124** [comment]
"jdbc:sqlserver://localhost:1433;DatabaseName=KIS_Sample“供参考!
