### ISSUE TITLE
unknown character set index for field

### ISSUE THREAD

**Issue by louishust** [alibaba/druid#803]
Hi all,

We are using druid, but sometimes (not always) we got the below error

```
Caused by: java.sql.SQLException: Unknown character set index for field '25459' received from server.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1074) ~[mysql-connector-java-5.1.21.jar:na]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:988) ~[mysql-connector-java-5.1.21.jar:na]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:974) ~[mysql-connector-java-5.1.21.jar:na]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919) ~[mysql-connector-java-5.1.21.jar:na]
	at com.mysql.jdbc.ConnectionImpl.getCharsetNameForIndex(ConnectionImpl.java:2976) ~[mysql-connector-java-5.1.21.jar:na]
	at com.mysql.jdbc.Field.<init>(Field.java:200) ~[mysql-connector-java-5.1.21.jar:na]
	at com.mysql.jdbc.MysqlIO.unpackField(MysqlIO.java:758) ~[mysql-connector-java-5.1.21.jar:na]
	at com.mysql.jdbc.MysqlIO.getResultSet(MysqlIO.java:423) ~[mysql-connector-java-5.1.21.jar:na]
	at com.mysql.jdbc.MysqlIO.readResultsForQueryOrUpdate(MysqlIO.java:3096) ~[mysql-connector-java-5.1.21.jar:na]
	at com.mysql.jdbc.MysqlIO.readAllResults(MysqlIO.java:2266) ~[mysql-connector-java-5.1.21.jar:na]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2687) ~[mysql-connector-java-5.1.21.jar:na]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2719) ~[mysql-connector-java-5.1.21.jar:na]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155) ~[mysql-connector-java-5.1.21.jar:na]
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1379) ~[mysql-connector-java-5.1.21.jar:na]
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:2925) ~[druid-0.2.6.jar:0.2.6]
	at com.alibaba.druid.filter.FilterAdapter.preparedStatement_execute(FilterAdapter.java:1041) ~[druid-0.2.6.jar:0.2.6]
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_execute(FilterEventAdapter.java:440) ~[druid-0.2.6.jar:0.2.6]
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:2923) ~[druid-0.2.6.jar:0.2.6]
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.execute(PreparedStatementProxyImpl.java:90) ~[druid-0.2.6.jar:0.2.6]
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:448) ~[druid-0.2.6.jar:0.2.6]
```

The error means read the field package error, and the field package is the metadate of the field. So i think it is not caused by JDBC. **I wonder if druid inject some redundant sql or anyone encounter the same problem**?

JDBC VERSION : 5.1.21
DRUID VERSION: 0.2.6

**Comment by wenshao** [comment]
http://bugs.mysql.com/bug.php?id=23645
