### ISSUE TITLE
1.0.13 版本 sqlite java.sql.SQLException: ResultSet closed

### ISSUE THREAD

**Issue by xiyoufang** [alibaba/druid#806]
```
    <dependency>
        <groupId>com.alibaba</groupId>
        <artifactId>druid</artifactId>
        <version>1.0.13</version>
    </dependency>
    <dependency>
        <groupId>org.xerial</groupId>
        <artifactId>sqlite-jdbc</artifactId>
        <version>3.8.7</version>
    </dependency>
```

ERROR DruidPooledPreparedStatement.<init>(100) | getFetchDirection error
java.sql.SQLException: ResultSet closed
    at org.sqlite.core.CoreResultSet.checkOpen(CoreResultSet.java:66)
    at org.sqlite.jdbc3.JDBC3ResultSet.getFetchDirection(JDBC3ResultSet.java:126)
    at org.sqlite.jdbc3.JDBC3Statement.getFetchDirection(JDBC3Statement.java:324)
    at com.alibaba.druid.filter.FilterChainImpl.statement_getFetchDirection(FilterChainImpl.java:2537)
    at com.alibaba.druid.filter.FilterAdapter.statement_getFetchDirection(FilterAdapter.java:2514)
    at com.alibaba.druid.filter.FilterChainImpl.statement_getFetchDirection(FilterChainImpl.java:2535)
    at com.alibaba.druid.proxy.jdbc.StatementProxyImpl.getFetchDirection(StatementProxyImpl.java:283)
    at com.alibaba.druid.pool.DruidPooledPreparedStatement.<init>(DruidPooledPreparedStatement.java:98)
    at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:327)
    at org.hibernate.jdbc.AbstractBatcher.getPreparedStatement(AbstractBatcher.java:534)
    at org.hibernate.jdbc.AbstractBatcher.getPreparedStatement(AbstractBatcher.java:452)
    at org.hibernate.jdbc.AbstractBatcher.prepareQueryStatement(AbstractBatcher.java:161)
    at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1700)
    at org.hibernate.loader.Loader.doQuery(Loader.java:801)
    at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:274)
    at org.hibernate.loader.Loader.loadEntity(Loader.java:2037)
    at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:86)
    at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:76)
    at org.hibernate.persister.entity.AbstractEntityPersister.load(AbstractEntityPersister.java:3294)
    at org.hibernate.event.def.DefaultLoadEventListener.loadFromDatasource(DefaultLoadEventListener.java:496)
    at org.hibernate.event.def.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:477)
    at org.hibernate.event.def.DefaultLoadEventListener.load(DefaultLoadEventListener.java:227)
    at org.hibernate.event.def.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:285)
    at org.hibernate.event.def.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:152)
    at org.hibernate.impl.SessionImpl.fireLoad(SessionImpl.java:1090)
    at org.hibernate.impl.SessionImpl.get(SessionImpl.java:1005)
    at org.hibernate.impl.SessionImpl.get(SessionImpl.java:998)
    at org.springframework.orm.hibernate3.HibernateTemplate$1.doInHibernate(HibernateTemplate.java:520)
    at org.springframework.orm.hibernate3.HibernateTemplate.doExecute(HibernateTemplate.java:407)
    at org.springframework.orm.hibernate3.HibernateTemplate.executeWithNativeSession(HibernateTemplate.java:375)
    at org.springframework.orm.hibernate3.HibernateTemplate.get(HibernateTemplate.java:513)
    at org.springframework.orm.hibernate3.HibernateTemplate.get(HibernateTemplate.java:507)

**Comment by kervin521** [comment]
这个问题在1.2.8版本解决了吗？

**Comment by dooonabe** [comment]
sqlite-jdbc getFetchDirection方法的缺陷
之前版本：
`
    public int getFetchDirection() throws SQLException {
        return ((ResultSet)rs).getFetchDirection();
    }
`
现在版本:
`
    public int getFetchDirection() throws SQLException {
        return 1000;
    }
`
