### ISSUE TITLE
1.0.13版本启动报错

### ISSUE THREAD

**Issue by Rekoe** [alibaba/druid#808]
```
com.alibaba.druid.stat.DruidDataSourceStatManager] - register mbean error
java.lang.NullPointerException
    at java.util.Hashtable.put(Hashtable.java:437)
    at com.caucho.jmx.MBeanContext.addMBean(MBeanContext.java:399)
    at com.caucho.jmx.MBeanContext.registerMBean(MBeanContext.java:261)
    at com.caucho.jmx.AbstractMBeanServer.registerMBean(AbstractMBeanServer.java:422)
    at com.alibaba.druid.stat.DruidDataSourceStatManager.addDataSource(DruidDataSourceStatManager.java:163)
    at com.alibaba.druid.pool.DruidDataSource$1.run(DruidDataSource.java:1395)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.alibaba.druid.pool.DruidDataSource.registerMbean(DruidDataSource.java:1391)
    at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:654)
    at com.myapp.db.conn.ConnectionFactory.getDataSource(ConnectionFactory.java:67)
    at com.myapp.db.conn.ConnectionFactory.<init>(ConnectionFactory.java:40)
    at com.myapp.db.conn.ConnectionFactory.getInstance(ConnectionFactory.java:26)
    at com.myapp.init.InitServlet.init(InitServlet.java:48)
    at com.caucho.server.dispatch.ServletConfigImpl.createServletImpl(ServletConfigImpl.java:1394)
    at com.caucho.server.dispatch.ServletConfigImpl.createServlet(ServletConfigImpl.java:1229)
    at com.caucho.server.dispatch.ServletManager.init(ServletManager.java:232)
    at com.caucho.server.webapp.WebApp.startImpl(WebApp.java:3688)
    at com.caucho.server.webapp.WebApp$StartupTask.run(WebApp.java:5196)
    at com.caucho.env.thread2.ResinThread2.runTasks(ResinThread2.java:173)
    at com.caucho.env.thread2.ResinThread2.run(ResinThread2.java:118)
2015-03-31 06:57:28,062 [DEBUG][org.nutz.castor.Castors] - Using 91 castor for Castors
2015-03-31 06:57:28,116 [ERROR][com.alibaba.druid.stat.DruidDataSourceStatManager] - register mbean error
java.lang.NullPointerException
    at java.util.Hashtable.put(Hashtable.java:437)
    at com.caucho.jmx.MBeanContext.addMBean(MBeanContext.java:399)
    at com.caucho.jmx.MBeanContext.registerMBean(MBeanContext.java:261)
    at com.caucho.jmx.AbstractMBeanServer.registerMBean(AbstractMBeanServer.java:422)
    at com.alibaba.druid.stat.DruidDataSourceStatManager.addDataSource(DruidDataSourceStatManager.java:163)
    at com.alibaba.druid.pool.DruidDataSource$1.run(DruidDataSource.java:1395)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.alibaba.druid.pool.DruidDataSource.registerMbean(DruidDataSource.java:1391)
    at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:654)
    at com.myapp.db.conn.ConnectionFactory.getDataSource(ConnectionFactory.java:67)
    at com.myapp.db.conn.ConnectionFactory.<init>(ConnectionFactory.java:40)
    at com.myapp.db.conn.ConnectionFactory.getInstance(ConnectionFactory.java:26)
    at com.myapp.init.InitServlet.init(InitServlet.java:48)
    at com.caucho.server.dispatch.ServletConfigImpl.createServletImpl(ServletConfigImpl.java:1394)
    at com.caucho.server.dispatch.ServletConfigImpl.createServlet(ServletConfigImpl.java:1229)
    at com.caucho.server.dispatch.ServletManager.init(ServletManager.java:232)
    at com.caucho.server.webapp.WebApp.startImpl(WebApp.java:3688)
    at com.caucho.server.webapp.WebApp$StartupTask.run(WebApp.java:5196)
    at com.caucho.env.thread2.ResinThread2.runTasks(ResinThread2.java:173)
    at com.caucho.env.thread2.ResinThread2.run(ResinThread2.java:118)
2015-03-31 06:57:28,129 [ERROR][com.alibaba.druid.stat.DruidDataSourceStatManager] - register mbean error
java.lang.NullPointerException
    at java.util.Hashtable.put(Hashtable.java:437)
    at com.caucho.jmx.MBeanContext.addMBean(MBeanContext.java:399)
    at com.caucho.jmx.MBeanContext.registerMBean(MBeanContext.java:261)
    at com.caucho.jmx.AbstractMBeanServer.registerMBean(AbstractMBeanServer.java:422)
    at com.alibaba.druid.stat.DruidDataSourceStatManager.addDataSource(DruidDataSourceStatManager.java:163)
    at com.alibaba.druid.pool.DruidDataSource$1.run(DruidDataSource.java:1395)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.alibaba.druid.pool.DruidDataSource.registerMbean(DruidDataSource.java:1391)
    at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:654)
    at com.myapp.db.conn.ConnectionFactory.getDataSource(ConnectionFactory.java:67)
    at com.myapp.db.conn.ConnectionFactory.<init>(ConnectionFactory.java:40)
    at com.myapp.db.conn.ConnectionFactory.getInstance(ConnectionFactory.java:26)
    at com.myapp.init.InitServlet.init(InitServlet.java:48)
    at com.caucho.server.dispatch.ServletConfigImpl.createServletImpl(ServletConfigImpl.java:1394)
    at com.caucho.server.dispatch.ServletConfigImpl.createServlet(ServletConfigImpl.java:1229)
    at com.caucho.server.dispatch.ServletManager.init(ServletManager.java:232)
    at com.caucho.server.webapp.WebApp.startImpl(WebApp.java:3688)
    at com.caucho.server.webapp.WebApp$StartupTask.run(WebApp.java:5196)
    at com.caucho.env.thread2.ResinThread2.runTasks(ResinThread2.java:173)
    at com.caucho.env.thread2.ResinThread2.run(ResinThread2.java:118)
2015-03-31 06:57:28,145 [ERROR][com.alibaba.druid.stat.DruidDataSourceStatManager] - register mbean error
java.lang.NullPointerException
    at java.util.Hashtable.put(Hashtable.java:437)
    at com.caucho.jmx.MBeanContext.addMBean(MBeanContext.java:399)
    at com.caucho.jmx.MBeanContext.registerMBean(MBeanContext.java:261)
    at com.caucho.jmx.AbstractMBeanServer.registerMBean(AbstractMBeanServer.java:422)
    at com.alibaba.druid.stat.DruidDataSourceStatManager.addDataSource(DruidDataSourceStatManager.java:163)
    at com.alibaba.druid.pool.DruidDataSource$1.run(DruidDataSource.java:1395)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.alibaba.druid.pool.DruidDataSource.registerMbean(DruidDataSource.java:1391)
    at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:654)
    at com.myapp.db.conn.ConnectionFactory.getDataSource(ConnectionFactory.java:67)
    at com.myapp.db.conn.ConnectionFactory.<init>(ConnectionFactory.java:40)
    at com.myapp.db.conn.ConnectionFactory.getInstance(ConnectionFactory.java:26)
    at com.myapp.init.InitServlet.init(InitServlet.java:48)
    at com.caucho.server.dispatch.ServletConfigImpl.createServletImpl(ServletConfigImpl.java:1394)
    at com.caucho.server.dispatch.ServletConfigImpl.createServlet(ServletConfigImpl.java:1229)
    at com.caucho.server.dispatch.ServletManager.init(ServletManager.java:232)
    at com.caucho.server.webapp.WebApp.startImpl(WebApp.java:3688)
    at com.caucho.server.webapp.WebApp$StartupTask.run(WebApp.java:5196)
    at com.caucho.env.thread2.ResinThread2.runTasks(ResinThread2.java:173)
    at com.caucho.env.thread2.ResinThread2.run(ResinThread2.java:118)
2015-03-31 06:57:28,158 [ERROR][com.alibaba.druid.stat.DruidDataSourceStatManager] - register mbean error
java.lang.NullPointerException
    at java.util.Hashtable.put(Hashtable.java:437)
    at com.caucho.jmx.MBeanContext.addMBean(MBeanContext.java:399)
    at com.caucho.jmx.MBeanContext.registerMBean(MBeanContext.java:261)
    at com.caucho.jmx.AbstractMBeanServer.registerMBean(AbstractMBeanServer.java:422)
    at com.alibaba.druid.stat.DruidDataSourceStatManager.addDataSource(DruidDataSourceStatManager.java:163)
    at com.alibaba.druid.pool.DruidDataSource$1.run(DruidDataSource.java:1395)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.alibaba.druid.pool.DruidDataSource.registerMbean(DruidDataSource.java:1391)
    at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:654)
    at com.myapp.db.conn.ConnectionFactory.getDataSource(ConnectionFactory.java:67)
    at com.myapp.db.conn.ConnectionFactory.<init>(ConnectionFactory.java:40)
    at com.myapp.db.conn.ConnectionFactory.getInstance(ConnectionFactory.java:26)
    at com.myapp.init.InitServlet.init(InitServlet.java:48)
    at com.caucho.server.dispatch.ServletConfigImpl.createServletImpl(ServletConfigImpl.java:1394)
    at com.caucho.server.dispatch.ServletConfigImpl.createServlet(ServletConfigImpl.java:1229)
    at com.caucho.server.dispatch.ServletManager.init(ServletManager.java:232)
    at com.caucho.server.webapp.WebApp.startImpl(WebApp.java:3688)
    at com.caucho.server.webapp.WebApp$StartupTask.run(WebApp.java:5196)
    at com.caucho.env.thread2.ResinThread2.runTasks(ResinThread2.java:173)
    at com.caucho.env.thread2.ResinThread2.run(ResinThread2.java:118)
2015-03-31 06:57:28,174 [ERROR][com.alibaba.druid.stat.DruidDataSourceStatManager] - register mbean error
java.lang.NullPointerException
    at java.util.Hashtable.put(Hashtable.java:437)
    at com.caucho.jmx.MBeanContext.addMBean(MBeanContext.java:399)
    at com.caucho.jmx.MBeanContext.registerMBean(MBeanContext.java:261)
    at com.caucho.jmx.AbstractMBeanServer.registerMBean(AbstractMBeanServer.java:422)
    at com.alibaba.druid.stat.DruidDataSourceStatManager.addDataSource(DruidDataSourceStatManager.java:163)
    at com.alibaba.druid.pool.DruidDataSource$1.run(DruidDataSource.java:1395)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.alibaba.druid.pool.DruidDataSource.registerMbean(DruidDataSource.java:1391)
    at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:654)
    at com.myapp.db.conn.ConnectionFactory.getDataSource(ConnectionFactory.java:67)
    at com.myapp.db.conn.ConnectionFactory.<init>(ConnectionFactory.java:40)
    at com.myapp.db.conn.ConnectionFactory.getInstance(ConnectionFactory.java:26)
    at com.myapp.init.InitServlet.init(InitServlet.java:48)
    at com.caucho.server.dispatch.ServletConfigImpl.createServletImpl(ServletConfigImpl.java:1394)
    at com.caucho.server.dispatch.ServletConfigImpl.createServlet(ServletConfigImpl.java:1229)
    at com.caucho.server.dispatch.ServletManager.init(ServletManager.java:232)
    at com.caucho.server.webapp.WebApp.startImpl(WebApp.java:3688)
    at com.caucho.server.webapp.WebApp$StartupTask.run(WebApp.java:5196)
    at com.caucho.env.thread2.ResinThread2.runTasks(ResinThread2.java:173)
    at com.caucho.env.thread2.ResinThread2.run(ResinThread2.java:118)
2015-03-31 06:57:28,187 [ERROR][com.alibaba.druid.stat.DruidDataSourceStatManager] - register mbean error
java.lang.NullPointerException
    at java.util.Hashtable.put(Hashtable.java:437)
    at com.caucho.jmx.MBeanContext.addMBean(MBeanContext.java:399)
    at com.caucho.jmx.MBeanContext.registerMBean(MBeanContext.java:261)
    at com.caucho.jmx.AbstractMBeanServer.registerMBean(AbstractMBeanServer.java:422)
    at com.alibaba.druid.stat.DruidDataSourceStatManager.addDataSource(DruidDataSourceStatManager.java:163)
    at com.alibaba.druid.pool.DruidDataSource$1.run(DruidDataSource.java:1395)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.alibaba.druid.pool.DruidDataSource.registerMbean(DruidDataSource.java:1391)
    at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:654)
    at com.myapp.db.conn.ConnectionFactory.getDataSource(ConnectionFactory.java:67)
    at com.myapp.db.conn.ConnectionFactory.<init>(ConnectionFactory.java:40)
    at com.myapp.db.conn.ConnectionFactory.getInstance(ConnectionFactory.java:26)
    at com.myapp.init.InitServlet.init(InitServlet.java:48)
    at com.caucho.server.dispatch.ServletConfigImpl.createServletImpl(ServletConfigImpl.java:1394)
    at com.caucho.server.dispatch.ServletConfigImpl.createServlet(ServletConfigImpl.java:1229)
    at com.caucho.server.dispatch.ServletManager.init(ServletManager.java:232)
    at com.caucho.server.webapp.WebApp.startImpl(WebApp.java:3688)
    at com.caucho.server.webapp.WebApp$StartupTask.run(WebApp.java:5196)
    at com.caucho.env.thread2.ResinThread2.runTasks(ResinThread2.java:173)
    at com.caucho.env.thread2.ResinThread2.run(ResinThread2.java:118)
2015-03-31 06:57:28,202 [ERROR][com.alibaba.druid.stat.DruidDataSourceStatManager] - register mbean error
java.lang.NullPointerException
    at java.util.Hashtable.put(Hashtable.java:437)
    at com.caucho.jmx.MBeanContext.addMBean(MBeanContext.java:399)
    at com.caucho.jmx.MBeanContext.registerMBean(MBeanContext.java:261)
    at com.caucho.jmx.AbstractMBeanServer.registerMBean(AbstractMBeanServer.java:422)
    at com.alibaba.druid.stat.DruidDataSourceStatManager.addDataSource(DruidDataSourceStatManager.java:163)
    at com.alibaba.druid.pool.DruidDataSource$1.run(DruidDataSource.java:1395)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.alibaba.druid.pool.DruidDataSource.registerMbean(DruidDataSource.java:1391)
    at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:654)
    at com.myapp.db.conn.ConnectionFactory.getDataSource(ConnectionFactory.java:67)
    at com.myapp.db.conn.ConnectionFactory.<init>(ConnectionFactory.java:40)
    at com.myapp.db.conn.ConnectionFactory.getInstance(ConnectionFactory.java:26)
    at com.myapp.init.InitServlet.init(InitServlet.java:48)
    at com.caucho.server.dispatch.ServletConfigImpl.createServletImpl(ServletConfigImpl.java:1394)
    at com.caucho.server.dispatch.ServletConfigImpl.createServlet(ServletConfigImpl.java:1229)
    at com.caucho.server.dispatch.ServletManager.init(ServletManager.java:232)
    at com.caucho.server.webapp.WebApp.startImpl(WebApp.java:3688)
    at com.caucho.server.webapp.WebApp$StartupTask.run(WebApp.java:5196)
    at com.caucho.env.thread2.ResinThread2.runTasks(ResinThread2.java:173)
    at com.caucho.env.thread2.ResinThread2.run(ResinThread2.java:118)
2015-03-31 06:57:28,216 [ERROR][com.alibaba.druid.stat.DruidDataSourceStatManager] - register mbean error
java.lang.NullPointerException
    at java.util.Hashtable.put(Hashtable.java:437)
    at com.caucho.jmx.MBeanContext.addMBean(MBeanContext.java:399)
    at com.caucho.jmx.MBeanContext.registerMBean(MBeanContext.java:261)
    at com.caucho.jmx.AbstractMBeanServer.registerMBean(AbstractMBeanServer.java:422)
    at com.alibaba.druid.stat.DruidDataSourceStatManager.addDataSource(DruidDataSourceStatManager.java:163)
    at com.alibaba.druid.pool.DruidDataSource$1.run(DruidDataSource.java:1395)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.alibaba.druid.pool.DruidDataSource.registerMbean(DruidDataSource.java:1391)
    at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:654)
    at com.myapp.db.conn.ConnectionFactory.getDataSource(ConnectionFactory.java:67)
    at com.myapp.db.conn.ConnectionFactory.<init>(ConnectionFactory.java:40)
    at com.myapp.db.conn.ConnectionFactory.getInstance(ConnectionFactory.java:26)
    at com.myapp.init.InitServlet.init(InitServlet.java:48)
    at com.caucho.server.dispatch.ServletConfigImpl.createServletImpl(ServletConfigImpl.java:1394)
    at com.caucho.server.dispatch.ServletConfigImpl.createServlet(ServletConfigImpl.java:1229)
    at com.caucho.server.dispatch.ServletManager.init(ServletManager.java:232)
    at com.caucho.server.webapp.WebApp.startImpl(WebApp.java:3688)
    at com.caucho.server.webapp.WebApp$StartupTask.run(WebApp.java:5196)
    at com.caucho.env.thread2.ResinThread2.runTasks(ResinThread2.java:173)
    at com.caucho.env.thread2.ResinThread2.run(ResinThread2.java:118)
2015-03-31 06:57:28,229 [ERROR][com.alibaba.druid.stat.DruidDataSourceStatManager] - register mbean error
java.lang.NullPointerException
    at java.util.Hashtable.put(Hashtable.java:437)
    at com.caucho.jmx.MBeanContext.addMBean(MBeanContext.java:399)
    at com.caucho.jmx.MBeanContext.registerMBean(MBeanContext.java:261)
    at com.caucho.jmx.AbstractMBeanServer.registerMBean(AbstractMBeanServer.java:422)
    at com.alibaba.druid.stat.DruidDataSourceStatManager.addDataSource(DruidDataSourceStatManager.java:163)
    at com.alibaba.druid.pool.DruidDataSource$1.run(DruidDataSource.java:1395)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.alibaba.druid.pool.DruidDataSource.registerMbean(DruidDataSource.java:1391)
    at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:654)
    at com.myapp.db.conn.ConnectionFactory.getDataSource(ConnectionFactory.java:67)
    at com.myapp.db.conn.ConnectionFactory.<init>(ConnectionFactory.java:40)
    at com.myapp.db.conn.ConnectionFactory.getInstance(ConnectionFactory.java:26)
    at com.myapp.init.InitServlet.init(InitServlet.java:48)
    at com.caucho.server.dispatch.ServletConfigImpl.createServletImpl(ServletConfigImpl.java:1394)
    at com.caucho.server.dispatch.ServletConfigImpl.createServlet(ServletConfigImpl.java:1229)
    at com.caucho.server.dispatch.ServletManager.init(ServletManager.java:232)
    at com.caucho.server.webapp.WebApp.startImpl(WebApp.java:3688)
    at com.caucho.server.webapp.WebApp$StartupTask.run(WebApp.java:5196)
    at com.caucho.env.thread2.ResinThread2.runTasks(ResinThread2.java:173)
    at com.caucho.env.thread2.ResinThread2.run(ResinThread2.java:118)
```

```
DruidDataSource dataSource = new DruidDataSource();
        // filters=stat,log4j
        dataSource.setUrl(pro.get("JdbcUrl"));
        dataSource.setUsername(pro.get("User"));
        dataSource.setPassword(pro.get("Password"));
        dataSource.setInitialSize(pro.getInt("InitialPoolSize"));
        dataSource.setMaxActive(pro.getInt("MaxPoolSize"));
        dataSource.setMinIdle(pro.getInt("minIdle",1));
        dataSource.setPoolPreparedStatements(true);
        dataSource.setDriverClassName(pro.get("DriverClass"));
        dataSource.setValidationQuery("SELECT 'x'");
        dataSource.setTestOnBorrow(pro.getBoolean("testOnBorrow", true));
        dataSource.setTestWhileIdle(pro.getBoolean("testWhileIdle", true));
        dataSource.setTestOnReturn(pro.getBoolean("testOnReturn", true));
        dataSource.getDriverClassName();
        dataSource.setDbType("mysql");
        dataSource.init();
```

**Comment by junfengcode** [comment]
1.0.14任然有这个问题，但不影响使用

**Comment by lizongbo** [comment]
请使用最新版再验证。
