### ISSUE TITLE
Default validate query of Postgresql

### ISSUE THREAD

**Issue by xuse** [alibaba/druid#814]
Version: 1.0.13
Issue: 
````
Caused by: 
java.sql.SQLException: validateConnection false
	at com.alibaba.druid.pool.DruidAbstractDataSource.validateConnection(DruidAbstractDataSource.java:1216)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1439)
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:632)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
````

Reason:
 ````
public class PGValidConnectionChecker extends ValidConnectionCheckerAdapter implements ValidConnectionChecker, Serializable {

    private static final long serialVersionUID     = -2227528634302168877L;

    private static final Log  LOG                  = LogFactory.getLog(PGValidConnectionChecker.class);

    private String            defaultValidateQuery = "SELECT 'x' FROM DUAL"; 
````

And
![image](https://cloud.githubusercontent.com/assets/4861309/7131824/1553c75a-e2b6-11e4-8b96-73b0d8ea991f.png)

----
BTW Suggesting:

DruidAbstractDataSource.java: 1216
````
            if (!validConnectionChecker.isValidConnection(conn, validationQuery, validationQueryTimeout)) {
                throw new SQLException("validateConnection false");
            }
            return;
````
Use SQLException.setNextException(throwable) to raise the raw exception of SQL executing is better.

Thx.

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/pull/864
