### ISSUE TITLE
mybatis  3.2.8：ncom.alibaba.druid.sql.parser.ParserException: syntax error, error in :'like ?"%" 

### ISSUE THREAD

**Issue by wing1000** [alibaba/druid#820]
ERROR 14:48:15.309 [localhost:8080] - com.alibaba.druid.filter.stat.StatFilter.mergeSql(StatFilter.java:147) merge sql error, dbType mysql, sql : 
select *
        from article
        where
        path like ?"%" and status = 'display' and `check` = 'yes'
        order by
        createTime desc limit ?,?
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'ike ?"%" and status = 'display' and',expect LITERAL_ALIAS, actual LITERAL_ALIAS %
    at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:230)
    at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:325)
    at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:121)
    at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:116)
    at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:53)
    at com.alibaba.druid.filter.stat.StatFilter.mergeSql(StatFilter.java:145)
    at com.alibaba.druid.filter.stat.StatFilter.createSqlStat(StatFilter.java:629)
    at com.alibaba.druid.filter.stat.StatFilter.statementPrepareAfter(StatFilter.java:305)
    at com.alibaba.druid.filter.FilterEventAdapter.connection_prepareStatement(FilterEventAdapter.java:124)
    at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:448)
    at com.alibaba.druid.filter.FilterAdapter.connection_prepareStatement(FilterAdapter.java:928)
    at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:448)
    at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.prepareStatement(ConnectionProxyImpl.java:342)
    at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:318)
    at org.apache.ibatis.executor.statement.PreparedStatementHandler.instantiateStatement(PreparedStatementHandler.java:75)
    at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:85)
    at org.apache.ibatis.executor.statement.RoutingStatementHandler.prepare(RoutingStatementHandler.java:57)
    at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:73)
    at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:59)
    at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:267)
    at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:137)
    at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:96)
    at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:77)
    at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:108)
    at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:102)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:358)
    at com.sun.proxy.$Proxy17.selectList(Unknown Source)
    at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:198)
    at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:119)
    at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:63)
    at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:52)
    at com.sun.proxy.$Proxy27.getArticleListOfDisplayByPath(Unknown Source)

**Comment by jacking124** [comment]
你的sql

**Comment by wenshao** [comment]
sql语法明显是不合法啊。。。

**Comment by wing1000** [comment]
select *
		from article
		where
		path like #{path}"%" and status = 'display' and `check` = 'yes'
		order by
		createTime desc limit #{offset},#{rows}

这是mybatis mapper xml中的配置，#{}是mybatis变量，结果sql是：

select *
		from article
		where
		path like ?"%" and status = 'display' and `check` = 'yes'
		order by
		createTime desc limit  ? ,?

项目中用其他jdbc pool没有问题

项目为开源项目，地址http://git.oschina.net/tietang/CMS

**Comment by wing1000** [comment]
附上数据库和代码：


DROP TABLE IF EXISTS `article`;
CREATE TABLE `article` (
  `articleId` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '文件ID',
  `folderId` bigint(20) DEFAULT NULL,
  `path` varchar(200) DEFAULT NULL,
  `adminId` bigint(20) DEFAULT '0' COMMENT '管理员ID',
  `picture` varchar(60) DEFAULT NULL,
  `title` varchar(200) DEFAULT '' COMMENT '文件名称',
  `summary` varchar(2000) DEFAULT NULL,
  `content` mediumtext COMMENT '文件内容',
  `viewCount` int(11) DEFAULT '0' COMMENT '浏览数',
  `commentCount` int(11) DEFAULT '0' COMMENT '评论数',
  `status` varchar(20) DEFAULT 'init' COMMENT '状态：0 隐藏 1 显示',
  `check` enum('yes','no','init') DEFAULT NULL,
  `createTime` datetime DEFAULT NULL COMMENT '创建时间',
  `updateTime` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`articleId`),
  KEY `idx_folder` (`status`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='文件';

 
INSERT INTO `article` VALUES ('1', '1', '1', '1', '', 'Hello World', 'Hello World!!', '<p>Hello World!!</p><div id=\"xunlei_com_thunder_helper_plugin_d462f475-c18e-46be-bd10-327458d045bd\"></div>', '0', '0', 'display', 'yes', '2014-10-29 00:00:00', '2014-10-29 20:49:54'), ('2', '6', '6', '1', 'upload/2015/05/03/05c0864a6b9b404f8507d07fba983b04.jpg', '测试', '哈哈', '<p>很快就很快就很快就好健康<sub><span style=\"border: 1px solid rgb(0, 0, 0);\"></span></sub></p>', '0', '0', 'display', 'yes', '2015-05-03 00:00:00', '2015-05-03 13:28:22');
 


public class JDBCLikeTest {

    public static void main(String[] args) throws ClassNotFoundException, SQLException {
        String url = "jdbc:mysql://127.0.0.1:3306/shishuocms?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull";
        String username = "root";
        String password = "";
        Class.forName("com.mysql.jdbc.Driver");
        Connection conn = DriverManager.getConnection(url, username, password);
        String sql = "select *  from article " +
                " where  content like ?\"%\" and status = 'display' and `check` = 'yes'" +
                " order by  createTime desc limit ?,?";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, "");
        ps.setInt(2, 0);
        ps.setInt(3, 2);
        ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            System.out.println(rs.getObject(1)+"，"+rs.getObject(6));
        }
        rs.close();
        ps.close();
        conn.close();

    }

}


运行结果：

2，测试
1，Hello World

**Comment by wing1000** [comment]
另外刚刚测试了druid连接池只要启用sql解析依赖的功能就抛出这个异常，如果没有启用sql解析依赖的功能，则可以正常使用。

如下面设置了：    dataSource.setFilters("wall,stat");

```java
import com.alibaba.druid.pool.DruidDataSource;

import java.sql.*;

/**
 * @Date: 15/5/10
 * @Time: 21:23
 */


public class JDBCLikeTest {

    public static void main(String[] args) throws ClassNotFoundException, SQLException {
        String url = "jdbc:mysql://127.0.0.1:3306/shishuocms?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull";
        String username = "root";
        String password = "";
        Class.forName("com.mysql.jdbc.Driver");
        DruidDataSource dataSource=new DruidDataSource();
        dataSource.setInitialSize(1);
        dataSource.setMaxActive(1);
        dataSource.setMinIdle(1);
        dataSource.setMaxIdle(1);
        dataSource.setPoolPreparedStatements(true);
        dataSource.setDriverClassName("com.mysql.jdbc.Driver");
        dataSource.setUrl(url);
        dataSource.setUsername(username);
        dataSource.setPassword(password);
        dataSource.setValidationQuery("SELECT 1");
        dataSource.setTestOnBorrow(true);
        dataSource.setFilters("wall,stat");
        dataSource.init();

        Connection conn = dataSource.getConnection();
//        Connection conn = DriverManager.getConnection(url, username, password);
        String sql = "select *  from article " +
                " where  title like \"%\"?\"%\" and status = 'display' and `check` = 'yes'" +
                " order by  createTime desc limit ?,?";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, "试");
        ps.setInt(2, 0);
        ps.setInt(3, 2);
        ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            System.out.println(rs.getObject(1)+"，"+rs.getObject(6));
        }
        rs.close();
        ps.close();
        conn.close();

    }

}
```

2015-05-10.22:15:12.933 ERROR main com.alibaba.druid.pool.DruidAbstractDataSource.setMaxIdle(935) - maxIdle is deprecated
2015-05-10.22:15:13.804 INFO main com.alibaba.druid.pool.DruidDataSource.init(669) - {dataSource-1} inited
Exception in thread "main" java.sql.SQLException: sql injection violation, syntax error: syntax error, error in :'like "%"?"%" and status = 'display'',expect QUES, actual QUES % : select *  from article  where  title like "%"?"%" and status = 'display' and `check` = 'yes' order by  createTime desc limit ?,?
	at com.alibaba.druid.wall.WallFilter.check(WallFilter.java:711)
	at com.alibaba.druid.wall.WallFilter.connection_prepareStatement(WallFilter.java:240)
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:448)
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.prepareStatement(ConnectionProxyImpl.java:342)
	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:318)
	at JDBCLikeTest.main(JDBCLikeTest.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'like "%"?"%" and status = 'display'',expect QUES, actual QUES %
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:230)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:325)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:121)
	at com.alibaba.druid.wall.WallProvider.checkInternal(WallProvider.java:620)
	at com.alibaba.druid.wall.WallProvider.check(WallProvider.java:574)
	at com.alibaba.druid.wall.WallFilter.check(WallFilter.java:699)
	... 10 more

**Comment by wenshao** [comment]
这个啥语法啊。。。

**Comment by chenyancun** [comment]
答案在这里[github.com/alibaba/druid/issues/832](https://github.com/alibaba/druid/issues/832)
