### ISSUE TITLE
format error - com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'like "%"?"%" OR v.video_desc like "',expect QUES, actual QUES %

### ISSUE THREAD

**Issue by ilaipi** [alibaba/druid#832]
这个错误发生在 通过sql监控 查看sql详细信息的时候。
后端的sql主要是mybatis的like：

```
    <if test="keyword != null">
        and v.video_title like "%"#{keyword}"%" OR v.video_desc like "%"#{keyword}"%"
    </if>
```

后端报错信息如下：

```
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'like "%"?"%" OR v.video_desc like "',expect QUES, actual QUES %
    at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:210)
    at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:307)
    at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:112)
    at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:107)
    at com.alibaba.druid.sql.SQLUtils.toStatementList(SQLUtils.java:173)
    at com.alibaba.druid.sql.SQLUtils.format(SQLUtils.java:186)
    at com.alibaba.druid.sql.SQLUtils.format(SQLUtils.java:181)
    at com.alibaba.druid.stat.DruidStatService.getSqlStat(DruidStatService.java:310)
    at com.alibaba.druid.stat.DruidStatService.service(DruidStatService.java:136)
    at com.alibaba.druid.support.http.StatViewServlet.process(StatViewServlet.java:162)
    at com.alibaba.druid.support.http.ResourceServlet.service(ResourceServlet.java:248)
```

**Comment by chenyancun** [comment]
请问您解决这个问题了吗？我也遇到了这样的问题，求帮忙。

**Comment by ilaipi** [comment]
太久了，我好像后来放弃了查看这个监控页面，反正正常执行没啥问题

**Comment by chenyancun** [comment]
我想出一个权宜之计。druid不是说变量左右不能有%吗？那我们干脆不加%就好了，变通的方法是直接在传值的时候，把%加上就好了。因此，你的sql可以改成`<if test="keyword != null">and v.video_title like "%"#{keyword}"%" OR v.video_desc like #{keyword}</if>` 你在传值的时候让`keyword=“%”+keyword+“%”;` 这样就不会再抛异常了。

**Comment by MerGades** [comment]
也遇到了这个问题，本地debug log会一直输出这种类似的错误

**Comment by chenyueling** [comment]
LIKE CONCAT(CONCAT('%',#{keword}),'%') 这种拼接的方式也可以解决。

**Comment by wenshao** [comment]
@MicyToy 其他数据库是不支持的，我下个加上支持吧

**Comment by wenshao** [comment]
https://github.com/alibaba/druid/releases/tag/1.1.9
问题已修复，请用新版本
