### ISSUE TITLE
MYSQL DDL语句解析错误

### ISSUE THREAD

**Issue by huaxiaoer** [alibaba/druid#849]
修改表时，一个Add 对应多个列定义的语句 解析错误
sql：
ALTER TABLE score1 ADD ( test3 int(11),test4 int(11))

错误信息：
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: error LPAREN
	at com.alibaba.druid.sql.parser.SQLExprParser.name(SQLExprParser.java:864)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.parseColumn(MySqlExprParser.java:521)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseAlter(MySqlStatementParser.java:2330)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:182)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:121)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:116)

**Comment by wenshao** [comment]
已经修复，等下一个版本吧
