### ISSUE TITLE
com.alibaba.druid.sql.parser.ParserException: ERROR. token : REPLACE, pos : 42

### ISSUE THREAD

**Issue by ghsau** [alibaba/druid#916]
[2015-07-20 11:23:52 http-bio-8080-exec-53-5125-1437362632616 ERROR com.alibaba.druid.filter.stat.StatFilter:147] merge sql error, dbType mysql, sql : 
UPDATE qadmin_user set tree_code = REPLACE(tree_code, ?, ?) WHERE tree_code LIKE CONCAT(?, '%');
com.alibaba.druid.sql.parser.ParserException: ERROR. token : REPLACE, pos : 42
        at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:464) ~[druid-0.2.18.jar:0.2.18]
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.primary(MySqlExprParser.java:180) ~[druid-0.2.18.jar:0.2.18]
        at com.alibaba.druid.sql.parser.SQLExprParser.expr(SQLExprParser.java:88) ~[druid-0.2.18.jar:0.2.18]
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseUpdateSet(MySqlStatementParser.java:2563) ~[druid-0.2.18.jar:0.2.18]
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseUpdateStatement(MySqlStatementParser.java:219) ~[druid-0.2.18.jar:0.2.18]
        at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:96) ~[druid-0.2.18.jar:0.2.18]
        at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:75) ~[druid-0.2.18.jar:0.2.18]
        at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:41) ~[druid-0.2.18.jar:0.2.18]
        at com.alibaba.druid.filter.stat.StatFilter.mergeSql(StatFilter.java:145) [druid-0.2.18.jar:0.2.18]
        at com.alibaba.druid.filter.stat.StatFilter.createSqlStat(StatFilter.java:627) [druid-0.2.18.jar:0.2.18]
        at com.alibaba.druid.filter.stat.StatFilter.statementPrepareAfter(StatFilter.java:305) [druid-0.2.18.jar:0.2.18]
        at com.alibaba.druid.filter.FilterEventAdapter.connection_prepareStatement(FilterEventAdapter.java:124) [druid-0.2.18.jar:0.2.18]
        at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:446) [druid-0.2.18.jar:0.2.18]
        at com.alibaba.druid.filter.FilterAdapter.connection_prepareStatement(FilterAdapter.java:911) [druid-0.2.18.jar:0.2.18]
        at com.alibaba.druid.filter.FilterEventAdapter.connection_prepareStatement(FilterEventAdapter.java:122) [druid-0.2.18.jar:0.2.18]
        at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:446) [druid-0.2.18.jar:0.2.18]
        at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.prepareStatement(ConnectionProxyImpl.java:342) [druid-0.2.18.jar:0.2.18]
        at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:311) [druid-0.2.18.jar:0.2.18]

**Comment by wenshao** [comment]
升级版本就好了

**Comment by nhsoft** [comment]
哪里可以获取最新版本编译后的jar包？

**Comment by ChetWang** [comment]
druid还有1.1.15版本？发布版只有1.0.xx啊，我用1.0.29还是有这个问题。

**Comment by xiaoshuaishuai** [comment]
遇到这个问题了，原因是因为表字段使用了关键字导致的

**Comment by yanggangying** [comment]
sql 错了一般是
