### ISSUE TITLE
MySQL获取连接ping命令验证连接是否有效时阻塞

### ISSUE THREAD

**Issue by DuLerWeil** [alibaba/druid#919]
MySQL: 5.5.28-enterprise
mysql-connector-java: 5.1.34
Druid: 1.0.14
应用服务器经A10到MySQL服务器。

Druid连接配置: 自定义的多数据源配置文件，标签和druid支持的属性一致
```
<?xml version="1.0" encoding="UTF-8" ?>
<druid>
  <databases>
    <database>
      <!--核心库-->
      <alias>CORE_DB</alias>
      <driverClassName>com.mysql.jdbc.Driver</driverClassName>
      <url>jdbc:mysql://xxxxxxxxxxxxxx?useUnicode=true&amp;characterEncoding=utf8</url>
      <username>xxxxxx</username>
      <password>xxxxxx</password>
      <initialSize>3</initialSize>
      <testWhileIdle>true</testWhileIdle>
      <validationQuery>SELECT 'x'</validationQuery>
      <timeBetweenEvictionRunsMillis>60000</timeBetweenEvictionRunsMillis>
    </database>
    <database>
      <!--统计库-->
      <alias>STAT_DB</alias>
      <driverClassName>com.mysql.jdbc.Driver</driverClassName>
      <url>jdbc:mysql://xxxxxxxxxxxxxx?useUnicode=true&amp;characterEncoding=utf8</url>
      <username>xxxxxx</username>
      <password>xxxxxx</password>
      <initialSize>3</initialSize>
      <testWhileIdle>true</testWhileIdle>
      <validationQuery>SELECT 'x'</validationQuery>
      <timeBetweenEvictionRunsMillis>60000</timeBetweenEvictionRunsMillis>
    </database>
  </databases>
</druid>
```

现象：如图jstack信息，该线程从21号17点阻塞到现在。
```
   java.lang.Thread.State: RUNNABLE
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.read(SocketInputStream.java:129)
        at com.mysql.jdbc.util.ReadAheadInputStream.fill(ReadAheadInputStream.java:100)
        at com.mysql.jdbc.util.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:143)
        at com.mysql.jdbc.util.ReadAheadInputStream.read(ReadAheadInputStream.java:173)
        - locked <0x00000007ac9cbc78> (a com.mysql.jdbc.util.ReadAheadInputStream)
        at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2911)
        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3337)
        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3327)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
        at com.mysql.jdbc.ConnectionImpl.pingInternal(ConnectionImpl.java:3971)
        at com.mysql.jdbc.ConnectionImpl.ping(ConnectionImpl.java:3951)
        at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at com.alibaba.druid.pool.vendor.MySqlValidConnectionChecker.isValidConnection(MySqlValidConnectionChecker.java:98)
        at com.alibaba.druid.pool.DruidAbstractDataSource.testConnectionInternal(DruidAbstractDataSource.java:1252)
        at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1000)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:940)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:930)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:102)
```
读到com.mysql.jdbc.ConnectionImpl的源码：得知timeoutMillis=0，若在失效的连接(Druid认为有效，但实际被A10中断)上执行ping检查，将一直阻塞。

```
    public void ping() throws SQLException {
        pingInternal(true, 0);
    }

    public void pingInternal(boolean checkForClosedConnection, int timeoutMillis) throws SQLException {
        if (checkForClosedConnection) {
            checkClosed();
        }

        long pingMillisLifetime = getSelfDestructOnPingSecondsLifetime();
        int pingMaxOperations = getSelfDestructOnPingMaxOperations();

        if ((pingMillisLifetime > 0 && (System.currentTimeMillis() - this.connectionCreationTimeMillis) > pingMillisLifetime)
                || (pingMaxOperations > 0 && pingMaxOperations <= this.io.getCommandCount())) {

            close();

            throw SQLError.createSQLException(Messages.getString("Connection.exceededConnectionLifetime"), SQLError.SQL_STATE_COMMUNICATION_LINK_FAILURE,
                    getExceptionInterceptor());
        }
        // Need MySQL-3.22.1, but who uses anything older!?
        this.io.sendCommand(MysqlDefs.PING, null, null, false, null, timeoutMillis);
    }

```

网上找到一个问题相同，且场景类似的帖子：http://www.cnblogs.com/zhukunrong/p/4525955.html
怀疑是A10连接时间设置太短，过早中断应用服务器与MySQL服务器之间维持的长连接。
询问网管得知A10设置120秒中断连接。

准备修改配置如下：添加获取连接最大等待时间
```
<?xml version="1.0" encoding="UTF-8" ?>
<druid>
  <databases>
    <database>
      <!--核心库-->
      <alias>CORE_DB</alias>
      <driverClassName>com.mysql.jdbc.Driver</driverClassName>
      <url>jdbc:mysql://xxxxxxxxxxxxxx?useUnicode=true&amp;characterEncoding=utf8</url>
      <username>xxxxxx</username>
      <password>xxxxxx</password>
      <initialSize>3</initialSize>
      <maxWait>5000</maxWait>
      <testWhileIdle>true</testWhileIdle>
      <validationQuery>SELECT 'x'</validationQuery>
      <timeBetweenEvictionRunsMillis>60000</timeBetweenEvictionRunsMillis>
    </database>
    <database>
      <!--统计库-->
      <alias>STAT_DB</alias>
      <driverClassName>com.mysql.jdbc.Driver</driverClassName>
      <url>jdbc:mysql://xxxxxxxxxxxxxx?useUnicode=true&amp;characterEncoding=utf8</url>
      <username>xxxxxx</username>
      <password>xxxxxx</password>
      <initialSize>3</initialSize>
      <maxWait>5000</maxWait>
      <testWhileIdle>true</testWhileIdle>
      <validationQuery>SELECT 'x'</validationQuery>
      <timeBetweenEvictionRunsMillis>60000</timeBetweenEvictionRunsMillis>
    </database>
  </databases>
</druid>
```

观察一段时间再回复，有没解决问题。

**Comment by DuLerWeil** [comment]
```
<maxWait>5000</maxWait>
```
应该是从连接池里获取连接的最大等待时间，影响不到ping的超时设置。
Druid是否考虑支持下？

**Comment by DuLerWeil** [comment]
哎，翻Druid源码才知道已经支持validationQueryTimeout属性，Wiki的属性表应该更新了。

**Comment by DuLerWeil** [comment]
光设置validationQueryTimeout并不能解决问题。
MySqlValidConnectionChecker默认使用com.mysql.jdbc.ConnectionImpl.ping()方法进行连接验证。
此时validationQueryTimeout不生效，所以会一直阻塞下去。

读Druid源码，尝试在配置文件添加以下配置也不生效，因为DruidDataSourceFactory.createDataSource(Properties)的初始化过程没有用到它。
不知道是设计上废弃了，还是其它原因？
```
<connectionProperties>druid.mysql.usePingMethod=false</connectionProperties>
```

最后只能通过增加系统属性-Ddruid.mysql.usePingMethod=false的方式，强制使用Druid的验证逻辑。

**Comment by DuLerWeil** [comment]
建议修改MySqlValidConnectionChecker中的反射逻辑，直接取com.mysql.jdbc.ConnectionImpl.pingInternal(boolean checkForClosedConnection, int timeoutMillis)方法，并将validationQueryTimeout作为它的超时值。

**Comment by wenshao** [comment]
好建议

**Comment by wenshao** [comment]
已经提交代码，还没做验证，是否能帮忙测试一下？

**Comment by cnhnnyzhy** [comment]
请问，这个问题在哪个版本里面解决了，我也遇到这个问题了！！！

**Comment by cnhnnyzhy** [comment]
我使用最新版本，问题还是没解决。如果一个系统等十几分钟没人用，第一个人使用的时间，请求数据库一直在等待，如果这时候第二个人使用的时候则正常，过一会儿第一个人的请求也正常了，这是什么问题啊？？？？

**Comment by thoslin** [comment]
@wenshao https://github.com/alibaba/druid/pull/933 早期版本的mysql驱动是没有com.mysql.jdbc.MySQLConnection这个类的，这么改会导致NullPointerException，而warning log并没有提到这一点，不知道可否改下log，给用户一点提示，否则报错的日志看起来很confusing。

**Comment by DuLerWeil** [comment]
哈，真是巧合，时隔一年想起来这事，回头找个机会验证下

**Comment by DuLerWeil** [comment]
@thoslin @wenshao 确实，此处改动需要谨慎些。也许druid每个版本发布时带上驱动适用的版本好些。

**Comment by DuLerWeil** [comment]
druid1.0.16~20验证可用，但存在个小bug，MySQLConnection.pingInternal(boolean checkForClosedConnection, int timeoutMillis)的超时单位是毫秒，而Statement.setQueryTimeout(int seconds)是秒。
都用validationQueryTimeout时，需要保持单位统一。

**Comment by zhangjun075** [comment]
我感觉druid确实有个bug啊。
if (null != query) {
            Statement stmt = null;
            ResultSet rs = null;
            try {
                stmt = conn.createStatement();
                if (getValidationQueryTimeout() > 0) {
                    stmt.setQueryTimeout(getValidationQueryTimeout());
                }
                rs = stmt.executeQuery(query);
                if (!rs.next()) {
                    throw new SQLException("validationQuery didn't return a row");
                }
            } finally {
                JdbcUtils.close(rs);
                JdbcUtils.close(stmt);
            }
        }
statment中的用的竟然是second作为单位。这里直接将query的timeout时间设置进去了。

**Comment by gMan1990** [comment]
@zhangjun075 兄弟，你markdown要好好学学了，我帮你重新编排下
https://github.com/alibaba/druid/blob/f69e367e6553a8d115377ccf503a85327b74f585/src/main/java/com/alibaba/druid/pool/DruidAbstractDataSource.java#L1380
```
        if (null != query) {
            Statement stmt = null;
            ResultSet rs = null;
            try {
                stmt = conn.createStatement();
                if (getValidationQueryTimeout() > 0) {
                    stmt.setQueryTimeout(getValidationQueryTimeout());
                }
                rs = stmt.executeQuery(query);
                if (!rs.next()) {
                    throw new SQLException("validationQuery didn't return a row");
                }
            } finally {
                JdbcUtils.close(rs);
                JdbcUtils.close(stmt);
            }
        }
```
这里没有问题，[validationQueryTimeout的时间单位就是秒](https://github.com/alibaba/druid/wiki/DruidDataSource配置属性列表)
