### ISSUE TITLE
spring3.2.12使用druid时报  java.lang.NoClassDefFoundError: Could not initialize class com.alibaba.druid.filter.FilterManager

### ISSUE THREAD

**Issue by zogwei** [alibaba/druid#934]
确认已经加入了 druid1.0.14的jar包，但是spring3.2.12使用druid时报  java.lang.NoClassDefFoundError: Could not initialize class com.alibaba.druid.filter.FilterManager

报错内容如下：
aused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlSessionFactoryForMybatis' defined in file [/public/temp/ala-service-container/WEB-INF/classes/config/biz-datasource.xml]: Cannot resolve reference to bean 'dataSource' while setting bean property 'dataSource'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in file [/public/temp/ala-service-container/WEB-INF/classes/config/biz-datasource.xml]: Error setting property values; nested exception is org.springframework.beans.PropertyBatchUpdateException; nested PropertyAccessExceptions (1) are:
PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'filters' threw exception; nested exception is java.lang.NoClassDefFoundError: Could not initialize class com.alibaba.druid.filter.FilterManager
    at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:334)
    at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1419)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1160)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:293)

**Comment by bigbigwei** [comment]
同问，也碰到了这样的问题

**Comment by wenshao** [comment]
找一下这个日志"load filter config error"看是什么问题

**Comment by liuyuyong** [comment]
怎么解决的
