### ISSUE TITLE
call,  exec 语句解析

### ISSUE THREAD

**Issue by wangyu4882** [alibaba/druid#949]
Sqlserver 解析如下语句出错
EXEC test_SP @P0 OUT

mysql 解析如下语句出错
CALL 'test'.'test_SP'

版本： 1.0.15

**Comment by wangyu4882** [comment]
Versino： 1.0.20
SQL：  CALL 'test'.'test_SP'
解析异常 ： 
Exception in thread "main" com.alibaba.druid.sql.parser.ParserException: error, LITERAL_CHARS
	at com.alibaba.druid.sql.parser.SQLExprParser.nameRest(SQLExprParser.java:994)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.nameRest(MySqlExprParser.java:773)
	at com.alibaba.druid.sql.parser.SQLExprParser.name(SQLExprParser.java:976)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseCall(SQLStatementParser.java:1548)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:339)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:145)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:140)
	at com.alibaba.druid.sql.SQLUtils.toStatementList(SQLUtils.java:234)
	at com.quicklaud.dfw.sqlwall.BaseSqlWallTest.main(BaseSqlWallTest.java:144)
