### ISSUE TITLE
jdbcTemplate一直报错syntax error: ERROR. token : FUNCTION, pos 

### ISSUE THREAD

**Issue by shaoxy** [alibaba/druid#950]
一个简单的查询语句，其他查询语句都是OK的

Caused by: java.sql.SQLException: sql injection violation, syntax error: ERROR. token : FUNCTION, pos : 163 :  SELECT function_id,
       parent_id,
       class,
       display_order,
       fullname,
       description,
       target,
       function_type
  FROM function
	at com.alibaba.druid.wall.WallFilter.check(WallFilter.java:711) ~[druid-1.0.15.jar:1.0.15]
	at com.alibaba.druid.wall.WallFilter.connection_prepareStatement(WallFilter.java:240) ~[druid-1.0.15.jar:1.0.15]
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:448) ~[druid-1.0.15.jar:na]
	at com.alibaba.druid.filter.FilterAdapter.connection_prepareStatement(FilterAdapter.java:928) ~[druid-1.0.15.jar:na]
	at com.alibaba.druid.filter.FilterEventAdapter.connection_prepareStatement(FilterEventAdapter.java:122) ~[druid-1.0.15.jar:na]
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:448) ~[druid-1.0.15.jar:na]
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.prepareStatement(ConnectionProxyImpl.java:342) ~[druid-1.0.15.jar:na]
	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:318) ~[druid-1.0.15.jar:1.0.15]
	at org.springframework.jdbc.core.PreparedStatementCreatorFactory$PreparedStatementCreatorImpl.createPreparedStatement(PreparedStatementCreatorFactory.java:238) ~[spring-jdbc-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:638) ~[spring-jdbc-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	... 70 common frames omitted
Caused by: com.alibaba.druid.sql.parser.ParserException: ERROR. token : FUNCTION, pos : 163
	at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:555) ~[druid-1.0.15.jar:na]
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.primary(MySqlExprParser.java:166) ~[druid-1.0.15.jar:1.0.15]
	at com.alibaba.druid.sql.parser.SQLExprParser.expr(SQLExprParser.java:121) ~[druid-1.0.15.jar:na]
	at com.alibaba.druid.sql.parser.SQLSelectParser.expr(SQLSelectParser.java:435) ~[druid-1.0.15.jar:na]
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseTableSourceQueryTableExpr(SQLSelectParser.java:339) ~[druid-1.0.15.jar:na]
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseTableSource(SQLSelectParser.java:327) ~[druid-1.0.15.jar:na]
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseFrom(SQLSelectParser.java:294) ~[druid-1.0.15.jar:na]
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlSelectParser.query(MySqlSelectParser.java:132) ~[druid-1.0.15.jar:1.0.15]
	at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:60) ~[druid-1.0.15.jar:na]
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseSelect(MySqlStatementParser.java:195) ~[druid-1.0.15.jar:1.0.15]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:144) ~[druid-1.0.15.jar:na]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:120) ~[druid-1.0.15.jar:na]
	at com.alibaba.druid.wall.WallProvider.checkInternal(WallProvider.java:620) ~[druid-1.0.15.jar:1.0.15]
	at com.alibaba.druid.wall.WallProvider.check(WallProvider.java:574) ~[druid-1.0.15.jar:1.0.15]
	at com.alibaba.druid.wall.WallFilter.check(WallFilter.java:699) ~[druid-1.0.15.jar:1.0.15]
	at com.alibaba.druid.wall.WallFilter.connection_prepareStatement(WallFilter.java:240) ~[druid-1.0.15.jar:1.0.15]
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:448) ~[druid-1.0.15.jar:na]
	at com.alibaba.druid.filter.FilterAdapter.connection_prepareStatement(FilterAdapter.java:928) ~[druid-1.0.15.jar:na]
	at com.alibaba.druid.filter.FilterEventAdapter.connection_prepareStatement(FilterEventAdapter.java:122) ~[druid-1.0.15.jar:na]
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:448) ~[druid-1.0.15.jar:na]
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.prepareStatement(ConnectionProxyImpl.java:342) ~[druid-1.0.15.jar:na]
	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:318) ~[druid-1.0.15.jar:1.0.15]
	at org.springframework.jdbc.core.PreparedStatementCreatorFactory$PreparedStatementCreatorImpl.createPreparedStatement(PreparedStatementCreatorFactory.java:238) ~[spring-jdbc-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:638) ~[spring-jdbc-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:695) ~[spring-jdbc-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:722) ~[spring-jdbc-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:772) ~[spring-jdbc-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.query(NamedParameterJdbcTemplate.java:192) ~[spring-jdbc-4.1.6.RELEASE.jar:na]
	... 65 common frames omitted

**Comment by gonedays** [comment]
FUNCTION 在mysql中是关键字，不知道是否能直接这样用，你用反单引号把function括起来看看?
 SELECT function_id,
parent_id,
class,
display_order,
fullname,
description,
target,
function_type
FROM `function`

**Comment by shaoxy** [comment]
谢谢 搞定咯
