### ISSUE TITLE
connection holder is null

### ISSUE THREAD

**Issue by ly01152000** [alibaba/druid#961]
```
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:745)
```

Caused by: java.sql.SQLException: connection holder is null
    at com.alibaba.druid.pool.DruidPooledConnection.checkStateInternal(DruidPooledConnection.java:1107)
    at com.alibaba.druid.pool.DruidPooledConnection.checkState(DruidPooledConnection.java:1100)
    at com.alibaba.druid.pool.DruidPooledConnection.getMetaData(DruidPooledConnection.java:832)
    at org.springframework.jdbc.support.JdbcUtils.extractDatabaseMetaData(JdbcUtils.java:294)
    ... 117 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 21,305 milliseconds ago.  The last packet sent successfully to the server was 21,301 milliseconds ago.
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at com.mysql.jdbc.Util.handleNewInstance(Util.java:400)
    at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1038)
    at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3434)
    at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3334)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3774)
    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2447)
    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2594)
    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)
    at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1901)
    at co

**Comment by kop-still** [comment]
应该是有连接泄漏

**Comment by wuyongwen** [comment]
我们也碰到了这种情况,应该是druid中的datasource配置有问题

**Comment by taoyangxu** [comment]
求问大佬，这个问题解决了么

**Comment by wubiliang** [comment]
不是说的很清楚了吗？
Communications link failure

The last packet successfully received from the server was 21,305 milliseconds ago. The last packet sent successfully to the server was 21,301 milliseconds ago.

看看MySQL是不是挂了，另外看看网络情况

**Comment by lizongbo** [comment]
请使用最新版本验证
