### ISSUE TITLE
druid1.0.15 ，mysql，delete from tableName where id =1，如果把where关键字写错了，如写成delete from tableName wher id =1，会导致整个表的数据被删除。期望：解析器报语法错误

### ISSUE THREAD

**Issue by abirdman** [alibaba/druid#974]

**Comment by lizongbo** [comment]
经过druid 1.2.20 版本验证，已经正常报语法错误。

```

@Test
    public void test_whereis() throws Exception {
        for (DbType dbType : new DbType[]{DbType.mysql}) {
            String sql = "delete from tableName wher userid =1";
            SQLStatementParser parser = SQLParserUtils.createSQLStatementParser(sql, dbType);
            SQLStatement statement = parser.parseStatement();
            System.out.println("原始的sql===" + sql);
            String parameterizedSql = ParameterizedOutputVisitorUtils.parameterize(sql, dbType).replace("\n", " ").replace('\'', '"');
            System.out.println("归一化sql===" + parameterizedSql);
            SchemaStatVisitor visitor = SQLUtils.createSchemaStatVisitor(dbType);
            statement.accept(visitor);
            System.out.println("getTables==" + visitor.getTables());
            Map<TableStat.Name, TableStat> tableMap = visitor.getTables();
            assertFalse(tableMap.isEmpty());
        }
    }

```

运行结果：

```
com.alibaba.druid.sql.parser.ParserException: syntax error. pos 33, line 1, column 28, token IDENTIFIER userid

	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseDeleteStatement(MySqlStatementParser.java:234)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseDeleteStatement(MySqlStatementParser.java:42)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:4838)

```
